SootopolisCity_House5_MapScripts:: @ 8226E93
	.byte 0

SootopolisCity_House5_EventScript_Maniac:: @ 8226E94
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl:: @ 8226E9D
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection: @ 8226EA6
	.string "이 루네시티와 송화산은\n"
	.string "뭔가 관계가 있는 것 같아...\p"
	.string "옛날 연구소에 있을 때 친구와\n"
	.string "그런 걸 조사했었거든$"

SootopolisCity_House5_Text_BrotherUsedToStudySea: @ 8226F35
	.string "오빠는 옛날에\n"
	.string "바다를 연구하고 있었어$"

