SootopolisCity_House5_MapScripts:: @ 8226E93
	.byte 0

SootopolisCity_House5_EventScript_Maniac:: @ 8226E94
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl:: @ 8226E9D
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection: @ 8226EA6
	.string "이 루네시티와 송화산은\n"
	.string "뭔가의 관계가 있는 것 같아...\p"
	.string "옛날에 있던 연구소에서\n"
	.string "친구와 그런 걸 조사했었거든$"
	// この ルネシティと おくりびやまはｎ
	// なにかの かんけいが あるらしい……ｐ
	// むかし いた けんきゅうじょでｎ
	// そんなことを ともだちと しらべていたよ

SootopolisCity_House5_Text_BrotherUsedToStudySea: @ 8226F35
	.string "오빠는\n"
	.string "고대의 바다를 연구했었어$"
	// おにいちゃんｎ
	// むかし うみの けんきゅうを してたんだ

