RustboroCity_House2_MapScripts:: @ 8215EB3
	.byte 0

RustboroCity_House2_EventScript_PokefanF:: @ 8215EB4
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl:: @ 8215EBD
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent: @ 8215EC6
	.string "트레이너스쿨은 참 좋아!\p"
	.string "거기서 포켓몬을 공부하면\n"
	.string "체육관 관장도 될 수 있다니까?!$"

RustboroCity_House2_Text_RoxanneKnowsALot: @ 8215F21
	.string "체육관 관장인 원규 언니는\n"
	.string "포켓몬을 정말 많이 알고\l"
	.string "포켓몬 배틀에도 엄청 강해$"

