gText_ApprenticeChallenge0:: @ 82B6EA5
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자입니다!\n"
	.string "훌쩍... 긴장되네$"
	@ §いさんの §うばん でしです!ｎ
	@ グスン…… きんちょう するなあ

gText_ApprenticeChallenge1:: @ 82B6EEC
	.string "나 {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자야! 간다-!$"
	@ ぼく §いさんのｎ
	@ §うばんの でし なんだ! いくぞ-!

gText_ApprenticeChallenge2:: @ 82B6F16
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자입니다!\n"
	.string "자 승부하죠!$"
	@ §いさんの §うばんの でしだ!ｎ
	@ いざ しょうぶ!

gText_ApprenticeChallenge3:: @ 82B6F4C
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자입니다...\n"
	.string "저 따위가 이길 수 있을까요...?$"
	@ §いさんの §うばんでしです…ｎ
	@ あたし なんかが かてる かな……?

gText_ApprenticeChallenge4:: @ 82B6F92
	.string "{STR_VAR_1}의 {STR_VAR_2}번째 제자야!\n"
	.string "승부해 줄게!$"
	@ §いの §うばん でしなの!ｎ
	@ しょうぶ して あげるわ!

gText_ApprenticeChallenge5:: @ 82B6FC9
	.string "전 바쁘면서도 {STR_VAR_1}의\n"
	.string "{STR_VAR_2}번째 제자를 하고 있습니다!$"
	@ いそがしい なか §いさんのｎ
	@ §うばんの でし やってる オレです!

gText_ApprenticeChallenge6:: @ 82B700C
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째\n"
	.string "제자 트레이너야 잘 부탁해!$"
	@ §いさんの §うばんのｎ
	@ でしトレ-ナ-よ よっろしくぅ!

gText_ApprenticeChallenge7:: @ 82B703A
	.string "전 {STR_VAR_1}님의 {STR_VAR_2}번째\n"
	.string "제자랍니다... 그럼 갈게요$"
	@ わたくし §いさまの §うばんのｎ
	@ でしで ございますの…… いきますわよ

gText_ApprenticeChallenge8:: @ 82B706A
	.string "꺄-! {STR_VAR_1} 선생님의\n"
	.string "{STR_VAR_2}번째 제자예요! 힘낼게요!$"
	@ キャ-! §いせんせいのｎ
	@ §うばん でし ですっ! がんばります!

gText_ApprenticeChallenge9:: @ 82B709C
	.string "예-이! {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자인 아저씨와 승부하자!$"
	@ いえ-い! §いさんのｎ
	@ §うばん でしの おじさんと しょうぶ!

gText_ApprenticeChallenge10:: @ 82B70CC
	.string "{STR_VAR_1}의 1000번째 제자야!\n"
	.string "거짓말이고 사실 {STR_VAR_2}번째지롱! 간다!$"
	@ §いの 1000ばんめの でしだ!ｎ
	@ うそ ほんとは §うばん! いくぞ!

gText_ApprenticeChallenge11:: @ 82B710A
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째\n"
	.string "제자다! 들썩들썩하게 가자고-!$"
	@ §いさんの §うばんのｎ
	@ でしだぜ! ノリノリで いってみようぜ-!

gText_ApprenticeChallenge12:: @ 82B714D
	.string "이야호! {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자는 날 말하는 거라고!$"
	@ イヤハァ! §いさんのｎ
	@ §うばんの でしとは オレのことっ!

gText_ApprenticeChallenge13:: @ 82B7185
	.string "...콜록 콜록 잘 부탁해!\n"
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자야!$"
	@ ……ゴホっ ゴホっ よろしく!ｎ
	@ §いさんの §うばんでしだ!

gText_ApprenticeChallenge14:: @ 82B71C1
	.string "부 부끄럽지만 {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자입니다...!$"
	@ て てれますが §いさんのｎ
	@ §うばんの でし やってます……!

gText_ApprenticeChallenge15:: @ 82B71F9
	.string "거짓말이 아냐! 난\n"
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자다$"
	@ うそじゃない! わたしはｎ
	@ §いさんの §うばんの でしだ

gText_ApprenticePleaseTeach0:: @ 82B7229
	.string "호 혹시 {PLAYER}님...?\n"
	.string "아아! 훌쩍...\p"
	.string "아... 죄송합니다!\n"
	.string "긴장해서 눈물이 나와버렸어요...\p"
	.string "저는 {STR_VAR_1}{K_I}라고 하고\n"
	.string "{PLAYER}님을 동경하고 있습니다!\l"
	.string "어 언젠가 {PLAYER}님을 만나서\l"
	.string "포켓몬에 대해 배우고 싶다고\l"
	.string "꿈꿔왔었어요...! 으흑...\p"
	.string "저기 저기 {PLAYER}님!\n"
	.string "괜찮다면... 포켓몬에 대해\l"
	.string "알려주세요!$"
	@ も もしかして §あさん……?ｌ
	@ ああ! グスっ……ｐ
	@ あ…… ごめんなさい!ｎ
	@ きんちょう して なみだが でちゃった……ｐ
	@ ぼくは §い って いってｎ
	@ §あさんに あこがれて います!ｌ
	@ い いつか §あさんに あってｌ
	@ ポケモンのこと おしえて もらう ってｌ
	@ ゆめ みて いたんです……! うう……ｐ
	@ あのう あのう §あさん!ｎ
	@ できたら…… ポケモンのことｌ
	@ おしえて ください!

gText_ApprenticeRejectTeaching0:: @ 82B731C
	.string "그... 그럴 수가...\n"
	.string "으 으흑 으아앙-!\p"
	.string "부탁이에요... 부탁이니까 제발...!$"
	@ そ そんな……ｎ
	@ う うう うわ-ん!ｐ
	@ おねがいです…… おねがい ですから……!

gText_ApprenticeWhichLevelMode0:: @ 82B735B
	.string "앗- 정말인가요!?\n"
	.string "해냈다! 너무 기뻐! 으헝헝-!\p"
	.string "아... 죄송합니다\n"
	.string "기뻐서 눈물이...\p"
	.string "저기 그럼 가르쳐주세요!\n"
	.string "배틀타워의 방 말인데\l"
	.string "레벨 50과 오픈 레벨의 방 중\l"
	.string "어느 쪽이 저한테 잘 맞을까요...?$"
	@ え- ほんとですか!ｎ
	@ やった! うれしいよう! うぉぉ-ん!ｐ
	@ あ…… ごめん なさいｎ
	@ うれしくて なみだが……ｐ
	@ あのう じゃあ おしえて ください!ｎ
	@ バトルタワ-の へや なんですけどｌ
	@ レベル50と オ-プンレベルの へやｌ
	@ ぼく だったら どっちが いいのかな……?

gText_ApprenticeLevelModeThanks0:: @ 82B7423
	.string "{STR_VAR_1}이군요? 으흑 으헝헝-!\p"
	.string "아! 죄송합니다\n"
	.string "{PLAYER}님이 제게 방을\l"
	.string "추천해주신 게 기뻐서 눈물이...\p"
	.string "...훌쩍\n"
	.string "정말 감사합니다!\l"
	.string "다음에도 얘기해주세요!$"
	@ §い ですね! うぅ うわ-ん!ｐ
	@ あ! ごめんなさいｎ
	@ §あさんが ぼくに へやをｌ
	@ きめてくれた うれしさで なみだが……ｐ
	@ ……グスンｎ
	@ ありがとう ございました!ｌ
	@ また おはなし してください!

gText_ApprenticePleaseTeach1:: @ 82B74C1
	.string "우와-! {PLAYER}님 맞지?\n"
	.string "엄청 강한 사람 맞지?\p"
	.string "난 {STR_VAR_1}!\n"
	.string "이제 막 트레이너가 됐어\p"
	.string "저기 부탁이야 {PLAYER}님!\n"
	.string "내 선생님이 돼서\l"
	.string "트레이너에 대해 잔뜩 알려주라!$"
	@ うわ-! §あさん だよね?ｎ
	@ すごく つよい ひと なんだよね?ｐ
	@ ボク §い!ｎ
	@ トレ-ナ-に なった ばかり なんだｐ
	@ ねえ おねがい §あさん!ｎ
	@ ぼくの せんせいに なってｌ
	@ トレ-ナ-のこと いっぱい おしえてよ!

gText_ApprenticeRejectTeaching1:: @ 82B756F
	.string "에- 왜?\n"
	.string "저기- 알려줘도 괜찮잖아\l"
	.string "선생님이 되어주라 부탁이야!$"
	@ え-? どうして?ｎ
	@ ね-っ いいでしょ いいでしょｌ
	@ せんせいに なってよ おねがい!

gText_ApprenticeWhichLevelMode1:: @ 82B75B2
	.string "와아 해냈다!\n"
	.string "그럼 있지- 처음으로 물어볼 건\l"
	.string "배틀타워에 대해서야!\p"
	.string "레벨 50과 오픈 레벨의 방 중\n"
	.string "어느 쪽이 나한테 잘 맞을까?$"
	@ わ-い やった!ｎ
	@ じゃあね- はじめに ききたい ことはねｌ
	@ バトルタワ-の こと!ｐ
	@ レベル50と オ-プンレベルの へやｎ
	@ どっちが ボクに ピッタリ かなあ?

gText_ApprenticeLevelModeThanks1:: @ 82B763F
	.string "{STR_VAR_1}이구나! 역시 그렇지-?\n"
	.string "그럼 나 열심히 해볼게!\p"
	.string "다음에 또 여기서 만나면\n"
	.string "뭔가 알려줘 선생님!$"
	@ §いか! そ-だよね!ｎ
	@ じゃあ ボク がんばるね!ｐ
	@ また こんど ここで あったらｎ
	@ なにか おしえてね せんせい!

gText_ApprenticePleaseTeach2:: @ 82B76AC
	.string "저기... {PLAYER}님이신가요!?\n"
	.string "전 {STR_VAR_1}{K_I}라고 합니다!\p"
	.string "저 포켓몬 트레이너가 되고 싶은데\n"
	.string "어떡하면 좋을지 모르겠어서요...\p"
	.string "그래서 유명한 {PLAYER}님께\n"
	.string "어떡하면 좋을지 여쭤봐야겠다고\l"
	.string "생각이 들었습니다!\p"
	.string "상담해주실 수 있나요?$"
	@ あの…… §あさん ですか!?ｎ
	@ ぼく §い って いいます!ｐ
	@ ぼく ポケモントレ-ナ-に なりたいんだけどｎ
	@ どうすれば いいのか わからなくて……ｐ
	@ それで ゆうめいな §あさんにｎ
	@ どうすれば いいのか きいてみようとｌ
	@ おもったんです!ｐ
	@ そうだんに のって もらえますか?

gText_ApprenticeRejectTeaching2:: @ 82B7772
	.string "그럴 수가!\n"
	.string "저 무슨 수를 써서라도 포켓몬 트레이너가\l"
	.string "되고 싶어요!\p"
	.string "질문에 대답해주실 수 있나요?$"
	@ そんなあ!ｎ
	@ ぼく どうしても ポケモントレ-ナ-にｌ
	@ なりたいんです!ｐ
	@ しつもんに こたえて もらえますか?

gText_ApprenticeWhichLevelMode2:: @ 82B77CE
	.string "감사합니다!\n"
	.string "그럼 바로 첫 번째 질문을 할게요!\p"
	.string "배틀타워엔 레벨 50과 오픈이라는\n"
	.string "두 개의 레벨이 있잖아요?\p"
	.string "어느 레벨이\n"
	.string "저한테 잘 맞을 거라고 생각하세요?$"
	@ ありがとう ございます!ｎ
	@ じゃあ さっそく さいしょの しつもん!ｐ
	@ バトルタワ-って レベル50と オ-プンとｎ
	@ ふたつの レベルが ありますよね!ｐ
	@ どっちの レベルがｎ
	@ ぼくに あってると おもいますか?

gText_ApprenticeLevelModeThanks2:: @ 82B7871
	.string "{STR_VAR_1}이군요! 알겠습니다!\n"
	.string "그럼 또 질문이 있으면\l"
	.string "여기에 올 테니 가르쳐주세요!$"
	@ §い ですね! わかりました!ｎ
	@ じゃあ また しつもんが あったらｌ
	@ ここに くるので おしえて ください!

gText_ApprenticePleaseTeach3:: @ 82B78D4
	.string "어라? 에? 당신은...!\n"
	.string "아니 그럴 리가 없어\l"
	.string "나 따위가 {PLAYER}님을\l"
	.string "만날 수 있을 리 없는걸\p"
	.string "...정말로 {PLAYER}님이신가요?\n"
	.string "이렇게 대화할 수 있다니 안 믿겨요!\l"
	.string "아아 이렇게나 좋은 일이 생겼으니\l"
	.string "나중에 분명 나쁜 일만 일어나겠네\p"
	.string "...아 죄송합니다\n"
	.string "저는... {STR_VAR_1}{K_I}라고 해요\l"
	.string "장점은 아무것도 없습니다\l"
	.string "...라면서 자기소개를 해도\l"
	.string "어차피 금방 잊어버리겠죠...\p"
	.string "{PLAYER}님을 만나면\n"
	.string "트레이너로서 상담해 달라고\l"
	.string "부탁할 생각이었는데\l"
	.string "어차피 안 되겠죠?\p"
	.string "...아니면 설마\n"
	.string "상담해주실 수 있는 건가요?$"
	@ あれ? え? あなたは……!ｎ
	@ いえ そんなはず ないわｌ
	@ あたし なんかが §あさんにｌ
	@ あえるはず なんて ないもんｐ
	@ ……ほんとに §あさん なの?ｎ
	@ しんじられない おはなし できるなんて!ｌ
	@ ああ こんな いいことが あったらｌ
	@ あとは わるいこと ばっかり おきるんだわｐ
	@ ……あ ごめんなさいｎ
	@ あたし…… §い です……ｌ
	@ なんの とりえも ありませんｌ
	@ って じこしょうかい なんて してもｌ
	@ どうせ すぐ わすれちゃいます よね……ｐ
	@ §あさんに あえたらｎ
	@ トレ-ナ-として そうだんに のって ってｌ
	@ おねがい しようと おもっていたけどｌ
	@ どうせ ムリですよね?ｐ
	@ ……それとも もしかしてｎ
	@ そうだんに のって もらえたり しますか?

gText_ApprenticeRejectTeaching3:: @ 82B7B1A
	.string "역시... 그렇겠죠\n"
	.string "저 따위는 정말로\l"
	.string "재미없는 여자애에 불과하니까요...\p"
	.string "그래도 혹시 몰라 여쭤보는데...\n"
	.string "다시 생각해주실 수는 없는 거죠?\p"
	.string "그치만 역시나 포기하기 싫단 말이에요\n"
	.string "아직 운이 좋을 때 부탁드립니다!\l"
	.string "...상담해주시면 안 될까요?$"
	@ やっぱり…… そうですよねｎ
	@ あたし なんて ほんとにｌ
	@ つまらない おんなのこで……ｐ
	@ でも もしかしたら って おもって……ｎ
	@ かんがえなおして なんて くれませんよね?ｐ
	@ けど やっぱり あきらめられないｎ
	@ うんが いい うちに おねがいしよう!ｌ
	@ ……そうだんに のって もらえますか?

gText_ApprenticeWhichLevelMode3:: @ 82B7C13
	.string "정말로요? 안 믿겨요!\n"
	.string "저 따위에게 상담을\l"
	.string "해주신다니 꿈 같아요!\l"
	.string "너무 기뻐요...\p"
	.string "정말 별것 아닌 얘기겠지만\n"
	.string "전 도저히 못 정하겠어서요\p"
	.string "배틀타워에선 레벨을\n"
	.string "레벨 50과 오픈 레벨\l"
	.string "둘 중 하나로 선택할 수 있잖아요...?\p"
	.string "저 따위라도 활약할 수 있는\n"
	.string "레벨은 어느 쪽 방인가요?$"
	@ ほんとう ですか? しんじられない!ｎ
	@ あたし なんかの そうだんにｌ
	@ のってもらえる なんて!ｌ
	@ うれしい です……ｐ
	@ ほんとうに くだらないです けどｎ
	@ あたし には きめられないん ですｐ
	@ バトルタワ-って レベルがｎ
	@ レベル50と オ-プンレベルとｌ
	@ ふたつ えらべる けど……ｐ
	@ あたし なんか でも がんばれそうなｎ
	@ レベルって どっちの へや でしょうか?

gText_ApprenticeLevelModeThanks3:: @ 82B7D18
	.string "{STR_VAR_1}이군요 알겠습니다!\n"
	.string "정말 이런 저라도\l"
	.string "잘할 수 있을까요?\l"
	.string "열심히 해볼게요 안 될지도 모르지만\p"
	.string "오늘 저 따위에게 시간 내주셔서\n"
	.string "정말 감사했습니다...!$"
	@ §い ですか わかりました!ｎ
	@ ほんとうに こんな あたしでもｌ
	@ だいじょうぶ でしょうかｌ
	@ がんばって みます ダメかも しれないけどｐ
	@ きょうは あたしなんかの ためにｎ
	@ ありがとう ございました……!

gText_ApprenticePleaseTeach4:: @ 82B7DD4
	.string "앗! {PLAYER} 맞지!?\n"
	.string "포켓몬 배틀을 아주 잘한다며!\p"
	.string "난 {STR_VAR_1}\n"
	.string "친구가 되어줄게!\p"
	.string "있지 트레이너스쿨에서\n"
	.string "배운 것만으로는\l"
	.string "배틀프런티어에서 이길 수 없더라구!\p"
	.string "상담해준다면 기쁘겠어\n"
	.string "당연히 OK겠지?$"
	@ あっ! §あ§お でしょ!?ｎ
	@ ポケモン つよいって きいてるよ!ｐ
	@ わたしは §いｎ
	@ おともだちに なって あげる!ｐ
	@ あのね トレ-ナ-ズスク-ル でｎ
	@ おそわった こと だけじゃｌ
	@ バトルフロンティア では かてないの!ｐ
	@ そうだんに のってくれても いいわよｎ
	@ もちろん オ-ケ- でしょ?

gText_ApprenticeRejectTeaching4:: @ 82B7EE5
	.string "에? 거절한다고?\n"
	.string "다른 사람도 아니고 내 부탁인데!\l"
	.string "다시 한 번 생각해봐!$"
	@ え? なんで ことわるの?ｎ
	@ あたしの おねがい なんだけど!ｌ
	@ かんがえなおしてよぉ!

gText_ApprenticeWhichLevelMode4:: @ 82B7F35
	.string "응 그럼 잘 부탁해\n"
	.string "바로 정해줬으면 하는 게 있어\p"
	.string "배틀타워엔\n"
	.string "레벨 50과 오픈 레벨의 방이 있잖아?\p"
	.string "{PLAYER}{K_EUNNEUN} 나한테\n"
	.string "어느 쪽이 좋을 것 같아?$"
	@ うん じゃあ おねがいねｎ
	@ さっそく きめて ほしいことが あるからｐ
	@ レベル50と オ-プンレベルの へやがｎ
	@ バトルタワ-に あるじゃない?ｌ
	@ §あ§おは わたしにはｌ
	@ どっちが いいと おもう?

gText_ApprenticeLevelModeThanks4:: @ 82B7FE8
	.string "그래? {STR_VAR_1}이\n"
	.string "나한테 어울리는구나 고마워!\l"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ そう §いがｎ
	@ わたしに ふさわしいのね ありがと!ｌ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticePleaseTeach5:: @ 82B8087
	.string "오오 너! {PLAYER}{K_I}구나!\n"
	.string "유명하니까 알고 있다고\l"
	.string "난 {STR_VAR_1}{K_I}야 잘 부탁해!\p"
	.string "난 트라이애슬리트를 하고 있는데\n"
	.string "몸도 단련하고\l"
	.string "포켓몬도 키우고\l"
	.string "아르바이트에 사교댄스까지...\p"
	.string "너무 바쁘게 살다 보니까\n"
	.string "좀처럼 좋은 트레이너가 되기 힘들더라고!\p"
	.string "그래서 부탁할 게 있어!\p"
	.string "여기서 만난 것도 무언가의 인연일 테니까!\n"
	.string "{PLAYER} 너 가끔씩 나한테\l"
	.string "어드바이스 좀 해주지 않을래?$"
	@ ああ きみ! §あ§お!ｎ
	@ ゆうめい だから しってるぜｌ
	@ オレは §い よろしく!ｐ
	@ オレは トライアスリ-ト やっててｎ
	@ からだを きたえる かたわらｌ
	@ ポケモンも そだてて ほかにもｌ
	@ バイトに ひるねに しゃこうダンス……ｐ
	@ いそがしくて なっかなかｎ
	@ いい トレ-ナ-に なれないんだよね!ｐ
	@ そこで おねがい!ｐ
	@ ここで あえたのも なにかの ごえん!ｎ
	@ §あ§お たまに オレにｌ
	@ アドバイスを おねがい できないかな?

gText_ApprenticeRejectTeaching5:: @ 82B822B
	.string "에-! 부탁 좀 할게!\n"
	.string "나한텐 {PLAYER} 같은 사람이\l"
	.string "필요하단 말이야-!\p"
	.string "나한테 어드바이스 해주라!$"
	@ え-! たのむよ!ｎ
	@ §あ§お みたいな ひとがｌ
	@ オレには ひつよう なんだよ-!ｐ
	@ オレに アドバイス たのむよ!

gText_ApprenticeWhichLevelMode5:: @ 82B8286
	.string "땡큐! 그렇게 나와야지!\n"
	.string "그럼 먼저 가벼운 질문 하나!\p"
	.string "저기 있지 배틀타워엔\n"
	.string "레벨이 2종류 있잖아?\l"
	.string "레벨 50과 오픈 레벨!\p"
	.string "바쁜 내게는\n"
	.string "어느 쪽이 어울릴 것 같아?$"
	@ サンキュ- そう こなくっちゃ!ｎ
	@ んじゃ てはじめに かるいのを 1つね!ｐ
	@ あのさ バトルタワ- ってｎ
	@ レベルが 2しゅるい あるじゃん?ｌ
	@ レベル50と オ-プンレベル!ｐ
	@ いそがしい オレ だったらｎ
	@ どっちで がんばれば いいかな?

gText_ApprenticeLevelModeThanks5:: @ 82B8356
	.string "{STR_VAR_1}이구나! 오케이-!\n"
	.string "어떻게든 시간을 내서 해볼게!\p"
	.string "...어이쿠 아르바이트 갈 시간이다!\n"
	.string "그럼 땡큐- 또 보자!$"
	@ §い ね! オ-ケ-!ｎ
	@ なんとか じかん つくって やってみるぜ!ｐ
	@ ……っと いけね バイトのじかんだ!ｎ
	@ じゃあ サンキュ- またな!

gText_ApprenticePleaseTeach6:: @ 82B83CE
	.string "말도 안 돼 설마\n"
	.string "진짜로 {PLAYER}님이야?\p"
	.string "와 굉장하다-!\n"
	.string "나 {STR_VAR_1}{K_I}야 잘 부탁해!\p"
	.string "{PLAYER}님 말야\n"
	.string "엄청 강하지?\l"
	.string "다들 그러더라구!\p"
	.string "아! 좋은 생각이 났어\n"
	.string "나 {PLAYER}님한테\l"
	.string "어드바이스 받을래!\l"
	.string "분명 강해질 수 있을 거야!\p"
	.string "저기 어때 괜찮지?\n"
	.string "나한테 어드바이스 좀 부탁할게!$"
	@ うっそ もしかしてｎ
	@ ほんものの §あさん?ｐ
	@ あっは! すご-い!ｎ
	@ わたし §いよ よろしくぅ!ｐ
	@ §あさん って なんかｎ
	@ とっても つよいんでしょｌ
	@ みんな うわさ してるもんね!ｐ
	@ あ! いいこと かんがえちゃったｎ
	@ わたし §あさんにｌ
	@ アドバイスを もらおうっと!ｌ
	@ きっと つよく なれそう!ｐ
	@ ねっ いいでしょ?ｎ
	@ わたしに アドバイス おねがい!

gText_ApprenticeRejectTeaching6:: @ 82B84FC
	.string "아하하하! 그렇게 짓궂게 말해도\n"
	.string "나한텐 안 통하거든!\l"
	.string "사실은 OK하고 싶지?$"
	@ あははは! そんな いじわる いってもｎ
	@ あたし には つうじないわよん!ｌ
	@ ほんとは オ-ケ- なんでしょ?

gText_ApprenticeWhichLevelMode6:: @ 82B8559
	.string "야호! 역시 {PLAYER}님이야!\n"
	.string "마음이 넓다니까-!\l"
	.string "먼저 뭐부터 물어볼까-?\l"
	.string "...앗 그래 생각났어!\p"
	.string "엣헴 그럼 질문입니다!\n"
	.string "내가 배틀타워에 도전한다면!\l"
	.string "레벨 50의 방! 오픈 레벨의 방!\l"
	.string "둘 중 어느 쪽이 어울릴까-요?$"
	@ わ-い さっすが §あさん!ｎ
	@ ココロひろ-い!ｌ
	@ まずは なにから きこうかな-?ｌ
	@ ……あっ おもいついた!ｐ
	@ ジャ-ン しつもんです!ｎ
	@ わたしが バトルタワ-に いどむなら!ｌ
	@ レベル50のへや! オ-プンレベルのへや!ｌ
	@ さて どっちが にあっている でしょう?

gText_ApprenticeLevelModeThanks6:: @ 82B8656
	.string "허허허-!\n"
	.string "{STR_VAR_1}이라고요!\l"
	.string "깔끔한 대답 고마워!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ ほほぉ-!ｎ
	@ §い と きましたか!ｌ
	@ シブイ おこたえ ありがとう!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticePleaseTeach7:: @ 82B86EA
	.string "혹시 당신은\n"
	.string "{PLAYER}님 맞으신가요?\p"
	.string "만나 뵙게 되어 참으로 기쁩니다\n"
	.string "전 {STR_VAR_1}{K_I}라고 해요\l"
	.string "{PLAYER}님을 이전부터\l"
	.string "동경하고 있었습니다...\p"
	.string "...... ...... ......\p"
	.string "저기... 이런 부탁이\n"
	.string "굉장히 실례가 될지도 모릅니다만...\p"
	.string "저를 {PLAYER}님의\n"
	.string "제자로 받아 주실 수 있으신지요?$"
	@ もし §あさんでｎ
	@ いらっしゃいますか?ｐ
	@ おめに かかれて うれしゅうございますｎ
	@ わたくし §いと もうしますのｌ
	@ §あさんに かねてよりｌ
	@ あこがれて おりました……ｐ
	@ …… …… ……ｐ
	@ あの…… こんな おねがいｎ
	@ おこまりに なるかも しれませんが…ｐ
	@ わたくしを §あさんにｎ
	@ でしいり させて いただけません?

gText_ApprenticeRejectTeaching7:: @ 82B87DA
	.string "어머...!\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\p"
	.string "...아 충격으로 정신을 잃을 뻔했네요\n"
	.string "그럴 리 없죠! 분명 잘못 들은 걸 거예요\p"
	.string "부탁이에요! 저를\n"
	.string "제자로 삼아 주세요!$"
	@ まあ……!ｐ
	@ …… …… ……ｎ
	@ …… …… ……ｐ
	@ ……あ ショックで きを うしないましたわｎ
	@ いいえ! きっと ききまちがい ですわｐ
	@ おねがい! わたくしをｎ
	@ でしに して くださると おっしゃって!

gText_ApprenticeWhichLevelMode7:: @ 82B887C
	.string "저 정말 기뻐요...!\p"
	.string "그럼 바로 저와\n"
	.string "상담해 주세요!\p"
	.string "저 한번 배틀타워에\n"
	.string "도전해보려고 생각 중이거든요\l"
	.string "다만 레벨이 두 개 있잖아요...\p"
	.string "저는 레벨 50과 오픈 레벨 중\n"
	.string "어디에 어울리는 것 같으신가요?$"
	@ うっ うれしい ですわ……!ｐ
	@ では さっそくですけど わたくしのｎ
	@ そうだんを きいて くださいませ!ｐ
	@ わたくし いちど バトルタワ-にｎ
	@ ちょうせん しようと おもっていますのｌ
	@ ただ レベルが ふたつ ありまして……ｐ
	@ わたくしは レベル50と オ-プンレベルｎ
	@ どちらに ふさわしいと おもわれますか?

gText_ApprenticeLevelModeThanks7:: @ 82B8957
	.string "{STR_VAR_1}이군요!\n"
	.string "알겠습니다 열심히 할게요!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "안녕히 계세요!$"
	@ §い ですのね!ｎ
	@ わかりました がんばりますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticePleaseTeach8:: @ 82B89C6
	.string "꺄-! 꺄-!!!\n"
	.string "{PLAYER}님이 말 걸어줬어!\l"
	.string "가 감격이야...!\p"
	.string "저! {STR_VAR_1}{K_I}라고 해요!\n"
	.string "트레이너가 된 지 얼마 안 돼서\l"
	.string "포켓몬계의 거물인 {PLAYER}님과\l"
	.string "대화할 수 있어서 감동이에요!\p"
	.string "마마마마 맞다!\n"
	.string "{PLAYER}님 부탁이 있어요!\l"
	.string "저를 제자로 받아주세요!\l"
	.string "여러 가지 배우고 싶어요!$"
	@ キャ-! キャ-!!!ｎ
	@ §あさんに はなしかけられた!ｌ
	@ かっ かんげきっ……!ｐ
	@ わたし! §いと いいますっ!ｎ
	@ トレ-ナ-に なって すぐにｌ
	@ ポケモンかいの おおもの §あさんとｌ
	@ おはなし できて かんどう してますっ!ｐ
	@ そそそそ そうだ!ｎ
	@ §あさん おねがいが!ｌ
	@ わたしを でしに して くださいっ!ｌ
	@ いろいろ おしえて ほしいのですっ!

gText_ApprenticeRejectTeaching8:: @ 82B8ACF
	.string "우와아아!!\n"
	.string "{PLAYER}님께 거절당했다...\l"
	.string "귀 귀중한 경험이야!\p"
	.string "{PLAYER}님! 이번엔\n"
	.string "좋은 대답을 들려주세요!\p"
	.string "제게 지도를 부탁드립니다!$"
	@ うっわああ!!ｎ
	@ §あさんに ことわられた……ｌ
	@ きっ きちょうな けいけん だわっ!ｐ
	@ §あさんっ! こんどはｎ
	@ よい おへんじも きかせて くださいっ!ｌ
	@ わたしに ごしどうを おねがいしますっ!

gText_ApprenticeWhichLevelMode8:: @ 82B8B66
	.string "히에에에에에! {PLAYER}님이\n"
	.string "예 라고 말씀하셨어어어!!\l"
	.string "오늘은 이제 잠 다 잤다...\l"
	.string "정말로 감사드립니다!\p"
	.string "그럼 여쭤보도록 할게요!\n"
	.string "저는 배틀타워\l"
	.string "레벨 50의 방과 오픈 레벨의 방 중\l"
	.string "어느 쪽에 어울린다고 생각하시나요?$"
	@ ひええええぇ! §あさんにｎ
	@ はい って いわれたああぁ!!ｌ
	@ きょうは もう ねむれない……ｌ
	@ おありがとう ございますう!ｐ
	@ ではっ うかがいます!ｎ
	@ わたしは バトルタワ-ｌ
	@ レベル50のへやと オ-プンレベルのへやｌ
	@ どちらに むいてると おもわれますかっ?

gText_ApprenticeLevelModeThanks8:: @ 82B8C20
	.string "{STR_VAR_1}이군요! 알겠습니다\n"
	.string "가슴에 새길게요!\l"
	.string "저 감격했어요!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 가르쳐 주세요!$"
	@ §い りょうかいですっｎ
	@ りょうかいで ありますっ!ｌ
	@ わたし かんげき です!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticePleaseTeach9:: @ 82B8CAA
	.string "와우! 너는\n"
	.string "설마 설마 {PLAYER}!?\l"
	.string "스트롱하고 페이머스한 트레이너!\l"
	.string "이야 아저씨는 럭키한걸-!\p"
	.string "헬로 아저씨는 {STR_VAR_1}{K_I}야!\n"
	.string "포켓몬 티처를 찾고 있지\l"
	.string "그런 때에 굿 타이밍!\l"
	.string "때마침 {PLAYER} 네가 나타났어!\p"
	.string "그렇게 됐으니 {PLAYER}!\n"
	.string "아저씨를 제자로 삼아줘!$"
	@ ワォ! きみはｎ
	@ もしや もしや §あ§お!ｌ
	@ ストロングで フェイマスな トレ-ナ-!ｌ
	@ いや おじさん ラッキ-だな-!ｐ
	@ ハロウ おじさんは §いね!ｎ
	@ ポケモン ティ-チャ- さがしてるんだｌ
	@ そんな ときに グッドタイミングでｌ
	@ §あ§おが あらわれた!ｐ
	@ と いうわけで §あ§お!ｎ
	@ おじさんを でしいり させて くれ!

gText_ApprenticeRejectTeaching9:: @ 82B8DD3
	.string "크아악-!\n"
	.string "너도 제법 쿨하고 터프한걸...\l"
	.string "그런 말 하지 말고 제발!$"
	@ ぐわ-っ!ｎ
	@ きみも なかなか ク-ルで タフだね……ｌ
	@ そんなこと いわずに おねがいだよ!

gText_ApprenticeWhichLevelMode9:: @ 82B8E24
	.string "오우-! 감동이 확 밀려오는데!\n"
	.string "엑설런트!\p"
	.string "그럼 퍼스트 어드바이스 부탁해!\n"
	.string "배틀타워 말인데\l"
	.string "아저씨가 도전한다면 레벨은\l"
	.string "50과 오픈 중 어느 게 베터-?$"
	@ おぅ-! グッと くるね!ｎ
	@ エクセレント!ｐ
	@ では ファ-スト アドバイス たのむね!ｎ
	@ バトルタワ- なんだけどさｌ
	@ おじさんが やるなら レベルはｌ
	@ 50と オ-プン どっちが ベタ-かな?

gText_ApprenticeLevelModeThanks9:: @ 82B8ED5
	.string "아-하 {STR_VAR_1}이구나\n"
	.string "오-케이 오-케이!\l"
	.string "아저씨 팍팍 힘내고 올게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん バ-っと がんばって くるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticePleaseTeach10:: @ 82B8F45
	.string "저 저기 {PLAYER} 맞지!\n"
	.string "방금 경찰 아저씨가 찾고 있었다고!\p"
	.string "...... ...... ......\n"
	.string "농담이야 거짓말 거짓말!\p"
	.string "난 {STR_VAR_1}{K_I}라고 해\n"
	.string "이래 봬도 포켓몬 챔피언이라구!\l"
	.string "...라는 말도 거짓말이지롱!\p"
	.string "실은 나 포켓몬 승부를\n"
	.string "그다지 잘하지 않아서 말야!\l"
	.string "거기서 제안 하나!\l"
	.string "내 스승님이 되어주지 않을래?$"
	@ お おいっ §あ§おだろ!ｎ
	@ さっき おまわりさんが さがしてたぞ!ｐ
	@ …… …… ……ｎ
	@ なんてね うっそ うそ!ｐ
	@ おいらは §い って いうんだｎ
	@ こうみえても ポケモンチャンピオンさ!ｌ
	@ ……て いうのも ウソ!ｐ
	@ じつは おいら ポケモンしょうぶがｎ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろｌ
	@ おいらの ししょうに なってくれない かな?

gText_ApprenticeRejectTeaching10:: @ 82B905F
	.string "그렇게 차가운 말 하면\n"
	.string "이렇게 해주지!\p"
	.string "우에-엥 우에-엥 흐엥 헝 헝!\p"
	.string "농담이야 거짓울음이지롱!\p"
	.string "저기! 괜찮은 제안이잖아\n"
	.string "내 스승님이 되어주라!$"
	@ そんな つめたい こと いうとｎ
	@ こうだぞ!ｐ
	@ うえ-ん うえ-ん え-ん えん えんｐ
	@ なんてね うそなき!ｐ
	@ ね! いいだろｎ
	@ おいらの ししょうに なって おくれよ!

gText_ApprenticeWhichLevelMode10:: @ 82B910E
	.string "앗싸-!\n"
	.string "답례로 배를 사줄게!\p"
	.string "뭐 물론 농담이지만...\n"
	.string "스승님! 잘 부탁해!\p"
	.string "저기 있지 배틀타워에는\n"
	.string "레벨 50과 오픈 레벨이 있잖아!\p"
	.string "어디서 열심히 하면 좋을지\n"
	.string "고민 중이거든...\l"
	.string "스승님이 정해주면 안 될까?$"
	@ やった-!ｎ
	@ おれいに ふねを かって あげよう!ｐ
	@ なんて じょうだん だけど……ｎ
	@ ししょう! よろしく たのむぜ!ｐ
	@ あのさ バトルタワ-でｎ
	@ レベル50と オ-プンレベルと あるだろ!ｐ
	@ どっちで がんばれば いいかｎ
	@ まよってるんだよ……ｌ
	@ ししょうが きめて くれないかな?

gText_ApprenticeLevelModeThanks10:: @ 82B9204
	.string "그렇구나\n"
	.string "{STR_VAR_1}이 좋다고!\l"
	.string "그럼 그 반대쪽으로 가야지!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ ちがうほうに いこうっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticePleaseTeach11:: @ 82B929C
	.string "처-음-뵙-겠-습-니-다!\n"
	.string "네 처음 뵙겠습니다!\l"
	.string "전 시원한 선원 {STR_VAR_1}!\l"
	.string "당신도 자기소개 해보시죠!\p"
	.string "흠흠 이름은 {PLAYER}{K_I}군요!\n"
	.string "포켓몬을 엄청 좋아하는\l"
	.string "미묘한 나이의 청년이고!\p"
	.string "사실 당신은 오늘 제가 말을 건\n"
	.string "10번째 트레이너랍-니-다!\p"
	.string "이 만남을 기념하여\n"
	.string "부디 저를 제자로 받아주세요!$"
	@ は®じ®め®ま®し®て!ｎ
	@ は-い はじめまして!ｌ
	@ わし ノリノリ ふなのり §い!ｌ
	@ きみも じこしょうかい いってみようぜ!ｐ
	@ ふん ふん なまえは §あ§お!ｎ
	@ ポケモン だいすきでｌ
	@ びみょうな おとしごろね!ｐ
	@ じつは きみは わしが はなしかけたｎ
	@ ほんじつ 10にんめの トレ-ナ-で-す!ｐ
	@ この であいを きねんしてｎ
	@ ぜひとも わしを でしに してください!

gText_ApprenticeRejectTeaching11:: @ 82B9438
	.string "그럴 수가!\n"
	.string "시원하지 못한 선택 아닌가요!\p"
	.string "저기 괜찮잖아요\n"
	.string "부디 저를 제자로 받아주세요!$"
	@ そんな!ｎ
	@ ノリが わるいじゃ ないか!ｐ
	@ な いいじゃ ないかｎ
	@ ぜひとも わしを でしに してください!

gText_ApprenticeWhichLevelMode11:: @ 82B9488
	.string "요요! 시원한 선택!\n"
	.string "{PLAYER}님 잘 부탁드립니다!\p"
	.string "그럼 1번째 질문\n"
	.string "가볼까요!\l"
	.string "배틀타워에 관한 질문입니다!\p"
	.string "레벨 50의 방과 오픈 레벨의 방\n"
	.string "제가 간다면 어느 쪽이 좋을까요?$"
	@ ようよう! ノリが いいね!ｎ
	@ §あさん よろしく たのみますよ!ｐ
	@ それじゃあ 1つめの しつもんｎ
	@ いってみようぜ!ｌ
	@ バトルタワ-に かんする しつもんだ!ｐ
	@ レベル50のへやと オ-プンレベルのへやｎ
	@ わしが いくなら さあ どっち?

gText_ApprenticeLevelModeThanks11:: @ 82B9564
	.string "{STR_VAR_1}입니까-앗! 요요!\n"
	.string "그렇다면 시원하게 가보겠습니다!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで いってみるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticePleaseTeach12:: @ 82B95D8
	.string "히야호- {PLAYER}님 아냐-!?\n"
	.string "어떡하지 나? 말 걸어볼까!?\l"
	.string "앗 근데 이미 대화하고 있잖아!!\p"
	.string "앗 근데 {PLAYER}님 지쳐보이는데!?\n"
	.string "어쩔 수 없지- 자기소개 해볼까!?\p"
	.string "안녕 난 {STR_VAR_1}{K_I}야!\n"
	.string "포켓몬 기타리스트계의 1등성이지!\p"
	.string "앗 근데 듣고 있는 거지!?\n"
	.string "마침 부탁이나 좀 해볼까!?\p"
	.string "저기 {PLAYER}님!\n"
	.string "날 {PLAYER}님의 제자로 삼아줘!$"
	@ ヒャホ- §あさんじゃな-い!?ｎ
	@ どうする オレ? はなしかけてみる!?ｌ
	@ ってもう はなし してるよ!!ｐ
	@ って §あさん あきれてる!?ｎ
	@ しかたね- じこしょうかい してみる!?ｐ
	@ オスっ オレっ §い!ｎ
	@ ポケモン ギタリストかいの 1ばんぼしさ!ｐ
	@ って きいてる!? きいてる!!ｎ
	@ ついでに たのみごと してみる!?ｐ
	@ あの §あさん!ｎ
	@ オレを §あさんの でしに して!

gText_ApprenticeRejectTeaching12:: @ 82B9763
	.string "앗 거절당했잖아!?\n"
	.string "어쩔 수 없지- 한 번 더 부탁해볼까!?\p"
	.string "부탁이야 {PLAYER}님!\n"
	.string "날 제자로 받아줘어어!!$"
	@ って ことわられてる オレっ!?ｎ
	@ しかたね- もういちど たのんでみる!?ｐ
	@ おねがい だよ §あさん!ｎ
	@ オレを でしに してエェ!!

gText_ApprenticeWhichLevelMode12:: @ 82B97E5
	.string "앗싸 럭키- 엄청 기쁜걸!!\n"
	.string "바로 뭔가 상담해볼까!?\l"
	.string "더군다나 여긴 배틀타워니\l"
	.string "그것부터 물어볼까!?\p"
	.string "저기! 나 배틀타워에서\n"
	.string "어느 레벨로 가면 좋을까!?$"
	@ やったラッキ- うれし-よ オレ!!ｎ
	@ さっそく なんか そうだんしてみる!?ｌ
	@ しかも ここは バトルタワ- だからｌ
	@ そのへん から きいてみる!?ｐ
	@ あのさっ! バトルタワ-で オレｎ
	@ どっちの レベルが にあってる!?

gText_ApprenticeLevelModeThanks12:: @ 82B989A
	.string "{STR_VAR_1}이라고!\n"
	.string "그럼 바로 가볼게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!$"
	@ §いだって!ｎ
	@ じゃ そこ いってみるよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticePleaseTeach13:: @ 82B992D
	.string "아... 거기 너!\n"
	.string "잠깐 어깨 좀 주물러줄래?\p"
	.string "...아아 그래그래 거기야 거기\n"
	.string "후- 기분 좋은걸!\p"
	.string "난 {STR_VAR_1}{K_I}라고 해\n"
	.string "태권도를 하고 있는데\l"
	.string "몸이 왠지 좀 약해서 말야...\p"
	.string "포켓몬 승부도 해서\n"
	.string "더 단련하려고 생각 중이지\p"
	.string "너 포켓몬리그에서 우승한\n"
	.string "{PLAYER} 맞지?\l"
	.string "어때 가끔씩 나한테\l"
	.string "상담 좀 해줄 수 있을까?$"
	@ あ…… きみきみ!ｎ
	@ ちょっとさ かた もんでくれる?ｐ
	@ ……ああ そうそう そこそこｎ
	@ は- きもちいい!ｐ
	@ おれ §い って いうんだｎ
	@ カラテ やってるんだけどｌ
	@ いまいち からだが よわくてさ……ｐ
	@ ポケモンしょうぶも やってｎ
	@ きたえようと おもって いるんだよねｐ
	@ きみ ポケモンリ-グで かったｎ
	@ §あ§お だろう?ｌ
	@ どうかな たまに おれのｌ
	@ そうだんに のって もらえない かい?

gText_ApprenticeRejectTeaching13:: @ 82B9A84
	.string "에- 왜!\p"
	.string "그렇게 폐 안 끼칠 테니까\n"
	.string "부탁 좀 할게!$"
	@ え- なんで!ｐ
	@ そんなに めんどうは かけないからさｎ
	@ おねがいだよ!

gText_ApprenticeWhichLevelMode13:: @ 82B9AB9
	.string "고맙고 미안\n"
	.string "...콜록 콜록!\p"
	.string "으으 빨리 단련해야겠어...\n"
	.string "바로 배틀타워에 갈 거라서\l"
	.string "레벨 50의 방과 오픈 레벨의 방 중\l"
	.string "어디가 좋을지 정해줄래?$"
	@ ありがとう わるいねｎ
	@ ……ゴホ ゴホっ!ｐ
	@ うう はやく きたえなきゃ……ｎ
	@ すぐに バトルタワ-に いくからｌ
	@ レベル50のへや オ-プンレベルのへやｌ
	@ どっちが いいか きめてくれるかい?

gText_ApprenticeLevelModeThanks13:: @ 82B9B76
	.string "응 알았어 {STR_VAR_1}이구나!\n"
	.string "그럼 바로 갔다 올게!\p"
	.string "앞으로도 나를 잘 부탁해!\n"
	.string "이젠 제자니까 말이지!$"
	@ ん わかった §いな!ｎ
	@ じゃあ さっそく いってくる!ｐ
	@ これからも おれを よろしく たのむよ!ｎ
	@ もう でしいり したんだからな!

gText_ApprenticePleaseTeach14:: @ 82B9BF2
	.string "아... 아...\n"
	.string "{PLAYER} 맞지...?\l"
	.string "그 그렇게 보지 말아주게!\l"
	.string "부끄럽단 말일세\p"
	.string "난 {STR_VAR_1}{K_I}라고 하는데\n"
	.string "부 부끄럽지만\l"
	.string "유적을 찾으며 살아가고 있지\p"
	.string "근데 배틀프런티어에도\n"
	.string "부끄럽지만 흐 흥미가 있다네\p"
	.string "{PLAYER} 자네는 포켓몬 배틀에\n"
	.string "강하다는 평판이 나 있더군...\l"
	.string "그 이런 말 하긴 그렇지만\l"
	.string "하나 부탁이 있다네\p"
	.string "내 선생님이 돼서\n"
	.string "어드바이스를 해주지 않겠나...?$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｐ
	@ ワシは §いと いってｎ
	@ は はずかしい けどｌ
	@ いせきを さがしたり して くらしてるんだｐ
	@ でも バトルフロンティア にもｎ
	@ はずかしながら き きょうみが あるんだｐ
	@ §あ§おは ポケモン つよいってｎ
	@ ひょうばん だから……ｌ
	@ その いいづらいん だけどｌ
	@ ひとつ おねがいを したいんだｐ
	@ ワシの せんせいに なってｎ
	@ アドバイスして もらえない かな……?

gText_ApprenticeRejectTeaching14:: @ 82B9D83
	.string "거 거절하지 말아주게!\n"
	.string "내게 부끄러움을 주지 말게나!\p"
	.string "부탁이니\n"
	.string "내 선생님이 되어주게!$"
	@ こ ことわらないでくれ!ｎ
	@ ワシに はじを かかせないで くれ!ｐ
	@ おねがい だからｎ
	@ ワシの せんせいに なってくれ!

gText_ApprenticeWhichLevelMode14:: @ 82B9DF9
	.string "고 고맙네...\p"
	.string "아니 그러니까 그렇게 보지 말아주게\n"
	.string "부끄럽단 말일세\p"
	.string "눈을 마주치지 말고 대답해 주게나!\p"
	.string "배 배틀타워... 배틀타워 말인데\n"
	.string "어느 레벨에 도전하면 좋겠는가?$"
	@ あ ありがとう……ｐ
	@ いや だから そんなに みないで くれよｎ
	@ てれるだろｐ
	@ めを あわせずに こたえて くれ!ｐ
	@ ば バトルタワ…… バトルタワ- だがｎ
	@ どの レベルに ちょうせん すれば いい?

gText_ApprenticeLevelModeThanks14:: @ 82B9EAA
	.string "아 알겠네!\n"
	.string "그쪽에서 열심히 해보겠네\p"
	.string "으으 부끄러움 안 타고\n"
	.string "열심히 할 수 있을까...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 보면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ それで がんばって みるよｐ
	@ うう はずかし がらずにｎ
	@ がんばれる かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticePleaseTeach15:: @ 82B9F55
	.string "응?\n"
	.string "{PLAYER}처럼 보인다만...\l"
	.string "진짜인가?\p"
	.string "난 {STR_VAR_1}\n"
	.string "지금 말이지 누군가 강한 트레이너의\l"
	.string "제자로 들어가려고 생각 중이었네\p"
	.string "그런 때에 자네가 와서 다행이군!\n"
	.string "...정말로 {PLAYER} 맞는 거지?\p"
	.string "아냐 진짜라면 됐어\n"
	.string "내가 제자가 되는 걸 허락해주게$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんもの なのかね?ｐ
	@ わたしは §いだｎ
	@ いまね だれか つよい トレ-ナ-にｌ
	@ でしいり したいと おもって いたんだよｐ
	@ きみが いるなら よかった!ｎ
	@ ……ほんとうに §あ§お だよね?ｐ
	@ いや ほんもの なら いいんだｎ
	@ わたしの でしいりを みとめて ほしい

gText_ApprenticeRejectTeaching15:: @ 82BA084
	.string "뭐? 왜 거절하는 거지?\p"
	.string "진짜인지 의심해서 미안했네\n"
	.string "사과할 테니 제자로 받아주게나$"
	@ え? なぜ ことわるのかね?ｐ
	@ ほんものか どうか うたがって わるかったｎ
	@ あやまるから でしいり させてほしい

gText_ApprenticeWhichLevelMode15:: @ 82BA11D
	.string "정말로 허락하는 겐가?\n"
	.string "괜한 기대를 가지고 싶진 않거든\p"
	.string "아니 진짜로 그런 거라면 됐네 미안하네\n"
	.string "바로 상담해주면 좋겠군\p"
	.string "내가 배틀타워에 간다면\n"
	.string "레벨 50... 오픈 레벨...\l"
	.string "어느 쪽이 어울린다고 생각하나?$"
	@ ほんとうに みとめて くれるのかね?ｎ
	@ ぬかよろこびは したく ないからなｐ
	@ いや ほんとうなら いいんだ わるかったｎ
	@ さっそく そうだんに のってほしいｐ
	@ わたしが バトルタワ-に でるならｎ
	@ レベル50…… オ-プンレベル……ｌ
	@ どちらの ほうが ふさわしいと おもうかね

gText_ApprenticeLevelModeThanks15:: @ 82BA1F3
	.string "{STR_VAR_1}... 정말인가?\p"
	.string "아니 진짜라면 됐네\n"
	.string "정말 고맙네\p"
	.string "이런 나를\n"
	.string "제자로 인정해 줘서 기쁘군\l"
	.string "언젠가 다시 보도록 하지!$"
	@ §い…… ほんとうかね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｐ
	@ こんな わたし だがｎ
	@ でし として みとめて くれて うれしいｌ
	@ いずれまた あおう!

gText_ApprenticeWhatHeldItem0:: @ 82BA2A3
	.string "하아... 훌쩍훌쩍...\n"
	.string "아앗 {PLAYER}님!\p"
	.string "저 말이죠 못 정하고 있는 게 있어서\n"
	.string "조금 곤란해하고 있었어요\p"
	.string "그게 뭐냐면 {STR_VAR_1}에게\n"
	.string "뭘 지니게 할지에 대해서예요\l"
	.string "알려주세요 {PLAYER}님\l"
	.string "뭘 지니게 하면 좋을까요?$"
	@ はあ…… シクシクｎ
	@ ああっ §あさん!ｐ
	@ ぼくね きめられない ことが あってｎ
	@ ちょっと こまってたんですｐ
	@ きめられない のは §いにｎ
	@ なにを もたせるかって ことなんですｌ
	@ おしえて ください §あさんｌ
	@ なにか もたせた ほうが いいですか?

gText_ApprenticeHoldNothing0:: @ 82BA34E
	.string "엣... {STR_VAR_1}{K_EUNNEUN}\n"
	.string "아무것도 지니지 않는 편이 좋나요?$"
	@ えっ…… §いはｎ
	@ なにも もたないほうが いいんですか?

gText_ApprenticeThanksNoHeldItem0:: @ 82BA380
	.string "아 알겠습니다!\n"
	.string "정해주셔서 기뻐요 으허엉-!\p"
	.string "오늘 정말 감사했습니다!$"
	@ わっ わかりました!ｎ
	@ きまって うれしいです うぉぉ-ん!ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeThanksHeldItem0:: @ 82BA3D2
	.string "다 다행이다...\n"
	.string "{STR_VAR_1}{K_I}라면 가지고 있었을 거예요...\l"
	.string "정해주셔서 기뻐요 으허엉-!\p"
	.string "오늘 정말 감사했습니다!$"
	@ よ よかったｎ
	@ §いなら もってるかも……ｌ
	@ きまって うれしいです うぉぉ-ん!ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeItemAlreadyRecommended0:: @ 82BA448
	.string "으아앙-! 너무해요\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 이미\l"
	.string "알려주신 도구라구요 훌쩍\p"
	.string "아니면 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "아무것도 지니지 않는 편이 좋나요?$"
	@ うわ-ん! ひどいですｎ
	@ §いは もうｌ
	@ おしえてもらった どうぐ です グスンｐ
	@ それとも §うはｎ
	@ なにも もたないほうが いいんですか?

gText_ApprenticeWhatHeldItem1:: @ 82BA4D3
	.string "와- {PLAYER}님이다!\n"
	.string "잘됐다! 물어보고 싶은 게 있었거든!\p"
	.string "저기 {PLAYER}님은\n"
	.string "포켓몬에게 도구를 지니게 해?\l"
	.string "나도 지니게 하고 싶은데...\p"
	.string "내 {STR_VAR_1}에겐\n"
	.string "무엇을 지니게 하면 좋을까?\l"
	.string "{PLAYER}님은 어떻게 생각해?$"
	@ わ- §あさん だ!ｎ
	@ よかった! ききたい ことが あったんだ!ｐ
	@ あのね §あさんはｎ
	@ ポケモンに どうぐを もたせてる?ｌ
	@ ボクも もたせたいんだけど……ｐ
	@ ボクの §いにはｎ
	@ なにを もたせたら いいのかなｌ
	@ §あさんは どう おもう?

gText_ApprenticeHoldNothing1:: @ 82BA58C
	.string "엣 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "아무것도 안 지녀도 괜찮다는 뜻이야?$"
	@ えっ §いはｎ
	@ なにも もたせなくて いいって こと?

gText_ApprenticeThanksNoHeldItem1:: @ 82BA5BF
	.string "알았어 그럼 그렇게 할게-!\n"
	.string "고마워 선생님!$"
	@ わかった- じゃあ そうする-!ｎ
	@ せんせい ありがと!

gText_ApprenticeThanksHeldItem1:: @ 82BA5F3
	.string "에헤헤 {STR_VAR_1} 말이구나-\n"
	.string "그럼 그렇게 할게-!\p"
	.string "고마워 선생님!$"
	@ へええ! §いか-ｎ
	@ じゃあ そうする-!ｐ
	@ せんせい ありがと!

gText_ApprenticeItemAlreadyRecommended1:: @ 82BA635
	.string "아 으음 그게 아니라\n"
	.string "아직 알려주지 않은 도구 중에서\l"
	.string "뭐가 좋은지 알고 싶은 거야!\p"
	.string "아니면 이번엔\n"
	.string "아무것도 안 지니게 해볼까?$"
	@ あ えっと そうじゃなくてｎ
	@ まだ おしえて もらってない どうぐでｌ
	@ なにが いいか しりたいんだ!ｐ
	@ それとも こんどはｎ
	@ なにも もたせなくって いいのかな?

gText_ApprenticeWhatHeldItem2:: @ 82BA6E6
	.string "{PLAYER}님 안녕하세요!\n"
	.string "제 {STR_VAR_1} 말인데요...\p"
	.string "뭐라도 지닌물건을 주고 싶어요!\n"
	.string "뭔가 좋은 지닌물건을 알려주세요!$"
	@ §あさん こんにちは!ｎ
	@ ぼくの §いの ことなんだけどｐ
	@ なにか もちものを もたせたいんだ!ｎ
	@ なにか いい もちもの おしえてください!

gText_ApprenticeHoldNothing2:: @ 82BA742
	.string "그럼 {STR_VAR_1}에겐\n"
	.string "아무것도 안 지니게 해도 되는 거죠?$"
	@ じゃあ §いにはｎ
	@ なにも もたせなくても いいんだね?

gText_ApprenticeThanksNoHeldItem2:: @ 82BA770
	.string "알겠습니다!\n"
	.string "그럼 다음에 봬요!$"
	@ わかりました!ｎ
	@ じゃあ また!

gText_ApprenticeThanksHeldItem2:: @ 82BA78F
	.string "{STR_VAR_1} 말이군요!\n"
	.string "알겠습니다!\p"
	.string "힘내서 찾아볼게요!\n"
	.string "그럼 다음에 봬요!$"
	@ §い ですか!ｎ
	@ わかりました!ｐ
	@ がんばって さがしてきます!ｎ
	@ じゃあ また!

gText_ApprenticeItemAlreadyRecommended2:: @ 82BA7D8
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "전에 알려주신 적이 있어요\p"
	.string "그거하곤 다른 지닌물건을\n"
	.string "지니게 하고 싶기도 하고요\p"
	.string "아니면 {STR_VAR_2}에게\n"
	.string "아무것도 안 지니게 해도 되나요?$"
	@ §いはｎ
	@ まえに おしえて もらいましたよｐ
	@ それとは ちがう もちものをｎ
	@ もたせたいんですｐ
	@ それとも §うにはｎ
	@ なにも もたせなくて いいんだね?

gText_ApprenticeWhatHeldItem3:: @ 82BA867
	.string "{PLAYER}님 안녕하세요...\n"
	.string "죄송합니다 저 오늘도\l"
	.string "여쭤보고 싶은 게 있어요\p"
	.string "제 힘만으로는\n"
	.string "승부에서 이기지 못할지도 모르니까\l"
	.string "뭔가 도구를 {STR_VAR_1}에게\l"
	.string "지니게 하려고 생각 중이거든요\l"
	.string "근데 뭐가 좋을지...\p"
	.string "{PLAYER}님 부탁드립니다\n"
	.string "저 대신 정해주세요!$"
	@ §あさん こんにちは……ｎ
	@ ごめんなさい きょうも あたしｌ
	@ ききたい ことが あるんですｐ
	@ あたしの ちから だけではｎ
	@ しょうぶに かてないかも しれないからｌ
	@ なにか どうぐを §いにｌ
	@ もたせようかと おもって いるんですｌ
	@ でも なにが いいのか……ｐ
	@ §あさん おねがいしますｎ
	@ あたしの かわりに きめてください!

gText_ApprenticeHoldNothing3:: @ 82BA96B
	.string "저기 저 따위의 포켓몬에겐\n"
	.string "아무것도 안 지니게 하는 편이 좋나요?$"
	@ あの あたしなんかの ポケモンにはｎ
	@ なにも もたせないほうが いいんですか?

gText_ApprenticeThanksNoHeldItem3:: @ 82BA9B7
	.string "알겠습니다...\n"
	.string "도구에 의존하지 말라는 말씀이시죠?\l"
	.string "열심히 하고 오겠습니다!\p"
	.string "감사합니다!$"
	@ わかりました……ｎ
	@ どうぐに たよるなって ことですね?ｌ
	@ がんばって みます!ｐ
	@ ありがとう ございます!

gText_ApprenticeThanksHeldItem3:: @ 82BAA1B
	.string "{STR_VAR_1} 말이군요!\n"
	.string "제가 손에 넣을 수 있을까요...\l"
	.string "아니죠! 열심히 구해볼게요\p"
	.string "감사합니다!$"
	@ §い ですか!ｎ
	@ あたしに みつけられるか……ｌ
	@ いえ! がんばって みますｐ
	@ ありがとう ございます!

gText_ApprenticeItemAlreadyRecommended3:: @ 82BAA81
	.string "에... 그건\n"
	.string "전에 알려주신 적이 있어요\p"
	.string "아 혹시\n"
	.string "제가 {STR_VAR_1}{K_EULREUL}\l"
	.string "잘 쓰지 못하고 있어서인가요?\p"
	.string "아니면 {STR_VAR_2}에겐 아무것도\n"
	.string "지니게 하지 않아도 된다는 뜻인가요?$"
	@ え…… それはｎ
	@ まえに おしえて いただいたと おもいますｐ
	@ あ もしかしてｎ
	@ あたしが §いをｌ
	@ つかいこなせて いないから ですか?ｐ
	@ それとも §うには なにもｎ
	@ もたせるなと いう こと でしょうか?

gText_ApprenticeWhatHeldItem4:: @ 82BAB22
	.string "어머 {PLAYER}\n"
	.string "잠깐 물어보고 싶은 게 있어!\p"
	.string "나 포켓몬은 정했는데\n"
	.string "어떤 도구를 지니게 할지까지는\l"
	.string "정하지 못했지 뭐야?\p"
	.string "어차피 할 거라면 마지막까지\n"
	.string "당신이 정해주는 게 좋지 않겠어?\l"
	.string "있지 뭐가 좋을까?\l"
	.string "{STR_VAR_1}에게 주고 싶어!$"
	@ あら §あ§おｎ
	@ ちょっと ききたい ことが あるのよ!ｐ
	@ わたし ポケモンは きめて もらったけどｎ
	@ どの どうぐを もたせるか まではｌ
	@ きめて もらってない じゃない?ｐ
	@ どうせ なら さいごまでｎ
	@ あなたが きめて くれない?ｌ
	@ ねえ なにが いいかしら?ｌ
	@ §いに もたせたいの!

gText_ApprenticeHoldNothing4:: @ 82BAC43
	.string "어머! {STR_VAR_1}{K_EULREUL}\n"
	.string "빈손으로 내보내라고?$"
	@ あら! §いはｎ
	@ てぶらで がんばれ って ことかしら?

gText_ApprenticeThanksNoHeldItem4:: @ 82BAC78
	.string "그게 좋다면 그렇게 할게!\n"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ それが よければ そうするわ!ｎ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeThanksHeldItem4:: @ 82BAD17
	.string "{STR_VAR_1} 말이지\n"
	.string "나쁘지 않네 그렇게 할게!\l"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ §いかｎ
	@ わるく ないわね そうするわ!ｌ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeItemAlreadyRecommended4:: @ 82BADB6
	.string "엣 무슨 소리 하는 거야\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 이미\l"
	.string "알려준 적 있잖아!\p"
	.string "아니면 {STR_VAR_2}{K_EULREUL}\n"
	.string "빈손으로 내보내라는 뜻이야?$"
	@ えっ なに いってるのよｎ
	@ §いは もうｌ
	@ おしえて もらった じゃない!ｐ
	@ それとも §うはｎ
	@ てぶらで がんばれ って ことかしら?

gText_ApprenticeWhatHeldItem5:: @ 82BAE36
	.string "요 {PLAYER}\n"
	.string "바쁜 것치고는 자주 만나네!\l"
	.string "나 오늘은\l"
	.string "워킹에 클리닝 게다가\l"
	.string "브러싱까지 하느라 엄청 큰일이었어!\p"
	.string "덕분에 소중한 {STR_VAR_1}에게\n"
	.string "도구조차 사주지 못했지-\p"
	.string "저기 말야! 시간도 없으니까\n"
	.string "무엇을 {STR_VAR_1}에게\l"
	.string "지니게 하면 좋을지만이라도\l"
	.string "어드바이스 해주라!$"
	@ よっ §あ§おｎ
	@ いそがしい わりには よく あうよね!ｌ
	@ オレは きょうはｌ
	@ ウォ-キング クリ-ニング それにｌ
	@ ブラッシングと たいへん そのものさ!ｐ
	@ おかげで だいじな §いにもｎ
	@ どうぐ さえ かって やれなくてね-ｐ
	@ あのさ! じかんも ないからｎ
	@ なにを §いにｌ
	@ もたせて やったら いいかｌ
	@ それだけでも アドバイス してよ!

gText_ApprenticeHoldNothing5:: @ 82BAF4E
	.string "오 그러면\n"
	.string "바쁜 내 {STR_VAR_1}{K_EUNNEUN}\l"
	.string "아무것도 안 지녀도 괜찮다는 거야?$"
	@ おっ それじゃｎ
	@ いそがしい オレの §いはｌ
	@ なにも もたなくて イイ ってこと?

gText_ApprenticeThanksNoHeldItem5:: @ 82BAF8F
	.string "오케이 알았어!\n"
	.string "그럼 굳이 시간 낼 필요도 없겠네\p"
	.string "오늘 상담해줘서 땡큐! 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ それ なら じかんも いらないぜｐ
	@ きょうは サンキュ-! じゃ またな!

gText_ApprenticeThanksHeldItem5:: @ 82BAFDB
	.string "오케이 알았어!\n"
	.string "그럼 어떻게든 시간 내서\l"
	.string "{STR_VAR_1}{K_EULREUL} 찾아볼게!\p"
	.string "난 좋은 선생님을 만났는걸\n"
	.string "땡큐! 그럼 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ じゃ なんとか じかん つくってｌ
	@ §いを さがすぜ!ｐ
	@ オレは いい せんせいに であえたよなｎ
	@ サンキュ-! じゃ またな!

gText_ApprenticeItemAlreadyRecommended5:: @ 82BB05F
	.string "나 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "이미 알고 있어!\p"
	.string "으음? 아니면\n"
	.string "바쁜 내 {STR_VAR_2}{K_EUNNEUN}\l"
	.string "아무것도 안 지녀도 괜찮다는 거야?$"
	@ あれっ §いはｎ
	@ もう しってるよ!ｐ
	@ ん? それともｎ
	@ いそがしい オレの §うはｌ
	@ なにも もたなくて イイ ってこと?

gText_ApprenticeWhatHeldItem6:: @ 82BB0D4
	.string "요 {PLAYER}님 나야 나!\n"
	.string "오늘도 하나 상담할 게 있으니까\l"
	.string "어드바이스 좀 부탁할게!\p"
	.string "자 그럼 상담 시작합니다!\n"
	.string "내 {STR_VAR_1}에게\l"
	.string "뭔가 도구를 지니게 한다면\l"
	.string "대체 뭘로 해야 좋을까?$"
	@ よぅ §あさん わたしだよ!ｎ
	@ きょうも ひとつ そうだんが あるのｌ
	@ アドバイス おねがい ねっ!ｐ
	@ ジャ-ン では そうだんです!ｎ
	@ わたしの §いにｌ
	@ なにか どうぐを もたせるならｌ
	@ いったい なにに したら いいかな?

gText_ApprenticeHoldNothing6:: @ 82BB18C
	.string "흐음-? {STR_VAR_1}한테\n"
	.string "지닌물건이 필요 없다는 뜻이야?$"
	@ ふ-ん? §いはｎ
	@ もちものは いらないって ことかな?

gText_ApprenticeThanksNoHeldItem6:: @ 82BB1CE
	.string "그럼 그렇게 할게!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ じゃ そうするね!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeThanksHeldItem6:: @ 82BB242
	.string "아항-!\n"
	.string "{STR_VAR_1}{K_I}라니 쿨하네\l"
	.string "꼭 그렇게 할게!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ ははぁ-ん!ｎ
	@ §いとは シブイわぁｌ
	@ ぜひ そうして みるね!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeItemAlreadyRecommended6:: @ 82BB2D9
	.string "앗하하 왜 그래\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 이미\l"
	.string "알려준 적이 있잖아!\l"
	.string "{PLAYER}님 괜찮은 거 맞지?\p"
	.string "아! 아니면 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "지닌물건이 필요 없다는 뜻이야?$"
	@ あっはは やだぁｎ
	@ §いは もうｌ
	@ おしえて もらった じゃない!ｌ
	@ §あさん だいじょぶ?ｐ
	@ あ! それとも §うはｎ
	@ もちものは いらないって ことかな?

gText_ApprenticeWhatHeldItem7:: @ 82BB370
	.string "{PLAYER}님 그간 평안하셨는지요\n"
	.string "잠깐 얘기 좀 들어주실래요?\p"
	.string "지난번에 싸웠던 트레이너님이\n"
	.string "포켓몬에게 뭔가 도구를\l"
	.string "지니게 했던 것 같더라고요\p"
	.string "때문에 지고 말았습니다...\p"
	.string "저도 지지 않고 뭔가\n"
	.string "{STR_VAR_1}에게 지니게 하고 싶어요!\l"
	.string "뭘 지니게 하면 좋을지\l"
	.string "정해주시면 감사하겠습니다만...$"
	@ ごきげん いかがですか §あさんｎ
	@ きいて くださる?ｐ
	@ このまえ たたかった トレ-ナ-さんｎ
	@ ポケモンに なにか どうぐをｌ
	@ もたせていた らしいんですのｐ
	@ おかげで まけて しまいましたわ……ｐ
	@ わたくしも まけずに なにかｎ
	@ §いに もたせたいんですの!ｌ
	@ なにが よろしいの でしょうｌ
	@ きめて いただければ うれしいのですが……

gText_ApprenticeHoldNothing7:: @ 82BB4C3
	.string "그건 즉... 도구를\n"
	.string "지니게 하지 않아도 괜찮다는 뜻인가요?$"
	@ それは つまり…… どうぐはｎ
	@ もたせなくて よろしいんですのね?

gText_ApprenticeThanksNoHeldItem7:: @ 82BB4FB
	.string "알겠습니다!\n"
	.string "이대로 계속 열심히 해볼게요\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "안녕히 계세요!$"
	@ わかりましたわ!ｎ
	@ このまま がんばる ことに しますわｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeThanksHeldItem7:: @ 82BB575
	.string "{STR_VAR_1} 말이군요!\n"
	.string "바로 주문해야겠네요!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "안녕히 계세요!$"
	@ §い ですのね!ｎ
	@ さっそく とりよせますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeItemAlreadyRecommended7:: @ 82BB5E1
	.string "그건 이미 가르쳐 주셔서\n"
	.string "갖고 있는 물건이에요!\p"
	.string "아니면... {STR_VAR_2}에게는\n"
	.string "아무것도 필요 없다는 뜻이신가요...?$"
	@ それは もう おしえて いただいてｎ
	@ わたくし もっておりますわ!ｐ
	@ それとも…… §うにはｎ
	@ なにも もたせないで よろしいと……?

gText_ApprenticeWhatHeldItem8:: @ 82BB656
	.string "{PLAYER}님!\n"
	.string "오늘도 만나서 감격했어요...!\p"
	.string "마마마마마 맞다!\n"
	.string "저기 {PLAYER}님께서\l"
	.string "정해주셨으면 하는 게 있는데요!\p"
	.string "제 {STR_VAR_1}에겐\n"
	.string "뭘 지니게 하면 좋을까요?$"
	@ §あさんっ!ｎ
	@ きょうも あえて かんげき ですっ……!ｐ
	@ そそそそそ そうだっ!ｎ
	@ あのっ §あさんにｌ
	@ きめて ほしいことが あるのですっ!ｐ
	@ わたしの §いにはｎ
	@ なにを もたせれば いいですかっ?

gText_ApprenticeHoldNothing8:: @ 82BB6E5
	.string "우와아앗 의외의 대답이었어요!\n"
	.string "즉 아무것도 필요 없다는 건가요?$"
	@ うわあぁっ いがいな おこたえだあ!ｎ
	@ つまり なにも いらないの ですねっ?

gText_ApprenticeThanksNoHeldItem8:: @ 82BB72C
	.string "확실히 이해했습니다!\n"
	.string "도구 없이 열심히 해볼게요!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 가르쳐 주세요!$"
	@ りょうかいで ありますっ!ｎ
	@ どうぐ なしで がんばるで あります!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticeThanksHeldItem8:: @ 82BB7A2
	.string "{STR_VAR_1} 말이군요!\n"
	.string "근데 지니게 하면 {PLAYER}님과\l"
	.string "커플 아이템이 되는 건가...?\p"
	.string "흐흐 반드시 지니게 할게요!\n"
	.string "그럼 다음에 또\l"
	.string "여러 가지 가르쳐 주세요!$"
	@ §い ですねっ!ｎ
	@ これって これって §あさんとｌ
	@ もしかして おそろい だったりしてっ!ｐ
	@ も- ぜったい もたせちゃいます!ｎ
	@ では また こんどｌ
	@ いろいろと おしえて くださいね!

gText_ApprenticeItemAlreadyRecommended8:: @ 82BB84A
	.string "어라 전에도 {STR_VAR_1}{K_EULREUL}\n"
	.string "알려주셨었잖아요!\p"
	.string "역시 그게 가장 좋은 건가요?\n"
	.string "앗 아니면 혹시\l"
	.string "{STR_VAR_2}에게는 아무것도\l"
	.string "지니게 할 필요가 없다는 뜻인가요?$"
	@ あれ まえにも §いをｎ
	@ おすすめして くれました よね!ｐ
	@ やっぱり コレが いちばん ですかっ?ｎ
	@ あ それとも もしかしてｌ
	@ §うには なにもｌ
	@ もたせなくて いいって ことですかっ?

gText_ApprenticeWhatHeldItem9:: @ 82BB8CD
	.string "헬로 헬-로\n"
	.string "마이 티처 {PLAYER}!\p"
	.string "오늘은 포켓몬의 도구에 대해서\n"
	.string "어드바이스를 부탁하고 싶어!\p"
	.string "아저씨의 {STR_VAR_1}에게는\n"
	.string "어떤 도구를 지니게 하면 좋을까?\l"
	.string "한 번에 딱 정해줘!$"
	@ ハロウ ハロ-ウｎ
	@ マイ ティ-チャ- §あ§お!ｐ
	@ きょうは ポケモンの どうぐに ついてｎ
	@ アドバイスを おねがい したいんだ!ｐ
	@ おじさんの §いにはｎ
	@ どんな どうぐを もたせれば いいかな?ｌ
	@ パ-っと きめちゃって くれ!

gText_ApprenticeHoldNothing9:: @ 82BB970
	.string "어이쿠 그건\n"
	.string "{STR_VAR_1}에게 빈손으로\l"
	.string "이기라고 말하라는 뜻이야?$"
	@ おっと それはｎ
	@ §いは なにも もたせずともｌ
	@ かてる っていう こと なのかな?

gText_ApprenticeThanksNoHeldItem9:: @ 82BB9AE
	.string "오케이 오케이!\n"
	.string "아저씨 팍팍 힘내볼게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ オ-ケイ オ-ケイ!ｎ
	@ おじさん グ-っと がんばるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeThanksHeldItem9:: @ 82BBA05
	.string "아하 {STR_VAR_1} 말이지!\n"
	.string "오케이 오케이!\l"
	.string "아저씨 후딱 찾아볼게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ゴ-っと さがして くるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeItemAlreadyRecommended9:: @ 82BBA6C
	.string "노노! {STR_VAR_1}{K_EUNNEUN}\n"
	.string "전에 알려줬었다구!\p"
	.string "오 아니면 혹시\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 아무것도 안 지녀도\l"
	.string "이길 수 있다는 뜻이야?$"
	@ ノンノン! §いはｎ
	@ まえに おしえて もらったよ!ｐ
	@ お それとも もしやｎ
	@ §うは なにも もたせずともｌ
	@ かてる っていう こと なのかな?

gText_ApprenticeWhatHeldItem10:: @ 82BBB01
	.string "{PLAYER} 나한테\n"
	.string "믿을 수 없는 일이 일어났어!\p"
	.string "아침에 일어났더니 포켓몬이\n"
	.string "금구슬을 10개나 가지고 있었다고!\l"
	.string "...거짓말이지롱! 으하하하!\p"
	.string "사실 나 포켓몬의 도구를\n"
	.string "뭘로 할지 고민 중인데\l"
	.string "그런 건 내 성격에 안 맞아!\l"
	.string "거기서 제안 하나! 내 {STR_VAR_1}에게\l"
	.string "뭘 지니게 하면 좋을지\l"
	.string "스승님이 정해주지 않을래?$"
	@ §あ§お ちょっとｎ
	@ しんじられん ことが おきた!ｐ
	@ けさ おきたら ポケモンがｎ
	@ きんのたまを 10コ もってたんだ!ｌ
	@ …… な-んて うっそさ! うわはは!ｐ
	@ じつは おいら ポケモンの どうぐをｎ
	@ かんがえる こと なんてｌ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろ おいらの §いｌ
	@ なにを もたせたら いいのかｌ
	@ ししょうが きめて くれない かな?

gText_ApprenticeHoldNothing10:: @ 82BBC1C
	.string "무슨 소리야?\n"
	.string "아무것도 지니게 하지 말라고?$"
	@ どういう ことかな?ｎ
	@ なにも もたせなくて いいんだな?

gText_ApprenticeThanksNoHeldItem10:: @ 82BBC4B
	.string "그렇구나 빈손으로도 괜찮다 이거지!\n"
	.string "그럼 뭐라도 지니게 해야겠다!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうか てぶらで いいのね!ｎ
	@ じゃあ なにか もたせようっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeThanksHeldItem10:: @ 82BBCF6
	.string "그렇구나\n"
	.string "{STR_VAR_1}{K_IGA} 좋다고!\l"
	.string "그럼 그거 말고 다른 거 줘야지!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ それだけは やめとこっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeItemAlreadyRecommended10:: @ 82BBD90
	.string "아- 그건 전에\n"
	.string "알려준 적 있지 않아?\l"
	.string "그거 말고 다른 거 안 돼?\p"
	.string "아니면 {STR_VAR_2}에게\n"
	.string "아무것도 지니게 하지 말라는 뜻이야?$"
	@ あ- それは いちどｎ
	@ おしえて もらったことが あるだろ?ｌ
	@ ちがうので なにか ないかな?ｐ
	@ それとも §うはｎ
	@ なにも もたせなくて いいのかな?

gText_ApprenticeWhatHeldItem11:: @ 82BBE0B
	.string "안-녕-하-세-요!\n"
	.string "네 안녕하십니까!\l"
	.string "시원한 선원인 저와 함께하는\l"
	.string "상담 타임 시간입니다!\l"
	.string "도구에 관한 상담인데요!\p"
	.string "제 {STR_VAR_1}에게 건넬\n"
	.string "지닌물건으로 뭐가 좋을까요?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしが おくるｌ
	@ そうだんタイム いってみよう!ｌ
	@ どうぐに かんする そうだんだよ!ｐ
	@ わしの §いに もたせるならｎ
	@ さあ どんな どうぐがいい?

gText_ApprenticeHoldNothing11:: @ 82BBEE5
	.string "그건 혹시 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "아무것도 지닐 필요가 없다는 뜻입니까?$"
	@ それは あれかな? §いはｎ
	@ なんにも もたなくて いいのかな?

gText_ApprenticeThanksNoHeldItem11:: @ 82BBF25
	.string "그럴 수가-앗! 요요!\n"
	.string "그럼 시원하게 빈손으로 가볼까!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ そうか-っ! ようよう!ｎ
	@ そんなら ノリノリで てぶらでいくぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeThanksHeldItem11:: @ 82BBFA4
	.string "{STR_VAR_1}{K_I}라니-잇! 요요!\n"
	.string "그럼 시원하게 지니게 해볼까!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで もたせてみるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeItemAlreadyRecommended11:: @ 82BC024
	.string "{STR_VAR_1}{K_I}라니-잇! 저기저기!\n"
	.string "그건 알려주신 적이 있다구요!\l"
	.string "뭔가 다른 걸로 부탁드립니다!\p"
	.string "아니면 그런 뜻인가요?\n"
	.string "아무것도 지니게 하지 말라는?$"
	@ §いか-っ! おいおい!ｎ
	@ それなら きいたことが あるぜ!ｌ
	@ なんか ちがうやつを たのむぜ!ｐ
	@ それとも あれかな?ｎ
	@ なにも もたせなくて いいのかな?

gText_ApprenticeWhatHeldItem12:: @ 82BC0C8
	.string "오케이 {PLAYER}님!\n"
	.string "오늘도 찾아냈다고!\l"
	.string "어떡하지 나? 상담해볼까!?\l"
	.string "앗 이미 얘기하고 있잖아!?\p"
	.string "앗 {PLAYER}님은 슬슬 내가\n"
	.string "싫어질 것 같다고!? 설마!!\l"
	.string "상담할 게 있는데 들어줘!\p"
	.string "내 {STR_VAR_1} 말인데\n"
	.string "좋은 도구를 지니게 하고 싶어!\l"
	.string "뭐가 좋을까? 자 정해줘!$"
	@ オッケ §あさん!ｎ
	@ きょうも みつけたぜェ!ｌ
	@ どうする オレ? そうだんしてみる!?ｌ
	@ って もう はなしかけてる!?ｐ
	@ って §あさん オレのこと そろそろｎ
	@ きらいに なってる!? なってない!!ｌ
	@ そうだんが あるんだけど きいてェ!ｐ
	@ オレの §い なんだけどｎ
	@ いい どうぐを もたせたいんだ!ｌ
	@ なにが いいか さあ きめて!

gText_ApprenticeHoldNothing12:: @ 82BC213
	.string "뭐어!? 그럼 {STR_VAR_1}{K_EULREUL}\n"
	.string "아무것도 안 지닌 상태로 내보내도 돼?$"
	@ エェ!? じゃあ §いにはｎ
	@ なにも もたせなくて いいって こと!?

gText_ApprenticeThanksNoHeldItem12:: @ 82BC247
	.string "아무것도 지니게 하지 말라니!\n"
	.string "그럼 말한 대로 할게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!!$"
	@ もたせないってエェ!ｎ
	@ じゃ いうとおりに するよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeThanksHeldItem12:: @ 82BC2DD
	.string "{STR_VAR_1}{K_I}라고!\n"
	.string "그럼 바로 지니게 해볼게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!!$"
	@ §いだってエェ!ｎ
	@ じゃ さっそく もたせてみるよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeItemAlreadyRecommended12:: @ 82BC373
	.string "잠깐 기다려봐!\n"
	.string "그 {STR_VAR_1}{K_I}라고 하는 거\l"
	.string "전에 들은 적 있는데!? 있다고!!\p"
	.string "다른 걸 알려줘!\n"
	.string "아니면 {STR_VAR_2}{K_EULREUL}\l"
	.string "빈손으로 내보내라는 거야!?$"
	@ ちょっと まったァ!ｎ
	@ その §いってｌ
	@ まえに きいたことが ある!? ある!!ｐ
	@ ほかのを おしえて!ｎ
	@ それとも §うにはｌ
	@ なにも もたせなくて いいって こと!?

gText_ApprenticeWhatHeldItem13:: @ 82BC40E
	.string "크헉 아야야! {PLAYER}\n"
	.string "팔이 부러졌으니까 만지지 말아줘!\p"
	.string "포켓몬에게 무엇을 지니게 할지\n"
	.string "스스로 이것저것 시험해보다가\l"
	.string "팔이 부러진 걸 거야 분명!\p"
	.string "그렇게 됐으니까 말이야\n"
	.string "대신 정해주라!\p"
	.string "{PLAYER}{K_EUNNEUN} 내 {STR_VAR_1}에게\n"
	.string "어떤 도구를 지니게 하면 좋을 것 같아?$"
	@ ギャッ いててっ! §あ§おｎ
	@ うでが おれてるから さわらないでよ!ｐ
	@ ポケモンに なにを もたせるかｎ
	@ じぶんで いろいろ ためしすぎちゃってｌ
	@ うでが おれちゃったん だよね きっと!ｐ
	@ というわけ だからさｎ
	@ かわりに きめて くれよ!ｐ
	@ §あ§おはさ おれの §いｎ
	@ どんな どうぐ もたせたら いいとおもう?

gText_ApprenticeHoldNothing13:: @ 82BC514
	.string "아야야... 으음 그 말은\n"
	.string "{STR_VAR_1}에겐 아무것도\l"
	.string "지니게 하지 않아도 된다는 뜻이야?$"
	@ いてて…… え-っと それってｎ
	@ §いには なにも もたせなくてｌ
	@ いいって ことかな?

gText_ApprenticeThanksNoHeldItem13:: @ 82BC555
	.string "응 알았어\n"
	.string "나한테도 그러는 편이 좋겠지!\p"
	.string "앞으로도 나를 잘 부탁한다구!$"
	@ ん わかったｎ
	@ おれも いまは そのほうが たすかるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeThanksHeldItem13:: @ 82BC5CE
	.string "응 알았어 {STR_VAR_1} 말이지!\n"
	.string "그럼 포켓몬은 팔팔하니까\l"
	.string "바로 지니게 해볼게!\p"
	.string "앞으로도 나를 잘 부탁한다구!$"
	@ ん わかった §いな!ｎ
	@ じゃあ ポケモンの うでは ぶじだからｌ
	@ さっそく もたせてみるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeItemAlreadyRecommended13:: @ 82BC666
	.string "아니아니 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "지난번에 알려줬었잖아?\l"
	.string "좀 더 굉장한 걸 알려달라고!\p"
	.string "앗 아니면\n"
	.string "{STR_VAR_1}에겐 아무것도\l"
	.string "지니게 하지 않아도 된다는 뜻이야?$"
	@ いやいや §いはｎ
	@ このあいだ おしえて くれただろ?ｌ
	@ もっと すごいの おしえてくれよ!ｐ
	@ あ それともｎ
	@ §うには なにも もたせなくてｌ
	@ いいって ことかな?

gText_ApprenticeWhatHeldItem14:: @ 82BC714
	.string "아... 아...\n"
	.string "{PLAYER}...\p"
	.string "그 그렇게 보지 말아주게\n"
	.string "내 포켓몬은 지닌물건이 없어서 말인데\p"
	.string "잠깐 그... 상담 좀 해주게나\n"
	.string "부 부끄럽지만 말일세!\l"
	.string "{STR_VAR_1}{K_IGA} 무엇을\l"
	.string "지니면 강해질지 고민하고 있거든\l"
	.string "{PLAYER} 자네는 뭐가 좋을 것 같나?$"
	@ あ…… あ……ｎ
	@ §あ§お……ｐ
	@ そ そんなに みないで くれよｎ
	@ ワシの ポケモン なにも もってないからさｐ
	@ ちょっと…… そうだん させて くれよｎ
	@ は はずかしいん だけどさ!ｌ
	@ §いが なにをｌ
	@ もったら つよいか って なやんでてさｌ
	@ §あ§お なにが いいと おもう?

gText_ApprenticeHoldNothing14:: @ 82BC808
	.string "그럼... {STR_VAR_1}{K_EUNNEUN} 아무것도\n"
	.string "지니지 않는 편이 좋은 겐가...?$"
	@ じゃ…… §いは なにもｎ
	@ もたない ほうが いいの かな……?

gText_ApprenticeThanksNoHeldItem14:: @ 82BC84D
	.string "아 알겠네!\n"
	.string "도구 없이 가도록 하지!\p"
	.string "으으 떨리는구먼\n"
	.string "너무 멋있는 것 같은데...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 만나면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ どうぐ なしで いくよ!ｐ
	@ うう てれるなｎ
	@ かっこ よすぎない かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeThanksHeldItem14:: @ 82BC8EA
	.string "아 알겠네!\n"
	.string "{STR_VAR_1}에게 지니게 해야겠군\p"
	.string "으으 떨리는구먼\n"
	.string "너무 멋있는 것 같은데...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 만나면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ §いに してみるよｐ
	@ うう てれるなｎ
	@ かっこ よすぎない かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeItemAlreadyRecommended14:: @ 82BC984
	.string "그건 이 이미 알려주었잖나\p"
	.string "나 나를 포기하지 말아주게!\n"
	.string "부디 나를 외면하지 말게나!\p"
	.string "아... 아니면\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 아무것도\l"
	.string "지니지 않는 편이 좋은 겐가...?$"
	@ それは も もう きいた じゃないかｐ
	@ て てを ぬかないでくれ!ｎ
	@ ワシに はじを かかせないで くれ!ｐ
	@ あ…… それともｎ
	@ §うは なにもｌ
	@ もたない ほうが いいの かな……?

gText_ApprenticeWhatHeldItem15:: @ 82BCA4D
	.string "응?\n"
	.string "{PLAYER}처럼 보인다만...\l"
	.string "정말로 자네 맞는 겐가?\l"
	.string "설마 쌍둥이는 아니겠지?\p"
	.string "앗 아닐세 아닐세!\n"
	.string "진짜라면 됐네 잊어주게!\l"
	.string "그리고 상담을 부탁하고 싶다네!\p"
	.string "나의 {STR_VAR_1} 말이다만!\n"
	.string "뭔가 편리한 도구를 건네주고 싶다네\l"
	.string "대체 어느 게 어울릴 것 같나?$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんもの なのかね?ｌ
	@ ふたごの きょうだい って ことは?ｐ
	@ あっ いやいや いやいや!ｎ
	@ ほんもの なら いいんだ わすれてくれ!ｌ
	@ さらに じょげんを おねがい したい!ｐ
	@ この わたしの §い!ｎ
	@ なにか べんりな どうぐを もたせたいｌ
	@ いったい どれが ふさわしい かな?

gText_ApprenticeHoldNothing15:: @ 82BCB75
	.string "아무것도 지니게 하지 않는 편이 좋다고...?\n"
	.string "정말인가?$"
	@ なにも もたない ほうが いい……?ｎ
	@ ほんとうかね?

gText_ApprenticeThanksNoHeldItem15:: @ 82BCBA6
	.string "흐음 그렇군 알겠네\n"
	.string "정말 고맙군\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ いや そうか なら いいんだｎ
	@ どうも ありがとうｐ
	@ では いずれまた あおう!

gText_ApprenticeThanksHeldItem15:: @ 82BCBFC
	.string "{STR_VAR_1}... 정말인가?\p"
	.string "아니 정말이라면 됐네\n"
	.string "정말 고맙군\l"
	.string "이런 나의 포켓몬이라도\l"
	.string "잘 쓸 수 있다면 좋겠어\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ §い…… ほんとうかね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｌ
	@ こんな わたしの ポケモンでもｌ
	@ つかいこなせると いいなｐ
	@ では いずれまた あおう!

gText_ApprenticeItemAlreadyRecommended15:: @ 82BCCA4
	.string "아니아니 기다려주게\n"
	.string "그건 전에 알려주었지 않나\l"
	.string "그것과는 다른 물건을\l"
	.string "추천받고 싶은 거라네\p"
	.string "아니면 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "아무것도 안 지니는 게 좋나...?\l"
	.string "자네 생각은 어떤가?$"
	@ いやいや まってくれｎ
	@ それは まえに おしえてくれた だろうｌ
	@ それとは ちがった ものをｌ
	@ すすめられて みたいんだｐ
	@ それとも §うはｎ
	@ なにも もたない ほうが いい……?ｌ
	@ ほんとうかね?

gText_ApprenticeWhichMonFirst0:: @ 82BCD68
	.string "우엥- {PLAYER}님!\n"
	.string "저 곤란해하고 있었어요 훌쩍\p"
	.string "슬슬 승부를 해보고 싶은데\n"
	.string "포켓몬을 어떤 순서로\l"
	.string "내보내는 게 좋을지 모르겠어서...\p"
	.string "{PLAYER}님이라면\n"
	.string "어느 포켓몬을 처음에 내보낼 건가요?\l"
	.string "...알려주세요!$"
	@ え-ん §あさ-ん!ｎ
	@ ぼく こまって いるんです グスンｐ
	@ そろそろ しょうぶを して みたいけどｎ
	@ ポケモンを どんな じゅんばんでｌ
	@ だしたら つよいのか わかんない……ｐ
	@ §あさん だったらｎ
	@ どの ポケモンを さいしょに だすかｌ
	@ ……おしえて ください!

gText_ApprenticeMonFirstThanks0:: @ 82BCE64
	.string "{STR_VAR_1} 말이군요! 으흑 으아앙-!\p"
	.string "아! 죄송합니다\n"
	.string "순서를 정해주신 게\l"
	.string "너무 기뻐서 눈물이...\p"
	.string "그럼 감사했습니다!$"
	@ §い ですね! うぅ うわ-ん!ｐ
	@ あ! ごめんなさいｎ
	@ じゅんばんが きまった うれしさでｌ
	@ なみだが……ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeWhichMonFirst1:: @ 82BCEF2
	.string "와앗! {PLAYER}님이다-!\n"
	.string "와아- 만나서 다행이야\l"
	.string "상담하고 싶은 게 있거든!\p"
	.string "저기 있지 내가 지닌\n"
	.string "포켓몬들 중에서\l"
	.string "어느 걸 처음으로 내보내면\l"
	.string "좋을 거라고 생각해?$"
	@ わわっ! §あさんだ-!ｎ
	@ わ-い あえて よかったｌ
	@ そうだん したいことが あるんだ!ｐ
	@ あのね ぼくの もってるｎ
	@ ポケモン たちの なかでｌ
	@ どれを さいしょに だせばｌ
	@ いいと おもう?

gText_ApprenticeMonFirstThanks1:: @ 82BCF61
	.string "{STR_VAR_1} 말이구나 역시 그렇지-!?\n"
	.string "그럼 그렇게 할게-!\p"
	.string "고마워 선생님!$"
	@ §いかあ そ-だよね!ｎ
	@ じゃあ そうする-!ｐ
	@ せんせい ありがと!

gText_ApprenticeWhichMonFirst2:: @ 82BCFA1
	.string "{PLAYER}님 안녕하세요!\n"
	.string "승부할 때 처음에\p"
	.string "어느 포켓몬을 내보낼지가\n"
	.string "무척이나 중요할 거 같은 기분이 들어서요!\p"
	.string "제가 지닌 포켓몬 중에서\n"
	.string "어느 포켓몬을\l"
	.string "처음에 내보내면 좋을까요?$"
	@ §あさん こんにちは!ｎ
	@ しょうぶのときって さいしょにｐ
	@ どの ポケモンを だすのかがｎ
	@ とても だいじな きが するんです!ｐ
	@ ぼくが もってる ポケモンの なかでｎ
	@ どの ポケモンをｌ
	@ さいしょに だすと いいでしょうか?

gText_ApprenticeMonFirstThanks2:: @ 82BD03C
	.string "{STR_VAR_1} 말이죠!\n"
	.string "알겠습니다!\p"
	.string "그럼 또 봬요!$"
	@ §い ですね!ｎ
	@ わかりました!ｐ
	@ じゃあ また!

gText_ApprenticeWhichMonFirst3:: @ 82BD06D
	.string "{PLAYER}님 언제나\n"
	.string "상담만 드려서 죄송합니다...\l"
	.string "저 자신이 없어서\l"
	.string "{PLAYER}님이 없으면 안 돼요...!\p"
	.string "저기 그 포켓몬의 순서 있죠...\n"
	.string "어떻게 해야 좋을 거라 생각하세요?\p"
	.string "저 따위가 고민을 해도\n"
	.string "아무 의미 없을지도 모르지만\l"
	.string "도저히 정하지 못하겠어서...\p"
	.string "어느 포켓몬을 1번\n"
	.string "그러니까 선두로 정하는 게 좋을까요!?$"
	@ §あさん いつもｎ
	@ そうだん ばかりで すみません……ｌ
	@ あたし じしんが なくってｌ
	@ §あさんが いないと……!ｐ
	@ あの ポケモンの じゅんばん って……ｎ
	@ どうすれば いいと おもいますか?ｐ
	@ あたし なんかが こだわってもｎ
	@ しかたが ないかも しれません けどｌ
	@ どうしても きめられなくて……ｐ
	@ どの ポケモンを 1ばんｎ
	@ せんとうに すれば よいんでしょうか!

gText_ApprenticeMonFirstThanks3:: @ 82BD18A
	.string "{STR_VAR_1} 말이군요 알겠습니다!\p"
	.string "이런 저 따위에게\n"
	.string "어떻게든 해답을 제시해 주시다니\l"
	.string "정말 믿기지 않아요!\p"
	.string "오늘 저 따위를 위해\n"
	.string "시간 내주셔서 감사했습니다...!$"
	@ §い ですか わかりました!ｐ
	@ こんな あたし なんかにｎ
	@ なんども こたえて いただけるなんてｌ
	@ しんじられない!ｐ
	@ きょうは あたしなんかの ためにｎ
	@ ありがとう ございました……!

gText_ApprenticeWhichMonFirst4:: @ 82BD222
	.string "{PLAYER}! 나야 나\n"
	.string "마침 잘됐다 곤란해하고 있었거든!\p"
	.string "잠깐 포켓몬의 순서를\n"
	.string "정하는 걸 도와줘야겠어!\l"
	.string "뭐 거창하게 말했지만\l"
	.string "1번째 포켓몬만 정해주면 돼\l"
	.string "어느 포켓몬으로 하면 좋을까?$"
	@ §あ§お! わたしよｎ
	@ よかったわ こまっていたの!ｐ
	@ ちょっと ポケモンの じゅんばんをｎ
	@ きめて もらえる かしら!ｌ
	@ と いっても そうねえｌ
	@ とりあえず 1ばんめの ポケモンで いいわｌ
	@ どの ポケモンに したら いいかしら?

gText_ApprenticeMonFirstThanks4:: @ 82BD325
	.string "{STR_VAR_1} 말이지 알았어!\n"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ §いね いいわ!ｎ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeWhichMonFirst5:: @ 82BD3B1
	.string "하이! 이 몸의 선생님\n"
	.string "{PLAYER}!\p"
	.string "난 오늘도 바쁘다구\n"
	.string "사이클링에 조깅에 허밍에!\p"
	.string "승부에 내보낼 포켓몬의\n"
	.string "순서조차 못 정하겠단 말이지-\p"
	.string "저기 있잖아!\n"
	.string "잠깐 내 포켓몬 좀 봐주라!\l"
	.string "어느 녀석이 처음으로 나가야 좋을까?$"
	@ ハイ! オレの せんせいｎ
	@ §あ§お!ｐ
	@ きょうも いそがしいんだ オレｎ
	@ サイクリングに ショッピングに ハミング!ｐ
	@ しょうぶに つかう ポケモンのｎ
	@ じゅんばんさえ きめられなくてね-ｐ
	@ あのさ!ｎ
	@ ちょっと オレの ポケモン みてよ!ｌ
	@ で どいつが はじめに でれば いいかな?

gText_ApprenticeMonFirstThanks5:: @ 82BD493
	.string "오케이 알았어!\n"
	.string "{STR_VAR_1}{K_EULREUL} 선두에\l"
	.string "서게 할 시간 정도는 있으니까!\p"
	.string "...어이쿠 여자친구가 기다리겠다!\n"
	.string "땡큐! 그럼 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ §いを せんとうに するｎ
	@ じかん くらいは あるぜ!ｐ
	@ ……と いけね かのじょが まってる!ｎ
	@ サンキュ-! じゃ またな!

gText_ApprenticeWhichMonFirst6:: @ 82BD51C
	.string "야호- 하이 {PLAYER}님-\n"
	.string "언제나 강해보이는 얼굴인걸\p"
	.string "저기 있지! 오늘도\n"
	.string "그거... 부탁할게! 괜찮지!?\p"
	.string "엣헴 그럼 오늘의 상담!\n"
	.string "제가 지니고 있는 포켓몬!\l"
	.string "자 어느 애를 첫 번째로\l"
	.string "내보내면 좋을까요?$"
	@ ヤッホ- ハ-イ §あさ-んｎ
	@ いつも つよそうな かおで あるいてるわねｐ
	@ ねえねえ! きょうもｎ
	@ あれ…… おねがい! いいでしょ!ｐ
	@ ジャ-ン では ほんじつの そうだん!ｎ
	@ わたしが もっている ポケモン!ｌ
	@ さあ どのコを いちばんｌ
	@ さいしょに だせば いいでしょう?

gText_ApprenticeMonFirstThanks6:: @ 82BD609
	.string "흠흠!\n"
	.string "{STR_VAR_1} 말이군요?\l"
	.string "깔끔한 대답 고마워!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ ふむふむ!ｎ
	@ §い ですねぇ?ｌ
	@ シブイ おこたえ ありがとう!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeWhichMonFirst7:: @ 82BD697
	.string "말을 걸어주셔서\n"
	.string "정말로 감사드립니다 {PLAYER}님\p"
	.string "그 친절함에 기대어\n"
	.string "오늘도 상담을 부탁드리고자 합니다만...\p"
	.string "포켓몬의 순서를\n"
	.string "정해 주셨으면 합니다\p"
	.string "처음에 내보낼 포켓몬으로\n"
	.string "어느 아이가 좋다고 생각하시는지요?$"
	@ はなしかけて くださってｎ
	@ ありがとう ございます §あさんｐ
	@ その おやさしさに あまえてｎ
	@ きょうも そうだんが ありますの……ｐ
	@ あの ポケモンの じゅんばんをｎ
	@ きめて いただきたいん ですのｐ
	@ さいしょに だす ならｎ
	@ どの ポケモンが よろしいでしょうか?

gText_ApprenticeMonFirstThanks7:: @ 82BD797
	.string "{STR_VAR_1} 말이군요!\n"
	.string "바로 순서를 바꿔 놔야겠어요!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "안녕히 계세요!$"
	@ §い ですのね!ｎ
	@ すぐに ならびかえますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeWhichMonFirst8:: @ 82BD806
	.string "꺄- 꺄-!\n"
	.string "{PLAYER}님이다!\l"
	.string "오늘도 만나서 감격했어요...!\p"
	.string "제 포켓몬들\n"
	.string "많이 강해졌답니다!\l"
	.string "근데 처음에 내보내는 포켓몬에 따라\l"
	.string "이기기도 하고 지기도 하더라고요\p"
	.string "{PLAYER}님 그러니 부탁드릴게요!\n"
	.string "어느 애를 처음으로 내보내면 좋을지\l"
	.string "제발 정해주세요!$"
	@ キャ-キャ-!ｎ
	@ §あ さ-んっ!ｌ
	@ きょうも あえて かんげきっ……!ｐ
	@ わたしの ポケモンたちｎ
	@ つよく なりましたよ!ｌ
	@ でも はじめに だす ポケモンでｌ
	@ かったり まけたり しちゃうんですｐ
	@ §あさん おねがいが!ｎ
	@ どのコを はじめに だしたら いいのかｌ
	@ ぜひ きめて ほしいのですっ!

gText_ApprenticeMonFirstThanks8:: @ 82BD8F5
	.string "하아아아... 너무 행복해요\n"
	.string "{PLAYER}님이 정해주시다니!\l"
	.string "알겠습니다! 저\l"
	.string "{STR_VAR_1}부터 내보내볼게요!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 가르쳐 주세요!$"
	@ はあああ…… しあわせすぎるｎ
	@ §あさんに きめて もらうなんて!ｌ
	@ りょうかいですっ! わたしｌ
	@ §いから いくで ありますっ!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticeWhichMonFirst9:: @ 82BD9BE
	.string "헬-로!\n"
	.string "마이 티처 {PLAYER}\l"
	.string "오늘도 어드바이스 팍팍 부탁할게!\p"
	.string "아저씨 쓰리 포켓몬으로\n"
	.string "팀을 만들기까진 했는데\l"
	.string "아직 순서를 못 정했거든\p"
	.string "그러니까! {PLAYER}{K_IGA}\n"
	.string "먼저 처음에 내보낼 포켓몬을\l"
	.string "파밧 정해줘!$"
	@ ハロ-ウ!ｎ
	@ マイ ティ-チャ- §あ§おｌ
	@ きょうも アドバイス バンバンたのむよ!ｐ
	@ おじさん スリ- ポケモンズでｎ
	@ ティ-ムを つくったのは いいんだがｌ
	@ まだ じゅんばんが きまって ないんだよｐ
	@ そこで! §あ§おがｎ
	@ まず はじめに だす ポケモンをｌ
	@ ササ-っと きめちゃって くれ!

gText_ApprenticeMonFirstThanks9:: @ 82BDAE1
	.string "아하 {STR_VAR_1} 말이지\n"
	.string "오케이 오케이!\l"
	.string "아저씨 휙 하고 바꿔둘게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ガガ-っと いれかえるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeWhichMonFirst10:: @ 82BDB4E
	.string "{PLAYER} 들어봐 큰일이라고!\n"
	.string "내 포켓몬 배틀하라고 하면\l"
	.string "3마리가 동시에 나가버려!\l"
	.string "...농담이야 그럴 리 없잖아 으하하!\p"
	.string "실은 나 포켓몬의\n"
	.string "순서를 정하는 데\l"
	.string "그다지 재능이 없거든!\l"
	.string "거기서 제안 하나! 내 포켓몬 중\l"
	.string "어느 녀석을 처음에 내보내면 좋을지\l"
	.string "스승님이 정해주지 않을래?$"
	@ §あ§お きいてくれ たいへんだ!ｎ
	@ おいらの ポケモンと きたらｌ
	@ 3びき いっしょに とびだすんだよ!ｌ
	@ ……なんて わきゃ ないな わはは!ｐ
	@ じつは おいら ポケモンのｎ
	@ じゅんばん なんて きめるのｌ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろ おいらの ポケモンｌ
	@ どいつを さいしょに だしたら いいかｌ
	@ ししょうが きめて くれない かな?

gText_ApprenticeMonFirstThanks10:: @ 82BDC6B
	.string "그렇구나\n"
	.string "{STR_VAR_1}{K_IGA} 좋단 말이지!\l"
	.string "그럼 그 녀석만 빼고 선두에 내보내야겠다!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ そいつだけは やめようっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeWhichMonFirst11:: @ 82BDD0D
	.string "안-녕-하-세-요!\n"
	.string "네 안녕하십니까!\l"
	.string "시원한 선원인 저와\l"
	.string "오늘의 상담 타임! 시작합니다!\l"
	.string "순서에 관한 상담이라구요!\p"
	.string "대답 주시죠! 이 중에서\n"
	.string "선두에 내보내야 할 포켓몬은?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしのｌ
	@ きょうの そうだん いってみようよ!ｌ
	@ じゅんばんに かんする そうだんだよ!ｐ
	@ こたえて! この なかでｎ
	@ せんとうに したい ポケモンは どれ?

gText_ApprenticeMonFirstThanks11:: @ 82BDDEC
	.string "{STR_VAR_1}{K_I}란 말인가-앗! 요요!\n"
	.string "그럼 시원하게 바꿔두겠습니다!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで いれかえるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeWhichMonFirst12:: @ 82BDE68
	.string "야-호- {PLAYER}님 아냐-?\n"
	.string "어떡하지 나? 그거 물어볼까?\l"
	.string "상담할 게 있는데 들어줘!\l"
	.string "앗 근데 이미 듣고 있네!!?\p"
	.string "내 포켓몬 중에서 어느 녀석을\n"
	.string "처음에 내보낼지 정해줘어엇!$"
	@ ヤァ-フゥ- §あさんじゃ-ん?ｎ
	@ どうする オレ? アレきいてみる!?ｌ
	@ そうだんが あるんだけど きいてェ!ｌ
	@ って きいてる!? きいてる!!ｐ
	@ オレの ポケモンの うち どいつをｎ
	@ さいしょに だしたら いいか きめてエェ!

gText_ApprenticeMonFirstThanks12:: @ 82BDF4D
	.string "{STR_VAR_1}{K_I}라고? 오우 예스!\n"
	.string "그럼 그렇게 해볼게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!$"
	@ §いだって! イエス!ｎ
	@ じゃ そうしてみる!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeWhichMonFirst13:: @ 82BDFD8
	.string "으으 {PLAYER}...\n"
	.string "배가 아프니까 잠깐 기다려줘...\p"
	.string "...아아 좀 나아졌다...\p"
	.string "어느 포켓몬을 승부할 때\n"
	.string "첫 번째로 내보낼지 고민 중인데\l"
	.string "고민을 해도 너무 했나봐!\p"
	.string "그러니까\n"
	.string "대신 좀 정해주라!\p"
	.string "{PLAYER}{K_EUNNEUN} 내 포켓몬 중\n"
	.string "누구를 처음에 내보내야\l"
	.string "이길 수 있다고 생각해?$"
	@ うう §あ§お ……ｎ
	@ おなか いたくってさ ちょっとまって……ｐ
	@ ……ああ なおってきた……ｐ
	@ どの ポケモンを しょうぶのときｎ
	@ さいしょに だすか なやんで いてｌ
	@ なやみ すぎちゃったん だよね きっと!ｐ
	@ というわけ だからさｎ
	@ かわりに きめて くれよ!ｐ
	@ §あ§おはさ おれの ポケモンｎ
	@ どれを さいしょに だせばｌ
	@ かてると おもうかい?

gText_ApprenticeMonFirstThanks13:: @ 82BE0FD
	.string "응 알았어 {STR_VAR_1} 말이지!\n"
	.string "그럼 밥 먹고 나서\l"
	.string "그렇게 해봐야겠다\p"
	.string "앞으로도 나를 잘 부탁한다고!$"
	@ ん わかった §いな!ｎ
	@ じゃあ ごはんを たべたらｌ
	@ そういうふうに してみるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeWhichMonFirst14:: @ 82BE189
	.string "아... 아...\n"
	.string "{PLAYER} 맞지?\l"
	.string "그 그렇게 보지 말아주게!\l"
	.string "부끄럽단 말일세\l"
	.string "하나... 상담할 게 있네\p"
	.string "부 부끄러워하면서\n"
	.string "참가시킬 포켓몬 3마리는 정했다만\l"
	.string "내보낼 순서를 못 정했다네\p"
	.string "어느 포켓몬을 1번째로\n"
	.string "내보내야 체면이 서겠나...?$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｌ
	@ ひとつ…… そうだん させてよｐ
	@ は はずかし ながらｎ
	@ ポケモン 3びき きまった けどさｌ
	@ じゅんばんが きまらないんだよｐ
	@ どの ポケモンを 1ばんめにｎ
	@ だせば かっこが つくの かな……?

gText_ApprenticeMonFirstThanks14:: @ 82BE2A5
	.string "아 알겠네!\n"
	.string "{STR_VAR_1}부터 내보내도록 하지\p"
	.string "으으 부끄러움 안 타고\n"
	.string "열심히 할 수 있을까...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 보면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ §いから だして みるよｐ
	@ うう はずかし がらずにｎ
	@ がんばれる かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeWhichMonFirst15:: @ 82BE33E
	.string "응?\n"
	.string "{PLAYER}처럼 보인다만...\l"
	.string "그림자분신이라도 쓴 건 아니겠지?\p"
	.string "아닐세 아닐세! 진짜라면 됐네\n"
	.string "화내지 말게나!\l"
	.string "그나저나 조언을 부탁하고 싶네!\p"
	.string "내 지닌 포켓몬 중에서\n"
	.string "어느 포켓몬을 승부에 처음으로\l"
	.string "내보내면 좋을지 알려주게나$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ かげむしゃ って ことは ないだろうねｐ
	@ いやいやいや! ほんものなら いいんだｎ
	@ おこらないで くれ!ｌ
	@ そして じょげんを おねがい したい!ｐ
	@ わたしの てもちの なかからｎ
	@ どのポケモンを しょうぶの はじめにｌ
	@ だせば いいのか おしえて ほしい

gText_ApprenticeMonFirstThanks15:: @ 82BE46C
	.string "{STR_VAR_1}...\n"
	.string "거짓말은 아니겠지?\p"
	.string "아니 진짜라면 됐네\n"
	.string "정말 고맙군\l"
	.string "이런 나지만 열심히 해보겠네\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ §い……ｎ
	@ うそでは ないだろうね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｌ
	@ こんな わたしだが がんばって みようｐ
	@ では いずれまた あおう!

gText_ApprenticeWhichMon0:: @ 82BE50D
	.string "훌쩍...\n"
	.string "앗 {PLAYER}님!\l"
	.string "마침 만나서 잘됐네요\l"
	.string "저 정하지 못하겠는 게 있어서...\p"
	.string "그게 있죠 포켓몬 말인데요\n"
	.string "어느 쪽을 쓸지 못 정하겠어요\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중에서\n"
	.string "고민하는 중인데...\l"
	.string "{PLAYER}님은 어느 쪽을 써야\l"
	.string "이런 제가 이길 수 있을 거라 생각하세요?$"
	@ グスン……ｎ
	@ あっ §あさん!ｌ
	@ ちょうど よかったようｌ
	@ ぼく きめられない ことが あって……ｐ
	@ あのね ポケモンをねｎ
	@ どっちを つかうか きめられないんですｐ
	@ §い と §うでｎ
	@ まよって いるんだけど……ｌ
	@ §あさんは どっち だったらｌ
	@ ぼくでも かてそう って おもいますか?

gText_ApprenticeMonThanks0:: @ 82BE5F5
	.string "훌쩍 아 알겠습니다!\n"
	.string "아 죄송해요 너무 기뻐서 눈물이...\p"
	.string "저 힘내서 {STR_VAR_1}{K_EULREUL}\n"
	.string "잡아오도록 할게요!\p"
	.string "정말 감사합니다! 이만 실례할게요$"
	@ グスっ わ わかりました!ｎ
	@ あ ごめんなさい うれしくて なみだが……ｐ
	@ ぼく がんばって §いをｎ
	@ つかまえてみます!ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeWhichMon1:: @ 82BE679
	.string "앗! {PLAYER}님이다-!\n"
	.string "와아 마침 잘 만났네\l"
	.string "오늘도 나하고 상담 좀 해주라!\p"
	.string "저기 있지 나 말야\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중에서\l"
	.string "어느 쪽을 쓸지 고민 중이거든\p"
	.string "누구를 키워야 할까\n"
	.string "{PLAYER}님은 어떻게 생각해?$"
	@ あっ! §あさんだ-!ｎ
	@ わ-い ちょうど よかったｌ
	@ きょうも ボクの そうだんに のってね!ｐ
	@ あのね ボクねｎ
	@ §いと §うの どっちをｌ
	@ つかうか まよっちゃったのｐ
	@ どっちを そだてようかなあｎ
	@ §あさんは どう おもう?

gText_ApprenticeMonThanks1:: @ 82BE71E
	.string "헤에\n"
	.string "{STR_VAR_1}{K_IGA} 좋구나!\l"
	.string "그럼 그렇게 할게-!\p"
	.string "고마워 선생님!$"
	@ へえｎ
	@ §いが いいのか!ｌ
	@ じゃあ そうする-!ｐ
	@ せんせい ありがと!

gText_ApprenticeWhichMon2:: @ 82BE762
	.string "{PLAYER}님 안녕하세요!\n"
	.string "잠깐 질문드릴 게 있습니다!\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중에서\n"
	.string "어느 쪽을 쓸지 고민하고 있거든요!\p"
	.string "어느 포켓몬이\n"
	.string "더 강하다고 생각하세요?$"
	@ §あさん こんにちは!ｎ
	@ ちょっと しつもん させて ください!ｐ
	@ §い と §う でｎ
	@ どっちを つかうか なやんでるんです!ｐ
	@ どっちの ポケモンがｎ
	@ つよいと おもいますか?

gText_ApprenticeMonThanks2:: @ 82BE7F8
	.string "{STR_VAR_1} 말이군요!\n"
	.string "알겠습니다!\p"
	.string "좋았어 바로\n"
	.string "강한 {STR_VAR_1}{K_EULREUL} 잡아야지!\p"
	.string "그럼 다음에 봬요!$"
	@ §い ですね!ｎ
	@ わかりました!ｐ
	@ よし さっそくｎ
	@ つよい §いを つかまえるぞ!ｐ
	@ じゃあ また!

gText_ApprenticeWhichMon3:: @ 82BE850
	.string "{PLAYER}님...!\n"
	.string "저기 어차피 저 같은 건\l"
	.string "잊어버리셨겠지만\p"
	.string "...그래도 괜찮으니까\n"
	.string "상담 좀 부탁드릴게요...\p"
	.string "저 키우고 싶은 포켓몬 하나조차\n"
	.string "스스로 결정하지 못하겠어서...\l"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}\l"
	.string "선택지를 두 개로 좁히긴 했는데\l"
	.string "고민이 끝나질 않아요...\p"
	.string "{PLAYER}님 싫으실지도 모르지만\n"
	.string "부디 저 대신 정해주세요!$"
	@ §あさん……!ｎ
	@ あの あたしの ことなんてｌ
	@ どうせ わすれて しまいました よねｐ
	@ ……それでも いいです からｎ
	@ そうだんに のって ください……ｐ
	@ あたし そだてたい ポケモン ひとつｎ
	@ じぶんで きめられなくって……ｌ
	@ §い か §うｌ
	@ どちらかに する までは きまったけどｌ
	@ そこで まよってしまって……ｐ
	@ §あさん いやかも しれませんがｎ
	@ あたしの かわりに きめてください!

gText_ApprenticeMonThanks3:: @ 82BE99C
	.string "저 따위가 하는 말을\n"
	.string "{STR_VAR_1}{K_IGA} 들어줄지...\p"
	.string "그래도 한번 해볼게요!\p"
	.string "근데 그 전에 잡을 수는 있을까...?\n"
	.string "아니지! 열심히 할게요\p"
	.string "감사합니다!$"
	@ あたし なんかの いうことｎ
	@ §いが きいて くれるか……ｐ
	@ でも やって みます!ｐ
	@ そのまえに つかまえられるか……ｎ
	@ いえ! がんばって みますｐ
	@ ありがとう ございます!

gText_ApprenticeWhichMon4:: @ 82BEA1B
	.string "{PLAYER} 잘됐다\n"
	.string "마침 찾으러 가려고 했었거든!\p"
	.string "저기 있지 내가 쓸 포켓몬\n"
	.string "네가 정해주면 안 될까?\p"
	.string "그러니까...\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중에서\l"
	.string "누가 더 좋다고 생각해?$"
	@ §あ§お よかったｎ
	@ さがしに いこうと おもってたのよ!ｐ
	@ ねえ わたしが つかう ポケモンｎ
	@ あなたが きめて くれない?ｐ
	@ そうね……ｎ
	@ §いと §うだったらｌ
	@ どっちが いいと おもう?

gText_ApprenticeMonThanks4:: @ 82BEAE9
	.string "{STR_VAR_1} 말이지 고마워!\n"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ §いね ありがと!ｎ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeWhichMon5:: @ 82BEB72
	.string "어라-\n"
	.string "{PLAYER}잖아 잘 지내?\l"
	.string "난 변함없이 바쁘다고!\p"
	.string "포켓몬 쪽에도 집중하고 싶은데\n"
	.string "누구를 잡을지도 못 정하겠어-\p"
	.string "그러니까 물어볼게!\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 강해보이잖아?\l"
	.string "근데 {STR_VAR_2}도 멋지단 말이지-\p"
	.string "{PLAYER} 어드바이스 좀 해줘!\n"
	.string "어느 포켓몬이 좋을까?$"
	@ あっれ-ｎ
	@ §あ§お じゃない げんき?ｌ
	@ オレは あいかわらず いそがしくてさ!ｐ
	@ ポケモンも がんばりたいんだ けどｎ
	@ どいつを つかうかも きまんなくてね-ｐ
	@ あのさ!ｎ
	@ §いって つよそう じゃん?ｌ
	@ でも §うも すてがたいよね-ｐ
	@ §あ§お アドバイス してよ!ｎ
	@ どっちの ポケモンが イイかな?

gText_ApprenticeMonThanks5:: @ 82BEC8E
	.string "오케이 알았어!\n"
	.string "그럼 어떻게든 시간을 내서\l"
	.string "{STR_VAR_1}{K_EULREUL} 잡아봐야겠다!\p"
	.string "난 좋은 선생님을 만났는걸\n"
	.string "땡큐! 그럼 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ じゃ なんとか じかん つくってｌ
	@ §いを つかまえて みるぜ!ｐ
	@ オレは いい せんせいに であえたよなｎ
	@ サンキュ-! じゃ またな!

gText_ApprenticeWhichMon6:: @ 82BED16
	.string "앗 와아!\n"
	.string "{PLAYER}님이잖아!\l"
	.string "나 요전에 친구들한테\l"
	.string "아는 사이라고 자랑했다!\p"
	.string "저기 있지 오늘도 어드바이스 부탁할게!\n"
	.string "간단한 거야!\p"
	.string "자 그럼 질문입니다!\n"
	.string "내가 키울 포켓몬으로!\l"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중 누가 좋을까?$"
	@ あっ わ-いｎ
	@ §あさん じゃない!ｌ
	@ わたし さっそく ともだちにｌ
	@ しりあいだって じまん しちゃったよ!ｐ
	@ ねえねえ きょうも アドバイス おねがい!ｎ
	@ かんたんな こと だから ねっ!ｐ
	@ ジャ-ン では しつもんです!ｎ
	@ わたしが そだてる なら!ｌ
	@ §いと §う さあどっち?

gText_ApprenticeMonThanks6:: @ 82BEE29
	.string "호오-!\n"
	.string "{STR_VAR_1}{K_I}라고요!\l"
	.string "깔끔한 대답 고마워!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ へっえ-!ｎ
	@ §い と きますかぁ!ｌ
	@ シブイ おこたえ ありがとう!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeWhichMon7:: @ 82BEEB4
	.string "어머 {PLAYER}님 아니신가요?\n"
	.string "그간 평안하셨는지요...!\p"
	.string "당신의 제자로 들어가고 나서\n"
	.string "저 조금 자신감이 붙기 시작했답니다!\l"
	.string "그래서 빨리 포켓몬을 키우고 싶다고\l"
	.string "생각하고 있지요!\p"
	.string "그래서 말이죠 {PLAYER}님께서\n"
	.string "제 포켓몬을\l"
	.string "정해주실 수는 없으신가요?\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}...\n"
	.string "어느 포켓몬이 괜찮을까요?$"
	@ まあ §あさんでは?ｎ
	@ ごきげんよう……!ｐ
	@ あなたに でしいり して わたくしｎ
	@ すこし じしんが ついて まいりました!ｌ
	@ ポケモンを さっそく そだてたいとｌ
	@ おもって おりますの!ｐ
	@ それでね §あさんにｎ
	@ わたしの ポケモンをｌ
	@ きめていただく わけには まいりませんか?ｐ
	@ §いと §う……ｎ
	@ どちらの ポケモンが よろしいでしょう?

gText_ApprenticeMonThanks7:: @ 82BEFE2
	.string "{STR_VAR_1} 말이군요!\n"
	.string "바로 찾아보도록 하겠습니다!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "안녕히 계세요!$"
	@ §い ですのね!ｎ
	@ さっそく さがして きますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeWhichMon8:: @ 82BF04E
	.string "꺄- 또 {PLAYER}님을 만났어!\n"
	.string "가 감격이야...!\p"
	.string "마마마 맞다!\n"
	.string "모처럼 만났는걸\l"
	.string "이 기회를 놓칠 수는 없지!\p"
	.string "{PLAYER}님 부탁이 있어요!\n"
	.string "제 포켓몬을 정해주세요!\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중에서\n"
	.string "어느 쪽이 더 좋은가요!$"
	@ キャ- §あさんに また あえた!ｎ
	@ かっ かんげきっ……!ｐ
	@ そそそ そうだわっ!ｎ
	@ せっかく あえたん ですものｌ
	@ この チャンスを のがす ては ないわっ!ｐ
	@ §あさん おねがいが!ｎ
	@ わたしの ポケモンを きめて くださいっ!ｐ
	@ §いと §うとｎ
	@ どちらが いいか きめて ほしいのですっ!

gText_ApprenticeMonThanks8:: @ 82BF11D
	.string "우와아아 정해주셨어!\n"
	.string "{STR_VAR_1} 말이군요!\l"
	.string "열심히 키워볼게요!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 가르쳐 주세요!$"
	@ うわぁぁ きめて もらっちゃったあ!ｎ
	@ §い ですねっ!ｌ
	@ がんばって そだてるで あります!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticeWhichMon9:: @ 82BF1A8
	.string "헤이 헤이 {PLAYER}!\n"
	.string "아저씨의 포켓몬 티처!\p"
	.string "헬로 너를 찾고 있었다고\n"
	.string "어드바이스를 부탁할게!\p"
	.string "아저씨가 쓸 포켓몬\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중에서\l"
	.string "어느 쪽이 더 좋을까?\l"
	.string "한 번에 딱 정해줘!$"
	@ ヘイ ヘイ §あ§お!ｎ
	@ おじさんの ポケモン ティ-チャ-!ｐ
	@ ハロウ きみを さがしてたんだよｎ
	@ アドバイスを おねがいするよ!ｐ
	@ おじさんが つかう ポケモンｎ
	@ どっちが いいかな?ｌ
	@ §いか §うかｌ
	@ パ-っと きめちゃって くれ!

gText_ApprenticeMonThanks9:: @ 82BF268
	.string "아하 {STR_VAR_1} 말이지\n"
	.string "오케이 오케이!\l"
	.string "아저씨 파박 잡고 올게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ガ-っと つかまえて くるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeWhichMon10:: @ 82BF2D1
	.string "{PLAYER} 큰일이야 큰일!\n"
	.string "환상의 포켓몬을 잡아버렸다구!\l"
	.string "...농담이야 거짓말이지롱! 와하하\p"
	.string "실은 나 포켓몬 잡는 데에\n"
	.string "그다지 재능이 없어서 말야!\l"
	.string "거기서 제안 하나! 어느 녀석을\l"
	.string "내 포켓몬으로 잡으면 좋을지\l"
	.string "스승님이 정해주지 않을래?\p"
	.string "어느 쪽이 좋을까?\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}{K_I}라면...$"
	@ §あ§お たいへんだ たいへんだ!ｎ
	@ まぼろしの ポケモン つかまえちゃった!ｌ
	@ ……なんて うそさ! わっはっはｐ
	@ じつは おいら ポケモン つかまえるのｎ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろ おいらの ポケモンｌ
	@ どいつを つかまえたら いいかｌ
	@ ししょうが きめて くれない かな?ｐ
	@ どっちが いいかな?ｎ
	@ §いと §うだと……

gText_ApprenticeMonThanks10:: @ 82BF3CF
	.string "그렇구나\n"
	.string "{STR_VAR_1}{K_IGA} 좋단 말이지!\l"
	.string "그럼 그 반대쪽을 잡아야겠다!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ ちがうほうに しようっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeWhichMon11:: @ 82BF46A
	.string "안-녕-하-세-요!\n"
	.string "네 안녕하십니까!\l"
	.string "시원한 선원인 저를\l"
	.string "당연히 기억하시겠죠 당신?\p"
	.string "자 오늘도 질문 갑니다!\n"
	.string "포켓몬에 관한 상담이라구요!\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}\n"
	.string "저는 어느 쪽을 잡으면 좋을까요?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしｌ
	@ きみは とうぜん おぼえてるだろ?ｐ
	@ きょうも わしの しつもん いってみよう!ｎ
	@ ポケモンに かんする そうだんだよ!ｐ
	@ §い と §うｎ
	@ わしが つかまえるなら さあ どっち?

gText_ApprenticeMonThanks11:: @ 82BF551
	.string "{STR_VAR_1}입니까-앗! 요요!\n"
	.string "그렇다면 시원시원하게 찾아보죠!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで さがしてくるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeWhichMon12:: @ 82BF5C3
	.string "우오옷 {PLAYER}님 아냐-!?\n"
	.string "어떡하지 나? 상담해볼까!?\l"
	.string "앗 근데 이미 말 걸고 있잖아!?\p"
	.string "안녕 오랜만이야!\n"
	.string "상담이 있는데 들어줘어!\l"
	.string "듣고 있지!? 들어야 돼!!\l"
	.string "내 포켓몬 뭘로 하면 좋을까!?\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}\n"
	.string "어느 쪽이 좋을까 자 정해줘!$"
	@ ゥワォ §あさんじゃな-い!?ｎ
	@ どうする オレ? そうだんしてみる!?ｌ
	@ って もう はなしかけてる!?ｐ
	@ オスっ ひさしぶり ですっ!ｎ
	@ そうだんが あるんだけど きいてェ!ｌ
	@ って きいてる!? きいてる!!ｌ
	@ オレの ポケモン なにに したらいいかな!ｐ
	@ §いと §うｎ
	@ どっちが いいか さあ きめて!

gText_ApprenticeMonThanks12:: @ 82BF6E5
	.string "{STR_VAR_1}{K_I}라고오오!\n"
	.string "그럼 빠르게 찾아보겠습니다!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!$"
	@ §いだってエェ!ｎ
	@ じゃ さっそく さがしてみるよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeWhichMon13:: @ 82BF773
	.string "{PLAYER}{K_I}구나\n"
	.string "나 머리가 아파서 말야...\p"
	.string "어느 포켓몬으로 할지\n"
	.string "고민을 너무 한 걸 거야 분명\l"
	.string "그러니까 말야\l"
	.string "나 대신 정해주라!\p"
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중\l"
	.string "어느 쪽이 내 포켓몬에 어울릴까?$"
	@ §あ§おかぁｎ
	@ おれ あたま いたくてさ……ｐ
	@ どの ポケモンに するかｎ
	@ なやみ すぎちゃったん だよね きっとｌ
	@ というわけ だからさｌ
	@ かわりに きめて くれよ!ｐ
	@ §あ§おはさ おれの ポケモンｎ
	@ §いと §う だったらｌ
	@ どっちが あってると おもうかい?

gText_ApprenticeMonThanks13:: @ 82BF869
	.string "응 알았어 {STR_VAR_1}{K_I}구나!\n"
	.string "그럼 컨디션이 좋을 때\l"
	.string "찾아볼게!\p"
	.string "앞으로도 나를 잘 부탁해!$"
	@ ん わかった §いな!ｎ
	@ じゃあ たいちょうの いいときにｌ
	@ さがしてみるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeWhichMon14:: @ 82BF8DD
	.string "아... 아...\n"
	.string "{PLAYER} 맞지...?\l"
	.string "그 그렇게 보지 말아주게!\l"
	.string "부끄럽단 말일세\l"
	.string "잠깐... 상담 좀 해주게나\p"
	.string "부 부끄럽지만 말일세!\n"
	.string "쓸 포켓몬을 뭘로 할지 고민 중이라네\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중\n"
	.string "어느 쪽을 쓰면 좋겠나...?$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｌ
	@ ちょっと…… そうだん させて くれよｐ
	@ は はずかしいん だけどさ!ｎ
	@ つかいたい ポケモンで なやんでててさｌ
	@ §いと §うだったらｌ
	@ どっちを つかったら いい かな……?

gText_ApprenticeMonThanks14:: @ 82BF9BA
	.string "아 알겠네!\n"
	.string "{STR_VAR_1}{K_EU}로 힘내보지\p"
	.string "으으 부끄러움 안 타고\n"
	.string "열심히 할 수 있을까...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 보면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ §いで がんばって みるよｐ
	@ うう はずかし がらずにｎ
	@ がんばれる かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeWhichMon15:: @ 82BFA5A
	.string "응?\n"
	.string "{PLAYER}처럼 보인다만...\l"
	.string "진짜인가?\p"
	.string "아니 진짜라면 됐네\n"
	.string "그리고 제자인 내게\l"
	.string "조언을 부탁하네!\p"
	.string "내가 쓸 포켓몬 말이다만\n"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 중\l"
	.string "어느 쪽이 내게 어울리나?$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんもの なのかね?ｐ
	@ いや ほんもの なら いいんだｎ
	@ ついでに でしの わたしにｌ
	@ じょげんを おねがい したい!ｐ
	@ わたしが つかう ポケモンの ことだがｎ
	@ §いと §うであればｌ
	@ どちらが わたしに ふさわしい かな?

gText_ApprenticeMonThanks15:: @ 82BFB4E
	.string "{STR_VAR_1}... 자네 맞나?\p"
	.string "아니 진짜라면 됐네\n"
	.string "정말 고맙네\l"
	.string "이런 나라도\l"
	.string "잘 쓸 수 있으면 좋겠군\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ §い…… ほんとうかね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｌ
	@ こんな わたし でもｌ
	@ なんとか つかい こなせると いいなｐ
	@ では いずれまた あおう!

gText_ApprenticeWhichMove0:: @ 82BFBF2
	.string "으앙- {PLAYER}님!\n"
	.string "훌쩍... 히끅\l"
	.string "저 어떻게 하면 좋을지 모르겠어요!\l"
	.string "제 {STR_VAR_1}한테 기술을\l"
	.string "뭘 가르칠지 못 정하고 있거든요...\p"
	.string "저기 그래서 말인데요!\n"
	.string "{PLAYER}님이 정해주시면 안 될까요?\p"
	.string "{STR_VAR_1}의 기술\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중에서\l"
	.string "어느 게 더 좋을까요...?$"
	@ うわ-ん §あさんだ!ｎ
	@ ぐすん ひっくｌ
	@ ぼく なやんで いるんですよう!ｌ
	@ ぼくの §いのね わざがｌ
	@ なかなか きまらないん です……ｐ
	@ あのう あのう!ｎ
	@ §あさん きめて もらえませんか?ｐ
	@ §いの わざｎ
	@ §うと §えならｌ
	@ どっちが いいんでしょう……?

gText_ApprenticeMoveThanks0:: @ 82BFCAE
	.string "{STR_VAR_1} 말이죠!\n"
	.string "으흑 으아아아앙!\p"
	.string "앗! 죄송합니다\n"
	.string "{PLAYER}님이 기술을\l"
	.string "정해주신 게 기뻐서 그만 눈물이...\p"
	.string "...훌쩍\n"
	.string "감사합니다!\l"
	.string "또 상담해 주세요!$"
	@ §い ですね!ｎ
	@ うぅ うわああぁん!ｐ
	@ あ! ごめんなさいｎ
	@ §あさんが わざをｌ
	@ きめてくれた うれしさで なみだが……ｐ
	@ ……グスンｎ
	@ ありがとう ございました!ｌ
	@ また おはなし してください!

gText_ApprenticeWhichMove1:: @ 82BFD26
	.string "{PLAYER} 선생님 안녕!\n"
	.string "또 알려줬으면 하는 게 있어!\p"
	.string "내 {STR_VAR_1}에게\n"
	.string "근사한 기술을 배우게 하고 싶거든!\l"
	.string "그러니까 추천 좀 해줄래?\p"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3}\n"
	.string "좋은 것 좀 골라줘...$"
	@ §あせんせい こんにちは!ｎ
	@ また おしえて ほしいことが あるの!ｐ
	@ ぼくの §いにｎ
	@ かっこいい わざを おしえたいの!ｌ
	@ おすすめは どっちかな?ｐ
	@ §うか §えがｎ
	@ いいんだけど……

gText_ApprenticeMoveThanks1:: @ 82BFDB1
	.string "{STR_VAR_1} 말이지! 역시나-!\n"
	.string "그럼 나 그 기술로 해볼게!\p"
	.string "다음에 또 여기서 만나면\n"
	.string "뭔가 더 알려줘 선생님!$"
	@ §いか! そ-だよね!ｎ
	@ じゃあ ボク それで いくね!ｐ
	@ また こんど ここで あったらｎ
	@ なにか おしえてね せんせい!

gText_ApprenticeWhichMove2:: @ 82BFE24
	.string "{PLAYER}님 안녕하세요!\n"
	.string "제 {STR_VAR_1} 말인데요\l"
	.string "기술을 뭘 가르칠지 고민이에요\p"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\n"
	.string "어느 기술이 더 강할지 모르겠어서...\p"
	.string "{STR_VAR_1}에게는 어느 기술이\n"
	.string "더 어울린다고 생각하세요?$"
	@ §あさん こんにちは!ｎ
	@ ぼくの §いの こと なんだけどｌ
	@ わざの ことで なやんでるんですｐ
	@ §う と §えｎ
	@ どっちの わざが つよいのか……ｐ
	@ §いには どっちの わざがｎ
	@ あってると おもいますか?

gText_ApprenticeMoveThanks2:: @ 82BFEAD
	.string "{STR_VAR_1} 말이죠!\n"
	.string "알겠습니다!\p"
	.string "좋았어 바로\n"
	.string "{STR_VAR_1}{K_EULREUL} 배우게 해야지!\p"
	.string "그럼 다음에 봬요!$"
	@ §い ですね!ｎ
	@ わかりました!ｐ
	@ よし さっそくｎ
	@ §いを おぼえさせるぞ!ｐ
	@ じゃあ また!

gText_ApprenticeWhichMove3:: @ 82BFF0A
	.string "아아 {PLAYER}님!\n"
	.string "저 말이죠 정말로 글러먹었어요!\p"
	.string "포켓몬을 한번 키워보려고 했는데\n"
	.string "...기술 하나도 제대로 못 정하겠어서\l"
	.string "이러지도 저러지도 못하는 중이에요...\p"
	.string "{PLAYER}님에겐 그런 것 따윈\n"
	.string "어찌 되든 상관없다는 건 알고 있습니다...\l"
	.string "하지만 저는...\p"
	.string "부탁이에요 {PLAYER}님\n"
	.string "제 {STR_VAR_1}의 기술을\l"
	.string "정해주시면 안 될까요?\p"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\n"
	.string "하나만 선택이라도 해주세요!$"
	@ ああ §あさん!ｎ
	@ あたし あたし ほんと ダメなんです!ｐ
	@ ポケモンを いざ そだてようと してもｎ
	@ ……わざ ひとつ まともに きめられなくてｌ
	@ どうしようも ありません……ｐ
	@ §あさんには そんな ことｎ
	@ どうでも いいのは わかってます……ｌ
	@ でも あたし……ｐ
	@ おねがいです §あさんｎ
	@ あたしの §いの わざｌ
	@ きめて いただけませんか?ｐ
	@ §うと §えかｎ
	@ どちらかを えらんで くださるだけでも!

gText_ApprenticeMoveThanks3:: @ 82C0032
	.string "알겠습니다!\p"
	.string "저 같은 걸 위해서\n"
	.string "{STR_VAR_1}{K_EULREUL} 배워줄지...\l"
	.string "아니죠! 열심히 해볼게요\p"
	.string "정말 감사합니다!$"
	@ わかりました!ｐ
	@ あたし なんかの ためにｎ
	@ §いを おぼえて くれるか……ｌ
	@ いえ! がんばって みますｐ
	@ ありがとう ございます!

gText_ApprenticeWhichMove4:: @ 82C0090
	.string "어머 {PLAYER}!\n"
	.string "만나고 싶다고 생각하고 있었는데!\l"
	.string "내 {STR_VAR_1}에게 걸맞은 기술은\l"
	.string "뭘까- 하고 고민 중이었거든...\l"
	.string "네가 정해주지 않을래?\p"
	.string "어디 보자...\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\l"
	.string "어느 게 더 좋다고 생각해?$"
	@ あら! §あ§おｎ
	@ あいたいと おもって いたの!ｌ
	@ わたしの §いに ふさわしい わざはｌ
	@ なにかな- って まよってて……ｌ
	@ あなたが きめて くれない?ｐ
	@ そうね……ｎ
	@ §うと §えだったらｌ
	@ どっちが いいと おもう?

gText_ApprenticeMoveThanks4:: @ 82C016E
	.string "{STR_VAR_1} 말이지 고마워!\n"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ §いね ありがと!ｎ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeWhichMove5:: @ 82C01F7
	.string "아- 바쁘다 바빠!\n"
	.string "어이쿠 넌 {PLAYER}{K_I}잖아!\l"
	.string "상태는 어때?\p"
	.string "난 말이지! 아침에 일어나자마자\n"
	.string "조깅에 스위밍에 쿠킹에\l"
	.string "바빠서 정신이 없을 지경이라고...!\p"
	.string "그래서 내 {STR_VAR_1}에게\n"
	.string "배우게 할 기술도 못 정했어-\p"
	.string "그래서 말인데!\n"
	.string "{STR_VAR_2} 좋아보이지 않아?\l"
	.string "근데 {STR_VAR_3}도 좋단 말이지!\p"
	.string "{PLAYER}의 어드바이스 부탁할게!\n"
	.string "어느 기술이 더 좋을까?$"
	@ あ- いそがしい いそがしい!ｎ
	@ おっと きみは §あ§お!ｌ
	@ ちょうしは どう?ｐ
	@ こっちはさ! けさ おきてからｎ
	@ ジョギング スイミング クッキングｌ
	@ いそがしいの なんのって……!ｐ
	@ オレの §いにｎ
	@ おしえさせる わざも きまんなくてね-ｐ
	@ あのさ!ｎ
	@ §う って よさそうじゃん?ｌ
	@ でも §え も イイよね!ｐ
	@ §あ§おの アドバイス たのむよ!ｎ
	@ どっちの わざが イイかな?

gText_ApprenticeMoveThanks5:: @ 82C034C
	.string "오케이 알았어!\n"
	.string "그럼 스케쥴 비워서\l"
	.string "배우게 해볼게!\p"
	.string "넌 정말 좋은 선생님이라니까\n"
	.string "땡큐! 다음에 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ じゃ スケジュ-ル あけてｌ
	@ おぼえさせて みるぜ!ｐ
	@ ほんと きみって いい せんせい だぜｎ
	@ サンキュ-! じゃ またな!

gText_ApprenticeWhichMove6:: @ 82C03CA
	.string "오옷 럭키!\n"
	.string "{PLAYER}님을 만났군요-!\l"
	.string "그럼 바로 질문 들어갑니다-!\p"
	.string "엣헴 그럼\n"
	.string "오늘의 상담!\p"
	.string "제 {STR_VAR_1}에게는\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\l"
	.string "어느 기술이 더 어울릴까요?$"
	@ おおっ ラッキ-!ｎ
	@ §あさんに あえました-!ｌ
	@ さっそく ききたいことが あるの-!ｐ
	@ ジャ-ン ではｎ
	@ ほんじつの そうだんで-す!ｐ
	@ わたしの §いにはｎ
	@ §うと §えｌ
	@ おにあいの わざは さあどっち?

gText_ApprenticeMoveThanks6:: @ 82C046E
	.string "흐으음-\n"
	.string "{STR_VAR_1}{K_IGA} 좋단 말입니까!\l"
	.string "깔끔한 대답 고마워!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ ははぁ-んｎ
	@ §い が イイですか!ｌ
	@ シブイ おこたえ ありがとう!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeWhichMove7:: @ 82C04F9
	.string "그간 평안하셨는지요 {PLAYER}님...!\n"
	.string "저기 있죠 저 오늘도\l"
	.string "상담드릴 게 있답니다\l"
	.string "제 귀여운\l"
	.string "{STR_VAR_1}에 대한 거예요\p"
	.string "{STR_VAR_1}에게 딱 맞는 기술...\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\l"
	.string "어느 것을 가르쳐야 괜찮을까요?$"
	@ ごきげんよう §あさん……!ｎ
	@ あのね きょうもｌ
	@ わたくし そうだんが あるのですｌ
	@ わたくしの かわいいｌ
	@ §いちゃんの ことですのｐ
	@ §いちゃんに ピッタリの わざ……ｎ
	@ §うと §えのｌ
	@ どちらを おしえたら よろしいでしょう?

gText_ApprenticeMoveThanks7:: @ 82C0598
	.string "{STR_VAR_1} 말이군요!\n"
	.string "신속히 그렇게 할게요!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "안녕히 계세요!$"
	@ §い ですのね!ｎ
	@ さっそく そのように しますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeWhichMove8:: @ 82C0602
	.string "꺄아아 {PLAYER}님이 있잖아-!\n"
	.string "가 감격이야...!\l"
	.string "곤란할 때는 역시 {PLAYER}님이 최고죠!\p"
	.string "오늘은 기술 추천을\n"
	.string "해주셨으면 좋겠어요!\l"
	.string "제 {STR_VAR_1}의 기술을\l"
	.string "정해주세요!\p"
	.string "어느 쪽이 좋을까요?\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중에서요!$"
	@ キャァァ §あさんが いる-っ!ｎ
	@ かっ かんげきっ……!ｌ
	@ こまった ときは §あさんですっ!ｐ
	@ ほんじつは わざの オススメをｎ
	@ おしえて ほしいのですっ!ｌ
	@ わたしの §いの わざをｌ
	@ きめて くださいっ!ｐ
	@ どっちが いいですかっ?ｎ
	@ §うと §え!

gText_ApprenticeMoveThanks8:: @ 82C06D8
	.string "가가가 감사합니닷!\n"
	.string "{STR_VAR_1} 말이죠\l"
	.string "가슴에 새기겠습니다!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 가르쳐 주세요!$"
	@ ああぁ ありがとう ございますっ!ｎ
	@ §い ですねっｌ
	@ りょうかいで ありますっ!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticeWhichMove9:: @ 82C074A
	.string "헬로 {PLAYER} 헬로!\n"
	.string "너 오늘도 아저씨에게\l"
	.string "어드바이스를 좀 해주라 플리즈!\p"
	.string "마이 포켓몬 {STR_VAR_1}에게\n"
	.string "베스트인 기술은 뭘까?\l"
	.string "파박 하고 이겨버릴 거 같은 기술!\p"
	.string "{STR_VAR_2}일까?\n"
	.string "오어 {STR_VAR_3}일까?$"
	@ ハロウ §あ§お ハロウ!ｎ
	@ おじさん きょうも きみにｌ
	@ アドバイスを もらいたいんだ プリ-ズ!ｐ
	@ マイ ポケモン §いのｎ
	@ ベストな わざは なんだろう?ｌ
	@ ババ-っと かてちゃいそうな わざ!ｐ
	@ §う かな?ｎ
	@ オア §え かな?

gText_ApprenticeMoveThanks9:: @ 82C0809
	.string "아-하 {STR_VAR_1} 말이지-\n"
	.string "오-케이 오-케이!\l"
	.string "아저씨 얼른 가르쳐볼게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いね-ｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ザザ-っと おぼえさせるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeWhichMove10:: @ 82C086E
	.string "{PLAYER} 큰일이야!\n"
	.string "내 포켓몬이 무려\l"
	.string "기술을 6개나 배웠다고!\p"
	.string "...농담이야 거짓말이지롱! 하하하!\p"
	.string "실은 나 포켓몬의 기술을 정하는 데\n"
	.string "그다지 일가견이 없어!\l"
	.string "거기서 제안 하나! 스승님이\l"
	.string "기술을 추천해주면 안 될까?\p"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\n"
	.string "{STR_VAR_1}한테 어느 게 더 어울릴까?$"
	@ §あ§お たいへんだぞ!ｎ
	@ おいらの ポケモンが なんとｌ
	@ わざを 6つ おぼえたんだ!ｐ
	@ ……なんてね ウソだよ! ははは!ｐ
	@ じつは おいら ポケモンの わざ きめるのｎ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろ ししょうがｌ
	@ オススメのわざ きめて くれない かな?ｐ
	@ §う と §えｎ
	@ §いなら どっちが あうかい?

gText_ApprenticeMoveThanks10:: @ 82C0982
	.string "그렇구나\n"
	.string "{STR_VAR_1}{K_IGA} 좋단 말이지!\l"
	.string "그럼 다른 기술로 해야겠다!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ ちがうわざに しようっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeWhichMove11:: @ 82C0A1D
	.string "안-녕-하-세-요!\n"
	.string "네 안녕하십니까!\l"
	.string "시원한 선원인 제가 왔습니다-!\p"
	.string "자 오늘의 상담\n"
	.string "가볼까요-!\l"
	.string "기술에 관한 상담입니다!\p"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3}\n"
	.string "{STR_VAR_1}한테 어느 걸 배우게 할까?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしだぜ-!ｐ
	@ よ-し きょうの わしの そうだんｎ
	@ いってみようぜ-!ｌ
	@ わざに かんする そうだんだよ!ｐ
	@ §うと §えｎ
	@ §いが おぼえるなら どっちだ?

gText_ApprenticeMoveThanks11:: @ 82C0AFD
	.string "{STR_VAR_1}입니까-앗! 요요!\n"
	.string "그렇다면 바로 시원하게 가르쳐야지!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで おぼえさせるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeWhichMove12:: @ 82C0B6F
	.string "예이 {PLAYER}님 아냐-?\n"
	.string "어떡하지 나? 또 말 걸어볼까!?\l"
	.string "앗 근데 이미 말 걸고 있잖아!?\l"
	.string "앗 근데 이미 {PLAYER}님이 지쳤잖아!?\l"
	.string "어쩔 수 없지- 상담해볼까!?\p"
	.string "오늘도 상담해줘!\n"
	.string "앗 근데 듣고 있는 거지!?\p"
	.string "내 {STR_VAR_1}의 기술\n"
	.string "어떡하면 좋을까? 정해줘어엇!\l"
	.string "{STR_VAR_2}!? 아니면 {STR_VAR_3}!?$"
	@ イエァ §あさんじゃないの-?ｎ
	@ どうする オレ? また はなしかける!?ｌ
	@ ってもう はなしかけてる!?ｌ
	@ って §あさん あきれてる!?ｌ
	@ しかたね- そうだん してみる!?ｐ
	@ きょうも そうだんに のってェ!ｎ
	@ って きいてる!? きいてる!!ｐ
	@ おれの §いの わざｎ
	@ どうしたら いいかな? きめてエェ!ｌ
	@ §う!? §え!?

gText_ApprenticeMoveThanks12:: @ 82C0C7D
	.string "{STR_VAR_1}{K_EU}로 결정-!\n"
	.string "그럼 바로 가르쳐볼게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!$"
	@ §いで オ-ライ!ｎ
	@ じゃ さっそく おぼえさせるぜェ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeWhichMove13:: @ 82C0D0B
	.string "쿨럭커헉! 아 {PLAYER}\n"
	.string "나 감기 걸렸어...\p"
	.string "포켓몬에게 가르칠 기술을\n"
	.string "정하고 싶은데 이 상태론 어림도 없겠지\l"
	.string "그러니까 나 대신 좀 해주라 부탁할게!\p"
	.string "{PLAYER}{K_EUNNEUN} 말야 내 {STR_VAR_1}에게\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3} 중\l"
	.string "어느 게 더 어울린다고 생각해?$"
	@ ガハゴホ あ §あ§おｎ
	@ カゼ ひいちゃったよ おれ……ｐ
	@ ポケモンに おしえる わざをｎ
	@ きめたいんだけど ムリっぽいん だよねｌ
	@ というわけ だからさ かわりに たのむよ!ｐ
	@ §あ§おはさ おれの §いｎ
	@ §うと §えならｌ
	@ どっちが あってると おもうかい?

gText_ApprenticeMoveThanks13:: @ 82C0DFE
	.string "응 알았어 {STR_VAR_1} 말이지!\n"
	.string "그럼 감기가 나으면\l"
	.string "콜록 가르쳐볼게!\p"
	.string "앞으로도 나를 잘 부탁한다구!$"
	@ ん わかった §いな!ｎ
	@ じゃあ カゼが なおったらｌ
	@ ゴホ おしえて みるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeWhichMove14:: @ 82C0E71
	.string "아... 아...\n"
	.string "{PLAYER} 맞지?\l"
	.string "그 그렇게 보지 말게나!\l"
	.string "부끄럽단 말일세\l"
	.string "또... 상담하게 해주게\p"
	.string "부 부끄럽지만 말일세\n"
	.string "포켓몬에게 가르칠 기술을 말이네\l"
	.string "도저히 못 정하겠으니 어드바이스를 주게!\p"
	.string "포켓몬은 {STR_VAR_1}인데\n"
	.string "그렇다면 어느 쪽이 좋겠나...?\l"
	.string "{STR_VAR_2}... {STR_VAR_3}...$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｌ
	@ また…… そうだん させて くれよｐ
	@ は はずかしながらさｎ
	@ ポケモンに おしえる わざがさｌ
	@ きまんないんだ アドバイス くれよ!ｐ
	@ ポケモンは §いなんだｎ
	@ だったら どっちが いい かな……?ｎ
	@ §う…… §え……

gText_ApprenticeMoveThanks14:: @ 82C0F6D
	.string "아 알겠네 {STR_VAR_1}{K_I}라고\n"
	.string "한번 해보겠네!\p"
	.string "그런 기술을 가르치라니\n"
	.string "부 부끄럽구만...\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 만나면... 잘 부탁하네$"
	@ よ よし §いｎ
	@ いって みるよ!ｐ
	@ そんな わざを おしえるなんてｎ
	@ て てれるな……ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeWhichMove15:: @ 82C1003
	.string "음?\n"
	.string "{PLAYER}처럼 보인다만...\l"
	.string "진짜인가?\l"
	.string "최근 유행하는 흉내내기는 아니겠지?\p"
	.string "아닐세 아닐세! 진짜라면 됐네!\n"
	.string "기분 나빠 하지 말게나!\l"
	.string "그리고 제자인 내게\l"
	.string "조언을 부탁하네!\l"
	.string "내 {STR_VAR_1}에 대한 것일세!\p"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3}\n"
	.string "어느 기술을 써야 좋겠는가?$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんものかな?ｌ
	@ さいきん はやりの モノマネ では?ｐ
	@ いやいや! ほんもの ならいいんだ!ｎ
	@ きを わるく しないでくれ!ｌ
	@ そして ついでに でしの わたしにｌ
	@ じょげんを おねがい したいｌ
	@ わたしの §いの ことだ!ｐ
	@ §う と §えｎ
	@ どっちの わざが つかえたら いいかね?

gText_ApprenticeMoveThanks15:: @ 82C1122
	.string "{STR_VAR_1}...\n"
	.string "틀림없는 거겠지?\p"
	.string "아니 정말이라면 됐네\n"
	.string "정말 고맙군\l"
	.string "이런 나의 포켓몬이라도\l"
	.string "잘 쓸 수 있다면 좋겠어\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ §い……ｎ
	@ まちがいなく そうなの かね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｌ
	@ こんな わたしの ポケモンでもｌ
	@ おぼえて くれると いいなｐ
	@ では いずれまた あおう!

gText_ApprenticePickWinSpeech0:: @ 82C11D1
	.string "아앗 {PLAYER}\n"
	.string "{PLAYER}님이다! 으앙-!\l"
	.string "훌쩍 히끅 제 말 좀 들어주세요\p"
	.string "저 저 말이죠 승부할 때\n"
	.string "엄청나게 긴장해서\l"
	.string "이겨도 울고 말아요...\p"
	.string "뭔가 멋진 말이라도 하면\n"
	.string "나아지지 않을까 싶은데...\p"
	.string "저기 {PLAYER}님\n"
	.string "만약 괜찮다면...\l"
	.string "제가 울지 않을 수 있게\l"
	.string "이겼을 때 할 말을\l"
	.string "생각해주시면 안 될까요?$"
	@ ああっ §あさんｎ
	@ §あさんだ! わわ-ん!ｌ
	@ ぐすん ひっく きいて くださいｐ
	@ ぼくっ ぼく しょうぶ するときｎ
	@ ものすごく きんちょう してｌ
	@ かっても ないちゃうん です……ｐ
	@ なにか かっこいい こと いえたらｎ
	@ いいなと おもうんです けど……ｐ
	@ あのう あのう §あさんｎ
	@ もし よかったら……ｌ
	@ ぼく なかなくて いいようにｌ
	@ なにか かったときに いう ことばをｌ
	@ かんがえて もらえませんか?

gText_ApprenticeWinSpeechThanks0:: @ 82C12D5
	.string "{STR_VAR_1}\p"
	.string "... 우와아아!\n"
	.string "엄청나게 멋져요!\p"
	.string "아 죄송합니다\n"
	.string "너무 기뻐서 눈물이...\p"
	.string "...훌쩍 {PLAYER}님!\n"
	.string "그동안 정말 감사했습니다!\l"
	.string "저 {PLAYER}님을 위해서라도\l"
	.string "계속 열심히 승부해 나갈게요!\p"
	.string "그럼 {PLAYER}님!\n"
	.string "다음엔... 어딘가에서 승부해요!$"
	@ §いｐ
	@ …… うぉぉ-ん!ｎ
	@ すごく かっこいいよう!ｐ
	@ あ ごめんなさいｎ
	@ うれしすぎて なみだが……ｐ
	@ ……グスン §あさん!ｎ
	@ いつも いつも ありがとう ございました!ｌ
	@ ぼく §あさんの ためにもｌ
	@ がんばって たたかい つづけます!ｐ
	@ では §あさん!ｎ
	@ こんどは…… どこかで たたかいましょう!

gText_ApprenticePickWinSpeech1:: @ 82C13AB
	.string "{PLAYER} 선생님 안녕!\n"
	.string "나 정하고 싶은 게 있어!\p"
	.string "저기 있잖아!\n"
	.string "나 승부에서 이겼을 때\l"
	.string "뭔가 멋있는 대사를 하고 싶거든!\p"
	.string "선생님은 추천하고 싶은\n"
	.string "멋있는 대사 같은 거 없어?$"
	@ §あせんせい こんにちは!ｎ
	@ ぼく きめたい ことが あるの!ｐ
	@ あのね!ｎ
	@ ぼく しょうぶに かった ときｌ
	@ なにか かっこいい セリフを いいたいの!ｐ
	@ せんせい おすすめのｎ
	@ かっこいい セリフって あるかな?

gText_ApprenticeWinSpeechThanks1:: @ 82C1444
	.string "{STR_VAR_1}\p"
	.string "우와아- 좋다-!\n"
	.string "그럼 나 그걸로 할게!\p"
	.string "선생님 지금까지 고마웠어!\n"
	.string "나 이제부터 다양한 곳에서\l"
	.string "열심히 할게!\p"
	.string "다음에 만날 때는 승부야!$"
	@ §いｐ
	@ うわあ- い-ね!ｎ
	@ じゃあ ボク それで いくね!ｐ
	@ せんせい いままで ありがとう!ｎ
	@ ボク これから いろんな ところでｌ
	@ がんばる ことに する!ｐ
	@ こんど あうときは しょうぶ だよ!

gText_ApprenticePickWinSpeech2:: @ 82C1501
	.string "{PLAYER}님 안녕하세요!\n"
	.string "포켓몬 배틀의 준비는\p"
	.string "완벽하게 끝났지만\n"
	.string "하나 고민이 있어서요\p"
	.string "포켓몬 트레이너니까\n"
	.string "승부에서 이겼을 때의 대사가\p"
	.string "있으면 좋겠다는 생각이 듭니다\n"
	.string "뭔가 좋은 대사를 생각해주세요!$"
	@ §あさん こんにちは!ｎ
	@ ポケモンの じゅんびはｐ
	@ ばんぜん なんですけどｎ
	@ ひとつ きに なってるんですｐ
	@ ポケモントレ-ナ-ってｎ
	@ しょうぶに かった ときに かけごえ がｐ
	@ あると いいかな-って おもうんですｎ
	@ なにか いいの かんがえて ください!

gText_ApprenticeWinSpeechThanks2:: @ 82C15B6
	.string "{STR_VAR_1}\p"
	.string "...멋지네요!\n"
	.string "그 대사를 쓰도록 하겠습니다!\p"
	.string "그럼 저는 앞으로\n"
	.string "다양한 곳에서 승부해 볼게요!\p"
	.string "언젠가 {PLAYER}님과도\n"
	.string "승부하는 날이\l"
	.string "찾아올지도 모르겠네요!\p"
	.string "그럼 다음엔 승부의 장에서\n"
	.string "만납시다!$"
	@ §いｐ
	@ ……かっこいいですね!ｎ
	@ それ つかわせて いただきます!ｐ
	@ じゃあ ぼくは これからｎ
	@ いろんな ところで しょうぶ してきます!ｐ
	@ いつか §あさんとｎ
	@ しょうぶ する ひがｌ
	@ くるかも しれませんね!ｐ
	@ では こんどは しょうぶの ば でｎ
	@ おあい しましょう!

gText_ApprenticePickWinSpeech3:: @ 82C165E
	.string "앗 {PLAYER}님...!\n"
	.string "전 정말로 쓸모없는 여자애예요!\p"
	.string "모처럼...\n"
	.string "모처럼 승부에서 이겼는데도\l"
	.string "말이 한마디도 안 나와서...\p"
	.string "{PLAYER}님에게 그런 건\n"
	.string "어찌 되든 좋은 일인 거 알아요!\l"
	.string "하지만 저는 무슨 일이 있더라도...\p"
	.string "부탁이에요! {PLAYER}님\n"
	.string "이겼을 때에\l"
	.string "무슨 말을 하면 좋을까요...?$"
	@ あっ §あさん……!ｎ
	@ あたし ほんと ダメな おんなのこです!ｐ
	@ せっかく……ｎ
	@ せっかく しょうぶに かってもｌ
	@ ことば ひとつ でてこなくって……ｐ
	@ §あさんには そんな ことｎ
	@ どうでも いいのは わかってます!ｌ
	@ でも あたし どうしても……ｐ
	@ おねがい! です §あさんｎ
	@ かったとき ってｌ
	@ なんて いうべき なんでしょうか……?

gText_ApprenticeWinSpeechThanks3:: @ 82C174F
	.string "{STR_VAR_1}\p"
	.string "굉장해...\p"
	.string "저 저 따위가\n"
	.string "그런 말을 해도 괜찮을까요...\l"
	.string "아니죠! 열심히 하겠습니다\p"
	.string "{PLAYER}님!\p"
	.string "지금까지 저 따위를 위해\n"
	.string "힘써주셔서... 감사했습니다...!\l"
	.string "저 이제부터 열심히 할게요!\p"
	.string "저 따위는\n"
	.string "금방 잊어버리실지도 모르지만\l"
	.string "그래도 어딘가에서 또 만나요!$"
	@ §いｐ
	@ すごいわ……ｐ
	@ あ あたしなんかがｎ
	@ そんな こと いって いいのか……ｌ
	@ いえ! がんばって みますｐ
	@ §あさん!ｐ
	@ いままで あたしなんかの ためにｎ
	@ ありがとう…… ございました……!ｌ
	@ あたし いまから がんばってきます!ｐ
	@ あたしの こと なんてｎ
	@ すぐに わすれて しまうと おもうけどｌ
	@ でも どこかで おあい しましょう!

gText_ApprenticePickWinSpeech4:: @ 82C1862
	.string "어머 {PLAYER}?\n"
	.string "잠깐 내 말 좀 들어줘!\p"
	.string "스스로도 알고는 있었지만\n"
	.string "난 정말 말버릇이 나빠서...\l"
	.string "승부에서 이겼을 때에\l"
	.string "잘난 척을 너무 한단 말이지!\p"
	.string "그치만 미움받고 싶진 않으니까\n"
	.string "나한테 진 상대에게\l"
	.string "부드럽게 말해주고 싶어!\p"
	.string "하지만 전혀 생각이 안 나!\n"
	.string "당신이 생각해 줄래?$"
	@ あら §あ§お?ｎ
	@ ちょっと きいて ほしいんだけど!ｐ
	@ じぶんでも わかって いるけどｎ
	@ わたし すこし くちが わるくて……ｌ
	@ しょうぶに かったときにｌ
	@ なんか えらそうに しちゃうのよね!ｐ
	@ だけど きらわれたく ないからｎ
	@ わたしに まけた あいてにｌ
	@ やさしい ことばを かけて あげたいのよ!ｐ
	@ でも ぜんぜん おもいつかなくて!ｎ
	@ あなたが かんがえて くれない?

gText_ApprenticeWinSpeechThanks4:: @ 82C19A0
	.string "{STR_VAR_1}\p"
	.string "나쁘지 않은데!\n"
	.string "음 그걸로 가야겠다!\p"
	.string "그럼... 여태까지\n"
	.string "{PLAYER}에게 배운\l"
	.string "다양한 것들을 가슴에 품고\l"
	.string "나 열심히 해볼게!\l"
	.string "이런저런 실례를 끼쳐서\l"
	.string "정말 미안했어!\p"
	.string "다음에 만날 때는 승부야!\n"
	.string "그럼 안녕!$"
	@ §いｐ
	@ わるく ないわね!ｎ
	@ うん それで いくことに するわ!ｐ
	@ じゃあ…… いままでｎ
	@ §あさんに おそわったｌ
	@ いろいろな ことを むねにｌ
	@ わたし がんばって くる!ｌ
	@ いろいろと なまいき いってｌ
	@ ごめんなさい!ｐ
	@ つぎに あう ときは しょうぶよ!ｎ
	@ じゃあね!

gText_ApprenticePickWinSpeech5:: @ 82C1A76
	.string "아- 바쁘다 바빠!\n"
	.string "어이쿠 찾고 있었다고 {PLAYER}\l"
	.string "오늘도 건강해?\p"
	.string "난 말이지-! 변함없이\n"
	.string "러닝에 파이팅에 매핑에...\l"
	.string "말이 안 될 정도로 바쁘다?\p"
	.string "하지만! 바쁘다고 해서\n"
	.string "승부에서 이겼을 때에\l"
	.string "아무 말도 안 하고\l"
	.string "가버리는 건 실례잖아?\p"
	.string "그래서 말인데!\n"
	.string "이긴 뒤 떠나는 나를\l"
	.string "멋있게 연출해줄 좋은 대사 없을까?\l"
	.string "{PLAYER} 뭐라도 부탁할게!$"
	@ あ- いそがしい いそがしい!ｎ
	@ おっと さがしてたよ §あ§おｌ
	@ きょうも げんきかい?ｐ
	@ こっちはさ-! あいかわらずｎ
	@ ランニング ファイティング マッピングとｌ
	@ なんで こんなに いそがしいんだ?ｐ
	@ でもさ! いそがしい からってｎ
	@ しょうぶに かった ときにｌ
	@ なにも いわないでｌ
	@ たちさっちゃ しつれいだろ?ｐ
	@ でさ!ｎ
	@ かっこよく たちさる オレをｌ
	@ えんしゅつする いい ことば ないかな?ｌ
	@ §あ§お なんか たのむよ!

gText_ApprenticeWinSpeechThanks5:: @ 82C1C16
	.string "{STR_VAR_1}\p"
	.string "오케이 알았어!\n"
	.string "그 정도 말을 할 시간은 있지!\l"
	.string "정말이지 너처럼\l"
	.string "좋은 선생님을 만나서 다행이야!\p"
	.string "난 이제부터 시간을 내서\n"
	.string "포켓몬 승부를 할게!\l"
	.string "지금까지 도와줘서 땡큐 {PLAYER}!\p"
	.string "언젠가 나하고 승부하자고!$"
	@ §いｐ
	@ オ-ケ- わかった!ｎ
	@ そのぐらい いう じかんは つくれるぜ!ｌ
	@ ほんと きみ みたいなｌ
	@ いい せんせいに であえて よかったぜ!ｐ
	@ オレは これから じかんを つくってｎ
	@ ポケモンしょうぶを してくるよ!ｌ
	@ いままで サンキュ- §あ§お!ｐ
	@ いつか オレと しょうぶ しようぜ!

gText_ApprenticePickWinSpeech6:: @ 82C1CF5
	.string "해냈다-!\n"
	.string "{PLAYER}님을 만났어!\l"
	.string "바로 상담하고 싶은 게 있었거든!\p"
	.string "자-\n"
	.string "그럼 마지막 상담입니다-!\p"
	.string "나 승부에서 이겼을 때\n"
	.string "멋있게 대사를 딱 날리고 싶은데\l"
	.string "뭐라고 하면 좋을까?$"
	@ やったね-っｎ
	@ §あさんに あえちゃった!ｌ
	@ さっそく そうだんが あるのよ!ｐ
	@ ジャ-ンｎ
	@ では さいごの そうだん で-す!ｐ
	@ わたしが しょうぶで かった ときｎ
	@ かっこよく キメたいと したらｌ
	@ さあ なんて いえばいい?

gText_ApprenticeWinSpeechThanks6:: @ 82C1DC1
	.string "{STR_VAR_1}\p"
	.string "너무 좋다!\n"
	.string "멋있어! 그걸로 할게!\p"
	.string "...저기 나 말이지\n"
	.string "이제 1인분은 할 수 있게 됐어!\p"
	.string "그래서 앞으로도 여러 사람과\n"
	.string "배틀해 보려고!\p"
	.string "{PLAYER}님의 어드바이스\n"
	.string "엄청 도움이 됐어-!\l"
	.string "언젠가 승부할지도 모르겠다\l"
	.string "여태까지 정말 고마웠어-!$"
	@ §いｐ
	@ いっ イイ!ｎ
	@ シブイ! それいただき!ｐ
	@ ……ねえ わたしｎ
	@ そろそろ いちにんまえに なったよね!ｐ
	@ あのね これから いろんなひととｎ
	@ たたかって みようと おもうの!ｐ
	@ §あさんの アドバイスｎ
	@ すっごく たすかったよ-!ｌ
	@ いつか しょうぶする ときが くるかもねｌ
	@ いままで ほんと ありがと-!

gText_ApprenticePickWinSpeech7:: @ 82C1EDC
	.string "어머 {PLAYER}님\n"
	.string "만나 뵙게 되어 다행이에요...!\p"
	.string "제 포켓몬에는\n"
	.string "이제 문제가 없습니다만\l"
	.string "제 자신에겐 있는지라...\p"
	.string "그게 포켓몬 트레이너분들은\n"
	.string "모두 승부에서 이겼을 때\l"
	.string "하는 대사가 있더라고요?\p"
	.string "저도 꼭! 그런 대사를\n"
	.string "말해 보고 싶어요!\l"
	.string "부탁이에요! 뭐라도\l"
	.string "승리했을 때의 대사를 정해 주세요!$"
	@ まあ §あさんｎ
	@ あえて よかった ですわ……!ｐ
	@ わたくし ポケモンの ほうはｎ
	@ もう しんぱい ないのです けれどｌ
	@ わたくし じしんの ほうが……ｐ
	@ その あの ポケモントレ-ナ-さんはｎ
	@ いつも しょうぶに かったときｌ
	@ ことばを かけて くださいますね?ｐ
	@ ぜひ! わたくしも あれをｎ
	@ やってみたいのです!ｌ
	@ おねがいです! なにかｌ
	@ かったときの ことば きめて ください!

gText_ApprenticeWinSpeechThanks7:: @ 82C1FEC
	.string "{STR_VAR_1}\p"
	.string "라고 하면 되는군요...!\p"
	.string "아아! 저 왠지\n"
	.string "다시 태어난 듯한 기분이 들어요...!\l"
	.string "바로 그 말을 써 보도록 하겠습니다!\p"
	.string "그럼 이만 가 볼게요...\n"
	.string "{PLAYER}님께서 알려 주신 것을\l"
	.string "결코 잊지 않고\l"
	.string "다양한 분들과 배틀하도록 하겠습니다!\p"
	.string "언젠가 또 봬요...\n"
	.string "감사했어요!$"
	@ §いｐ
	@ ですのね……!ｐ
	@ ああ! なんだか わたくしｎ
	@ うまれかわれる きが しますわ……!ｌ
	@ さっそく そのことば つかってみますわ!ｐ
	@ それでは ここで おわかれです……ｎ
	@ §あさんの ごしどうｌ
	@ わたくし けっして わすれずにｌ
	@ みなさまと たたかって まいります!ｐ
	@ また いずれ……ｎ
	@ ごきげんよう!

gText_ApprenticePickWinSpeech8:: @ 82C20D1
	.string "꺄아-!\n"
	.string "{PLAYER}님 발-견!\l"
	.string "가 감격이야...!\p"
	.string "저기 상담할 게 있어요!\p"
	.string "지난번에 포켓몬 승부에서\n"
	.string "이기긴 했는데 말이죠!\l"
	.string "저 너무 감격한 나머지\l"
	.string "아무 말도 못 했거든요...!\p"
	.string "그래서 말인데요 {PLAYER}님!\n"
	.string "제가 이겼을 때의 결정타 대사 있죠!\l"
	.string "뭘로 할지 정해주세요!$"
	@ キャァ-!ｎ
	@ §あさんを はっけん-っ!ｌ
	@ かっ かんげきっ……!ｐ
	@ あのっ そうだんが あります!ｐ
	@ このあいだ ポケモンしょうぶにｎ
	@ かったは いいんですけど!ｌ
	@ わたし かんげき しすぎちゃってｌ
	@ なんにも いえなく なっちゃって……!ｐ
	@ そこで §あさん!ｎ
	@ わたしが かった ときの きめぜりふ!ｌ
	@ かんがえて ほしいのですっ!

gText_ApprenticeWinSpeechThanks8:: @ 82C21FF
	.string "{STR_VAR_1}\p"
	.string "우 우와아아아아아!\n"
	.string "이런 말을 제가요!?\l"
	.string "가 감격했어요...!!\p"
	.string "가가가 감사합니다!\n"
	.string "이제 궁금한 건 없어요!\l"
	.string "저 앞으로는 새출발해서\l"
	.string "다양한 사람과 승부해 볼게요!\p"
	.string "모두 {PLAYER}님\n"
	.string "덕분이에요!\l"
	.string "정말 감사드립니다!\p"
	.string "자 그럼\n"
	.string "언젠가 승부의 장에서 봐요!$"
	@ §いｐ
	@ う うわああぁぁあ!ｎ
	@ この ことばを わたしが!ｌ
	@ かっ かんげき………っ!!ｐ
	@ あああ ありがとう ございますっ!ｎ
	@ もう おもいのこす ことは ありませんっ!ｌ
	@ わたし これから たびだってｌ
	@ いろいろな ひとと しょうぶ してみます!ｐ
	@ なにもかも §あさんのｎ
	@ おかげで あります!ｌ
	@ ほんとうに ありがとう ございますっ!ｐ
	@ それでは それではｎ
	@ いつか しょうぶの ばで あいましょう!

gText_ApprenticePickWinSpeech9:: @ 82C231C
	.string "헬로-\n"
	.string "헬로 {PLAYER}!\p"
	.string "아저씨 슬슬 이곳저곳에서\n"
	.string "승부하고 싶어졌어!\l"
	.string "그래서 그 전에 네게\l"
	.string "어드바이스를 받고 싶어 플리즈!\p"
	.string "아저씨가 승부에서 이겼을 때\n"
	.string "상대 트레이너를 향해서\l"
	.string "뭐라고 자랑하면 좋을까?$"
	@ ハッロ-ウｎ
	@ ハロウ §あ§お!ｐ
	@ おじさん そろそろ あちこちでｎ
	@ しょうぶが したく なって きたよ!ｌ
	@ そこで そのまえに きみにｌ
	@ アドバイスを もらいたいんだ プリ-ズ!ｐ
	@ おじさんが もし しょうぶに かったらｎ
	@ あいての トレ-ナ-に むかってｌ
	@ じまん するような ことばって ないかな?

gText_ApprenticeWinSpeechThanks9:: @ 82C2407
	.string "{STR_VAR_1}\p"
	.string "아하 그거 좋네\n"
	.string "오케이 오케이!\l"
	.string "아저씨 팍팍 말해볼게!\p"
	.string "그럼 이제 작별이네!\n"
	.string "지금까지 여러모로 고마웠어\l"
	.string "언젠가 승부도 해주라!\p"
	.string "아디오스-!$"
	@ §いｐ
	@ あはぁ それいいねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ババ-っと いってみるよ!ｐ
	@ それじゃあ おわかれだ!ｎ
	@ いままで いろいろ ありがとうねｌ
	@ いつか しょうぶも してくれよ!ｐ
	@ アディオ-ス!

gText_ApprenticePickWinSpeech10:: @ 82C24B5
	.string "{PLAYER} 들어봐 큰일이라고-!\p"
	.string "나 승부에서 이기면\n"
	.string "1시간이나 자랑해버린단 말야!\p"
	.string "...농담이야 농담! 으하하\p"
	.string "실은 나 다른 사람하고 대화를\n"
	.string "그다지 잘하지 못하거든!\l"
	.string "거기서 제안 하나!\l"
	.string "내가 승부에서 이겼을 때\l"
	.string "하면 좋을 거 같은 대사를\l"
	.string "스승님이 정해주지 않을래?$"
	@ §あ§お たいへんだ-っ!ｐ
	@ おいら しょうぶに かつとｎ
	@ 1じかんも えばっちゃうんだ!ｐ
	@ ……なんてね ウソなんだよ! うっははｐ
	@ じつは おいら ひとと はなし するのｎ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろｌ
	@ おいらが しょうぶに かったときにｌ
	@ いう ことばをｌ
	@ ししょうが きめて くれない かな?

gText_ApprenticeWinSpeechThanks10:: @ 82C25B1
	.string "{STR_VAR_1}\p"
	.string "직접 말해보니 좋은걸!\n"
	.string "그럼 이 대사만큼은 피해야겠다!\p"
	.string "...농담이야 농담!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "여태까지 정말 고마웠어 스승님!\n"
	.string "나 드디어 트레이너가 뭔지\l"
	.string "이해한 거 같아!\p"
	.string "이제부터 다양한 녀석들과\n"
	.string "승부해서 이기고 올게!\l"
	.string "스승님하고 승부하게 될지도 몰라!\p"
	.string "그럼 이만!\n"
	.string "작별이야 스승님!$"
	@ §いｐ
	@ こう いえば いいのね!ｎ
	@ じゃあ それだけは やめておこうっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ずっとずっと ありがとう ししょう!ｎ
	@ おいら やっと トレ-ナ-って もんがｌ
	@ わかった きがするよ!ｐ
	@ いまから いろんな やつとｎ
	@ しょうぶして かって くるぞ!ｌ
	@ ししょう とも しょうぶ するかもな!ｐ
	@ それじゃな!ｎ
	@ さらばだ ししょう!

gText_ApprenticePickWinSpeech11:: @ 82C2707
	.string "안-녕-하-세-요!\n"
	.string "네 안녕하십니까!\l"
	.string "시원한 선원인 제가 왔습니다-!\p"
	.string "자 마지막 상담\n"
	.string "시작해볼까요-!\l"
	.string "대사에 관한 상담인데요!\p"
	.string "제가 만약 승부에서 이기면\n"
	.string "어떤 대사를 날리는 게 좋을까요?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしだぜ-!ｐ
	@ よ-し さいごの わしの そうだんｎ
	@ いってみようぜ-!ｌ
	@ ことばに かんする そうだんだよ!ｐ
	@ わしが もし しょうぶで かったらｎ
	@ どういう ことばで キメたら いいかな?

gText_ApprenticeWinSpeechThanks11:: @ 82C27D4
	.string "{STR_VAR_1}\p"
	.string "과연-! 요요!\n"
	.string "그렇다면 시원하게 써보도록 하죠!\p"
	.string "저 슬슬 독립하겠습니다\n"
	.string "시원하게 마구 싸워볼게요!\l"
	.string "여러모로 감사했어요!\p"
	.string "고-생-하-셨-습-니-다!\n"
	.string "또 어디선가 만나요!$"
	@ §いｐ
	@ なるほど-っ! ようよう!ｎ
	@ そんなら ノリノリで それ つかうぜ!ｐ
	@ そろそろ わしも すだつと するかｎ
	@ ノリノリで たたかい まくるぜ!ｌ
	@ いろいろと ありがとうな!ｐ
	@ お®つ®か®れ®さ®ま!ｎ
	@ は-い おつかれさま ごきげんよう!

gText_ApprenticePickWinSpeech12:: @ 82C28D6
	.string "오우예 {PLAYER}니임!\n"
	.string "어떡하지 나? 오늘도 물어볼까?\l"
	.string "앗 근데 이미 물어보고 있잖아!\p"
	.string "애초에 {PLAYER}님은\n"
	.string "언제나 받아주지!? 그렇잖아!!\l"
	.string "그러니까 상담 좀 해주라!\p"
	.string "내가 이겼을 때에 외칠\n"
	.string "멋지고 엄청나고\l"
	.string "굉장한 대사를...\l"
	.string "뭐라도 추천해 줘어어어!$"
	@ オ-イェッ §あさあん!ｎ
	@ どうする オレ? きょうも きいてみる?ｌ
	@ ってもう きこうとしてる!?ｐ
	@ そもそも §あさんってｎ
	@ いつも きいてる!? きいてる!!ｌ
	@ じゃ そうだんに のってェ!ｐ
	@ おれが かった ときに さけぶｎ
	@ カッコイイ キメキメのｌ
	@ すんごい セリフ……ｌ
	@ なんか かんがえてエエェ!

gText_ApprenticeWinSpeechThanks12:: @ 82C2A0B
	.string "{STR_VAR_1}\p"
	.string "오-케-이 오-케이!\n"
	.string "그럼 바로 그걸로 갈게!\p"
	.string "앗 근데 이젠\n"
	.string "물어볼 게 없어졌어!\l"
	.string "어쩔 수 없지- 이걸로 끝낼까!?\l"
	.string "라고 말해놓고 어딘가에서 딱\l"
	.string "마주치는 거 아니야!?\p"
	.string "뭐- 그래도 일단 여기서 작별하자!\p"
	.string "{PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "그럼 안녕 {PLAYER}님! 사랑한다구!$"
	@ §いｐ
	@ オ-ラ-イ オ-ライ!ｎ
	@ じゃ さっそく それでいくぜェ!ｐ
	@ ってオレ もうｎ
	@ きくことが なくなったぜ!ｌ
	@ しかたね- これで おわかれする!?ｌ
	@ とかいって どこかで ちゃっかりｌ
	@ また あえちゃったり するかも!?ｐ
	@ ま- とりあえずは おわかれだぜ!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ じゃあな §あさん! スキだぜェ!

gText_ApprenticePickWinSpeech13:: @ 82C2B50
	.string "{PLAYER}{KUN}, I'm finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think up something\n"
	.string "cool to say when I win a battle.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose won't stop running…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"
	@ §あ§お おれはｎ
	@ もう ダメだよ……ｌ
	@ はなみずが とまらなくってさ……ｐ
	@ しょうぶに かった ときにｎ
	@ なにか かっこいいこと いおうとしてｌ
	@ あたまで かんがえてたら……ｐ
	@ われながら ジ-ンと なけちゃってｎ
	@ はなみずが でたんだよね きっと!ｌ
	@ というわけ だからさｌ
	@ §あ§お かんがえてよ!ｐ
	@ しょうぶに かったらｎ
	@ おれ なんて いえば いいかな?

gText_ApprenticeWinSpeechThanks13:: @ 82C2C77
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"
	@ §いｐ
	@ …… …… ……いいよｎ
	@ それ いいよ!ｌ
	@ ダメだ なみだが また とまらないよｐ
	@ でも なみだと はなみずを こらえてｎ
	@ そのセリフ つかわせて もらうよ!ｐ
	@ おれは もう §あ§おにｎ
	@ ききたい ことは なくなった!ｌ
	@ これからは ライバルだよ!ｐ
	@ ん いままで ありがとうな!

gText_ApprenticePickWinSpeech14:: @ 82C2D67
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all nervous.\p"
	.string "I… I need your advice again.\n"
	.string "I'll make it my last, though…\p"
	.string "It's really embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｐ
	@ また…… そうだん させて くれよｎ
	@ こ これで さいごに するからさｐ
	@ あのさ はずかしいん だけどさｎ
	@ もし もし しょうぶに かったら!ｌ
	@ ワシは なんて いったら いいんだろう……?

gText_ApprenticeWinSpeechThanks14:: @ 82C2E41
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll obey all that you've taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"
	@ §いｐ
	@ よ よし それｎ
	@ いって みるよ!ｌ
	@ は はずかしいな いえるかな……ｐ
	@ ありがとう §あ§おｎ
	@ さようならだ!ｌ
	@ §あ§おに いわれた ことｌ
	@ ぜんぶ まもって ワシ がんばるよ!

gText_ApprenticePickWinSpeech15:: @ 82C2EF5
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps a clever {PLAYER} DOLL?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are real, please\l"
	.string "forget about my rudeness.\p"
	.string "No need to be so angry. All I wish for\n"
	.string "is more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say\n"
	.string "if I win a battle?$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんものかな?ｌ
	@ §あ§お ぬいぐるみ では?ｐ
	@ いや! いやいやいやいや!ｎ
	@ すまない ほんものなら いいんだｌ
	@ まあ そう おこらないで くれ!ｌ
	@ それでもって じょげんを おねがいするｌ
	@ ことばに かんする ことだ!ｐ
	@ もし わたしが しょうぶに かったらｎ
	@ ぜんたい なんと いえば いいかね?

gText_ApprenticeWinSpeechThanks15:: @ 82C3023
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope even I will be able to\n"
	.string "put that saying to good use.\p"
	.string "I seem to have run dry on what advice\n"
	.string "I need.\p"
	.string "I do believe it's high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my mentor!\n"
	.string "I apologize for my skepticism!$"
	@ §いｐ
	@ …… …… ……ｎ
	@ しょうぶに かったらｐ
	@ §いｐ
	@ …… ほんき なのかね?ｐ
	@ いや ほんき なら いいんだ!ｎ
	@ どうも ありがとうｌ
	@ こんな わたしでも いつかｌ
	@ つかえる ときが くれば いいなｐ
	@ では そろそろｎ
	@ ほしい じょげんも なくなってきたｌ
	@ §あ§おとは おわかれしてｌ
	@ ひとりで がんばって みようかと おもうｐ
	@ では ありがとう!ｎ
	@ うたがって すまなかった!
