gText_ApprenticeChallenge0:: @ 82B6EA5
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자입니다!\n"
	.string "훌쩍... 긴장되네$"
	@ §いさんの §うばん でしです!ｎ
	@ グスン…… きんちょう するなあ

gText_ApprenticeChallenge1:: @ 82B6EEC
	.string "나 {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자야! 간다-!$"
	@ ぼく §いさんのｎ
	@ §うばんの でし なんだ! いくぞ-!

gText_ApprenticeChallenge2:: @ 82B6F16
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자입니다!\n"
	.string "자 승부하죠!$"
	@ §いさんの §うばんの でしだ!ｎ
	@ いざ しょうぶ!

gText_ApprenticeChallenge3:: @ 82B6F4C
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자입니다...\n"
	.string "저 따위가 이길 수 있을까요...?$"
	@ §いさんの §うばんでしです…ｎ
	@ あたし なんかが かてる かな……?

gText_ApprenticeChallenge4:: @ 82B6F92
	.string "{STR_VAR_1}의 {STR_VAR_2}번째 제자야!\n"
	.string "승부해 줄게!$"
	@ §いの §うばん でしなの!ｎ
	@ しょうぶ して あげるわ!

gText_ApprenticeChallenge5:: @ 82B6FC9
	.string "전 바쁘면서도 {STR_VAR_1}의\n"
	.string "{STR_VAR_2}번째 제자를 하고 있습니다!$"
	@ いそがしい なか §いさんのｎ
	@ §うばんの でし やってる オレです!

gText_ApprenticeChallenge6:: @ 82B700C
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째\n"
	.string "제자 트레이너야 잘 부탁해!$"
	@ §いさんの §うばんのｎ
	@ でしトレ-ナ-よ よっろしくぅ!

gText_ApprenticeChallenge7:: @ 82B703A
	.string "전 {STR_VAR_1}님의 {STR_VAR_2}번째\n"
	.string "제자입니다... 갈게요$"
	@ わたくし §いさまの §うばんのｎ
	@ でしで ございますの…… いきますわよ

gText_ApprenticeChallenge8:: @ 82B706A
	.string "꺄-! {STR_VAR_1} 선생님의\n"
	.string "{STR_VAR_2}번째 제자예요! 힘낼게요!$"
	@ キャ-! §いせんせいのｎ
	@ §うばん でし ですっ! がんばります!

gText_ApprenticeChallenge9:: @ 82B709C
	.string "예-이! {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자인 아저씨와 승부하자!$"
	@ いえ-い! §いさんのｎ
	@ §うばん でしの おじさんと しょうぶ!

gText_ApprenticeChallenge10:: @ 82B70CC
	.string "{STR_VAR_1}의 1000번째 제자야!\n"
	.string "거짓말이고 사실 {STR_VAR_2}번째지롱! 간다!$"
	@ §いの 1000ばんめの でしだ!ｎ
	@ うそ ほんとは §うばん! いくぞ!

gText_ApprenticeChallenge11:: @ 82B710A
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째\n"
	.string "제자라고! 들썩들썩하게 가자고-!$"
	@ §いさんの §うばんのｎ
	@ でしだぜ! ノリノリで いってみようぜ-!

gText_ApprenticeChallenge12:: @ 82B714D
	.string "이야호! {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자는 날 말하는 거라고!$"
	@ イヤハァ! §いさんのｎ
	@ §うばんの でしとは オレのことっ!

gText_ApprenticeChallenge13:: @ 82B7185
	.string "...콜록 콜록 잘 부탁해!\n"
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자야!$"
	@ ……ゴホっ ゴホっ よろしく!ｎ
	@ §いさんの §うばんでしだ!

gText_ApprenticeChallenge14:: @ 82B71C1
	.string "부 부끄럽지만 {STR_VAR_1}님의\n"
	.string "{STR_VAR_2}번째 제자입니다...!$"
	@ て てれますが §いさんのｎ
	@ §うばんの でし やってます……!

gText_ApprenticeChallenge15:: @ 82B71F9
	.string "거짓말이 아냐! 난\n"
	.string "{STR_VAR_1}님의 {STR_VAR_2}번째 제자다$"
	@ うそじゃない! わたしはｎ
	@ §いさんの §うばんの でしだ

gText_ApprenticePleaseTeach0:: @ 82B7229
	.string "호 혹시 {PLAYER}님...?\n"
	.string "아아! 훌쩍...\p"
	.string "아... 죄송합니다!\n"
	.string "긴장해서 눈물이 나와버렸어요...\p"
	.string "저는 {STR_VAR_1}{K_I}라고 하고\n"
	.string "{PLAYER}님을 동경하고 있습니다!\l"
	.string "어 언젠가 {PLAYER}님을 만나서\l"
	.string "포켓몬에 대해 배우고 싶다고\l"
	.string "꿈꿔왔었어요...! 으흑...\p"
	.string "저기 저기 {PLAYER}님!\n"
	.string "괜찮다면... 포켓몬에 대해\l"
	.string "알려주세요!$"
	@ も もしかして §あさん……?ｌ
	@ ああ! グスっ……ｐ
	@ あ…… ごめんなさい!ｎ
	@ きんちょう して なみだが でちゃった……ｐ
	@ ぼくは §い って いってｎ
	@ §あさんに あこがれて います!ｌ
	@ い いつか §あさんに あってｌ
	@ ポケモンのこと おしえて もらう ってｌ
	@ ゆめ みて いたんです……! うう……ｐ
	@ あのう あのう §あさん!ｎ
	@ できたら…… ポケモンのことｌ
	@ おしえて ください!

gText_ApprenticeRejectTeaching0:: @ 82B731C
	.string "그... 그럴 수가...\n"
	.string "으 으흑 으아앙-!\p"
	.string "부탁이에요... 부탁이니까 제발...!$"
	@ そ そんな……ｎ
	@ う うう うわ-ん!ｐ
	@ おねがいです…… おねがい ですから……!

gText_ApprenticeWhichLevelMode0:: @ 82B735B
	.string "앗- 정말인가요!?\n"
	.string "해냈다! 너무 기뻐! 으헝헝-!\p"
	.string "아... 죄송합니다\n"
	.string "기뻐서 눈물이...\p"
	.string "저기 그럼 가르쳐주세요!\n"
	.string "배틀타워의 방 말인데\l"
	.string "레벨 50과 오픈 레벨의 방 중\l"
	.string "어느 쪽이 저한테 잘 맞을까요...?$"
	@ え- ほんとですか!ｎ
	@ やった! うれしいよう! うぉぉ-ん!ｐ
	@ あ…… ごめん なさいｎ
	@ うれしくて なみだが……ｐ
	@ あのう じゃあ おしえて ください!ｎ
	@ バトルタワ-の へや なんですけどｌ
	@ レベル50と オ-プンレベルの へやｌ
	@ ぼく だったら どっちが いいのかな……?

gText_ApprenticeLevelModeThanks0:: @ 82B7423
	.string "{STR_VAR_1}이군요? 으흑 으헝헝-!\p"
	.string "아! 죄송합니다\n"
	.string "{PLAYER}님이 제게 방을\l"
	.string "추천해주신 게 기뻐서 눈물이...\p"
	.string "...훌쩍\n"
	.string "정말 감사합니다!\l"
	.string "다음에도 얘기해주세요!$"
	@ §い ですね! うぅ うわ-ん!ｐ
	@ あ! ごめんなさいｎ
	@ §あさんが ぼくに へやをｌ
	@ きめてくれた うれしさで なみだが……ｐ
	@ ……グスンｎ
	@ ありがとう ございました!ｌ
	@ また おはなし してください!

gText_ApprenticePleaseTeach1:: @ 82B74C1
	.string "우와-! {PLAYER}님 맞지?\n"
	.string "엄청 강한 사람 맞지?\p"
	.string "난 {STR_VAR_1}!\n"
	.string "이제 막 트레이너가 됐어\p"
	.string "저기 부탁이야 {PLAYER}님!\n"
	.string "내 선생님이 돼서\l"
	.string "트레이너에 대해 잔뜩 알려주라!$"
	@ うわ-! §あさん だよね?ｎ
	@ すごく つよい ひと なんだよね?ｐ
	@ ボク §い!ｎ
	@ トレ-ナ-に なった ばかり なんだｐ
	@ ねえ おねがい §あさん!ｎ
	@ ぼくの せんせいに なってｌ
	@ トレ-ナ-のこと いっぱい おしえてよ!

gText_ApprenticeRejectTeaching1:: @ 82B756F
	.string "에- 왜?\n"
	.string "저기- 알려줘도 괜찮잖아\l"
	.string "선생님이 되어주라 부탁이야!$"
	@ え-? どうして?ｎ
	@ ね-っ いいでしょ いいでしょｌ
	@ せんせいに なってよ おねがい!

gText_ApprenticeWhichLevelMode1:: @ 82B75B2
	.string "와아 해냈다!\n"
	.string "그럼 있지- 처음으로 물어볼 건\l"
	.string "배틀타워에 대해서야!\p"
	.string "레벨 50과 오픈 레벨의 방 중\n"
	.string "어느 쪽이 나한테 잘 맞을까?$"
	@ わ-い やった!ｎ
	@ じゃあね- はじめに ききたい ことはねｌ
	@ バトルタワ-の こと!ｐ
	@ レベル50と オ-プンレベルの へやｎ
	@ どっちが ボクに ピッタリ かなあ?

gText_ApprenticeLevelModeThanks1:: @ 82B763F
	.string "{STR_VAR_1}이구나! 역시 그렇지-?\n"
	.string "그럼 나 열심히 해볼게!\p"
	.string "다음에 또 여기서 만나면\n"
	.string "뭔가 알려줘 선생님!$"
	@ §いか! そ-だよね!ｎ
	@ じゃあ ボク がんばるね!ｐ
	@ また こんど ここで あったらｎ
	@ なにか おしえてね せんせい!

gText_ApprenticePleaseTeach2:: @ 82B76AC
	.string "저기... {PLAYER}님이신가요!?\n"
	.string "전 {STR_VAR_1}{K_I}라고 합니다!\p"
	.string "저 포켓몬 트레이너가 되고 싶은데\n"
	.string "어떡하면 좋을지 모르겠어서요...\p"
	.string "그래서 유명한 {PLAYER}님께\n"
	.string "어떡하면 좋을지 여쭤봐야겠다고\l"
	.string "생각이 들었습니다!\p"
	.string "상담해주실 수 있나요?$"
	@ あの…… §あさん ですか!?ｎ
	@ ぼく §い って いいます!ｐ
	@ ぼく ポケモントレ-ナ-に なりたいんだけどｎ
	@ どうすれば いいのか わからなくて……ｐ
	@ それで ゆうめいな §あさんにｎ
	@ どうすれば いいのか きいてみようとｌ
	@ おもったんです!ｐ
	@ そうだんに のって もらえますか?

gText_ApprenticeRejectTeaching2:: @ 82B7772
	.string "그럴 수가!\n"
	.string "저 무슨 수를 써서라도 포켓몬 트레이너가\l"
	.string "되고 싶어요!\p"
	.string "질문에 대답해주실 수 있나요?$"
	@ そんなあ!ｎ
	@ ぼく どうしても ポケモントレ-ナ-にｌ
	@ なりたいんです!ｐ
	@ しつもんに こたえて もらえますか?

gText_ApprenticeWhichLevelMode2:: @ 82B77CE
	.string "감사합니다!\n"
	.string "그럼 바로 첫 번째 질문을 할게요!\p"
	.string "배틀타워엔 레벨 50과 오픈이라는\n"
	.string "두 개의 레벨이 있잖아요?\p"
	.string "어느 레벨이\n"
	.string "저한테 잘 맞을 거라고 생각하세요?$"
	@ ありがとう ございます!ｎ
	@ じゃあ さっそく さいしょの しつもん!ｐ
	@ バトルタワ-って レベル50と オ-プンとｎ
	@ ふたつの レベルが ありますよね!ｐ
	@ どっちの レベルがｎ
	@ ぼくに あってると おもいますか?

gText_ApprenticeLevelModeThanks2:: @ 82B7871
	.string "{STR_VAR_1}이군요! 알겠습니다!\n"
	.string "그럼 또 질문이 있으면\l"
	.string "여기에 올 테니 가르쳐주세요!$"
	@ §い ですね! わかりました!ｎ
	@ じゃあ また しつもんが あったらｌ
	@ ここに くるので おしえて ください!

gText_ApprenticePleaseTeach3:: @ 82B78D4
	.string "어라? 에? 당신은...!\n"
	.string "아니 그럴 리가 없어\l"
	.string "나 따위가 {PLAYER}님을\l"
	.string "만날 수 있을 리 없는걸\p"
	.string "...정말로 {PLAYER}님이신가요?\n"
	.string "이렇게 대화할 수 있다니 안 믿겨요!\l"
	.string "아아 이렇게나 좋은 일이 생겼으니\l"
	.string "나중에 분명 나쁜 일만 일어나겠네\p"
	.string "...아 죄송합니다\n"
	.string "저는... {STR_VAR_1}{K_I}라고 해요\l"
	.string "장점은 아무것도 없습니다\l"
	.string "...라면서 자기소개를 해도\l"
	.string "어차피 금방 잊어버리겠죠...\p"
	.string "{PLAYER}님을 만나면\n"
	.string "트레이너로서 상담해 달라고\l"
	.string "부탁할 생각이었는데\l"
	.string "어차피 안 되겠죠?\p"
	.string "...아니면 설마\n"
	.string "상담해주실 수 있는 건가요?$"
	@ あれ? え? あなたは……!ｎ
	@ いえ そんなはず ないわｌ
	@ あたし なんかが §あさんにｌ
	@ あえるはず なんて ないもんｐ
	@ ……ほんとに §あさん なの?ｎ
	@ しんじられない おはなし できるなんて!ｌ
	@ ああ こんな いいことが あったらｌ
	@ あとは わるいこと ばっかり おきるんだわｐ
	@ ……あ ごめんなさいｎ
	@ あたし…… §い です……ｌ
	@ なんの とりえも ありませんｌ
	@ って じこしょうかい なんて してもｌ
	@ どうせ すぐ わすれちゃいます よね……ｐ
	@ §あさんに あえたらｎ
	@ トレ-ナ-として そうだんに のって ってｌ
	@ おねがい しようと おもっていたけどｌ
	@ どうせ ムリですよね?ｐ
	@ ……それとも もしかしてｎ
	@ そうだんに のって もらえたり しますか?

gText_ApprenticeRejectTeaching3:: @ 82B7B1A
	.string "역시... 그렇겠죠\n"
	.string "저 따위는 정말로\l"
	.string "재미없는 여자애에 불과하니까요...\p"
	.string "그래도 혹시 몰라 여쭤보는데...\n"
	.string "다시 생각해주실 수는 없는 거죠?\p"
	.string "그치만 역시나 포기하기 싫단 말이에요\n"
	.string "아직 운이 좋을 때 부탁드립니다!\l"
	.string "...상담해주시면 안 될까요?$"
	@ やっぱり…… そうですよねｎ
	@ あたし なんて ほんとにｌ
	@ つまらない おんなのこで……ｐ
	@ でも もしかしたら って おもって……ｎ
	@ かんがえなおして なんて くれませんよね?ｐ
	@ けど やっぱり あきらめられないｎ
	@ うんが いい うちに おねがいしよう!ｌ
	@ ……そうだんに のって もらえますか?

gText_ApprenticeWhichLevelMode3:: @ 82B7C13
	.string "정말로요? 안 믿겨요!\n"
	.string "저 따위에게 상담을\l"
	.string "해주신다니 꿈 같아요!\l"
	.string "너무 기뻐요...\p"
	.string "정말 별것 아닌 얘기겠지만\n"
	.string "전 도저히 못 정하겠어서요\p"
	.string "배틀타워에선 레벨을\n"
	.string "레벨 50과 오픈 레벨\l"
	.string "둘 중 하나로 선택할 수 있잖아요...?\p"
	.string "저 따위라도 활약할 수 있는\n"
	.string "레벨은 어느 쪽 방인가요?$"
	@ ほんとう ですか? しんじられない!ｎ
	@ あたし なんかの そうだんにｌ
	@ のってもらえる なんて!ｌ
	@ うれしい です……ｐ
	@ ほんとうに くだらないです けどｎ
	@ あたし には きめられないん ですｐ
	@ バトルタワ-って レベルがｎ
	@ レベル50と オ-プンレベルとｌ
	@ ふたつ えらべる けど……ｐ
	@ あたし なんか でも がんばれそうなｎ
	@ レベルって どっちの へや でしょうか?

gText_ApprenticeLevelModeThanks3:: @ 82B7D18
	.string "{STR_VAR_1}이군요 알겠습니다!\n"
	.string "정말 이런 저라도\l"
	.string "잘할 수 있을까요?\l"
	.string "열심히 해볼게요 안 될지도 모르지만\p"
	.string "오늘 저 따위에게 시간 내주셔서\n"
	.string "정말 감사했습니다...!$"
	@ §い ですか わかりました!ｎ
	@ ほんとうに こんな あたしでもｌ
	@ だいじょうぶ でしょうかｌ
	@ がんばって みます ダメかも しれないけどｐ
	@ きょうは あたしなんかの ためにｎ
	@ ありがとう ございました……!

gText_ApprenticePleaseTeach4:: @ 82B7DD4
	.string "앗! {PLAYER} 맞지!?\n"
	.string "포켓몬 배틀을 아주 잘한다며!\p"
	.string "난 {STR_VAR_1}\n"
	.string "친구가 되어줄게!\p"
	.string "있지 트레이너스쿨에서\n"
	.string "배운 것만으로는\l"
	.string "배틀프런티어에서 이길 수 없더라구!\p"
	.string "상담해준다면 기쁘겠어\n"
	.string "당연히 OK겠지?$"
	@ あっ! §あ§お でしょ!?ｎ
	@ ポケモン つよいって きいてるよ!ｐ
	@ わたしは §いｎ
	@ おともだちに なって あげる!ｐ
	@ あのね トレ-ナ-ズスク-ル でｎ
	@ おそわった こと だけじゃｌ
	@ バトルフロンティア では かてないの!ｐ
	@ そうだんに のってくれても いいわよｎ
	@ もちろん オ-ケ- でしょ?

gText_ApprenticeRejectTeaching4:: @ 82B7EE5
	.string "에? 거절한다고?\n"
	.string "다른 사람도 아니고 내 부탁인데!\l"
	.string "다시 한 번 생각해봐!$"
	@ え? なんで ことわるの?ｎ
	@ あたしの おねがい なんだけど!ｌ
	@ かんがえなおしてよぉ!

gText_ApprenticeWhichLevelMode4:: @ 82B7F35
	.string "응 그럼 잘 부탁해\n"
	.string "바로 정해줬으면 하는 게 있어\p"
	.string "배틀타워엔\n"
	.string "레벨 50과 오픈 레벨의 방이 있잖아?\p"
	.string "{PLAYER}{K_EUNNEUN} 나한테\n"
	.string "어느 쪽이 좋을 것 같아?$"
	@ うん じゃあ おねがいねｎ
	@ さっそく きめて ほしいことが あるからｐ
	@ レベル50と オ-プンレベルの へやがｎ
	@ バトルタワ-に あるじゃない?ｌ
	@ §あ§おは わたしにはｌ
	@ どっちが いいと おもう?

gText_ApprenticeLevelModeThanks4:: @ 82B7FE8
	.string "그래? {STR_VAR_1}이\n"
	.string "나한테 어울리는구나 고마워!\l"
	.string "{PLAYER}{K_IGA} 정해주니까\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ そう §いがｎ
	@ わたしに ふさわしいのね ありがと!ｌ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticePleaseTeach5:: @ 82B8087
	.string "오오 너! {PLAYER}{K_I}구나!\n"
	.string "유명하니까 알고 있다고\l"
	.string "난 {STR_VAR_1}{K_I}야 잘 부탁해!\p"
	.string "난 트라이애슬리트를 하고 있는데\n"
	.string "몸도 단련하고\l"
	.string "포켓몬도 키우고\l"
	.string "아르바이트에 사교댄스까지...\p"
	.string "너무 바쁘게 살다 보니까\n"
	.string "좀처럼 좋은 트레이너가 되기 힘들더라고!\p"
	.string "그래서 부탁할 게 있어!\p"
	.string "여기서 만난 것도 무언가의 인연일 테니까!\n"
	.string "{PLAYER} 너 가끔씩 나한테\l"
	.string "어드바이스 좀 해주지 않을래?$"
	@ ああ きみ! §あ§お!ｎ
	@ ゆうめい だから しってるぜｌ
	@ オレは §い よろしく!ｐ
	@ オレは トライアスリ-ト やっててｎ
	@ からだを きたえる かたわらｌ
	@ ポケモンも そだてて ほかにもｌ
	@ バイトに ひるねに しゃこうダンス……ｐ
	@ いそがしくて なっかなかｎ
	@ いい トレ-ナ-に なれないんだよね!ｐ
	@ そこで おねがい!ｐ
	@ ここで あえたのも なにかの ごえん!ｎ
	@ §あ§お たまに オレにｌ
	@ アドバイスを おねがい できないかな?

gText_ApprenticeRejectTeaching5:: @ 82B822B
	.string "에-! 부탁 좀 할게!\n"
	.string "나한텐 {PLAYER} 같은 사람이\l"
	.string "필요하단 말이야-!\p"
	.string "나한테 어드바이스 해주라!$"
	@ え-! たのむよ!ｎ
	@ §あ§お みたいな ひとがｌ
	@ オレには ひつよう なんだよ-!ｐ
	@ オレに アドバイス たのむよ!

gText_ApprenticeWhichLevelMode5:: @ 82B8286
	.string "땡큐! 그렇게 나와야지!\n"
	.string "그럼 먼저 가벼운 질문 하나!\p"
	.string "저기 있지 배틀타워엔\n"
	.string "레벨이 2종류 있잖아?\l"
	.string "레벨 50과 오픈 레벨!\p"
	.string "바쁜 내게는\n"
	.string "어느 쪽이 어울릴 것 같아?$"
	@ サンキュ- そう こなくっちゃ!ｎ
	@ んじゃ てはじめに かるいのを 1つね!ｐ
	@ あのさ バトルタワ- ってｎ
	@ レベルが 2しゅるい あるじゃん?ｌ
	@ レベル50と オ-プンレベル!ｐ
	@ いそがしい オレ だったらｎ
	@ どっちで がんばれば いいかな?

gText_ApprenticeLevelModeThanks5:: @ 82B8356
	.string "{STR_VAR_1}이구나! 오케이-!\n"
	.string "어떻게든 시간을 내서 해볼게!\p"
	.string "...어이쿠 아르바이트 갈 시간이다!\n"
	.string "그럼 땡큐- 또 보자!$"
	@ §い ね! オ-ケ-!ｎ
	@ なんとか じかん つくって やってみるぜ!ｐ
	@ ……っと いけね バイトのじかんだ!ｎ
	@ じゃあ サンキュ- またな!

gText_ApprenticePleaseTeach6:: @ 82B83CE
	.string "말도 안 돼 설마\n"
	.string "진짜로 {PLAYER}님이야?\p"
	.string "와 굉장하다-!\n"
	.string "나 {STR_VAR_1}{K_I}야 잘 부탁해!\p"
	.string "{PLAYER}님 말야\n"
	.string "엄청 강하지?\l"
	.string "다들 그러더라구!\p"
	.string "아! 좋은 생각이 났어\n"
	.string "나 {PLAYER}님한테\l"
	.string "어드바이스 받을래!\l"
	.string "분명 강해질 수 있을 거야!\p"
	.string "저기 어때 괜찮지?\n"
	.string "나한테 어드바이스 좀 부탁할게!$"
	@ うっそ もしかしてｎ
	@ ほんものの §あさん?ｐ
	@ あっは! すご-い!ｎ
	@ わたし §いよ よろしくぅ!ｐ
	@ §あさん って なんかｎ
	@ とっても つよいんでしょｌ
	@ みんな うわさ してるもんね!ｐ
	@ あ! いいこと かんがえちゃったｎ
	@ わたし §あさんにｌ
	@ アドバイスを もらおうっと!ｌ
	@ きっと つよく なれそう!ｐ
	@ ねっ いいでしょ?ｎ
	@ わたしに アドバイス おねがい!

gText_ApprenticeRejectTeaching6:: @ 82B84FC
	.string "아하하하! 그렇게 짓궂게 말해도\n"
	.string "나한텐 안 통하거든!\l"
	.string "사실은 OK하고 싶지?$"
	@ あははは! そんな いじわる いってもｎ
	@ あたし には つうじないわよん!ｌ
	@ ほんとは オ-ケ- なんでしょ?

gText_ApprenticeWhichLevelMode6:: @ 82B8559
	.string "야호! 역시 {PLAYER}님이야!\n"
	.string "마음이 넓다니까-!\l"
	.string "먼저 뭐부터 물어볼까-?\l"
	.string "...앗 그래 생각났어!\p"
	.string "엣헴 그럼 질문입니다!\n"
	.string "내가 배틀타워에 도전한다면!\l"
	.string "레벨 50의 방! 오픈 레벨의 방!\l"
	.string "둘 중 어느 쪽이 어울릴까-요?$"
	@ わ-い さっすが §あさん!ｎ
	@ ココロひろ-い!ｌ
	@ まずは なにから きこうかな-?ｌ
	@ ……あっ おもいついた!ｐ
	@ ジャ-ン しつもんです!ｎ
	@ わたしが バトルタワ-に いどむなら!ｌ
	@ レベル50のへや! オ-プンレベルのへや!ｌ
	@ さて どっちが にあっている でしょう?

gText_ApprenticeLevelModeThanks6:: @ 82B8656
	.string "허허허-!\n"
	.string "{STR_VAR_1}이라고요!\l"
	.string "깔끔한 대답 고마워!\p"
	.string "응 오늘은 이 정도만 할게\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ ほほぉ-!ｎ
	@ §い と きましたか!ｌ
	@ シブイ おこたえ ありがとう!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticePleaseTeach7:: @ 82B86EA
	.string "혹시 당신은\n"
	.string "{PLAYER}님 맞으신가요?\p"
	.string "만나 뵙게 되어 참으로 기쁩니다\n"
	.string "전 {STR_VAR_1}{K_I}라고 해요\l"
	.string "{PLAYER}님을 이전부터\l"
	.string "동경하고 있었습니다...\p"
	.string "...... ...... ......\p"
	.string "저기... 이런 부탁이\n"
	.string "굉장히 실례가 될지도 모릅니다만...\p"
	.string "저를 {PLAYER}님의\n"
	.string "제자로 받아 주실 수 있으신지요?$"
	@ もし §あさんでｎ
	@ いらっしゃいますか?ｐ
	@ おめに かかれて うれしゅうございますｎ
	@ わたくし §いと もうしますのｌ
	@ §あさんに かねてよりｌ
	@ あこがれて おりました……ｐ
	@ …… …… ……ｐ
	@ あの…… こんな おねがいｎ
	@ おこまりに なるかも しれませんが…ｐ
	@ わたくしを §あさんにｎ
	@ でしいり させて いただけません?

gText_ApprenticeRejectTeaching7:: @ 82B87DA
	.string "어머...!\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\p"
	.string "...아 충격으로 정신을 잃을 뻔했네요\n"
	.string "그럴 리 없죠! 분명 잘못 들은 걸 거예요\p"
	.string "부탁이에요! 저를\n"
	.string "제자로 삼아 주세요!$"
	@ まあ……!ｐ
	@ …… …… ……ｎ
	@ …… …… ……ｐ
	@ ……あ ショックで きを うしないましたわｎ
	@ いいえ! きっと ききまちがい ですわｐ
	@ おねがい! わたくしをｎ
	@ でしに して くださると おっしゃって!

gText_ApprenticeWhichLevelMode7:: @ 82B887C
	.string "저 정말 기뻐요...!\p"
	.string "그럼 바로 저와\n"
	.string "상담해 주세요!\p"
	.string "저 한번 배틀타워에\n"
	.string "도전해보려고 생각 중이거든요\l"
	.string "다만 레벨이 두 개 있잖아요...\p"
	.string "저는 레벨 50과 오픈 레벨 중\n"
	.string "어디에 어울리는 것 같으신가요?$"
	@ うっ うれしい ですわ……!ｐ
	@ では さっそくですけど わたくしのｎ
	@ そうだんを きいて くださいませ!ｐ
	@ わたくし いちど バトルタワ-にｎ
	@ ちょうせん しようと おもっていますのｌ
	@ ただ レベルが ふたつ ありまして……ｐ
	@ わたくしは レベル50と オ-プンレベルｎ
	@ どちらに ふさわしいと おもわれますか?

gText_ApprenticeLevelModeThanks7:: @ 82B8957
	.string "{STR_VAR_1}이군요!\n"
	.string "알겠습니다 열심히 할게요!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "다음에 뵈어요!$"
	@ §い ですのね!ｎ
	@ わかりました がんばりますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticePleaseTeach8:: @ 82B89C6
	.string "꺄-! 꺄-!!!\n"
	.string "{PLAYER}님이 말 걸어줬어!\l"
	.string "가 감격이야...!\p"
	.string "저! {STR_VAR_1}{K_I}라고 해요!\n"
	.string "트레이너가 된 지 얼마 안 돼서\l"
	.string "포켓몬계의 거물인 {PLAYER}님과\l"
	.string "대화할 수 있어서 감동이에요!\p"
	.string "마마마마 맞다!\n"
	.string "{PLAYER}님 부탁이 있어요!\l"
	.string "저를 제자로 받아주세요!\l"
	.string "여러 가지 배우고 싶어요!$"
	@ キャ-! キャ-!!!ｎ
	@ §あさんに はなしかけられた!ｌ
	@ かっ かんげきっ……!ｐ
	@ わたし! §いと いいますっ!ｎ
	@ トレ-ナ-に なって すぐにｌ
	@ ポケモンかいの おおもの §あさんとｌ
	@ おはなし できて かんどう してますっ!ｐ
	@ そそそそ そうだ!ｎ
	@ §あさん おねがいが!ｌ
	@ わたしを でしに して くださいっ!ｌ
	@ いろいろ おしえて ほしいのですっ!

gText_ApprenticeRejectTeaching8:: @ 82B8ACF
	.string "우와아아!!\n"
	.string "{PLAYER}님께 거절당했다...\l"
	.string "귀 귀중한 경험이야!\p"
	.string "{PLAYER}님! 이번엔\n"
	.string "좋은 대답을 들려주세요!\p"
	.string "제게 지도를 부탁드립니다!$"
	@ うっわああ!!ｎ
	@ §あさんに ことわられた……ｌ
	@ きっ きちょうな けいけん だわっ!ｐ
	@ §あさんっ! こんどはｎ
	@ よい おへんじも きかせて くださいっ!ｌ
	@ わたしに ごしどうを おねがいしますっ!

gText_ApprenticeWhichLevelMode8:: @ 82B8B66
	.string "히에에에에에! {PLAYER}님이\n"
	.string "예 라고 말씀하셨어어어!!\l"
	.string "오늘은 이제 잠 다 잤다...\l"
	.string "정말로 감사드립니다!\p"
	.string "그럼 여쭤보도록 할게요!\n"
	.string "저는 배틀타워\l"
	.string "레벨 50의 방과 오픈 레벨의 방 중\l"
	.string "어느 쪽에 어울린다고 생각하시나요?$"
	@ ひええええぇ! §あさんにｎ
	@ はい って いわれたああぁ!!ｌ
	@ きょうは もう ねむれない……ｌ
	@ おありがとう ございますう!ｐ
	@ ではっ うかがいます!ｎ
	@ わたしは バトルタワ-ｌ
	@ レベル50のへやと オ-プンレベルのへやｌ
	@ どちらに むいてると おもわれますかっ?

gText_ApprenticeLevelModeThanks8:: @ 82B8C20
	.string "{STR_VAR_1}이군요! 알겠습니다\n"
	.string "가슴에 새길게요!\l"
	.string "저 감격했어요!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 알려주세요!$"
	@ §い りょうかいですっｎ
	@ りょうかいで ありますっ!ｌ
	@ わたし かんげき です!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticePleaseTeach9:: @ 82B8CAA
	.string "와우! 너는\n"
	.string "설마 설마 {PLAYER}!?\l"
	.string "스트롱하고 페이머스한 트레이너!\l"
	.string "이야 아저씨는 럭키한걸-!\p"
	.string "헬로 아저씨는 {STR_VAR_1}{K_I}야!\n"
	.string "포켓몬 티처를 찾고 있지\l"
	.string "그런 때에 굿 타이밍!\l"
	.string "때마침 {PLAYER} 네가 나타났어!\p"
	.string "그렇게 됐으니 {PLAYER}!\n"
	.string "아저씨를 제자로 삼아줘!$"
	@ ワォ! きみはｎ
	@ もしや もしや §あ§お!ｌ
	@ ストロングで フェイマスな トレ-ナ-!ｌ
	@ いや おじさん ラッキ-だな-!ｐ
	@ ハロウ おじさんは §いね!ｎ
	@ ポケモン ティ-チャ- さがしてるんだｌ
	@ そんな ときに グッドタイミングでｌ
	@ §あ§おが あらわれた!ｐ
	@ と いうわけで §あ§お!ｎ
	@ おじさんを でしいり させて くれ!

gText_ApprenticeRejectTeaching9:: @ 82B8DD3
	.string "크아악-!\n"
	.string "너도 제법 쿨하고 터프한걸...\l"
	.string "그런 말 하지 말고 제발!$"
	@ ぐわ-っ!ｎ
	@ きみも なかなか ク-ルで タフだね……ｌ
	@ そんなこと いわずに おねがいだよ!

gText_ApprenticeWhichLevelMode9:: @ 82B8E24
	.string "오우-! 감동이 확 밀려오는데!\n"
	.string "엑설런트!\p"
	.string "그럼 퍼스트 어드바이스 부탁해!\n"
	.string "배틀타워 말인데\l"
	.string "아저씨가 도전한다면 레벨은\l"
	.string "50과 오픈 중 어느 게 베터-?$"
	@ おぅ-! グッと くるね!ｎ
	@ エクセレント!ｐ
	@ では ファ-スト アドバイス たのむね!ｎ
	@ バトルタワ- なんだけどさｌ
	@ おじさんが やるなら レベルはｌ
	@ 50と オ-プン どっちが ベタ-かな?

gText_ApprenticeLevelModeThanks9:: @ 82B8ED5
	.string "아-하 {STR_VAR_1}이구나\n"
	.string "오-케이 오-케이!\l"
	.string "아저씨 팍팍 힘내고 올게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん バ-っと がんばって くるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticePleaseTeach10:: @ 82B8F45
	.string "저 저기 {PLAYER} 맞지!\n"
	.string "방금 경찰 아저씨가 찾고 있었다고!\p"
	.string "...... ...... ......\n"
	.string "농담이야 거짓말 거짓말!\p"
	.string "난 {STR_VAR_1}{K_I}라고 해\n"
	.string "이래 봬도 포켓몬 챔피언이라구!\l"
	.string "...라는 말도 거짓말이지롱!\p"
	.string "실은 나 포켓몬 승부를\n"
	.string "그다지 잘하지 않아서 말야!\l"
	.string "제안 하나 할게\l"
	.string "내 스승님이 되어주지 않을래?$"
	@ お おいっ §あ§おだろ!ｎ
	@ さっき おまわりさんが さがしてたぞ!ｐ
	@ …… …… ……ｎ
	@ なんてね うっそ うそ!ｐ
	@ おいらは §い って いうんだｎ
	@ こうみえても ポケモンチャンピオンさ!ｌ
	@ ……て いうのも ウソ!ｐ
	@ じつは おいら ポケモンしょうぶがｎ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろｌ
	@ おいらの ししょうに なってくれない かな?

gText_ApprenticeRejectTeaching10:: @ 82B905F
	.string "그렇게 차가운 말 하면\n"
	.string "이렇게 해주지!\p"
	.string "우에-엥 우에-엥 흐엥 헝 헝!\p"
	.string "농담이야 거짓울음이지롱!\p"
	.string "저기! 괜찮은 제안이잖아\n"
	.string "내 스승님이 되어주라!$"
	@ そんな つめたい こと いうとｎ
	@ こうだぞ!ｐ
	@ うえ-ん うえ-ん え-ん えん えんｐ
	@ なんてね うそなき!ｐ
	@ ね! いいだろｎ
	@ おいらの ししょうに なって おくれよ!

gText_ApprenticeWhichLevelMode10:: @ 82B910E
	.string "앗싸-!\n"
	.string "답례로 배를 사줄게!\p"
	.string "뭐 물론 농담이지만...\n"
	.string "스승님! 잘 부탁해!\p"
	.string "저기 있지 배틀타워에는\n"
	.string "레벨 50과 오픈 레벨이 있잖아!\p"
	.string "어디서 열심히 하면 좋을지\n"
	.string "고민 중이거든...\l"
	.string "스승님이 정해주면 안 될까?$"
	@ やった-!ｎ
	@ おれいに ふねを かって あげよう!ｐ
	@ なんて じょうだん だけど……ｎ
	@ ししょう! よろしく たのむぜ!ｐ
	@ あのさ バトルタワ-でｎ
	@ レベル50と オ-プンレベルと あるだろ!ｐ
	@ どっちで がんばれば いいかｎ
	@ まよってるんだよ……ｌ
	@ ししょうが きめて くれないかな?

gText_ApprenticeLevelModeThanks10:: @ 82B9204
	.string "그렇구나\n"
	.string "{STR_VAR_1}이 좋다고!\l"
	.string "그럼 그 반대쪽으로 가야지!\p"
	.string "...농담이야!\n"
	.string "스승님 말씀은 제대로 들어야지\p"
	.string "고마워 스승님!\n"
	.string "또 만나면 그때도 부탁할게-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ ちがうほうに いこうっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticePleaseTeach11:: @ 82B929C
	.string "처-음-뵙-겠-습-니-다!\n"
	.string "네 처음 뵙겠습니다!\l"
	.string "전 선선한 선원 {STR_VAR_1}!\l"
	.string "당신도 자기소개 해보십시오!\p"
	.string "흠흠 이름은 {PLAYER}{K_I}군요!\n"
	.string "포켓몬을 엄청 좋아하는\l"
	.string "미묘한 나이의 청년이고!\p"
	.string "사실 당신은 오늘 제가 말을 건\n"
	.string "10번째 트레이너랍-니-다!\p"
	.string "이 만남을 기념하여\n"
	.string "부디 저를 제자로 받아주세요!$"
	@ は®じ®め®ま®し®て!ｎ
	@ は-い はじめまして!ｌ
	@ わし ノリノリ ふなのり §い!ｌ
	@ きみも じこしょうかい いってみようぜ!ｐ
	@ ふん ふん なまえは §あ§お!ｎ
	@ ポケモン だいすきでｌ
	@ びみょうな おとしごろね!ｐ
	@ じつは きみは わしが はなしかけたｎ
	@ ほんじつ 10にんめの トレ-ナ-で-す!ｐ
	@ この であいを きねんしてｎ
	@ ぜひとも わしを でしに してください!

gText_ApprenticeRejectTeaching11:: @ 82B9438
	.string "그럴 수가!\n"
	.string "선선하지 못한 선택 아닌가요!\p"
	.string "저기 괜찮잖아요\n"
	.string "부디 저를 제자로 받아주세요!$"
	@ そんな!ｎ
	@ ノリが わるいじゃ ないか!ｐ
	@ な いいじゃ ないかｎ
	@ ぜひとも わしを でしに してください!

gText_ApprenticeWhichLevelMode11:: @ 82B9488
	.string "요요! 선선한 선택!\n"
	.string "{PLAYER}님 잘 부탁드립니다!\p"
	.string "그럼 1번째 질문\n"
	.string "가볼까요!\l"
	.string "배틀타워에 관한 질문입니다!\p"
	.string "레벨 50의 방과 오픈 레벨의 방\n"
	.string "제가 간다면 어느 쪽이 좋을까요?$"
	@ ようよう! ノリが いいね!ｎ
	@ §あさん よろしく たのみますよ!ｐ
	@ それじゃあ 1つめの しつもんｎ
	@ いってみようぜ!ｌ
	@ バトルタワ-に かんする しつもんだ!ｐ
	@ レベル50のへやと オ-プンレベルのへやｎ
	@ わしが いくなら さあ どっち?

gText_ApprenticeLevelModeThanks11:: @ 82B9564
	.string "{STR_VAR_1}입니까-앗! 요요!\n"
	.string "그렇다면 선선하게 가보겠습니다!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで いってみるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticePleaseTeach12:: @ 82B95D8
	.string "히야호- {PLAYER}님 아냐-!?\n"
	.string "어떡하지 나? 말 걸어볼까!?\l"
	.string "앗 근데 이미 대화하고 있잖아!!\p"
	.string "앗 근데 {PLAYER}님 지쳐보이는데!?\n"
	.string "어쩔 수 없지- 자기소개 해볼까!?\p"
	.string "안녕 난 {STR_VAR_1}{K_I}야!\n"
	.string "포켓몬 기타리스트계의 1등성이지!\p"
	.string "앗 근데 듣고 있는 거지!?\n"
	.string "마침 부탁이나 좀 해볼까!?\p"
	.string "저기 {PLAYER}님!\n"
	.string "날 {PLAYER}님의 제자로 삼아줘!$"
	@ ヒャホ- §あさんじゃな-い!?ｎ
	@ どうする オレ? はなしかけてみる!?ｌ
	@ ってもう はなし してるよ!!ｐ
	@ って §あさん あきれてる!?ｎ
	@ しかたね- じこしょうかい してみる!?ｐ
	@ オスっ オレっ §い!ｎ
	@ ポケモン ギタリストかいの 1ばんぼしさ!ｐ
	@ って きいてる!? きいてる!!ｎ
	@ ついでに たのみごと してみる!?ｐ
	@ あの §あさん!ｎ
	@ オレを §あさんの でしに して!

gText_ApprenticeRejectTeaching12:: @ 82B9763
	.string "앗 거절당했잖아!?\n"
	.string "어쩔 수 없지- 한 번 더 부탁해볼까!?\p"
	.string "부탁이야 {PLAYER}님!\n"
	.string "날 제자로 받아줘어어!!$"
	@ って ことわられてる オレっ!?ｎ
	@ しかたね- もういちど たのんでみる!?ｐ
	@ おねがい だよ §あさん!ｎ
	@ オレを でしに してエェ!!

gText_ApprenticeWhichLevelMode12:: @ 82B97E5
	.string "앗싸 럭키- 엄청 기쁜걸!!\n"
	.string "바로 뭔가 상담해볼까!?\l"
	.string "더군다나 여긴 배틀타워니\l"
	.string "그것부터 물어볼까!?\p"
	.string "저기! 나 배틀타워에서\n"
	.string "어느 레벨로 가면 좋을까!?$"
	@ やったラッキ- うれし-よ オレ!!ｎ
	@ さっそく なんか そうだんしてみる!?ｌ
	@ しかも ここは バトルタワ- だからｌ
	@ そのへん から きいてみる!?ｐ
	@ あのさっ! バトルタワ-で オレｎ
	@ どっちの レベルが にあってる!?

gText_ApprenticeLevelModeThanks12:: @ 82B989A
	.string "{STR_VAR_1}이라고!\n"
	.string "그럼 바로 가볼게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!$"
	@ §いだって!ｎ
	@ じゃ そこ いってみるよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticePleaseTeach13:: @ 82B992D
	.string "아... 거기 너!\n"
	.string "잠깐 어깨 좀 주물러줄래?\p"
	.string "...아아 그래그래 거기야 거기\n"
	.string "후- 기분 좋은걸!\p"
	.string "난 {STR_VAR_1}{K_I}라고 해\n"
	.string "태권도를 하고 있는데\l"
	.string "몸이 왠지 좀 약해서 말야...\p"
	.string "포켓몬 승부도 해서\n"
	.string "더 단련하려고 생각 중이지\p"
	.string "너 포켓몬리그에서 우승한\n"
	.string "{PLAYER} 맞지?\l"
	.string "어때 가끔씩 나한테\l"
	.string "상담 좀 해줄 수 있을까?$"
	@ あ…… きみきみ!ｎ
	@ ちょっとさ かた もんでくれる?ｐ
	@ ……ああ そうそう そこそこｎ
	@ は- きもちいい!ｐ
	@ おれ §い って いうんだｎ
	@ カラテ やってるんだけどｌ
	@ いまいち からだが よわくてさ……ｐ
	@ ポケモンしょうぶも やってｎ
	@ きたえようと おもって いるんだよねｐ
	@ きみ ポケモンリ-グで かったｎ
	@ §あ§お だろう?ｌ
	@ どうかな たまに おれのｌ
	@ そうだんに のって もらえない かい?

gText_ApprenticeRejectTeaching13:: @ 82B9A84
	.string "에- 왜!\p"
	.string "그렇게 폐 안 끼칠 테니까\n"
	.string "부탁 좀 할게!$"
	@ え- なんで!ｐ
	@ そんなに めんどうは かけないからさｎ
	@ おねがいだよ!

gText_ApprenticeWhichLevelMode13:: @ 82B9AB9
	.string "고맙고 미안\n"
	.string "...콜록 콜록!\p"
	.string "으으 빨리 단련해야겠어...\n"
	.string "바로 배틀타워에 갈 거라서\l"
	.string "레벨 50의 방과 오픈 레벨의 방 중\l"
	.string "어디가 좋을지 정해줄래?$"
	@ ありがとう わるいねｎ
	@ ……ゴホ ゴホっ!ｐ
	@ うう はやく きたえなきゃ……ｎ
	@ すぐに バトルタワ-に いくからｌ
	@ レベル50のへや オ-プンレベルのへやｌ
	@ どっちが いいか きめてくれるかい?

gText_ApprenticeLevelModeThanks13:: @ 82B9B76
	.string "응 알았어 {STR_VAR_1}이구나!\n"
	.string "그럼 바로 갔다 올게!\p"
	.string "앞으로도 나를 잘 부탁해!\n"
	.string "이젠 제자니까 말이지!$"
	@ ん わかった §いな!ｎ
	@ じゃあ さっそく いってくる!ｐ
	@ これからも おれを よろしく たのむよ!ｎ
	@ もう でしいり したんだからな!

gText_ApprenticePleaseTeach14:: @ 82B9BF2
	.string "아... 아...\n"
	.string "{PLAYER} 맞지...?\l"
	.string "그 그렇게 보지 말아주게!\l"
	.string "부끄럽단 말일세\p"
	.string "난 {STR_VAR_1}{K_I}라고 하는데\n"
	.string "부 부끄럽지만\l"
	.string "유적을 찾으며 살아가고 있지\p"
	.string "근데 배틀프런티어에도\n"
	.string "부끄럽지만 흐 흥미가 있다네\p"
	.string "{PLAYER} 자네는 포켓몬 배틀에\n"
	.string "강하다는 평판이 나 있더군...\l"
	.string "그 이런 말 하긴 그렇지만\l"
	.string "하나 부탁이 있다네\p"
	.string "내 선생님이 돼서\n"
	.string "어드바이스를 해주지 않겠나...?$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｐ
	@ ワシは §いと いってｎ
	@ は はずかしい けどｌ
	@ いせきを さがしたり して くらしてるんだｐ
	@ でも バトルフロンティア にもｎ
	@ はずかしながら き きょうみが あるんだｐ
	@ §あ§おは ポケモン つよいってｎ
	@ ひょうばん だから……ｌ
	@ その いいづらいん だけどｌ
	@ ひとつ おねがいを したいんだｐ
	@ ワシの せんせいに なってｎ
	@ アドバイスして もらえない かな……?

gText_ApprenticeRejectTeaching14:: @ 82B9D83
	.string "거 거절하지 말아주게!\n"
	.string "내게 부끄러움을 주지 말게나!\p"
	.string "부탁이니\n"
	.string "내 선생님이 되어주게!$"
	@ こ ことわらないでくれ!ｎ
	@ ワシに はじを かかせないで くれ!ｐ
	@ おねがい だからｎ
	@ ワシの せんせいに なってくれ!

gText_ApprenticeWhichLevelMode14:: @ 82B9DF9
	.string "고 고맙네...\p"
	.string "아니 그러니까 그렇게 보지 말아주게\n"
	.string "부끄럽단 말일세\p"
	.string "눈을 마주치지 말고 대답해 주게나!\p"
	.string "배 배틀타워... 배틀타워 말인데\n"
	.string "어느 레벨에 도전하면 좋겠는가?$"
	@ あ ありがとう……ｐ
	@ いや だから そんなに みないで くれよｎ
	@ てれるだろｐ
	@ めを あわせずに こたえて くれ!ｐ
	@ ば バトルタワ…… バトルタワ- だがｎ
	@ どの レベルに ちょうせん すれば いい?

gText_ApprenticeLevelModeThanks14:: @ 82B9EAA
	.string "아 알겠네!\n"
	.string "그쪽에서 열심히 해보겠네\p"
	.string "으으 부끄러움 안 타고\n"
	.string "열심히 할 수 있을까...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 보면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ それで がんばって みるよｐ
	@ うう はずかし がらずにｎ
	@ がんばれる かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticePleaseTeach15:: @ 82B9F55
	.string "응?\n"
	.string "{PLAYER}처럼 보이는데...\l"
	.string "진짜인가?\p"
	.string "난 {STR_VAR_1}\n"
	.string "지금 말이지 누군가 강한 트레이너의\l"
	.string "제자로 들어가려고 생각 중이었네\p"
	.string "그런 때에 자네가 와서 다행이군!\n"
	.string "...정말로 {PLAYER} 맞는 거지?\p"
	.string "아냐 진짜라면 됐어\n"
	.string "내가 제자가 되는 걸 허락해주게$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんもの なのかね?ｐ
	@ わたしは §いだｎ
	@ いまね だれか つよい トレ-ナ-にｌ
	@ でしいり したいと おもって いたんだよｐ
	@ きみが いるなら よかった!ｎ
	@ ……ほんとうに §あ§お だよね?ｐ
	@ いや ほんもの なら いいんだｎ
	@ わたしの でしいりを みとめて ほしい

gText_ApprenticeRejectTeaching15:: @ 82BA084
	.string "뭐? 왜 거절하는 거지?\p"
	.string "진짜인지 의심해서 미안했네\n"
	.string "사과할 테니 제자로 받아주게나$"
	@ え? なぜ ことわるのかね?ｐ
	@ ほんものか どうか うたがって わるかったｎ
	@ あやまるから でしいり させてほしい

gText_ApprenticeWhichLevelMode15:: @ 82BA11D
	.string "정말로 허락하는 겐가?\n"
	.string "괜한 기대를 가지고 싶진 않거든\p"
	.string "아니 진짜로 그런 거라면 됐네 미안하네\n"
	.string "바로 상담해주면 좋겠군\p"
	.string "내가 배틀타워에 간다면\n"
	.string "레벨 50... 오픈 레벨...\l"
	.string "어느 쪽이 어울린다고 생각하나?$"
	@ ほんとうに みとめて くれるのかね?ｎ
	@ ぬかよろこびは したく ないからなｐ
	@ いや ほんとうなら いいんだ わるかったｎ
	@ さっそく そうだんに のってほしいｐ
	@ わたしが バトルタワ-に でるならｎ
	@ レベル50…… オ-プンレベル……ｌ
	@ どちらの ほうが ふさわしいと おもうかね

gText_ApprenticeLevelModeThanks15:: @ 82BA1F3
	.string "{STR_VAR_1}... 정말인가?\p"
	.string "아니 진짜라면 됐네\n"
	.string "정말 고맙네\p"
	.string "이런 나를\n"
	.string "제자로 인정해 줘서 기쁘군\l"
	.string "언젠가 다시 보도록 하지!$"
	@ §い…… ほんとうかね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｐ
	@ こんな わたし だがｎ
	@ でし として みとめて くれて うれしいｌ
	@ いずれまた あおう!

gText_ApprenticeWhatHeldItem0:: @ 82BA2A3
	.string "하아… 훌쩍훌쩍…\n"
	.string "아앗 {PLAYER}님!\p"
	.string "저 말이죠 못 정하고 있는 게 있어서\n"
	.string "조금 곤란해하고 있었어요\p"
	.string "그게 뭐냐면 {STR_VAR_1}에게\n"
	.string "뭘 지니게 할지에 대해서예요\l"
	.string "알려주세요 {PLAYER}님\l"
	.string "뭘 지니게 하면 좋을까요?$"
	@ はあ…… シクシクｎ
	@ ああっ §あさん!ｐ
	@ ぼくね きめられない ことが あってｎ
	@ ちょっと こまってたんですｐ
	@ きめられない のは §いにｎ
	@ なにを もたせるかって ことなんですｌ
	@ おしえて ください §あさんｌ
	@ なにか もたせた ほうが いいですか?

gText_ApprenticeHoldNothing0:: @ 82BA34E
	.string "엣... {STR_VAR_1}{K_EUNNEUN}\n"
	.string "아무것도 지니지 않는 편이 좋나요?$"
	@ えっ…… §いはｎ
	@ なにも もたないほうが いいんですか?

gText_ApprenticeThanksNoHeldItem0:: @ 82BA380
	.string "아 알겠습니다!\n"
	.string "정해주셔서 기뻐요 으허엉-!\p"
	.string "오늘 정말 감사했습니다!$"
	@ わっ わかりました!ｎ
	@ きまって うれしいです うぉぉ-ん!ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeThanksHeldItem0:: @ 82BA3D2
	.string "다 다행이다...\n"
	.string "{STR_VAR_1}{K_I}라면 가지고 있었을 거예요...\l"
	.string "정해주셔서 기뻐요 으허엉-!\p"
	.string "오늘 정말 감사했습니다!$"
	@ よ よかったｎ
	@ §いなら もってるかも……ｌ
	@ きまって うれしいです うぉぉ-ん!ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeItemAlreadyRecommended0:: @ 82BA448
	.string "으아앙-! 너무해요\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 이미\l"
	.string "알려주신 도구라구요 훌쩍\p"
	.string "아니면 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "아무것도 지니지 않는 편이 좋나요?$"
	@ うわ-ん! ひどいですｎ
	@ §いは もうｌ
	@ おしえてもらった どうぐ です グスンｐ
	@ それとも §うはｎ
	@ なにも もたないほうが いいんですか?

gText_ApprenticeWhatHeldItem1:: @ 82BA4D3
	.string "와- {PLAYER}님이다!\n"
	.string "잘됐다! 물어보고 싶은 게 있었거든!\p"
	.string "저기 {PLAYER}님은\n"
	.string "포켓몬에게 도구를 지니게 해?\l"
	.string "나도 지니게 하고 싶은데...\p"
	.string "내 {STR_VAR_1}에겐\n"
	.string "무엇을 지니게 하면 좋을까?\l"
	.string "{PLAYER}님은 어떻게 생각해?$"
	@ わ- §あさん だ!ｎ
	@ よかった! ききたい ことが あったんだ!ｐ
	@ あのね §あさんはｎ
	@ ポケモンに どうぐを もたせてる?ｌ
	@ ボクも もたせたいんだけど……ｐ
	@ ボクの §いにはｎ
	@ なにを もたせたら いいのかなｌ
	@ §あさんは どう おもう?

gText_ApprenticeHoldNothing1:: @ 82BA58C
	.string "엣 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "아무것도 안 지녀도 괜찮다는 뜻이야?$"
	@ えっ §いはｎ
	@ なにも もたせなくて いいって こと?

gText_ApprenticeThanksNoHeldItem1:: @ 82BA5BF
	.string "알았어 그럼 그렇게 할게-!\n"
	.string "고마워 선생님!$"
	@ わかった- じゃあ そうする-!ｎ
	@ せんせい ありがと!

gText_ApprenticeThanksHeldItem1:: @ 82BA5F3
	.string "에헤헤 {STR_VAR_1} 말이구나-\n"
	.string "그럼 그렇게 할게-!\p"
	.string "고마워 선생님!$"
	@ へええ! §いか-ｎ
	@ じゃあ そうする-!ｐ
	@ せんせい ありがと!

gText_ApprenticeItemAlreadyRecommended1:: @ 82BA635
	.string "아 으음 그게 아니라\n"
	.string "아직 알려주지 않은 도구 중에서\l"
	.string "뭐가 좋은지 알고 싶은 거야!\p"
	.string "아니면 이번엔\n"
	.string "아무것도 안 지니게 해볼까?$"
	@ あ えっと そうじゃなくてｎ
	@ まだ おしえて もらってない どうぐでｌ
	@ なにが いいか しりたいんだ!ｐ
	@ それとも こんどはｎ
	@ なにも もたせなくって いいのかな?

gText_ApprenticeWhatHeldItem2:: @ 82BA6E6
	.string "{PLAYER}님 안녕하세요!\n"
	.string "제 {STR_VAR_1} 말인데요...\p"
	.string "뭐라도 지닌물건을 주고 싶어요!\n"
	.string "뭔가 좋은 지닌물건을 알려주세요!$"
	@ §あさん こんにちは!ｎ
	@ ぼくの §いの ことなんだけどｐ
	@ なにか もちものを もたせたいんだ!ｎ
	@ なにか いい もちもの おしえてください!

gText_ApprenticeHoldNothing2:: @ 82BA742
	.string "그럼 {STR_VAR_1}에겐\n"
	.string "아무것도 안 지니게 해도 되는 거죠?$"
	@ じゃあ §いにはｎ
	@ なにも もたせなくても いいんだね?

gText_ApprenticeThanksNoHeldItem2:: @ 82BA770
	.string "알겠습니다!\n"
	.string "그럼 다음에 봬요!$"
	@ わかりました!ｎ
	@ じゃあ また!

gText_ApprenticeThanksHeldItem2:: @ 82BA78F
	.string "{STR_VAR_1} 말이군요!\n"
	.string "알겠습니다!\p"
	.string "힘내서 찾아볼게요!\n"
	.string "그럼 다음에 봬요!$"
	@ §い ですか!ｎ
	@ わかりました!ｐ
	@ がんばって さがしてきます!ｎ
	@ じゃあ また!

gText_ApprenticeItemAlreadyRecommended2:: @ 82BA7D8
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "전에 알려주신 적이 있어요\p"
	.string "그거하곤 다른 지닌물건을\n"
	.string "지니게 하고 싶기도 하고요\p"
	.string "아니면 {STR_VAR_2}에게\n"
	.string "아무것도 안 지니게 해도 되나요?$"
	@ §いはｎ
	@ まえに おしえて もらいましたよｐ
	@ それとは ちがう もちものをｎ
	@ もたせたいんですｐ
	@ それとも §うにはｎ
	@ なにも もたせなくて いいんだね?

gText_ApprenticeWhatHeldItem3:: @ 82BA867
	.string "{PLAYER}님 안녕하세요...\n"
	.string "죄송합니다 저 오늘도\l"
	.string "여쭤보고 싶은 게 있어요\p"
	.string "제 힘만으로는\n"
	.string "승부에서 이기지 못할지도 모르니까\l"
	.string "뭔가 도구를 {STR_VAR_1}에게\l"
	.string "지니게 하려고 생각 중이거든요\l"
	.string "근데 뭐가 좋을지...\p"
	.string "{PLAYER}님 부탁드립니다\n"
	.string "저 대신 정해주세요!$"
	@ §あさん こんにちは……ｎ
	@ ごめんなさい きょうも あたしｌ
	@ ききたい ことが あるんですｐ
	@ あたしの ちから だけではｎ
	@ しょうぶに かてないかも しれないからｌ
	@ なにか どうぐを §いにｌ
	@ もたせようかと おもって いるんですｌ
	@ でも なにが いいのか……ｐ
	@ §あさん おねがいしますｎ
	@ あたしの かわりに きめてください!

gText_ApprenticeHoldNothing3:: @ 82BA96B
	.string "저기 저 따위의 포켓몬에겐\n"
	.string "아무것도 안 지니게 하는 편이 좋나요?$"
	@ あの あたしなんかの ポケモンにはｎ
	@ なにも もたせないほうが いいんですか?

gText_ApprenticeThanksNoHeldItem3:: @ 82BA9B7
	.string "알겠습니다...\n"
	.string "도구에 의존하지 말라는 말씀이시죠?\l"
	.string "열심히 하고 오겠습니다!\p"
	.string "감사합니다!$"
	@ わかりました……ｎ
	@ どうぐに たよるなって ことですね?ｌ
	@ がんばって みます!ｐ
	@ ありがとう ございます!

gText_ApprenticeThanksHeldItem3:: @ 82BAA1B
	.string "{STR_VAR_1} 말이군요!\n"
	.string "제가 손에 넣을 수 있을까요...\l"
	.string "아니죠! 열심히 구해볼게요\p"
	.string "감사합니다!$"
	@ §い ですか!ｎ
	@ あたしに みつけられるか……ｌ
	@ いえ! がんばって みますｐ
	@ ありがとう ございます!

gText_ApprenticeItemAlreadyRecommended3:: @ 82BAA81
	.string "에... 그건\n"
	.string "전에 알려주신 적이 있어요\p"
	.string "아 혹시\n"
	.string "제가 {STR_VAR_1}{K_EULREUL}\l"
	.string "잘 쓰지 못하고 있어서인가요?\p"
	.string "아니면 {STR_VAR_2}에겐 아무것도\n"
	.string "지니게 하지 않아도 된다는 뜻인가요?$"
	@ え…… それはｎ
	@ まえに おしえて いただいたと おもいますｐ
	@ あ もしかしてｎ
	@ あたしが §いをｌ
	@ つかいこなせて いないから ですか?ｐ
	@ それとも §うには なにもｎ
	@ もたせるなと いう こと でしょうか?

gText_ApprenticeWhatHeldItem4:: @ 82BAB22
	.string "어머 {PLAYER}\n"
	.string "잠깐 물어보고 싶은 게 있어!\p"
	.string "나 포켓몬은 정했는데\n"
	.string "어떤 도구를 지니게 할지까지는\l"
	.string "정하지 못했지 뭐야?\p"
	.string "어차피 할 거라면 마지막까지\n"
	.string "당신이 정해주는 게 좋지 않겠어?\l"
	.string "있지 뭐가 좋을까?\l"
	.string "{STR_VAR_1}에게 주고 싶어!$"
	@ あら §あ§おｎ
	@ ちょっと ききたい ことが あるのよ!ｐ
	@ わたし ポケモンは きめて もらったけどｎ
	@ どの どうぐを もたせるか まではｌ
	@ きめて もらってない じゃない?ｐ
	@ どうせ なら さいごまでｎ
	@ あなたが きめて くれない?ｌ
	@ ねえ なにが いいかしら?ｌ
	@ §いに もたせたいの!

gText_ApprenticeHoldNothing4:: @ 82BAC43
	.string "어머! {STR_VAR_1}{K_EULREUL}\n"
	.string "빈손으로 내보내라고?$"
	@ あら! §いはｎ
	@ てぶらで がんばれ って ことかしら?

gText_ApprenticeThanksNoHeldItem4:: @ 82BAC78
	.string "그게 좋다면 그렇게 할게!\n"
	.string "{PLAYER}{K_IGA} 정해줬으니\l"
	.string "지더라도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ それが よければ そうするわ!ｎ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeThanksHeldItem4:: @ 82BAD17
	.string "{STR_VAR_1} 말이지\n"
	.string "나쁘지 않네 그렇게 할게!\l"
	.string "{PLAYER}{K_IGA} 정해줬으니\l"
	.string "지더라도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ §いかｎ
	@ わるく ないわね そうするわ!ｌ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeItemAlreadyRecommended4:: @ 82BADB6
	.string "엣 무슨 소리 하는 거야\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 이미\l"
	.string "알려준 적 있잖아!\p"
	.string "아니면 {STR_VAR_2}{K_EULREUL}\n"
	.string "빈손으로 내보내라는 뜻이야?$"
	@ えっ なに いってるのよｎ
	@ §いは もうｌ
	@ おしえて もらった じゃない!ｐ
	@ それとも §うはｎ
	@ てぶらで がんばれ って ことかしら?

gText_ApprenticeWhatHeldItem5:: @ 82BAE36
	.string "요 {PLAYER}\n"
	.string "바쁜 것치고는 자주 만나네!\l"
	.string "나 오늘은\l"
	.string "워킹에 클리닝 게다가\l"
	.string "브러싱까지 하느라 엄청 큰일이었어!\p"
	.string "덕분에 소중한 {STR_VAR_1}에게\n"
	.string "도구조차 사주지 못했지-\p"
	.string "저기 말야! 시간도 없으니까\n"
	.string "무엇을 {STR_VAR_1}에게\l"
	.string "지니게 하면 좋을지만이라도\l"
	.string "어드바이스 해주라!$"
	@ よっ §あ§おｎ
	@ いそがしい わりには よく あうよね!ｌ
	@ オレは きょうはｌ
	@ ウォ-キング クリ-ニング それにｌ
	@ ブラッシングと たいへん そのものさ!ｐ
	@ おかげで だいじな §いにもｎ
	@ どうぐ さえ かって やれなくてね-ｐ
	@ あのさ! じかんも ないからｎ
	@ なにを §いにｌ
	@ もたせて やったら いいかｌ
	@ それだけでも アドバイス してよ!

gText_ApprenticeHoldNothing5:: @ 82BAF4E
	.string "오 그러면\n"
	.string "바쁜 내 {STR_VAR_1}{K_EUNNEUN}\l"
	.string "아무것도 안 지녀도 괜찮다는 거야?$"
	@ おっ それじゃｎ
	@ いそがしい オレの §いはｌ
	@ なにも もたなくて イイ ってこと?

gText_ApprenticeThanksNoHeldItem5:: @ 82BAF8F
	.string "오케이 알았어!\n"
	.string "그럼 굳이 시간 낼 필요도 없겠네\p"
	.string "오늘 상담해줘서 땡큐! 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ それ なら じかんも いらないぜｐ
	@ きょうは サンキュ-! じゃ またな!

gText_ApprenticeThanksHeldItem5:: @ 82BAFDB
	.string "오케이 알았어!\n"
	.string "그럼 어떻게든 시간 내서\l"
	.string "{STR_VAR_1}{K_EULREUL} 찾아볼게!\p"
	.string "난 좋은 선생님을 만났는걸\n"
	.string "땡큐! 그럼 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ じゃ なんとか じかん つくってｌ
	@ §いを さがすぜ!ｐ
	@ オレは いい せんせいに であえたよなｎ
	@ サンキュ-! じゃ またな!

gText_ApprenticeItemAlreadyRecommended5:: @ 82BB05F
	.string "나 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "이미 알고 있어!\p"
	.string "으음? 아니면\n"
	.string "바쁜 내 {STR_VAR_2}{K_EUNNEUN}\l"
	.string "아무것도 안 지녀도 괜찮다는 거야?$"
	@ あれっ §いはｎ
	@ もう しってるよ!ｐ
	@ ん? それともｎ
	@ いそがしい オレの §うはｌ
	@ なにも もたなくて イイ ってこと?

gText_ApprenticeWhatHeldItem6:: @ 82BB0D4
	.string "요 {PLAYER}님 나야 나!\n"
	.string "오늘도 하나 상담할 게 있으니까\l"
	.string "어드바이스 좀 부탁할게!\p"
	.string "자 그럼 상담 시작합니다!\n"
	.string "내 {STR_VAR_1}에게\l"
	.string "뭔가 도구를 지니게 한다면\l"
	.string "대체 뭘로 해야 좋을까?$"
	@ よぅ §あさん わたしだよ!ｎ
	@ きょうも ひとつ そうだんが あるのｌ
	@ アドバイス おねがい ねっ!ｐ
	@ ジャ-ン では そうだんです!ｎ
	@ わたしの §いにｌ
	@ なにか どうぐを もたせるならｌ
	@ いったい なにに したら いいかな?

gText_ApprenticeHoldNothing6:: @ 82BB18C
	.string "흐음-? {STR_VAR_1}한테\n"
	.string "지닌물건이 필요 없다는 뜻이야?$"
	@ ふ-ん? §いはｎ
	@ もちものは いらないって ことかな?

gText_ApprenticeThanksNoHeldItem6:: @ 82BB1CE
	.string "그럼 그렇게 할게!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ じゃ そうするね!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeThanksHeldItem6:: @ 82BB242
	.string "아항-!\n"
	.string "{STR_VAR_1}{K_I}라니 쿨하네\l"
	.string "꼭 그렇게 할게!\p"
	.string "응 오늘은 이 정도가 다야\n"
	.string "다음에 또 여기서 보자!\l"
	.string "고마워!$"
	@ ははぁ-ん!ｎ
	@ §いとは シブイわぁｌ
	@ ぜひ そうして みるね!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeItemAlreadyRecommended6:: @ 82BB2D9
	.string "앗하하 왜 그래\n"
	.string "{STR_VAR_1}{K_EUNNEUN} 이미\l"
	.string "알려준 적이 있잖아!\l"
	.string "{PLAYER}님 괜찮은 거 맞지?\p"
	.string "아! 아니면 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "지닌물건이 필요 없다는 뜻이야?$"
	@ あっはは やだぁｎ
	@ §いは もうｌ
	@ おしえて もらった じゃない!ｌ
	@ §あさん だいじょぶ?ｐ
	@ あ! それとも §うはｎ
	@ もちものは いらないって ことかな?

gText_ApprenticeWhatHeldItem7:: @ 82BB370
	.string "{PLAYER}님 그간 평안하셨는지요\n"
	.string "잠깐 얘기 좀 들어주실래요?\p"
	.string "지난번에 싸웠던 트레이너님이\n"
	.string "포켓몬에게 뭔가 도구를\l"
	.string "지니게 했던 것 같더라고요\p"
	.string "때문에 지고 말았습니다...\p"
	.string "저도 지지 않고 뭔가\n"
	.string "{STR_VAR_1}에게 지니게 하고 싶어요!\l"
	.string "뭘 지니게 하면 좋을지\l"
	.string "정해주시면 감사하겠습니다만...$"
	@ ごきげん いかがですか §あさんｎ
	@ きいて くださる?ｐ
	@ このまえ たたかった トレ-ナ-さんｎ
	@ ポケモンに なにか どうぐをｌ
	@ もたせていた らしいんですのｐ
	@ おかげで まけて しまいましたわ……ｐ
	@ わたくしも まけずに なにかｎ
	@ §いに もたせたいんですの!ｌ
	@ なにが よろしいの でしょうｌ
	@ きめて いただければ うれしいのですが……

gText_ApprenticeHoldNothing7:: @ 82BB4C3
	.string "그건 즉... 도구를\n"
	.string "지니게 하지 않아도 괜찮다는 뜻인가요?$"
	@ それは つまり…… どうぐはｎ
	@ もたせなくて よろしいんですのね?

gText_ApprenticeThanksNoHeldItem7:: @ 82BB4FB
	.string "알겠습니다!\n"
	.string "이대로 계속 열심히 해볼게요\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "다음에 뵈어요!$"
	@ わかりましたわ!ｎ
	@ このまま がんばる ことに しますわｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeThanksHeldItem7:: @ 82BB575
	.string "{STR_VAR_1} 말이군요!\n"
	.string "바로 주문해야겠네요!\p"
	.string "그럼 {PLAYER}님\n"
	.string "앞으로도 잘 부탁드립니다\l"
	.string "다음에 뵈어요!$"
	@ §い ですのね!ｎ
	@ さっそく とりよせますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeItemAlreadyRecommended7:: @ 82BB5E1
	.string "그건 이미 가르쳐 주셔서\n"
	.string "갖고 있는 물건이에요!\p"
	.string "아니면... {STR_VAR_2}에게는\n"
	.string "아무것도 필요 없다는 뜻이신가요...?$"
	@ それは もう おしえて いただいてｎ
	@ わたくし もっておりますわ!ｐ
	@ それとも…… §うにはｎ
	@ なにも もたせないで よろしいと……?

gText_ApprenticeWhatHeldItem8:: @ 82BB656
	.string "{PLAYER}님!\n"
	.string "오늘도 만나서 감격했어요...!\p"
	.string "마마마마마 맞다!\n"
	.string "저기 {PLAYER}님께서\l"
	.string "정해주셨으면 하는 게 있는데요!\p"
	.string "제 {STR_VAR_1}에겐\n"
	.string "뭘 지니게 하면 좋을까요?$"
	@ §あさんっ!ｎ
	@ きょうも あえて かんげき ですっ……!ｐ
	@ そそそそそ そうだっ!ｎ
	@ あのっ §あさんにｌ
	@ きめて ほしいことが あるのですっ!ｐ
	@ わたしの §いにはｎ
	@ なにを もたせれば いいですかっ?

gText_ApprenticeHoldNothing8:: @ 82BB6E5
	.string "우와아앗 의외의 대답이었어요!\n"
	.string "즉 아무것도 필요 없다는 건가요?$"
	@ うわあぁっ いがいな おこたえだあ!ｎ
	@ つまり なにも いらないの ですねっ?

gText_ApprenticeThanksNoHeldItem8:: @ 82BB72C
	.string "확실히 이해했습니다!\n"
	.string "도구 없이 열심히 해볼게요!\p"
	.string "그럼 다음에 또\n"
	.string "여러 가지 가르쳐 주세요!$"
	@ りょうかいで ありますっ!ｎ
	@ どうぐ なしで がんばるで あります!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticeThanksHeldItem8:: @ 82BB7A2
	.string "{STR_VAR_1} 말이군요!\n"
	.string "근데 지니게 하면 {PLAYER}님과\l"
	.string "커플 아이템이 되는 건가...?\p"
	.string "흐흐 반드시 지니게 할게요!\n"
	.string "그럼 다음에 또\l"
	.string "여러 가지 가르쳐 주세요!$"
	@ §い ですねっ!ｎ
	@ これって これって §あさんとｌ
	@ もしかして おそろい だったりしてっ!ｐ
	@ も- ぜったい もたせちゃいます!ｎ
	@ では また こんどｌ
	@ いろいろと おしえて くださいね!

gText_ApprenticeItemAlreadyRecommended8:: @ 82BB84A
	.string "어라 전에도 {STR_VAR_1}{K_EULREUL}\n"
	.string "알려주셨었잖아요!\p"
	.string "역시 그게 가장 좋은 건가요?\n"
	.string "앗 아니면 혹시\l"
	.string "{STR_VAR_2}에게는 아무것도\l"
	.string "지니게 할 필요가 없다는 뜻인가요?$"
	@ あれ まえにも §いをｎ
	@ おすすめして くれました よね!ｐ
	@ やっぱり コレが いちばん ですかっ?ｎ
	@ あ それとも もしかしてｌ
	@ §うには なにもｌ
	@ もたせなくて いいって ことですかっ?

gText_ApprenticeWhatHeldItem9:: @ 82BB8CD
	.string "헬로 헬로\n"
	.string "마이 티처 {PLAYER}!\p"
	.string "오늘은 포켓몬의 도구에 대해서\n"
	.string "어드바이스를 부탁하고 싶어!\p"
	.string "아저씨의 {STR_VAR_1}에게는\n"
	.string "어떤 도구를 지니게 하면 좋을까?\l"
	.string "한 번에 딱 정해줘!$"
	@ ハロウ ハロ-ウｎ
	@ マイ ティ-チャ- §あ§お!ｐ
	@ きょうは ポケモンの どうぐに ついてｎ
	@ アドバイスを おねがい したいんだ!ｐ
	@ おじさんの §いにはｎ
	@ どんな どうぐを もたせれば いいかな?ｌ
	@ パ-っと きめちゃって くれ!

gText_ApprenticeHoldNothing9:: @ 82BB970
	.string "어이쿠 그건\n"
	.string "{STR_VAR_1}에게 빈손으로\l"
	.string "이기라고 말하라는 뜻이야?$"
	@ おっと それはｎ
	@ §いは なにも もたせずともｌ
	@ かてる っていう こと なのかな?

gText_ApprenticeThanksNoHeldItem9:: @ 82BB9AE
	.string "오케이 오케이!\n"
	.string "아저씨 팍팍 힘내볼게!\p"
	.string "그럼 앞으로도 잘 부탁해!\n"
	.string "아디오스-!$"
	@ オ-ケイ オ-ケイ!ｎ
	@ おじさん グ-っと がんばるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeThanksHeldItem9:: @ 82BBA05
	.string "아하 {STR_VAR_1} 말이지!\n"
	.string "오케이 오케이!\l"
	.string "아저씨 후딱 찾아볼게!\p"
	.string "그럼 앞으로도 잘 부탁해\n"
	.string "아디오스-!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ゴ-っと さがして くるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeItemAlreadyRecommended9:: @ 82BBA6C
	.string "노노! {STR_VAR_1}{K_EUNNEUN}\n"
	.string "전에 알려줬었다구!\p"
	.string "오 아니면 혹시\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 아무것도 안 지녀도\l"
	.string "이길 수 있다는 뜻이야?$"
	@ ノンノン! §いはｎ
	@ まえに おしえて もらったよ!ｐ
	@ お それとも もしやｎ
	@ §うは なにも もたせずともｌ
	@ かてる っていう こと なのかな?

gText_ApprenticeWhatHeldItem10:: @ 82BBB01
	.string "{PLAYER} 나한테\n"
	.string "믿을 수 없는 일이 일어났어!\p"
	.string "아침에 일어났더니 포켓몬이\n"
	.string "금구슬을 10개나 가지고 있었다고!\l"
	.string "...거짓말이지롱! 으하하하!\p"
	.string "사실 나 포켓몬의 도구를\n"
	.string "뭘로 할지 고민 중인데\l"
	.string "그런 건 내 성격에 안 맞아!\l"
	.string "그러니까 내 {STR_VAR_1}에게\l"
	.string "뭘 지니게 하면 좋을지\l"
	.string "스승님이 정해주지 않을래?$"
	@ §あ§お ちょっとｎ
	@ しんじられん ことが おきた!ｐ
	@ けさ おきたら ポケモンがｎ
	@ きんのたまを 10コ もってたんだ!ｌ
	@ …… な-んて うっそさ! うわはは!ｐ
	@ じつは おいら ポケモンの どうぐをｎ
	@ かんがえる こと なんてｌ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろ おいらの §いｌ
	@ なにを もたせたら いいのかｌ
	@ ししょうが きめて くれない かな?

gText_ApprenticeHoldNothing10:: @ 82BBC1C
	.string "무슨 소리야?\n"
	.string "아무것도 지니게 하지 말라고?$"
	@ どういう ことかな?ｎ
	@ なにも もたせなくて いいんだな?

gText_ApprenticeThanksNoHeldItem10:: @ 82BBC4B
	.string "그렇구나 빈손으로도 괜찮다 이거지!\n"
	.string "그럼 뭐라도 지니게 해야겠다!\p"
	.string "...농담이야!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうか てぶらで いいのね!ｎ
	@ じゃあ なにか もたせようっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeThanksHeldItem10:: @ 82BBCF6
	.string "그렇구나\n"
	.string "{STR_VAR_1}{K_IGA} 좋다고!\l"
	.string "그럼 그거 말고 다른 거 줘야지!\p"
	.string "...농담이야!\n"
	.string "스승님이 말한 대로 할게\p"
	.string "고마워 스승님!\n"
	.string "다음에도 잘 부탁해-$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ それだけは やめとこっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeItemAlreadyRecommended10:: @ 82BBD90
	.string "아- 그건 전에\n"
	.string "알려준 적 있지 않아?\l"
	.string "그거 말고 다른 거 안 돼?\p"
	.string "아니면 {STR_VAR_2}에게\n"
	.string "아무것도 지니게 하지 말라는 뜻이야?$"
	@ あ- それは いちどｎ
	@ おしえて もらったことが あるだろ?ｌ
	@ ちがうので なにか ないかな?ｐ
	@ それとも §うはｎ
	@ なにも もたせなくて いいのかな?

gText_ApprenticeWhatHeldItem11:: @ 82BBE0B
	.string "안-녕-하-세-요!\n"
	.string "네 안녕하십니까!\l"
	.string "선선한 선원인 저와 함께하는\l"
	.string "상담 타임 시간입니다!\l"
	.string "도구에 관한 상담인데요!\p"
	.string "제 {STR_VAR_1}에게 건넬\n"
	.string "지닌물건으로 뭐가 좋을까요?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしが おくるｌ
	@ そうだんタイム いってみよう!ｌ
	@ どうぐに かんする そうだんだよ!ｐ
	@ わしの §いに もたせるならｎ
	@ さあ どんな どうぐがいい?

gText_ApprenticeHoldNothing11:: @ 82BBEE5
	.string "그건 혹시 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "아무것도 지닐 필요가 없다는 뜻입니까?$"
	@ それは あれかな? §いはｎ
	@ なんにも もたなくて いいのかな?

gText_ApprenticeThanksNoHeldItem11:: @ 82BBF25
	.string "그럴 수가-앗! 요요!\n"
	.string "그럼 선선하게 빈손으로 가볼까!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ そうか-っ! ようよう!ｎ
	@ そんなら ノリノリで てぶらでいくぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeThanksHeldItem11:: @ 82BBFA4
	.string "{STR_VAR_1}{K_I}라니-잇! 요요!\n"
	.string "그럼 선선하게 지니게 해볼까!\p"
	.string "앞으로도 잘 부탁드립니다\n"
	.string "{PLAYER}님!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで もたせてみるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeItemAlreadyRecommended11:: @ 82BC024
	.string "{STR_VAR_1}{K_I}라니-잇! 저기저기!\n"
	.string "그건 알려주신 적이 있다구요!\l"
	.string "뭔가 다른 걸로 부탁드립니다!\p"
	.string "아니면 그런 뜻인가요?\n"
	.string "아무것도 지니게 하지 말라는?$"
	@ §いか-っ! おいおい!ｎ
	@ それなら きいたことが あるぜ!ｌ
	@ なんか ちがうやつを たのむぜ!ｐ
	@ それとも あれかな?ｎ
	@ なにも もたせなくて いいのかな?

gText_ApprenticeWhatHeldItem12:: @ 82BC0C8
	.string "오케이 {PLAYER}님!\n"
	.string "오늘도 찾아냈다고!\l"
	.string "어떡하지 나? 상담해볼까!?\l"
	.string "앗 이미 얘기하고 있잖아!?\p"
	.string "앗 {PLAYER}님은 슬슬 내가\n"
	.string "싫어질 것 같다고!? 설마!!\l"
	.string "상담할 게 있는데 들어줘!\p"
	.string "내 {STR_VAR_1} 말인데\n"
	.string "좋은 도구를 지니게 하고 싶어!\l"
	.string "뭐가 좋을까? 자 정해줘!$"
	@ オッケ §あさん!ｎ
	@ きょうも みつけたぜェ!ｌ
	@ どうする オレ? そうだんしてみる!?ｌ
	@ って もう はなしかけてる!?ｐ
	@ って §あさん オレのこと そろそろｎ
	@ きらいに なってる!? なってない!!ｌ
	@ そうだんが あるんだけど きいてェ!ｐ
	@ オレの §い なんだけどｎ
	@ いい どうぐを もたせたいんだ!ｌ
	@ なにが いいか さあ きめて!

gText_ApprenticeHoldNothing12:: @ 82BC213
	.string "뭐어!? 그럼 {STR_VAR_1}{K_EULREUL}\n"
	.string "아무것도 안 지닌 상태로 내보내도 돼?$"
	@ エェ!? じゃあ §いにはｎ
	@ なにも もたせなくて いいって こと!?

gText_ApprenticeThanksNoHeldItem12:: @ 82BC247
	.string "아무것도 지니게 하지 말라니!\n"
	.string "그럼 말한 대로 할게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!!$"
	@ もたせないってエェ!ｎ
	@ じゃ いうとおりに するよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeThanksHeldItem12:: @ 82BC2DD
	.string "{STR_VAR_1}{K_I}라고!\n"
	.string "그럼 바로 지니게 해볼게!!\p"
	.string "앗 근데 {PLAYER}님\n"
	.string "나 잊으면 안 돼!\l"
	.string "또 보자!!$"
	@ §いだってエェ!ｎ
	@ じゃ さっそく もたせてみるよ!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeItemAlreadyRecommended12:: @ 82BC373
	.string "잠깐 기다려봐!\n"
	.string "그 {STR_VAR_1}{K_I}라고 하는 거\l"
	.string "전에 들은 적 있는데!? 있다고!!\p"
	.string "다른 걸 알려줘!\n"
	.string "아니면 {STR_VAR_2}{K_EULREUL}\l"
	.string "빈손으로 내보내라는 거야!?$"
	@ ちょっと まったァ!ｎ
	@ その §いってｌ
	@ まえに きいたことが ある!? ある!!ｐ
	@ ほかのを おしえて!ｎ
	@ それとも §うにはｌ
	@ なにも もたせなくて いいって こと!?

gText_ApprenticeWhatHeldItem13:: @ 82BC40E
	.string "크헉 아야야! {PLAYER}\n"
	.string "팔이 부러졌으니까 만지지 말아줘!\p"
	.string "포켓몬에게 무엇을 지니게 할지\n"
	.string "스스로 이것저것 시험해보다가\l"
	.string "팔이 부러진 걸 거야 분명!\p"
	.string "그렇게 됐으니까 말이야\n"
	.string "대신 정해주라!\p"
	.string "{PLAYER}{K_EUNNEUN} 내 {STR_VAR_1}에게\n"
	.string "어떤 도구를 지니게 하면 좋을 것 같아?$"
	@ ギャッ いててっ! §あ§おｎ
	@ うでが おれてるから さわらないでよ!ｐ
	@ ポケモンに なにを もたせるかｎ
	@ じぶんで いろいろ ためしすぎちゃってｌ
	@ うでが おれちゃったん だよね きっと!ｐ
	@ というわけ だからさｎ
	@ かわりに きめて くれよ!ｐ
	@ §あ§おはさ おれの §いｎ
	@ どんな どうぐ もたせたら いいとおもう?

gText_ApprenticeHoldNothing13:: @ 82BC514
	.string "아야야... 으음 그 말은\n"
	.string "{STR_VAR_1}에겐 아무것도\l"
	.string "지니게 하지 않아도 된다는 뜻이야?$"
	@ いてて…… え-っと それってｎ
	@ §いには なにも もたせなくてｌ
	@ いいって ことかな?

gText_ApprenticeThanksNoHeldItem13:: @ 82BC555
	.string "응 알았어\n"
	.string "나한테도 그러는 편이 좋겠지!\p"
	.string "앞으로도 나를 잘 부탁한다구!$"
	@ ん わかったｎ
	@ おれも いまは そのほうが たすかるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeThanksHeldItem13:: @ 82BC5CE
	.string "응 알았어 {STR_VAR_1} 말이지!\n"
	.string "그럼 포켓몬은 팔팔하니까\l"
	.string "바로 지니게 해볼게!\p"
	.string "앞으로도 나를 잘 부탁한다구!$"
	@ ん わかった §いな!ｎ
	@ じゃあ ポケモンの うでは ぶじだからｌ
	@ さっそく もたせてみるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeItemAlreadyRecommended13:: @ 82BC666
	.string "아니아니 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "지난번에 알려줬었잖아?\l"
	.string "좀 더 굉장한 걸 알려달라고!\p"
	.string "앗 아니면\n"
	.string "{STR_VAR_1}에겐 아무것도\l"
	.string "지니게 하지 않아도 된다는 뜻이야?$"
	@ いやいや §いはｎ
	@ このあいだ おしえて くれただろ?ｌ
	@ もっと すごいの おしえてくれよ!ｐ
	@ あ それともｎ
	@ §うには なにも もたせなくてｌ
	@ いいって ことかな?

gText_ApprenticeWhatHeldItem14:: @ 82BC714
	.string "아... 아...\n"
	.string "{PLAYER}...\p"
	.string "그 그렇게 보지 말게나\n"
	.string "내 포켓몬은 지닌물건이 없어서 말인데\p"
	.string "잠깐 그... 상담 좀 해주게\n"
	.string "부 부끄럽지만 말일세!\l"
	.string "{STR_VAR_1}{K_IGA} 무엇을\l"
	.string "지니면 강해질지 고민하고 있거든\l"
	.string "{PLAYER} 자네는 뭐가 좋을 것 같나?$"
	@ あ…… あ……ｎ
	@ §あ§お……ｐ
	@ そ そんなに みないで くれよｎ
	@ ワシの ポケモン なにも もってないからさｐ
	@ ちょっと…… そうだん させて くれよｎ
	@ は はずかしいん だけどさ!ｌ
	@ §いが なにをｌ
	@ もったら つよいか って なやんでてさｌ
	@ §あ§お なにが いいと おもう?

gText_ApprenticeHoldNothing14:: @ 82BC808
	.string "그럼... {STR_VAR_1}{K_EUNNEUN} 아무것도\n"
	.string "지니지 않는 편이 좋은 겐가...?$"
	@ じゃ…… §いは なにもｎ
	@ もたない ほうが いいの かな……?

gText_ApprenticeThanksNoHeldItem14:: @ 82BC84D
	.string "아 알겠네!\n"
	.string "도구 없이 가도록 하지!\p"
	.string "으으 떨리는구먼\n"
	.string "너무 멋있는 것 같은데...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 만나면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ どうぐ なしで いくよ!ｐ
	@ うう てれるなｎ
	@ かっこ よすぎない かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeThanksHeldItem14:: @ 82BC8EA
	.string "아 알겠네!\n"
	.string "{STR_VAR_1}에게 지니게 해야겠군\p"
	.string "으으 떨리는구먼\n"
	.string "너무 멋있는 것 같은데...?\p"
	.string "고맙네 {PLAYER}\n"
	.string "다음에 또 만나면... 잘 부탁하네$"
	@ よ よし!ｎ
	@ §いに してみるよｐ
	@ うう てれるなｎ
	@ かっこ よすぎない かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeItemAlreadyRecommended14:: @ 82BC984
	.string "그건 이 이미 알려주었잖나\p"
	.string "나 나를 포기하지 말아주게!\n"
	.string "부디 나를 외면하지 말게나!\p"
	.string "아... 아니면\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 아무것도\l"
	.string "지니지 않는 편이 좋은 겐가...?$"
	@ それは も もう きいた じゃないかｐ
	@ て てを ぬかないでくれ!ｎ
	@ ワシに はじを かかせないで くれ!ｐ
	@ あ…… それともｎ
	@ §うは なにもｌ
	@ もたない ほうが いいの かな……?

gText_ApprenticeWhatHeldItem15:: @ 82BCA4D
	.string "응?\n"
	.string "{PLAYER} 같아 보인다만...\l"
	.string "정말로 자네 맞는 겐가?\l"
	.string "설마 쌍둥이는 아니겠지?\p"
	.string "앗 아닐세 아닐세!\n"
	.string "진짜라면 됐네 잊어주게!\l"
	.string "그리고 상담을 부탁하고 싶다네!\p"
	.string "나의 {STR_VAR_1} 말이다만!\n"
	.string "뭔가 편리한 도구를 건네주고 싶다네\l"
	.string "대체 어느 게 어울릴 것 같나?$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ ほんもの なのかね?ｌ
	@ ふたごの きょうだい って ことは?ｐ
	@ あっ いやいや いやいや!ｎ
	@ ほんもの なら いいんだ わすれてくれ!ｌ
	@ さらに じょげんを おねがい したい!ｐ
	@ この わたしの §い!ｎ
	@ なにか べんりな どうぐを もたせたいｌ
	@ いったい どれが ふさわしい かな?

gText_ApprenticeHoldNothing15:: @ 82BCB75
	.string "아무것도 지니게 하지 않는 편이 좋다고...?\n"
	.string "정말인가?$"
	@ なにも もたない ほうが いい……?ｎ
	@ ほんとうかね?

gText_ApprenticeThanksNoHeldItem15:: @ 82BCBA6
	.string "흐음 그렇군 알겠네\n"
	.string "정말 고맙군\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ いや そうか なら いいんだｎ
	@ どうも ありがとうｐ
	@ では いずれまた あおう!

gText_ApprenticeThanksHeldItem15:: @ 82BCBFC
	.string "{STR_VAR_1}... 정말인가?\p"
	.string "아니 정말이라면 됐네\n"
	.string "정말 고맙군\l"
	.string "이런 나의 포켓몬이라도\l"
	.string "잘 쓸 수 있다면 좋겠어\p"
	.string "그럼 언젠가 다시 보도록 하지!$"
	@ §い…… ほんとうかね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｌ
	@ こんな わたしの ポケモンでもｌ
	@ つかいこなせると いいなｐ
	@ では いずれまた あおう!

gText_ApprenticeItemAlreadyRecommended15:: @ 82BCCA4
	.string "아니아니 기다려주게\n"
	.string "그건 전에 알려주었지 않나\l"
	.string "그것과는 다른 물건을\l"
	.string "추천받고 싶은 거라네\p"
	.string "아니면 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "아무것도 안 지니는 게 좋나...?\l"
	.string "자네 생각은 어떤가?$"
	@ いやいや まってくれｎ
	@ それは まえに おしえてくれた だろうｌ
	@ それとは ちがった ものをｌ
	@ すすめられて みたいんだｐ
	@ それとも §うはｎ
	@ なにも もたない ほうが いい……?ｌ
	@ ほんとうかね?

gText_ApprenticeWhichMonFirst0:: @ 82BCD68
	.string "우엥- {PLAYER}님!\n"
	.string "저 곤란해하고 있었어요 훌쩍\p"
	.string "슬슬 승부를 해보고 싶은데\n"
	.string "포켓몬을 어떤 순서로\l"
	.string "내보내는 게 좋을지 모르겠어서...\p"
	.string "{PLAYER}님이라면\n"
	.string "어느 포켓몬을 처음에 내보낼 건가요?\l"
	.string "...알려주세요!$"
	@ え-ん §あさ-ん!ｎ
	@ ぼく こまって いるんです グスンｐ
	@ そろそろ しょうぶを して みたいけどｎ
	@ ポケモンを どんな じゅんばんでｌ
	@ だしたら つよいのか わかんない……ｐ
	@ §あさん だったらｎ
	@ どの ポケモンを さいしょに だすかｌ
	@ ……おしえて ください!

gText_ApprenticeMonFirstThanks0:: @ 82BCE64
	.string "{STR_VAR_1} 말이군요! 으흑 으아앙-!\p"
	.string "아! 죄송합니다\n"
	.string "순서를 정해주신 게\l"
	.string "너무 기뻐서 눈물이...\p"
	.string "그럼 감사했습니다!$"
	@ §い ですね! うぅ うわ-ん!ｐ
	@ あ! ごめんなさいｎ
	@ じゅんばんが きまった うれしさでｌ
	@ なみだが……ｐ
	@ じゃあ ありがとう ございました!

gText_ApprenticeWhichMonFirst1:: @ 82BCEF2
	.string "와앗! {PLAYER}님이다-!\n"
	.string "와아- 만나서 다행이야\l"
	.string "상담하고 싶은 게 있거든!\p"
	.string "저기 있지 내가 지닌\n"
	.string "포켓몬들 중에서\l"
	.string "어느 걸 처음으로 내보내면\l"
	.string "좋을 거라고 생각해?$"
	@ わわっ! §あさんだ-!ｎ
	@ わ-い あえて よかったｌ
	@ そうだん したいことが あるんだ!ｐ
	@ あのね ぼくの もってるｎ
	@ ポケモン たちの なかでｌ
	@ どれを さいしょに だせばｌ
	@ いいと おもう?

gText_ApprenticeMonFirstThanks1:: @ 82BCF61
	.string "{STR_VAR_1} 말이구나 역시 그렇지-!?\n"
	.string "그럼 그렇게 할게-!\p"
	.string "고마워 선생님!$"
	@ §いかあ そ-だよね!ｎ
	@ じゃあ そうする-!ｐ
	@ せんせい ありがと!

gText_ApprenticeWhichMonFirst2:: @ 82BCFA1
	.string "{PLAYER}님 안녕하세요!\n"
	.string "승부할 때 처음에\p"
	.string "어느 포켓몬을 내보낼지가\n"
	.string "무척이나 중요할 거 같은 기분이 들어서요!\p"
	.string "제가 지닌 포켓몬 중에서\n"
	.string "어느 포켓몬을\l"
	.string "처음에 내보내면 좋을까요?$"
	@ §あさん こんにちは!ｎ
	@ しょうぶのときって さいしょにｐ
	@ どの ポケモンを だすのかがｎ
	@ とても だいじな きが するんです!ｐ
	@ ぼくが もってる ポケモンの なかでｎ
	@ どの ポケモンをｌ
	@ さいしょに だすと いいでしょうか?

gText_ApprenticeMonFirstThanks2:: @ 82BD03C
	.string "{STR_VAR_1} 말이죠!\n"
	.string "알겠습니다!\p"
	.string "그럼 또 봬요!$"
	@ §い ですね!ｎ
	@ わかりました!ｐ
	@ じゃあ また!

gText_ApprenticeWhichMonFirst3:: @ 82BD06D
	.string "{PLAYER}님 언제나\n"
	.string "상담만 드려서 죄송합니다...\l"
	.string "저 자신이 없어서\l"
	.string "{PLAYER}님이 없으면 안 돼요...!\p"
	.string "저기 그 포켓몬의 순서 있죠...\n"
	.string "어떻게 해야 좋을 거라 생각하세요?\p"
	.string "저 따위가 고민을 해도\n"
	.string "아무 의미 없을지도 모르지만\l"
	.string "도저히 정하지 못하겠어서...\p"
	.string "어느 포켓몬을 1번\n"
	.string "그러니까 선두로 정하는 게 좋을까요!?$"
	@ §あさん いつもｎ
	@ そうだん ばかりで すみません……ｌ
	@ あたし じしんが なくってｌ
	@ §あさんが いないと……!ｐ
	@ あの ポケモンの じゅんばん って……ｎ
	@ どうすれば いいと おもいますか?ｐ
	@ あたし なんかが こだわってもｎ
	@ しかたが ないかも しれません けどｌ
	@ どうしても きめられなくて……ｐ
	@ どの ポケモンを 1ばんｎ
	@ せんとうに すれば よいんでしょうか!

gText_ApprenticeMonFirstThanks3:: @ 82BD18A
	.string "{STR_VAR_1} 말이군요 알겠습니다!\p"
	.string "이런 저 따위에게\n"
	.string "어떻게든 해답을 제시해 주시다니\l"
	.string "정말 믿기지 않아요!\p"
	.string "오늘 저 따위를 위해\n"
	.string "시간 내주셔서 감사했습니다...!$"
	@ §い ですか わかりました!ｐ
	@ こんな あたし なんかにｎ
	@ なんども こたえて いただけるなんてｌ
	@ しんじられない!ｐ
	@ きょうは あたしなんかの ためにｎ
	@ ありがとう ございました……!

gText_ApprenticeWhichMonFirst4:: @ 82BD222
	.string "{PLAYER}! 나야 나\n"
	.string "마침 잘됐다 곤란해하고 있었거든!\p"
	.string "잠깐 포켓몬의 순서를\n"
	.string "정하는 걸 도와줘야겠어!\l"
	.string "뭐 거창하게 말했지만\l"
	.string "1번째 포켓몬만 정해주면 돼\l"
	.string "어느 포켓몬으로 하면 좋을까?$"
	@ §あ§お! わたしよｎ
	@ よかったわ こまっていたの!ｐ
	@ ちょっと ポケモンの じゅんばんをｎ
	@ きめて もらえる かしら!ｌ
	@ と いっても そうねえｌ
	@ とりあえず 1ばんめの ポケモンで いいわｌ
	@ どの ポケモンに したら いいかしら?

gText_ApprenticeMonFirstThanks4:: @ 82BD325
	.string "{STR_VAR_1} 말이지 알았어!\n"
	.string "{PLAYER}{K_IGA} 정해줬다고 생각하니\l"
	.string "져도 마음이 편할 것 같아!\p"
	.string "그럼 안녕\n"
	.string "다음에 또 상담해줘!$"
	@ §いね いいわ!ｎ
	@ §あ§おが きめた って おもえばｌ
	@ まけても きが らくだわ!ｐ
	@ じゃあねｎ
	@ また そうだんに のってね!

gText_ApprenticeWhichMonFirst5:: @ 82BD3B1
	.string "하이! 이 몸의 선생님\n"
	.string "{PLAYER}!\p"
	.string "난 오늘도 바쁘다구\n"
	.string "사이클링에 조깅에 허밍에!\p"
	.string "승부에 내보낼 포켓몬의\n"
	.string "순서조차 못 정하겠단 말이지-\p"
	.string "저기 있잖아!\n"
	.string "잠깐 내 포켓몬 좀 봐주라!\l"
	.string "어느 녀석이 처음으로 나가야 좋을까?$"
	@ ハイ! オレの せんせいｎ
	@ §あ§お!ｐ
	@ きょうも いそがしいんだ オレｎ
	@ サイクリングに ショッピングに ハミング!ｐ
	@ しょうぶに つかう ポケモンのｎ
	@ じゅんばんさえ きめられなくてね-ｐ
	@ あのさ!ｎ
	@ ちょっと オレの ポケモン みてよ!ｌ
	@ で どいつが はじめに でれば いいかな?

gText_ApprenticeMonFirstThanks5:: @ 82BD493
	.string "오케이 알았어!\n"
	.string "{STR_VAR_1}{K_EULREUL} 선두에\l"
	.string "서게 할 시간 정도는 있으니까!\p"
	.string "...어이쿠 여자친구가 기다리겠다!\n"
	.string "땡큐! 그럼 또 보자!$"
	@ オ-ケ- わかった!ｎ
	@ §いを せんとうに するｎ
	@ じかん くらいは あるぜ!ｐ
	@ ……と いけね かのじょが まってる!ｎ
	@ サンキュ-! じゃ またな!

gText_ApprenticeWhichMonFirst6:: @ 82BD51C
	.string "Yoohoo! Hiya, {PLAYER}!\n"
	.string "You always walk around looking tough!\p"
	.string "Listen, I need something from you\n"
	.string "again! It's the usual thing!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is about my team.\p"
	.string "Which POKéMON of mine should be first\n"
	.string "to go out in a battle?$"
	@ ヤッホ- ハ-イ §あさ-んｎ
	@ いつも つよそうな かおで あるいてるわねｐ
	@ ねえねえ! きょうもｎ
	@ あれ…… おねがい! いいでしょ!ｐ
	@ ジャ-ン では ほんじつの そうだん!ｎ
	@ わたしが もっている ポケモン!ｌ
	@ さあ どのコを いちばんｌ
	@ さいしょに だせば いいでしょう?

gText_ApprenticeMonFirstThanks6:: @ 82BD609
	.string "Hmhm!\n"
	.string "My {STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"
	@ ふむふむ!ｎ
	@ §い ですねぇ?ｌ
	@ シブイ おこたえ ありがとう!ｐ
	@ ん きょうは こんなところ かなｎ
	@ こんど また ここで あおうね!ｌ
	@ ありがと!

gText_ApprenticeWhichMonFirst7:: @ 82BD697
	.string "Thank you so much for stopping to\n"
	.string "chat with me, {PLAYER}.\p"
	.string "I know I'm taking advantage of your\n"
	.string "kindness, but may I ask for advice?\p"
	.string "I would like you to decide on the order\n"
	.string "of my POKéMON team.\p"
	.string "It would please me if you could decide\n"
	.string "which POKéMON should come first.$"
	@ はなしかけて くださってｎ
	@ ありがとう ございます §あさんｐ
	@ その おやさしさに あまえてｎ
	@ きょうも そうだんが ありますの……ｐ
	@ あの ポケモンの じゅんばんをｎ
	@ きめて いただきたいん ですのｐ
	@ さいしょに だす ならｎ
	@ どの ポケモンが よろしいでしょうか?

gText_ApprenticeMonFirstThanks7:: @ 82BD797
	.string "My {STR_VAR_1} it is!\n"
	.string "I will put it first right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"
	@ §い ですのね!ｎ
	@ すぐに ならびかえますわ!ｐ
	@ それでは §あさんｎ
	@ これからも よろしく おねがいしますわｌ
	@ ごきげんよう!

gText_ApprenticeWhichMonFirst8:: @ 82BD806
	.string "Eek! {PLAYER}!\n"
	.string "I… I'm overjoyed to see you again!\p"
	.string "My POKéMON have become much\n"
	.string "stronger!\p"
	.string "But I don't always win. It seems to\n"
	.string "depend on which POKéMON goes first.\p"
	.string "{PLAYER}, please, I need your help!\p"
	.string "Please decide which of my POKéMON\n"
	.string "should go out first!$"
	@ キャ-キャ-!ｎ
	@ §あ さ-んっ!ｌ
	@ きょうも あえて かんげきっ……!ｐ
	@ わたしの ポケモンたちｎ
	@ つよく なりましたよ!ｌ
	@ でも はじめに だす ポケモンでｌ
	@ かったり まけたり しちゃうんですｐ
	@ §あさん おねがいが!ｎ
	@ どのコを はじめに だしたら いいのかｌ
	@ ぜひ きめて ほしいのですっ!

gText_ApprenticeMonFirstThanks8:: @ 82BD8F5
	.string "Sigh… I'm overwhelmed with happiness…\p"
	.string "It's like a dream having you decide\n"
	.string "for me, {PLAYER}.\p"
	.string "But perfectly understood!\n"
	.string "I will go with my {STR_VAR_1} first!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"
	@ はあああ…… しあわせすぎるｎ
	@ §あさんに きめて もらうなんて!ｌ
	@ りょうかいですっ! わたしｌ
	@ §いから いくで ありますっ!ｐ
	@ では また こんどｎ
	@ いろいろと おしえて くださいね!

gText_ApprenticeWhichMonFirst9:: @ 82BD9BE
	.string "Hello, hello!\n"
	.string "My mentor, {PLAYER}{KUN}!\l"
	.string "Hit me with your sage advice today!\p"
	.string "You see, I pulled together a team of\n"
	.string "three POKéMON. So far so good.\p"
	.string "But the team's battling order's not\n"
	.string "settled yet.\p"
	.string "This is where you come in, {PLAYER}{KUN}!\n"
	.string "You decide which POKéMON leads off!\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"
	@ ハロ-ウ!ｎ
	@ マイ ティ-チャ- §あ§おｌ
	@ きょうも アドバイス バンバンたのむよ!ｐ
	@ おじさん スリ- ポケモンズでｎ
	@ ティ-ムを つくったのは いいんだがｌ
	@ まだ じゅんばんが きまって ないんだよｐ
	@ そこで! §あ§おがｎ
	@ まず はじめに だす ポケモンをｌ
	@ ササ-っと きめちゃって くれ!

gText_ApprenticeMonFirstThanks9:: @ 82BDAE1
	.string "Uh-huh, my {STR_VAR_1} leads off!\n"
	.string "OK, A-OK!\l"
	.string "I'll reorder the lineup, like, wham!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"
	@ あはぁ §いねｎ
	@ オ-ケイ オ-ケイ!ｌ
	@ おじさん ガガ-っと いれかえるよ!ｐ
	@ それじゃあ これからも よろしくねｎ
	@ アディオ-ス!

gText_ApprenticeWhichMonFirst10:: @ 82BDB4E
	.string "{PLAYER}{KUN}, listen!\n"
	.string "It's a crisis!\p"
	.string "My POKéMON, all three of them, go into\n"
	.string "battle at once!\p"
	.string "Of course that's impossible!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at thinking about\l"
	.string "how I should line up my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "POKéMON should go first, master?$"
	@ §あ§お きいてくれ たいへんだ!ｎ
	@ おいらの ポケモンと きたらｌ
	@ 3びき いっしょに とびだすんだよ!ｌ
	@ ……なんて わきゃ ないな わはは!ｐ
	@ じつは おいら ポケモンのｎ
	@ じゅんばん なんて きめるのｌ
	@ あんまり とくいじゃ なくてさ!ｌ
	@ ひとつ どうだろ おいらの ポケモンｌ
	@ どいつを さいしょに だしたら いいかｌ
	@ ししょうが きめて くれない かな?

gText_ApprenticeMonFirstThanks10:: @ 82BDC6B
	.string "Okay, so it's my {STR_VAR_1} you chose?\n"
	.string "I'll let any but that one go first!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"
	@ そうかｎ
	@ §いが いいのね!ｌ
	@ じゃあ そいつだけは やめようっと!ｐ
	@ …… なんて じょうだん!ｎ
	@ ちゃんと ししょうの いうこと きくよｐ
	@ ありがとう ししょう!ｎ
	@ また あったら よろしくな-

gText_ApprenticeWhichMonFirst11:: @ 82BDD0D
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I present to you a question\l"
	.string "that's pretty fly!\p"
	.string "It's a team lineup question\n"
	.string "that begs your suggestion!\p"
	.string "Out of this lot, which should go first\n"
	.string "as the first on the spot?$"
	@ こ®ん®に®ち®は!ｎ
	@ は-い こんにちは!ｌ
	@ ノリノリ ふなのりの わしのｌ
	@ きょうの そうだん いってみようよ!ｌ
	@ じゅんばんに かんする そうだんだよ!ｐ
	@ こたえて! この なかでｎ
	@ せんとうに したい ポケモンは どれ?

gText_ApprenticeMonFirstThanks11:: @ 82BDDEC
	.string "Okay, I hear you, sure I do!\n"
	.string "I'll switch them up, that I'll do!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"
	@ §いか-っ! ようよう!ｎ
	@ そんなら ノリノリで いれかえるぜ!ｐ
	@ これからも ヨロシク たのむぜｎ
	@ §あさん!

gText_ApprenticeWhichMonFirst12:: @ 82BDE68
	.string "Yahoo, {PLAYER}!\n"
	.string "How do you do?\p"
	.string "What should I do? Go ahead and ask?\n"
	.string "Uh-huh, I have something to ask!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "You have to decide, which of my\n"
	.string "POKéMON is the first to ride!\l"
	.string "Into battle, I mean to say.$"
	@ ヤァ-フゥ- §あさんじゃ-ん?ｎ
	@ どうする オレ? アレきいてみる!?ｌ
	@ そうだんが あるんだけど きいてェ!ｌ
	@ って きいてる!? きいてる!!ｐ
	@ オレの ポケモンの うち どいつをｎ
	@ さいしょに だしたら いいか きめてエェ!

gText_ApprenticeMonFirstThanks12:: @ 82BDF4D
	.string "My {STR_VAR_1}? Yes!\n"
	.string "That'll do, there's no distress!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"
	@ §いだって! イエス!ｎ
	@ じゃ そうしてみる!!ｐ
	@ って §あさんｎ
	@ オレの こと わすれんなよ!ｌ
	@ また あおうぜ!!

gText_ApprenticeWhichMonFirst13:: @ 82BDFD8
	.string "…Oof…ooch… {PLAYER}{KUN}…\n"
	.string "My stomach's hurting all of a sudden…\p"
	.string "…It's getting better now…\p"
	.string "I must've worried myself sick racking\n"
	.string "my brains on how I should line up\l"
	.string "my posse of POKéMON.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, which of my POKéMON should\n"
	.string "go first? So I'd win, I mean.$"
	@ うう §あ§お ……ｎ
	@ おなか いたくってさ ちょっとまって……ｐ
	@ ……ああ なおってきた……ｐ
	@ どの ポケモンを しょうぶのときｎ
	@ さいしょに だすか なやんで いてｌ
	@ なやみ すぎちゃったん だよね きっと!ｐ
	@ というわけ だからさｎ
	@ かわりに きめて くれよ!ｐ
	@ §あ§おはさ おれの ポケモンｎ
	@ どれを さいしょに だせばｌ
	@ かてると おもうかい?

gText_ApprenticeMonFirstThanks13:: @ 82BE0FD
	.string "Hm, all right.\n"
	.string "My {STR_VAR_1} goes first.\p"
	.string "I'll fix the lineup like that after\n"
	.string "I have my supper.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"
	@ ん わかった §いな!ｎ
	@ じゃあ ごはんを たべたらｌ
	@ そういうふうに してみるよ!ｐ
	@ これからも おれを よろしく たのむよ!

gText_ApprenticeWhichMonFirst14:: @ 82BE189
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me feel all flustered.\p"
	.string "Um…\n"
	.string "I really need your advice.\p"
	.string "It makes me bashful to say this,\n"
	.string "but I chose my 3-POKéMON team.\l"
	.string "I can't decide on the order, though.\p"
	.string "Which POKéMON should I send out first\n"
	.string "so I at least look capable?$"
	@ あ…… あ……ｎ
	@ §あ§お だよね?ｌ
	@ そ そんなに みないで くれよ!ｌ
	@ てれるだろｌ
	@ ひとつ…… そうだん させてよｐ
	@ は はずかし ながらｎ
	@ ポケモン 3びき きまった けどさｌ
	@ じゅんばんが きまらないんだよｐ
	@ どの ポケモンを 1ばんめにｎ
	@ だせば かっこが つくの かな……?

gText_ApprenticeMonFirstThanks14:: @ 82BE2A5
	.string "Oh… Okay!\n"
	.string "I'll lead with my {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"
	@ よ よし!ｎ
	@ §いから だして みるよｐ
	@ うう はずかし がらずにｎ
	@ がんばれる かな……?ｐ
	@ ありがとう §あ§おｎ
	@ また こんど あえたら…… よろしくね

gText_ApprenticeWhichMonFirst15:: @ 82BE33E
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps you're a clever look-alike?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are {PLAYER}, please\l"
	.string "forget about my rudeness.\p"
	.string "What I would like is your fine advice.\p"
	.string "I have here my POKéMON team.\n"
	.string "I would like you to tell me which one\l"
	.string "should go first in a battle.$"
	@ ん?ｎ
	@ §あ§おの ように みえるが……ｌ
	@ かげむしゃ って ことは ないだろうねｐ
	@ いやいやいや! ほんものなら いいんだｎ
	@ おこらないで くれ!ｌ
	@ そして じょげんを おねがい したい!ｐ
	@ わたしの てもちの なかからｎ
	@ どのポケモンを しょうぶの はじめにｌ
	@ だせば いいのか おしえて ほしい

gText_ApprenticeMonFirstThanks15:: @ 82BE46C
	.string "My {STR_VAR_1}…\n"
	.string "You aren't pulling my leg?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I am as you see, but I shall do\n"
	.string "my best.\p"
	.string "Let us meet again!$"
	@ §い……ｎ
	@ うそでは ないだろうね?ｐ
	@ いや ほんとう なら いいんだｎ
	@ どうも ありがとうｌ
	@ こんな わたしだが がんばって みようｐ
	@ では いずれまた あおう!

gText_ApprenticeWhichMon0:: @ 82BE50D
	.string "Snivel…\n"
	.string "Oh, {PLAYER}!\p"
	.string "What perfect timing!\n"
	.string "There's something I just can't decide…\p"
	.string "I can't decide which POKéMON I should\n"
	.string "be using.\p"
	.string "I can't decide between the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "{PLAYER}, which do you think will give\n"
	.string "even me a chance at winning?$"

gText_ApprenticeMonThanks0:: @ 82BE5F5
	.string "Snivel… I… I understand!\n"
	.string "Oh! I'm so sorry!\l"
	.string "You've made me so happy, I'm crying…\p"
	.string "I'll do my best to catch one\n"
	.string "{STR_VAR_1}!\p"
	.string "Thank you so much!$"

gText_ApprenticeWhichMon1:: @ 82BE679
	.string "Yay! It's {PLAYER}!\n"
	.string "Yay, you came at the right time, too!\l"
	.string "I need your advice again!\p"
	.string "Um, I'm all mixed up--should I use\n"
	.string "my {STR_VAR_1} or {STR_VAR_2}…\p"
	.string "Which do you think I should raise,\n"
	.string "{PLAYER}?$"

gText_ApprenticeMonThanks1:: @ 82BE71E
	.string "Oh, so my {STR_VAR_1} is better!\n"
	.string "Okay, I'll do that!\p"
	.string "Thanks for teaching me!$"

gText_ApprenticeWhichMon2:: @ 82BE762
	.string "{PLAYER}, hello!\n"
	.string "I have a question I wanted to ask.\p"
	.string "I'm in a dilemma over whether I should\n"
	.string "raise one {STR_VAR_1} or {STR_VAR_2}.\p"
	.string "Which POKéMON do you think will\n"
	.string "be stronger?$"

gText_ApprenticeMonThanks2:: @ 82BE7F8
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go catch a strong {STR_VAR_1}\n"
	.string "right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMon3:: @ 82BE850
	.string "Hello, {PLAYER}…\p"
	.string "Um, you've probably already forgotten\n"
	.string "about someone like me…\p"
	.string "…But that doesn't matter if you\n"
	.string "could give me advice…\p"
	.string "I can't decide on the one kind of\n"
	.string "POKéMON I should raise…\p"
	.string "I've narrowed the field to the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, but that's\l"
	.string "where I became stuck…\p"
	.string "{PLAYER}, you probably don't want to\n"
	.string "bother, but please decide for me.$"

gText_ApprenticeMonThanks3:: @ 82BE99C
	.string "But will a wild {STR_VAR_1} even pay\n"
	.string "attention to me?\p"
	.string "I will try!\p"
	.string "But will I even be able to catch one…\n"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMon4:: @ 82BEA1B
	.string "Oh, {PLAYER}{KUN}! I'm so glad to see you!\n"
	.string "I was about to go looking for you!\p"
	.string "Can you decide what kind of POKéMON\n"
	.string "I should use?\p"
	.string "For instance…\n"
	.string "How about the POKéMON {STR_VAR_1}\l"
	.string "and {STR_VAR_2}?\p"
	.string "Which one do you think would be\n"
	.string "better?$"

gText_ApprenticeMonThanks4:: @ 82BEAE9
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMon5:: @ 82BEB72
	.string "If it isn't {PLAYER}{KUN}! How's it going?\n"
	.string "I'm busy again as always!\p"
	.string "I want to do good with POKéMON, too,\n"
	.string "but I haven't been able to decide\l"
	.string "which POKéMON I should use.\p"
	.string "You know how {STR_VAR_1} look strong?\n"
	.string "But {STR_VAR_2} are tough to ignore.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which one'd be good for me?$"

gText_ApprenticeMonThanks5:: @ 82BEC8E
	.string "Okay, gotcha.\n"
	.string "I'll find time somehow and catch me\l"
	.string "that {STR_VAR_1} you recommended.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMon6:: @ 82BED16
	.string "Oh!\n"
	.string "Yay, it's {PLAYER}!\p"
	.string "I didn't waste any time boasting to\n"
	.string "my friends about meeting you!\p"
	.string "I need to tap your mind again today.\n"
	.string "It's an easy one for you!\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "If I were to raise a POKéMON,\n"
	.string "and the choices were one {STR_VAR_1}\l"
	.string "or {STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks6:: @ 82BEE29
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMon7:: @ 82BEEB4
	.string "Oh, is it you, {PLAYER}?\n"
	.string "I'm delighted to see you again!\p"
	.string "Ever since I became your apprentice,\n"
	.string "my confidence has been blooming.\p"
	.string "I think I'm ready to raise a POKéMON\n"
	.string "of my own!\p"
	.string "{PLAYER}, may I impose on you to choose\n"
	.string "which POKéMON I should raise?\p"
	.string "The choices are the POKéMON\n"
	.string "{STR_VAR_1} or {STR_VAR_2}…\l"
	.string "Which POKéMON is right for me?$"

gText_ApprenticeMonThanks7:: @ 82BEFE2
	.string "One {STR_VAR_1} it is!\n"
	.string "I will find one right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMon8:: @ 82BF04E
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Oh-oh-oh, I know!\n"
	.string "I shouldn't pass up this opportunity!\p"
	.string "May I ask a huge favor, {PLAYER}?\n"
	.string "Please choose a POKéMON for me!\p"
	.string "Please decide which would be better,\n"
	.string "{STR_VAR_1} or {STR_VAR_2}!$"

gText_ApprenticeMonThanks8:: @ 82BF11D
	.string "Wow! You decided for me!\n"
	.string "One {STR_VAR_1} is what I'll raise to\l"
	.string "the best of my ability.\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMon9:: @ 82BF1A8
	.string "Hey, hey!\n"
	.string "My mentor, {PLAYER}{KUN}!\p"
	.string "Hello, I've been looking for you\n"
	.string "for some more of your sage advice!\p"
	.string "Which kind of POKéMON would be right\n"
	.string "for me, one {STR_VAR_1} or {STR_VAR_2}?\p"
	.string "Don't be shy now.\n"
	.string "Let's blurt it out!$"

gText_ApprenticeMonThanks9:: @ 82BF268
	.string "Uh-huh, one {STR_VAR_1} it is!\n"
	.string "OK, A-OK!\l"
	.string "I'll get one in a BALL, like, cram!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10:: @ 82BF2D1
	.string "{PLAYER}{KUN}, listen! Big news!\n"
	.string "I caught a mirage POKéMON!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at catching\l"
	.string "POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of POKéMON I should catch,\l"
	.string "master?\p"
	.string "Which would be better?\n"
	.string "{STR_VAR_1} or {STR_VAR_2}?$"

gText_ApprenticeMonThanks10:: @ 82BF3CF
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll grab the other kind, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMon11:: @ 82BF46A
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "Surely you remember who am I?\p"
	.string "Today, I have a POKéMON question\n"
	.string "that begs your suggestion!\p"
	.string "I have the choice between this\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, you see.\l"
	.string "Which is the one to catch for me?$"

gText_ApprenticeMonThanks11:: @ 82BF551
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go get me one right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMon12:: @ 82BF5C3
	.string "Oh, wow, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "It's been a long time. Let me break\n"
	.string "the ice. I'm also looking for advice!\l"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\p"
	.string "My POKéMON--which should I use?\n"
	.string "It's either {STR_VAR_1} or {STR_VAR_2}.\l"
	.string "Which do you choose?$"

gText_ApprenticeMonThanks12:: @ 82BF6E5
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMon13:: @ 82BF773
	.string "Oh, hi, {PLAYER}{KUN}…\n"
	.string "I have this horrible headache…\p"
	.string "I must've worried too much about\n"
	.string "the kind of POKéMON I should raise.\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "the POKéMON {STR_VAR_1} and\l"
	.string "{STR_VAR_2}, which should it be?$"

gText_ApprenticeMonThanks13:: @ 82BF869
	.string "Hm, one {STR_VAR_1}, all right.\n"
	.string "I'll go look for one when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMon14:: @ 82BF8DD
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide which POKéMON to use.\p"
	.string "If the choices were {STR_VAR_1} or\n"
	.string "{STR_VAR_2}, which would be better?$"

gText_ApprenticeMonThanks14:: @ 82BF9BA
	.string "Oh… Okay!\n"
	.string "I'll do my best with one {STR_VAR_1}.\p"
	.string "I hope I can do my best without\n"
	.string "getting all flustered.\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMon15:: @ 82BFA5A
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "Incidentally, I would like to obtain\l"
	.string "your advice.\p"
	.string "It's about the POKéMON I am to use.\p"
	.string "If the choices are the POKéMON\n"
	.string "{STR_VAR_1} and {STR_VAR_2}, which is\l"
	.string "more worthy of me?$"

gText_ApprenticeMonThanks15:: @ 82BFB4E
	.string "{STR_VAR_1}?\n"
	.string "Are you certain?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even I can\n"
	.string "handle with aplomb.\p"
	.string "Let us meet again!$"

gText_ApprenticeWhichMove0:: @ 82BFBF2
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Snivel… Hiccup…\p"
	.string "I have a dilemma!\n"
	.string "I can't decide on a move for\l"
	.string "my {STR_VAR_1}…\p"
	.string "Please, please, {PLAYER}.\n"
	.string "Can you decide for me?\p"
	.string "For my {STR_VAR_1}, which move would\n"
	.string "be the better choice: {STR_VAR_2}\l"
	.string "or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0:: @ 82BFCAE
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! I'm so sorry, {PLAYER}!\n"
	.string "You've made me so happy by deciding\l"
	.string "the move, I'm crying…\p"
	.string "Snivel…\n"
	.string "Thank you so much!$"

gText_ApprenticeWhichMove1:: @ 82BFD26
	.string "Yay! Hi, {PLAYER}!\n"
	.string "I need your advice again!\p"
	.string "I want to teach my {STR_VAR_1}\n"
	.string "a cool move.\p"
	.string "I like either of the moves\n"
	.string "{STR_VAR_2} or {STR_VAR_3}.\l"
	.string "What's your recommendation?$"

gText_ApprenticeMoveThanks1:: @ 82BFDB1
	.string "{STR_VAR_1} is better? I guess so!\n"
	.string "Okay, I'll go with that!\p"
	.string "If we meet here again, please teach\n"
	.string "me something else, teacher!$"

gText_ApprenticeWhichMove2:: @ 82BFE24
	.string "{PLAYER}, hello!\n"
	.string "It's about my {STR_VAR_1}, but I'm\l"
	.string "worried about its moves.\p"
	.string "You see, it's the moves {STR_VAR_2}\n"
	.string "and {STR_VAR_3}.\p"
	.string "Which is stronger and better for\n"
	.string "my {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2:: @ 82BFEAD
	.string "{STR_VAR_1} is your choice?\n"
	.string "Okay, I got it!\p"
	.string "I'll go teach {STR_VAR_1} to\n"
	.string "my POKéMON right away!\p"
	.string "See you again!$"

gText_ApprenticeWhichMove3:: @ 82BFF0A
	.string "Ohhh, {PLAYER}…\n"
	.string "I'm hopeless, no, really!\p"
	.string "I've decided to raise a POKéMON,\n"
	.string "but now I can't even decide what\l"
	.string "move I should let it learn…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, could you choose\n"
	.string "a move for my {STR_VAR_1}?\p"
	.string "If you could even choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3:: @ 82C0032
	.string "I understand!\p"
	.string "But will it even be willing to learn\n"
	.string "{STR_VAR_1} for me…\l"
	.string "No! I'll do my best!\p"
	.string "Thank you!$"

gText_ApprenticeWhichMove4:: @ 82C0090
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "I was just hoping to see you, too!\p"
	.string "I was wondering what move would\n"
	.string "be suitable for my {STR_VAR_1}.\p"
	.string "I can't decide, so can you decide\n"
	.string "for me instead?\p"
	.string "For instance… How about the moves\n"
	.string "{STR_VAR_2} and {STR_VAR_3}?\l"
	.string "Which one would be better?$"

gText_ApprenticeMoveThanks4:: @ 82C016E
	.string "{STR_VAR_1}? That's great!\p"
	.string "Knowing that you made the decision,\n"
	.string "{PLAYER}{KUN}, I won't be so upset if\l"
	.string "I lose.\p"
	.string "Okay, I'll look to you for advice again.\n"
	.string "Bye!$"

gText_ApprenticeWhichMove5:: @ 82C01F7
	.string "How could things be this busy?\n"
	.string "Hey, if it isn't {PLAYER}{KUN}!\l"
	.string "How's it going?\p"
	.string "Since I got up this morning, I've done\n"
	.string "my jogging, swimming, and cooking!\p"
	.string "You wouldn't believe how busy I am!\p"
	.string "I can't even decide what move\n"
	.string "my {STR_VAR_1} should learn!\p"
	.string "{STR_VAR_2} looks good, huh?\n"
	.string "But {STR_VAR_3}'s also decent.\p"
	.string "{PLAYER}{KUN}, give me some of your good\n"
	.string "advice! Which move'd be good for me?$"

gText_ApprenticeMoveThanks5:: @ 82C034C
	.string "Okay, gotcha.\n"
	.string "I'll make room in my schedule and\l"
	.string "teach that move.\p"
	.string "I'm glad I met a good mentor in you.\n"
	.string "Thanks! See you around!$"

gText_ApprenticeWhichMove6:: @ 82C03CA
	.string "Oh! Lucky!\n"
	.string "I met you again, {PLAYER}!\l"
	.string "I need to tap your mind again today.\p"
	.string "Drum roll, please!\n"
	.string "The question I have is…\p"
	.string "For my {STR_VAR_1}, which is the move\n"
	.string "best suited, {STR_VAR_2} or\l"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6:: @ 82C046E
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, you say!\l"
	.string "Thanks for a most cool answer!\p"
	.string "I guess that's about all I wanted\n"
	.string "to ask you today.\p"
	.string "Let's meet here again, okay?\n"
	.string "Thanks!$"

gText_ApprenticeWhichMove7:: @ 82C04F9
	.string "Oh, hello, {PLAYER}.\n"
	.string "I trust you've been well?\p"
	.string "I have to seek your advice again.\n"
	.string "It's about my dearest {STR_VAR_1}.\p"
	.string "What would be the ideal move for\n"
	.string "my lovable {STR_VAR_1}?\l"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7:: @ 82C0598
	.string "{STR_VAR_1} it is!\n"
	.string "I will teach that right away!\p"
	.string "Thank you, {PLAYER}.\n"
	.string "I hope I can count on you again.\l"
	.string "Please take care!$"

gText_ApprenticeWhichMove8:: @ 82C0602
	.string "Eek! {PLAYER}! I met you again!\n"
	.string "I… I'm overjoyed!\p"
	.string "Whenever I'm in need, you're always\n"
	.string "there for me, {PLAYER}!\p"
	.string "Today, I want you to recommend\n"
	.string "a move for me!\p"
	.string "Please choose a move for\n"
	.string "my {STR_VAR_1}!\p"
	.string "Which move would be better,\n"
	.string "{STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8:: @ 82C06D8
	.string "Oh-oh-oh! Thank you!\n"
	.string "{STR_VAR_1} is it!\l"
	.string "Perfectly understood!\p"
	.string "I hope you'll be willing to teach me\n"
	.string "some more another time.$"

gText_ApprenticeWhichMove9:: @ 82C074A
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "I'm hoping for some more of\l"
	.string "your sage advice today!\p"
	.string "What would be the best move for\n"
	.string "my {STR_VAR_1}?\p"
	.string "It should be something that'll\n"
	.string "let me win just like that!\p"
	.string "Would it be {STR_VAR_2}?\n"
	.string "Or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9:: @ 82C0809
	.string "Uh-huh, {STR_VAR_1} it is!\n"
	.string "Si, bueno!\l"
	.string "I'll get it taught, like, ka-blam!\p"
	.string "All right, thanks, as always!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10:: @ 82C086E
	.string "{PLAYER}{KUN}, it's completely wild!\p"
	.string "My POKéMON!\n"
	.string "It learned six moves!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at choosing moves\l"
	.string "for my POKéMON.\p"
	.string "So, how about deciding for me which\n"
	.string "kind of move I should teach?\p"
	.string "{STR_VAR_2} or {STR_VAR_3}--which\n"
	.string "would go with my {STR_VAR_1} best?$"

gText_ApprenticeMoveThanks10:: @ 82C0982
	.string "Okay, so it's {STR_VAR_1} you chose?\n"
	.string "I'll choose another move, then!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks, master!\n"
	.string "I hope you'll keep teaching me!$"

gText_ApprenticeWhichMove11:: @ 82C0A1D
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "I'm always with it, don't ask me why.\p"
	.string "Today, I have a move question\n"
	.string "that begs your suggestion!\p"
	.string "{STR_VAR_2} and {STR_VAR_3} are\n"
	.string "the moves. What would be the best\l"
	.string "for my {STR_VAR_1} so it grooves?$"

gText_ApprenticeMoveThanks11:: @ 82C0AFD
	.string "{STR_VAR_1}, you say, hey, hey!\n"
	.string "I'll go teach that right away!\p"
	.string "If it's advice I ever need,\n"
	.string "{PLAYER}, your word I'll always heed!$"

gText_ApprenticeWhichMove12:: @ 82C0B6F
	.string "Oh, yeahah, if it isn't {PLAYER}!\p"
	.string "What should I do? Get your advice?\n"
	.string "Why not? I'm already talking to you!\p"
	.string "{PLAYER}, are you surprised by me?\n"
	.string "I want your advice, can't you see?\p"
	.string "Are you receiving me?\n"
	.string "You are receiving me!\p"
	.string "My {STR_VAR_1}--what should it use?\n"
	.string "It's {STR_VAR_2} or {STR_VAR_3},\l"
	.string "what do you choose?$"

gText_ApprenticeMoveThanks12:: @ 82C0C7D
	.string "If that {STR_VAR_1} is the best,\n"
	.string "I'll do as you suggest!\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me.\p"
	.string "See you again, my smart friend!$"

gText_ApprenticeWhichMove13:: @ 82C0D0B
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "I have this lousy cold, I do…\p"
	.string "I want to pick a move for my POKéMON,\n"
	.string "but I'm not up to it…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me.\p"
	.string "{PLAYER}{KUN}, if I had to choose between\n"
	.string "{STR_VAR_2} and {STR_VAR_3} for\l"
	.string "my {STR_VAR_1}, which would it be?$"

gText_ApprenticeMoveThanks13:: @ 82C0DFE
	.string "Hm, {STR_VAR_1}, all right. Cough!\n"
	.string "I'll go teach it when I get better.\p"
	.string "I hope I can keep hitting you up\n"
	.string "for help like this.$"

gText_ApprenticeWhichMove14:: @ 82C0E71
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Please, don't look at me that way.\n"
	.string "I'm getting all flustered…\l"
	.string "I… I need your advice.\p"
	.string "I… I'm really embarrassed, but I can't\n"
	.string "decide what move I should teach\l"
	.string "my POKéMON.\p"
	.string "It's for my {STR_VAR_1}.\n"
	.string "If the choices were {STR_VAR_2} or\l"
	.string "{STR_VAR_3}, which would be better?$"

gText_ApprenticeMoveThanks14:: @ 82C0F6D
	.string "Oh… Okay!\n"
	.string "I'll try that {STR_VAR_1}.\p"
	.string "I hope I can teach that move…\n"
	.string "This is so nerve-racking…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "If we meet again, I hope you will be\l"
	.string "as helpful.$"

gText_ApprenticeWhichMove15:: @ 82C1003
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really real?\p"
	.string "Perhaps you're one of those popular\n"
	.string "mimics?\p"
	.string "No, no, if you are real, it's fine.\n"
	.string "No need to be upset, I assure you!\p"
	.string "Incidentally, I would like to obtain\n"
	.string "your advice.\p"
	.string "It's about my {STR_VAR_1}.\p"
	.string "Which move would be better for it to\n"
	.string "use, {STR_VAR_2} or {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15:: @ 82C1122
	.string "{STR_VAR_1}?\n"
	.string "There's no question about that?\p"
	.string "I see. If that's the case, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope it is something even\n"
	.string "my POKéMON can learn.\p"
	.string "Let us meet again!$"

gText_ApprenticePickWinSpeech0:: @ 82C11D1
	.string "Oh… {PLAYER}?\n"
	.string "It is {PLAYER}!\l"
	.string "Oh! Sniff…sob… Please, listen!\p"
	.string "I… When I battle, I get so nervous,\n"
	.string "I can't help crying even if I win…\p"
	.string "I wish I could say something cool\n"
	.string "when I win…\p"
	.string "Please, please, {PLAYER}!\n"
	.string "Could you maybe teach me something\l"
	.string "cool to say when I win so I don't cry?$"

gText_ApprenticeWinSpeechThanks0:: @ 82C12D5
	.string "{STR_VAR_1}\p"
	.string "Awesome! Wicked! Awoooh!\n"
	.string "It's really cool!\p"
	.string "Oh… I'm sorry…\n"
	.string "I'm so happy, I'm crying…\p"
	.string "Snivel… {PLAYER}!\n"
	.string "Thank you so much for everything!\p"
	.string "I will battle the best I can for\n"
	.string "your sake, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Next time… We should battle!$"

gText_ApprenticePickWinSpeech1:: @ 82C13AB
	.string "Yay! It's {PLAYER}! Hello!\n"
	.string "I wanted to ask you something!\p"
	.string "I want to say something cool when\n"
	.string "I win a match.\p"
	.string "Do you have a cool saying that\n"
	.string "you could recommend?$"

gText_ApprenticeWinSpeechThanks1:: @ 82C1444
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! That is so cool!\n"
	.string "Okay, I'll say that!\p"
	.string "Thanks for teaching me all this time!\n"
	.string "I'm going to do the best I can\l"
	.string "wherever I go from now on!\p"
	.string "When we meet again, it'll be for\n"
	.string "a battle!$"

gText_ApprenticePickWinSpeech2:: @ 82C1501
	.string "{PLAYER}, hello!\p"
	.string "My POKéMON and I are ready for\n"
	.string "anything, except for one thing.\p"
	.string "I think it would be good if I had\n"
	.string "something to shout when I win.\p"
	.string "Could you think up something good\n"
	.string "to say?$"

gText_ApprenticeWinSpeechThanks2:: @ 82C15B6
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "I will use that!\p"
	.string "I'm going out to battle all over\n"
	.string "the place.\p"
	.string "Who knows, I may even get to battle\n"
	.string "you one day, {PLAYER}.\p"
	.string "Next time, let's meet at a place\n"
	.string "of battle!$"

gText_ApprenticePickWinSpeech3:: @ 82C165E
	.string "Hello, {PLAYER}…\n"
	.string "I'm sorry to bug you, but I'm hopeless…\p"
	.string "Even when…\n"
	.string "Even when I win, I don't have anything\l"
	.string "special to say…\p"
	.string "I know that it doesn't mean anything\n"
	.string "to you, {PLAYER}.\p"
	.string "But it means a lot to me…\p"
	.string "Please, {PLAYER}, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks3:: @ 82C174F
	.string "{STR_VAR_1}\p"
	.string "That's inspired…\p"
	.string "Uh… Is it okay for someone like me\n"
	.string "to even say that?\p"
	.string "No! I'll do my best!\p"
	.string "{PLAYER}, thank you so much for\n"
	.string "putting up with me for so long…\p"
	.string "I promise to do my best from now on.\p"
	.string "I'm sure you'll quickly forget about\n"
	.string "someone like me, but let's meet\l"
	.string "somewhere again!$"

gText_ApprenticePickWinSpeech4:: @ 82C1862
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "There's something I want you to hear.\p"
	.string "I know that I don't always sound\n"
	.string "nice or polite…\p"
	.string "When I win a battle, I think I come\n"
	.string "across as being arrogant.\p"
	.string "I don't want people to dislike me,\n"
	.string "so I want to say something nice to\l"
	.string "someone I beat.\p"
	.string "But I can't think of anything good!\n"
	.string "Could you think something up for me?$"

gText_ApprenticeWinSpeechThanks4:: @ 82C19A0
	.string "{STR_VAR_1}\p"
	.string "Not bad!\n"
	.string "Yup, that's what I'll go with!\p"
	.string "I'm going to hit the road and do what\n"
	.string "I can with what you taught me in\l"
	.string "my head and heart.\p"
	.string "I'm sorry that I've been so pushy\n"
	.string "with you!\p"
	.string "Next time, we battle, okay?\n"
	.string "See you!$"

gText_ApprenticePickWinSpeech5:: @ 82C1A76
	.string "Oh, I can't get over how busy I am!\n"
	.string "Oh, hey, I was looking for you, {PLAYER}{KUN}.\p"
	.string "Are you well as usual?\n"
	.string "Things haven't changed for me at all.\p"
	.string "I've got running, fighting, and mapping\n"
	.string "to do. Why am I so busy?\p"
	.string "But even though I'm busy, it'd be rude\n"
	.string "to just turn on my heels and walk away\l"
	.string "from a win without saying a word.\p"
	.string "So, what would be a cool saying to\n"
	.string "underline my coolness when I'm done\l"
	.string "and walking away? {PLAYER}{KUN}, help me!$"

gText_ApprenticeWinSpeechThanks5:: @ 82C1C16
	.string "{STR_VAR_1}\p"
	.string "Okay, gotcha.\n"
	.string "I can find time to say that!\p"
	.string "Honestly, I'm glad I met a good mentor\n"
	.string "like you.\p"
	.string "I'm going to make time somehow so\n"
	.string "I can get into battling.\p"
	.string "Thanks for everything, {PLAYER}{KUN}!\n"
	.string "We have to battle, you and me, one day!$"

gText_ApprenticePickWinSpeech6:: @ 82C1CF5
	.string "I lucked out again!\n"
	.string "{PLAYER}! Am I glad to see you!\l"
	.string "Like usual, I need your advice!\p"
	.string "Drum roll, please!\n"
	.string "The last question I have is…\p"
	.string "If I win a battle and want to end\n"
	.string "it with a cool flourish, what\l"
	.string "should I say?$"

gText_ApprenticeWinSpeechThanks6:: @ 82C1DC1
	.string "{STR_VAR_1}\p"
	.string "That… That's fabulous!\n"
	.string "It's dignified and cool! I claim it!\p"
	.string "…Listen, I think I'm getting decent\n"
	.string "at this, huh?\p"
	.string "So, I'm thinking of challenging other\n"
	.string "TRAINERS from now on.\p"
	.string "{PLAYER}, your advice really helped me.\p"
	.string "Maybe one day, there'll be a time when\n"
	.string "we battle!\p"
	.string "Thank you for everything!$"

gText_ApprenticePickWinSpeech7:: @ 82C1EDC
	.string "Oh, {PLAYER}.\n"
	.string "I'm so glad I met you!\p"
	.string "I no longer have any concerns with\n"
	.string "regard to my POKéMON.\p"
	.string "It's myself that worries me…\p"
	.string "Do you know how a TRAINER says\n"
	.string "a few things upon winning a battle?\p"
	.string "Definitely, I wish I could do that,\n"
	.string "too!\p"
	.string "Please, what should I say when\n"
	.string "I win a battle?$"

gText_ApprenticeWinSpeechThanks7:: @ 82C1FEC
	.string "{STR_VAR_1}\p"
	.string "Ah! That saying! It refreshes me\n"
	.string "and makes me feel reborn!\p"
	.string "I must use that right away!\p"
	.string "And now, I must take my leave,\n"
	.string "{PLAYER}…\p"
	.string "I will go out to battle many others,\n"
	.string "but never will I forget your teachings.\p"
	.string "Perhaps one day…\n"
	.string "Farewell!$"

gText_ApprenticePickWinSpeech8:: @ 82C20D1
	.string "Eek! I spotted {PLAYER}!\n"
	.string "I… I'm overjoyed to see you!\p"
	.string "Oh-oh-oh! There's something I just\n"
	.string "had to ask you!\p"
	.string "A little while ago, I won a battle.\n"
	.string "That part was giddying!\p"
	.string "But it made me so overjoyed that\n"
	.string "I choked up and couldn't say a thing!\p"
	.string "So now, {PLAYER}, please, I want you to\n"
	.string "think up an exit line for when I win!$"

gText_ApprenticeWinSpeechThanks8:: @ 82C21FF
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "I'm going to say that?!\l"
	.string "I… I'm delirious with joy!\p"
	.string "Th-th-thank you!\n"
	.string "I have nothing left to regret now!\p"
	.string "I'm going to travel now and battle\n"
	.string "all sorts of people.\p"
	.string "Everything, I owe it to you, {PLAYER}.\n"
	.string "Really, really, thank you!\p"
	.string "I've got to go now, but let's meet\n"
	.string "in battle one day!$"

gText_ApprenticePickWinSpeech9:: @ 82C231C
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "You know, I'm getting the itch to roam\n"
	.string "and battle where I may.\p"
	.string "But before I do, I want your advice\n"
	.string "once again, please!\p"
	.string "If I were to win a battle, what would\n"
	.string "be a good boast I could say to my\l"
	.string "fallen TRAINER opponent?$"

gText_ApprenticeWinSpeechThanks9:: @ 82C2407
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, that's sweet!\n"
	.string "Si, bueno!\l"
	.string "I'll try saying that, like, ham!\p"
	.string "And now, it's time to say good-bye!\n"
	.string "Thanks for all sorts of things!\p"
	.string "Give me a battle one day, OK?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10:: @ 82C24B5
	.string "{PLAYER}{KUN}, there's big trouble!\p"
	.string "When I win a battle, I brag about it\n"
	.string "for an hour at least!\p"
	.string "Of course I'm lying!\n"
	.string "Wahahaha!\p"
	.string "This is no lie, though.\n"
	.string "I'm not very good at chatting.\p"
	.string "So, how about deciding for me what\n"
	.string "I should say after winning a battle,\l"
	.string "master?$"

gText_ApprenticeWinSpeechThanks10:: @ 82C25B1
	.string "{STR_VAR_1}\p"
	.string "That's what I should say, huh?\n"
	.string "Then, I'll stay away from that!\p"
	.string "Just kidding!\n"
	.string "I'll obey your teaching, master!\p"
	.string "Thanks for teaching me all this time,\n"
	.string "master!\p"
	.string "I'm finally understanding what being\n"
	.string "a TRAINER is about.\p"
	.string "I'm going to go out and win battles\n"
	.string "against any TRAINER.\p"
	.string "Maybe it'll be you one day, master!\p"
	.string "That's all!\n"
	.string "Farewell, my master!$"

gText_ApprenticePickWinSpeech11:: @ 82C2707
	.string "A-H-O-Y!\n"
	.string "And that spells ahoy!\p"
	.string "The rappin' SAILOR am I!\n"
	.string "This will be my last question,\l"
	.string "don't you cry!\p"
	.string "It's a saying question\n"
	.string "that begs your suggestion!\p"
	.string "If I win a match, what can I say\n"
	.string "in a real cool way?$"

gText_ApprenticeWinSpeechThanks11:: @ 82C27D4
	.string "{STR_VAR_1}\p"
	.string "Perfect! That's what I'll use.\n"
	.string "I was right to make you choose!\p"
	.string "And now, I think it'd be best,\n"
	.string "if I were to fly the nest!\p"
	.string "Thanks for all you taught me.\n"
	.string "I'll be off on a battle spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "And that spells bon voyage,\l"
	.string "to you this is my homage!$"

gText_ApprenticePickWinSpeech12:: @ 82C28D6
	.string "Oh, yeah, {PLAYER}!\n"
	.string "I found you again today!\p"
	.string "What should I do? Ask you again?\n"
	.string "Why not? I'm already asking you!\p"
	.string "Anyways, {PLAYER}…\n"
	.string "Are you receiving me?\l"
	.string "You are receiving me!\l"
	.string "I need some more advice for me!\p"
	.string "It's about what I should yell.\n"
	.string "Something cool to holler when\l"
	.string "a battle ends well.\p"
	.string "Come on, I wanna hear you say it!$"

gText_ApprenticeWinSpeechThanks12:: @ 82C2A0B
	.string "{STR_VAR_1}\p"
	.string "All right, all right!\n"
	.string "I'll use that because it's so tight!\p"
	.string "I'm out of things to ask you.\n"
	.string "Waving bye is all that's left to do.\p"
	.string "But maybe one day we'll meet, with one\n"
	.string "destined to go down in defeat.\p"
	.string "But, it really is time to say farewell.\p"
	.string "Well, {PLAYER}, I have to roam free,\n"
	.string "but don't you forget about me!\p"
	.string "Take care, {PLAYER}!\n"
	.string "Love ya!$"

gText_ApprenticePickWinSpeech13:: @ 82C2B50
	.string "{PLAYER}{KUN}, I'm finished…\n"
	.string "My nose won't stop dripping…\p"
	.string "I was trying to think up something\n"
	.string "cool to say when I win a battle.\p"
	.string "It inspired me so much, it made me cry,\n"
	.string "and now my nose won't stop running…\p"
	.string "So, things being this way,\n"
	.string "I need you to decide for me, {PLAYER}{KUN}.\p"
	.string "When I win a battle,\n"
	.string "what should I say?$"

gText_ApprenticeWinSpeechThanks13:: @ 82C2C77
	.string "{STR_VAR_1}\p"
	.string "… … …That's good.\n"
	.string "No, it's awe inspiring!\l"
	.string "It's bringing fresh tears to my eyes!\p"
	.string "But in spite of my tears and runny\n"
	.string "nose, I will use that saying!\p"
	.string "I'm plumb out of things to ask you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "From now on, we're rivals!\n"
	.string "Thanks for everything!$"

gText_ApprenticePickWinSpeech14:: @ 82C2D67
	.string "Er… Um…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Please, don't look at me that way.\n"
	.string "You're making me all nervous.\p"
	.string "I… I need your advice again.\n"
	.string "I'll make it my last, though…\p"
	.string "It's really embarrassing to ask,\n"
	.string "but what if I win a battle?\l"
	.string "What should I say?$"

gText_ApprenticeWinSpeechThanks14:: @ 82C2E41
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "I'll try to say that!\l"
	.string "I might be too nervous to say it…\p"
	.string "Thank you, {PLAYER}{KUN}.\n"
	.string "I have to say good-bye now.\p"
	.string "I'll obey all that you've taught me,\n"
	.string "{PLAYER}{KUN}, and do the best I can.$"

gText_ApprenticePickWinSpeech15:: @ 82C2EF5
	.string "Hm? You appear to be {PLAYER}{KUN}…\n"
	.string "But are you really?\l"
	.string "Perhaps a clever {PLAYER} DOLL?\p"
	.string "Oh, no, no, no, don't worry!\n"
	.string "If you really are real, please\l"
	.string "forget about my rudeness.\p"
	.string "No need to be so angry. All I wish for\n"
	.string "is more of your fine advice.\p"
	.string "It concerns a saying.\p"
	.string "More precisely, what should I say\n"
	.string "if I win a battle?$"

gText_ApprenticeWinSpeechThanks15:: @ 82C3023
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "When I win a match…\p"
	.string "{STR_VAR_1}\p"
	.string "…Are you serious?\p"
	.string "I see. If you are serious, that's fine.\n"
	.string "I thank you for your time.\p"
	.string "I do hope even I will be able to\n"
	.string "put that saying to good use.\p"
	.string "I seem to have run dry on what advice\n"
	.string "I need.\p"
	.string "I do believe it's high time I bid you\n"
	.string "farewell and strike out on my own.\p"
	.string "Thank you, my mentor!\n"
	.string "I apologize for my skepticism!$"
