FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C47EB
	.string "배틀텐트 단풍회장에\n"
	.string "어서 오십시오!\p"
	.string "여기서는 연승팀배틀의\n"
	.string "안내를 하고 있습니다!$"
	// バトルテント ハジツゲかいじょうへｎ
	// ようこそ おいでなされた!ｐ
	// こちらでは かちぬきチ-ムバトルのｎ
	// あんないを しておりますぞ!

FallarborTown_BattleTentLobby_Text_TakeChallenge: @ 82C4843
	.string "연승팀배틀에\n"
	.string "도전하겠습니까?$"
	// かちぬきチ-ムバトルにｎ
	// ちょうせん されますかな?

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge: @ 82C487F
	.string "다음에 또 도전해 주세요\n"
	.string "기다리고 있겠습니다!$"
	// またの ちょうせんをｎ
	// おまちして おりますぞ!

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent: @ 82C48AC
	.string "배틀텐트 단풍회장에서는\n"
	.string "연승팀배틀에\l"
	.string "참가하실 수 있습니다!\p"
	.string "참가하는 분께서는\n"
	.string "3마리의 포켓몬과 배틀에 내보낼\l"
	.string "순서를 정해 주십시오!\p"
	.string "배틀하는 동안은\n"
	.string "이 순서대로\l"
	.string "포켓몬을 내보내게 됩니다!\p"
	.string "배틀에 한 번 내보낸 포켓몬은\n"
	.string "결착이 날 때까지\l"
	.string "교체할 수 없습니다!\p"
	.string "게다가 3턴 이내에\n"
	.string "배틀의 결착이 나지 않는다면\l"
	.string "판정이 나게 됩니다!\p"
	.string "또한 도중에 도전을\n"
	.string "중단하고 싶을 경우에는\l"
	.string "리포트를 작성하지 않으면\l"
	.string "계속해서 도전을 할 수 없으므로\l"
	.string "주의해 주십시오!\p"
	.string "멋지게 3명을 돌파하시면\n"
	.string "근사한 상품을 선물합니다!$"
	// バトルテント ハジツゲかいじょうではｎ
	// かちぬきチ-ムバトルをｌ
	// おこなって おりますぞ!ｐ
	// さんかする かたには しゅつじょう させるｎ
	// 3ひきの ポケモンと たたかいに だすｌ
	// じゅんばんを きめて いただきますぞ!ｐ
	// たたかいの あいだはｎ
	// この じゅんばん どおりにｌ
	// ポケモンを だすことに なりますな!ｐ
	// たたかいに いちど だした ポケモンはｎ
	// けっちゃくが つくまでｌ
	// こうたいさせる ことが できませぬ!ｐ
	// さらに 3タ-ン いないにｎ
	// たたかいの けっちゃくが つかなければｌ
	// はんていと なりますぞ!ｐ
	// また とちゅうで ちょうせんをｎ
	// ちゅうだんしたい ばあいはｌ
	// レポ-トを かかないとｌ
	// つづけて ちょうせんが できないのでｌ
	// おきをつけ くだされ!ｐ
	// みごと 3にんぬきを なされた あかつきにはｎ
	// すてきな しょうひんをｌ
	// おおくり いたしますぞ!

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C4B35
	.string "배틀텐트에 입장하기 전에\n"
	.string "리포트를 작성합니다만 괜찮겠습니까?$"
	// バトルテントへ おつれする まえにｎ
	// レポ-トを かきますが よろしいですかな?

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode: @ 82C4B77
	.string "배틀아레나에는\n"
	.string "레벨 50과 오픈 레벨이 있습니다만\l"
	.string "어느 쪽으로 입장하겠습니까?$"
	// レベル50と レベル100の へやがｎ
	// ありますが どちらに まいられますかな?

FallarborTown_BattleTentLobby_Text_SelectThreeMons: @ 82C4BC8
	.string "그럼 참가할 포켓몬을\n"
	.string "3마리 선택해 주십시오$"
	// では ちょうせんする ポケモンをｎ
	// 3ひき おえらび くだされ!

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50: @ 82C4BFA
	.string "손님!!\p"
	.string "참가할 수 있는 포켓몬이\n"
	.string "3마리는 필요합니다!\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구로 해주십시오!\p"
	.string "그리고 알{STR_VAR_1}"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오!$"
	// おきゃくじん!!ｐ
	// さんかできる ポケモンがｎ
	// 3ひき おりませんぬ!ｐ
	// また もたせる どうぐもｎ
	// すべて ちがう どうぐに してくだされ!ｐ
	// なお タマゴ§いさんか させる ことは できませぬ!ｐ
	// じゅんびが できましたらｎ
	// また おこし くだされ!

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen: @ 82C4CC0
	.string "손님!!\p"
	.string "참가할 수 있는 포켓몬이\n"
	.string "3마리는 필요합니다!\p"
	.string "참가하려면\n"
	.string "종류가 다른 포켓몬을\l"
	.string "3마리 준비해 주십시오!\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구로 해주십시오!\p"
	.string "그리고 알{STR_VAR_1}"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오!$"
	// おきゃくじん!!ｐ
	// さんかできる ポケモンがｎ
	// 3ひき おりませぬ!ｐ
	// さんかする ためにはｎ
	// すべて ちがう しゅるいの ポケモンをｌ
	// 3ひき よういして くだされｐ
	// また もたせる どうぐもｎ
	// すべて ちがう どうぐに してくだされ!ｐ
	// なお タマゴ§いさんか させる ことは できませぬ!ｐ
	// じゅんびが できましたらｎ
	// また おこし くだされ!

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent: @ 82C4DC3
	.string "그럼 배틀텐트로\n"
	.string "안내하겠습니다!$"
	// では バトルテントへｎ
	// おつれいたしますぞ!

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting: @ 82C4DED
	.string "손님!\p"
	.string "지난번 종료하기 전에\n"
	.string "리포트를 제대로\l"
	.string "작성하지 않으셨죠?\p"
	.string "유감이지만 이런 경우에는\n"
	.string "도전이 무효가 됩니다!\p"
	.string "다시 처음부터\n"
	.string "도전해 주십시오!!$"
	// おきゃくじん!ｐ
	// ぜんかい レポ-トを かいてｎ
	// しゅうりょう しませんでしたな?ｐ
	// ざんねんですが その ばあいｎ
	// ちょうせんは むこうと なりますぞ!ｐ
	// また はじめからｎ
	// ちょうせん してくだされ!!

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers: @ 82C4EC3
	.string "3명 돌파를 달성하셨군요\n"
	.string "정말로 멋졌습니다!$"
	// 3にんぬき たっせいｎ
	// おみごとで ございました!

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame: @ 82C4EFF
	.string "성적을 리포트에 작성하므로\n"
	.string "기다려 주십시오!$"
	// レポ-トを かきますのでｎ
	// おまちくだされ!

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize: @ 82C4F22
	.string "3명을 돌파하기를 달성하였으므로\n"
	.string "이 상품을 드리겠습니다!$"
	// 3にんぬきを たっせい されましたのでｎ
	// この しょうひんを おうけとり くだされ!

FallarborTown_BattleTentLobby_Text_ReceivedPrize: @ 82C4F69
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_EULREUL} 받았다!$"
	// §あはｎ
	// §いを もらった!

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize: @ 82C4F83
	.string "...오옷!\n"
	.string "도구가 가득하시군요!\p"
	.string "도구를 정리하고 나서\n"
	.string "다시 와주십시오!$"
	// ……おおっ!ｎ
	// どうぐが いっぱいの ようですな!ｐ
	// どうぐを せいりしてからｎ
	// また おこしくだされ!

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving: @ 82C4FD7
	.string "수고하셨습니다!\p"
	.string "성적을 리포트에 작성하므로\n"
	.string "기다려 주십시오$"
	// おつかれさまでした!ｐ
	// レポ-トを かきますのでｎ
	// おまちくだされ!

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2: @ 82C501F
	.string "다음에 도전해 주세요\n"
	.string "기다리고 있겠습니다!$"
	// またの ちょうせんをｎ
	// おまちして おりますぞ!

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival: @ 82C504C
	.string "기다리고 있었습니다!\p"
	.string "배틀아레나에 입장하기 전에\n"
	.string "리포트를 작성하고 있으므로\l"
	.string "잠시 기다려 주십시오!$"
	// おまちしておりました!ｐ
	// バトルテントに おつれする まえにｎ
	// レポ-トを かきますので おまちくだされ!

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C50C3
	.string "배틀텐트\n"
	.string "잔디회장에 어서 오게\p"
	.string "여기서는 트레이너의\n"
	.string "신뢰하는 마음을 시험하고 있지$"
	// バトルテントｎ
	// シダケかいじょうへ ようこそｐ
	// ここでは トレ-ナ-のｎ
	// しんらいの こころを ためしておる

VerdanturfTown_BattleTentLobby_Text_TakeChallenge: @ 82C5129
	.string "배틀텐트 잔디회장에\n"
	.string "도전할 텐가?$"
	// バトルテント シダケかいじょうにｎ
	// ちょうせん するか?

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent: @ 82C5163
	.string "배틀텐트 잔디회장에서의\n"
	.string "배틀은 반드시 지켜야만 하는\l"
	.string "하나의 규칙이 있지\p"
	.string "여기서는 포켓몬에게\n"
	.string "교체만 명령할 수 있고\p"
	.string "그 외의 명령은\n"
	.string "일체 금지되어 있다네!\p"
	.string "포켓몬이 성격대로\n"
	.string "생각하고 행동해야 하지!\p"
	.string "자네는 자신의\n"
	.string "포켓몬들을 믿고\l"
	.string "배틀을 지켜보면 된다네\p"
	.string "훌륭히 3명의 트레이너를\n"
	.string "돌파하게 된다면\l"
	.string "상품을 주도록 하지\p"
	.string "또한 도중에 도전을\n"
	.string "중단하고 싶을 경우에는\l"
	.string "제대로 리포트를 작성하지 않으면\l"
	.string "계속해서 도전할 수 없게 되니\l"
	.string "주의를 부탁하네...$"
	// バトルテント シダケかいじょうでのｎ
	// たたかいには まもらなければ ならないｌ
	// ひとつの おきてが あるｐ
	// ここでは ポケモンはｎ
	// いれかえ しか できない!ｐ
	// それいがいの めいれいはｎ
	// いっさい きんし して おるのだ!ｐ
	// ポケモンには おのれの せいかくの ままにｎ
	// かんがえ こうどう して もらう!ｐ
	// おぬしは じぶんのｎ
	// ポケモンたちを しんじてｌ
	// たたかいを みまもって やれｐ
	// みごと 3にんの トレ-ナ-をｎ
	// うちやぶることが できればｌ
	// しょうひんを さしあげようｐ
	// また とちゅうで ちょうせんをｎ
	// ちゅうだん したい ときはｌ
	// きちんと レポ-トを かかないとｌ
	// つづけて ちょうせん できん からなｌ
	// きを つけてくれ……

VerdanturfTown_BattleTentLobby_Text_ReturnFortified: @ 82C539A
	.string "자신의 마음과 포켓몬을 단련하고 나서\n"
	.string "다시 오도록 하게나...$"
	// おのれの こころと ポケモンを きたえたらｎ
	// また くるがよい……

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode: @ 82C53DB
	.string "레벨 50과 오픈 레벨의 방이\n"
	.string "있는데 어느 쪽에 도전할 텐가?$"
	// レベル50の へやと レベル100の へやがｎ
	// あるが どちらに ちょうせん するのだ?

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50: @ 82C543D
	.string "자네...\p"
	.string "도전할 수 있는 포켓몬이\n"
	.string "3마리는 필요하다네!\p"
	.string "도전하려면\n"
	.string "종류가 다른 포켓몬을\p"
	.string "3마리 준비해 주게\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구여야 하네\p"
	.string "그리고 알{STR_VAR_1}"
	.string "참가시킬 수 없네!\p"
	.string "준비되면 다시 와 주게나$"
	// おぬし……ｐ
	// ちょうせん できる ポケモンがｎ
	// 3ひき おらんぞ!ｐ
	// ちょうせん するにはｎ
	// すべて ちがう しゅるいの ポケモンをｌ
	// 3ひき ようい してくれｐ
	// また もたせる どうぐもｎ
	// すべて ちがう もので なければ いかんｐ
	// なお タマゴ§いちょうせん させる ことは できん!ｐ
	// じゅんびを ととのえてから また きなさい

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen: @ 82C5538
	.string "자네...\p"
	.string "도전할 수 있는 포켓몬이\n"
	.string "3마리는 필요하다네!\p"
	.string "도전하려면\n"
	.string "종류가 다른 포켓몬을\p"
	.string "3마리 준비해 주게\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구여야 하네\p"
	.string "그리고 알{STR_VAR_1}"
	.string "참가시킬 수 없네!\p"
	.string "준비되면 다시 와 주게나$"
	// おぬし……ｐ
	// ちょうせん できる ポケモンがｎ
	// 3ひき おらんぞ!ｐ
	// ちょうせん するにはｎ
	// すべて ちがう しゅるいの ポケモンをｐ
	// 3ひき ようい してくれｐ
	// また もたせる どうぐもｎ
	// すべて ちがう もので なければ いかんｐ
	// そして タマゴ§いちょうせんｎ
	// させる ことは できん!ｐ
	// じゅんびを ととえてから また きなさい

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons: @ 82C5633
	.string "그럼 도전할 포켓몬을\n"
	.string "3마리 고르게나$"
	// では ちょうせんする ポケモンをｎ
	// 3ひき えらんでくれ

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C5662
	.string "배틀텐트로 가기 전에\n"
	.string "리포트를 작성할 건데 괜찮겠는가?$"
	// バトルテントへ むかうまえにｎ
	// レポ-トを かくが よろしいか?

VerdanturfTown_BattleTentLobby_Text_NowFollowMe: @ 82C56A2
	.string "그럼\n"
	.string "나를 따라오게...$"
	// それではｎ
	// わしに ついてこい……

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded: @ 82C56B8
	.string "좋은 구경을 했네\p"
	.string "그럼 성적을 리포트에 작성하지...\n"
	.string "잠시 기다려 주게...$"
	// よいものを みせて もらったｐ
	// それでは レポ-トを かこう……ｎ
	// しばし またれよ……

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak: @ 82C5731
	.string "3연승 달성이라니...\p"
	.string "자네와 포켓몬의 마음속 유대감은\n"
	.string "진짜로구먼...$"
	// 3にんぬき たっせい とは……ｐ
	// おぬしと ポケモンの こころの きずなはｎ
	// まことの ようじゃな……

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded: @ 82C5791
	.string "성적을 리포트에 작성할 테니\n"
	.string "잠시 기다려 주게...$"
	// レポ-トに かくぞｎ
	// しばし またれよ……

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize: @ 82C57CD
	.string "7연승을 거둔 증거로\n"
    .string "배틀포인트를 주겠네...$"
	// 3にんぬきの あかしにｎ
	// こちらを さしあげよう……

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C5810
	.string "배틀텐트 잿빛회장에\n"
	.string "어서 오세요!\p"
	.string "배틀트레이드의\n"
	.string "안내를 하고 있습니다!$"
	// バトルテント カイナかいじょうへｎ
	// ようこそ!ｐ
	// バトルトレ-ドのｎ
	// ごあんないは こちらです!

SlateportCity_BattleTentLobby_Text_TakeChallenge: @ 82C586A
	.string "배틀트레이드에\n"
	.string "도전하겠습니까?$"
	// バトルトレ-ドにｎ
	// ちょうせん しますか?

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent: @ 82C589C
	.string "배틀텐트 잿빛회장에서는\n"
	.string "대여 포켓몬을 빌려서\l"
	.string "배틀트레이드라는 이벤트를\l"
	.string "열고 있습니다!\p"
	.string "우선 배틀트레이드 전용의\n"
	.string "포켓몬 3마리를 빌려드립니다!\p"
	.string "다음은 그 포켓몬을\n"
	.string "써서 싱글배틀을\l"
	.string "치루시면 됩니다!\p"
	.string "훌륭히 배틀에서 승리하면\n"
	.string "싸웠던 트레이너와 포켓몬을\l"
	.string "트레이드할 수 있습니다!\p"
	.string "트레이드와 배틀을 반복해서\n"
	.string "멋지게 3연승을 하시면\l"
	.string "근사한 상품을 드립니다!\p"
	.string "또한 도중에 도전을\n"
	.string "중단하고 싶을 경우에는\l"
	.string "제대로 리포트를 작성하지 않으면\l"
	.string "계속해서 도전할 수 없습니다!\p"
	.string "아무쪼록 주의를 부탁드립니다!$"
	// バトルテント カイナかいじょうではｎ
	// レンタルポケモンを つかったｌ
	// バトルトレ-ド という イベントをｌ
	// おこなっています!ｐ
	// まずは バトルトレ-ド せんようのｎ
	// ポケモン 3ひきを おかし します!ｐ
	// つぎに そちらの 3ひきの ポケモンをｎ
	// つかって シングルバトルをｌ
	// おこなって いただきます!ｐ
	// みごと たたかいに しょうりするとｎ
	// たたかった トレ-ナ-と ポケモンをｌ
	// トレ-ド することが できます!ｐ
	// トレ-ドと たたかいを くりかえしｎ
	// みごと 3れんしょう したらｌ
	// すてきな しょうひんを さしあげます!ｐ
	// なお とちゅうで ちょうせんをｎ
	// ちゅうだん したい ときにはｌ
	// きちんと レポ-トを かかないとｌ
	// つづけて ちょうせんが できません!ｐ
	// くれぐれも きをつけて くださいね!

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit: @ 82C5AA5
	.string "다음에 또 이용해 주세요\n"
	.string "기다리고 있겠습니다!$"
	// またの ごりようを おまちしていますよ!

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode: @ 82C5AC9
	.string "레벨 50과 오픈 레벨의 이벤트\n"
	.string "어느 쪽에 도전하겠습니까?$"
	// レベル50と レベル100の イベントｎ
	// どちらに ちょうせん しますか?

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C5B06
	.string "그럼 도전을 시작하기 전에\n"
	.string "리포트를 작성합니다만\l"
	.string "괜찮겠습니까?$"
	// では ちょうせんを はじめる まえにｎ
	// レポ-トを かきますが よろしいですか?

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping: @ 82C5B4A
	.string "그럼 포켓몬을\n"
	.string "맡아두겠습니다!$"
	// それでは ポケモンをｎ
	// おあずかり します!

SlateportCity_BattleTentLobby_Text_StepThisWay: @ 82C5B8C
	.string "자 자 이쪽으로 와 주세요!$"
	// さあさあ こちらに どうぞ!

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults: @ 82C5BA2
	.string "수고하셨습니다!\p"
	.string "대여 포켓몬과\n"
	.string "맡아두고 있던 포켓몬을\l"
	.string "교환합니다!\p"
	.string "성적을 리포트에 작성하므로\n"
	.string "잠시 기다려 주십시오!$"
	// おつかれさまでした!ｐ
	// レンタルポケモンとｎ
	// おあずかり していた ポケモンをｌ
	// こうかん します!ｐ
	// レポ-トを かきますのでｎ
	// しょうしょう おまちください!

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals: @ 82C5C30
	.string "대여 포켓몬과\n"
	.string "맡아두고 있던 포켓몬을\l"
	.string "교환합니다!$"
	// レンタルポケモンとｎ
	// おあずかり していた ポケモンをｌ
	// こうかん します!

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons: @ 82C5C6F
	.string "3연승 축하합니다!\n"
	.string "대여 포켓몬과\n"
	.string "맡아두고 있던 포켓몬을\l"
	.string "교환합니다!\p"
	.string "리포트를 작성하므로\n"
	.string "잠시 기다려 주십시오!$"
	// 3れんしょう おめでとう ございます!ｐ
	// レンタルポケモンとｎ
	// おあずかり していた ポケモンをｌ
	// こうかん します!ｐ
	// レポ-トを かきますのでｎ
	// しょうしょう おまちください!

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize: @ 82C5D14
	.string "3연승을 기념하여\n"
	.string "상품을 선물합니다!$"
	// 3れんしょうを きねんしてｎ
	// こちらを さしあげます!

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom: @ 82C5D52
	.string "어라?\n"
	.string "도구가 가득찬 모양이군요\p"
	.string "도구를 정리하고 나서\n"
	.string "다시 와주세요!$"
	// おやや?ｎ
	// どうぐが いっぱい ですね-ｐ
	// どうぐを せいり してからｎ
	// また きてください!

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou: @ 82C5DA7
	.string "기다리고 있었습니다!\p"
	.string "도전을 재개하기 전에\n"
	.string "리포트를 작성합니다!$"
	// おまちして おりましたよ!ｐ
	// ちょうせんを さいかいする まえにｎ
	// レポ-トを かきます!

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting: @ 82C5DFA
	.string "손님-!!\p"
	.string "지난번에 종료하기 전에 리포트를\n"
	.string "제대로 작성하지 않으셨죠!\p"
	.string "죄송합니다만\n"
	.string "도전이 무효가 됩니다!$"
	// おきゃくさま-!!ｐ
	// ぜんかい ちゃんと レポ-トを かいてｎ
	// しゅうりょう しませんでしたね!ｐ
	// ざんねんですがｎ
	// ちょうせんは むこうと なります!

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons: @ 82C5E85
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_EULREUL} 받았다!$"
	// おきゃくさまの ポケモンをｎ
	// おかえしします!

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize: @ 82C5EA9
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_EULREUL} 받았다!$"
	// §あはｎ
	// §いを もらった!

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed: @ 82C5EC3
	.string "배틀트레이드의 규칙이 적혀 있다!$"
	// バトルトレ-ドの ル-ルが かかれてる!

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading: @ 82C5EE5
	.string "어느 설명을 읽겠습니까?$"
	// どの せつめいを よみますか?

SlateportCity_BattleTentLobby_Text_ExplainBasicRules: @ 82C5F08
	.string "배틀트레이드에서 사용할 수 있는\n"
	.string "포켓몬은 3마리까지입니다\p"
	.string "대여할 때 트레이드할 때\n"
	.string "어느 때라도\l"
	.string "같은 종류의 포켓몬을\l"
	.string "2마리 이상 지닐 수는 없습니다$"
	// バトルトレ-ドで つかうことの できるｎ
	// ポケモンは 3ひき まで ですｐ
	// レンタルするとき トレ-ドするときｎ
	// どちらの ときもｌ
	// おなじ しゅるいの ポケモンをｌ
	// 2ひき いじょう もつことは できません

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules: @ 82C5F9D
	.string "트레이드할 수 있는 상대는\n"
	.string "당신이 배틀에서\l"
	.string "쓰러뜨린 트레이너입니다\p"
	.string "트레이드로 받을 수 있는 건\n"
	.string "트레이너가 사용하던 포켓몬입니다$"
	// トレ-ドが できる あいてはｎ
	// あなたが たたかいでｌ
	// たおした トレ-ナ-ですｐ
	// トレ-ドで うけとる ことが できるのはｎ
	// トレ-ナ-が つかっていた ポケモンです

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules: @ 82C6020
	.string "한 번 배틀에서 이길 때마다\n"
	.string "1회에 1마리만 포켓몬을\l"
	.string "트레이드할 수 있습니다\p"
	.string "1회의 도전으로\n"
	.string "트레이드할 수 있는 건\l"
	.string "2번째의 트레이너까지입니다$"
	// いちど たたかいに かつ たびにｎ
	// 1かい 1ひき だけ ポケモンをｌ
	// トレ-ド することが できますｐ
	// 1かいの ちょうせんでｎ
	// トレ-ドが できるのはｌ
	// 2にんめの トレ-ナ-まで です

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes: @ 82C60C0
	.string "트레이드를 할 때에는\n"
	.string "2개 주의할 사항이 있습니다\p"
	.string "1번째로 트레이드를 할 때는\n"
	.string "상대로부터 받는 포켓몬의\l"
	.string "능력치를 확인할 수 없습니다\p"
	.string "2번째로 도전을 시작했을 때에\n"
	.string "빌린 대여 포켓몬의 순서가\l"
	.string "트레이드 이후의 배틀에도\l"
	.string "이어지게 됩니다$"
	// トレ-ドを おこなう ときにはｎ
	// 2つ ちゅういする ことが ありますｐ
	// その1 トレ-ドを おこなう ときはｎ
	// あいてから うけとる ポケモンのｌ
	// つよさは かくにん できませんｐ
	// その2 ちょうせんを はじめた ときにｎ
	// かりた レンタルポケモンの じゅんばんがｌ
	// トレ-ドの あとの たたかいにもｌ
	// ひきつがれます

SlateportCity_BattleTentLobby_Text_ExplainMonRules: @ 82C61FE
	.string "배틀텐트 잿빛회장의 포켓몬은\n"
	.string "모두 대여 포켓몬입니다\p"
	.string "대여 포켓몬의 레벨은\n"
	.string "모두 30입니다$"
	// バトルテント カイナの ポケモンはｎ
	// すべて レンタルポケモン ですｐ
	// レンタルポケモンの レベルはｎ
	// すべて 30に なります

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2: @ 82C6261
	.string "배틀텐트 잔디회장의\n"
	.string "규칙이 적혀 있다!$"
	// バトルテント シダケ かいじょうのｎ
	// ル-ルが かかれてる!

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading: @ 82C628E
	.string "어느 설명을 읽겠습니까?$"
	// どの せつめいを よみますか?

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules: @ 82C62B1
	.string "배틀텐트 잔디회장에서는\n"
	.string "포켓몬들이 스스로\l"
	.string "생각해서 배틀합니다\p"
	.string "순수한 야생과는 달리\n"
	.string "사람과 살아온 포켓몬은\l"
	.string "성격에 따라 어떤 행동을\l"
	.string "할지가 결정됩니다$"
	// バトルテント シダケかいじょう ではｎ
	// ポケモンたちが じぶんでｌ
	// かんがえ たたかいますｐ
	// じゅんすいな やせいの ときとは ちがってｎ
	// ひとと くらしている ポケモンはｌ
	// せいかくに よって どんな こうどうをｌ
	// するかが かわるのです

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules: @ 82C636D
	.string "아무튼 공격하는 것을\n"
	.string "선호하는 성격\p"
	.string "자신의 몸을 지키는 것을\n"
	.string "선호하는 성격\p"
	.string "상대를 난처하게\n"
	.string "만드는 것을 선호하는 성격\p"
	.string "포켓몬은 성격에 따라\n"
	.string "좋아하고 능숙한 기술과\l"
	.string "싫어하고 서투른 기술이 다릅니다$"
	// とにかく こうげきがｎ
	// すきな せいかくｐ
	// じぶんの みを まもることがｎ
	// すきな せいかくｐ
	// あいてを こまらせたりｎ
	// かわったことが すきな せいかくｐ
	// ポケモンは せいかくに よってｎ
	// すきで とくいな わざとｌ
	// きらいで にがてな わざが ちがいます

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules: @ 82C64BA
	.string "상대를 향해서 자신이\n"
	.string "직접 데미지를 주는\l"
	.string "공격 기술\p"
	.string "배틀의 준비나 상처입은 몸을\n"
	.string "회복하는 방어 기술\p"
	.string "상대의 능력을 내리거나\n"
	.string "독이나 마비를 거는 등의\l"
	.string "조금 변화를 주는 기술\p"
	.string "포켓몬은 모든 기술을\n"
	.string "크게 3개의 종류로 나눠서\l"
	.string "어떤 기술을 쓸지 생각합니다$"
	// あいてに むかって じぶんからｎ
	// ちょくせつ ダメ-ジを あたえるｌ
	// こうげきの わざｐ
	// たたかいの じゅんびや キズついた からだのｎ
	// かいふくを する ぼうぎょの わざｐ
	// あいての のうりょくを さげたりｎ
	// どくや まひに したり などｌ
	// すこし かわった ことを する わざｐ
	// ポケモンは すべての わざをｎ
	// おおきく 3つの しゅるいに わけてｌ
	// どんな わざを だすか かんがえて います

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules: @ 82C6612
	.string "트레이너의 명령을 받지 않는\n"
	.string "포켓몬은 기술을 잘\l"
	.string "쓸 수 없을 때가 있습니다\p"
	.string "포켓몬은 싫어하는 기술을\n"
	.string "쓰는 것에 서투릅니다\p"
	.string "성격에 맞지 않는 기술만을\n"
	.string "배우고 있다면 배틀에서\l"
	.string "포켓몬이 자신의 힘을 발휘할\l"
	.string "수 없을 확률이 큽니다$"
	// トレ-ナ-の めいれいを うけて いないｎ
	// ポケモンは うまく わざをｌ
	// だせない ことが ありますｐ
	// ポケモンは きらいな わざをｎ
	// つかうのは とくいでは ありませんｐ
	// せいかくに あわない わざ ばかりをｎ
	// おぼえさせて いると たたかいでｌ
	// ポケモンが じぶんの ちからを はっきｌ
	// できない ことが おおく なります

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules: @ 82C671E
	.string "포켓몬의 성격 중에서는\n"
	.string "위기에 몰리면 원래\l"
	.string "성격과는 다른 종류의\l"
	.string "기술을 쓰는\l"
	.string "경우가 있습니다\p"
	.string "위기에 몰렸을 때\n"
	.string "별난 행동을 시작한 포켓몬은\l"
	.string "주의하도록 합시다$"
	// ポケモンの せいかくの なかにはｎ
	// ピンチに なることで もともとのｌ
	// せいかくとは ちがう タイプのｌ
	// わざを つかう ようにｌ
	// なるものが ありますｐ
	// ピンチに なって すこし かわったｎ
	// こうどうを はじめた ポケモンにはｌ
	// じゅうぶん ちゅうい しましょう

BattleTentLobby_Text_ExplainLevelRules: @ 82C67CD
	.string "배틀텐트에서는\n"
	.string "당신의 포켓몬의 레벨에 맞춰서\l"
	.string "대전하는 트레이너의 포켓몬의\l"
	.string "레벨도 바뀝니다\p"
	.string "하지만 레벨 30보다 낮은 레벨의\n"
	.string "포켓몬을 지닌 트레이너가\l"
	.string "나타날 일은 없습니다$"
	// バトルテントではｎ
	// あなたの ポケモンの レベルに あわせてｌ
	// たいせんする トレ-ナ-の ポケモンのｌ
	// レベルが かわりますｐ
	// ただし レベル30より ひくい レベルのｎ
	// ポケモンを つれた トレ-ナ-がｌ
	// とうじょう することは ありません

VerdanturfTown_BattleTentLobby_Text_RulesAreListed: @ 82C6878
	.string "배틀텐트 잔디회장의\n"
	.string "규칙이 적혀 있다!$"
	// バトルテント シダケかいじょうのｎ
	// ル-ルが かかれている!
