BattleDome_Text_Potential1::
	.string "이번 대회의 우승 후보 넘버원!$"
	// こんたいかいの ゆうしょうこうほ ナンバ-1!

BattleDome_Text_Potential2::
	.string "결승 진출이 확실한 팀.$"
	// けっしょうまでは かくじつと いわれる チ-ム。

BattleDome_Text_Potential3::
	.string "베스트 3에 들 정도의 팀.$"
	// ベスト3に はいる ちからを もった チ-ム。

BattleDome_Text_Potential4::
	.string "이번 대회의 우승 후보 1팀.$"
	// こんたいかい ゆうしょうこうほの 1チ-ム。

BattleDome_Text_Potential5::
	.string "톱클래스의 힘을 갖춘 팀.$"
	// トップクラスの ちからを そなえた チ-ム。

BattleDome_Text_Potential6::
	.string "이번 대회의 주목 받는 다크호스!$"
	// こんたいかい ちゅうもくの ダ-クホ-ス!

BattleDome_Text_Potential7::
	.string "평균 이상의 힘을 지닌 팀.$"
	// へいきんより すこし ちからが うえの チ-ム。

BattleDome_Text_Potential8::
	.string "이번 대회의 평범한 팀.$"
	// こんたいかいの へいきんてきな チ-ム。

BattleDome_Text_Potential9::
	.string "평균 레벨의 힘을 지닌 팀.$"
	// へいきん レベルの ちからを もった チ-ム。

BattleDome_Text_Potential10::
	.string "평균보다 약한 힘을 지닌 팀.$"
	// へいきんより やや ちからが おちる チ-ム。

BattleDome_Text_Potential11::
	.string "일단 1승이 목표인 팀.$"
	// まず 1しょうが もくひょうと なる チ-ム。

BattleDome_Text_Potential12::
	.string "1승을 거두는 게 신기한 팀.$"
	// 1しょう できれば じょうじょうの チ-ム。

BattleDome_Text_Potential13::
	.string "전체적으로 낮은 레벨의 팀.$"
	// ぜんたいの なかで したの レベルの チ-ム。

BattleDome_Text_Potential14::
	.string "실력이 상당히 낮은 팀.$"
	// じつりょくは かなり したの レベルの チ-ム。

BattleDome_Text_Potential15::
	.string "우승이 상당히 어려운 팀.$"
	// ゆうしょうは かなり むずかしい チ-ム。

BattleDome_Text_Potential16::
	.string "우승에서 가장 먼 팀.$"
	// ゆうしょうから もっとも とおい チ-ム。

BattleDome_Text_PotentialDomeAceTucker::
	.string "완전 무적의 슈퍼스타!!$"
	// かんぜん むてきの ス-パ-スタ-!!

BattleDome_Text_StyleRiskDisaster::
	.string "때로는 쓰러질 각오로 배틀을 한다.$"
	// ときには はめつ かくごで たたかいを いどむ。

BattleDome_Text_StyleEndureLongBattles::
	.string "장기전과 끈기가 매우 특기.$"
	// ちょうきせんでの ねばりが とても とくい。

BattleDome_Text_StyleVariesTactics::
	.string "상대에 맞춰 다채로운 기술로 싸운다.$"
	// あいてに おうじて たさいな わざで たたかう。

BattleDome_Text_StyleToughWinningPattern::
	.string "승리 패턴에 말려들면 강하다.$"
	// かちパタ-ンを もっていて はまると つよい。

BattleDome_Text_StyleUsesVeryRareMove::
	.string "매우 희귀한 기술을 가끔씩 쓴다.$"
	// とても めずらしい わざを ときどき つかう。

BattleDome_Text_StyleUsesStartlingMoves::
	.string "뜻밖의 기술로 배틀을 어지럽힌다.$"
	// いひょうを つく わざで たたかいを みだす。

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "항상 체력에 주의하며 싸운다.$"
	// つねに たいりょくに きを くばって たたかう。

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "힘을 모아서 한 번에 공격한다.$"
	// ちからを ためて いっきに せめるのが とくい。

BattleDome_Text_StyleEnfeeblesFoes::
	.string "상대의 힘을 떨어뜨린다.$"
	// あいての ちからを おとすのが とくい。

BattleDome_Text_StylePrefersLuckTactics::
	.string "운에 맡기는 배틀을 즐긴다.$"
	// うんに まかせた たたかいかたを このむ。

BattleDome_Text_StyleRegalAtmosphere::
	.string "왕자의 품격을 갖춘 공격을 한다.$"
	// おうじゃの ふうかく ただよう せめを する。

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "PP가 적고 강한 기술로 승부한다.$"
	// PPの すくない おおわざで しょうぶする。

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "약하게 만든 후 공격한다.$"
	// よわらせてから こうげきを するのが とくい。

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "온갖 공격에도 버텨가며 싸운다.$"
	// あらゆる こうげきに たえながら たたかう。

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "상대의 마음을 어지럽게 한다.$"
	// あいての こころを かきみだすのが とくい。

BattleDome_Text_StyleStrongAndStraightforward::
	.string "강하고 쉬운 기술을 쓴다.$"
	// つよくて あつかいやすい わざを つかう。

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "강력한 기술로 점점 밀어붙인다.$"
	// きょうりょくな わざで どんどん おしまくる。

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "공격을 잘 피해가면서 싸운다.$"
	// こうげきを うまく かわしながら たたかう。

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "상대가 싫어하는 배틀을 한다.$"
	// あいてが いやがる たたかいが とくい。

BattleDome_Text_StyleUsesPopularMoves::
	.string "인기 있는 기술을 잔뜩 쓴다.$"
	// にんきの ある わざを たくさん つかう。

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "강력한 콤보가 되는 기술을 지녔다.$"
	// きょうりょくな コンボになる わざを もつ。

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "명중이 높은 기술로 공격한다.$"
	// てがたい わざで きっちりと こうげきする。

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "화려한 기술로 점점 밀어붙인다.$"
	// はでな わざを つかって どんどん せめる。

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "방어보다 공격을 중시한다.$"
	// まもりより とにかく せめを だいじに する。

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "공격보다 방어를 중시한다.$"
	// せめるより まもりを だいじに する。

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "강한 기술로 빠르게 승부를 본다.$"
	// つよいわざで しょうぶの しかけが はやい。

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "추가 효과가 있는 기술을 쓴다.$"
	// ついかこうかが ある わざを よく つかう。

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "밸런스 좋게 여러 기술로 싸운다.$"
	// バランスよく いろいろな わざで たちむかう。

BattleDome_Text_StyleSampleMessage1::
	.string "더미 메시지 1입니다.$"
	// ダミ-メッセ-ジ1です。

BattleDome_Text_StyleSampleMessage2::
	.string "더미 메시지 2입니다.$"
	// ダミ-メッセ-ジ2です。

BattleDome_Text_StyleSampleMessage3::
	.string "더미 메시지 3입니다.$"
	// ダミ-メッセ-ジ3です。

BattleDome_Text_StyleSampleMessage4::
	.string "더미 메시지 4입니다.$"
	// ダミ-メッセ-ジ4です。

BattleDome_Text_EmphasizesHPAndAtk::
	.string "HP와 공격에 신경을 쓴다.$"
	// HPと こうげきに ちからを いれている。

BattleDome_Text_EmphasizesHPAndDef::
	.string "HP와 방어에 신경을 쓴다.$"
	// HPと ぼうぎょに ちからを いれている。

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "HP와 스피드에 신경을 쓴다.$"
	// HPと すばやさに ちからを いれている。

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "HP와 특수공격에 신경을 쓴다.$"
	// HPと とくこうに ちからを いれている。

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "HP와 특수방어에 신경을 쓴다.$"
	// HPと とくぼうに ちからを いれている。

BattleDome_Text_EmphasizesAtkAndDef::
	.string "공격과 방어에 신경을 쓴다.$"
	// こうげきと ぼうぎょに ちからを いれている。

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "공격과 스피드에 신경을 쓴다.$"
	// こうげきと すばやさに ちからを いれている。

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "공격과 특수공격에 신경을 쓴다.$"
	// こうげきと とくこうに ちからを いれている。

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "공격과 특수방어에 신경을 쓴다.$"
	// こうげきと とくぼうに ちからを いれている。

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "방어와 스피드에 신경을 쓴다.$"
	// ぼうぎょと すばやさに ちからを いれている。

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "방어와 특수공격에 신경을 쓴다.$"
	// ぼうぎょと とくこうに ちからを いれている。

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "방어와 특수방어에 신경을 쓴다.$"
	// ぼうぎょと とくぼうに ちからを いれている。

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "스피드와 특수공격에 신경을 쓴다.$"
	// すばやさと とくこうに ちからを いれている。

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "스피드와 특수방어에 신경을 쓴다.$"
	// すばやさと とくぼうに ちからを いれている。

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "특수공격과 특수방어에 신경을 쓴다.$"
	// とくこうと とくぼうに ちからを いれている。

BattleDome_Text_EmphasizesHP::
	.string "HP에 신경을 쓴다.$"
	// HPに ちからを いれている。

BattleDome_Text_EmphasizesAtk::
	.string "공격에 신경을 쓴다.$"
	// こうげきに ちからを いれている。

BattleDome_Text_EmphasizesDef::
	.string "방어에 신경을 쓴다.$"
	// ぼうぎょに ちからを いれている。

BattleDome_Text_EmphasizesSpeed::
	.string "스피드에 신경을 쓴다.$"
	// すばやさに ちからを いれている。

BattleDome_Text_EmphasizesSpAtk::
	.string "특수공격에 신경을 쓴다.$"
	// とくこうに ちからを いれている。

BattleDome_Text_EmphasizesSpDef::
	.string "특수방어에 신경을 쓴다.$"
	// とくぼうに ちからを いれている。

BattleDome_Text_NeglectsHPAndAtk::
	.string "HP와 공격에 부주의하다!$"
	// HPと こうげきに ちからを いれていない!

BattleDome_Text_NeglectsHPAndDef::
	.string "HP와 방어에 부주의하다!$"
	// HPと ぼうぎょに ちからを いれていない!

BattleDome_Text_NeglectsHPAndSpeed::
	.string "HP와 스피드에 부주의하다!$"
	// HPと すばやさに ちからを いれていない!

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "HP와 특수공격에 부주의하다!$"
	// HPと とくこうに ちからを いれていない!

BattleDome_Text_NeglectsHPAndSpDef::
	.string "HP와 특수방어에 부주의하다!$"
	// HPと とくぼうに ちからを いれていない!

BattleDome_Text_NeglectsAtkAndDef::
	.string "공격과 방어에 부주의하다!$"
	// こうげきと ぼうぎょに ちからを いれていない!

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "공격과 스피드에 부주의하다!$"
	// こうげきと すばやさに ちからを いれていない!

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "공격과 특수공격에 부주의하다!$"
	// こうげきと とくこうに ちからを いれていない!

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "공격과 특수방어에 부주의하다!$"
	// こうげきと とくぼうに ちからを いれていない!

BattleDome_Text_NeglectsDefAndSpeed::
	.string "방어와 스피드에 부주의하다!$"
	// ぼうぎょと すばやさに ちからを いれていない!

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "방어와 특수공격에 부주의하다!$"
	// ぼうぎょと とくこうに ちからを いれていない!

BattleDome_Text_NeglectsDefAndSpDef::
	.string "방어와 특수방어에 부주의하다!$"
	// ぼうぎょと とくぼうに ちからを いれていない!

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "스피드와 특수공격에 부주의하다!$"
	// すばやさと とくこうに ちからを いれていない!

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "스피드와 특수방어에 부주의하다!$"
	// すばやさと とくぼうに ちからを いれていない!

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "특수공격과 특수방어에 부주의하다!$"
	// とくこうと とくぼうに ちからを いれていない!

BattleDome_Text_NeglectsHP::
	.string "HP에 부주의하다!$"
	// HPには ちからを いれていない!

BattleDome_Text_NeglectsAtk::
	.string "공격에 부주의하다!$"
	// こうげきには ちからを いれていない!

BattleDome_Text_NeglectsDef::
	.string "방어에 부주의하다!$"
	// ぼうぎょには ちからを いれていない!

BattleDome_Text_NeglectsSpeed::
	.string "스피드에 부주의하다!$"
	// すばやさには ちからを いれていない!

BattleDome_Text_NeglectsSpAtk::
	.string "특수공격에 부주의하다!$"
	// とくこうには ちからを いれていない!

BattleDome_Text_NeglectsSpDef::
	.string "특수방어에 부주의하다!$"
	// とくぼうには ちからを いれていない!

BattleDome_Text_RaisesMonsWellBalanced::
	.string "밸런스 좋게 포켓몬을 키우고 있다.$"
	// バランスよく ポケモンを そだてている。

BattleDome_Text_LetTheBattleBegin::
	.string "지금부터 대결 시작!$"
	// これより たいけつ!

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_2}{K_EU}로 {STR_VAR_1}의 승리!$"
	// §う などで §いが しょうり!

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_2}{K_EU}로 {STR_VAR_1}의 우승!$"
	// §う などで §い ゆうしょう!

BattleDome_Text_TrainerWonByDefault::
	.string "상대의 기권으로 {STR_VAR_1}의 승리!$"
	// あいての リタイアで §いが しょうり!

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "상대의 기권으로 {STR_VAR_1}의 우승!$"
	// あいての リタイアで §い ゆうしょう!

BattleDome_Text_TrainerWonNoMoves::
	.string "기술을 쓰지 않고 {STR_VAR_1}의 승리!$"
	// わざを つかわずに §いが しょうり!

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "기술을 쓰지 않고 {STR_VAR_1}의 우승!$"
	// わざを つかわずに §い ゆうしょう!

BattleDome_Text_Round1Match1::
	.string " 1회전 제1시합$"
	//  1かいせん だい1しあい

BattleDome_Text_Round1Match2::
	.string " 1회전 제2시합$"
	//  1かいせん だい2しあい

BattleDome_Text_Round1Match3::
	.string " 1회전 제3시합$"
	//  1かいせん だい3しあい

BattleDome_Text_Round1Match4::
	.string " 1회전 제4시합$"
	//  1かいせん だい4しあい

BattleDome_Text_Round1Match5::
	.string " 1회전 제5시합$"
	//  1かいせん だい5しあい

BattleDome_Text_Round1Match6::
	.string " 1회전 제6시합$"
	//  1かいせん だい6しあい

BattleDome_Text_Round1Match7::
	.string " 1회전 제7시합$"
	//  1かいせん だい7しあい

BattleDome_Text_Round1Match8::
	.string " 1회전 제8시합$"
	//  1かいせん だい8しあい

BattleDome_Text_Round2Match1::
	.string " 2회전 제1시합$"
	//  2かいせん だい1しあい

BattleDome_Text_Round2Match2::
	.string " 2회전 제2시합$"
	//  2かいせん だい2しあい

BattleDome_Text_Round2Match3::
	.string " 2회전 제3시합$"
	//  2かいせん だい3しあい

BattleDome_Text_Round2Match4::
	.string " 2회전 제4시합$"
	//  2かいせん だい4しあい

BattleDome_Text_SemifinalMatch1::
	.string "준결승 제1시합$"
	// じゅんけっしょう だい1しあい

BattleDome_Text_SemifinalMatch2::
	.string "준결승 제2시합$"
	// じゅんけっしょう だい2しあい

BattleDome_Text_FinalMatch::
	.string "  결승전$"
	//     けっしょうせん
