FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C47EB
	.string "배틀텐트 단풍회장에\n"
	.string "어서 오십시오!\p"
	.string "여기서는 연승팀배틀의\n"
	.string "안내를 하고 있습니다!$"
	// バトルテント ハジツゲかいじょうへｎ
	// ようこそ おいでなされた!ｐ
	// こちらでは かちぬきチ-ムバトルのｎ
	// あんないを しておりますぞ!

FallarborTown_BattleTentLobby_Text_TakeChallenge: @ 82C4843
	.string "연승팀배틀에\n"
	.string "도전하겠습니까?$"
	// かちぬきチ-ムバトルにｎ
	// ちょうせん されますかな?

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge: @ 82C487F
	.string "다음에 또 도전해 주세요\n"
	.string "기다리고 있겠습니다!$"
	// またの ちょうせんをｎ
	// おまちして おりますぞ!

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent: @ 82C48AC
	.string "배틀텐트 단풍회장에서는\n"
	.string "연승팀배틀에\l"
	.string "참가하실 수 있습니다!\p"
	.string "참가하는 분께서는\n"
	.string "3마리의 포켓몬과 배틀에 내보낼\l"
	.string "순서를 정해 주십시오!\p"
	.string "배틀하는 동안은\n"
	.string "이 순서대로\l"
	.string "포켓몬을 내보내게 됩니다!\p"
	.string "배틀에 한 번 내보낸 포켓몬은\n"
	.string "결착이 날 때까지\l"
	.string "교대할 수 없습니다!\p"
	.string "게다가 3턴 이내에\n"
	.string "배틀의 결착이 나지 않는다면\l"
	.string "판정이 나게 됩니다!\p"
	.string "또한 도중에 도전을\n"
	.string "중단하고 싶을 경우에는\l"
	.string "리포트를 작성하지 않으면\l"
	.string "계속해서 도전을 할 수 없으므로\l"
	.string "주의해 주십시오!\p"
	.string "멋지게 3명을 돌파하시면\n"
	.string "근사한 상품을 선물합니다!$"
	// バトルテント ハジツゲかいじょうではｎ
	// かちぬきチ-ムバトルをｌ
	// おこなって おりますぞ!ｐ
	// さんかする かたには しゅつじょう させるｎ
	// 3ひきの ポケモンと たたかいに だすｌ
	// じゅんばんを きめて いただきますぞ!ｐ
	// たたかいの あいだはｎ
	// この じゅんばん どおりにｌ
	// ポケモンを だすことに なりますな!ｐ
	// たたかいに いちど だした ポケモンはｎ
	// けっちゃくが つくまでｌ
	// こうたいさせる ことが できませぬ!ｐ
	// さらに 3タ-ン いないにｎ
	// たたかいの けっちゃくが つかなければｌ
	// はんていと なりますぞ!ｐ
	// また とちゅうで ちょうせんをｎ
	// ちゅうだんしたい ばあいはｌ
	// レポ-トを かかないとｌ
	// つづけて ちょうせんが できないのでｌ
	// おきをつけ くだされ!ｐ
	// みごと 3にんぬきを なされた あかつきにはｎ
	// すてきな しょうひんをｌ
	// おおくり いたしますぞ!

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C4B35
	.string "배틀텐트에 입장하기 전에\n"
	.string "리포트를 작성합니다만\l"
	.string "괜찮겠습니까?$"
	// バトルテントへ おつれする まえにｎ
	// レポ-トを かきますが よろしいですかな?

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode: @ 82C4B77
	.string "배틀아레나에는\n"
	.string "레벨 50과 오픈 레벨이 있습니다만\l"
	.string "어느 쪽으로 입장하겠습니까?$"
	// レベル50と レベル100の へやがｎ
	// ありますが どちらに まいられますかな?

FallarborTown_BattleTentLobby_Text_SelectThreeMons: @ 82C4BC8
	.string "그럼 참가할 포켓몬을\n"
	.string "3마리 선택해 주십시오$"
	// では ちょうせんする ポケモンをｎ
	// 3ひき おえらび くだされ!

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50: @ 82C4BFA
	.string "손님!!\p"
	.string "참가할 수 있는 포켓몬이\n"
	.string "3마리는 필요합니다!\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구로 해주십시오!\p"
	.string "그리고 알, 뮤,\n"
	.string "뮤츠, 칠색조,\l"
	.string "루기아, 세레비,\l"
	.string "가이오가, 그란돈,\l"
	.string "레쿠쟈, 지라치,\l"
	.string "테오키스는\l"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오!$"
	// おきゃくじん!!ｐ
	// さんかできる ポケモンがｎ
	// 3ひき おりませんぬ!ｐ
	// また もたせる どうぐもｎ
	// すべて ちがう どうぐに してくだされ!ｐ
	// なお タマゴ§いさんか させる ことは できませぬ!ｐ
	// じゅんびが できましたらｎ
	// また おこし くだされ!

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen: @ 82C4CC0
	.string "손님!!\p"
	.string "참가할 수 있는 포켓몬이\n"
	.string "3마리는 필요합니다!\p"
	.string "참가하려면\n"
	.string "종류가 다른 포켓몬을\l"
	.string "3마리 준비해 주십시오!\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구로 해주십시오!\p"
	.string "그리고 알, 뮤,\n"
	.string "뮤츠, 칠색조,\l"
	.string "루기아, 세레비,\l"
	.string "가이오가, 그란돈,\l"
	.string "레쿠쟈, 지라치,\l"
	.string "테오키스는\l"
	.string "참가시킬 수 없습니다!\p"
	.string "준비되면\n"
	.string "다시 방문해 주십시오!$"
	// おきゃくじん!!ｐ
	// さんかできる ポケモンがｎ
	// 3ひき おりませぬ!ｐ
	// さんかする ためにはｎ
	// すべて ちがう しゅるいの ポケモンをｌ
	// 3ひき よういして くだされｐ
	// また もたせる どうぐもｎ
	// すべて ちがう どうぐに してくだされ!ｐ
	// なお タマゴ§いさんか させる ことは できませぬ!ｐ
	// じゅんびが できましたらｎ
	// また おこし くだされ!

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent: @ 82C4DC3
	.string "그럼 배틀텐트로\n"
	.string "안내하겠습니다!$"
	// では バトルテントへｎ
	// おつれいたしますぞ!

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting: @ 82C4DED
	.string "손님!\p"
	.string "지난번 종료하기 전에\n"
	.string "리포트를 제대로\l"
	.string "작성하지 않으셨죠?\p"
	.string "유감이지만 이런 경우에는\n"
	.string "도전이 무효가 됩니다!\p"
	.string "다시 처음부터\n"
	.string "도전해 주십시오!!$"
	// おきゃくじん!ｐ
	// ぜんかい レポ-トを かいてｎ
	// しゅうりょう しませんでしたな?ｐ
	// ざんねんですが その ばあいｎ
	// ちょうせんは むこうと なりますぞ!ｐ
	// また はじめからｎ
	// ちょうせん してくだされ!!

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers: @ 82C4EC3
	.string "3명 돌파를 달성하셨군요\n"
	.string "정말로 멋졌습니다!$"
	// 3にんぬき たっせいｎ
	// おみごとで ございました!

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame: @ 82C4EFF
	.string "성적을 리포트에 작성하므로\n"
	.string "기다려 주십시오!$"
	// レポ-トを かきますのでｎ
	// おまちくだされ!

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize: @ 82C4F22
	.string "3명을 돌파하기를 달성하였으므로\n"
	.string "이 상품을 드리겠습니다!$"
	// 3にんぬきを たっせい されましたのでｎ
	// この しょうひんを おうけとり くだされ!

FallarborTown_BattleTentLobby_Text_ReceivedPrize: @ 82C4F69
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "{STR_VAR_1}{K_EULREUL} 받았다!$"
	// §あはｎ
	// §いを もらった!

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize: @ 82C4F83
	.string "..오옷!\n"
	.string "도구가 가득하시군요!\p"
	.string "도구를 정리하고 나서\n"
	.string "다시 와주십시오!$"
	// ……おおっ!ｎ
	// どうぐが いっぱいの ようですな!ｐ
	// どうぐを せいりしてからｎ
	// また おこしくだされ!

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving: @ 82C4FD7
	.string "수고하셨습니다!\p"
	.string "성적을 리포트에 작성하므로\n"
	.string "기다려 주십시오$"
	// おつかれさまでした!ｐ
	// レポ-トを かきますのでｎ
	// おまちくだされ!

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2: @ 82C501F
	.string "다음에 도전해 주세요\n"
	.string "기다리고 있겠습니다!$"
	// またの ちょうせんをｎ
	// おまちして おりますぞ!

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival: @ 82C504C
	.string "기다리고 있었습니다!\p"
	.string "배틀아레나에 입장하기 전에\n"
	.string "리포트를 작성하고 있으므로\l"
	.string "잠시 기다려 주십시오!$"
	// おまちしておりました!ｐ
	// バトルテントに おつれする まえにｎ
	// レポ-トを かきますので おまちくだされ!

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C50C3
	.string "배틀텐트\n"
	.string "잔디회장에 어서 오게\p"
	.string "여기서는 트레이너의\n"
	.string "신뢰하는 마음을 시험하고 있지$"
	// バトルテントｎ
	// シダケかいじょうへ ようこそｐ
	// ここでは トレ-ナ-のｎ
	// しんらいの こころを ためしておる

VerdanturfTown_BattleTentLobby_Text_TakeChallenge: @ 82C5129
	.string "배틀텐트 잔디회장에\n"
	.string "도전할 텐가?$"
	// バトルテント シダケかいじょうにｎ
	// ちょうせん するか?

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent: @ 82C5163
	.string "배틀텐트 잔디회장에서의\n"
	.string "배틀은 반드시 지켜야만 하는\l"
	.string "하나의 규칙이 있지\p"
	.string "여기서는 포켓몬에게\n"
	.string "교체만 명령할 수 있고\p"
	.string "그 외의 명령은\n"
	.string "일체 금지되어 있다네!\p"
	.string "포켓몬이 성격대로\n"
	.string "생각하고 행동해야 하지!\p"
	.string "자네는 자신의\n"
	.string "포켓몬들을 믿고\l"
	.string "배틀을 지켜보면 된다네\p"
	.string "훌륭히 3명의 트레이너를\n"
	.string "돌파하게 된다면\l"
	.string "상품을 주도록 하지\p"
	.string "또한 도중에 도전을\n"
	.string "중단하고 싶을 경우에는\l"
	.string "제대로 리포트를 작성하지 않으면\l"
	.string "계속해서 도전할 수 없게 되니\l"
	.string "주의를 부탁하네...$"
	// バトルテント シダケかいじょうでのｎ
	// たたかいには まもらなければ ならないｌ
	// ひとつの おきてが あるｐ
	// ここでは ポケモンはｎ
	// いれかえ しか できない!ｐ
	// それいがいの めいれいはｎ
	// いっさい きんし して おるのだ!ｐ
	// ポケモンには おのれの せいかくの ままにｎ
	// かんがえ こうどう して もらう!ｐ
	// おぬしは じぶんのｎ
	// ポケモンたちを しんじてｌ
	// たたかいを みまもって やれｐ
	// みごと 3にんの トレ-ナ-をｎ
	// うちやぶることが できればｌ
	// しょうひんを さしあげようｐ
	// また とちゅうで ちょうせんをｎ
	// ちゅうだん したい ときはｌ
	// きちんと レポ-トを かかないとｌ
	// つづけて ちょうせん できん からなｌ
	// きを つけてくれ……

VerdanturfTown_BattleTentLobby_Text_ReturnFortified: @ 82C539A
	.string "자신의 마음과 포켓몬을 단련하고\n"
	.string "나서 다시 오게나...$"
	// おのれの こころと ポケモンを きたえたらｎ
	// また くるがよい……

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode: @ 82C53DB
	.string "레벨 50과 오픈 레벨의 방이\n"
	.string "있는데 어느 쪽에 도전할 텐가?$"
	// レベル50の へやと レベル100の へやがｎ
	// あるが どちらに ちょうせん するのだ?

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50: @ 82C543D
	.string "자네…\p"
	.string "도전할 수 있는 포켓몬이\n"
	.string "3마리는 필요하다네!\p"
	.string "도전하려면\n"
	.string "종류가 다른 포켓몬을\p"
	.string "3마리 준비해 주게\p"
	.string "또한 지니게 할 도구도\n"
	.string "모두 다른 도구여야 하네\p"
	.string "그리고 알, 뮤,\n"
	.string "뮤츠, 칠색조,\l"
	.string "루기아, 세레비,\l"
	.string "가이오가, 그란돈,\l"
	.string "레쿠쟈, 지라치,\l"
	.string "테오키스는\l"
	.string "참가시킬 수 없네!\p"
	.string "준비되면 다시 와 주게나$"
	// おぬし……ｐ
	// ちょうせん できる ポケモンがｎ
	// 3ひき おらんぞ!ｐ
	// ちょうせん するにはｎ
	// すべて ちがう しゅるいの ポケモンをｌ
	// 3ひき ようい してくれｐ
	// また もたせる どうぐもｎ
	// すべて ちがう もので なければ いかんｐ
	// なお タマゴ§いちょうせん させる ことは できん!ｐ
	// じゅんびを ととのえてから また きなさい

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen: @ 82C5538
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"
	// おぬし……ｐ
	// ちょうせん できる ポケモンがｎ
	// 3ひき おらんぞ!ｐ
	// ちょうせん するにはｎ
	// すべて ちがう しゅるいの ポケモンをｐ
	// 3ひき ようい してくれｐ
	// また もたせる どうぐもｎ
	// すべて ちがう もので なければ いかんｐ
	// そして タマゴ§いちょうせんｎ
	// させる ことは できん!ｐ
	// じゅんびを ととえてから また きなさい

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons: @ 82C5633
	.string "Good. Now, you must select your\n"
	.string "three POKéMON.$"
	// では ちょうせんする ポケモンをｎ
	// 3ひき えらんでくれ

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C5662
	.string "I must save before I show you to\n"
	.string "the BATTLE TENT. Is that okay?$"
	// バトルテントへ むかうまえにｎ
	// レポ-トを かくが よろしいか?

VerdanturfTown_BattleTentLobby_Text_NowFollowMe: @ 82C56A2
	.string "Good.\n"
	.string "Now, follow me.$"
	// それではｎ
	// わしに ついてこい……

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded: @ 82C56B8
	.string "I feel privileged for having seen\n"
	.string "your POKéMON's exploits.\p"
	.string "The results will be recorded.\n"
	.string "I must ask you to briefly wait.$"
	// よいものを みせて もらったｐ
	// それでは レポ-トを かこう……ｎ
	// しばし またれよ……

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak: @ 82C5731
	.string "To achieve a 3-win streak…\p"
	.string "The bonds that bind your heart with\n"
	.string "your POKéMON seem firm and true.$"
	// 3にんぬき たっせい とは……ｐ
	// おぬしと ポケモンの こころの きずなはｎ
	// まことの ようじゃな……

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded: @ 82C5791
	.string "Your feat will be recorded.\n"
	.string "I must ask you to briefly wait.$"
	// レポ-トに かくぞｎ
	// しばし またれよ……

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize: @ 82C57CD
	.string "For the feat of your 3-win streak,\n"
	.string "we present you with this prize.$"
	// 3にんぬきの あかしにｎ
	// こちらを さしあげよう……

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent: @ 82C5810
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
	// バトルテント カイナかいじょうへｎ
	// ようこそ!ｐ
	// バトルトレ-ドのｎ
	// ごあんないは こちらです!

SlateportCity_BattleTentLobby_Text_TakeChallenge: @ 82C586A
	.string "Would you like to take the Battle\n"
	.string "Swap challenge?$"
	// バトルトレ-ドにｎ
	// ちょうせん しますか?

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent: @ 82C589C
	.string "Here at the SLATEPORT BATTLE TENT,\n"
	.string "we hold Battle Swap events\l"
	.string "using rental POKéMON.\p"
	.string "First, you will be loaned three\n"
	.string "POKéMON specifically for this event.\p"
	.string "Using the supplied rental POKéMON,\n"
	.string "you must conduct a SINGLE BATTLE.\p"
	.string "If you win, you are permitted to trade\n"
	.string "one of your rental POKéMON.\p"
	.string "Repeat this cycle of battling and\n"
	.string "trading--if you win three times in\l"
	.string "a row, you will earn a fine prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"
	// バトルテント カイナかいじょうではｎ
	// レンタルポケモンを つかったｌ
	// バトルトレ-ド という イベントをｌ
	// おこなっています!ｐ
	// まずは バトルトレ-ド せんようのｎ
	// ポケモン 3ひきを おかし します!ｐ
	// つぎに そちらの 3ひきの ポケモンをｎ
	// つかって シングルバトルをｌ
	// おこなって いただきます!ｐ
	// みごと たたかいに しょうりするとｎ
	// たたかった トレ-ナ-と ポケモンをｌ
	// トレ-ド することが できます!ｐ
	// トレ-ドと たたかいを くりかえしｎ
	// みごと 3れんしょう したらｌ
	// すてきな しょうひんを さしあげます!ｐ
	// なお とちゅうで ちょうせんをｎ
	// ちゅうだん したい ときにはｌ
	// きちんと レポ-トを かかないとｌ
	// つづけて ちょうせんが できません!ｐ
	// くれぐれも きをつけて くださいね!

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit: @ 82C5AA5
	.string "We look forward to your next visit.$"
	// またの ごりようを おまちしていますよ!

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode: @ 82C5AC9
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"
	// レベル50と レベル100の イベントｎ
	// どちらに ちょうせん しますか?

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge: @ 82C5B06
	.string "Before you begin your challenge,\n"
	.string "I need to save data. Is that okay?$"
	// では ちょうせんを はじめる まえにｎ
	// レポ-トを かきますが よろしいですか?

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping: @ 82C5B4A
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"
	// それでは ポケモンをｎ
	// おあずかり します!

SlateportCity_BattleTentLobby_Text_StepThisWay: @ 82C5B8C
	.string "Please step this way.$"
	// さあさあ こちらに どうぞ!

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults: @ 82C5BA2
	.string "Thank you for participating!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"
	// おつかれさまでした!ｐ
	// レンタルポケモンとｎ
	// おあずかり していた ポケモンをｌ
	// こうかん します!ｐ
	// レポ-トを かきますのでｎ
	// しょうしょう おまちください!

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals: @ 82C5C30
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"
	// レンタルポケモンとｎ
	// おあずかり していた ポケモンをｌ
	// こうかん します!

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons: @ 82C5C6F
	.string "Congratulations!\n"
	.string "You've won three straight matches!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"
	// 3れんしょう おめでとう ございます!ｐ
	// レンタルポケモンとｎ
	// おあずかり していた ポケモンをｌ
	// こうかん します!ｐ
	// レポ-トを かきますのでｎ
	// しょうしょう おまちください!

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize: @ 82C5D14
	.string "In recognition of your 3-win streak,\n"
	.string "we award you this prize.$"
	// 3れんしょうを きねんしてｎ
	// こちらを さしあげます!

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom: @ 82C5D52
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"
	// おやや?ｎ
	// どうぐが いっぱい ですね-ｐ
	// どうぐを せいり してからｎ
	// また きてください!

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou: @ 82C5DA7
	.string "We've been waiting for you!\p"
	.string "Before we resume your challenge,\n"
	.string "I must save the game.$"
	// おまちして おりましたよ!ｐ
	// ちょうせんを さいかいする まえにｎ
	// レポ-トを かきます!

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting: @ 82C5DFA
	.string "I'm sorry to say this, but you didn't\n"
	.string "save before you quit playing last time.\p"
	.string "As a result, you have been disqualified\n"
	.string "from your challenge.$"
	// おきゃくさま-!!ｐ
	// ぜんかい ちゃんと レポ-トを かいてｎ
	// しゅうりょう しませんでしたね!ｐ
	// ざんねんですがｎ
	// ちょうせんは むこうと なります!

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons: @ 82C5E85
	.string "We'll return your personal POKéMON.$"
	// おきゃくさまの ポケモンをｎ
	// おかえしします!

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize: @ 82C5EA9
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"
	// §あはｎ
	// §いを もらった!

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed: @ 82C5EC3
	.string "The Battle Swap rules are listed.$"
	// バトルトレ-ドの ル-ルが かかれてる!

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading: @ 82C5EE5
	.string "Which heading do you want to read?$"
	// どの せつめいを よみますか?

SlateportCity_BattleTentLobby_Text_ExplainBasicRules: @ 82C5F08
	.string "In a Battle Swap event, you may use\n"
	.string "only three POKéMON.\p"
	.string "Whether you are renting or swapping,\n"
	.string "your team may not have two or more\l"
	.string "of the same POKéMON.$"
	// バトルトレ-ドで つかうことの できるｎ
	// ポケモンは 3ひき まで ですｐ
	// レンタルするとき トレ-ドするときｎ
	// どちらの ときもｌ
	// おなじ しゅるいの ポケモンをｌ
	// 2ひき いじょう もつことは できません

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules: @ 82C5F9D
	.string "You may swap POKéMON only with\n"
	.string "the TRAINER you have just defeated.\p"
	.string "You may swap for only those POKéMON\n"
	.string "used by the beaten TRAINER.$"
	// トレ-ドが できる あいてはｎ
	// あなたが たたかいでｌ
	// たおした トレ-ナ-ですｐ
	// トレ-ドで うけとる ことが できるのはｎ
	// トレ-ナ-が つかっていた ポケモンです

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules: @ 82C6020
	.string "After every battle you win, you may\n"
	.string "swap for one of your defeated\l"
	.string "opponent's POKéMON.\p"
	.string "You will not be able to swap POKéMON\n"
	.string "with the third TRAINER in the event.$"
	// いちど たたかいに かつ たびにｎ
	// 1かい 1ひき だけ ポケモンをｌ
	// トレ-ド することが できますｐ
	// 1かいの ちょうせんでｎ
	// トレ-ドが できるのはｌ
	// 2にんめの トレ-ナ-まで です

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes: @ 82C60C0
	.string "There are two key points to be aware\n"
	.string "of when swapping POKéMON.\p"
	.string "First, when swapping, you can't check\n"
	.string "the stats of the POKéMON you are\l"
	.string "about to receive.\p"
	.string "Second, the POKéMON on your team\n"
	.string "are lined up in sequence, depending on\l"
	.string "the order in which you rented them.\p"
	.string "This sequence remains unchanged\n"
	.string "even when swaps are made.$"
	// トレ-ドを おこなう ときにはｎ
	// 2つ ちゅういする ことが ありますｐ
	// その1 トレ-ドを おこなう ときはｎ
	// あいてから うけとる ポケモンのｌ
	// つよさは かくにん できませんｐ
	// その2 ちょうせんを はじめた ときにｎ
	// かりた レンタルポケモンの じゅんばんがｌ
	// トレ-ドの あとの たたかいにもｌ
	// ひきつがれます

SlateportCity_BattleTentLobby_Text_ExplainMonRules: @ 82C61FE
	.string "The POKéMON of the SLATEPORT\n"
	.string "BATTLE TENT are all rentals.\p"
	.string "All rental POKéMON are kept at\n"
	.string "Level 30.$"
	// バトルテント カイナの ポケモンはｎ
	// すべて レンタルポケモン ですｐ
	// レンタルポケモンの レベルはｎ
	// すべて 30に なります

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2: @ 82C6261
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
	// バトルテント シダケ かいじょうのｎ
	// ル-ルが かかれてる!

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading: @ 82C628E
	.string "Which heading do you want to read?$"
	// どの せつめいを よみますか?

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules: @ 82C62B1
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"
	// バトルテント シダケかいじょう ではｎ
	// ポケモンたちが じぶんでｌ
	// かんがえ たたかいますｐ
	// じゅんすいな やせいの ときとは ちがってｎ
	// ひとと くらしている ポケモンはｌ
	// せいかくに よって どんな こうどうをｌ
	// するかが かわるのです

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules: @ 82C636D
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"
	// とにかく こうげきがｎ
	// すきな せいかくｐ
	// じぶんの みを まもることがｎ
	// すきな せいかくｐ
	// あいてを こまらせたりｎ
	// かわったことが すきな せいかくｐ
	// ポケモンは せいかくに よってｎ
	// すきで とくいな わざとｌ
	// きらいで にがてな わざが ちがいます

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules: @ 82C64BA
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"
	// あいてに むかって じぶんからｎ
	// ちょくせつ ダメ-ジを あたえるｌ
	// こうげきの わざｐ
	// たたかいの じゅんびや キズついた からだのｎ
	// かいふくを する ぼうぎょの わざｐ
	// あいての のうりょくを さげたりｎ
	// どくや まひに したり などｌ
	// すこし かわった ことを する わざｐ
	// ポケモンは すべての わざをｎ
	// おおきく 3つの しゅるいに わけてｌ
	// どんな わざを だすか かんがえて います

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules: @ 82C6612
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"
	// トレ-ナ-の めいれいを うけて いないｎ
	// ポケモンは うまく わざをｌ
	// だせない ことが ありますｐ
	// ポケモンは きらいな わざをｎ
	// つかうのは とくいでは ありませんｐ
	// せいかくに あわない わざ ばかりをｎ
	// おぼえさせて いると たたかいでｌ
	// ポケモンが じぶんの ちからを はっきｌ
	// できない ことが おおく なります

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules: @ 82C671E
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don't match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"
	// ポケモンの せいかくの なかにはｎ
	// ピンチに なることで もともとのｌ
	// せいかくとは ちがう タイプのｌ
	// わざを つかう ようにｌ
	// なるものが ありますｐ
	// ピンチに なって すこし かわったｎ
	// こうどうを はじめた ポケモンにはｌ
	// じゅうぶん ちゅうい しましょう

BattleTentLobby_Text_ExplainLevelRules: @ 82C67CD
	.string "At this BATTLE TENT, the levels of\n"
	.string "your opponents will be adjusted to\l"
	.string "match the levels of your POKéMON.\p"
	.string "However, no TRAINER you face will\n"
	.string "have any POKéMON below Level 30.$"
	// バトルテントではｎ
	// あなたの ポケモンの レベルに あわせてｌ
	// たいせんする トレ-ナ-の ポケモンのｌ
	// レベルが かわりますｐ
	// ただし レベル30より ひくい レベルのｎ
	// ポケモンを つれた トレ-ナ-がｌ
	// とうじょう することは ありません

VerdanturfTown_BattleTentLobby_Text_RulesAreListed: @ 82C6878
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
	// バトルテント シダケかいじょうのｎ
	// ル-ルが かかれている!
