PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "아빠: 여어 {PLAYER}{K_AYA}!\p"
	.string "희귀한 나무열매를 손에 넣었으니\n"
	.string "선물할게!$"
	// パパ『やあ §あ!ｐ
	// めずらしい きのみを てに いれたからｎ
	// プレゼント するよ!

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "푹신푹신한 흙에 자라고 있는 나무열매는\n"
	.string "언제든지 따도 상관은 없지만...\p"
	.string "나무열매를 1개 같은 장소에 심는 것\n"
	.string "하나만 지켜주렴 그게 예의란다\p"
	.string "자 그럼 이걸 나눠주마$"
	// ふかふかの つちに はえている きのみはｎ
	// じゆうに とっても よいのじゃが…ｐ
	// 1つだけ きのみを おなじ ばしょに うめるｎ
	// それが れいぎと いうものじゃｐ
	// ほれ これを わけてやろう

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "보아하니 자네 트레이너지?\p"
	.string "트레이너는 자주 포켓몬에게\n"
	.string "나무열매를 지니게 하지\p"
	.string "심든지 사용하든지 자네 맘이라네$"
	// あんた みたところ トレ-ナ-じゃろ?ｐ
	// トレ-ナ-は よく きのみを ポケモンにｎ
	// もたせとるわいｐ
	// ふやすも つかうも あんた しだいじゃ

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "매일 물을 줬더니\n"
	.string "꽃이 잔뜩 피었어\p"
	.string "그랬더니 나무열매도 많이 열렸어!\p"
	.string "자!\n"
	.string "이거 줄게$"
	// いつも みずを あげてたらｎ
	// たくさん はなが さいたんだｐ
	// そしたら きのみも たくさん できた!ｐ
	// はい!ｎ
	// これ あげる

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "열심히 해서 다양한 색의\n"
	.string "나무열매를 키울 거야!\l"
	.string "{K_GIRL_CALL}도 힘내!$"
	// がんばって いろんな いろのｎ
	// きのみを そだてるんだ!ｌ
	// §いも がんばってね!

Route111_Text_WhatColorBerriesToLookForToday:
	.string "오늘은 무슨 색의 나무열매를\n"
	.string "찾아볼까나-$"
	// きょうは なにいろの きのみをｎ
	// さがそっかな-

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "나무열매크러시가 너무 재밌어서\n"
	.string "나무열매를 모으고 있어\p"
	.string "괜찮으면 네게도 나눠줄게!$"
	// きのみクラッシュが だいすきだからｎ
	// きのみを あつめているんだｐ
	// よかったら きみにも わけて あげるよ!

Route114_Text_TryBerryCrushWithFriends:
	.string "너도 친구들이랑\n"
	.string "나무열매크러시를 한번 해봐!$"
	// きみも ともだちとｎ
	// きのみクラッシュ やってみなよ!

Route114_Text_FunToThinkAboutBerries:
	.string "어떤 나무열매를 심을까?\n"
	.string "나무열매를 쓸까 늘릴까?\p"
	.string "이러면서 고민하는 것도 즐거워$"
	// どの きのみを うめるか?ｎ
	// きのみは つかうのか ふやすのか?ｐ
	// って なやむのも また たのしいよ

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "빛을 잔뜩 받고\n"
	.string "자라는 나무열매들...\p"
	.string "그리고 나무열매가 건강히 자라도록\n"
	.string "물뿌리개로 물을 주는 우리들...\p"
	.string "이거 사랑 맞지?$"
	// ひかりを いっぱい あびてｎ
	// そだつ きのみたち…ｐ
	// そして きのみが げんきに そだつようにｎ
	// じょうろで みずを あげる わたしたち…ｐ
	// これって あい だよね?

Route120_Text_YesYouUnderstand:
	.string "응 응!\n"
	.string "역시 아는 사람은 안단 말이지\p"
	.string "이거 줄게$"
	// うん うん!ｎ
	// やっぱ わかるひとには わかるよねｐ
	// これ あげる

Route120_Text_MakeYourOwnImpressions:
	.string "그렇구나...\n"
	.string "하지만 다르게 느끼는 것도 중요하지\p"
	.string "이거 줄게$"
	// そっか……ｎ
	// でも ちがうと かんじることも たいせつだねｐ
	// これ あげる

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "그 나무열매는 희귀한 것 같으니까\n"
	.string "소중하게 키워줘!$"
	// その きのみは めずらしいもの らしいからｎ
	// たいせつに そだててね!

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "또 나무열매 명인에게 받아 와야지$"
	// また きのみめいじんに もらって こようっと

LilycoveCity_Text_BerrySuitsYou:
	.string "역시\p"
	.string "나에게 슈트가 어울리듯\n"
	.string "바다에는 바닷바람이 어울려\l"
	.string "그리고 자네에겐 나무열매가 어울리는군...\p"
	.string "왜일까?$"
	// やっぱりｐ
	// わたしに ス-ツが にあうようにｎ
	// うみには しおかぜが にあうなｌ
	// そして きみには きのみが にあいそうだ……ｐ
	// なんでだろうね?

LilycoveCity_Text_BecauseYoureTrainer:
	.string "역시 그건......\p"
	.string "자네가 트레이너이기 때문이지!$"
	// やっぱり それは…………ｐ
	// きみが トレ-ナ-だからだ!

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "역시\p"
	.string "나에게 심플함이 어울리듯\n"
	.string "포켓몬에게는 포켓몬스넥이 어울려$"
	// やっぱりｐ
	// わたしに シンプルさが にあうようにｎ
	// ポケモンには ポロックが にあうな

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "난 나무열매 명인이라고 불리고 있지\p"
	.string "난 온 세상을 아름다운 꽃으로\n"
	.string "채우기 위해 나무열매를 키우고\l"
	.string "그리고 마구 나눠주고 있다네\p"
	.string "너에게도 나무열매를 나눠 주지!$"
	// わしは きのみめいじんと よばれておるｐ
	// わしは せかいじゅうを うつくしい はなでｎ
	// うめつくそうと きのみを そだててｌ
	// そして くばり まくって おるのじゃｐ
	// きみにも きのみを わけて あげよう!

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "자자 사양 말고 하나 더!$"
	// ほれ えんりょ せずに もう ひとつ!

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "금탄도시 근처에 있는 꽃잎 화원이라는\n"
	.string "플라워숍도 잘 부탁하네\p"
	.string "온 세상에 꽃을 피우자!$"
	// カナズミの ちかくにある サン®トウカというｎ
	// フラワ-ショップも よろしくのｐ
	// せかいに はなを さかせましょう!

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "오늘은 이만 끝내야겠구먼\n"
	.string "또 오게나\p"
	.string "온 세상에 꽃을 피우자!$"
	// きょうは もう おしまいじゃｎ
	// また おいでｐ
	// せかいに はなを さかせましょう!

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "영감이 키운 나무열매는\n"
	.string "말할 것도 없이 세계 제일이지\p"
	.string "그래서 나도 자랑스럽구먼\p"
	.string "그런데 자네\n"
	.string "혹시 최근에 멋진 말을 들은 적 없나?$"
	// じいさんの きのみの そだてかたはｎ
	// そりゃあ せかいいちじゃｐ
	// わしも はなが たかいわいｐ
	// ところで あんたｎ
	// いい ことばを きいたことが ないかい?

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "오옷! 정말 멋진 말이구먼!\n"
	.string "감동했네\p"
	.string "자 이것을 가져가게나$"
	// おお! とても よい ことばじゃ!ｎ
	// かんどう したわいｐ
	// ほれ これを もっていきなされ

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "오옷! 꽤 멋진 말이구먼\n"
	.string "자네도 좀 하는데\p"
	.string "자 이것을 가져가게나$"
	// おお! なかなか よい ことばじゃｎ
	// あんたも たいしたもんじゃｐ
	// ほれ これを もっていきなされ

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "손자 4명도 영감을 능가하는\n"
	.string "큰 인물이 되겠지\p"
	.string "인생에 재미있는 일이 끝이 없구먼!$"
	// まごたち 4にんも じいさんを しのぐｎ
	// おおものに なるじゃろうてｐ
	// じんせい たのしいことが つきんのう!

Route123_BerryMastersHouse_Text_Ah:
	.string "호오...$"
	// ほう……

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "안녕하세요!\p"
	.string "꽃을 온 세상에 퍼뜨리는\n"
	.string "플라워숍 꽃잎 화원입니다!$"
	// こんにちは!ｐ
	// はなを せかいに ひろめるｎ
	// フラワ-ショップ サン®トウカです!

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER} 나무열매에 대해 알고 싶어?$"
	// §あ§お きのみの こと しりたい?

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "당신의 이름은...\p"
	.string "{PLAYER}{K_I}구나!\n"
	.string "정말 좋은 이름이네!\l"
	.string "{PLAYER} 나무열매에 대해 알고 싶어?$"
	// あなたの なまえは……ｐ
	// §あ§おね!ｎ
	// とっても いい なまえだね!ｌ
	// §あ§お きのみのこと しりたい?

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "나무열매는 말이지 푹신푹신한\n"
	.string "흙에서 가끔 딸 수 있어\l"
	.string "그리고...\p"
	.string "딴 열매 중 하나를 또 심을 수 있지!\p"
	.string "그렇게 하면 그 나무열매에서\n"
	.string "새싹이 트고 줄기가 자라고 꽃이 펴서\l"
	.string "거기에 또 나무열매가 열려\p"
	.string "그렇게 꽃을 늘려서\n"
	.string "온 세상을 꽃으로 가득 채우는 게\l"
	.string "내 꿈이야!\p"
	.string "그러니까 {PLAYER}도 나무열매를 심어서\n"
	.string "온 세상에 꽃을 퍼뜨려줘!$"
	// きのみはね くろい ふかふかの つちのｎ
	// ところで たまに とれるのｌ
	// でね……ｐ
	// とったら その1つを また うめるの!ｐ
	// そうすると その きのみ からｎ
	// めがでて みきが できて はながさいてｌ
	// また きのみ が できるのｐ
	// そうやって はなを ふやしてｎ
	// せかいじゅうを はなに するのがｌ
	// わたしの ゆめ なんだ!ｐ
	// だから §あ§おも きのみを うめてｎ
	// せかいに はなを ふやしてね!

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "꽃은 정말 행복한 기분으로\n"
	.string "만들어 주는 거 같아$"
	// おはなって とっても しあわせな きぶんにｎ
	// してくれるよね

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "안녕!\p"
	.string "꽃은 진심을 담아 돌보면\n"
	.string "엄청 예쁘게 피고 나무열매도 많이 열려\p"
	.string "너도 돌보고 싶어졌지?\n"
	.string "이거 줄게$"
	// こんにちは!ｐ
	// おはなは せわを すれば するほどｎ
	// たくさん きれいに さいて くれるのｐ
	// あなたも せわを したく なった でしょ?ｎ
	// これ あげるわ

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "나무열매가 자랄 때마다\n"
	.string "물뿌리개로 물을 주도록 해!\p"
	.string "그리고 있지\p"
	.string "나무열매는 계속 방치해 놓으면\n"
	.string "땅에 떨어져버려\l"
	.string "하지만 거기서 또다시 새싹이 트게 되지!\p"
	.string "정말 대단하지 않아?\n"
	.string "생명의 힘이 느껴져$"
	// きのみが そだつ たびにｎ
	// じょうろで みずを あげてね!ｐ
	// あとねｐ
	// きのみは ずっと ずっと ほうっておくとｎ
	// じめんに おちてしまうのｌ
	// でもね そこから また めがでて くるの!ｐ
	// すごいよね!ｎ
	// いきものの ちからを かんじるよね

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "언니들을 본받아서\n"
	.string "열심히 꽃을 키우고 있어\p"
	.string "자! 이거 줄게!$"
	// おね-ちゃんたちを みならってｎ
	// がんばって おはなを そだててるのｐ
	// はい! これあげる!

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "나무열매는 심어서 자라게 하거나\n"
	.string "포켓몬한테 지니게 할 수 있어\p"
	.string "그런데 최근에는 여러 나무열매를 섞으면\n"
	.string "포켓몬의 과자를 만들어주는 기계가\l"
	.string "있다고 하더라고\p"
	.string "나도 과자 먹고 싶어-$"
	// きのみは うめて おおきく したりｎ
	// ポケモンに もたせたり できるのｐ
	// でも さいきん きのみを いくつか まぜるとｎ
	// ポケモンの おかしになる きかいがｌ
	// ある らしいんだｐ
	// あたしも おかし ほし-

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "{K_GIRL_CALL}{K_EUNNEUN} 이름이 뭐야?\p"
	.string "...... ...... ......\n"
	.string "오- 좋은 이름이네-\p"
	.string "내 이름은 키리라고 해\p"
	.string "아빠랑 엄마가 잘 자라서\n"
	.string "마음이 따뜻한 여자아이가 되라는\l"
	.string "바람을 담아 내 이름을 지었다나 봐!\p"
	.string "{K_GIRL_CALL}한테도 이거 줄게$"
	// §い なまえ なんていうの?ｐ
	// ……… ……… ………ｎ
	// へ- いいね-ｐ
	// わたしは キリ っていう なまえなのｐ
	// パパと ママが すくすくと そだってｎ
	// こころの あたたかい おんなのこに なってｌ
	// ほしいっていう ねがいを こめたんだって!ｐ
	// §いにも これ あげる

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "그리고 {K_GIRL_CALL}한테는\n"
	.string "내가 정말 좋아하는\l"
	.string "이 나무열매도 줄게!$"
	// あと §いには キリの だいすきなｎ
	// この きのみも あげちゃう!

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "{K_GIRL_CALL} 이름에는\n"
	.string "어떤 바람이 담겨 있어?$"
	// §いの なまえにはｎ
	// どんな ねがいが こめられてるの?

SootopolisCity_Text_LikeSeasonBornIn:
	.string "봄 여름 가을 겨울\n"
	.string "봄에 태어나면 봄이 좋아지고\l"
	.string "여름에 태어나면 여름이 좋아지는 걸까?$"
	// はる なつ あき ふゆｎ
	// はるに うまれると はるが すきでｌ
	// なつに うまれると なつが すきなのかな?

SootopolisCity_Text_ThenILoveAutumn:
	.string "그럼 난 가을에 태어났으니까\n"
	.string "가을이 정말 좋아!\p"
	.string "{K_GIRL_CALL}{K_EUNNEUN} 언제가 좋아?$"
	// じゃあ キリは あきに うまれたからｎ
	// あきが だいすき!ｐ
	// §いは いつが すき?

SootopolisCity_Text_OhDoesntMatter:
	.string "그렇구나...\n"
	.string "상관없구나...\p"
	.string "알고 싶은 게 너무 많아-$"
	// そっか…ｎ
	// かんけいないのか…ｐ
	// しりたいことって たくさんあるな-
