gBerryDescriptionPart1_Cheri:: @ 8589AE4
	.string "매우 귀여운 꽃이 핀다.$"

gBerryDescriptionPart2_Cheri:: @ 8589B09
	.string "새빨간 열매는 아주 맵다.$"

gBerryDescriptionPart1_Chesto:: @ 8589B2D
	.string "겉 부분과 속 모두$"

gBerryDescriptionPart2_Chesto:: @ 8589B52
	.string "딱딱하다. 어느 부분을 먹어도 떫다.$"

gBerryDescriptionPart1_Pecha:: @ 8589B7A
	.string "매우 달고 맛있다.$"

gBerryDescriptionPart2_Pecha:: @ 8589B94
	.string "부드러워서 운반할 때는 주의.$"

gBerryDescriptionPart1_Rawst:: @ 8589BB9
	.string "잎사귀의 부분이 길고 둥글게$"

gBerryDescriptionPart2_Rawst:: @ 8589BDC
	.string "말려 있으면 아주 쓴 듯하다.$"

gBerryDescriptionPart1_Aspear:: @ 8589C01
	.string "딱딱한 열매 속에는 수분이 매우$"

gBerryDescriptionPart2_Aspear:: @ 8589C25
	.string "많이 들어 있다. 꽤 시다.$"

gBerryDescriptionPart1_Leppa:: @ 8589C3E
	.string "버치 등과 비교해 느리게$"

gBerryDescriptionPart2_Leppa:: @ 8589C62
	.string "자란다. 열매가 작은 것일수록 맛있다.$"

gBerryDescriptionPart1_Oran:: @ 8589C86
	.string "여러 가지 맛이 섞인 신기한 열매.$"

gBerryDescriptionPart2_Oran:: @ 8589CAE
	.string "열매를 키우는 데 반나절이 걸린다.$"

gBerryDescriptionPart1_Persim:: @ 8589CCA
	.string "태양을 좋아한다. 햇빛을 받으면$"

gBerryDescriptionPart2_Persim:: @ 8589CEC
	.string "점점 색이 선명해진다.$"

gBerryDescriptionPart1_Lum:: @ 8589D11
	.string "자라는 데 시간이 걸리지만 소중하게$"

gBerryDescriptionPart2_Lum:: @ 8589D35
	.string "키우면 열매가 2개 자라기도 한다.$"

gBerryDescriptionPart1_Sitrus:: @ 8589D54
	.string "오랭과는 형제 같은 존재.$"

gBerryDescriptionPart2_Sitrus:: @ 8589D77
	.string "크고 맛도 고르다.$"

gBerryDescriptionPart1_Figy:: @ 8589D98
	.string "먹힌 듯한 모양 속에는$"

gBerryDescriptionPart2_Figy:: @ 8589DBA
	.string "매운 성분이 가득 차 있다.$"

gBerryDescriptionPart1_Wiki:: @ 8589DD7
	.string "주위에 붙어 있는 돌기는 포켓몬이$"

gBerryDescriptionPart2_Wiki:: @ 8589DFD
	.string "지니기 쉽게 하기 위해서라고 한다.$"

gBerryDescriptionPart1_Mago:: @ 8589E16
	.string "크게 자랄수록 열매가 구부러진다.$"

gBerryDescriptionPart2_Mago:: @ 8589E39
	.string "구부러질수록 달고 맛있다.$"

gBerryDescriptionPart1_Aguav:: @ 8589E5F
	.string "작은 크기의 꽃으로 그것도 빛을$"

gBerryDescriptionPart2_Aguav:: @ 8589E87
	.string "필요로 하지 않는 희귀한 나무열매다.$"

gBerryDescriptionPart1_Iapapa:: @ 8589EA6
	.string "매우 크고 신 나무열매다.$"

gBerryDescriptionPart2_Iapapa:: @ 8589EC6
	.string "키우는 데는 적어도 1일이 걸린다.$"

gBerryDescriptionPart1_Razz:: @ 8589EE7
	.string "빨간 열매는 먹으면 약간 맵고$"

gBerryDescriptionPart2_Razz:: @ 8589F0C
	.string "빠르게 자라서 4시간이면 열매가 열린다.$"

gBerryDescriptionPart1_Bluk:: @ 8589F31
	.string "겉 부분은 파란색이지만 먹으면$"

gBerryDescriptionPart2_Bluk:: @ 8589F57
	.string "입속이 새까맣게 된다.$"

gBerryDescriptionPart1_Nanab:: @ 8589F79
	.string "세상에서 7번째로 발견된 것이$"

gBerryDescriptionPart2_Nanab:: @ 8589F94
	.string "이름의 유래라는 설이 유력하다. 달다.$"

gBerryDescriptionPart1_Wepear:: @ 8589FBA
	.string "작고 하얀 꽃이 핀다. 쓴맛과$"

gBerryDescriptionPart2_Wepear:: @ 8589FE2
	.string "신맛이 섞여 있는 미묘한 맛이다.$"

gBerryDescriptionPart1_Pinap:: @ 858A007
	.string "바람에 약하고 추위에도 약하다.$"

gBerryDescriptionPart2_Pinap:: @ 858A023
	.string "열매의 속이 맵고 겉 부분은 시다.$"

gBerryDescriptionPart1_Pomeg:: @ 858A04A
	.string "아무리 비가 내려도 영양이$"

gBerryDescriptionPart2_Pomeg:: @ 858A066
	.string "있어도 6개의 열매밖에 자라지 않는다.$"

gBerryDescriptionPart1_Kelpsy:: @ 858A087
	.string "뿌리 같은 모양의 희귀한$"

gBerryDescriptionPart2_Kelpsy:: @ 858A0AA
	.string "종류이다. 매우 큰 꽃이 핀다.$"

gBerryDescriptionPart1_Qualot:: @ 858A0C5
	.string "물을 좋아한다. 계속 비가 내리는$"

gBerryDescriptionPart2_Qualot:: @ 858A0E7
	.string "장소라도 쑥쑥 잘 자란다.$"

gBerryDescriptionPart1_Hondew:: @ 858A109
	.string "매우 비싸서 좀처럼 눈으로$"

gBerryDescriptionPart2_Hondew:: @ 858A12B
	.string "보기 힘든 나무열매. 아주 맛있다.$"

gBerryDescriptionPart1_Grepa:: @ 858A14E
	.string "부드러움과 둥근 모양으로는$"

gBerryDescriptionPart2_Grepa:: @ 858A16F
	.string "상상할 수 없을 정도로 시다.$"

gBerryDescriptionPart1_Tamato:: @ 858A196
	.string "입술이 새빨개질 정도로 맵다.$"

gBerryDescriptionPart2_Tamato:: @ 858A1B8
	.string "키우는 데에도 시간이 걸린다.$"

gBerryDescriptionPart1_Cornn:: @ 858A1CF
	.string "옛날부터 자라왔다. 많이 심지$"

gBerryDescriptionPart2_Cornn:: @ 858A1F4
	.string "않으면 열매가 열리지 않을 때도 있다.$"

gBerryDescriptionPart1_Magost:: @ 858A215
	.string "매우 맛의 균형이 좋다고$"

gBerryDescriptionPart2_Magost:: @ 858A239
	.string "평판이 자자한 나무열매다.$"

gBerryDescriptionPart1_Rabuta:: @ 858A253
	.string "많은 털이 자라있는 희귀한$"

gBerryDescriptionPart2_Rabuta:: @ 858A279
	.string "종류이다. 꽤 쓰다.$"

gBerryDescriptionPart1_Nomel:: @ 858A293
	.string "꽤 시다. 한입 먹으면$"

gBerryDescriptionPart2_Nomel:: @ 858A2B6
	.string "3일간 다른 맛이 나지 않게 된다.$"

gBerryDescriptionPart1_Spelon:: @ 858A2DA
	.string "새빨개진 열매는 말도 못하게 맵다.$"

gBerryDescriptionPart2_Spelon:: @ 858A2FF
	.string "돌기로부터도 매운 성분이 나오고 있다.$"

gBerryDescriptionPart1_Pamtre:: @ 858A324
	.string "어딘가에서 난데없이 떠내려온다.$"

gBerryDescriptionPart2_Pamtre:: @ 858A346
	.string "세상 어딘가에서 키워지고 있는 듯하다.$"

gBerryDescriptionPart1_Watmel:: @ 858A367
	.string "매우 커서 50cm를 넘는 것도$"

gBerryDescriptionPart2_Watmel:: @ 858A387
	.string "발견되었다. 굉장히 달다$"

gBerryDescriptionPart1_Durin:: @ 858A3AD
	.string "보기만 해도 쓰다. 너무나도 써서$"

gBerryDescriptionPart2_Durin:: @ 858A3CE
	.string "그대로 먹은 사람은 아무도 없다.$"

gBerryDescriptionPart1_Belue:: @ 858A3F6
	.string "매끈해서 맛있어 보이지만 말도 못하게$"

gBerryDescriptionPart2_Belue:: @ 858A41C
	.string "시다. 키우는 데에도 시간이 걸린다.$"

gBerryDescriptionPart1_Liechi:: @ 858A444
	.string "수수께끼의 씨앗. 치리열매에는$"

gBerryDescriptionPart2_Liechi:: @ 858A469
	.string "바다의 힘이 깃들어 있다는 소문이 있다.$"

gBerryDescriptionPart1_Ganlon:: @ 858A487
	.string "수수께끼의 씨앗. 용아열매에는$"

gBerryDescriptionPart2_Ganlon:: @ 858A4AC
	.string "육지의 힘이 깃들어 있다는 소문이 있다.$"

gBerryDescriptionPart1_Salac:: @ 858A4CB
	.string "수수께끼의 씨앗. 캄라열매에는$"

gBerryDescriptionPart2_Salac:: @ 858A4F0
	.string "하늘의 힘이 깃들어 있다는 소문이 있다.$"

gBerryDescriptionPart1_Petaya:: @ 858A50E
	.string "수수께끼의 씨앗. 야타비열매에는 모든$"

gBerryDescriptionPart2_Petaya:: @ 858A533
	.string "생명체의 힘이 깃들어 있다고 전해진다$"

gBerryDescriptionPart1_Apicot:: @ 858A55B
	.string "이상하고 이상한 나무열매다. 무엇이$"

gBerryDescriptionPart2_Apicot:: @ 858A57F
	.string "일어날지 무엇이 생길지 알 수 없다.$"

gBerryDescriptionPart1_Lansat:: @ 858A5A6
	.string "전설의 열매라고 전해진다. 이 열매를$"

gBerryDescriptionPart2_Lansat:: @ 858A5C4
	.string "가지고 있으면 매우 행복해지는 듯하다.$"

gBerryDescriptionPart1_Starf:: @ 858A5E6
	.string "너무나도 힘이 강하기 때문에$"

gBerryDescriptionPart2_Starf:: @ 858A609
	.string "세상의 끝에 버려진 나무열매다.$"

gBerryDescriptionPart1_Enigma:: @ 858A62C
	.string "정체불명의 나무열매다.$"

gBerryDescriptionPart2_Enigma:: @ 858A64A
	.string "별의 힘을 지니고 있는 듯하다.$"

