BerryBlender_Text_BlendWithTheBlendMaster: @ 82C427C
	.string "명인: 그래 내가 바로!\n"
	.string "블렌드 명인일세!\p"
	.string "함께 돌려서\n"
	.string "내 훌륭한 기술을 보는 게 좋을 걸세$"
	// めいじん『いかにも!ｎ
	// わしが ブレンドめいじん じゃ!ｐ
	// いっしょに まわしてｎ
	// わしの すごい わざを みるがよい

BerryBlender_Text_SeeMyMasteryInAction: @ 82C42F4
	.string "명인: 흐으으음! 그대\n"
	.string "내 훌륭한 기술을 보고 싶은 겐가?$"
	// めいじん『ふむむむっ! おぬしｎ
	// わしの すごい わざを みたいのじゃな?

BerryBlender_Text_TooBusyNowIsee: @ 82C4332
	.string "흐으으음!\p"
	.string "지금은 바쁜 듯하구먼!\p"
	.string "안심하는 좋다네!\n"
	.string "나는 오늘 쭉 여기 있겠네\l"
	.string "볼일이 있다면 바로 오게!$"
	// ふむむむっ!ｐ
	// いまは いそがしいのじゃな!ｐ
	// あんしん するのじゃ!ｎ
	// わしは きょう ずっと ここに おるｌ
	// ようが すんだら すぐに くるのじゃぞ!

BerryBlender_Text_BlendMasterNoBerries: @ 82C439D
	.string "흐으으음! 그대\p"
	.string "나무열매를 지니고 있지 않구먼!\p"
	.string "나는 오늘 쭉 여기 있을 테니\n"
	.string "빨리 나무열매를 찾아서 오게나!$"
	// ふむむむっ!ｐ
	// おぬし きのみを もっておらんぞ!ｐ
	// わしは きょう ずっと ここに おるからｎ
	// はやく きのみを みつけて くるのじゃぞ!

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks: @ 82C43FA
	.string "그렇지!\n"
	.string "그렇지!\p"
	.string "그나저나 그대...\n"
	.string "당연히 포켓몬스넥을 만드는\l"
	.string "방법은 알고 있겠지?$"
	// そうじゃろう!ｎ
	// そうじゃろう!ｐ
	// とろころで おぬし……ｎ
	// むろん ポロックの つくりかたはｌ
	// しっておる じゃろうな?

BerryBlender_Text_BlendMasterExplainBerryBlending: @ 82C444C
	.string "흐으으음!\p"
	.string "뭐어 간단한 걸세!\p"
	.string "나무열매블렌더의 마크가\n"
	.string "자신이 있는 쪽으로 오면\l"
	.string "버튼을 누르는 것 뿐이라네!\p"
	.string "내 완벽한 손짓을 본다면\n"
	.string "바로 알 수 있을 걸세!$"
	// ふむむむっ!ｐ
	// まあ かんたんな ことじゃ!ｐ
	// きのみ ブレンダ-の マ-クがｎ
	// じぶんの ところに きたらｌ
	// ボタンを おせば いいだけじゃ!ｐ
	// わしの かんぺきな おしかたを みればｎ
	// すぐに わかるはずじゃ!

BerryBlender_Text_BlendMasterLetsBerryBlender: @ 82C451B
	.string "좋네!\p"
	.string "그럼 시작해 봅세!\p"
	.string "명인과 함께\n"
	.string "레츠 나무열매블렌더!$"
	// よしっ!ｐ
	// では はじめるぞ!ｐ
	// めいじんと いっしょにｎ
	// レッツ きのみブレンダ-!

BerryBlender_Text_BlendMasterNoPokeblockCase: @ 82C4573
	.string "흐으으음!\p"
	.string "그대 포켓몬스넥케이스를\n"
	.string "아직 가지고 있지 않구먼!\p"
	.string "나는 오늘 쭉 여기 있을 테니\n"
	.string "포켓몬스넥케이스를 얻고 나서\l"
	.string "다시 오게나!$"
	// ふむむむっ!ｐ
	// おぬし ポロックケ-スをｎ
	// まだ もっておらん ようじゃぞ!ｐ
	// わしは きょう ずっと ここに おるからｎ
	// ポロックケ-スを もらってからｌ
	// また くるのじゃ!

BerryBlender_Text_BlendMasterPokeblockCaseFull: @ 82C45E8
	.string "흐으으음!\p"
	.string "그대 포켓몬스넥케이스가\n"
	.string "가득 찬 모양이구먼!\p"
	.string "나는 오늘 쭉 여기 있을 테니\n"
	.string "포켓몬스넥을 줄이고 나서\l"
	.string "다시 오게나!$"
	// ふむむむっ!ｐ
	// おぬし ポロックケ-スがｎ
	// いっぱいの ようじゃぞ!ｐ
	// わしは きょう ずっと ここに おるからｎ
	// ポロックを へらしてからｌ
	// また くるのじゃ!

BerryBlender_Text_WhoaAwesome: @ 82C464B
	.string "대단해-!$"
	// すげぇ-!

BerryBlender_Text_WickedlyFast: @ 82C465A
	.string "빨라-!$"
	// はぇ-!

BerryBlender_Text_WhatAnExpert: @ 82C4669
	.string "맛있어-!$"
	// うめぇ-!

BerryBlender_Text_MadeAmazingPokeblocksWithMaster: @ 82C4679
	.string "명인과 함께 만들었더니\n"
	.string "매우 훌륭한 포켓몬스넥이 나왔어$"
	// めいじんと いっしょに やったらｎ
	// とっても すごい ポロック できたの

BerryBlender_Text_QualitiesOfBlendMaster: @ 82C46B1
	.string "화살표를 따라가는\n"
	.string "빈틈없는 눈의 움직임!\p"
	.string "버튼을 누를 때의\n"
	.string "정확한 손의 움직임!\p"
	.string "이 둘을 겸비한\n"
	.string "명인은 정말 대단하네!$"
	// やじるしを おっていくｎ
	// スキのない めの うごき!ｐ
	// ボタンを おすときのｎ
	// せいかくな ての うごき!ｐ
	// この ふたつを あわせもつｎ
	// めいじんは ホント すごいね!

BerryBlender_Text_MasterWorksOnSkillsInMountains: @ 82C4763
	.string "명인은 어딘가의 산속에서\n"
	.string "수행을 하고 있는 것 같아\p"
	.string "그리고 가끔씩\n"
	.string "해안시티로 와서\l"
	.string "나무열매블렌더를 1일 동안\l"
	.string "한다고 들었어$"
	// めいじんは どこかの やまおくでｎ
	// しゅぎょう しているらしいのｐ
	// そして ときどきｎ
	// ミナモシティに やってきてｌ
	// きのみブレンダ-を 1にちじゅうｌ
	// するらしいわ$
