Underwater_SealedChamber_Braille_GoUpHere: @ 82A6B15
	.byte 3
	.byte 6
	.byte 26
	.byte 13
	.byte 5
	.byte 9
	.braille "⠱⠈⠕⠠⠎⠀⠍⠗⠐⠥$"
	@ 여기서 위로(작업 완료)

SealedChamber_OuterRoom_Braille_ABC: @ 82A6B27
	.byte 1
	.byte 6
	.byte 29
	.byte 13
	.byte 3
	.byte 9
	.braille "⠈⠉⠊⠐⠑⠘⠠⠨⠰⠋⠓⠙⠚$"
	@ ᄀᄂᄃᄅᄆᄇᄉᄌᄎᄏᄐᄑᄒ(작업 완료)

SealedChamber_OuterRoom_Braille_GHI: @ 82A6B31
	.byte 10
	.byte 6
	.byte 18
	.byte 13
	.byte 14
	.byte 9
	.braille "⠠$"
	@ 쌍자음 표시(작업 완료)

SealedChamber_OuterRoom_Braille_MNO: @ 82A6B3B
	.byte 0
	.byte 6
	.byte 29
	.byte 13
	.byte 1
	.byte 9
	.braille "⠁⠒⠔⠂⠢⠃⠄⠶⠅⠆⠖⠦⠲⠴$"
	@ ᆨᆫᆮᆯᆷᆸᆺᆼᆽᆾᆿᇀᇁᇂ(작업 완료)

SealedChamber_OuterRoom_Braille_TUV: @ 82A6B45
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠣⠜⠎⠱⠥⠬⠍⠩⠪⠕⠗$"
	@ ᅡᅣᅥᅧᅩᅭᅮᅲᅳᅵᅢ(작업 완료)

SealedChamber_OuterRoom_Braille_DEF: @ 82A6B4F
	.byte 0
	.byte 6
	.byte 29
	.byte 13
	.byte 1
	.byte 9
	.braille "⠜⠗⠝⠌⠧⠧⠗⠽⠏⠏⠗⠍⠗⠺$"
	@ ᅤᅦᅨᅪᅫᅬᅯᅰᅱᅴ(작업 완료)

SealedChamber_OuterRoom_Braille_JKL: @ 82A6B59
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠫⠉⠊⠑⠘⠇⠨⠋⠓⠙⠚$"
	@ 가나다마바사자카타파하(작업 완료)

SealedChamber_OuterRoom_Braille_PQRS: @ 82A6B63
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠹⠾⠞⠡⠳⠻⠭⠷⠿⠛⠯$"
	@ 억언얼연열영옥온옹운울(작업 완료)

SealedChamber_OuterRoom_Braille_Period: @ 82A6B6E
	.byte 8
	.byte 6
	.byte 22
	.byte 13
	.byte 10
	.byte 9
	.braille "⠵⠮⠟⠸⠎⠌$"
	@ 은을인것ㅆ(작업 완료)

SealedChamber_OuterRoom_Braille_WXYZ: @ 82A6B76
	.byte 3
	.byte 6
	.byte 27
	.byte 13
	.byte 5
	.byte 9
	.braille "⠁⠎ ⠁⠉⠀⠁⠒⠀⠁⠢$"
	@ 그래서 그러나 그러면 그러므로(작업 완료)

SealedChamber_OuterRoom_Braille_Comma: @ 82A6B81
	.byte 5
	.byte 6
	.byte 24
	.byte 13
	.byte 7
	.byte 9
	.braille "⠁⠝⠀⠁⠥⠀⠁⠱$"
	@ 그런데 그리고 그리하여(작업 완료)

SealedChamber_OuterRoom_Braille_DigHere: @ 82A6B89
	.byte 5
	.byte 4
	.byte 25
	.byte 15
	.byte 7
	.byte 7
	.braille "⠱⠈⠕⠠⠎\n"
	.braille "⠈⠍⠑⠎⠶⠙⠈⠕$"
	@ 여기서\n구멍파기(작업 완료)

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth: @ 82A6B99
	.byte 2
	.byte 0
	.byte 28
	.byte 19
	.byte 4
	.byte 3
	.braille "⠰⠎⠪⠢⠝⠀⠈⠥⠐⠗⠧⠶\n"
	.braille "⠠⠈⠪⠦⠝⠀⠠⠕⠐⠣⠋⠒\n"
	.braille "⠁⠒⠀⠑⠥⠊⠵⠀⠸⠎⠕\n"
	.braille "⠳⠐⠟⠊$"
	@ 처음에 고래왕\n끝에 시라칸\n그러면 모든 것이\n열린다(작업 완료)

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived: @ 82A6BCA
	.byte 4
	.byte 0
	.byte 24
	.byte 19
	.byte 6
	.byte 3
	.braille "⠍⠐⠕⠊⠮⠵\n"
	.braille "⠕⠀⠊⠿⠈⠯⠝⠠⠎\n"
	.braille "⠠⠗⠶⠚⠧⠂⠚⠈⠥\n"
	.braille "⠇⠂⠣⠧⠌⠊$"
	@ 우리들은\n이 동굴에서\n생활하고\n살아왔다(작업 완료)

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon: @ 82A6BEC
	.byte 4
	.byte 2
	.byte 22
	.byte 17
	.byte 6
	.byte 5
	.braille "⠑⠥⠊⠵⠀⠸⠎⠵\n"
	.braille "⠙⠥⠋⠝⠄⠑⠷\n"
	.braille "⠊⠹⠘⠛⠕⠊$"
	@ 모든 것은\n포켓몬\n덕분이다(작업 완료)

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway: @ 82A6C0D
	.byte 3
	.byte 0
	.byte 27
	.byte 19
	.byte 5
	.byte 3
	.braille "⠁⠉\n"
	.braille "⠍⠐⠕⠊⠮⠵\n"
	.braille "⠈⠪⠀⠙⠥⠋⠝⠄⠑⠷⠮\n"
	.braille "⠫⠊⠍⠎⠌⠊$"
	@ 그러나\n우리들은\n그 포켓몬을\n가두었다(작업 완료)

SealedChamber_InnerRoom_Braille_WeFearedIt: @ 82A6C34
	.byte 7
	.byte 6
	.byte 23
	.byte 13
	.byte 9
	.byte 9
	.braille "⠑⠍⠠⠎⠏⠌⠊$"
	@ 무서웠다(작업 완료)

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope: @ 82A6C48
	.byte 4
	.byte 0
	.byte 24
	.byte 19
	.byte 6
	.byte 3
	.braille "⠬⠶⠈⠕⠀⠕⠌⠉⠵\n"
	.braille "⠨⠣⠱\n"
	.braille "⠚⠺⠑⠶⠝⠀⠰⠣⠒\n"
	.braille "⠨⠣⠱$"
	@ 용기 있는\n자여\n희망에 찬\n자여(작업 완료)

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits: @ 82A6C73
	.byte 2
	.byte 2
	.byte 28
	.byte 17
	.byte 4
	.byte 5
	.braille "⠑⠛⠮⠀⠳⠎⠐⠣\n"
	.braille "⠈⠪⠈⠥⠄⠝⠀⠻⠏⠒⠺\n"
	.braille "⠙⠥⠋⠝⠄⠑⠷⠕⠀⠕⠌⠊$"
	@ 문을 열어라\n그곳에 영원의\n포켓몬이 있다(작업 완료)

DesertRuins_Braille_UseRockSmash: @ 82A6CA0
	.byte 1
	.byte 0
	.byte 27
	.byte 19
	.byte 3
	.byte 3
	.braille "⠨⠧⠀⠨⠧\n"
	.braille "⠚⠀⠚\n"
	.braille "⠈⠎⠈⠕⠠⠎\n"
	.braille "⠘⠣⠍⠗⠐⠮⠀⠠⠈⠗⠐⠣$"
	@ 좌 좌\n하 하\n거기서\n바위를 깨라(작업 완료)

IslandCave_Braille_RunLapAroundWall: @ 82A6CD4
	.byte 1
	.byte 0
	.byte 29
	.byte 19
	.byte 3
	.byte 3
	.braille "⠘⠱⠁⠝⠠⠎\n"
	.braille "⠠⠊⠞⠎⠨⠕⠨⠕⠀⠑⠂⠈⠥\n"
	.braille "⠕⠈⠥⠄⠮\n"
	.braille "⠚⠒⠀⠘⠋⠍⠗⠀⠊⠥⠂⠣⠐⠣$"
	@ 벽에서\n떨어지지 말고\n이곳을\n한 바퀴 돌아라(작업 완료)

AncientTomb_Braille_ShineInTheMiddle: @ 82A6D06
	.byte 0
	.byte 0
	.byte 29
	.byte 19
	.byte 1
	.byte 3
	.braille "⠍⠐⠕⠊⠮⠺⠀⠺⠨⠕⠐⠮\n"
	.braille "⠕⠄⠉⠵⠀⠨⠣⠱\n"
	.braille "⠨⠍⠶⠠⠕⠢⠝⠠⠎\n"
	.braille "⠘⠕⠆⠉⠐⠣$"
	@ 우리들의 의지를\n잇는 자여\n중심에서\n빛나라(작업 완료)
