CableClub_Text_WelcomeWhichCableClubService: @ 8277EA4
	.string "통신케이블 클럽에\n"
	.string "잘 오셨습니다!\p"
	.string "어느 쪽을 이용하겠습니까?$"
	// つうしん ケ-ブル クラブにｎ
	// ようこそ!ｐ
	// どちらを ごりよう ですか?

CableClub_Text_WhichService: @ 8277EF1
	.string "어느 쪽을 이용하겠습니까?$"
	// どちらを ごりよう ですか?

CableClub_Text_TradeUsingLinkCable:: @ 8277F1B
	.string "케이블로 연결된 친구와\n"
	.string "포켓몬 교환을 할 수 있습니다$"
	// ケ-ブルで つないだ おともだちとｎ
	// ポケモン こうかんが できます

CableClub_Text_BattleUsingLinkCable:: @ 8277F5A
	.string "케이블로 연결된 친구와\n"
	.string "포켓몬 대전을 할 수 있습니다$"
	// ケ-ブルで つないだ おともだちとｎ
	// ポケモン たいせんが できます

CableClub_Text_RecordCornerUsingLinkCable:: @ 8277F96
	.string "케이블로 연결된 친구와\n"
	.string "레코드코너를 할 수 있습니다$"
	// ケ-ブルで つないだ おともだちとｎ
	// レコ-ドコ-ナ-が できます

@ Unused
CableClub_Text_CloseThisMenu: @ 8277FDD
	.string "종료합니다$"
	// おわります

CableClub_Text_NeedTwoMonsForDoubleBattle: @ 8277FEE
	.string "더블배틀에서는 2마리 이상의\n"
	.string "포켓몬이 필요합니다$"
	// ダブルバトルでは 2ひき いじょうのｎ
	// ポケモンが ひつようです

CableClub_Text_NeedTwoMonsToTrade: @ 8278027
	.string "교환을 하기 위해서는 2마리 이상의\n"
	.string "포켓몬을 지니고 있어야 합니다$"
	// こうかんでは 2ひき いじょうのｎ
	// てもちが ひつようです

CableClub_Text_CantTradeEnigmaBerry: @ 8278061
	.string "{STR_VAR_1}열매를 지닌 포켓몬은\n"
	.string "교환할 수 없습니다!$"
	// {STR_VAR_1}のみを もっているｎ
	// ポケモンは こうかん できません!

gText_PleaseWaitForLink:: @ 8278091
	.string "잠시 기다려 주십시오\n"
	.string "...B 버튼으로 취소$"
	// しょうしょう おまち くださいｎ
	// ……Bボタンで キャンセル

gText_ConfirmLinkWhenPlayersReady:: @ 82780B3
	.string "모이면 A 버튼으로 진행한다\n"
	.string "...B 버튼으로 취소$"
	// そろったら Aボタンで すすむｎ
	// ……Bボタンで キャンセル

gText_ConfirmStartLinkWithXPlayers:: @ 82780F2
	.string "{STR_VAR_1}명이서 통신을 시작합니다\n"
	.string "A 버튼...결정 B 버튼...취소$"
	// {STR_VAR_1}にんで つうしんを はじめますｎ
	// Aボタン…けってい Bボタン…もどる

gText_AwaitingLinkup:: @ 8278131
	.string "통신 시작을 기다리고 있습니다\n"
	.string "...B 버튼으로 취소$"
	// つうしんかいしを まっていますｎ
	// ……Bボタンで キャンセル

@ Unused
CableClub_Text_OkayToSaveProgress:: @ 8278157
	.string "통신을 시작하기 전에\n"
	.string "리포트를 작성합니다만 괜찮습니까?$"
	// はじめる まえに レポ-トをｎ
	// かきますが よろしいですか?

CableClub_Text_PleaseEnter: @ 8278197
	.string "그럼 방으로 들어가십시오$"
	// それでは へやへ どうぞ

CableClub_Text_DirectYouToYourRoom: @ 82781A5
	.string "그럼\n"
	.string "방으로 안내하겠습니다$"
	// それではｎ
	// へやに ごあんないします

Text_SomeoneIsNotReadyToLink: @ 82781C7
	.string "친구의 준비가\n"
	.string "되지가 않은 것 같습니다\p"
	.string "준비를 마치면\n"
	.string "다시 와주십시오$"
	// おともだちの じゅんびがｎ
	// できて いない ようですｐ
	// じゅんびが できましたらｎ
	// また おこしください

Text_LinkErrorPleaseReset: @ 827821C
	.string "통신 에러입니다\n"
	.string "리셋한 후 다시 해주십시오$"
	// つうしんエラ- ですｎ
	// リセットして やりなおしてください

Text_PlayersMadeDifferentSelections: @ 8278255
	.string "서로 선택한 것이\n"
	.string "다른 것 같습니다$"
	// おたがいが えらんだ ものがｎ
	// ちがっている ようです

CableClub_Text_PleaseVisitAgain: @ 8278291
	.string "그럼 또 방문해 주십시오$"
	// それでは また おこしください

CableClub_Text_IncorrectNumberOfParticipants: @ 82782A8
	.string "참가한 인원수가\n"
	.string "맞지 않습니다$"
	// さんかしている にんずうがｎ
	// ただしく ありません

CableClub_Text_CantSingleBattleWithXPlayers: @ 82782D1
	.string "싱글배틀은 {STR_VAR_1}명이서\n"
	.string "즐길 수 없습니다!$"
	// シングルバトルは {STR_VAR_1}にんでｎ
	// あそぶことは できません!

CableClub_Text_CantDoubleBattleWithXPlayers: @ 8278307
	.string "더블배틀은 {STR_VAR_1}명이서\n"
	.string "즐길 수 없습니다!$"
	// ダブルバトルは {STR_VAR_1}にんではｎ
	// あそぶことは できません!

CableClub_Text_NeedFourPlayers: @ 827833D
	.string "참가 인원수가 4명이 아니면\n"
	.string "대전할 수 없습니다!$"
	// さんか にんずうが 4にん いないとｎ
	// たいせん することが できません!

CableClub_Text_PleaseConfirmNumberAndRestart: @ 8278372
	.string "다시 한 번 인원수를 확인하고\n"
	.string "처음부터 다시 해주십시오$"
	// もういちど にんずうを たしかめてｎ
	// はじめから やりなおして ください

Text_TerminateLinkConfirmation: @ 82783A8
	.string "방에서 나가면 통신이\n"
	.string "종료됩니다만 괜찮겠습니까?$"
	// へやからでると つうしんがｎ
	// おわりますが よろしいですか?

Text_TerminateLinkPleaseWait: @ 82783E9
	.string "통신을 종료합니다\n"
	.string "잠시 기다려 주십시오$"
	// つうしんを しゅうりょう しますｎ
	// しばらく おまちください

CableClub_Text_TooBusyToNotice: @ 827842E
	.string "바쁜 것 같다...$"
	// とりこみちゅうの ようだ…

CableClub_Text_GotToLookAtTrainerCard: @ 8278452
	.string "{STR_VAR_1}의 트레이너카드를\n"
	.string "봤다!$"
	// {STR_VAR_1}の トレ-ナ-カ-ドをｎ
	// みせてもらった!

CableClub_Text_GotToLookAtColoredTrainerCard: @ 827847B
	.string "{STR_VAR_1}의 트레이너카드를\n"
	.string "봤다!\p"
	.string "...{STR_VAR_2}카드다!$"
	// {STR_VAR_1}の トレ-ナ-カ-ドをｎ
	// みせてもらった!ｐ
	// …{STR_VAR_2}うカ-ドだ!

BattleColosseum_2P_Text_TakePlaceStartBattle: @ 82784B4
	.string "각자 자리에 서서\n"
	.string "대전을 시작해 주십시오$"
	// しょていの いちに ついてｎ
	// たいせんを はじめて ください

TradeCenter_Text_TakeSeatStartTrade: @ 82784E2
	.string "각자 자리에 서서\n"
	.string "교환을 시작해 주십시오$"
	// しょていの いちに ついてｎ
	// こうかんを はじめて ください

RecordCorner_Text_ThanksForComing: @ 827850E
	.string "이용해 주셔서 감사합니다$"
	// ごりよう ありがとう ございました

CableClub_Text_TrainerCardDataOverwritten: @ 8278521
	.string "트레이너카드의\n"
	.string "기록을 다시 씁니다!$"
	// トレ-ナ-カ-ドのｎ
	// きろくを かきかえます!

CableClub_Text_HopeToSeeYouAgain: @ 827854C
	.string "또 이용해 주세요!$"
	// では また どうぞ!

CableClub_Text_NotSetUpForFarAwayRegion: @ 8278565
	.string "손님\n"
	.string "죄송합니다\p"
	.string "먼 지방의 분과\n"
	.string "포켓몬을 교환하는 건\l"
	.string "지금은 할 수 없습니다...$"
	// おきゃくさまｎ
	// もうしわけ ありませんｐ
	// とおい ちほうの かたとｎ
	// ポケモンを こうかん することはｌ
	// いまは できません…

CableClub_Text_OtherTrainerNotReady: @ 82785C9
	.string "상대의 준비가\n"
	.string "되지 않은 것 같습니다$"
	// あいての じゅんびがｎ
	// できていません

CableClub_Text_YouHaveAMonThatCantBeTaken: @ 82785E9
	.string "지닌 포켓몬에 데려갈 수 없는\n"
	.string "포켓몬이 있습니다$"
	// てもちに つれていけないｎ
	// ポケモンが います

RecordCorner_Text_TakeSeatAndWait: @ 827861C
	.string "자리에 서서\n"
	.string "기다려 주십시오$"
	// しょていの いちに ついてｎ
	// おまち ください

RecordCorner_Text_PlayerSentOverOneX: @ 827863C
	.string "{STR_VAR_1}{K_EU}로부터\n"
	.string "{STR_VAR_2}{K_IGA} 전송됐다!$"
	// {STR_VAR_1}さんからｎ
	// {STR_VAR_2}が おくられてきた!

CableClub_Text_CantMixWithJapaneseGame: @ 8278651
	.string "손님 죄송합니다\n"
	.string "전송 에러가 발생했습니다\p"
	.string "일어판 루비나 사파이어와는\n"
	.string "레코드를 섞을 수 없습니다\p"
	.string "또한 일어판 에메랄드나\n"
	.string "해외의 루비나 사파이어와도\l"
	.string "레코드를 섞을 수 없습니다$"

CableClub_Text_AdapterNotConnected: @ 827871F
	.string "무선어댑터가\n"
	.string "연결되어 있지 않습니다$"
	// ワイヤレスアダプタがｎ
	// つながって いません

CableClub_Text_ParticipantsStepUpToCounter: @ 827874F
	.string "참가하고 싶은 사람은\n"
	.string "카운터에 들어오십시오$"
	// さんか したい ひとはｎ
	// カウンタ-に おこしください

@ Unused
CableClub_Text_Hello: @ 827878B
	.string "안녕하세요!$"
	// こんにちは!

@ Unused
CableClub_Text_PleaseWait: @ 8278792
	.string "잠시 기다려 주십시오$"
	// しょうしょう おまちください

CableClub_Text_YouMayTradeHere:: @ 827879F
	.string "친구와 포켓몬 교환을\n"
	.string "즐길 수 있습니다$"
	// ともだちと ポケモンのｎ
	// こうかんが たのしめます

CableClub_Text_YouMayBattleHere:: @ 82787D5
	.string "친구와 포켓몬 대전을\n"
	.string "즐길 수 있습니다$"
	// ともだちと ポケモンのｎ
	// たいせんが たのしめます

CableClub_Text_CanMakeBerryPowder:: @ 82787FC
	.string "2명부터 5명의 친구와\n"
	.string "나무열매로 가루를 만듭니다$"
	// 2にんから 5にんの ともだちとｎ
	// きのみで こなを つくります

CableClub_Text_CanMixRecords:: @ 8278831
	.string "2명부터 4명의 친구와\n"
	.string "레코드를 섞습니다$"
	// 2にんから 4にんの ともだちとｎ
	// レコ-ドを まぜます

@ Unused
CableClub_Text_GuideToVariousServices: @ 827886B
	.string "무선 클럽의\n"
	.string "이용 방법을 설명합니다$"
	// ワイヤレス クラブでのｎ
	// あそびかたを せつめいします

CableClub_Text_CancelSelectedItem:: @ 827889C
	.string "그만둡니다$"
	// やめます

@ Unused
CableClub_Text_WhichBattleMode: @ 82788BC
	.string "어느 승부를 하겠습니까?$"
	// どちらの しょうぶに しますか?

@ Unused
CableClub_Text_ReturnsToPreviousStep: @ 82788DE
	.string "한 단계 전으로 돌아갑니다$"
	// ひとつ まえに もどります

CableClub_Text_NeedBerryForBerryCrush: @ 82788FC
	.string "나무열매를 지니고 있지 않으면\n"
	.string "나무열매크러시는 할 수 없습니다$"
	// きのみを もって いないとｎ
	// きのみクラッシュは できません

CableClub_Text_NeedTwoMonsForUnionRoom: @ 827893E
	.string "유니언 룸에 들어가려면\n"
	.string "2마리 이상의 포켓몬을\l"
	.string "지니고 와주십시오$"
	// ユニオンル-ムに はいるにはｎ
	// 2ひき いじょうの ポケモンをｌ
	// もって おこしください

CableClub_Text_NoEnigmaBerryInUnionRoom: @ 827897B
	.string "{STR_VAR_1}열매를 지닌\n"
	.string "포켓몬을 데리고 계신 분은\l"
	.string "유니언 룸에 들어갈 수 없습니다...$"
	// {STR_VAR_1}のみを もっているｎ
	// ポケモンを おもちの かたはｌ
	// ユニオンル-ムには はいれません…

CableClub_Text_UnionRoomAdapterNotConnected: @ 82789B5
	.string "여기는\n"
	.string "포켓몬 무선 클럽\l"
	.string "유니언 룸입니다\p"
	.string "무선어댑터가\n"
	.string "연결되어 있지 않습니다\p"
	.string "다음에 와주십시오$"
	// こちらはｎ
	// ポケモン ワイヤレス クラブｌ
	// ユニオン ル-ムですｐ
	// ワイヤレスアダプタがｎ
	// つながって いませんｐ
	// また おこしください

@ Unused
CableClub_Text_OhExcuseMe: @ 8278A39
	.string "아...\n"
	.string "손님!$"
	// あ……ｎ
	// おきゃくさま!

CableClub_Text_PlayerIsWaiting: @ 8278A48
	.string "어머! 지금 {STR_VAR_1}님도\n"
	.string "플레이 중인 것 같네요\l"
	.string "열심히 해주세요!$"
	// あら! いま {STR_VAR_1}さんもｎ
	// プレイちゅう みたいですねｌ
	// がんばって くださいね!

MossdeepCity_GameCorner_1F_Text_DescribeWhichGame: @ 8278A7D
	.string "저는 게임의 설명을\n"
	.string "맡고 있습니다!\p"
	.string "어느 설명을 듣겠습니까?$"
	// ぼくは ゲ-ムの せつめいをｎ
	// しますよ!ｌ
	// どの せつめいを ききますか?

MossdeepCity_GameCorner_1F_Text_PokemonJumpInfo: @ 8278ACB
	.string "“미니 포켓몬 점프”는\n"
	.string "덩굴로 된 줄을 A 버튼으로\l"
	.string "타이밍 좋게 뛰어넘는 게임입니다\p"
	.string "참가 가능한 포켓몬은\n"
	.string "키 70cm 정도의\l"
	.string "작은 포켓몬입니다\p"
	.string "박혀 있거나 날고 있는\n"
	.string "포켓몬은 점프를\l"
	.string "할 수 없기 때문에\l"
	.string "안타깝게도 참가할 수 없습니다\p"
	.string "모두 점프하는 타이밍이\n"
	.string "딱 맞는다면\l"
	.string "좋은 일이 있을 겁니다!$"
	// 「ミニポケモンでジャンプ」はｎ
	// ツルの なわを Aボタンでｌ
	// タイミングよく とぶ ゲ-ムですｐ
	// さんか できる ポケモンはｎ
	// たかさ 70センチくらい までのｌ
	// ちいさい ポケモンに なりますｐ
	// もぐっていたり とんでいたり するｎ
	// ポケモンは ジャンプがｌ
	// じょうずに できないのでｌ
	// ざんねんながら さんか できませんｐ
	// みんなの ジャンプの タイミングがｎ
	// ピッタリ あえばｌ
	// よいことが ありますよ!

MossdeepCity_GameCorner_1F_Text_DodrioBerryPickingInfo: @ 8278BF1
	.string "“두트리오 나무열매먹기”는\n"
	.string "두트리오의 머리 3개에\l"
	.string "명령해서 위에서 떨어지는\l"
	.string "나무열매가 땅에 닿지 않도록\l"
	.string "계속 먹는 게임입니다\p"
	.string "십자 버튼의\n"
	.string "위 오른쪽 왼쪽을 사용합니다\p"
	.string "이 게임을 하기 위해서는\n"
	.string "두트리오가 필요합니다$"
	// 「ド-ドリオのきのみどり」はｎ
	// ド-ドリオの 3つの あたまにｌ
	// めいれいして うえから おちてくるｌ
	// きのみを おとさないようにｌ
	// とりつづける ゲ-ムですｐ
	// じゅうじボタンのｎ
	// うえ みぎ ひだりを つかいますｐ
	// この ゲ-ムを あそぶにはｎ
	// ド-ドリオが ひつようです

MossdeepCity_GameCorner_1F_Text_TalkToOldManToPlay: @ 8278CAC
	.string "게임을 하려면\n"
	.string "옆의 할아버지한테 말해 줘$"
	// ゲ-ムを するならｎ
	// おとなりの おじいさんに いってね

MossdeepCity_GameCorner_1F_Text_WelcomeCanYouWait: @ 8278CEB
	.string "이야 어서 오렴\n"
	.string "무선 통신 게임하러 온 거지?\l"
	.string "잠깐만 기다려 주게나$"
	// やあ いらっしゃいｎ
	// ワイヤレスつうしんの ゲ-ムかな?ｌ
	// ちょっと まってね

MossdeepCity_GameCorner_1F_Text_ComeAgain: @ 8278D51
	.string "나중에 또 오렴!$"
	// また おいでね

MossdeepCity_GameCorner_1F_Text_AdapterNotConnected: @ 8278D68
	.string "무선어댑터를 연결하고 나서\n"
	.string "놀러 오렴!$"
	// ワイヤレスアダプタを つなげてｎ
	// あそびに おいで!

MossdeepCity_GameCorner_1F_Text_PlayWhichGame: @ 8278DAD
	.string "그럼 어느 게임을\n"
	.string "하고 싶니?$"
	// さて どの ゲ-ムをｎ
	// やりたいのかな?

MossdeepCity_GameCorner_1F_Text_EnterWhichPokemon: @ 8278DD9
	.string "어느 포켓몬을\n"
	.string "참가시킬 거니?$"
	// どの ポケモンをｎ
	// さんか させるのかな?

MossdeepCity_GameCorner_1F_Text_AllGoodToGo: @ 8278E00
	.string "준비가 되었다면\n"
	.string "힘차게 놀고 오렴!$"
	// じゅんびが できたよｎ
	// げんきに あそんで おいで!

@ Unused
MossdeepCity_GameCorner_1F_Text_LeavingDoComeAgain: @ 8278E3C
	.string "오늘은 돌아가는 거니?\n"
	.string "나중에 또 오렴!$"
	// きょうは かえるのかい?ｎ
	// また おいでね

MossdeepCity_GameCorner_1F_Text_ExplainRequiredMon: @ 8278E60
	.string "게임에 참가할 수 있는\n"
	.string "포켓몬을 지니고 있지 않네\p"
	.string "누가 참가할 수 있는지\n"
	.string "설명해 줄까?$"
	// ゲ-ムに さんかできるｎ
	// ポケモンを もって いないんだねｐ
	// だれが さんか できるかｎ
	// せつめいを しようか?

MossdeepCity_GameCorner_1F_Text_ShortJumpingPokemonAllowed: @ 8278EDC
	.string "“미니 포켓몬 점프”에\n"
	.string "참가할 수 있는 포켓몬은\l"
	.string "키 70cm 정도까지란다\p"
	.string "땅에 박혀 있거나\n"
	.string "떠 있는 포켓몬은\l"
	.string "점프할 수 없으니까\l"
	.string "나갈 수 없다네$"
	// 「ミニポケモンでジャンプ」にｎ
	// さんか できる ポケモンはｌ
	// たかさ 70センチくらい までだよｐ
	// じめんに もぐったりｎ
	// うかんでいる ポケモンはｌ
	// ジャンプ できないからｌ
	// でられないんだよ

MossdeepCity_GameCorner_1F_Text_OnlyDodrioAllowed: @ 8278FA4
	.string "“두트리오 나무열매먹기”는\n"
	.string "두트리오만\l"
	.string "참가할 수 있는 게임이야$"
	// 「ド-ドリオのきのみどり」はｎ
	// ド-ドリオ だけがｌ
	// さんか できる ゲ-ムなんだよ

@ Unused
MossdeepCity_GameCorner_1F_Text_RetryPlease: @ 8278FE0
	.string "다시 한 번 처음부터\n"
	.string "시도해 봐 주겠니?$"
	// もういちど はじめからｎ
	// やりなおして みて くれるかな?

CableClub_Text_WelcomeWhichDirectCornerRoom: @ 8279013
	.string "포켓몬 무선 클럽\n"
	.string "다이렉트 코너에 잘 오셨습니다!\p"
	.string "이쪽에서는 친구와 직접\n"
	.string "교류할 수 있습니다\p"
	.string "어느 방에 들어가겠습니까?$"
	// ポケモン ワイヤレス クラブｎ
	// ダイレクト コ-ナ-に ようこそ!ｐ
	// こちらでは ともだちと ちょくせつｎ
	// やりとり できますｐ
	// どの へやに はいりますか?

CableClub_Text_TradePokemon: @ 827909D
	.string "교환을 하겠습니까?$"
	// こうかんを しますか?

CableClub_Text_PlayWhichBattleMode: @ 82790BE
	.string "어느 대전을 하겠습니까?$"
	// どちらの たいせんを しますか?

CableClub_Text_AccessRecordCorner: @ 82790E8
	.string "레코드코너를 하겠습니까?$"
	// レコ-ドコ-ナ-を しますか?

CableClub_Text_UseBerryCrush: @ 8279114
	.string "나무열매크러시를 하겠습니까?$"
	// きのみクラッシュを しますか?

CableClub_Text_ExplainBattleModes: @ 8279142
	.string "대전에는 3종류의\n"
	.string "모드가 있습니다\p"
	.string "싱글배틀은 배틀하는 곳에\n"
	.string "포켓몬을 1마리 내보내서\l"
	.string "두 명이서 대전합니다\p"
	.string "더블배틀은 배틀하는 곳에\n"
	.string "포켓몬을 2마리씩 내보내서\l"
	.string "두 명이서 대전합니다\p"
	.string "멀티배틀은 배틀하는 곳에\n"
	.string "4명이서 포켓몬을 1마리씩\l"
	.string "내보내서 2대2로 대전합니다$"
	// たいせんには 3しゅるいのｎ
	// モ-ドが ありますｐ
	// シングルバトルは たたかいの ばにｎ
	// ポケモンを 1ひきだしてｌ
	// ふたりで たいせんしますｐ
	// ダブルバトルは たたかいの ばにｎ
	// ポケモンを 2ひきずつ だしてｌ
	// ふたりで たいせんしますｐ
	// マルチバトルは たたかいの ばにｎ
	// 4にんで ポケモンを 1ひきずつｌ
	// だして 2たい2で たいせんします

CableClub_Text_ChooseGroupLeaderOfTwo: @ 82792CD
	.string "둘이 의논해서 한 명이\n"
	.string "리더가 되어 주십시오\p"
	.string "다른 한 명은 그룹에 들어간다를\n"
	.string "선택해 주십시오$"
	// ふたりで はなしあって ひとりがｎ
	// リ-ダ-に なってくださいｐ
	// もうひとりは グル-プにはいる をｎ
	// えらんでください

CableClub_Text_ChooseGroupLeaderOfFour: @ 8279334
	.string "4명이 의논해서 한 명이\n"
	.string "그룹의 리더가 되어 주십시오\p"
	.string "다른 사람은 그룹에 들어간다를\n"
	.string "선택해 주십시오$"
	// 4にんで はなしあって ひとりがｎ
	// グル-プリ-ダ-に なってくださいｐ
	// ほかの ひとは グル-プにはいる をｎ
	// えらんで ください

CableClub_Text_ChooseGroupLeader: @ 82793A3
	.string "모두 의논해서 한 명이\n"
	.string "그룹의 리더가 되어 주십시오\p"
	.string "다른 사람은 그룹에 들어간다를\n"
	.string "선택해 주십시오$"
	// みんなで はなしあって ひとりがｎ
	// グル-プリ-ダ-に なってくださいｐ
	// ほかの ひとは グル-プにはいる をｎ
	// えらんでください

CableClub_Text_WelcomeUnionRoomEnter: @ 827940D
	.string "포켓몬 무선 클럽\n"
	.string "유니언 룸에 잘 오셨습니다!\p"
	.string "여기에서는 전혀 모르는 친구들과\n"
	.string "교류할 수 있습니다\p"
	.string "방에 들어가겠습니까?$"
	// ポケモン ワイヤレス クラブｎ
	// ユニオン ル-ムに ようこそ!ｐ
	// こちらでは みしらぬ ともだちとｎ
	// やりとり できますｐ
	// へやに はいりますか?

CableClub_Text_UnionRoomInfo: @ 82794B8
	.string "유니언 룸으로 들어가면\n"
	.string "근처에서 유니언 룸에\l"
	.string "입장한 사람이 나타납니다\p"
	.string "간단한 인사를 하거나\p"
	.string "레벨 30까지의 포켓몬 2마리로\n"
	.string "1대1 대전\p"
	.string "2명부터 5명까지 동시에\n"
	.string "대화할 수 있는 채팅\p"
	.string "그리고 등록시킨\n"
	.string "포켓몬 교환을 할 수 있습니다\p"
	.string "방에 들어가겠습니까?$"
	// ユニオン ル-ム は あなたのｎ
	// ちかくで ユニオン ル-ムにｌ
	// はいっている ひとが あらわれますｐ
	// かんたんな あいさつをしたりｐ
	// レベル30までの ポケモン2ひきでｎ
	// 1たい1の たいせんｐ
	// 2にんから 5にんまで どうじにｎ
	// おしゃべりが できる チャットｐ
	// そして とうろくしきｎ
	// ポケモン こうかんが たのしめますｐ
	// へやに はいりますか?

CableClub_Text_EnjoyUnionRoom: @ 827961C
	.string "그럼 유니언 룸에서\n"
	.string "즐거운 시간을 보내십시오$"
	// それでは ユニオン ル-ムでｎ
	// おたのしみ ください

CableClub_Text_FirstTimeRightThisWay: @ 827964A
	.string "안녕하세요!\p"
	.string "무선 통신이\n"
	.string "처음이신 분이군요?\p"
	.string "저는 안내원인\n"
	.string "청채라고 합니다\p"
	.string "포켓몬센터 2층의\n"
	.string "안내를 맡고 있으니\l"
	.string "이쪽으로 와주세요!$"
	// こんにちは!ｐ
	// ワイヤレス つうしんがｎ
	// はじめての かたですね?ｐ
	// わたくし あんないやくのｎ
	// アオナと もうしますｐ
	// ポケモンセンタ- 2かいのｎ
	// ごあんないを いたしますのでｌ
	// こちらへ どうぞ!

CableClub_Text_ExplainWirelessClubFirstTime: @ 8279718
	.string "이쪽 2층에는\n"
	.string "두 개의 방이 있습니다\p"
	.string "첫 번째는 왼쪽 방\n"
	.string "유니언 룸!\p"
	.string "근처에서\n"
	.string "유니언 룸에 입장한\l"
	.string "전혀 모르는 친구와\l"
	.string "여러 대화를\l"
	.string "나눌 수 있습니다\p"
	.string "두 번째는 오른쪽 방\n"
	.string "다이렉트 코너!\p"
	.string "당신이 알고 있는 친구와\n"
	.string "포켓몬 교환이나\l"
	.string "대전 등 즐거운 일들을\l"
	.string "할 수 있습니다!\p"
	.string "만약 무선어댑터가\n"
	.string "연결되어 있지 않더라도\p"
	.string "오른쪽 방에서\n"
	.string "케이블 통신을 즐길 수 있습니다\p"
	.string "그럼\p"
	.string "무선 통신을\n"
	.string "즐겨 주십시오!$"
	// こちら 2かいにはｎ
	// ふたつの おへやが ございますｐ
	// ひとつめは ひだりがわの おへやｎ
	// ユニオン ル-ム!ｐ
	// あなたの ちかくでｎ
	// ユニオン ル-ムに はいっているｌ
	// みしらぬ おともだちとｌ
	// いろいろな コミュニケ-ションがｌ
	// たのしめます!ｐ
	// ふたつめは みぎがわの おへやｎ
	// ダイレクト コ-ナ-!ｐ
	// あなたの しっている おともだちとｎ
	// ポケモンの こうかんやｌ
	// たいせん などをｌ
	// たのしむ ことが できます!ｐ
	// もし ワイヤレスアダプタがｎ
	// つながって いない ばあいでもｐ
	// みぎがわの おへやでｎ
	// ケ-ブル つうしんが たのしめますｐ
	// それではｐ
	// ワイヤレス つうしんをｎ
	// たのしんで くださいね!

CableClub_Text_AskAboutLinking: @ 8279937
	.string "안녕하세요! {PLAYER}님!\p"
	.string "포켓몬센터 2층의 안내를\n"
	.string "맡고 있는 청채라고 합니다\p"
	.string "통신에 대해\n"
	.string "뭔가 궁금하신 점이 있으십니까?$"
	// こんにちは! {PLAYER}さん!ｐ
	// ポケモンセンタ- 2かいのｎ
	// あんないやく アオナですｐ
	// なにか つうしんで おこまりですか?

CableClub_Text_ExplainWirelessClub: @ 82799AA
	.string "포켓몬 무선 클럽의\n"
	.string "이용 방법을 설명합니다!\p"
	.string "이쪽 2층에는\n"
	.string "두 개의 방이 있습니다\p"
	.string "첫 번째는 왼쪽 방\n"
	.string "유니언 룸!\p"
	.string "근처에서\n"
	.string "유니언 룸에 입장한\l"
	.string "전혀 모르는 친구와\l"
	.string "여러 대화를\l"
	.string "나눌 수 있습니다\p"
	.string "두 번째는 오른쪽 방\n"
	.string "다이렉트 코너!\p"
	.string "당신이 알고 있는 친구와\n"
	.string "포켓몬 교환이나\l"
	.string "대전 등 즐거운 일들을\l"
	.string "할 수 있습니다!\p"
	.string "만약 유니언 룸이나\n"
	.string "다이렉트 코너에서\l"
	.string "친구를 찾지 못했을 때는\p"
	.string "조금 더 친구에게\n"
	.string "다가가 주세요\p"
	.string "또 무선어댑터가\n"
	.string "연결되어 있지 않더라도\p"
	.string "오른쪽 방에서\n"
	.string "케이블 통신을 즐길 수 있습니다\p"
	.string "그럼\p"
	.string "무선 통신을\n"
	.string "즐겨 주십시오!$"
	// ポケモン ワイヤレス クラブでのｎ
	// あそびかたを せつめい します!ｐ
	// こちら 2かいにはｎ
	// ふたつの おへやが ございますｐ
	// ひとつめは ひだりがわの おへやｎ
	// ユニオン ル-ム!ｐ
	// あなたの ちかくでｎ
	// ユニオン ル-ムに はいっているｌ
	// みしらぬ おともだちとｌ
	// いろいろな コミュニケ-ションがｌ
	// たのしめます!ｐ
	// ふたつめは みぎがわの おへやｎ
	// ダイレクト コ-ナ-!ｐ
	// あなたの しっている おともだちとｎ
	// ポケモンの こうかんやｌ
	// たいせん などをｌ
	// たのしむ ことが できます!ｐ
	// もし ユニオン ル-ムやｎ
	// ダイレクト コ-ナ-でｌ
	// おともだちが みつからない ときはｐ
	// もうすこし おともだちとｎ
	// ちかづいて みて くださいｐ
	// また ワイヤレスアダプタがｎ
	// つながって いない ばあいでもｐ
	// みぎがわの おへやでｎ
	// ケ-ブル つうしんが たのしめますｐ
	// それではｐ
	// ワイヤレス つうしんをｎ
	// たのしんで くださいね!

CableClub_Text_HopeYouEnjoyWirelessSystem: @ 8279C91
	.string "포켓몬 무선 클럽에서\n"
	.string "즐거운 시간을 보내십시오$"
	// ポケモン ワイヤレス クラブでｎ
	// おたのしみ ください
