Text_PictureBookShelf: @ 82A81E5
	.string "포켓몬 그림책이 모여 있다!$"

Text_BookShelf: @ 82A820D
	.string "다양한 책이 가득 있다!$"

Text_PokemonCenterBookShelf: @ 82A8232
	.string "포켓몬 잡지가 진열되어 있다!\p"
	.string "...“포켓몬의 친구”\n"
	.string "...“포켓몬수첩”\l"
	.string "...“귀여운 포켓몬”$"

Text_Vase: @ 82A8276
	.string "비싸 보이는 항아리가 있다!\n"
	.string "들여다보니...\l"
	.string "안은 텅 비었다!$"

Text_EmptyTrashCan: @ 82A82B3
	.string "안은 텅 비었다!$"

Text_ShopShelf: @ 82A82BF
	.string "가지각색의 포켓몬 상품이\n"
	.string "빽빽하게 진열되어 있다!$"

Text_Blueprint: @ 82A82F7
	.string "무언가의 설계도...?\n"
	.string "봐도 뭐가 뭔지 모르겠다!$"
