gUnknown_0827EA0C:: @ 827EA0C
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}의 {STR_VAR_3}$"

gUnknown_0827EA17:: @ 827EA17
	.string "콘테스트$"

gContestRankNormal::
	.string "노말랭크$"

gContestRankSuper::
	.string "슈퍼랭크$"

gContestRankHyper::
	.string "하이퍼랭크$"

gContestRankMaster::
	.string "마스터랭크$"

gContestLink::
	.string "통신$"

gContestCoolness::
	.string "근사함$"

gContestBeauty::
	.string "아름다움$"

gContestCuteness::
	.string "귀여움$"

gContestSmartness::
	.string "슬기로움$"

gContestToughness::
	.string "강인함$"

gContestPaintingCool1::
	.string "슈퍼 쿨\n"
	.string "논스톱 {STR_VAR_1}$"
	// ス-パ- ク-ルｎ
	// ノンストップ §い

gContestPaintingCool2::
	.string "굿 루킹 포켓몬 {STR_VAR_1}$"
	// グッドルッキン ポケモン §い

gContestPaintingCool3::
	.string "마블러스 원더풀\n"
	.string "그레이트 {STR_VAR_1}$"
	// マ-ベラス ワンダフルｎ
	// グレ-ト §い

gContestPaintingBeauty1::
	.string "금세기 최고의 비너스\n"
	.string "뷰티 {STR_VAR_1}$"
	// こんせいき さいごの ビ-ナスｎ
	// ビュ-ティ- §い

gContestPaintingBeauty2::
	.string "{STR_VAR_1}의 눈부신\n"
	.string "반짝반짝 스마일$"
	// §い クンの マブシイｎ
	// キラキラ スマイル

gContestPaintingBeauty3::
	.string "포켓몬센터의\n"
	.string "슈퍼 아이돌 {STR_VAR_1}$"
	// ポケモンセンタ- のｎ
	// ス-パ- アイドル §い

gContestPaintingCute1::
	.string "러블리 스위트 {STR_VAR_1}$"
	// ラブリ- スウィ-ト §い ちゃん

gContestPaintingCute2::
	.string "프리티 {STR_VAR_1}의\n"
	.string "새침한 숏$"
	// プリティ- §いたんのｎ
	// おすまし ショット

gContestPaintingCute3::
	.string "이쪽 봐줘!\n"
	.string "큐트 포켓몬 {STR_VAR_1}$"
	// こっち むいて!ｎ
	// キュ-ト ポケモン §い ちゃん

gContestPaintingSmart1::
	.string "슬기로운 마에스트로\n"
	.string "와이즈 포켓몬 {STR_VAR_1}$"
	// かしこさ マエストロｎ
	// ワイズ ポケモン §い

gContestPaintingSmart2::
	.string "선택받은 포켓몬...\n"
	.string "포켓몬 중의 포켓몬 {STR_VAR_1}$"
	// えらばれた ポケモン…ｎ
	// ポケモンの なかの ポケモン §い

gContestPaintingSmart3::
	.string "엑설런트 {STR_VAR_1}의\n"
	.string "우아한 순간$"
	// エクセレント §い のｎ
	// ゆうがな ひととき

gContestPaintingTough1::
	.string "파워풀 머슬\n"
	.string "허슬 {STR_VAR_1}$"
	// パワフル マッスルｎ
	// ハッスル §い

gContestPaintingTough2::
	.string "스트롱 스트롱거\n"
	.string "스트롱기스트 {STR_VAR_1}$"
	// ストロング ストロンガ-ｎ
	// ストロンゲスト §い

gContestPaintingTough3::
	.string "터프니스 마이티\n"
	.string "하이퍼 포켓몬 {STR_VAR_1}!$"
	// タフネス マイティ-ｎ
	// ハイパ-ポケモン §い!
