@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.string "많이 어필할 수 있다$"

gText_UserMoreEasilyStartled::
	.string "이 어필 다음에\n"
	.string "깜짝 놀라기 쉬워진다$"

gText_GreatAppealButNoMoreToEnd::
	.string "엄청난 어필이 되지만 이후부터\n"
	.string "마지막까지 아무것도 할 수 없다$"

gText_UsedRepeatedlyWithoutBoringJudge::
	.string "계속해서 써도 심사위원이\n"
	.string "싫증 내지 않게 어필할 수 있다$"

gText_AvoidStartledByOthersOnce::
	.string "다른 포켓몬이 놀래도\n"
	.string "한 번 정도는 참을 수 있다$"

gText_AvoidStartledByOthers::
	.string "다른 포켓몬이 놀래도\n"
	.string "참을 수 있다$"

gText_AvoidStartledByOthersLittle::
	.string "다른 포켓몬이 놀래도\n"
	.string "조금 참을 수 있다$"

gText_UserLessLikelyStartled::
	.string "이 기술을 쓴 이후부터\n"
	.string "그다지 놀라지 않게 된다$"

gText_SlightlyStartleFrontMon::
	.string "자신의 앞에서 어필한\n"
	.string "포켓몬을 조금 놀라게 만든다$"

gText_SlightlyStartleAppealed::
	.string "어필이 끝난\n"
	.string "포켓몬 모두를 조금 놀라게 만든다$"

gText_StartleAppealedBeforeUser::
	.string "자신의 앞에서 어필한\n"
	.string "포켓몬을 놀라게 만든다$"

gText_StartleAllAppealed::
	.string "어필이 끝난\n"
	.string "포켓몬 모두를 놀라게 만든다$"

gText_BadlyStartleFrontMon::
	.string "자신의 앞에서 어필한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_BadlyStartleAppealed::
	.string "어필이 끝난 포켓몬\n"
	.string "모두를 상당히 놀라게 만든다$"

gText_StartleAppealedBeforeUser2::
	.string "자신의 앞에서 어필한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_StartleAllAppealed2::
	.string "어필이 끝난\n"
	.string "포켓몬 모두를 놀라게 만든다$"

gText_ShiftJudgesAttentionFromOthers::
	.string "심사위원의 다른 포켓몬에 대한\n"
	.string "주목을 줄일 수 있다$"

gText_StartleMonHasJudgesAttention::
	.string "심사위원에게 주목받는\n"
	.string "포켓몬을 특히 놀라게 한다$"

gText_JamOthersMissesTurn::
	.string "모두를 방해하고\n"
	.string "다음 어필은 참가하지 않는다$"

gText_StartleMonsMadeSameTypeAppeal::
	.string "같은 타입의 어필을 한\n"
	.string "포켓몬을 특히 놀라게 만든다$"

gText_BadlyStartleCoolAppeals::
	.string "근사한 어필을 한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_BadlyStartleBeautyAppeals::
	.string "아름다운 어필을 한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_BadlyStartleCuteAppeals::
	.string "귀여운 어필을 한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_BadlyStartleSmartAppeals::
	.string "슬기로운 어필을 한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_BadlyStartleToughAppeals::
	.string "강인한 어필을 한\n"
	.string "포켓몬을 상당히 놀라게 만든다$"

gText_MakeMonAfterUserNervous::
	.string "이다음 어필을 하는\n"
	.string "포켓몬 한 마리를 긴장시킨다$"

gText_MakeAllMonsAfterUserNervous::
	.string "이다음 어필을 하는\n"
	.string "포켓몬 모두를 긴장시킨다$"

gText_WorsenConditionOfThoseMadeAppeals::
	.string "어필이 끝난\n"
	.string "포켓몬의 컨디션을 떨어뜨린다$"

gText_BadlyStartleMonsGoodCondition::
	.string "컨디션이 좋은 포켓몬\n"
	.string "모두를 상당히 놀라게 만든다$"

gText_AppealGreatIfPerformedFirst::
	.string "제일 처음으로 어필하면\n"
	.string "어필이 굉장히 잘 된다$"

gText_AppealGreatIfPerformedLast::
	.string "제일 마지막에 어필하면\n"
	.string "어필이 굉장히 잘 된다$"

gText_AppealAsGoodAsThoseBeforeIt::
	.string "그 턴에서 어필한 다른 포켓몬과\n"
	.string "같은 정도의 어필을 보인다$"

gText_AppealAsGoodAsOneBeforeIt::
	.string "하나 앞의 포켓몬 어필과\n"
	.string "같은 정도로 잘 할 수 있다$"

gText_AppealBetterLaterItsPerformed::
	.string "나중에 어필을 할수록\n"
	.string "굉장한 어필을 보여줄 수 있다$"

gText_AppealVariesDependingOnTiming::
	.string "쓸 때마다 어필의 완성도가\n"
	.string "여러 가지로 바뀐다$"

gText_WorksWellIfSameTypeAsBefore::
	.string "하나 앞의 포켓몬 어필과\n"
	.string "타입이 같다면 마음에 들게 된다$"

gText_WorksWellIfDifferentTypeAsBefore::
	.string "하나 앞의 포켓몬 어필과\n"
	.string "타입이 다르다면 마음에 들게 된다$"

gText_AffectedByAppealInFront::
	.string "하나 앞의 포켓몬 어필이\n"
	.string "잘 된 정도에 따라 영향을 받는다$"

gText_UpsConditionHelpsPreventNervousness::
	.string "어필 컨디션이 올라간다\n"
	.string "긴장도 잘 하지 않게 된다$"

gText_AppealWorksWellIfConditionGood::
	.string "컨디션이 좋을 때 쓰면\n"
	.string "어필이 아주 잘 된다$"

gText_NextAppealMadeEarlier::
	.string "이다음의 어필을\n"
	.string "첫 번째로 할 수 있다$"

gText_NextAppealMadeLater::
	.string "이다음의 어필을\n"
	.string "마지막에 쓸 수 있다$"

gText_TurnOrderMoreEasilyScrambled::
	.string "이다음의 어필의\n"
	.string "순서가 바뀌기 쉬워진다$"

gText_ScrambleOrderOfNextAppeals::
	.string "이다음의 어필 순서를\n"
	.string "엉망으로 한다$"

gText_AppealExcitesAudienceInAnyContest::
	.string "어느 콘테스트에서 보여도\n"
	.string "반드시 열광하는 어필$"

gText_BadlyStartlesMonsGoodAppeals::
	.string "어필이 잘 된 포켓몬 모두를\n"
	.string "상당히 놀라게 만든다$"

gText_AppealBestMoreCrowdExcited::
	.string "관객이 열광하고 있을수록\n"
	.string "어필이 마음에 들게 된다$"

gText_TemporarilyStopCrowdExcited::
	.string "이 어필 다음에 관객이\n"
	.string "잠시 열광하지 않게 된다$"

@ Unused move names

gText_RainDance::
	.string "비바라기$"

gText_Rage::
	.string "분노$"

gText_FocusEnergy::
	.string "기충전$"

gText_Hypnosis::
	.string "최면술$"

gText_Softboiled::
	.string "알낳기$"

gText_HornAttack::
	.string "뿔찌르기$"

gText_SwordsDance::
	.string "칼춤$"

gText_Conversion::
	.string "텍스처$"

gText_SunnyDay::
	.string "쾌청$"

gText_Rest2::
	.string "잠자기$"

gText_Vicegrip::
	.string "찝기$"

gText_DefenseCurl::
	.string "웅크리기$"

gText_LockOn::
	.string "록온$"


@ Contest type names

gContestMoveTypeCoolText::
	.string "근사한$"

gContestMoveTypeBeautyText::
	.string "아름다운$"

gContestMoveTypeCuteText::
	.string "귀여운$"

gContestMoveTypeSmartText::
	.string "슬기로운$"

gContestMoveTypeToughText::
	.string "강인한$"

gText_AppealNumWhichMoveWillBePlayed::
	.string "{STR_VAR_1}번째 어필!\n"
	.string "어느 기술을 쓸까?$"

gText_AppealNumButItCantParticipate::
	.string "{STR_VAR_1}번째 어필!\n"
	.string "하지만 참가할 수 없다!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "{STR_VAR_2}{K_EU}로 어필!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} was watching\n"
	.string ""
	.string "the others.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "어필타임 종료!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButAppealWasJammed::
	.string "그러나 방해를 받았다!$"

gText_FollowedAnotherMonsLead::
	.string "다른 포켓몬을 따라했다!$"

gText_ButItMessedUp::
	.string "그러나 실패했다!$"

gText_WentBetterThanUsual::
	.string "평소보다 잘했다!$"

gText_JudgeLookedAwayForSomeReason::
	.string "심사위원이 어쩐지\n"
	.string "시선을 돌렸다!$"

gText_WorkedHardToBuildOnPastMistakes::
	.string "지금까지의 실패를\n"
	.string "토대로 열심히 해보았다!$"

gText_CantMakeAnyMoreMoves::
	.string "더 이상 기술을\n"
	.string "쓸 수 없게 됐다!$"

gText_WorkedFrighteninglyWell::
	.string "무서울 정도로 잘했다!$"

gText_WorkedHardAsStandoutMon::
	.string "주목받고 있는 포켓몬과\n"
	.string "똑같이 열심히 했다!$"

gText_JudgedLookedOnExpectantly::
	.string "심사위원이 기대하는\n"
	.string "눈으로 바라봤다!$"

gText_WorkedRatherWell::
	.string "상당히 잘했다!$"

gText_WorkedLittleBetterThanUsual::
	.string "아주 약간 잘했다!$"

gText_MonFailedToStandOutAtAll::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "전혀 눈에 띄지 않았다...{PAUSE_UNTIL_PRESS}$"

gText_MonDidntStandOutVeryMuch::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "그다지 눈에 띄지 않았다...{PAUSE_UNTIL_PRESS}$"

gText_MonCaughtALittleAttention::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "그런대로 눈에 띄었다{PAUSE_UNTIL_PRESS}$"

gText_MonAttractedALotOfAttention::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "상당히 눈에 띄었다!{PAUSE_UNTIL_PRESS}$"

gText_MonCommandedTotalAttention::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "대단히 눈에 띄었다!{PAUSE_UNTIL_PRESS}$"

gText_MonHasntMadeItsAppeal::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "어필하지 않았다!{PAUSE_UNTIL_PRESS}$"

gText_AnticipationSwelledForMonsAppealNext2::
	.string "{STR_VAR_1}의 어필에\n"
	.string " 기대가 높아졌다!$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.string "심사위원의 {STR_VAR_1}에게의\n"
	.string "인상은 변하지 않는다!$"

gText_MonsXChangedPerceptions::
	.string "{STR_VAR_1}의 {STR_VAR_3}{K_EUNNEUN}\n"
	.string "인상을 바꾸어 놓았다!$"

gText_MonsAppealEffectWoreOff::
	.string "{STR_VAR_1}의\n"
	.string "어필효과가 없어졌다!$"

gText_SpecialAppealsEffectWoreOff::
	.string "스페셜 어필의\n"
	.string "효과가 없어졌다!$"

gText_EveryonesAppealsMadeToLookSame::
	.string "전원의 어필을\n"
	.string "수준이 같아 보이도록 보여줬다!$"

gText_CheapenedMonsAppeal::
	.string "{STR_VAR_2}의 어필을\n"
	.string "좋지 않게 보이게 했다!$"

gText_CheapenedAppealOfThoseAhead::
	.string "앞 포켓몬의 어필을\n"
	.string "좋지 않게 보이게 했다!$"

gText_StoleAttentionAwayFromMon::
	.string "{STR_VAR_2}의\n"
	.string "주목을 빼앗았다!$"

gText_CheapenedMonsAppeal2::
	.string "{STR_VAR_2}의 어필을\n"
	.string "좋지 않게 보이게 했다!$"

gText_SeverelyCheapenedOtherAppeals::
	.string "모두의 어필을\n"
	.string "아주 좋지 않게 보이게 했다!$"

gText_AnticipationSwelledForMonsAppealNext::
	.string "다음 {STR_VAR_1}의 어필에\n"
	.string "기대가 높아졌다!$"

gText_CheapenedAppealOfThoseAhead2::
	.string "앞 포켓몬의 어필을\n"
	.string "좋지 않게 보이게 했다!$"

gText_CheapenedJudgesFavoriteAppeal::
	.string "심사위원의 좋아하는 어필을\n"
	.string "평소보다 좋지 않게 보여줬다!$"

gText_AppealsOfOthersCheapenedByHalf::
	.string "자신 이외의 어필을\n"
	.string "반 정도만 좋아 보이게 보여줬다!$"

gText_StoodOutToMakeUpForBeingJammed::
	.string "지금까지 방해받았던\n"
	.string "울분을 떨쳐내고 주목받았다!$"

gText_CantParticipateInAppealsAnyMore::
	.string "더는 어필에\n"
	.string "참가할 수 없게 됐다!$"

gText_TouchedJudgeForFantasticAppeal::
	.string "심사위원의 마음에 호소하여\n"
	.string "굉장한 어필이 되었다!$"

gText_AnticipationRoseForUpcomingAppeals::
	.string "다음부터의 어필에\n"
	.string "조금 기대가 높아졌다!$"

gText_StoodOutAsMuchAsSpecialAppeals::
	.string "스페셜 어필이 있는\n"
	.string "수만큼 주목받았다!$"

gText_StoodOutAsMuchAsMon::
	.string "{STR_VAR_1}{K_WAGWA})\n"
	.string "같은 정도로 주목받았다!$"

gText_JammedAppealsMadeEvenLessNoticeable::
	.string "방해받은 어필을\n"
	.string "더욱 눈에 띄지 않게 했다!$"

gText_EveryonesAppealsMadeSame::
	.string "전원의 어필과\n"
	.string "수준이 같아 보이도록 보여줬다!$"

gText_BecameMoreConsciousOfOtherMons::
	.string "다른 포켓몬에 대해 평소보다\n"
	.string "걱정이 밀려왔다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1}{K_EUNNEUN} 이후부터\n"
	.string "어필을 할 수 없게 되었다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "아주 조금 마음이 진정되었다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "다른 포켓몬이\n"
	.string "전혀 신경쓰이지 않게 되었다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "다른 포켓몬이\n"
	.string "그다지 신경쓰이지 않게 되었다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "다른 포켓몬을\n"
	.string "그다지 신경쓰지 않게 되었다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "다른 포켓몬을\n"
	.string "놀라게 만들어 보았다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "관객의 눈을\n"
	.string "속이도록 했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "심사위원은 {STR_VAR_1}에게서\n"
	.string "시선을 돌리고 말았다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "다음을 기다리는 포켓몬을\n"
	.string "긴장하도록 했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "긴장해 버렸다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "어필을 아직 하지 않은 포켓몬을\n"
	.string "긴장하도록 했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "컨디션이 좋은 포켓몬을\n"
	.string "약 올렸다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1}의 컨디션이\n"
	.string "돌아와 버렸다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "컨디션이 좋은 포켓몬을\n"
	.string "방해해 보았다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "주목받고 있는 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "더욱 힘을 냈다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "주목받지 못한 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "열심히 했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "앞의 포켓몬들에게\n"
	.string "지지 않을 정도로 힘을 냈다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1}{K_EUNNEUN} 어필을\n"
	.string "잘 보여주지 못했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "앞의 포켓몬과\n"
	.string "같은 정도로 힘을 냈다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1}{K_EUNNEUN} 어필을\n"
	.string "잘 보여주지 못했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1}{K_EUNNEUN} 어필을\n"
	.string "잘 보여주지 못했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "그럭저럭 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "매우 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "굉장히 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "어필을 실패하고 말았다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "그다지 어필을 잘하지 못했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "그럭저럭 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "매우 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "상당히 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "굉장히 어필을 잘했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "앞의 포켓몬과 같은 타입으로\n"
	.string "호감을 샀다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "앞의 포켓몬과 다른 타입으로\n"
	.string "호감을 샀다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "앞의 포켓몬보다\n"
	.string "꽤 주목받았다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "앞의 포켓몬보다\n"
	.string "잘하지 못했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1}의 컨디션이\n"
	.string "평상시보다 좋아졌다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1}{K_EUNNEUN} 컨디션이 좋아서\n"
	.string "더할 수 없이 좋은 어필을 했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "다음 어필을 빨리 하려고\n"
	.string "앞에 나왔다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "다음 어필을 늦게 하려고\n"
	.string "한 걸음 물러섰다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "다음 턴의 순서를\n"
	.string "이상하게 했다!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "심사위원이 기대하며\n"
	.string "{STR_VAR_1}{K_EULREUL} 바라봤다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "어필의 조합이\n"
	.string "마음에 들었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "어필의 조합이\n"
	.string "상당히 마음에 들었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "어필의 조합이\n"
	.string "굉장히 마음에 들었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1}{K_EUNNEUN} 어떻게든\n"
	.string "시선을 돌렸다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "그쪽을 보지 않았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "괜찮았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1}{K_EUNNEUN} 조금\n"
	.string "정신이 팔리고 말았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "다른 포켓몬을\n"
	.string "놀라게 만들어 보았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1}{K_EUNNEUN} 정신이 팔려서\n"
	.string "아래를 내려다봐버렸다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1}{K_EUNNEUN} 정신이 팔려서\n"
	.string "돌아봐버렸다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1}{K_EUNNEUN} 무의식 중에\n"
	.string "소리를 질러버렸다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1}{K_EUNNEUN} 자기도 모르게\n"
	.string "펄쩍 뛰어버렸다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}{K_EUNNEUN} 정신이 팔려서\n"
	.string "뒤집히고 말았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1}{K_EUNNEUN} 긴장해서\n"
	.string "어필을 할 수 없었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "그러나 실패하고 말았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "그러나 긴장\n"
	.string "시킬 수 없었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "그러나 아무도\n"
	.string "긴장하지 않았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "그러나 무시당하고 말았다...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "그러나 컨디션이\n"
	.string "좋아지지 않았다...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "컨디션이 좋지 않아서\n"
	.string "그리 잘하지 못했다...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "괜찮았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1}{K_EUNNEUN} 같은 어필을\n"
	.string "계속했기에 모두를 실망시켰다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}의 {STR_VAR_3}{K_IGA}\n"
	.string "주변에서 엄청 좋았다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}의 {STR_VAR_3}{K_EUNNEUN}\n"
	.string "여기서 먹히지 않는 듯하다...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}의 {STR_VAR_3}에\n"
	.string "주변의 분위기가 달아올랐다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1}{K_EUNNEUN} 다음 어필에\n"
	.string "참가할 수 없게 되었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "관객의\n"
	.string "주의를 끌었다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "관객은 {STR_VAR_3}{K_EULREUL}\n"
	.string "계속 주목하고 있다!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}의 {STR_VAR_2}{K_EUNNEUN}\n"
	.string "눈길을 받지 못했다...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "부끄부끄$"

gText_Contest_Anxiety::
	.string "두근두근$"

gText_Contest_Laziness::
	.string "느릿느릿$"

gText_Contest_Hesitancy::
	.string "꾸물꾸물$"

gText_Contest_Fear::
	.string "흠칫흠칫$"

gText_Contest_Coolness::
	.string "근사함$"

gText_Contest_Beauty::
	.string "아름다움$"

gText_Contest_Cuteness::
	.string "귀여움$"

gText_Contest_Smartness::
	.string "슬기로움$"

gText_Contest_Toughness::
	.string "강인함$"

gText_Tension::
	.string "텐션$"

gText_CoolMove::
	.string "근사한 기술$"

gText_BeautyMove::
	.string "아름다운 기술$"

gText_CuteMove::
	.string "귀여운 기술$"

gText_SmartMove::
	.string "슬기로운 기술$"

gText_ToughMove::
	.string "강인한 기술$"

gText_3QuestionMarks::
	.string "???$"
