EventTicket_Text_ShowOldSeaMap: @ 82A6848
	.string "잿빛도시행 연락선...\p"
	.string "에? 이 지도대로\n"
	.string "가 달라고요?\p"
	.string "저는 잘 모르겠으니\n"
	.string "기다려 주세요$"
	// カイナいき れんらくせん……ｐ
	// え? この ちずの とおりにｎ
	// いってくれって?ｐ
	// わたしでは よく わからないのでｎ
	// おまちください

EventTicket_Text_ThatPass: @ 82A68D2
	.string "잿빛도시행 연락선...\p"
	.string "어머?\n"
	.string "그 티켓은...!$"

EventTicket_Text_ShowEonTicket: @ 82A68FC
	.string "이상한 티켓을\n"
	.string "가지고 온 게 너야?\p"
	.string "네가 가려고 하는 곳은\n"
	.string "남쪽 제일 끝에 있는 조그만 섬...\p"
	.string "그곳은 뭐가 일어날지\n"
	.string "아무도 모르는 곳...\l"
	.string "으음 선원의 피가 들끓는구만!\p"
	.string "자 어서 타!$"

EventTicket_Text_SouthernIslandSailBack: @ 82A69F1
	.string "아무것도 없는 시시한 섬이구만...\n"
	.string "해안시티로 돌아갈래?$"

EventTicket_Text_SailHome: @ 82A6A5D
	.string "그래 그럼 돌아간다$"

EventTicket_Text_AsYouLike: @ 82A6A82
	.string "그러냐\n"
	.string "뭐 마음대로 해$"

SouthernIsland_Interior_Text_Sign: @ 82A6AA1
	.string "모든 꿈은 또 하나의 현실\n"
	.string "그걸 잊지 마...$"

SouthernIsland_Exterior_Text_Sign: @ 82A6AD5
	.string "기억이 흐려지는 자는\n"
	.string "마음에 새기는 것을 희망한다...$"
