EventTicket_Text_OldSeaMapTooFar: @ 82C68A5
    .string "뭐야?\n"
	.string "낡은 지도를 가지고 온 게\l"
	.string "너야? 한번 보여줘 봐!\p"
	.string "...... ...... ......\p"
    .string "이건 또 상당히 멀구만\n"
    .string "미안하지만 다른 곳에 가보는 게...$"
	// なんだ?ｎ
	// ボロっちい ちずを もってきたってのはｌ
	// おまえさんか? みせてみな!ｐ
	// …… …… ……ｐ
	// こりゃ また ずいぶん とおいなあｎ
	// わりいが ほかを あたったほうが……

EventTicket_Text_BrineyHoldOnASecond: @ 82C6951
    .string "하기: 이봐! 내 은인의\n"
    .string "부탁을 거절하다니 무슨 짓인가!$"
	// ハギ『こら! わしの おんじんのｎ
	// ねがいを ことわるとは なにごとだ!

EventTicket_Text_BrineyLetsSail: @ 82C69AA
    .string "{PLAYER} 미안하네\n"
	.string "이 배를 믿고 와주었는데...\l"
    .string "물론 지금 바로 출항하지!\p"
    .string "자 가자!\n"
    .string "해도에 있는 섬으로 출발!$"
	// {PLAYER}{KUN}すまなかったねｎ
	// このふねを たよって きて くれたのに……ｌ
	// もちろん いますぐに しゅっこうだ!ｐ
	// さあいくぞ!ｎ
	// かいずに ある しまへ しゅっぱつ!

EventTicket_Text_OddTicketGetOnBoard: @ 82C6A71
    .string "기묘한 티켓을\n"
	.string "가지고 온 게 너야?\p"
	.string "네가 가려고 하는 곳은\n"
	.string "멀리 떨어진 지방의 섬...\l"
	.string "그곳은 뭐가 기다리고 있을지\l"
	.string "아는 사람이 없어...\l"
	.string "으음 선원의 피가 들끓는구만!\p"
	.string "자 어서 타!$"
	// みょうな チケットをｎ
	// もってきたのは おまえさんか?ｐ
	// おまえが いこうと しているのはｎ
	// とおく はなれた ちほうの しま……ｌ
	// そこには なにが まっているのかｌ
	// しって いるやつは いねえ……ｌ
	// ううむ ふなのりの ちが さわぐぜ!ｐ
	// さあ のりな!

FarawayIsland_Entrance_Text_SailorReturn: @ 82C6B42
    .string "정말 하기 선장의\n"
    .string "변덕에도 기가 막히는군\p"
    .string "이제 해안시티로 돌아가지 않을래?$"
	// まったく ハギ せんちょうのｎ
	// きまぐれにも まいるよなあ……ｐ
	// もう ミナモへ かえるのかい?

BirthIsland_Harbor_Text_SailorReturn: @ 82C6B90
    .string "이상한 모양의 섬이구만\n"
    .string "이제 해안시티로 돌아갈래?$"
	// ふしぎな かたちの しまだなあｎ
	// もう ミナモへ かえるか?

EventTicket_Text_OddTicketsWhereTo: @ 82C6BD4
    .string "이상한 티켓을\n"
	.string "가지고 온 게 너야?\p"
	.string "...... ...... ......흐음\p"
	.string "이것들로 갈 수 있는 곳은\n"
	.string "모두 여기서 멀리 있는 섬\l"
	.string "그곳은 뭐가 일어날지\l"
	.string "뭐가 기다리고 있는지\l"
	.string "아는 사람이 없어...\l"
	.string "으음 선원의 피가 들끓는구만!\p"
	.string "자 어서 타!$"
    .string "우선 어디부터 가 볼래?$"
	// ヘンテコな チケットをｎ
	// いくつも もってきたのは おまえさんか?ｐ
	// …… …… ……ふむｐ
	// こいつらで いける ところはｎ
	// どこも ここから とおい しまｌ
	// そこでは なにが おきるのかｌ
	// なにが まっているのかｌ
	// しっている やつは いねえ……ｌ
	// ううむ ふなのりの ちが さわぐぜ!ｐ
	// さあ のりな!ｎ
	// まずは どこから いってみるかい?

NavelRock_Harbor_Text_SailorReturn: @ 82C6CE6
    .string "뭐... 뭔가 안쪽 깊은 곳으로부터\n"
    .string "낮은 울음소리를 들은 거 같은...\p"
    .string "괘 괜찮지?\n"
    .string "이제 돌아가는 편이 좋지 않을까?$"
	// な…… なんか おくふかくからｎ
	// ひくい うなりが きこえたような……ｐ
	// だ だいじょうぶか?ｎ
	// もう かえった ほうが いいんじゃないか?

FarawayIsland_Entrance_Text_Sign: @ 82C6D5A
    .string "몇 년도 전에 적힌 듯한\n"
    .string "오래된 글이 있다...\p"
    .string "...월 6일\n"
    .string "여기에 들어서는 인...이\l"
    .string "다시 ...난다면\l"
	.string "마음이 상냥한 ...이기를\p"
	.string "...기에 그 소원을 새겨\n"
    .string "이 ...을 뒤로한다\p"
	.string "...무$"
	// なんねんも まえに かかれたようなｎ
	// ふるい かきおきが ある……ｐ
	// ……がつ 6かｎ
	// ここに たちいる にんげ……がｌ
	// ふたたび ……らわれると すればｌ
	// こころ やさし……で あらんことをｐ
	// ……こに その ねがいを しるしｎ
	// この ……を あとにするｐ
	// ……ジ

FarawayIsland_Interior_Text_Mew: @ 82C6DFF
    .string "뮤...$"
	// ミュ-……
