@ Battle Tower
gText_AnabelWonSilver:: @ 82C843F
	.string "유감이야...$"
	// ざんねん だよ……

gText_AnabelDefeatSilver:: @ 82C8458
	.string "과연...$"
	// なるほどね……

gText_AnabelWonGold:: @ 82C846C
	.string "미안해...$"
	// ごめんね……

gText_AnabelDefeatGold:: @ 82C8480
	.string "고마워...$"
	// ありがとう……

@ Battle Dome
gText_TuckerWonSilver:: @ 82C848B
	.string "아하하!! 부끄럽지 않아!?\n"
	.string "모두가 보고 있다고!!$"
	// アッハッハッ!! はずかしく ないのっ!?ｎ
	// みんなが みてるよっ!!

gText_TuckerDefeatSilver:: @ 82C84C1
	.string "큭... 무슨 일이...$"
	// クッ…… なんて こと……

gText_TuckerWonGold:: @ 82C84D0
	.string "돔슈퍼스타의\n"
	.string "이름은 장식이 아니다!!$"
	// ド-ムス-パ-スタ-のｎ
	// なまえは かざりじゃ ないっ!!

gText_TuckerDefeatGold:: @ 82C84F7
	.string "아하하!! 멋져!!$"
	// アッハッハッ!! ステキっ!!

@ Battle Factory
gText_NolandWonSilver:: @ 82C8512
	.string "수고했어!\n"
	.string "좋은 수업이 됐지?$"
	// おつかれさん!ｎ
	// イイ べんきょうに なったろ?

gText_NolandDefeatSilver:: @ 82C853B
	.string "좋네-!\n"
	.string "너 알고 있구나-!$"
	// イイねぇ-!ｎ
	// おめえ わかってる ねぇ-!

gText_NolandWonGold:: @ 82C8561
	.string "어이어이어이--!\n"
	.string "벌써 끝이야-?$"
	// おいおいおい--!!ｎ
	// もう おしまいか-?

gText_NolandDefeatGold:: @ 82C8589
	.string "무슨 일이...$"
	// なんだとぉ……

@ Battle Pike
gText_LucyWonSilver:: @ 82C859D
	.string "흥...$"
	// フン……

gText_LucyDefeatSilver:: @ 82C85A4
	.string "큭...$"
	// くっ……

gText_LucyWonGold:: @ 82C85A9
	.string "핫!!$"
	// ハッ!!

gText_LucyDefeatGold:: @ 82C85AE
	.string "젠자아아아앙---!!$"
	// ちくしょおぉぉぉっ---!!

@ Battle Arena
gText_GretaWonSilver:: @ 82C85B4
	.string "잠깐 잠깐-!\n"
	.string "더 힘내도록 해-!!$"
	// ちょっと ちょっとぉ-!ｎ
	// もっと がんばってよね-!!

gText_GretaDefeatSilver:: @ 82C85E3
	.string "거짓말! 꽤 하잖아-!!$"
	// うっそ! やるじゃん-!!

gText_GretaWonGold:: @ 82C85F5
	.string "네-엡!\n"
	.string "당연한 결과지!!$"
	// ウィ-ッス! とうぜん!!

gText_GretaDefeatGold:: @ 82C8611
	.string "엇!? 진짜로!?$"
	// い-っ!? マジっ!?

@ Battle Palace
gText_SpenserWonSilver:: @ 82C8628
	.string "포켓몬이 연약한 것은\n"
	.string "트레이너가 연약하기 때문이지!!$"
	// ポケモンが なんじゃく なのはｎ
	// トレ-ナ-が なんじゃく だからだ!!

gText_SpenserDefeatSilver:: @ 82C8662
	.string "허허...\n"
	.string "이거야 원...$"
	// ほほぅ……ｎ
	// これは これは……

gText_SpenserWonGold:: @ 82C8682
	.string "크핫핫핫!!\n"
	.string "내 형제 앞에 적은 없다!!$"
	// ぐわはっはっは!!ｎ
	// わが きょうだいの まえに てき なし!!

gText_SpenserDefeatGold:: @ 82C86B3
	.string "크하---핫핫핫!$"
	// ぐわ---はっはっは!!

@ Battle Pyramid
gText_BrandonWonSilver:: @ 82C86C3
	.string "어이! 뭐하고 있는 거야!\n"
	.string "좀 더 힘내 봐! 일어서는 거다!!$"
	// おい! なにを やってるんだ!ｎ
	// ほら がんばれ! たちあがるんだ!!

gText_BrandonDefeatSilver:: @ 82C86FE
	.string "좋아! 힘냈구나!\n"
	.string "잘 버텼구나!!$"
	// よおしっ! がんばった!ｎ
	// よく がんばったぞ!!

gText_BrandonWonGold:: @ 82C8739
	.string "어이! 포기하지 마라!\n"
	.string "자아 일어서는 거다! 힘내는 거다!!$"
	// おい! あきらめるんじゃ ない!ｎ
	// さあ たつんだ! がんばるんだ!!

gText_BrandonDefeatGold:: @ 82C877B
	.string "좋아! 잘했구나!\n"
	.string "힘냈구나! 열심히 했구나!!$"
	// よおしっ! よく やったぞ!ｎ
	// がんばった! がんばった じゃないか!!
