LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "이곳은 ID 추첨센터\n"
	.string "추첨 코너입니다\p"
	.string "본 백화점에 방문하신\n"
	.string "모든 분께 ID 추첨센터\l"
	.string "추첨을 하고 있습니다!\p"
	.string "추첨한 번호와 손님의\n"
	.string "포켓몬 ID를 뒤에서부터 비교하여\l"
	.string "일치한 자릿수에 따라 멋진 상품을\l"
	.string "선물로 드립니다!\p"
	.string "ID 추첨센터\n"
	.string "추첨에 도전하겠습니까?$"
	@ こちらは ポケモンくじｎ
	@ ちゅうせん コ-ナ-ですｐ
	@ とうデパ-トに おこし いただいた かたにｎ
	@ もれなく ポケモンくじをｌ
	@ ひいて いただいて います!ｐ
	@ ひいた くじの ナンバ-とｎ
	@ おきゃくさまの ポケモンの IDがｌ
	@ あっていましたら すてきな しょうひんをｌ
	@ プレゼント いたします!ｐ
	@ ポケモンくじを ひかれますか?

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "내일 다시 생각이\n"
	.string "나신다면 와 주십시오$"
	@ また あした いこうｎ
	@ おこし ください

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "그럼 다음에 또 이용해 주세요$"
	@ それでは また おこし ください

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "그럼 추첨을 하겠습니다\n"
	.string "...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}...{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	@ では くじを ひいて くださいｎ
	@ …©くそ©くそ©くそ©くそ…©くそ©くそ©くそ©くそ…©くそ©くそ©くそ©くそ

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "추첨 번호는 {STR_VAR_1}입니다!\p"
	.string "번호가 당신의 포켓몬 ID와\n"
	.string "일치하는지 알아볼 테니\l"
	.string "잠시 기다려 주십시오$"
	@ くじの ナンバ-は §いです!ｐ
	@ ナンバ-が あなたの ポケモンの IDとｎ
	@ いっちしているか おしらべ いたしますのでｌ
	@ しょうしょう おまちください

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "축하합니다!\p"
	.string "당신이 데리고 있는\n"
	.string "{STR_VAR_1}의 ID가\l"
	.string "추첨 번호와 일치합니다!$"
	@ おめでとう ございます!ｐ
	@ あなたが つれているｎ
	@ §いちゃんの IDが みごとにｌ
	@ くじの ナンバ-と いっち しました!

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "축하합니다!\p"
	.string "PC에 맡긴\n"
	.string "{STR_VAR_1}의 ID가\l"
	.string "추첨 번호와 일치합니다!$"
	@ おめでとう ございます!ｐ
	@ パソコンに あずけているｎ
	@ §いちゃんの IDが みごとにｌ
	@ くじの ナンバ-と いっち しました!

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "아쉽네요\n"
	.string "모두 꽝인 모양입니다$"
	@ ざんねんでしたｎ
	@ すべて はずれの ようです

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "2자리 일치하니\n"
	.string "3등입니다!\l"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!!$"
	@ 2ケタ あって いましたのでｎ
	@ 3とう です!ｌ
	@ §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "3자리 일치하니\n"
	.string "2등입니다!\l"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!!$"
	@ 3ケタ あって いましたのでｎ
	@ 2とう です!ｌ
	@ §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "4자리 일치하니\n"
	.string "1등입니다!\l"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!!$"
	@ 4ケタ あって いましたのでｎ
	@ 1とう です!ｌ
	@ §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "무려! 5자리 모두\n"
	.string "일치합니다!!\p"
	.string "특등입니다!!\n"
	.string "{STR_VAR_1}{K_EULREUL} 드리겠습니다!!$"
	@ なんと 5ケタ すべてｎ
	@ あって いました!!ｐ
	@ とくとうです!!ｎ
	@ §いを さしあげます!!

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "...어라?\n"
	.string "도구가 가득한 모양이네요\p"
	.string "도구를 정리하고 나서 다시 한 번\n"
	.string "와 주십시오$"
	@ ………あら?ｎ
	@ どうぐが いっぱいの ようですねｐ
	@ どうぐを せいりしてから もういちどｎ
	@ おこし ください

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}님이시군요\n"
	.string "보관하고 있었습니다!\p"
	.string "그럼 상품을\n"
	.string "드리도록 하겠습니다$"
	@ §あさん ですねｎ
	@ おまちして おりました!ｐ
	@ では しょうひんをｎ
	@ おわたし いたします

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "그럼 다음에 또 이용해 주세요$"
	@ それでは また おこし ください
