MatchCall_WildBattleText1:: @ 82A971C
	.string "아! {PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지난번에 {STR_VAR_2}{K_EULREUL} 발견했는데\n"
	.string "잡지 못했어\p"
	.string "너무 아까운 거 있지-\n"
	.string "그럼 또 봐!$"
	// あ! §あ§お こんにちは!ｎ
	// §い ですｐ
	// このまえ §うを みつけたんだけどｎ
	// つかまえられなかったよｐ
	// おしかったな-ｎ
	// じゃあ またね!

MatchCall_WildBattleText2:: @ 82A9798
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지난번에 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\p"
	.string "도망쳐버렸어\n"
	.string "안타깝네\p"
	.string "그럼 또 봐!$"
	// こんにちは §あ§お!ｎ
	// §い ですｐ
	// このまえ §う をｎ
	// つかまえようと したんだけどｐ
	// にげられちゃったのｎ
	// ざんねん だったなあｐ
	// じゃあ またね!

MatchCall_WildBattleText3:: @ 82A9813
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "지난번에 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\l"
	.string "거의 다 된 상태에서 도망쳐버렸어!\p"
	.string "엄청 분했지...\n"
	.string "그럼 나중에 또 보자-$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// このまえ §う をｎ
	// つかまえようと したんだけどｌ
	// あとすこしの ところで にげられたんだ!ｐ
	// くやしかった なあ®®®ｎ
	// じゃあ またな-

MatchCall_WildBattleText4:: @ 82A98A8
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}{K_I}라는 포켓몬 알아?\n"
	.string "지난번에 조금만 더 했으면\p"
	.string "잡을 것 같았는데\n"
	.string "도망쳐버렸어\p"
	.string "다음번에 발견하면 반드시\n"
	.string "잡을 거야\p"
	.string "그럼 나중에 또 보자$"
	// やあ §あ§おｎ
	// §い だｐ
	// §うって ポケモン しってるかい?ｎ
	// このまえ あとすこしでｐ
	// つかまえられそう だったんだけどｎ
	// にげられて しまったよｐ
	// こんど みつけたら ぜったいｎ
	// つかまえて みせるよｐ
	// じゃあ またな

MatchCall_WildBattleText5:: @ 82A9977
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬 잡고 있어?\p"
	.string "나도 지난번에 조금만 더 하면\n"
	.string "잡을 것 같았는데\p"
	.string "도망쳐버렸지 뭐야\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あ§おｎ
	// §い だけどｌ
	// ポケモン つかまえてる?ｐ
	// おれも このまえ もうすこしでｎ
	// つかまえられそう だったけどｐ
	// にげられちゃったよｎ
	// じゃあ またな

MatchCall_WildBattleText6:: @ 82A99FD
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬 잡고 있어?\p"
	.string "난 지난번에 조금만 더 하면\n"
	.string "잡을 것 같았는데\p"
	.string "도망쳐버렸어\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あ§おｎ
	// §い だけどｌ
	// ポケモン つかまえてる?ｐ
	// おれも このまえ もうすこしでｎ
	// つかまえられそう だったけどｐ
	// にげられちゃったよｎ
	// じゃあ またな

MatchCall_WildBattleText7:: @ 82A9A78
	.string "...아 {PLAYER}?\n"
	.string "{STR_VAR_1}인데...\p"
	.string "아 잠깐 기다려!\n"
	.string "지금 {STR_VAR_2}{K_EULREUL} 잡으려고...\p"
	.string "아아아아 도망쳐버렸어-!\n"
	.string "거의 다 됐었는데!$"
	// ®®®あ §あ§お?ｎ
	// §い だけど®®®ｐ
	// あ ちょっと まって!ｎ
	// いま §うを つかまえ®®®ｐ
	// ああああ にげられた-!ｎ
	// もうすこし だったのに!

MatchCall_WildBattleText8:: @ 82A9AE8
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "그때 이후로 포켓몬 잡았어?\n"
	.string "난 지난번에 조금만 더 하면\p"
	.string "잡을 것 같았는데\n"
	.string "도망쳐버렸지 뭐야\p"
	.string "좀 더 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// あれから ポケモン つかまえた?ｎ
	// わたし このまえ もうすこしでｐ
	// つかまえられそう だったのにｎ
	// にげられちゃったｐ
	// もっと がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_WildBattleText9:: @ 82A9BA7
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "어때? 포켓몬 모으고 있어?\n"
	.string "나는 자꾸 도망쳐서\p"
	.string "전혀 못 잡고 있어\n"
	.string "그럼 또 봐!$"
	// あ §あ§お こんにちは-!ｎ
	// §い です!ｐ
	// どう? ポケモン あつまってる?ｎ
	// わたしは にげられて ばっかりでｐ
	// ぜんぜん うまく いかないのｎ
	// じゃあ またね!

MatchCall_WildBattleText10:: @ 82A9C36
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "조금만 더 하면 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡을 뻔했는데\l"
	.string "도망쳐버렸어\p"
	.string "좀 더 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちはｎ
	// §い よｐ
	// もうすこしで §う をｎ
	// つかまえられそう だったのにｌ
	// にげられちゃったｐ
	// もっと がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_WildBattleText11:: @ 82A9CC8
	.string "아아 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "잘 지내니?\p"
	.string "난 저번에 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\p"
	.string "도망쳐버렸어\n"
	.string "후우$"
	// ああ §あ§おｎ
	// §いだけどｌ
	// ちょうしは どうだい?ｐ
	// おれは このまえ §う をｎ
	// つかまえようと したんだけどｐ
	// にげられちゃったよｎ
	// がっくり

MatchCall_WildBattleText12:: @ 82A9D44
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬은 잡고 있나?\p"
	.string "나도 잡으려고 하는데\n"
	.string "좀처럼 잘 안 되네\p"
	.string "포켓몬의 길은\n"
	.string "심오하구먼$"
	// やあ §あ§おｎ
	// §い じゃがｌ
	// ポケモン つかまえとるかな?ｐ
	// わしも つかまえようと おもったがｎ
	// なかなか うまくいかんｐ
	// ポケモンの みちはｎ
	// おくが ふかいのう
	
MatchCall_WildBattleText13:: @ 82A9DD7
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬은 잡고 있나?\p"
	.string "나도 잡으려고 하는데\n"
	.string "좀처럼 잘 안 되네\p"
	.string "포켓몬의 길은\n"
	.string "심오하구먼$"
	// やあ §あ§おｎ
	// §い じゃがｌ
	// ポケモン つかまえとるかな?ｐ
	// わしも つかまえようと おもったがｎ
	// なかなか うまくいかんｐ
	// ポケモンの みちはｎ
	// おくが ふかいのう

MatchCall_WildBattleText14:: @ 82A9E70
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "아까 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\p"
	.string "도망쳐버렸어 아깝지!\n"
	.string "그럼 또 봐$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// さっき §うちゃんをｎ
	// つかまえようと したんだけどｐ
	// にげられちゃったのよ ざんねん!ｎ
	// じゃあ またね

MatchCall_WildBattleText15:: @ 82A9EFD
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "포켓몬을 잡으려고\n"
	.string "하는 중인데\l"
	.string "하나도 안 나와서 말이지-\l"
	.string "아저씨는 고생하는 중이란다\p"
	.string "곤란하네 정말-\n"
	.string "그럼 나중에 또 보자-$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// ポケモンを つかまえようとｎ
	// おもってるんだがｌ
	// みつからなくてさ-ｌ
	// おじさん こまってる とこなのよｐ
	// まいったな-ｎ
	// じゃあ またな-

MatchCall_NegativeBattleText1:: @ 82A9FAB
	.string "{PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "다른 사람이랑 승부를 했는데\n"
	.string "져버렸어 후우\p"
	.string "그럼 또 봐$"
	// §あ§お こんにちは!ｎ
	// §い です!ｐ
	// ほかのひとと しょうぶ したんだけどｎ
	// まけちゃったよ がっくしｐ
	// じゃあ またね

MatchCall_NegativeBattleText2:: @ 82AA028
	.string "{PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "나 있지\n"
	.string "그때 이후로 승부해 봤어\p"
	.string "하지만 아깝게\n"
	.string "저버렸지 아-아$"
	// §あ§お こんにちは!ｎ
	// §いよ!ｐ
	// わたし ねｎ
	// あれから また しょうぶ してみたのｐ
	// でも あとちょっとの ところでｎ
	// まけちゃった あ-あ

MatchCall_NegativeBattleText3:: @ 82AA099
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "승부에서 졌어-\n"
	.string "좀 더 키워야 하는 걸까-$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// しょうぶ に まけたよ-ｎ
	// もっと そだてないと だめだな-

MatchCall_NegativeBattleText4:: @ 82AA100
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "어제 또 승부해 봤는데\n"
	.string "역시 이기지 못했어\p"
	.string "좀 더 키울 필요가 있는 걸까\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あｎ
	// §い だｐ
	// きのう また しょうぶ してみたんだｎ
	// でも かてなかったよｐ
	// もっと そだてが ひつようだなｎ
	// じゃあ またな

MatchCall_NegativeBattleText5:: @ 82AA188
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내?\n"
	.string "난 승부를 해도\l"
	.string "잘 이기지 못하고 있어\p"
	.string "상태가 나쁜 것 같아\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あｎ
	// §い だよｐ
	// ちょうしは どうだい?ｎ
	// おれは しょうぶ してもｌ
	// あまり かてないんだよｐ
	// ちょうし わるいなあｎ
	// じゃあ またな

MatchCall_NegativeBattleText6:: @ 82AA214
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내니?\n"
	.string "난 승부를 해도\l"
	.string "잘 이기지 못하고 있어\p"
	.string "상태가 나쁜가봐\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あｎ
	// §い だよｐ
	// ちょうしは どうだい?ｎ
	// おれは しょうぶ してもｌ
	// あまり かてないんだよｐ
	// ちょうし わるいなあｎ
	// じゃあ またな

MatchCall_NegativeBattleText7:: @ 82AA2A1
	.string "{STR_VAR_1}인데-\n"
	.string "요즘 어때?\p"
	.string "난 어제 승부에서 져서\n"
	.string "그것 때문에 머리가 꽉 찼어\p"
	.string "대책을 생각해야 하는데...\n"
	.string "그럼 또 보자$"
	// §い だけど-ｎ
	// さいきん どう?ｐ
	// きのう しょうぶに まけてさｎ
	// そのことで あたまが いっぱいなんだｐ
	// たいさく かんがえないと®®®ｎ
	// じゃあ また

MatchCall_NegativeBattleText8:: @ 82AA31B
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "나는 지난번에 승부에서\l"
	.string "져버렸어\p"
	.string "좀 더 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// ポケモンの ちょうしは どう?ｎ
	// わたしは このまえの しょうぶでｌ
	// まけちゃったｐ
	// もっと がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_NegativeBattleText9:: @ 82AA3A8
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야-\p"
	.string "있지- 들어봐 들어봐!\n"
	.string "저번에 포켓몬 승부를 했는데\p"
	.string "거의 다 됐는데 아깝게\n"
	.string "져버렸어-! 분해!$"
	// あ §あ§お こんにちは-!ｎ
	// §い で-すｐ
	// ね- きいて きいて!ｎ
	// このまえ ポケモン しょうぶ したんだけどｐ
	// あとちょっとの ところでｎ
	// まけちゃったのよ-! くやしい!

MatchCall_NegativeBattleText10:: @ 82AA442
	.string "어머 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "방금 승부를 했는데\n"
	.string "져버렸지 뭐야\p"
	.string "좀 더 포켓몬을 키워야겠어\n"
	.string "그럼 또 봐$"
	// あら §あ§おｎ
	// §い ですｐ
	// さっき しょうぶ したんだけどｎ
	// まけちゃったｐ
	// もっと ポケモン そだてないと だめねｎ
	// じゃあ またね

MatchCall_NegativeBattleText11:: @ 82AA4C5
	.string "여어 {PLAYER} 잘 지내?\n"
	.string "{STR_VAR_1}{K_I}야\l"
	.string "포켓몬의 상태는 어때?\p"
	.string "이쪽은 또 승부에서\n"
	.string "져버렸어\p"
	.string "그럼 또 보자$"
	// やあ §あ§お げんきかい?ｎ
	// §い だよｌ
	// ポケモンの ちょうしは どう?ｐ
	// こっちは また しょうぶにｎ
	// まけちゃったよｐ
	// じゃあ また

MatchCall_NegativeBattleText12:: @ 82AA520
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "승부는 하고 있느냐?\p"
	.string "나는 지난번에 져버려서\n"
	.string "또 포켓몬을\l"
	.string "키우고 있다네\p"
	.string "그럼 나중에 보세$"
	// やあやあ §あ§おｎ
	// §い じゃがｌ
	// しょうぶ しておるのかな?ｐ
	// わしのほうは このまえ まけてしまってｎ
	// また ポケモンをｌ
	// そだてておる ところじゃよｐ
	// では またな

MatchCall_NegativeBattleText13:: @ 82AA5AD
	.string "오오 {PLAYER}\n"
	.string "{STR_VAR_1}일세\p"
	.string "잘 지내는가?\n"
	.string "방금 전까지 포켓몬 승부를\l"
	.string "하고 있었다네\p"
	.string "{PLAYER}도 힘내게나\n"
	.string "그럼 또 보세$"
	// おお §あ§おｎ
	// §い じゃｐ
	// げんき かのう?ｎ
	// さっきまで ポケモン しょうぶをｌ
	// しておったよｐ
	// §あ§おも がんばるんじゃぞｎ
	// では またの

MatchCall_NegativeBattleText14:: @ 82AA64D
	.string "어머 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내니?\n"
	.string "가끔은 집에 돌아가보도록 해\l"
	.string "그럼 또 봐$"
	// あら §あ§おｎ
	// §い よｐ
	// ちょうしは どうなの?ｎ
	// たまには いえに かえらないと だめよｌ
	// じゃあ またね

MatchCall_PositiveBattleText1:: @ 82AA6AF
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "아까 승부를 했었는데\n"
	.string "이겼어! 이겼다고!\p"
	.string "내 {STR_VAR_2}{K_IGA}\n"
	.string "엄청 열심히 해줬어! 기쁘다-$"
	// こんにちは §あ§お!ｎ
	// §い です!ｐ
	// さっき しょうぶ したんだけどｎ
	// かったよ! かったよ!ｐ
	// ぼくの §う がｎ
	// すごく がんばったんだ! うれしいな-

MatchCall_PositiveBattleText2:: @ 82AA730
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "어제 승부를 했는데\n"
	.string "이겼어! 기뻐-!$"
	// こんにちは §あ§お!ｎ
	// §い です!ｐ
	// きのう しょうぶ したんだけどｎ
	// かったのよ! うれしい-!

MatchCall_PositiveBattleText3:: @ 82AA77A
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}라고\p"
	.string "상태는 어때?\n"
	.string "난 지난번에 승부를 했는데\l"
	.string "내 {STR_VAR_2}{K_IGA} 엄청 활약했어!\p"
	.string "다음에 {PLAYER}{K_WAGWA} 승부할 때는\n"
	.string "절대로 지지 않을 거야-!$"
	// お-っす §あ!ｎ
	// §い だぞｐ
	// ちょうしは どうだ?ｎ
	// おれも このまえ しょうぶ したんだけどｌ
	// おれの §うが だいかつやく さ!ｐ
	// つぎ §あと しょうぶ するときはｎ
	// ぜったい まけない からな-!

MatchCall_PositiveBattleText4:: @ 82AA81C
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "아까 승부했는데\n"
	.string "어떻게든 이길 수 있었어\p"
	.string "내 {STR_VAR_2}{K_IGA}\n"
	.string "엄청 열심히 해줬지$"
	// やあ §あｎ
	// §い だｐ
	// さっき しょうぶ したんだけどｎ
	// なんとか かつ ことが できたよｐ
	// ぼくの §うがｎ
	// すごく がんばったんだ

MatchCall_PositiveBattleText5:: @ 82AA88C
	.string "여어 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "상태는 어때?\n"
	.string "승부는 하고 있어?\p"
	.string "난 지난번에 이겼어!\n"
	.string "{STR_VAR_2}{K_IGA} 엄청 활약했거든!\p"
	.string "다음엔 너한테 이길 거야!\n"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §い だｐ
	// ちょうしは どうだい?ｎ
	// しょうぶ してる?ｐ
	// おれ このまえ かったよ!ｎ
	// §うが だいかつやく さ!ｐ
	// つぎこそ きみに かつからね!ｎ
	// じゃあ またね

MatchCall_PositiveBattleText6:: @ 82AA934
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내지?\n"
	.string "난 최근 상태가 좋아서\l"
	.string "아까도 승부에서 이겼어\p"
	.string "다음에 너하고 승부할 때는\n"
	.string "절대로 지지 않을 거야$"
	// やあ §あ§おｎ
	// §い だｐ
	// げんき かい?ｎ
	// おれは さいきん ちょうしが よくてｌ
	// さっきも しょうぶに かったところだｐ
	// つぎに きみと しょうぶ するときはｎ
	// ぜったいに まけないからな

MatchCall_PositiveBattleText7:: @ 82AA9D3
	.string "{PLAYER}?\n"
	.string "{STR_VAR_1}인데\p"
	.string "내 {STR_VAR_2} 강한가봐!\n"
	.string "아까도 승부에서 이겼거든!\p"
	.string "다음에 너하고 승부할 때가\n"
	.string "기대된다$"
	// §あ§お?ｎ
	// §い だけどｐ
	// ぼくの §う つよいわけよ!ｎ
	// さっきも しょうぶで かったわけよ!ｐ
	// つぎに きみと しょうぶ するのがｎ
	// たのしみだなあ

MatchCall_PositiveBattleText8:: @ 82AAA40
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내니?\n"
	.string "난 방금 승부에서 이겼어\p"
	.string "{STR_VAR_2}{K_IGA} 엄청 열심히 했지\n"
	.string "그럼 또 봐$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// げんき かしら?ｎ
	// わたしね さっき しょうぶ して かったのｐ
	// §う が とっても がんばったのよｎ
	// じゃあ またね

MatchCall_PositiveBattleText9:: @ 82AAAE4
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "내 쪽은 방금 승부해서\l"
	.string "막 이긴 참이야!\p"
	.string "내 {STR_VAR_2}{K_IGA}\n"
	.string "굉장한 활약을 했었지\p"
	.string "보여주고 싶었는데-\n"
	.string "그럼 또 봐!$"
	// こんにちは §あ§お!ｎ
	// §い で-す!ｐ
	// ポケモンの ちょうしは どう?ｎ
	// わたしのほうは さっき しょうぶしてｌ
	// かった ところよ!ｐ
	// わたしの §う がｎ
	// すごい かつやく だったのよｐ
	// みせたかったな-ｎ
	// じゃあ またね!

MatchCall_PositiveBattleText10:: @ 82AAB8C
	.string "어머 안녕 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "상태는 어때?\n"
	.string "내 포켓몬은 상태가 좋은 것 같아\p"
	.string "아까도 승부에서 이겼거든\n"
	.string "그럼 또 봐$"
	// あら こんにちは §あ§おｎ
	// §い よｐ
	// ちょうしは どうかしら?ｎ
	// わたしの ポケモン ちょうし いいみたいｐ
	// さっきも しょうぶで かてたのよｎ
	// じゃあ またね

MatchCall_PositiveBattleText11:: @ 82AAC25
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "포켓몬 승부는 하고 있니?\n"
	.string "아저씨는 오늘도 승부에서 이겼단다-\p"
	.string "상태가 너무 좋아 으하하하\n"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §い だよｐ
	// ポケモン しょうぶ してるかい?ｎ
	// おじさん きょうも しょうぶに かってね-ｐ
	// ちょうし いいんだよ がはははｎ
	// じゃあ またね

MatchCall_PositiveBattleText12:: @ 82AAC9D
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\p"
	.string "잘 지내고 있나?\n"
	.string "난 잘 지내고 있다네\p"
	.string "방금도 승부에서 이겼거든\n"
	.string "젊은 것들에게 아직 질 수는 없지!$"
	// やあ §あ§おｎ
	// §い じゃよｐ
	// げんきに してるかのう?ｎ
	// わしは げんき じゃぞｐ
	// さっきも しょうぶに かった ところじゃｎ
	// わかいもんには まだまだ まけんぞ

MatchCall_PositiveBattleText13:: @ 82AAD41
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\p"
	.string "잘 지내고 있나?\n"
	.string "난 잘 지내고 있다네\p"
	.string "방금도 승부에서 이겼거든\n"
	.string "젊은 것들에게 아직 질 수는 없지\p"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃよｐ
	// げんきに してるかのう?ｎ
	// わしは げんき じゃぞｐ
	// さっきも しょうぶに かった ところじゃｎ
	// わかいもんには まだまだ まけんぞｐ
	// じゃあ またのう

MatchCall_PositiveBattleText14:: @ 82AAE00
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "저번에 승부를 했는데\n"
	.string "내 {STR_VAR_2}{K_IGA} 대활약했어!\p"
	.string "{PLAYER}에게도 보여주고 싶었는데\n"
	.string "그럼 또 보자$"
	// §あ§お こんにちはｎ
	// §い よｐ
	// このまえ しょうぶ したんだけどｎ
	// わたしの §うが だいかつやく!ｐ
	// §あ§おにも みせたかったなｎ
	// じゃあ また

MatchCall_SameRouteBattleRequestText1:: @ 82AAE7F
	.string "{PLAYER}씨 안녕!\n"
	.string "{STR_VAR_1}{K_I}라구\p"
	.string "에! 지금 {STR_VAR_2}에 있는 거야?\n"
	.string "그럼 지금부터 승부하자!\l"
	.string "기다릴게! 그럼 안녕!$"
	// §あさん こんにちは!ｎ
	// §い だよｐ
	// え! いま §う に いるの?ｎ
	// じゃあ いまから しょうぶ しようよ!ｌ
	// まってるよ! じゃあね!

MatchCall_SameRouteBattleRequestText2:: @ 82AAEF1
	.string "{PLAYER}씨 안녕!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "에! 지금 {STR_VAR_2}에 있는 거야?\n"
	.string "그럼 지금부터 승부하지 않을래?\l"
	.string "기다릴게! 그럼 안녕!$"
	// §あさん こんにちは!ｎ
	// §い で-すｐ
	// え! いま §う に いるの?ｎ
	// じゃあ いまから しょうぶ しない?ｌ
	// まってるわよ! じゃあね!

MatchCall_SameRouteBattleRequestText3:: @ 82AAF69
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "오 지금 {STR_VAR_2}에 있다고?\n"
	.string "그럼 지금부터 승부하지 않을래?\p"
	.string "이번에야말로 지지 않을 거야!\n"
	.string "기다릴게- 그럼 안녕$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// お いま §うにいるのか?ｎ
	// じゃあ これから しょうぶ しないか?ｐ
	// こんどこそ まけない からな!ｎ
	// まってるぞ- じゃあな

MatchCall_SameRouteBattleRequestText4:: @ 82AB010
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지금 어디 있어?\n"
	.string "뭐? {STR_VAR_2}?\p"
	.string "그럼 지금부터 승부하지 않을래?\n"
	.string "기다릴게 그럼 안녕$"
	// やあ §あ§おｎ
	// §い だｐ
	// いま どこに いるんだい?ｎ
	// え §う?ｐ
	// じゃあ これから しょうぶ しないか?ｎ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText5:: @ 82AB076
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라구\p"
	.string "상태는 어때?\n"
	.string "뭐? 지금 {STR_VAR_2}에 있다고?\p"
	.string "그렇다면 지금부터 나하고\n"
	.string "승부해보지 않을래?\p"
	.string "기다릴게 그럼 안녕$"
	// やあ §あ§おｎ
	// §い だよｐ
	// ちょうしは どうだい?ｎ
	// え? いま §うに いるの?ｐ
	// それなら これから おれとｎ
	// しょうぶ してみないかい?ｐ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText6:: @ 82AB11A
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "헤에 지금 {STR_VAR_2}에 있구나\p"
	.string "그럼 지금부터 나하고\n"
	.string "승부하자\p"
	.string "기다릴게 그럼 안녕$"
	// やあ §あ§おｎ
	// §い だｐ
	// ポケモンの ちょうしは どうだい?ｎ
	// へえ いま §うに いるのかｐ
	// じゃあ これから おれとｎ
	// しょうぶ しようｐ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText7:: @ 82AB1B4
	.string "...아 {PLAYER}?\n"
	.string "{STR_VAR_1}인데...\p"
	.string "헤에- 지금 {STR_VAR_2}에 있다고?\n"
	.string "그럼 승부하자 지금부터\p"
	.string "내 포켓몬을 보여줄게\n"
	.string "그럼 기다리고 있는다$"
	// ®®®あ §あ§お?ｎ
	// §い だけど®®®ｐ
	// へ- いま §うに いるの?ｎ
	// じゃあ しょうぶ しよう これからｐ
	// おれの ポケモンを みせてあげるよｎ
	// じゃあ まってるよ

MatchCall_SameRouteBattleRequestText8:: @ 82AB23D
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내고 있니?\n"
	.string "어머 지금 {STR_VAR_2}에 있는 거구나\p"
	.string "그럼 지금부터\n"
	.string "나하고 승부하지 않을래?\p"
	.string "기다릴게 그럼 안녕!$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// あら いま §うに いるのねｐ
	// じゃあ これからｎ
	// わたしと しょうぶ しない?ｐ
	// まってるわよ じゃあね!

MatchCall_SameRouteBattleRequestText9:: @ 82AB2E9
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "잘 지내고 있어?\n"
	.string "어머 지금 {STR_VAR_2}에 있다고?\p"
	.string "그렇구나- 그럼 지금부터\n"
	.string "나하고 승부해보지 않을래?\p"
	.string "그럼 안녕 기다릴게$"
	// あ §あ§お こんにちは-!ｎ
	// §い です!ｐ
	// げんきに してる?ｎ
	// あら いま §うに いるの?ｐ
	// そっか- じゃあ これからｎ
	// わたしと しょうぶ してみない?ｐ
	// じゃあね まってるわよ

MatchCall_SameRouteBattleRequestText10:: @ 82AB382
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내고 있어?\n"
	.string "어머 지금 {STR_VAR_2}에 있다고\p"
	.string "그럼 지금부터\n"
	.string "나랑 승부하지 않을래?\p"
	.string "기다릴게 그럼 안녕!$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// あら いま §うに いるのねｐ
	// じゃあ これからｎ
	// わたしと しょうぶ しない?ｐ
	// まってるわよ じゃあね!

MatchCall_SameRouteBattleRequestText11:: @ 82AB410
	.string "아아 {PLAYER}\n"
	.string "{STR_VAR_1}인데\p"
	.string "호오\n"
	.string "지금 {STR_VAR_2}에 있다고?\p"
	.string "그럼 지금부터 아저씨하고\n"
	.string "포켓몬 승부하지 않을래?\p"
	.string "기다릴게 그럼 안녕$"
	// ああ §あ§おｎ
	// §いだけどｐ
	// ほほうｎ
	// いま §うに いるんだって?ｐ
	// じゃあ これから おじさんとｎ
	// ポケモン しょうぶ しないかい?ｐ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText12:: @ 82AB4B0
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\l"
	.string "지금 어디에 있는가?\p"
	.string "{STR_VAR_2}{K_I}라고! 가까이에 있구먼\n"
	.string "지금부터 나하고 승부하지 않겠나?\p"
	.string "기다리고 있겠네 그럼 이만$"
	// やあ §あ§おｎ
	// §い じゃがｌ
	// いま どこに いるのかな?ｐ
	// §う か! すぐ ちかく じゃなｎ
	// これから わしと しょうぶ せんか?ｐ
	// まっておるぞ じゃあの

MatchCall_SameRouteBattleRequestText13:: @ 82AB538
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내나?\p"
	.string "호오호오 지금 {STR_VAR_2}에 있는 겐가\n"
	.string "멀지도 않으니 이쪽에 와서\p"
	.string "한번 승부하지 않겠나?\n"
	.string "기다리고 있겠네 그럼 이만$"
	// やあ §あ§おｎ
	// §い じゃが げんきかのう?ｐ
	// ほうほう いまは §うに おるのかｎ
	// ちかいから こっちへ よってｐ
	// いちど しょうぶ して いかんかの?ｎ
	// まっておるぞ じゃあの

MatchCall_SameRouteBattleRequestText14:: @ 82AB5E4
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "어머 지금 {STR_VAR_2}에 있는 거야?\n"
	.string "엄청 가까이에 있네\p"
	.string "그럼 지금부터 아주머니랑\n"
	.string "포켓몬 승부해보지 않을래?\p"
	.string "기다리고 있을게 그럼 안녕$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// あら いま §うに いるの?ｎ
	// すぐちかくに いるのねｐ
	// じゃあ これから おばさんとｎ
	// ポケモンしょうぶ してみない?ｐ
	// まってるわよ じゃあね

MatchCall_DifferentRouteBattleRequestText1:: @ 82AB670
	.string "아! {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지금부터 나하고 승부할래?\n"
	.string "{STR_VAR_2}에서 기다리고 있을게!$"
	// あ! §あ§お!ｎ
	// §い ですｐ
	// これから ぼくと しょうぶ しない?ｎ
	// §う で まってるよ!

MatchCall_DifferentRouteBattleRequestText2:: @ 82AB6CD
	.string "아! {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지금부터 나하고 승부해보지 않을래?\n"
	.string "{STR_VAR_2}에서 기다릴게!$"
	// あ! §あ§お!ｎ
	// §い ですｐ
	// これから わたしと しょうぶ してみない?ｎ
	// §う で まってるよ!

MatchCall_DifferentRouteBattleRequestText3:: @ 82AB73C
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "그때 이후로 내 포켓몬도\n"
	.string "믿음직해졌어!\p"
	.string "{PLAYER}의 포켓몬으로\n"
	.string "실력을 시험해보고 싶으니까\p"
	.string "승부해보지 않을래?\n"
	.string "{STR_VAR_2}에서 기다릴게$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// あれから おれの ポケモンもｎ
	// たくましく なったぞ!ｐ
	// §あの ポケモンでｎ
	// うでだめし したいからｐ
	// しょうぶ してみないか?ｎ
	// §う で まってるぞ

MatchCall_DifferentRouteBattleRequestText4:: @ 82AB808
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "How are things with you?\p"
	.string "My POKéMON have grown pretty\n"
	.string "tough lately.\p"
	.string "Hey, how would you like to have\n"
	.string "another battle with me?\p"
	.string "Let's meet up around\n"
	.string "{STR_VAR_2}, okay?$"
	// やあ §あ§おｎ
	// §い だｐ
	// ちょうしは どうだい?ｎ
	// おれの ポケモンもｌ
	// ずいぶん つよく なったよｐ
	// そうだ また おれとｎ
	// しょうぶ しないかい?ｐ
	// じゃあ §うで あおう

MatchCall_DifferentRouteBattleRequestText5:: @ 82AB8B7
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "My POKéMON are growing up in\n"
	.string "decent ways.\p"
	.string "I'd really like to have another\n"
	.string "battle with you.\p"
	.string "I'll keep an eye out for you around\n"
	.string "{STR_VAR_2}. See you soon!$"
	// やあ §あ§おｎ
	// §い だけどｐ
	// おれの ポケモンｎ
	// けっこう いいかんじに そだってきたよｐ
	// きみと もういちどｎ
	// しょうぶ してみたいなあｐ
	// §う で まってるよｎ
	// じゃあね

MatchCall_DifferentRouteBattleRequestText6:: @ 82AB95D
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\l"
	.string "I hope you're on top of things.\p"
	.string "I was thinking I'd like another\n"
	.string "battle with you. What do you say?\p"
	.string "If you feel like a battle,\n"
	.string "come to {STR_VAR_2}.\p"
	.string "See you!$"

MatchCall_DifferentRouteBattleRequestText7:: @ 82ABA03
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\l"
	.string "So? Are your POKéMON growing?\p"
	.string "Mine sure got stronger.\n"
	.string "I'd like to show you.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me for a match.\p"
	.string "See you around.$"

MatchCall_DifferentRouteBattleRequestText8:: @ 82ABA9F
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\p"
	.string "I hope you're doing well.\n"
	.string "My POKéMON are very frisky.\p"
	.string "If you're ever in the area, please\n"
	.string "give me a rematch.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Until then, good-bye!$"

MatchCall_DifferentRouteBattleRequestText9:: @ 82ABB62
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "How are your POKéMON doing?\p"
	.string "My POKéMON keep getting better.\n"
	.string "I'd like to show you, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now,\n"
	.string "so let's battle if you're close by.\p"
	.string "Hope I see you soon!$"

MatchCall_DifferentRouteBattleRequestText10:: @ 82ABC26
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\l"
	.string "So, how are things with you?\p"
	.string "My POKéMON have grown much\n"
	.string "stronger than before.\p"
	.string "I'd love another battle with you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "I'll be around {STR_VAR_2}.\n"
	.string "Come see me if you're close.$"

MatchCall_DifferentRouteBattleRequestText11:: @ 82ABCE9
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Where might you be now?\p"
	.string "My POKéMON are full of life.\n"
	.string "They appear to be looking forward\l"
	.string "to seeing your POKéMON, {PLAYER}{KUN}.\p"
	.string "I'm around {STR_VAR_2} now.\n"
	.string "I hope you'll seek us out.$"

MatchCall_DifferentRouteBattleRequestText12:: @ 82ABDA2
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I should tell you, my POKéMON have\n"
	.string "grown to be quite robust lately.\p"
	.string "I would like to see them in a battle\n"
	.string "with you, {PLAYER}{KUN}.\p"
	.string "We'll be around {STR_VAR_2}.\n"
	.string "Come see us anytime!$"

MatchCall_DifferentRouteBattleRequestText13:: @ 82ABE5E
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "Are your POKéMON keeping well?\p"
	.string "My POKéMON have been so healthy,\n"
	.string "they don't look capable of losing!\p"
	.string "I would surely love to have another\n"
	.string "battle with you.\p"
	.string "If you're near {STR_VAR_2},\n"
	.string "do come see us.$"

MatchCall_DifferentRouteBattleRequestText14:: @ 82ABF36
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "Keeping well, I hope.\p"
	.string "Oh, yes! My POKéMON are\n"
	.string "much stronger than before.\p"
	.string "Don't you think we ought to have\n"
	.string "a battle, {PLAYER}{KUN}?\p"
	.string "We'll be waiting for you around\n"
	.string "{STR_VAR_2}.\p"
	.string "Come see us anytime, okay?$"

MatchCall_PersonalizedText1:: @ 82AC009
	.string "It's me, the mountain-loving\n"
	.string "{STR_VAR_1}!\p"
	.string "Well, since we met, have you grown\n"
	.string "to appreciate the mountains more?\p"
	.string "I rarely see you in the mountains…\p"
	.string "Next time, we'll meet somewhere\n"
	.string "around {STR_VAR_2}.$"

MatchCall_PersonalizedText2:: @ 82AC0BD
	.string "This is {STR_VAR_1}.\n"
	.string "Hello.\p"
	.string "I was just telling a new TRAINER\n"
	.string "about you.\p"
	.string "I told her about a strong TRAINER\n"
	.string "who raises POKéMON with care.\p"
	.string "I hope you'll become a TRAINER\n"
	.string "that everyone will admire.\p"
	.string "I hope we meet again!$"

MatchCall_PersonalizedText3:: @ 82AC18C
	.string "Hello! It's {STR_VAR_1}.\p"
	.string "I love where I am now.\n"
	.string "It's pleasant with sweet aromas!\p"
	.string "I think someone planted BERRIES,\n"
	.string "and they burst into bloom.\p"
	.string "See you again sometime!$"

MatchCall_PersonalizedText4:: @ 82AC228
	.string "Hello! Thirty years of exploration,\n"
	.string "{STR_VAR_1} at your service!\p"
	.string "It seems that you're energetically\n"
	.string "traveling here and there.\p"
	.string "Have you discovered any new ruins?\n"
	.string "Please tell if you have!\p"
	.string "Now, if you'll excuse me,\n"
	.string "I have ruins to explore.$"

MatchCall_PersonalizedText5:: @ 82AC30C
	.string "It's {STR_VAR_1}!\p"
	.string "Know what I'm doing today?\n"
	.string "Looking at waves from the beach!\p"
	.string "Sigh… The waves are all sparkly.\n"
	.string "The sea is the prettiest from here.\l"
	.string "I'm getting hungry, so bye-bye!$"

MatchCall_PersonalizedText6:: @ 82AC3B6
	.string "Munch-chew…\n"
	.string "Oh, hi, it's {STR_VAR_1}.\l"
	.string "I love eating on the beach.\p"
	.string "My POKéMON and I have been doing\n"
	.string "great. We're fully fueled!\l"
	.string "I'm going for a swim. Bye!$"

MatchCall_PersonalizedText7:: @ 82AC446
	.string "Hello, this is {STR_VAR_1}…\p"
	.string "I've grown a little jaded with this\n"
	.string "whole COOLTRAINER thing…\p"
	.string "Everyone thinks I'm a perfect\n"
	.string "TRAINER, and that makes me try to\l"
	.string "live up to that expectation.\p"
	.string "But I guess that goes with being\n"
	.string "a COOLTRAINER.\p"
	.string "I'll just have to buckle down…\n"
	.string "and grin and bear it.\p"
	.string "You're the only person that I could\n"
	.string "confide in like this.\p"
	.string "But when I see you next,\n"
	.string "don't worry, I won't whine!$"

MatchCall_PersonalizedText8:: @ 82AC5C7
	.string "Yahoo, it's {STR_VAR_1}!\n"
	.string "How do you do?\p"
	.string "I've been raising my POKéMON with\n"
	.string "you as the target.\p"
	.string "I don't intend to lose when we\n"
	.string "battle again.\p"
	.string "Isn't it great to have TRAINER\n"
	.string "friends? Let's meet again!$"

MatchCall_PersonalizedText9:: @ 82AC682
	.string "It's {STR_VAR_1}…\n"
	.string "Right now, behind you…\l"
	.string "Wasn't there something…?\p"
	.string "The power of the POKéMON that\n"
	.string "sleep here at MT. PYRE…\p"
	.string "It's telling me about you…\p"
	.string "You should walk away quickly and\n"
	.string "never once look back…\p"
	.string "Giggle…\n"
	.string "Farewell…$"

MatchCall_PersonalizedText10:: @ 82AC755
	.string "This is {STR_VAR_1}.\n"
	.string "How do you do?\p"
	.string "Isn't it convenient that we can\n"
	.string "chat like this at a distance?\p"
	.string "Before, if I wanted to speak with\n"
	.string "anyone, I had to have my father\l"
	.string "drive me…\p"
	.string "I should be going now.\n"
	.string "I'm glad we had this chat.$"

MatchCall_PersonalizedText11:: @ 82AC82C
	.string "It's {STR_VAR_1}!\n"
	.string "Will you listen to this?\p"
	.string "I like the SAFARI ZONE a lot,\n"
	.string "but whenever I go, I get lost!\p"
	.string "All that tall grass!\n"
	.string "And it's much too spread out!\p"
	.string "I feel better getting that off\n"
	.string "my chest!\p"
	.string "I'm off to the SAFARI ZONE again!\n"
	.string "Catch you!$"

MatchCall_PersonalizedText12:: @ 82AC914
	.string "Hello, {STR_VAR_1} here.\n"
	.string "Yes, correct, I am rich, yes.\p"
	.string "I should tell you, my wealth has\n"
	.string "grown since we last met.\p"
	.string "What's more, my POKéMON have also\n"
	.string "grown stronger.\p"
	.string "I can't shake the feeling that\n"
	.string "this world exists for me!\p"
	.string "Oh, no need to say a word!\n"
	.string "Everyone knows it's true!\p"
	.string "Oh, you must excuse me, I have this\n"
	.string "formal dinner to attend.$"

MatchCall_PersonalizedText13:: @ 82ACA59
	.string "Ufufufufu…\n"
	.string "It's me, {STR_VAR_1}…\p"
	.string "Can you guess what I'm seeing?\n"
	.string "A pair of {STR_VAR_2} in a battle.\p"
	.string "Maybe I'll try catching the winner…\n"
	.string "Ufufufufufu…\p"
	.string "I… I'm kind of busy now.\n"
	.string "I have to go.$"

MatchCall_PersonalizedText14:: @ 82ACB02
	.string "Oh, it's {STR_VAR_1}!\p"
	.string "I was just thinking I'm getting\n"
	.string "bored of the ABANDONED SHIP.\p"
	.string "But since I'm already here,\n"
	.string "and I want to beat you once,\l"
	.string "I'll be sticking around a bit more.\p"
	.string "If you feel compelled, why don't\n"
	.string "you come see me?\p"
	.string "I think today will be the day that\n"
	.string "I finally challenge the man next\l"
	.string "door to a match.\p"
	.string "Be seeing you!$"

MatchCall_PersonalizedText15:: @ 82ACC3F
	.string "I'm {STR_VAR_1}!\n"
	.string "The man of the sea!\p"
	.string "You know what I think?\p"
	.string "The TRAINERS out at sea are\n"
	.string "the toughest of the tough!\p"
	.string "You should learn from me and train\n"
	.string "in the sea…\p"
	.string "Whoops, giant surf rising!\p"
	.string "It's a great training opportunity!\n"
	.string "Sorry, but I have to go!$"

MatchCall_PersonalizedText16:: @ 82ACD2F
	.string "It's {STR_VAR_1}! Listen, I've been\n"
	.string "teaching karate to my POKéMON.\p"
	.string "But now they're better than me!\n"
	.string "I've done nothing but lose to them!\p"
	.string "But even though I may lose to\n"
	.string "POKéMON, I won't lose to another\l"
	.string "TRAINER, no sir!\p"
	.string "We have to battle again!\n"
	.string "Ugwaah!$"

MatchCall_PersonalizedText17:: @ 82ACE1E
	.string "It's me, {STR_VAR_1}.\n"
	.string "How're your travels unwinding?\p"
	.string "…Whoa, is that right?\n"
	.string "Sounds awfully stimulating!\p"
	.string "I think I could write a song about\n"
	.string "one of your episodes.\p"
	.string "…Oh, hey, I'm feeling it.\n"
	.string "I hear the riffs in my head.\p"
	.string "I'd better get this tune properly\n"
	.string "written, so I've got to fly! Later!$"

MatchCall_PersonalizedText18:: @ 82ACF32
	.string "This is {STR_VAR_1}…\n"
	.string "Hear my new song.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Why are you that {STR_VAR_2}?\l"
	.string "Why can't I be you, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} and {STR_VAR_1},\l"
	.string "{STR_VAR_1} and {STR_VAR_2}…\p"
	.string "Repeat chorus, fade…$"

MatchCall_PersonalizedText19:: @ 82ACFBE
	.string "I'm {STR_VAR_1}, you know,\n"
	.string "the camping expert!\p"
	.string "When we battled, I couldn't help\n"
	.string "but lose to you.\p"
	.string "After all, my expertise is in\n"
	.string "camping.\p"
	.string "But win or lose, I like to battle\n"
	.string "when I'm camping.\p"
	.string "Battle with us again, okay?\n"
	.string "Oh, and let's go camping, too!$"

MatchCall_PersonalizedText20:: @ 82AD0AC
	.string "It's me, me, {STR_VAR_1}!\p"
	.string "I'd like to climb other mountains\n"
	.string "than this one, to be honest.\p"
	.string "But I'm not sure if there'd be any\n"
	.string "ladies like on MT. CHIMNEY.\p"
	.string "If you know any other mountain\n"
	.string "with ladies around, let me know!\p"
	.string "Ehehehe, see you around!$"

MatchCall_PersonalizedText21:: @ 82AD194
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "It's {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "That's all today…$"

MatchCall_PersonalizedText22:: @ 82AD1DF
	.string "This is {STR_VAR_1}. Today, I had\n"
	.string "this feeling I would chat with you.\p"
	.string "My desire to defeat you builds\n"
	.string "by day and by night.\p"
	.string "You have a rival like that, yes?\n"
	.string "I wish it were me…\p"
	.string "I'm glad you heard me out.\n"
	.string "See you!$"

MatchCall_PersonalizedText23:: @ 82AD2A8
	.string "It's {STR_VAR_1}.\p"
	.string "When there's a strong TRAINER\n"
	.string "nearby, I can sometimes sense that\l"
	.string "somehow.\p"
	.string "Did you pass close by, {PLAYER}{KUN}?\n"
	.string "Maybe it was you.\p"
	.string "I'll be waiting for your visit.\n"
	.string "Bye!$"

MatchCall_PersonalizedText24:: @ 82AD34F
	.string "Hello, this is {STR_VAR_1}.\n"
	.string "You sound well, {PLAYER}{KUN}.\p"
	.string "I've traveled around the world,\n"
	.string "but I must say I've taken a great\l"
	.string "shine to this region.\p"
	.string "I plan to stay here a while.\n"
	.string "Perhaps we can meet again?\p"
	.string "I've not forgotten your dazzling\n"
	.string "techniques.\p"
	.string "I do hope for a rematch.$"

MatchCall_PersonalizedText25:: @ 82AD44E
	.string "Snivel… It's… {STR_VAR_1}…\n"
	.string "…Sob…\p"
	.string "ROXANNE chewed me out in class\n"
	.string "today.\p"
	.string "But I don't dislike her or anything.\p"
	.string "ROXANNE tells me exactly what\n"
	.string "I did wrong so I can learn from it.\p"
	.string "You bet I'll be going to\n"
	.string "the TRAINER'S SCHOOL tomorrow!\p"
	.string "See you later!$"

MatchCall_PersonalizedText26:: @ 82AD53A
	.string "It's {STR_VAR_1}!\p"
	.string "ROXANNE let me battle with her\n"
	.string "yesterday.\p"
	.string "The results…\n"
	.string "Terrible, like you needed to ask.\p"
	.string "But I was delighted that ROXANNE\n"
	.string "would even let me challenge her!\p"
	.string "You wouldn't believe how much\n"
	.string "more I admire her!\p"
	.string "I'm going to really focus and work!\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText27:: @ 82AD642
	.string "Hi, it's ANNA! I'm with my junior\n"
	.string "partner MEG again today.\p"
	.string "I really love caring for MEG and\n"
	.string "POKéMON. They're so cute!\p"
	.string "I wish I could look after them\n"
	.string "as if they were my siblings!\p"
	.string "Oh, hi, MEG!\n"
	.string "Did you get the buns?\p"
	.string "Huh? No, no, I'm not treating you\n"
	.string "like my personal slave!\p"
	.string "You lost the match, so you have\n"
	.string "to go buy the bread as punishment!\p"
	.string "I wouldn't treat you like a slave,\n"
	.string "MEG! You're too special to me!\p"
	.string "I have to go now.\n"
	.string "It's time for our snack!$"

MatchCall_PersonalizedText28:: @ 82AD801
	.string "I love POKéMON!\n"
	.string "It's {STR_VAR_1} from the FAN CLUB!\p"
	.string "You have to hear this!\n"
	.string "My sweet POKéMON…\p"
	.string "Snort! Wahaha!\n"
	.string "I can't say any more! It's a secret!\l"
	.string "It's just too cute for words!\p"
	.string "Oh, my sweet {STR_VAR_2} is begging\n"
	.string "for a {POKEBLOCK}!\p"
	.string "It's the picture of cuteness!\p"
	.string "Sorry, but I can't talk now!\n"
	.string "You'll have to hear this next time!$"

MatchCall_PersonalizedText29:: @ 82AD92E
	.string "Ohoho!\p"
	.string "This is {STR_VAR_1}! I can't wait to\n"
	.string "tell you about my darling POKéMON!\p"
	.string "Please, you must listen to this.\n"
	.string "It's about my darling {STR_VAR_2}.\p"
	.string "Whenever anyone picks it up,\n"
	.string "it leaps straight into my arms!\p"
	.string "Oh… Oh… Could there be anything\n"
	.string "more blissful?\p"
	.string "Oh, it feels so heavenly!\p"
	.string "I'm so glad I could share some of\n"
	.string "my happiness with you.\p"
	.string "Well, I must be going.\n"
	.string "Bye, now!$"

MatchCall_PersonalizedText30:: @ 82ADA8F
	.string "I am… {STR_VAR_1}.\n"
	.string "People call me an EXPERT.\p"
	.string "But there is one thing I know.\n"
	.string "I could not be an EXPERT on my own\l"
	.string "power.\p"
	.string "Only with the help of POKéMON can\n"
	.string "a TRAINER become an EXPERT.\p"
	.string "Humph! I believe I may have said\n"
	.string "something deep and profound!\p"
	.string "I shall leave you in good spirits!$"

MatchCall_PersonalizedText31:: @ 82ADB9B
	.string "It's {STR_VAR_1}.\n"
	.string "I'm glad to chat with you!\p"
	.string "I am feeling alive and refreshed\n"
	.string "soaking in this hot-spring tub.\p"
	.string "I've been battling young TRAINERS\n"
	.string "since we met, but you're still\l"
	.string "the best of the lot.\p"
	.string "I imagine you'll become an EXPERT\n"
	.string "in your old age! Ohohoho…$"

MatchCall_PersonalizedText32:: @ 82ADC92
	.string "Yay! This is {STR_VAR_1}!\n"
	.string "What's up?\p"
	.string "I might be imagining this, but when\n"
	.string "I win battles, my shorts seem to\l"
	.string "feel, like, better. Materially.\p"
	.string "What do I mean by that?\n"
	.string "It's kind of hard to explain, but…\l"
	.string "How would I say this now…\l"
	.string "My shorts feel silkier!\p"
	.string "And when I battled you, {PLAYER}{KUN},\n"
	.string "my shorts felt icky and coarse.\p"
	.string "… … … … … …\n"
	.string "You didn't really believe that?\l"
	.string "Ehehehe, that's all! Bye now!$"

MatchCall_PersonalizedText33:: @ 82ADE08
	.string "Ahoy!\n"
	.string "{STR_VAR_1} here!\p"
	.string "As always, I'm fishing with wild\n"
	.string "abandon!\p"
	.string "Are there other places I can fish\n"
	.string "than the sea and rivers?\p"
	.string "I get these powerful urges to\n"
	.string "fish just about anywhere!\p"
	.string "Oh, gosh, darn it!\n"
	.string "My line's tangled up!\p"
	.string "Gotta go!\n"
	.string "Find me some new fishing spots!$"

MatchCall_PersonalizedText34:: @ 82ADF07
	.string "Hey, there! It's {STR_VAR_1}.\n"
	.string "Are you taking it casually?\p"
	.string "Ever since I was a kid, you know,\n"
	.string "I've always been placid, huh?\p"
	.string "I never was much for getting all\n"
	.string "stressed or rushing things.\p"
	.string "But wouldn't you know it,\n"
	.string "I'm now a TRIATHLETE.\p"
	.string "You just can't tell where life will\n"
	.string "take you, if you get my drift.\p"
	.string "You're a TRAINER now, but who\n"
	.string "knows what the future holds, huh?\p"
	.string "Imagine yourself as a teacher,\n"
	.string "or maybe an artist. Cool, huh?\p"
	.string "But, hey, be cool. Take it casual.\n"
	.string "See you around.$"

MatchCall_PersonalizedText35:: @ 82AE0D9
	.string "This is {STR_VAR_1}!\n"
	.string "I'm cycling right now.\p"
	.string "I love swimming and running,\n"
	.string "but cycling is my first love!\p"
	.string "It makes my whole body feel as if\n"
	.string "I'm one with the wind.\p"
	.string "It exhilarates me as if I were\n"
	.string "flying!\p"
	.string "Okay! Today, I'm going to set a new\n"
	.string "CYCLING ROAD record!\p"
	.string "You should make the challenge, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText36:: @ 82AE1FD
	.string "Yo, this is {STR_VAR_1}! I'm smack\n"
	.string "in the middle of a triathlon!\p"
	.string "But, hey, I've always got time to\n"
	.string "shoot the breeze!\p"
	.string "Working out with POKéMON feels\n"
	.string "mighty good!\p"
	.string "Without exchanging words, we synch\n"
	.string "as if we shared a heart.\p"
	.string "It's inspiring!\p"
	.string "Gasp… Chatting while running…\n"
	.string "I'm getting run down…\l"
	.string "Gasp… Have…to…go…$"

MatchCall_PersonalizedText37:: @ 82AE327
	.string "Hi, it's {STR_VAR_1}.\n"
	.string "If you want to improve endurance,\l"
	.string "high-altitude training is it!\p"
	.string "Try running on a mountaintop.\n"
	.string "You'll be gasping in no time!\p"
	.string "I'm getting oxygen starved, too!\n"
	.string "See you!$"

MatchCall_PersonalizedText38:: @ 82AE3DA
	.string "Oh, it's {STR_VAR_1}, hello.\p"
	.string "I've been swimming a lot but I still\n"
	.string "can't seem to reach EVERGRANDE.\p"
	.string "Maybe I'm just going in circles.\p"
	.string "No, no, that can't be possible.\n"
	.string "Wahahaha.\l"
	.string "Take care!$"

MatchCall_PersonalizedText39:: @ 82AE489
	.string "Hey, it's {STR_VAR_1}…\n"
	.string "Whoops!\p"
	.string "Splash!\p"
	.string "Blug-blug-blug-blug…\p"
	.string "Sploosh!\p"
	.string "Whiff-whiff! Whiff-whiff!\p"
	.string "Hey! Sorry about that!\n"
	.string "I just put on some suntan oil.\p"
	.string "So my POKéNAV went whoopsy\n"
	.string "out of my hand into the water!\p"
	.string "But, boy, DEVON's POKéNAV is built\n"
	.string "tough. It survived that dunking!\p"
	.string "Anyways, I'm busy sunbathing,\n"
	.string "so let's chat another time.$"

MatchCall_PersonalizedText40:: @ 82AE5CD
	.string "Hello, this is {STR_VAR_1}.\p"
	.string "Out of the three triathlon events,\n"
	.string "I like swimming best.\p"
	.string "But if I stay in the sea too long,\n"
	.string "won't I get all prune-like?\p"
	.string "Ooh, triathlon is such a grueling\n"
	.string "test of human endurance! Bye!$"

MatchCall_PersonalizedText41:: @ 82AE698
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "How are your POKéMON doing?\p"
	.string "My DRAGON POKéMON appear to be\n"
	.string "in peak form. Bye for now.$"

MatchCall_PersonalizedText42:: @ 82AE704
	.string "{STR_VAR_1} here.\p"
	.string "My {STR_VAR_2} has grown even more\n"
	.string "tough than that last time.\p"
	.string "I'm not going to lose again to you.\n"
	.string "You wait till next time!\p"
	.string "See you around!$"

MatchCall_PersonalizedText43:: @ 82AE78F
	.string "It is {STR_VAR_1} here.\p"
	.string "I have continued with my studies\n"
	.string "in the art of concealment.\p"
	.string "But I have been too successful.\n"
	.string "No one has been able to find me.\l"
	.string "My success makes me lonely…\p"
	.string "Like smoke I disappear!\n"
	.string "Farewell!$"

MatchCall_PersonalizedText44:: @ 82AE859
	.string "This is {STR_VAR_1}.\n"
	.string "I kept up my training since we met.\p"
	.string "My {STR_VAR_2} is getting pretty\n"
	.string "tough.\p"
	.string "Training on a beach is effective,\n"
	.string "just as I thought. Bye now!$"

MatchCall_PersonalizedText45:: @ 82AE8E6
	.string "How do you do?\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I wonder when this yucky volcanic\n"
	.string "ash will stop falling?\p"
	.string "If it gets too deep, it will cover\n"
	.string "up the pattern on my parasol…\p"
	.string "Let's promise to meet again!$"

MatchCall_PersonalizedText46:: @ 82AE998
	.string "Hi, {STR_VAR_1} here.\p"
	.string "Did you know that it's easier to\n"
	.string "float in the sea than a pool?\p"
	.string "Just by lying still, your body will\n"
	.string "float on its own.\p"
	.string "But if you float for too long,\n"
	.string "watch that you don't get carried\l"
	.string "off too far out.\p"
	.string "…Where am I, anyway?\n"
	.string "I'd better go!$"

MatchCall_PersonalizedText47:: @ 82AEA8F
	.string "Oh, {PLAYER}{KUN}, hello!\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I'm up in the mountains now.\p"
	.string "But the ground is too bumpy.\n"
	.string "I can't pitch my tent here…\p"
	.string "Oh, I had a brilliant idea!\p"
	.string "Maybe I can get my POKéMON to tamp\n"
	.string "the ground flat here!\p"
	.string "I'm going to try that!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48:: @ 82AEB77
	.string "Oh, hi, hi, this is {STR_VAR_1}!\p"
	.string "I'm raising POKéMON with LIV!\n"
	.string "We're trying very hard!\p"
	.string "If we try harder, can we become\n"
	.string "number one? Bye-bye!$"

MatchCall_PersonalizedText49:: @ 82AEBFA
	.string "{STR_VAR_1} here!\p"
	.string "I'm a SAILOR, but I'm not on a boat\n"
	.string "now.\p"
	.string "It makes me wonder--what should\n"
	.string "a SAILOR on land be called?\p"
	.string "That's what I've been thinking\n"
	.string "while staring out across the waves.\p"
	.string "All right, next time!$"

MatchCall_PersonalizedText50:: @ 82AECC1
	.string "It's {STR_VAR_1}.\n"
	.string "So? Get any more POKéMON?\p"
	.string "If you catch a new POKéMON,\n"
	.string "you have to come show me.\p"
	.string "I won't whine for it, honest.\n"
	.string "I'll be waiting. See you.$"

MatchCall_PersonalizedText51:: @ 82AED52
	.string "This is {STR_VAR_1}.\p"
	.string "Are you raising your POKéMON\n"
	.string "in the optimal way?\p"
	.string "The air is clean where I am.\n"
	.string "It's the perfect environment for\l"
	.string "raising POKéMON.\p"
	.string "If you're going to focus on raising\n"
	.string "POKéMON, you should come out to\l"
	.string "{STR_VAR_2}. Take care now.$"

MatchCall_PersonalizedText52:: @ 82AEE35
	.string "Hi, this is {STR_VAR_1}.\p"
	.string "I gave a {POKEBLOCK} to my {STR_VAR_2}.\n"
	.string "It seemed to enjoy it very much.\p"
	.string "It looks like POKéMON have their\n"
	.string "likes and dislikes with {POKEBLOCK}S.\p"
	.string "I find that quite fascinating.\n"
	.string "Please do take care.$"

MatchCall_PersonalizedText53:: @ 82AEEF4
	.string "{STR_VAR_1} here.\p"
	.string "If you cooperate with POKéMON,\n"
	.string "one can be comfortable in the wild.\p"
	.string "Everyone should realize that and\n"
	.string "cooperate with POKéMON more.\p"
	.string "That would be ideal.\n"
	.string "I really think so.\p"
	.string "I think you're on the right track!\n"
	.string "Catch you later!$"

MatchCall_PersonalizedText54:: @ 82AEFDA
	.string "Hi, it's {STR_VAR_1}. You know,\n"
	.string "the TRAINER who's always prepared!\p"
	.string "{PLAYER}{KUN}, do you have enough items?\n"
	.string "Are your POKéMON fit for action?\p"
	.string "Keeping everything perfect around\n"
	.string "you all the time is the secret to\l"
	.string "keeping your journey going.\p"
	.string "I'd better go check my own\n"
	.string "supplies! Be vigilant!$"

MatchCall_PersonalizedText55:: @ 82AF0E7
	.string "It's {STR_VAR_1}!\n"
	.string "It's {STR_VAR_1}!\p"
	.string "{STR_VAR_2} is a very busy\n"
	.string "thoroughfare, so I get challenged\l"
	.string "by all kinds of TRAINERS every day.\p"
	.string "Today, I won five battles and lost\n"
	.string "only three!\p"
	.string "How did you do today?\n"
	.string "Tell me about it next time, okay?$"

MatchCall_PersonalizedText56:: @ 82AF1B8
	.string "It's me, {STR_VAR_1}.\p"
	.string "I'm popular because I have lots\n"
	.string "of BUG POKéMON, right?\p"
	.string "Well, I took a bunch of my fave\n"
	.string "bugs to school today.\p"
	.string "This girl I like started crying!\n"
	.string "Go ahead and laugh if you want.\p"
	.string "I have to try teaching her what\n"
	.string "makes BUG POKéMON so appealing.\p"
	.string "Snivel…\n"
	.string "See you!$"

MatchCall_PersonalizedText57:: @ 82AF2C4
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! It's {STR_VAR_1}! Hah! Hah!\p"
	.string "Trying to chat…\n"
	.string "While climbing…\l"
	.string "Is harsh exercise… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "It's steeper now…\l"
	.string "We'll chat…another time…\l"
	.string "Hah! Hah! Hah!$"

MatchCall_PersonalizedText58:: @ 82AF371
	.string "Oh, hi!\p"
	.string "I'm still searching for treasures\n"
	.string "with KIRA!\p"
	.string "Maybe there isn't any treasure\n"
	.string "here at all…\p"
	.string "But the important thing is for me\n"
	.string "to search alongside KIRA.\p"
	.string "Oh, hey, KIRA!\n"
	.string "Wh-why are you angry?\p"
	.string "I'm not ignoring you, honey!\n"
	.string "You're my one and only!\p"
	.string "…{PLAYER}, I have to go, bye!$"

MatchCall_PersonalizedText59:: @ 82AF480
	.string "This is {STR_VAR_1}!\p"
	.string "I went to DEWFORD's GYM again\n"
	.string "for training.\p"
	.string "BRAWLY, the GYM LEADER, seems\n"
	.string "to be tougher now.\p"
	.string "Something about being toughened\n"
	.string "by the wild waves…\p"
	.string "But he's still as cool as ever.\n"
	.string "The ladies adore him!\l"
	.string "It makes me envious, frankly.\p"
	.string "I wonder… Is his friend BRUNO\n"
	.string "the same way as BRAWLY?\p"
	.string "You know, all sweaty or smelly,\n"
	.string "and prone to calling people\l"
	.string "“big wave,” that sort of thing.\p"
	.string "But, hey, this jealousy thing isn't\n"
	.string "very seemly, is it?\p"
	.string "Forget this chat ever happened,\n"
	.string "how about it? So long!$"

MatchCall_PersonalizedText60:: @ 82AF671
	.string "It's a pleasure to chat with\n"
	.string "a young TRAINER like you.\p"
	.string "I imagine that you will continue to\n"
	.string "enjoy POKéMON whatever your age.\p"
	.string "Wouldn't it be good if you had\n"
	.string "a partnership like ours?\p"
	.string "Of course, {PLAYER}{KUN}, you already\n"
	.string "enjoy the trust and companionship\l"
	.string "of your POKéMON now.\p"
	.string "You have the makings of long and\n"
	.string "enduring relationships already!\p"
	.string "Hahaha!\n"
	.string "Never be discouraged!$"

MatchCall_PersonalizedText61:: @ 82AF7D8
	.string "Hi, this is {STR_VAR_1}!\n"
	.string "We just won a battle!\p"
	.string "We don't win often, but it was this\n"
	.string "cool SWIMMER guy.\p"
	.string "My sister was steamed!\p"
	.string "She wanted to pretend that she\n"
	.string "was weak to make an impression!\p"
	.string "She always chews me out whether\n"
	.string "we win or lose!\p"
	.string "{PLAYER}{KUN}, can you say something\n"
	.string "to her next time?\p"
	.string "Okay, see you!$"

MatchCall_PersonalizedText62:: @ 82AF8F7
	.string "{STR_VAR_1} here, yes.\n"
	.string "I headed out to sea yesterday.\p"
	.string "I had been hoping to find a new\n"
	.string "ruin to explore.\p"
	.string "But the tides somehow seemed to\n"
	.string "carry me back where I started.\p"
	.string "I'm still weak at battling, too…\n"
	.string "Feel free to mock me…\l"
	.string "But I won't give up.\p"
	.string "My day will come when I discover\n"
	.string "a new ruin!\p"
	.string "That's all I have to say!\n"
	.string "Farewell for now!$"

MatchCall_PersonalizedText63:: @ 82AFA39
	.string "Ahoy there!\n"
	.string "It's me, {STR_VAR_1}!\l"
	.string "I'm out on ROUTE 108 now!\l"
	.string "In other words, where I always am!\p"
	.string "Today, a gorgeous SWIMMER \n"
	.string "swam by me!\p"
	.string "So I startled her with a shout!\p"
	.string "And she gave me a nasty glare!\p"
	.string "That's all from ROUTE 108!\n"
	.string "Brought to you by {STR_VAR_1}!$"

MatchCall_PersonalizedText64:: @ 82AFB26
	.string "It's {STR_VAR_1}!\p"
	.string "I'm kind of busy, but I figured\n"
	.string "I should let you know that I've\l"
	.string "beaten five TRAINERS again today.\p"
	.string "If I keep this pace up, I can\n"
	.string "probably beat you next time.\p"
	.string "I think we'll be good rivals,\n"
	.string "you and I. Good-bye for now!$"

MatchCall_BattleFrontierStreakText1:: @ 82AFC07
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome, {STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText2:: @ 82AFC78
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierStreakText3:: @ 82AFCFF
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierStreakText4:: @ 82AFDA7
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText5:: @ 82AFE3D
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "I'd better work on my POKéMON more.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierStreakText6:: @ 82AFECA
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That inspires me to focus on\n"
	.string "raising my team.$"

MatchCall_BattleFrontierStreakText7:: @ 82AFF64
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierStreakText8:: @ 82AFFF0
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I hope you stay successful.$"

MatchCall_BattleFrontierStreakText9:: @ 82B00B5
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierStreakText10:: @ 82B0129
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierStreakText11:: @ 82B01A5
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierStreakText12:: @ 82B0232
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierStreakText13:: @ 82B02D9
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierStreakText14:: @ 82B0366
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I heard about you!\n"
	.string "Didn't you just win {STR_VAR_3} battles in\l"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1:: @ 82B03E6
	.string "Hi! This is {STR_VAR_1}.\n"
	.string "I heard the news!\p"
	.string "They say you did excellent at\n"
	.string "the {STR_VAR_2}.\p"
	.string "It's awesome--{STR_VAR_3} straight wins?\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText2:: @ 82B0457
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "That's special! I should try\n"
	.string "harder, too! See you!$"

MatchCall_BattleFrontierRecordStreakText3:: @ 82B04DE
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\p"
	.string "I heard you went on a tear at\n"
	.string "the {STR_VAR_2}!\p"
	.string "A big {STR_VAR_3}-win streak…\n"
	.string "That is a big record, isn't it?\p"
	.string "I'd better get it together, too!\n"
	.string "Catch you soon!$"

MatchCall_BattleFrontierRecordStreakText4:: @ 82B0586
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. What's up?\p"
	.string "There's a rumor going around that\n"
	.string "you strung together {STR_VAR_3} straight\l"
	.string "wins at the {STR_VAR_2}.\p"
	.string "I'd better step it up, too.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText5:: @ 82B061C
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won {STR_VAR_3} battles in a row?\l"
	.string "Isn't that something!\p"
	.string "Me? I'd say I'm coming along.\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText6:: @ 82B06A3
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you pulled off\n"
	.string "the feat of {STR_VAR_3} straight wins at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better try harder myself!\n"
	.string "See you soon!$"

MatchCall_BattleFrontierRecordStreakText7:: @ 82B073B
	.string "…Er, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here…\p"
	.string "Oh, yeah, you were over at\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "And you won {STR_VAR_3} battles in a row.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "I have to go!$"

MatchCall_BattleFrontierRecordStreakText8:: @ 82B07C7
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\p"
	.string "Oh, but, you are. I've heard that\n"
	.string "you won {STR_VAR_3} matches in a row at\l"
	.string "the {STR_VAR_2}.\p"
	.string "That's very impressive!\n"
	.string "I'd better work on my POKéMON, too!$"

MatchCall_BattleFrontierRecordStreakText9:: @ 82B0894
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! Your {STR_VAR_3}-win streak at\n"
	.string "the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleFrontierRecordStreakText10:: @ 82B0908
	.string "Oh, {PLAYER}{KUN}, hello…\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight battles at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleFrontierRecordStreakText11:: @ 82B0984
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} matches in\n"
	.string "a row?\p"
	.string "You're good, you.\n"
	.string "I wonder how many I can win?$"

MatchCall_BattleFrontierRecordStreakText12:: @ 82B0A11
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "Someone passed on word about you.\n"
	.string "How you won {STR_VAR_3} straight battles\l"
	.string "at a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleFrontierRecordStreakText13:: @ 82B0AB8
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} straight\n"
	.string "battles at the {STR_VAR_2}.\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleFrontierRecordStreakText14:: @ 82B0B45
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you just win {STR_VAR_3} battles in\n"
	.string "a row at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1:: @ 82B0BC5
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You became the champion at\n"
	.string "the {STR_VAR_2} {STR_VAR_3} times?\p"
	.string "It's awesome! I have to do better!\n"
	.string "See you!$"

MatchCall_BattleDomeText2:: @ 82B0C4A
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "That's super! I wonder if I can\n"
	.string "become a champion?$"

MatchCall_BattleDomeText3:: @ 82B0CC7
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won events {STR_VAR_3} times\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Make it one more next time!\n"
	.string "Catch you soon!$"

MatchCall_BattleDomeText4:: @ 82B0D4A
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you became the champion\n"
	.string "at the {STR_VAR_2} {STR_VAR_3} times.\p"
	.string "Sounds like you're working hard.\n"
	.string "I'll try to keep up!$"

MatchCall_BattleDomeText5:: @ 82B0DC8
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you won {STR_VAR_3} times\n"
	.string "outright at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattleDomeText6:: @ 82B0E35
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you became\n"
	.string "the champion {STR_VAR_3} times at\l"
	.string "the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull farther ahead.$"

MatchCall_BattleDomeText7:: @ 82B0ED1
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and became the champ {STR_VAR_3} times?\p"
	.string "That's neat. By the way, have you\n"
	.string "caught any rare POKéMON lately?\p"
	.string "Oh, is that right.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8:: @ 82B0F72
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you won {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I must raise my POKéMON like you.\n"
	.string "See you again.$"

MatchCall_BattleDomeText9:: @ 82B102A
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You took the title\n"
	.string "{STR_VAR_3} times at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattleDomeText10:: @ 82B10A7
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won {STR_VAR_3} straight times at\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattleDomeText11:: @ 82B1121
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You won, what, {STR_VAR_3} straight times\n"
	.string "now?\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattleDomeText12:: @ 82B11D3
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won {STR_VAR_3} events at a place\n"
	.string "named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattleDomeText13:: @ 82B124D
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won {STR_VAR_3} events\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattleDomeText14:: @ 82B12D0
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you win {STR_VAR_3} titles\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePikeText1:: @ 82B1347
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You got through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "That's awesome!\n"
	.string "See you!$"

MatchCall_BattlePikeText2:: @ 82B13B1
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I have to try much harder!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3:: @ 82B142B
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you won through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePikeText4:: @ 82B14B4
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you blew through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better train my POKéMON and\n"
	.string "try to keep up!$"

MatchCall_BattlePikeText5:: @ 82B1525
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you got past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePikeText6:: @ 82B158E
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePikeText7:: @ 82B1622
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way past {STR_VAR_3} rooms?\p"
	.string "That's wicked.\p"
	.string "Oh, there goes a rare POKéMON!\n"
	.string "Okay, bye.$"

MatchCall_BattlePikeText8:: @ 82B169D
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePikeText9:: @ 82B1775
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} rooms at the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePikeText10:: @ 82B17F8
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You won your way past {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePikeText11:: @ 82B1877
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You got through, what, {STR_VAR_3} rooms?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePikeText12:: @ 82B1946
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} rooms at\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePikeText13:: @ 82B19C7
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you won in {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePikeText14:: @ 82B1A4C
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} rooms\n"
	.string "at the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_BattlePyramidText1:: @ 82B1ACA
	.string "Hi! {PLAYER}?\n"
	.string "Hello, this is {STR_VAR_1}!\l"
	.string "I heard the news!\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}, right?\p"
	.string "That's awesome!\n"
	.string "I should try that challenge.$"

MatchCall_BattlePyramidText2:: @ 82B1B50
	.string "Hello, it's {STR_VAR_1}!\n"
	.string "I heard about you!\p"
	.string "They said you won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "Wow, that's fantastic!\n"
	.string "I'd better raise my POKéMON, too!$"

MatchCall_BattlePyramidText3:: @ 82B1BE4
	.string "Hey there, {PLAYER}!\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "How's it going?\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}!\p"
	.string "Try to do even better next time!\n"
	.string "Catch you soon!$"

MatchCall_BattlePyramidText4:: @ 82B1C6A
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} here.\p"
	.string "I heard you scaled {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better work hard and try\n"
	.string "to keep up!$"

MatchCall_BattlePyramidText5:: @ 82B1CCF
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "It's {STR_VAR_1}.\p"
	.string "I heard you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}.\p"
	.string "I'd better get with it, too!\n"
	.string "See you soon!$"

MatchCall_BattlePyramidText6:: @ 82B1D38
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here. How are you?\p"
	.string "By the way, I heard you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "I'd better raise my POKéMON before\n"
	.string "you pull further ahead.$"

MatchCall_BattlePyramidText7:: @ 82B1DCD
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} here.\p"
	.string "You were at the {STR_VAR_2}\n"
	.string "and won your way up {STR_VAR_3} floors?\p"
	.string "Neat. Were there any rare POKéMON\n"
	.string "there?\p"
	.string "No, huh?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8:: @ 82B1E4B
	.string "Oh, {PLAYER}{KUN}, how do you do?\n"
	.string "This is {STR_VAR_1} speaking.\l"
	.string "I hope you're doing well.\l"
	.string "Oh, but, you are.\p"
	.string "I've heard that you got through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}.\p"
	.string "That's quite impressive!\n"
	.string "I must raise my POKéMON like you.\l"
	.string "See you again.$"

MatchCall_BattlePyramidText9:: @ 82B1F24
	.string "Oh, {PLAYER}{KUN}, hi there!\n"
	.string "This is {STR_VAR_1}!\p"
	.string "I heard! You won your way through\n"
	.string "{STR_VAR_3} floors in the {STR_VAR_2}!\p"
	.string "That is so cool!\n"
	.string "I'd better try harder, too!$"

MatchCall_BattlePyramidText10:: @ 82B1FA8
	.string "Oh, {PLAYER}{KUN}, hello.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "You climbed {STR_VAR_3} floors inside\n"
	.string "the {STR_VAR_2}?\p"
	.string "That's quite the accomplishment.\n"
	.string "I need to work harder.$"

MatchCall_BattlePyramidText11:: @ 82B2022
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\p"
	.string "I hear you're the terror of\n"
	.string "the {STR_VAR_2}?\p"
	.string "You rose through, what, {STR_VAR_3} floors?\n"
	.string "That's gotta count for something.\p"
	.string "I wonder if I can ever become\n"
	.string "a champion?\p"
	.string "…Pretty well impossible?\n"
	.string "Well, see you!$"

MatchCall_BattlePyramidText12:: @ 82B20F3
	.string "Hello, {PLAYER}{KUN}.\n"
	.string "It's me, {STR_VAR_1}.\l"
	.string "Are you keeping well?\p"
	.string "You've won through {STR_VAR_3} floors in\n"
	.string "a place named {STR_VAR_2}?\p"
	.string "That's quite the tale.\n"
	.string "See you!$"

MatchCall_BattlePyramidText13:: @ 82B2175
	.string "Ah, hello, {PLAYER}{KUN}!\n"
	.string "This is {STR_VAR_1}!\l"
	.string "I hope you've been keeping well.\p"
	.string "They say you climbed {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "I admire your energy!\n"
	.string "Bye now.$"

MatchCall_BattlePyramidText14:: @ 82B21FC
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "This is {STR_VAR_1}.\l"
	.string "I heard about you!\p"
	.string "Didn't you get through {STR_VAR_3} floors\n"
	.string "in the {STR_VAR_2}?\p"
	.string "You're an inspiration!\n"
	.string "See you again!$"

MatchCall_Text_Mom1:: @ 82B227B
	.string "MOM: Your father and you…\n"
	.string "Everyone is captivated by POKéMON.\p"
	.string "What is the charm of POKéMON?\p"
	.string "Me?\n"
	.string "I adore POKéMON that help me with\l"
	.string "my everyday chores.$"

MatchCall_Text_Mom2:: @ 82B2310
	.string "MOM: Hi, {PLAYER}!\n"
	.string "Your father keeps himself locked\l"
	.string "away in the PETALBURG GYM.\p"
	.string "He comes home every so often.\n"
	.string "But he goes back to the GYM when\l"
	.string "he's eaten everything he can.\p"
	.string "I'm guessing that losing to you\n"
	.string "was a big blow to his pride!$"

MatchCall_Text_Mom3:: @ 82B23F3
	.string "MOM: {PLAYER}…\n"
	.string "Don't worry about me or the house.\p"
	.string "Wear those RUNNING SHOES until\n"
	.string "they fall apart, honey!$"

MatchCall_Text_Roxanne1:: @ 82B2456
	.string "ROXANNE: Oh, hello, {PLAYER}!\p"
	.string "I've been hard at work retraining\n"
	.string "since we met.\p"
	.string "I will still need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne2:: @ 82B250E
	.string "ROXANNE: Is this {PLAYER}?\n"
	.string "Congratulations!\l"
	.string "I've been hearing about you!\p"
	.string "As for me, I need some more time\n"
	.string "before I can reopen the GYM.\p"
	.string "But when I do, please visit my GYM\n"
	.string "for a rematch!$"

MatchCall_Text_Roxanne3:: @ 82B25C1
	.string "ROXANNE: {PLAYER}!\n"
	.string "My GYM is ready!\p"
	.string "Please visit RUSTBORO whenever\n"
	.string "you can!$"

MatchCall_Text_Roxanne4:: @ 82B2607
	.string "ROXANNE: At the RUSTBORO GYM,\n"
	.string "the fact that we battled, {PLAYER},\l"
	.string "is a matter of pride.$"

MatchCall_Text_Brawly1:: @ 82B2659
	.string "BRAWLY: Hey, there, {PLAYER}{KUN}!\p"
	.string "I learned a lot from the battle we\n"
	.string "had together.\p"
	.string "I intend to do my training over,\n"
	.string "then reopen the GYM.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly2:: @ 82B275D
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "Congratulations!\p"
	.string "Word about your exploits arrived\n"
	.string "on tidal winds!\p"
	.string "It appears as if I need to work on\n"
	.string "my training some more.\p"
	.string "It's going to take some time before\n"
	.string "I'm ready to run the GYM again.\p"
	.string "But if I can reopen the GYM,\n"
	.string "I want you to challenge us again.$"

MatchCall_Text_Brawly3:: @ 82B286F
	.string "BRAWLY: Hey, {PLAYER}{KUN}!\n"
	.string "My GYM's ready for action!\p"
	.string "Come back to DEWFORD anytime\n"
	.string "for another challenge!$"

MatchCall_Text_Brawly4:: @ 82B28D1
	.string "BRAWLY: {PLAYER}{KUN}, I don't think\n"
	.string "I'll ever get bored of battling you!$"

MatchCall_Text_Wattson1:: @ 82B2912
	.string "WATTSON: Oh, it's you!\p"
	.string "After you left, I've been redoing\n"
	.string "my training from scratch.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2:: @ 82B29CA
	.string "WATTSON: Wahahahaha!\p"
	.string "You've really done it, haven't you?\n"
	.string "I've been getting word about you!\p"
	.string "It seems I need to retrain some\n"
	.string "more still.\p"
	.string "I'd say I could use a wee bit more\n"
	.string "time to reopen my GYM.\p"
	.string "You'll have to wait till then!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3:: @ 82B2AB6
	.string "WATTSON: Oh, it's you!\n"
	.string "My GYM's ready!\p"
	.string "Visit MAUVILLE anytime!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4:: @ 82B2B01
	.string "WATTSON: Wahahaha!\p"
	.string "A battle with you is always charged\n"
	.string "with shocking power!$"

MatchCall_Text_Flannery1:: @ 82B2B4D
	.string "FLANNERY: {PLAYER}…\p"
	.string "When we battled, I learned exactly\n"
	.string "how immature I was.\p"
	.string "But I'm not done yet!\p"
	.string "I'm going to redo my training and\n"
	.string "reopen the GYM.\p"
	.string "When the time comes, {PLAYER},\n"
	.string "please challenge us again.$"

MatchCall_Text_Flannery2:: @ 82B2C0E
	.string "FLANNERY: Hello, {PLAYER}?\n"
	.string "Congratulations!\p"
	.string "Word of your success has reached\n"
	.string "us like the heat of a volcano!\p"
	.string "Our training is coming along very\n"
	.string "well here.\p"
	.string "When the GYM's ready, a mark will\n"
	.string "appear beside my name in the\l"
	.string "MATCH CALL list.$"

MatchCall_Text_Flannery3:: @ 82B2CF1
	.string "FLANNERY: Oh, {PLAYER}?\n"
	.string "Our GYM's ready!\p"
	.string "Come to LAVARIDGE for a soak\n"
	.string "in the hot spring and a challenge!$"

MatchCall_Text_Flannery4:: @ 82B2D54
	.string "FLANNERY: {PLAYER}…\n"
	.string "I'm positive that you keep getting\l"
	.string "better at training every time.$"

MatchCall_Text_Winona1:: @ 82B2DA4
	.string "WINONA: Hello, {PLAYER}!\p"
	.string "Thanks to our battle, I've come\n"
	.string "to understand my weak points!\p"
	.string "When I reopen the GYM, I won't go\n"
	.string "down in defeat again!$"

MatchCall_Text_Winona2:: @ 82B2E2B
	.string "WINONA: You've done it, {PLAYER}!\p"
	.string "News about the new CHAMPION\n"
	.string "has reached us in FORTREE!\p"
	.string "But… The next time we battle,\n"
	.string "it's not going to end the same way.$"

MatchCall_Text_Winona3:: @ 82B2EC2
	.string "WINONA: Is this {PLAYER}?\n"
	.string "Our GYM is back in operation!\p"
	.string "We're waiting for you in FORTREE!$"

MatchCall_Text_Winona4:: @ 82B2F16
	.string "WINONA: {PLAYER}…\n"
	.string "Though I have lost, my wings will\l"
	.string "never break.\p"
	.string "Yes, in exactly the same way that\n"
	.string "you never lost sight of your dream.$"

MatchCall_Text_TateLiza1:: @ 82B2F97
	.string "TATE: Oh! You're…\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: We're in training again…\n"
	.string "LIZA: So we can reopen our GYM!\p"
	.string "TATE: When our GYM is ready…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza2:: @ 82B306E
	.string "TATE: {PLAYER}, congratulations!\n"
	.string "LIZA: {PLAYER}, congratulations!\p"
	.string "TATE: The two of us are…\n"
	.string "LIZA: Still in training!\p"
	.string "TATE: We need some more time, but…\n"
	.string "LIZA: When our GYM is ready…\p"
	.string "TATE: A mark'll appear by our name…\n"
	.string "LIZA: On the MATCH CALL list.$"

MatchCall_Text_TateLiza3:: @ 82B3158
	.string "TATE: {PLAYER}!\n"
	.string "LIZA: {PLAYER}!\p"
	.string "TATE: Our GYM is ready!\n"
	.string "LIZA: Our GYM is ready!\p"
	.string "TATE: Please come visit…\n"
	.string "LIZA: MOSSDEEP anytime!$"

MatchCall_Text_TateLiza4:: @ 82B31CD
	.string "TATE: {PLAYER}, the battle we had…\n"
	.string "LIZA: Is an invaluable experience.\p"
	.string "TATE: It would be nice if…\n"
	.string "LIZA: We could all battle again!$"

MatchCall_Text_Juan1:: @ 82B3249
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Was it?\p"
	.string "Our battle together--it brought\n"
	.string "to me memories of when I first\l"
	.string "encountered WALLACE.\p"
	.string "Perhaps you are a genius who may\n"
	.string "yet surpass WALLACE!$"

MatchCall_Text_Juan2:: @ 82B32EC
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "You've finally achieved your goal.\p"
	.string "My eye for appraising talent wasn't\n"
	.string "mistaken…\p"
	.string "I wish for another chance to meet\n"
	.string "you, for you have scaled the peak\l"
	.string "of power and prestige.$"

MatchCall_Text_Juan3:: @ 82B33AA
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "Our SOOTOPOLIS GYM has finally\n"
	.string "reopened.\p"
	.string "If you wish to see me, you are\n"
	.string "welcome to visit anytime.$"

MatchCall_Text_Juan4:: @ 82B341E
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Like the finest music, the battles\n"
	.string "we wage together strike chords\l"
	.string "of inspiration in my heart…\p"
	.string "When I close my eyes, I see visions\n"
	.string "of you soaring with the melody…$"

MatchCall_Text_Sidney:: @ 82B34CC
	.string "SIDNEY: Yo, {PLAYER}!\p"
	.string "If you want to battle with me\n"
	.string "again, you come on back whenever\l"
	.string "you like to the POKéMON LEAGUE.\p"
	.string "I'll always be here!\n"
	.string "I'll be waiting!$"

MatchCall_Text_Phoebe:: @ 82B3561
	.string "PHOEBE: Hi, {PLAYER}!\p"
	.string "How about coming back here again\n"
	.string "sometime?\p"
	.string "I'd like to see how much tighter\n"
	.string "your bond has grown with your\l"
	.string "POKéMON.$"

MatchCall_Text_Glacia:: @ 82B35E4
	.string "GLACIA: Hello, {PLAYER}.\p"
	.string "I trust you haven't become\n"
	.string "complacent with your power?\p"
	.string "If you feel the need to cool your\n"
	.string "hot emotions just a little, do come\l"
	.string "to the POKéMON LEAGUE…$"

MatchCall_Text_Drake:: @ 82B368B
	.string "DRAKE: That voice… {PLAYER}, is it?\n"
	.string "You sound well…\p"
	.string "I understand that there is now\n"
	.string "a facility called the BATTLE\l"
	.string "FRONTIER that tests the skills of\l"
	.string "TRAINERS.\p"
	.string "However, if you wish to have real\n"
	.string "battles, there is no substitute for\l"
	.string "the POKéMON LEAGUE!\p"
	.string "Don't you agree, {PLAYER}?$"

MatchCall_Text_Wallace:: @ 82B3790
	.string "WALLACE: Hello, {PLAYER}{KUN}.\n"
	.string "Have you met STEVEN?\p"
	.string "He is…\n"
	.string "Actually incredibly skilled.\p"
	.string "However, he's an odd soul who\n"
	.string "rarely battles.\p"
	.string "Instead, he would rather look for\n"
	.string "rare stones.\p"
	.string "I'm sure he's digging in a cave or\n"
	.string "a craggy mountain somewhere.\p"
	.string "But what is a rare stone exactly?\n"
	.string "All I can think of is a METEORITE…$"

MatchCall_Text_MayRayquazaCall: @ 82B38C1
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was just in PACIFIDLOG a little\n"
	.string "while ago.\p"
	.string "I saw a giant green POKéMON\n"
	.string "flying high in the sky.\p"
	.string "I…\n"
	.string "I've never seen anything like it.\p"
	.string "I wonder what it was.\n"
	.string "Is this maybe a major discovery?\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_BrendanRayquazaCall: @ 82B39C6
	.string "… … … … … …\n"
	.string "… … … … … Beep!\p"
	.string "BRENDAN: Hey, {PLAYER}!\n"
	.string "I was in PACIFIDLOG just now.\p"
	.string "I saw this huge green POKéMON\n"
	.string "flying across the sky.\p"
	.string "I've never seen anything that\n"
	.string "amazing before.\p"
	.string "I wish you could've seen it,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Click!$"

MatchCall_Text_May1:: @ 2B3AB3
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "He must love the sea still.$"

MatchCall_Text_May2:: @ 2B3B3F
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "You know how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS?\p"
	.string "For some reason, the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_May3:: @ 2B3C13
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Do you remember a man named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, remember?\p"
	.string "Well, I found out his younger\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_May4:: @ 2B3CF3
	.string "MAY: {PLAYER}{KUN}?\p"
	.string "RUSTURF TUNNEL…\n"
	.string "They named it that because it\l"
	.string "joins RUSTBORO and VERDANTURF.$"

MatchCall_Text_May5:: @ 2B3D4B
	.string "MAY: {PLAYER}{KUN}, how are you?\p"
	.string "I'm out on ROUTE 111 now.\p"
	.string "I'm going to get a rest at an old\n"
	.string "lady's house.\p"
	.string "She lives just north of\n"
	.string "the desert.$"

MatchCall_Text_May6:: @ 2B3DD1
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it seems\n"
	.string "to mysteriously come and go.\p"
	.string "I wish I could see it.$"

MatchCall_Text_May7:: @ 2B3E69
	.string "MAY: {PLAYER}{KUN}, yahoo!\n"
	.string "I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it often rains.\p"
	.string "I got soaked!$"

MatchCall_Text_May8:: @ 2B3ECD
	.string "MAY: {PLAYER}{KUN}, hi.\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "Maybe as a result, it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_May9:: @ 2B3F2B
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "I was thinking of going to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But on the way, around JAGGED\n"
	.string "PASS, I ran into some bad-looking\l"
	.string "characters. The mood was ugly!$"

MatchCall_Text_May10:: @ 2B3FFB
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Did you see the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_May11:: @ 2B402B
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Don't you think it's neat?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "Did you know there's more?\p"
	.string "There's a POKéMON move that lets\n"
	.string "you go to the bottom of the sea.$"

MatchCall_Text_May12:: @ 2B414B
	.string "MAY: Hi, {PLAYER}{KUN}!\n"
	.string "Hope things are okay!\p"
	.string "Have you been on the sea and\n"
	.string "found your way to the other side\l"
	.string "blocked?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Easy!$"

MatchCall_Text_May13:: @ 2B4228
	.string "MAY: Hi, {PLAYER}{KUN}!\p"
	.string "How's it going?\n"
	.string "Are you filling your POKéDEX?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And there are three of them!\p"
	.string "I would love to see even one…$"

MatchCall_Text_May14:: @ 2B42E0
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER?\p"
	.string "That means you don't have far\n"
	.string "to go, do you?$"

MatchCall_Text_May15:: @ 2B4350
	.string "MAY: There isn't a single TRAINER\n"
	.string "left in HOENN who doesn't know who\l"
	.string "you are, {PLAYER}{KUN}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}{KUN}, they're all\l"
	.string "surprised!$"

MatchCall_Text_Brendan1:: @ 2B43EF
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "MR. BRINEY retired as a SAILOR,\n"
	.string "but I still see him out on the sea\l"
	.string "with his pet PEEKO sometimes.\p"
	.string "I guess he must love\n"
	.string "the sea still.$"

MatchCall_Text_Brendan2:: @ 2B4486
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "I don't get how little towns like\n"
	.string "PETALBURG and DEWFORD have GYMS.\p"
	.string "I mean, not when the big port of\n"
	.string "SLATEPORT doesn't have a GYM.\p"
	.string "When they finally build a GYM there,\n"
	.string "I should apply to be the LEADER.$"

MatchCall_Text_Brendan3:: @ 2B4560
	.string "BRENDAN: Yo, {PLAYER}!\p"
	.string "Do you remember a guy named\n"
	.string "the CUTTER in RUSTBORO?\l"
	.string "He had a house there, right?\p"
	.string "Well, it turns out his little\n"
	.string "brother lives in MAUVILLE.\p"
	.string "Can you guess his name?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "The ROCK SMASH GUY!$"

MatchCall_Text_Brendan4:: @ 2B463F
	.string "BRENDAN: This voice… {PLAYER}?\p"
	.string "They gave RUSTURF TUNNEL its name\n"
	.string "because it joins RUSTBORO and\l"
	.string "VERDANTURF.\p"
	.string "Did you know that?$"

MatchCall_Text_Brendan5:: @ 2B46B7
	.string "BRENDAN: {PLAYER}, what's up?\p"
	.string "Hey, I'm out on ROUTE 111 now.\p"
	.string "I'm going to rest up at an old\n"
	.string "lady's house north of the desert.\p"
	.string "If you're in the area, you should\n"
	.string "visit her, too.$"

MatchCall_Text_Brendan6:: @ 2B4761
	.string "BRENDAN: Hey, {PLAYER}!\p"
	.string "Did you know about the MIRAGE\n"
	.string "TOWER in the desert?\p"
	.string "They say, like a mirage, it can be\n"
	.string "seen only sometimes.\p"
	.string "I'd like to see that!$"

MatchCall_Text_Brendan7:: @ 2B47F4
	.string "BRENDAN: Who's this? Oh, {PLAYER}?\n"
	.string "Guess what? I'm on ROUTE 119 now.\p"
	.string "There's a big river here, and\n"
	.string "it rains all the time.\p"
	.string "I got soaked to the bone!$"

MatchCall_Text_Brendan8:: @ 2B4882
	.string "BRENDAN: {PLAYER}!\p"
	.string "MT. PYRE is a memorial to POKéMON\n"
	.string "whose lives have ended.\p"
	.string "That's probably why it's infested\n"
	.string "with many GHOST-type POKéMON!$"

MatchCall_Text_Brendan9:: @ 2B4909
	.string "BRENDAN: Hey there, {PLAYER}.\p"
	.string "I was on my way back to the hot\n"
	.string "spring in LAVARIDGE.\p"
	.string "But around JAGGED PASS, I ran into\n"
	.string "some nasty-looking characters.\p"
	.string "Those creeps…\n"
	.string "I think they were TEAM MAGMA.$"

MatchCall_Text_Brendan10:: @ 2B49C4
	.string "BRENDAN: Hi, {PLAYER}!\n"
	.string "Did you catch the news?\p"
	.string "They say CAPT. STERN discovered\n"
	.string "the SEAFLOOR CAVERN while on his\l"
	.string "submarine expedition.$"

MatchCall_Text_Brendan11:: @ 2B4A44
	.string "BRENDAN: Hey there, {PLAYER}!\n"
	.string "Don't you think it's awesome?\p"
	.string "Even if you don't have a boat,\n"
	.string "you can cross the sea using\l"
	.string "a POKéMON's move.\p"
	.string "And, there's a move that lets you\n"
	.string "travel to the bottom of the sea.\p"
	.string "Man, POKéMON can do anything!$"

MatchCall_Text_Brendan12:: @ 2B4B28
	.string "BRENDAN: Howdy, {PLAYER}!\n"
	.string "How are you holding up?\p"
	.string "Ever found your way to the other\n"
	.string "side blocked while on the sea?\p"
	.string "Try diving deep underwater and\n"
	.string "following trenches at the bottom.\p"
	.string "When you get to the other side,\n"
	.string "come up to the surface. Simple!$"

MatchCall_Text_Brendan13:: @ 2B4C15
	.string "BRENDAN: Hey there, {PLAYER}!\p"
	.string "How's it going? Filling up your\n"
	.string "POKéDEX successfully?\p"
	.string "I heard a rumor that there are\n"
	.string "super-ancient POKéMON out there.\l"
	.string "And not just one--three!\p"
	.string "I'd love to catch even one…$"

MatchCall_Text_Brendan14:: @ 2B4CD8
	.string "BRENDAN: {PLAYER}!\n"
	.string "I heard the rumors!\p"
	.string "You beat the SOOTOPOLIS GYM\n"
	.string "LEADER? Awesome!\p"
	.string "You're getting awful close now!$"

MatchCall_Text_Brendan15:: @ 2B4D46
	.string "BRENDAN: There isn't a TRAINER in\n"
	.string "all of HOENN who doesn't know who\l"
	.string "you are, {PLAYER}!\p"
	.string "When I tell people that I'm friends\n"
	.string "with you, {PLAYER}, they get pretty\l"
	.string "envious!$"

MatchCall_Text_Wally1:: @ 2B4DE2
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2:: @ 2B4E57
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3:: @ 2B4EA5
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4:: @ 2B4F41
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my POKéMON with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5:: @ 2B4FF3
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the POKéMON that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6:: @ 2B50B1
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Wally7:: @ 2B5100
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1:: @ 2B5184
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how POKéMON can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like POKéMON, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2:: @ 2B5275
	.string "SCOTT: I'm on ROUTE 119 right now.\n"
	.string "It's teeming with TRAINERS!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3:: @ 2B5323
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "The place is a memorial to POKéMON\n"
	.string "that have passed away.\p"
	.string "It's somewhere every TRAINER\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4:: @ 2B53DB
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5:: @ 2B54A5
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise POKéMON…$"

MatchCall_Text_Scott6:: @ 2B5541
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the POKéMON LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the POKéMON LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7:: @ 2B56CA
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Norman1:: @ 82B5719
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2:: @ 82B5795
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3:: @ 82B584D
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4:: @ 82B58E3
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5:: @ 82B5979
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6:: @ 82B5A07
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7:: @ 82B5A69
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8:: @ 82B5ACF
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9:: @ 82B5B5E
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1:: @ 82B5B95
	.string "성호: 여어 {PLAYER}!\p"
	.string "보라시티에는 벌써 가봤어?\p"
	.string "마을에 있는 사이클숍에서\n"
	.string "마하자전거를 얻었다면\p"
	.string "한 번 더 바위 동굴 안쪽에\n"
	.string "가보도록 해!\p"
	.string "뭔가 새로운 발견이\n"
	.string "있을지도 몰라!$"
	// ダイゴ『やあ §あ§お!ｐ
	// もう キンセツシティには いったかな?ｐ
	// まちの サイクルショップでｎ
	// マッハじてんしゃを てにいれたらｐ
	// もういちど いしのどうくつの おくにｎ
	// いってみるのも いいね!ｐ
	// なにか あたらしい はっけんがｎ
	// あるかも しれないよ!

MatchCall_Text_Steven2:: @ 82B5C53
	.string "성호: 여어 {PLAYER}!\p"
	.string "난 여태까지 꽤나 다양한\n"
	.string "트레이너를 봐왔지만\p"
	.string "넌 누구와도 닮지 않은\n"
	.string "처음으로 보는 타입의 사람이야!$"
	// ダイゴ『やあ §あ§お!ｐ
	// ボクは これまでに ずいぶん いろいろなｎ
	// トレ-ナ-を みてきた けれどｐ
	// キミは だれにも にていないｎ
	// はじめて みる タイプの ひとだよ!

MatchCall_Text_Steven3:: @ 82B5CC9
	.string "성호: 여어 {PLAYER}!\p"
	.string "너는 포켓몬과 모험하면서\n"
	.string "어떤 기분을 느끼고 있니?\p"
	.string "강한 아군이라고 생각하니?\n"
	.string "재밌는 동료라고 생각하니?\p"
	.string "네가 어떻게 생각하느냐에 따라\n"
	.string "그 모험의 의미가 바뀔 거야!$"
	// ダイゴ『やあ §あ§お!ｐ
	// キミは ポケモンと ぼうけんを していてｎ
	// どんな きぶんに なる?ｐ
	// つよいみかた だと おもうかい?ｎ
	// たのしいなかま だと おもうかい?ｐ
	// キミが どう かんじるかに よってｎ
	// その ぼうけんの いみは かわるんだ!

MatchCall_Text_Steven4:: @ 82B5DB4
	.string "성호: 아아 {PLAYER}{K_I}니?\p"
	.string "지금 막 우주센터에서\n"
	.string "성가신 일이 일어났어\p"
	.string "미안하지만 나중에 보자!$"
	// ダイゴ『ああ §あ§お かい?ｐ
	// ちょっと いま うちゅうセンタ-でｎ
	// めんどうな ことが おきてるんだｐ
	// わるいけど また あとでね!

MatchCall_Text_Steven5:: @ 82B5E26
	.string "성호: 앗 {PLAYER}!\p"
	.string "아무 말 안 해도 돼!\n"
	.string "아무튼 지금은...\p"
	.string "네가 생각하는 대로 나아가!$"
	// ダイゴ『あっ §あ§お!ｐ
	// なにも いわなくて いいよ!ｎ
	// とにかく いまは……ｐ
	// キミが おもうように すすむんだ!

MatchCall_Text_Steven6:: @ 82B5EA2
	.string "...... ...... ......\p"
	.string "성호에게는 호출이\n"
	.string "닿지 않는 것 같다...$"
	// …… …… ……ｐ
	// ダイゴには よびだしがｎ
	// つうじていない ようだ……

MatchCall_Text_Steven7:: @ 82B5ED9
	.string "성호: {PLAYER}...\n"
	.string "전당등록 축하해\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\p"
	.string "또 언젠가 만나면 좋겠다!$"
	// ダイゴ『§あ§お……ｎ
	// でんどういり おめでとうｐ
	// …… …… ……ｎ
	// …… …… ……ｐ
	// また いつか あえると いいね!

MatchCall_Text_BirchRegisterCall: @ 82B5F52
	.string "털보박사: 오오 {PLAYER}{K_AYA}!\n"
	.string "얘기는 이미 들었단다!\p"
	.string "네 포켓내비에 엔트리콜이\n"
	.string "장착되었다고 하더구나!\p"
	.string "그렇다면 나도 등록해 두렴!\p"
	.string "이걸로 너와 떨어져 있어도\n"
	.string "바로 포켓몬 도감의 평가를\l"
	.string "해줄 수 있겠구나!\p"
	.string "...... ...... ......$"
	// オダマキ『おお §あ§お!ｎ
	// はなしは すでに きいて いるよ!ｐ
	// きみの ポケナビに エントリ-コ-ルがｎ
	// セットされた らしいな!ｐ
	// ならば わたしも とうろく しておこう!ｐ
	// これで きみと はなれていてもｎ
	// すぐに ポケモンずかんの ひょうかをｌ
	// してあげられる からね!ｐ
	// …… …… ……

MatchCall_Text_RegisteredBirch: @ 82B603A
	.string "털보박사를\n"
	.string "포켓내비에 등록했다!$"

MatchCall_Text_UnusedProfBirch:
	.string "털보박사: 도감과 포켓내비가 있으면\n"
	.string "포켓몬 조사도\l"
	.string "더욱 즐거워지겠구나!$"
	// オダマキ『ずかんと ポケナビが あればｎ
	// ポケモンの ちょうさもｌ
	// より いっそう たのしくなるな!

MatchCall_Text_MrStone1:: @ 82B60C0
	.string "나발명: 오! {PLAYER}인가?\p"
	.string "이렇게 나를 호출했다는 건\n"
	.string "포켓내비가 잘 작동한다는 뜻이구나!\p"
	.string "나 말고도 다양한 사람들이\n"
	.string "등록되어 갈 테니까 계속\l"
	.string "호출해서 얘기해 보거라!\p"
	.string "좋아 좋아!\n"
	.string "기분이 좋아 보이는구나!\p"
	.string "...응? 어떻게 아냐고?\p"
	.string "그건... 사장실 창문에서\n"
	.string "자네를 내려다보고 있으니까지!\p"
	.string "와하하하! 그럼 나중에 보자꾸나!$"
	// ツワブキ『おっ! §あ§おか?ｐ
	// こうして わしを よびだした ってことはｎ
	// ポケナビの ちょうしは よさそうだな!ｐ
	// わしの ほかにも いろんな ひとがｎ
	// とうろく されて いくから どんどんｌ
	// よびだして はなしを すると いいぞ!ｐ
	// けっこう! けっこう!ｎ
	// うれしそうに しとる ようだな!ｐ
	// ……ん? なんで わかるのかって?ｐ
	// それは…… しゃちょうしつの まどからｎ
	// きみを みおろして いるからだよ!ｐ
	// わははは! じゃあ またな!

MatchCall_Text_MrStone2:: @ 82B61E6
	.string "나발명: 오! {PLAYER}인가?\p"
	.string "왜 그러냐! 내가 부탁한 일이\n"
	.string "뭐였는지 까먹은 건가?\p"
	.string "우선 무로마을에서 성호에게\n"
	.string "편지를 전해주게나!\p"
	.string "그 후 잿빛도시의 해양관장에게\n"
	.string "우리 회사의 화물을 전달하면 된단다!\p"
	.string "자 기억했니?\n"
	.string "난 바쁜 사장이니\l"
	.string "이만 실례하마!$"
	// ツワブキ『おっ! §あ§おか?ｐ
	// どうした! わしが たのんだ しごとｎ
	// わすれちゃったの かな?ｐ
	// まずは ムロタウンで ダイゴにｎ
	// てがみを わたしてくれ!ｐ
	// そのあと カイナシティの クスノキくんにｎ
	// わがしゃの にもつを とどけるんだ!ｐ
	// な? おぼえたかな?ｎ
	// わしは いそがしい しゃちょう だからねｌ
	// これで しつれい するよ!

MatchCall_Text_MrStone3:: @ 82B6302
	.string "나발명: 오! {PLAYER}!\p"
	.string "그런가 성호에게 전해줬구나!\n"
	.string "좋-아 답례로 선물을 주마!\p"
	.string "금탄도시에 올 일이 있다면\n"
	.string "내 방에 찾아오거라!\p"
	.string "그럼 기다리고 있으마!$"
	// ツワブキ『おっ! §あ§お!ｐ
	// そうか ダイゴに あえたのか!ｎ
	// よ-し おれいに プレゼントを やろう!ｐ
	// カナズミに くることが あったらｎ
	// わしの へやに よっていって おくれ!ｐ
	// じゃあな まっとるぞ!

MatchCall_Text_MrStone4:: @ 82B63A0
	.string "나발명: 오오! {PLAYER}!\p"
	.string "그래그래 금잔터널은\n"
	.string "우리 회사가 파고 있었는데\p"
	.string "그 주변에 서식하고 있는\n"
	.string "포켓몬을 보호하기 위해서\l"
	.string "공사를 중지했었단다\p"
	.string "뭐 인간의 편리함보다는\n"
	.string "포켓몬이 조용하게 사는 게\l"
	.string "중요하니까 말이지!$"
	// ツワブキ『おお! §あ§お!ｐ
	// そうそう カナシダトンネルはｎ
	// わがしゃが ほって いたんだけどねｐ
	// あの あたりに せいそく しているｎ
	// ポケモンを ほご するためにｌ
	// こうじは ちゅうし したんだよｐ
	// まあ にんげんの べんりさ よりはｎ
	// ポケモンが しずかに くらせるｌ
	// そのほうが だいじな ことだからね!

MatchCall_Text_MrStone5:: @ 82B64A2
	.string "나발명: 여어여어 {PLAYER}!\p"
	.string "등화도시의 사람한테서 들었는데\n"
	.string "자네가 종길씨의 자식이었군\p"
	.string "어쩐지 믿음직스럽다 했어!$"
	// ツワブキ『やあやあ §あ§お!ｐ
	// トウカシティの ひとから きいたんだけどｎ
	// きみは センリさんの こども なんだねｐ
	// どうりで たのもしいと おもったよ!

MatchCall_Text_MrStone6:: @ 82B6526
	.string "나발명: 에엑!\n"
	.string "자네가 자신의 아버지와\l"
	.string "포켓몬 승부를 해서 이겼다고?\p"
	.string "이거 놀랍군!\n"
	.string "나는 굉장한 사람과 친구가\l"
	.string "됐어! 와하하!$"
	// ツワブキ『ええっ!ｎ
	// きみは じぶんの おとうさんとｌ
	// ポケモンしょうぶを して かったのかい?ｐ
	// こりゃ びっくりだ!ｎ
	// わしは すごい ひとと ともだちにｌ
	// なっちゃったんだなあ! わはは!

MatchCall_Text_MrStone7:: @ 82B65BB
	.string "여보세요!\n"
	.string "데봉 코포레이션입니...\l"
	.string "아아 {PLAYER}씨였군요!\p"
	.string "사장님은 방금까지 계셨는데\n"
	.string "지금은 부재중이십니다!\p"
	.string "저희 사장님도 바쁘시지만\n"
	.string "{PLAYER}씨도 바쁜 것 같네요!$"
	// もしもし!ｎ
	// デボンコ-ポレ-ションで ございま……ｌ
	// ああ §あさん ですね!ｐ
	// しゃちょうは さっきまで いたんですけどｎ
	// いまは るすに してるんですよ!ｐ
	// うちの しゃちょうも いそがしいけどｎ
	// §あさんも いそがしそう ですね!

MatchCall_Text_MrStone8:: @ 82B6664
	.string "...에 ...무슨 일인가?\p"
	.string "그란... 뭐? ...돈?\p"
	.string "왠지 잘... 안 들리...\p"
	.string "지지지지직...... ...... ......$"
	// ……え ……なにかね?ｐ
	// グラ…… はい? ……ドン?ｐ
	// なんだか…… きこえな……ｐ
	// ザザザザザ…… …… ……

MatchCall_Text_MrStone9:: @ 82B66B1
	.string "...에 ...무슨 일인가?\p"
	.string "해저... 뭐? ...동굴?\p"
	.string "왠지 잘... 안 들리...\p"
	.string "지지지지직...... ...... ......$"
	// ……え ……なにかね?ｐ
	// かいて…… はい? ……どうくつ?ｐ
	// なんだか…… きこえな……ｐ
	// ザザザザザ…… …… ……

MatchCall_Text_MrStone10:: @ 82B6703
	.string "나발명: {PLAYER}! 나일세!\p"
	.string "왠지 여러 일이 있었던 것 같지만\n"
	.string "바쁜 나는 무슨 일이\l"
	.string "일어난 건지 전혀 모르겠네!\p"
	.string "아무튼 자네는 자신이 믿은\n"
	.string "길을 걸어나가게나!\p"
	.string "나도 뒤에서나마 응원할 테니!\n"
	.string "그럼 이만!$"
	// ツワブキ『§あ§お! わしだ!ｐ
	// なんだか いろいろ あった らしいがｎ
	// いそがしい わしにはｌ
	// なんの ことだか サッパリ わからん!ｐ
	// とにかく キミは じぶんの しんじたｎ
	// みちを あゆんで いきたまえ!ｐ
	// わしも カゲながら おうえん しとるぞ!ｎ
	// じゃあな!

MatchCall_Text_MrStone11:: @ 82B67ED
	.string "나발명: ...... ...... ......\n"
	.string "혹시 {PLAYER}인가?\p"
	.string "목소리에 자신감이 넘쳐서\n"
	.string "순간 다른 사람인 줄 알았네!\p"
	.string "그래! 가끔은 우리 회사에도\n"
	.string "놀러오게나!$"
	// ツワブキ『…… …… ……ｎ
	// もしかして §あ§お か?ｐ
	// こえに じしんが みなぎっていてｎ
	// いっしゅん ちがうひとかと おもったぞ!ｐ
	// うむ! たまには わがしゃにもｎ
	// あそびに きておくれ!
