MatchCall_WildBattleText1:: @ 82A971C
	.string "아! {PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지난번에 {STR_VAR_2}{K_EULREUL} 발견했는데\n"
	.string "잡지 못했어\p"
	.string "너무 아까운 거 있지-\n"
	.string "그럼 또 봐!$"
	// あ! §あ§お こんにちは!ｎ
	// §い ですｐ
	// このまえ §うを みつけたんだけどｎ
	// つかまえられなかったよｐ
	// おしかったな-ｎ
	// じゃあ またね!

MatchCall_WildBattleText2:: @ 82A9798
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지난번에 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\p"
	.string "도망쳐버렸어\n"
	.string "안타깝네\p"
	.string "그럼 또 봐!$"
	// こんにちは §あ§お!ｎ
	// §い ですｐ
	// このまえ §う をｎ
	// つかまえようと したんだけどｐ
	// にげられちゃったのｎ
	// ざんねん だったなあｐ
	// じゃあ またね!

MatchCall_WildBattleText3:: @ 82A9813
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "지난번에 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\l"
	.string "거의 다 된 상태에서 도망쳐버렸어!\p"
	.string "엄청 분했지...\n"
	.string "그럼 나중에 또 보자-$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// このまえ §う をｎ
	// つかまえようと したんだけどｌ
	// あとすこしの ところで にげられたんだ!ｐ
	// くやしかった なあ®®®ｎ
	// じゃあ またな-

MatchCall_WildBattleText4:: @ 82A98A8
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}{K_I}라는 포켓몬 알아?\n"
	.string "지난번에 조금만 더 했으면\p"
	.string "잡을 것 같았는데\n"
	.string "도망쳐버렸어\p"
	.string "다음번에 발견하면 반드시\n"
	.string "잡을 거야\p"
	.string "그럼 나중에 또 보자$"
	// やあ §あ§おｎ
	// §い だｐ
	// §うって ポケモン しってるかい?ｎ
	// このまえ あとすこしでｐ
	// つかまえられそう だったんだけどｎ
	// にげられて しまったよｐ
	// こんど みつけたら ぜったいｎ
	// つかまえて みせるよｐ
	// じゃあ またな

MatchCall_WildBattleText5:: @ 82A9977
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬 잡고 있어?\p"
	.string "나도 지난번에 조금만 더 하면\n"
	.string "잡을 것 같았는데\p"
	.string "도망쳐버렸지 뭐야\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あ§おｎ
	// §い だけどｌ
	// ポケモン つかまえてる?ｐ
	// おれも このまえ もうすこしでｎ
	// つかまえられそう だったけどｐ
	// にげられちゃったよｎ
	// じゃあ またな

MatchCall_WildBattleText6:: @ 82A99FD
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬 잡고 있어?\p"
	.string "난 지난번에 조금만 더 하면\n"
	.string "잡을 것 같았는데\p"
	.string "도망쳐버렸어\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あ§おｎ
	// §い だけどｌ
	// ポケモン つかまえてる?ｐ
	// おれも このまえ もうすこしでｎ
	// つかまえられそう だったけどｐ
	// にげられちゃったよｎ
	// じゃあ またな

MatchCall_WildBattleText7:: @ 82A9A78
	.string "...아 {PLAYER}?\n"
	.string "{STR_VAR_1}인데...\p"
	.string "아 잠깐 기다려!\n"
	.string "지금 {STR_VAR_2}{K_EULREUL} 잡으려고...\p"
	.string "아아아아 도망쳐버렸어-!\n"
	.string "거의 다 됐었는데!$"
	// ®®®あ §あ§お?ｎ
	// §い だけど®®®ｐ
	// あ ちょっと まって!ｎ
	// いま §うを つかまえ®®®ｐ
	// ああああ にげられた-!ｎ
	// もうすこし だったのに!

MatchCall_WildBattleText8:: @ 82A9AE8
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "그때 이후로 포켓몬 잡았어?\n"
	.string "난 지난번에 조금만 더 하면\p"
	.string "잡을 것 같았는데\n"
	.string "도망쳐버렸지 뭐야\p"
	.string "좀 더 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// あれから ポケモン つかまえた?ｎ
	// わたし このまえ もうすこしでｐ
	// つかまえられそう だったのにｎ
	// にげられちゃったｐ
	// もっと がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_WildBattleText9:: @ 82A9BA7
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "어때? 포켓몬 모으고 있어?\n"
	.string "나는 자꾸 도망쳐서\p"
	.string "전혀 못 잡고 있어\n"
	.string "그럼 또 봐!$"
	// あ §あ§お こんにちは-!ｎ
	// §い です!ｐ
	// どう? ポケモン あつまってる?ｎ
	// わたしは にげられて ばっかりでｐ
	// ぜんぜん うまく いかないのｎ
	// じゃあ またね!

MatchCall_WildBattleText10:: @ 82A9C36
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "조금만 더 하면 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡을 뻔했는데\l"
	.string "도망쳐버렸어\p"
	.string "좀 더 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちはｎ
	// §い よｐ
	// もうすこしで §う をｎ
	// つかまえられそう だったのにｌ
	// にげられちゃったｐ
	// もっと がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_WildBattleText11:: @ 82A9CC8
	.string "아아 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "잘 지내니?\p"
	.string "난 저번에 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\p"
	.string "도망쳐버렸어\n"
	.string "후우$"
	// ああ §あ§おｎ
	// §いだけどｌ
	// ちょうしは どうだい?ｐ
	// おれは このまえ §う をｎ
	// つかまえようと したんだけどｐ
	// にげられちゃったよｎ
	// がっくり

MatchCall_WildBattleText12:: @ 82A9D44
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬은 잡고 있나?\p"
	.string "나도 잡으려고 하는데\n"
	.string "좀처럼 잘 안 되네\p"
	.string "포켓몬의 길은\n"
	.string "심오하구먼$"
	// やあ §あ§おｎ
	// §い じゃがｌ
	// ポケモン つかまえとるかな?ｐ
	// わしも つかまえようと おもったがｎ
	// なかなか うまくいかんｐ
	// ポケモンの みちはｎ
	// おくが ふかいのう
	
MatchCall_WildBattleText13:: @ 82A9DD7
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "포켓몬은 잡고 있나?\p"
	.string "나도 잡으려고 하는데\n"
	.string "좀처럼 잘 안 되네\p"
	.string "포켓몬의 길은\n"
	.string "심오하구먼$"
	// やあ §あ§おｎ
	// §い じゃがｌ
	// ポケモン つかまえとるかな?ｐ
	// わしも つかまえようと おもったがｎ
	// なかなか うまくいかんｐ
	// ポケモンの みちはｎ
	// おくが ふかいのう

MatchCall_WildBattleText14:: @ 82A9E70
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "아까 {STR_VAR_2}{K_EULREUL}\n"
	.string "잡으려고 했는데\p"
	.string "도망쳐버렸어 아깝지!\n"
	.string "그럼 또 봐$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// さっき §うちゃんをｎ
	// つかまえようと したんだけどｐ
	// にげられちゃったのよ ざんねん!ｎ
	// じゃあ またね

MatchCall_WildBattleText15:: @ 82A9EFD
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "포켓몬을 잡으려고\n"
	.string "하는 중인데\l"
	.string "하나도 안 나와서 말이지-\l"
	.string "아저씨는 고생하는 중이란다\p"
	.string "곤란하네 정말-\n"
	.string "그럼 나중에 또 보자-$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// ポケモンを つかまえようとｎ
	// おもってるんだがｌ
	// みつからなくてさ-ｌ
	// おじさん こまってる とこなのよｐ
	// まいったな-ｎ
	// じゃあ またな-

MatchCall_NegativeBattleText1:: @ 82A9FAB
	.string "{PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "다른 사람이랑 승부를 했는데\n"
	.string "져버렸어 후우\p"
	.string "그럼 또 봐$"
	// §あ§お こんにちは!ｎ
	// §い です!ｐ
	// ほかのひとと しょうぶ したんだけどｎ
	// まけちゃったよ がっくしｐ
	// じゃあ またね

MatchCall_NegativeBattleText2:: @ 82AA028
	.string "{PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "나 있지\n"
	.string "그때 이후로 승부해 봤어\p"
	.string "하지만 아깝게\n"
	.string "저버렸지 아-아$"
	// §あ§お こんにちは!ｎ
	// §いよ!ｐ
	// わたし ねｎ
	// あれから また しょうぶ してみたのｐ
	// でも あとちょっとの ところでｎ
	// まけちゃった あ-あ

MatchCall_NegativeBattleText3:: @ 82AA099
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "승부에서 졌어-\n"
	.string "좀 더 키워야 하는 걸까-$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// しょうぶ に まけたよ-ｎ
	// もっと そだてないと だめだな-

MatchCall_NegativeBattleText4:: @ 82AA100
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "어제 또 승부해 봤는데\n"
	.string "역시 이기지 못했어\p"
	.string "좀 더 키울 필요가 있는 걸까\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あｎ
	// §い だｐ
	// きのう また しょうぶ してみたんだｎ
	// でも かてなかったよｐ
	// もっと そだてが ひつようだなｎ
	// じゃあ またな

MatchCall_NegativeBattleText5:: @ 82AA188
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내?\n"
	.string "난 승부를 해도\l"
	.string "잘 이기지 못하고 있어\p"
	.string "상태가 나쁜 것 같아\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あｎ
	// §い だよｐ
	// ちょうしは どうだい?ｎ
	// おれは しょうぶ してもｌ
	// あまり かてないんだよｐ
	// ちょうし わるいなあｎ
	// じゃあ またな

MatchCall_NegativeBattleText6:: @ 82AA214
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내니?\n"
	.string "난 승부를 해도\l"
	.string "잘 이기지 못하고 있어\p"
	.string "상태가 나쁜가봐\n"
	.string "그럼 나중에 또 보자$"
	// やあ §あｎ
	// §い だよｐ
	// ちょうしは どうだい?ｎ
	// おれは しょうぶ してもｌ
	// あまり かてないんだよｐ
	// ちょうし わるいなあｎ
	// じゃあ またな

MatchCall_NegativeBattleText7:: @ 82AA2A1
	.string "{STR_VAR_1}인데-\n"
	.string "요즘 어때?\p"
	.string "난 어제 승부에서 져서\n"
	.string "그것 때문에 머리가 꽉 찼어\p"
	.string "대책을 생각해야 하는데...\n"
	.string "그럼 또 보자$"
	// §い だけど-ｎ
	// さいきん どう?ｐ
	// きのう しょうぶに まけてさｎ
	// そのことで あたまが いっぱいなんだｐ
	// たいさく かんがえないと®®®ｎ
	// じゃあ また

MatchCall_NegativeBattleText8:: @ 82AA31B
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "나는 지난번에 승부에서\l"
	.string "져버렸어\p"
	.string "좀 더 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// ポケモンの ちょうしは どう?ｎ
	// わたしは このまえの しょうぶでｌ
	// まけちゃったｐ
	// もっと がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_NegativeBattleText9:: @ 82AA3A8
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야-\p"
	.string "있지- 들어봐 들어봐!\n"
	.string "저번에 포켓몬 승부를 했는데\p"
	.string "거의 다 됐는데 아깝게\n"
	.string "져버렸어-! 분해!$"
	// あ §あ§お こんにちは-!ｎ
	// §い で-すｐ
	// ね- きいて きいて!ｎ
	// このまえ ポケモン しょうぶ したんだけどｐ
	// あとちょっとの ところでｎ
	// まけちゃったのよ-! くやしい!

MatchCall_NegativeBattleText10:: @ 82AA442
	.string "어머 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "방금 승부를 했는데\n"
	.string "져버렸지 뭐야\p"
	.string "좀 더 포켓몬을 키워야겠어\n"
	.string "그럼 또 봐$"
	// あら §あ§おｎ
	// §い ですｐ
	// さっき しょうぶ したんだけどｎ
	// まけちゃったｐ
	// もっと ポケモン そだてないと だめねｎ
	// じゃあ またね

MatchCall_NegativeBattleText11:: @ 82AA4C5
	.string "여어 {PLAYER} 잘 지내?\n"
	.string "{STR_VAR_1}{K_I}야\l"
	.string "포켓몬의 상태는 어때?\p"
	.string "이쪽은 또 승부에서\n"
	.string "져버렸어\p"
	.string "그럼 또 보자$"
	// やあ §あ§お げんきかい?ｎ
	// §い だよｌ
	// ポケモンの ちょうしは どう?ｐ
	// こっちは また しょうぶにｎ
	// まけちゃったよｐ
	// じゃあ また

MatchCall_NegativeBattleText12:: @ 82AA520
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "승부는 하고 있느냐?\p"
	.string "나는 지난번에 져버려서\n"
	.string "또 포켓몬을\l"
	.string "키우고 있다네\p"
	.string "그럼 나중에 보세$"
	// やあやあ §あ§おｎ
	// §い じゃがｌ
	// しょうぶ しておるのかな?ｐ
	// わしのほうは このまえ まけてしまってｎ
	// また ポケモンをｌ
	// そだてておる ところじゃよｐ
	// では またな

MatchCall_NegativeBattleText13:: @ 82AA5AD
	.string "오오 {PLAYER}\n"
	.string "{STR_VAR_1}일세\p"
	.string "잘 지내는가?\n"
	.string "방금 전까지 포켓몬 승부를\l"
	.string "하고 있었다네\p"
	.string "{PLAYER}도 힘내게나\n"
	.string "그럼 또 보세$"
	// おお §あ§おｎ
	// §い じゃｐ
	// げんき かのう?ｎ
	// さっきまで ポケモン しょうぶをｌ
	// しておったよｐ
	// §あ§おも がんばるんじゃぞｎ
	// では またの

MatchCall_NegativeBattleText14:: @ 82AA64D
	.string "어머 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내니?\n"
	.string "가끔은 집에 돌아가보도록 해\l"
	.string "그럼 또 봐$"
	// あら §あ§おｎ
	// §い よｐ
	// ちょうしは どうなの?ｎ
	// たまには いえに かえらないと だめよｌ
	// じゃあ またね

MatchCall_PositiveBattleText1:: @ 82AA6AF
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "아까 승부를 했었는데\n"
	.string "이겼어! 이겼다고!\p"
	.string "내 {STR_VAR_2}{K_IGA}\n"
	.string "엄청 열심히 해줬어! 기쁘다-$"
	// こんにちは §あ§お!ｎ
	// §い です!ｐ
	// さっき しょうぶ したんだけどｎ
	// かったよ! かったよ!ｐ
	// ぼくの §う がｎ
	// すごく がんばったんだ! うれしいな-

MatchCall_PositiveBattleText2:: @ 82AA730
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "어제 승부를 했는데\n"
	.string "이겼어! 기뻐-!$"
	// こんにちは §あ§お!ｎ
	// §い です!ｐ
	// きのう しょうぶ したんだけどｎ
	// かったのよ! うれしい-!

MatchCall_PositiveBattleText3:: @ 82AA77A
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}라고\p"
	.string "상태는 어때?\n"
	.string "난 지난번에 승부를 했는데\l"
	.string "내 {STR_VAR_2}{K_IGA} 엄청 활약했어!\p"
	.string "다음에 {PLAYER}{K_WAGWA} 승부할 때는\n"
	.string "절대로 지지 않을 거야-!$"
	// お-っす §あ!ｎ
	// §い だぞｐ
	// ちょうしは どうだ?ｎ
	// おれも このまえ しょうぶ したんだけどｌ
	// おれの §うが だいかつやく さ!ｐ
	// つぎ §あと しょうぶ するときはｎ
	// ぜったい まけない からな-!

MatchCall_PositiveBattleText4:: @ 82AA81C
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "아까 승부했는데\n"
	.string "어떻게든 이길 수 있었어\p"
	.string "내 {STR_VAR_2}{K_IGA}\n"
	.string "엄청 열심히 해줬지$"
	// やあ §あｎ
	// §い だｐ
	// さっき しょうぶ したんだけどｎ
	// なんとか かつ ことが できたよｐ
	// ぼくの §うがｎ
	// すごく がんばったんだ

MatchCall_PositiveBattleText5:: @ 82AA88C
	.string "여어 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "상태는 어때?\n"
	.string "승부는 하고 있어?\p"
	.string "난 지난번에 이겼어!\n"
	.string "{STR_VAR_2}{K_IGA} 엄청 활약했거든!\p"
	.string "다음엔 너한테 이길 거야!\n"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §い だｐ
	// ちょうしは どうだい?ｎ
	// しょうぶ してる?ｐ
	// おれ このまえ かったよ!ｎ
	// §うが だいかつやく さ!ｐ
	// つぎこそ きみに かつからね!ｎ
	// じゃあ またね

MatchCall_PositiveBattleText6:: @ 82AA934
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내지?\n"
	.string "난 최근 상태가 좋아서\l"
	.string "아까도 승부에서 이겼어\p"
	.string "다음에 너하고 승부할 때는\n"
	.string "절대로 지지 않을 거야$"
	// やあ §あ§おｎ
	// §い だｐ
	// げんき かい?ｎ
	// おれは さいきん ちょうしが よくてｌ
	// さっきも しょうぶに かったところだｐ
	// つぎに きみと しょうぶ するときはｎ
	// ぜったいに まけないからな

MatchCall_PositiveBattleText7:: @ 82AA9D3
	.string "{PLAYER}?\n"
	.string "{STR_VAR_1}인데\p"
	.string "내 {STR_VAR_2} 강한가봐!\n"
	.string "아까도 승부에서 이겼거든!\p"
	.string "다음에 너하고 승부할 때가\n"
	.string "기대된다$"
	// §あ§お?ｎ
	// §い だけどｐ
	// ぼくの §う つよいわけよ!ｎ
	// さっきも しょうぶで かったわけよ!ｐ
	// つぎに きみと しょうぶ するのがｎ
	// たのしみだなあ

MatchCall_PositiveBattleText8:: @ 82AAA40
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내니?\n"
	.string "난 방금 승부에서 이겼어\p"
	.string "{STR_VAR_2}{K_IGA} 엄청 열심히 했지\n"
	.string "그럼 또 봐$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// げんき かしら?ｎ
	// わたしね さっき しょうぶ して かったのｐ
	// §う が とっても がんばったのよｎ
	// じゃあ またね

MatchCall_PositiveBattleText9:: @ 82AAAE4
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "내 쪽은 방금 승부해서\l"
	.string "막 이긴 참이야!\p"
	.string "내 {STR_VAR_2}{K_IGA}\n"
	.string "굉장한 활약을 했었지\p"
	.string "보여주고 싶었는데-\n"
	.string "그럼 또 봐!$"
	// こんにちは §あ§お!ｎ
	// §い で-す!ｐ
	// ポケモンの ちょうしは どう?ｎ
	// わたしのほうは さっき しょうぶしてｌ
	// かった ところよ!ｐ
	// わたしの §う がｎ
	// すごい かつやく だったのよｐ
	// みせたかったな-ｎ
	// じゃあ またね!

MatchCall_PositiveBattleText10:: @ 82AAB8C
	.string "어머 안녕 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "상태는 어때?\n"
	.string "내 포켓몬은 상태가 좋은 것 같아\p"
	.string "아까도 승부에서 이겼거든\n"
	.string "그럼 또 봐$"
	// あら こんにちは §あ§おｎ
	// §い よｐ
	// ちょうしは どうかしら?ｎ
	// わたしの ポケモン ちょうし いいみたいｐ
	// さっきも しょうぶで かてたのよｎ
	// じゃあ またね

MatchCall_PositiveBattleText11:: @ 82AAC25
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "포켓몬 승부는 하고 있니?\n"
	.string "아저씨는 오늘도 승부에서 이겼단다-\p"
	.string "상태가 너무 좋아 으하하하\n"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §い だよｐ
	// ポケモン しょうぶ してるかい?ｎ
	// おじさん きょうも しょうぶに かってね-ｐ
	// ちょうし いいんだよ がはははｎ
	// じゃあ またね

MatchCall_PositiveBattleText12:: @ 82AAC9D
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\p"
	.string "잘 지내고 있나?\n"
	.string "난 잘 지내고 있다네\p"
	.string "방금도 승부에서 이겼거든\n"
	.string "젊은 것들에게 아직 질 수는 없지!$"
	// やあ §あ§おｎ
	// §い じゃよｐ
	// げんきに してるかのう?ｎ
	// わしは げんき じゃぞｐ
	// さっきも しょうぶに かった ところじゃｎ
	// わかいもんには まだまだ まけんぞ

MatchCall_PositiveBattleText13:: @ 82AAD41
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\p"
	.string "잘 지내고 있나?\n"
	.string "난 잘 지내고 있다네\p"
	.string "방금도 승부에서 이겼거든\n"
	.string "젊은 것들에게 아직 질 수는 없지\p"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃよｐ
	// げんきに してるかのう?ｎ
	// わしは げんき じゃぞｐ
	// さっきも しょうぶに かった ところじゃｎ
	// わかいもんには まだまだ まけんぞｐ
	// じゃあ またのう

MatchCall_PositiveBattleText14:: @ 82AAE00
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "저번에 승부를 했는데\n"
	.string "내 {STR_VAR_2}{K_IGA} 대활약했어!\p"
	.string "{PLAYER}에게도 보여주고 싶었는데\n"
	.string "그럼 또 보자$"
	// §あ§お こんにちはｎ
	// §い よｐ
	// このまえ しょうぶ したんだけどｎ
	// わたしの §うが だいかつやく!ｐ
	// §あ§おにも みせたかったなｎ
	// じゃあ また

MatchCall_SameRouteBattleRequestText1:: @ 82AAE7F
	.string "{PLAYER}씨 안녕!\n"
	.string "{STR_VAR_1}{K_I}라구\p"
	.string "에! 지금 {STR_VAR_2}에 있는 거야?\n"
	.string "그럼 지금부터 승부하자!\l"
	.string "기다릴게! 그럼 안녕!$"
	// §あさん こんにちは!ｎ
	// §い だよｐ
	// え! いま §う に いるの?ｎ
	// じゃあ いまから しょうぶ しようよ!ｌ
	// まってるよ! じゃあね!

MatchCall_SameRouteBattleRequestText2:: @ 82AAEF1
	.string "{PLAYER}씨 안녕!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "에! 지금 {STR_VAR_2}에 있는 거야?\n"
	.string "그럼 지금부터 승부하지 않을래?\l"
	.string "기다릴게! 그럼 안녕!$"
	// §あさん こんにちは!ｎ
	// §い で-すｐ
	// え! いま §う に いるの?ｎ
	// じゃあ いまから しょうぶ しない?ｌ
	// まってるわよ! じゃあね!

MatchCall_SameRouteBattleRequestText3:: @ 82AAF69
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "오 지금 {STR_VAR_2}에 있다고?\n"
	.string "그럼 지금부터 승부하지 않을래?\p"
	.string "이번에야말로 지지 않을 거야!\n"
	.string "기다릴게- 그럼 안녕$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// お いま §うにいるのか?ｎ
	// じゃあ これから しょうぶ しないか?ｐ
	// こんどこそ まけない からな!ｎ
	// まってるぞ- じゃあな

MatchCall_SameRouteBattleRequestText4:: @ 82AB010
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지금 어디 있어?\n"
	.string "뭐? {STR_VAR_2}?\p"
	.string "그럼 지금부터 승부하지 않을래?\n"
	.string "기다릴게 그럼 안녕$"
	// やあ §あ§おｎ
	// §い だｐ
	// いま どこに いるんだい?ｎ
	// え §う?ｐ
	// じゃあ これから しょうぶ しないか?ｎ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText5:: @ 82AB076
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라구\p"
	.string "상태는 어때?\n"
	.string "뭐? 지금 {STR_VAR_2}에 있다고?\p"
	.string "그렇다면 지금부터 나하고\n"
	.string "승부해보지 않을래?\p"
	.string "기다릴게 그럼 안녕$"
	// やあ §あ§おｎ
	// §い だよｐ
	// ちょうしは どうだい?ｎ
	// え? いま §うに いるの?ｐ
	// それなら これから おれとｎ
	// しょうぶ してみないかい?ｐ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText6:: @ 82AB11A
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "헤에 지금 {STR_VAR_2}에 있구나\p"
	.string "그럼 지금부터 나하고\n"
	.string "승부하자\p"
	.string "기다릴게 그럼 안녕$"
	// やあ §あ§おｎ
	// §い だｐ
	// ポケモンの ちょうしは どうだい?ｎ
	// へえ いま §うに いるのかｐ
	// じゃあ これから おれとｎ
	// しょうぶ しようｐ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText7:: @ 82AB1B4
	.string "...아 {PLAYER}?\n"
	.string "{STR_VAR_1}인데...\p"
	.string "헤에- 지금 {STR_VAR_2}에 있다고?\n"
	.string "그럼 승부하자 지금부터\p"
	.string "내 포켓몬을 보여줄게\n"
	.string "그럼 기다리고 있는다$"
	// ®®®あ §あ§お?ｎ
	// §い だけど®®®ｐ
	// へ- いま §うに いるの?ｎ
	// じゃあ しょうぶ しよう これからｐ
	// おれの ポケモンを みせてあげるよｎ
	// じゃあ まってるよ

MatchCall_SameRouteBattleRequestText8:: @ 82AB23D
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내고 있니?\n"
	.string "어머 지금 {STR_VAR_2}에 있는 거구나\p"
	.string "그럼 지금부터\n"
	.string "나하고 승부하지 않을래?\p"
	.string "기다릴게 그럼 안녕!$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// あら いま §うに いるのねｐ
	// じゃあ これからｎ
	// わたしと しょうぶ しない?ｐ
	// まってるわよ じゃあね!

MatchCall_SameRouteBattleRequestText9:: @ 82AB2E9
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "잘 지내고 있어?\n"
	.string "어머 지금 {STR_VAR_2}에 있다고?\p"
	.string "그렇구나- 그럼 지금부터\n"
	.string "나하고 승부해보지 않을래?\p"
	.string "그럼 안녕 기다릴게$"
	// あ §あ§お こんにちは-!ｎ
	// §い です!ｐ
	// げんきに してる?ｎ
	// あら いま §うに いるの?ｐ
	// そっか- じゃあ これからｎ
	// わたしと しょうぶ してみない?ｐ
	// じゃあね まってるわよ

MatchCall_SameRouteBattleRequestText10:: @ 82AB382
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내고 있어?\n"
	.string "어머 지금 {STR_VAR_2}에 있다고\p"
	.string "그럼 지금부터\n"
	.string "나랑 승부하지 않을래?\p"
	.string "기다릴게 그럼 안녕!$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// あら いま §うに いるのねｐ
	// じゃあ これからｎ
	// わたしと しょうぶ しない?ｐ
	// まってるわよ じゃあね!

MatchCall_SameRouteBattleRequestText11:: @ 82AB410
	.string "아아 {PLAYER}\n"
	.string "{STR_VAR_1}인데\p"
	.string "호오\n"
	.string "지금 {STR_VAR_2}에 있다고?\p"
	.string "그럼 지금부터 아저씨하고\n"
	.string "포켓몬 승부하지 않을래?\p"
	.string "기다릴게 그럼 안녕$"
	// ああ §あ§おｎ
	// §いだけどｐ
	// ほほうｎ
	// いま §うに いるんだって?ｐ
	// じゃあ これから おじさんとｎ
	// ポケモン しょうぶ しないかい?ｐ
	// まってるよ じゃあね

MatchCall_SameRouteBattleRequestText12:: @ 82AB4B0
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\l"
	.string "지금 어디에 있는가?\p"
	.string "{STR_VAR_2}{K_I}라고! 가까이에 있구먼\n"
	.string "지금부터 나하고 승부하지 않겠나?\p"
	.string "기다리고 있겠네 그럼 이만$"
	// やあ §あ§おｎ
	// §い じゃがｌ
	// いま どこに いるのかな?ｐ
	// §う か! すぐ ちかく じゃなｎ
	// これから わしと しょうぶ せんか?ｐ
	// まっておるぞ じゃあの

MatchCall_SameRouteBattleRequestText13:: @ 82AB538
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내나?\p"
	.string "호오호오 지금 {STR_VAR_2}에 있는 겐가\n"
	.string "멀지도 않으니 이쪽에 와서\p"
	.string "한번 승부하지 않겠나?\n"
	.string "기다리고 있겠네 그럼 이만$"
	// やあ §あ§おｎ
	// §い じゃが げんきかのう?ｐ
	// ほうほう いまは §うに おるのかｎ
	// ちかいから こっちへ よってｐ
	// いちど しょうぶ して いかんかの?ｎ
	// まっておるぞ じゃあの

MatchCall_SameRouteBattleRequestText14:: @ 82AB5E4
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "어머 지금 {STR_VAR_2}에 있는 거야?\n"
	.string "엄청 가까이에 있네\p"
	.string "그럼 지금부터 아주머니랑\n"
	.string "포켓몬 승부해보지 않을래?\p"
	.string "기다리고 있을게 그럼 안녕$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// あら いま §うに いるの?ｎ
	// すぐちかくに いるのねｐ
	// じゃあ これから おばさんとｎ
	// ポケモンしょうぶ してみない?ｐ
	// まってるわよ じゃあね

MatchCall_DifferentRouteBattleRequestText1:: @ 82AB670
	.string "아! {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지금부터 나하고 승부할래?\n"
	.string "{STR_VAR_2}에서 기다리고 있을게!$"
	// あ! §あ§お!ｎ
	// §い ですｐ
	// これから ぼくと しょうぶ しない?ｎ
	// §う で まってるよ!

MatchCall_DifferentRouteBattleRequestText2:: @ 82AB6CD
	.string "아! {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "지금부터 나하고 승부해보지 않을래?\n"
	.string "{STR_VAR_2}에서 기다릴게!$"
	// あ! §あ§お!ｎ
	// §い ですｐ
	// これから わたしと しょうぶ してみない?ｎ
	// §う で まってるよ!

MatchCall_DifferentRouteBattleRequestText3:: @ 82AB73C
	.string "안녕 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "그때 이후로 내 포켓몬도\n"
	.string "믿음직해졌어!\p"
	.string "{PLAYER}의 포켓몬으로\n"
	.string "실력을 시험해보고 싶으니까\p"
	.string "승부해보지 않을래?\n"
	.string "{STR_VAR_2}에서 기다릴게$"
	// お-っす §あ!ｎ
	// §い だ!ｐ
	// あれから おれの ポケモンもｎ
	// たくましく なったぞ!ｐ
	// §あの ポケモンでｎ
	// うでだめし したいからｐ
	// しょうぶ してみないか?ｎ
	// §う で まってるぞ

MatchCall_DifferentRouteBattleRequestText4:: @ 82AB808
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\l"
	.string "상태는 어때?\n"
	.string "내 포켓몬도\l"
	.string "충분히 강해졌어\p"
	.string "승부하지 않을래?\n"
	.string "그럼 {STR_VAR_2}에서 보자$"
	// やあ §あ§おｎ
	// §い だｐ
	// ちょうしは どうだい?ｎ
	// おれの ポケモンもｌ
	// ずいぶん つよく なったよｐ
	// そうだ また おれとｎ
	// しょうぶ しないかい?ｐ
	// じゃあ §うで あおう

MatchCall_DifferentRouteBattleRequestText5:: @ 82AB8B7
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\p"
	.string "내 포켓몬\n"
	.string "제법 좋은 느낌으로 자란 것 같아\p"
	.string "너하고도 한 번 더\n"
	.string "승부해보고 싶어\p"
	.string "{STR_VAR_2}에서 기다리고 있을게\n"
	.string "그럼 안녕$"
	// やあ §あ§おｎ
	// §い だけどｐ
	// おれの ポケモンｎ
	// けっこう いいかんじに そだってきたよｐ
	// きみと もういちどｎ
	// しょうぶ してみたいなあｐ
	// §う で まってるよｎ
	// じゃあね

MatchCall_DifferentRouteBattleRequestText6:: @ 82AB95D
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "잘 지내고 있어?\p"
	.string "또 너하고 포켓몬 승부를\n"
	.string "해보고 싶은데 어때?\p"
	.string "승부하고 싶어지면\n"
	.string "{STR_VAR_2}에 와줘\p"
	.string "그럼 나중에 보자$"
	// やあ §あ§おｎ
	// §い だけどｌ
	// げんきで やってるかい?ｐ
	// また きみと ポケモンしょうぶをｎ
	// してみたいんだけど どうだい?ｐ
	// しょうぶ したくなったらｎ
	// §うに きてくれよｐ
	// じゃあ また

MatchCall_DifferentRouteBattleRequestText7:: @ 82ABA03
	.string "아 {PLAYER}?\n"
	.string "{STR_VAR_1}인데...\p"
	.string "어때? 포켓몬 키우고 있어?\n"
	.string "내 포켓몬도 강해졌으니까\l"
	.string "네게 보여주고 싶어\p"
	.string "{STR_VAR_2}에서 기다릴 테니까\n"
	.string "승부하러 와줘\p"
	.string "그럼 나중에 보자$"
	// あ §あ§お?ｎ
	// §い だけど®®®ｐ
	// どう? ポケモン そだってる?ｎ
	// ぼくの ポケモンも つよくなったからｌ
	// きみに みせたいなあｐ
	// §うで まってるからｎ
	// しょうぶ しに きてくれよｐ
	// じゃあ また

MatchCall_DifferentRouteBattleRequestText8:: @ 82ABA9F
	.string "아 {PLAYER} 안녕하세요\n"
	.string "{STR_VAR_1}입니다\p"
	.string "상태는 어떤가요?\n"
	.string "제 포켓몬은 무척 건강하답니다\p"
	.string "다음에 이쪽에 온다면\n"
	.string "또 저하고\l"
	.string "승부해 주셔야 돼요\p"
	.string "{STR_VAR_2}에서 기다리고 있어요\n"
	.string "그럼 나중에 봐요$"
	// あ §あ§お こんにちはｎ
	// §い ですｐ
	// ちょうしは どうですか?ｎ
	// わたしの ポケモンは とても げんきですよｐ
	// こんど こちらに いらしたらｎ
	// また わたしとｌ
	// しょうぶ してくださいねｐ
	// §うで まってますｎ
	// では また

MatchCall_DifferentRouteBattleRequestText9:: @ 82ABB62
	.string "아 {PLAYER} 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "포켓몬의 상태는 어때?\n"
	.string "내 포켓몬도\p"
	.string "점점 강해지고 있어\n"
	.string "{PLAYER}에게도 보여주고 싶네\p"
	.string "{STR_VAR_2}에 있을 테니까\n"
	.string "근처에 오면 승부라도 하자\p"
	.string "그럼 또 봐$"
	// あ §あ§お こんにちは-!ｎ
	// §い です!ｐ
	// ポケモンの ちょうしは どうかな?ｎ
	// わたしの ポケモンもｐ
	// どんどん つよく なってるのよｎ
	// §あ§おにも みせてあげたいなあｐ
	// §うに いるからｎ
	// ちかくに きたら しょうぶでも しようよｐ
	// じゃあ またね

MatchCall_DifferentRouteBattleRequestText10:: @ 82ABC26
	.string "아 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "어때? 잘 지내고 있어?\n"
	.string "그때 이후로 내 포켓몬도\l"
	.string "충분히 강해졌어\p"
	.string "또 {PLAYER}하고\n"
	.string "승부하고 싶은걸\p"
	.string "{STR_VAR_2}에 있을 테니까\n"
	.string "근처에 오면 만나러 와줘$"
	// あ §あ§お こんにちはｎ
	// §い よｐ
	// どう? げんきで やってるかしら?ｎ
	// あれから わたしの ポケモンもｌ
	// ずいぶん つよく なったのよｐ
	// また §あ§おとｎ
	// しょうぶ したいなあｐ
	// §うに いるからｎ
	// ちかくに きたら あいに きてね

MatchCall_DifferentRouteBattleRequestText11:: @ 82ABCE9
	.string "아아 {PLAYER}\n"
	.string "{STR_VAR_1}인데\l"
	.string "지금 어디에 있나?\p"
	.string "내 포켓몬은 건강하게 있다네\n"
	.string "{PLAYER}의 포켓몬과 만나는 걸\l"
	.string "기대하고 있는 모양이더군\p"
	.string "{STR_VAR_2}에 있을 테니\n"
	.string "꼭 만나러 와주게나$"
	// ああ §あ§おｎ
	// §いだけどｌ
	// いま どこに いるのかな?ｐ
	// わしの ポケモンは とても げんき だぞｎ
	// §あ§おの ポケモンと あうのをｌ
	// たのしみに しているみたいだｐ
	// §うに いるからｎ
	// ぜひ あいに きてくれよ

MatchCall_DifferentRouteBattleRequestText12:: @ 82ABDA2
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\p"
	.string "내 포켓몬도 그때 이후로\n"
	.string "충분히 믿음직해졌다네\p"
	.string "{PLAYER}의 포켓몬과\n"
	.string "한 번 더 겨뤄보고 싶구먼\p"
	.string "{STR_VAR_2}에서 기다릴 테니\n"
	.string "언제든지 와주게$"
	// やあ §あ§おｎ
	// §い じゃｐ
	// わしの ポケモンも あれからｎ
	// ずいぶんと たくましく なったぞｐ
	// §あ§おの ポケモンとｎ
	// もういちど てあわせ したいのうｐ
	// §うに おるからｎ
	// いつでも きてくれたまえ

MatchCall_DifferentRouteBattleRequestText13:: @ 82ABE5E
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}라네\p"
	.string "포켓몬은 건강하게 있나?\n"
	.string "내 포켓몬도\l"
	.string "지지 않을 만큼 건강하다네\p"
	.string "또 승부해보고 싶으니\n"
	.string "{STR_VAR_2} 근처에 온다면\p"
	.string "만나러 와주겠나\n"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃｐ
	// ポケモンは げんきに しとるかね?ｎ
	// わしの ポケモンもｌ
	// まけない ぐらい げんきに しておるよｐ
	// また しょうぶ してみたいのでｎ
	// §うの ちかくに きたらｐ
	// あいに きてくれんかのうｎ
	// では またの

MatchCall_DifferentRouteBattleRequestText14:: @ 82ABF36
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "잘 지내고 있니?\n"
	.string "아 맞다 맞다\p"
	.string "내 포켓몬\n"
	.string "그때 이후로 제법 강해졌어\p"
	.string "{PLAYER}{K_WAGWA} 한 번 더\n"
	.string "승부해보고 싶은걸\p"
	.string "{STR_VAR_2}에서 기다릴 테니까\n"
	.string "언제든지 만나러 와줘$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// げんきに してる?ｎ
	// あ そうそうｐ
	// わたしの ポケモンｎ
	// あれから けっこう つよく なったのよｐ
	// §あ§おと もういちどｎ
	// しょうぶ してみたいわねえｐ
	// §うで まってるからｎ
	// いつでも あいに きてね

MatchCall_PersonalizedText1:: @ 82AC009
	.string "산을 사랑하는 {STR_VAR_1}인데\p"
	.string "어떤가 그 후로\n"
	.string "조금은 산을 좋아하게 됐나?\l"
	.string "산에서 자네를 좀처럼 보는 것 같다만...\p"
	.string "좋아 다음은 {STR_VAR_2}에서\n"
	.string "만나도록 하지 그럼 또 보세!$"
	// やまを あいする §いだがｐ
	// どうだね あれからｎ
	// すこしは やまが すきに なったか?ｌ
	// あまり やまで きみを みかけないが……ｐ
	// よし つぎは §うでｎ
	// あおう じゃないか またな!

MatchCall_PersonalizedText2:: @ 82AC0BD
	.string "{STR_VAR_1}{K_I}야\n"
	.string "안녕\p"
	.string "지금 말이지 막 트레이너가 된 애한테\n"
	.string "너에 대해서 알려주고 있었어!\l"
	.string "포켓몬을 소중하게 키우고 있는\l"
	.string "강한 트레이너가 있다고 했지...\p"
	.string "모두가 동경할 만한\n"
	.string "굉장한 트레이너가 되어줘!\l"
	.string "그럼 나중에 또 만나자!$"
	// §いですｎ
	// こんにちはｐ
	// いまね トレ-ナ-に なりたてのコにｎ
	// あなたの ことを きかせて いたのよ!ｌ
	// ポケモンを たいせつに そだてているｌ
	// つよい トレ-ナ-が いるのよって……ｐ
	// みんなの あこがれに なるようなｎ
	// すばらしい トレ-ナ-に なってね!ｌ
	// じゃあ また あいましょう!

MatchCall_PersonalizedText3:: @ 82AC18C
	.string "안녕! {STR_VAR_1}{K_I}야\n"
	.string "이 주변에선 정말\l"
	.string "좋은 향기가 나서 기분이 좋아\p"
	.string "누군가가 나무열매를 심어서\n"
	.string "꽃을 피우게 한 걸까? 우후후\p"
	.string "그럼 다음에 봐!$"
	// こんにちは! §いよｎ
	// この あたりは ほんとうにｌ
	// いいかおりが して きもちがいいわｐ
	// だれかが きのみを うめてｎ
	// はなを さかせて くれたのかしら? うふふｐ
	// それじゃ またね!

MatchCall_PersonalizedText4:: @ 82AC228
	.string "예예! 유적을 찾아서 30년\n"
	.string "그게 바로 나 {STR_VAR_1}{K_I}라네\p"
	.string "자네는 적극적으로 이곳저곳을\n"
	.string "돌아다니는 모양이던데\l"
	.string "혹시 유적을 본 적은 없나?\l"
	.string "찾으면 알려주게!\p"
	.string "그럼 나는\n"
	.string "유적을 찾으러 이만$"
	// はいはい! いせきを さがして 30ねんｎ
	// わたし §いで ございますｐ
	// きみは せっきょくてきに あちこちをｎ
	// まわって いるよう だけどｌ
	// なにか いせきを みつけたかい?ｌ
	// みつけたら おしえて くれよ!ｐ
	// では わたしはｎ
	// いせきを さがすので これで

MatchCall_PersonalizedText5:: @ 82AC30C
	.string "{STR_VAR_1}{K_I}야-\n"
	.string "오늘은 말이지 모래사장에서\l"
	.string "바다를 바라보고 있었어!\p"
	.string "하-... 반짝반짝 물결이 빛나서\n"
	.string "여기서 보는 바다가 가장 예뻐!\l"
	.string "아- 배고프네 그럼 이만!$"
	// い で-すｎ
	// きょうはね すなはま からｌ
	// うみを ながめて いるんだ!ｐ
	// は-…… キラキラ なみが ひかってｎ
	// ここから みる うみが いちばん きれい!ｌ
	// あ- おなかすいた じゃあまたね!

MatchCall_PersonalizedText6:: @ 82AC3B6
	.string "우물우물...\n"
	.string "{STR_VAR_1}{K_I}야\l"
	.string "모래사장에서 먹는 주먹밥은 맛있네-\p"
	.string "으-음 나도 포켓몬도\n"
	.string "건강해졌어!\l"
	.string "그럼 수영하고 올게!$"
	// もぐもぐ……ｎ
	// あ §いですｌ
	// すなはまで たべる おにぎりは うまいな-ｐ
	// う-ん ぼくも ポケモンもｎ
	// げんきに なったぞ!ｌ
	// じゃ およいで くるね!

MatchCall_PersonalizedText7:: @ 82AC446
	.string "여어 {STR_VAR_1}인데...\p"
	.string "엘리트 트레이너의 생활에\n"
	.string "조금 지쳐버렸어...\p"
	.string "다들 나를\n"
	.string "완벽한 트레이너라고 생각하니까\l"
	.string "나도 그렇게 행동해야만 해\p"
	.string "하지만 이것도 엘리트 트레이너의\n"
	.string "숙명이라고 생각하고\l"
	.string "열심히 하기로 했어!\p"
	.string "이런 말을 할 수 있는 건 너뿐이야\n"
	.string "하지만 다음에 만날 때는\l"
	.string "약한 소리 안 할 테니까 안심해!\l"
	.string "그럼 안녕!$"
	// やあ §い だけど……ｐ
	// エリ-トトレ-ナ- の せいかつにｎ
	// ちょっと つかれちゃってね……ｐ
	// みんな ぼくのことをｎ
	// かんぺきな トレ-ナ-だと おもうからｌ
	// ぼくも それらしく しないと いけないｐ
	// でも それも エリ-トトレ-ナ-のｎ
	// しゅくめいだと おもってｌ
	// がんばる ことに するよ!ｐ
	// こんな ことが いえるのは キミだけだｎ
	// でも こんど あった ときはｌ
	// よわねは はかないから あんしんして!ｌ
	// じゃ!

MatchCall_PersonalizedText8:: @ 82AC5C7
	.string "얏호- {STR_VAR_1}{K_I}야\n"
	.string "안녕!\p"
	.string "지금 너를 목표로\n"
	.string "포켓몬을 키우고 있어!\l"
	.string "다음에 배틀할 때는\l"
	.string "절대로 지지 않을 거야! 후훗\p"
	.string "동료 트레이너가 있으니까 좋네\n"
	.string "또 만나자!$"
	// ヤッホ- §いよｎ
	// こんにちは!ｐ
	// いま あなたを めざしてｎ
	// ポケモンを そだてて いるの!ｌ
	// こんど たたかう ときはｌ
	// ぜったい まけない つもり! ふふっｐ
	// トレ-ナ- なかまが いるって いいよねｎ
	// また あいましょう!

MatchCall_PersonalizedText9:: @ 82AC682
	.string "{STR_VAR_1}인데...\n"
	.string "지금 네 뒤에...\l"
	.string "뭔가가 있지 않아...?\p"
	.string "이곳 송화산에 잠들어 있는\n"
	.string "포켓몬들의 힘이\l"
	.string "나한테 알려주고 있어...\l"
	.string "뒤돌아보지 말고 그대로\l"
	.string "똑바로 걷는 편이 좋을 거야...\p"
	.string "후후...\n"
	.string "그럼 이만...$"
	// §い ですけど……ｎ
	// いま あなたの うしろ……ｌ
	// なにかが いない……?ｐ
	// ここ おくりびやまで ねむっているｎ
	// ポケモンたちの ちからがｌ
	// わたしに おしえて くれるの……ｌ
	// ふりかえらないで そのままｌ
	// まっすぐ あるいたほうが いいわよ……ｐ
	// フフ……ｎ
	// それじゃあ さよなら……

MatchCall_PersonalizedText10:: @ 82AC755
	.string "나 {STR_VAR_1}{K_I}야\n"
	.string "잘 지내니?\p"
	.string "떨어져 있어도 이렇게\n"
	.string "얘기할 수 있으니까 편리하네\p"
	.string "여태까지는 만나고 싶은 사람이 있으면\n"
	.string "아빠한테 데려가달라고 했었거든...\p"
	.string "그럼 나중에 보자...\n"
	.string "얘기할 수 있어서 기뻤어$"
	// わたくし §いですわｎ
	// ごきげんようｐ
	// はなれていても こうしてｎ
	// おはなし できるなんて べんりねｐ
	// いままでは あいたい ひとが いたらｎ
	// パパに おくってもらって いたもの……ｐ
	// それではまた……ｎ
	// おはなし できて うれしかった ですわ

MatchCall_PersonalizedText11:: @ 82AC82C
	.string "{STR_VAR_1}{K_I}야\n"
	.string "잠깐 얘기 좀 들어봐!\p"
	.string "나 사파리존이 좋지만\n"
	.string "거기 있으면 반드시 헤매게 돼!\l"
	.string "풀만 엄청 자라있어서\l"
	.string "너무 넓은 거 있지-! 흥흥!\p"
	.string "아- 화냈더니 마음이 좀 놓이네\n"
	.string "잠깐 사파리존에라도 가야지!\n"
	.string "또 봐!$"
	// §いよｎ
	// ちょっと はなし ききなさいよ!ｐ
	// わたし サファリゾ-ンが すきなんだけどｎ
	// あそこに いくと かならず まようのよ!ｌ
	// くさ ばっかり はえててｌ
	// ちょっと ひろすぎるのよね-! ぷんぷん!ｐ
	// あ- おこったら きが すんだわｎ
	// ちょっと サファリゾ-ンでも いこっと!ｌ
	// またね!

MatchCall_PersonalizedText12:: @ 82AC914
	.string "여어\n"
	.string "돈 많은 {STR_VAR_1}인데\p"
	.string "나 그때 이후로 더욱더\n"
	.string "돈이 많아져버려서\l"
	.string "포켓몬도 더욱더 강해졌어\p"
	.string "이 세상은\n"
	.string "날 위해서 있는 게 아닐까?\p"
	.string "아아 대답하지 않아도 돼\n"
	.string "알고 있으니까!\l"
	.string "어이쿠 슬슬 디너 타임이네\l"
	.string "실례할게!$"
	// やあｎ
	// おかねもちの §い だけどｐ
	// ボク あれから ますますｎ
	// おかねもちに なっちゃったしｌ
	// ポケモンも ますます つよく なったよｐ
	// この せかいってｎ
	// ボクの ために あるんじゃない かな?ｐ
	// ああ へんじは しなくて いいよｎ
	// わかっている ことだからね!ｌ
	// おっと そろそろ ディナ-のじかんだｌ
	// しつれい するよ!

MatchCall_PersonalizedText13:: @ 82ACA59
	.string "우후후후후후후...\n"
	.string "나 나야 {STR_VAR_1}\p"
	.string "지금 눈앞에서\n"
	.string "{STR_VAR_2}끼리 싸우고 있어\l"
	.string "이긴 쪽을 잡을까?\l"
	.string "우후후후후...\p"
	.string "그 그럼 바쁘니까\n"
	.string "난 이만$"
	// うふふふふふふ……ｎ
	// ボ ボク §いですｐ
	// いま めのまえでｎ
	// §う どうしが たたかってるんだｌ
	// かった ほうを つかまえよう かな?ｌ
	// うふふふふ……ｐ
	// じ じゃ いそがしいからｎ
	// ボクは これで

MatchCall_PersonalizedText14:: @ 82ACB02
	.string "아 {STR_VAR_1}{K_I}야!\n"
	.string "슬슬 버려진 배도\l"
	.string "질리기 시작했어\p"
	.string "그래도 모처럼이기도 하고\n"
	.string "한 번은 널 이기고 싶어서\l"
	.string "당분간은 여기서 산책할 거야\l"
	.string "생각이 든다면 만나러 와!\p"
	.string "좋았어 오늘은\n"
	.string "옆방에 있는 아저씨에게\l"
	.string "승부를 걸어볼까?\p"
	.string "그럼 이만!$"
	// あ §いです!ｎ
	// そろそろ すてられぶね にもｌ
	// あきて きちゃった のよねｐ
	// でも せっかく だからｎ
	// いちどは キミに かって みたいしｌ
	// とうぶんは ここで さんぽ してるわｌ
	// きが むいたら あいに きてよね!ｐ
	// よし きょうは ついにｎ
	// となりの へやの おじさんにｌ
	// しょうぶを いどんで みようかな?ｐ
	// ではね!

MatchCall_PersonalizedText15:: @ 82ACC3F
	.string "바다의 사나이\n"
	.string "{STR_VAR_1}{K_I}다!\p"
	.string "역시나!\n"
	.string "커다란 바다에 있는 트레이너는\l"
	.string "강한 녀석들밖에 없어!\p"
	.string "너도 우리를 본받아\n"
	.string "바다에서 수행한다면 좋을 텐데...\l"
	.string "...이런 큰 파도가 올 거 같군!\p"
	.string "수행할 찬스야!\n"
	.string "미안하지만 나중에 봐!$"
	// うみの おとこｎ
	// §いだぜ!ｐ
	// やっぱさ!ｎ
	// でっかい うみに いる トレ-ナ-はｌ
	// つよいやつ ばっかりだぜ!ｐ
	// おまえも オレらを みならってｎ
	// うみで しゅぎょうすりゃ いいのによ……ｌ
	// ……と おおなみが きそうだ!ｐ
	// しゅぎょうの チャンスだぜ!ｎ
	// わるいけど またなっ!

MatchCall_PersonalizedText16:: @ 82ACD2F
	.string "{STR_VAR_1}{K_I}다!\n"
	.string "포켓몬에게 태권도를 가르쳤더니\l"
	.string "정말로 나보다 강해져버려서\l"
	.string "계속 지고 있다구!\p"
	.string "하지만 난 포켓몬한테 져도\n"
	.string "트레이너한테는 안 져!\l"
	.string "언젠가 또 나하고 승부하자!\l"
	.string "우가-!$"
	// §いだ!ｎ
	// ポケモンに カラテを おしえてたらｌ
	// ほんとに おれより つよくなっちまってｌ
	// おれ まけまくりだ!ｐ
	// だが おれは ポケモンに まけてもｎ
	// トレ-ナ- には まけん!ｌ
	// いつか また おれと しょうぶだ!ｌ
	// うが-!

MatchCall_PersonalizedText17:: @ 82ACE1E
	.string "{STR_VAR_1}인데\n"
	.string "그쪽의 여행은 어떤 느낌이야?\p"
	.string "...헤에- 과연 과연\n"
	.string "재밌을 거 같아!\l"
	.string "네 에피소드로\l"
	.string "한 곡 쓸 수 있겠는데!\p"
	.string "...옷 떠오른다\n"
	.string "좋은 가사가 떠오르기 시작했어!\p"
	.string "그럼 나 지금부터\n"
	.string "곡을 쓸 테니까 나중에 보자!$"
	// §いだけどｎ
	// そっちの たびは どんなカンジ?ｐ
	// ……へえ- なるほど なるほどｎ
	// たのしそうじゃん!ｌ
	// きみの エピソ-ドでｌ
	// 1きょく つくれそうだな!ｐ
	// ……おッ うかんできたｎ
	// いい フレ-ズ うかんできたよ!ｐ
	// じゃ オレ いまからｎ
	// きょくづくりに はいるから またな!

MatchCall_PersonalizedText18:: @ 82ACF32
	.string "{STR_VAR_1}인데...\n"
	.string "내 신곡을 들어줘\p"
	.string "랄라 {STR_VAR_2} {STR_VAR_2}\n"
	.string "왜 너는 {STR_VAR_2}인 거니\l"
	.string "왜 나는 {STR_VAR_2}{K_IGA}아닌 거니\l"
	.string "아- 랄랄라 {STR_VAR_2}{K_WAGWA} {STR_VAR_1}\l"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2} 랄라...\p"
	.string "페이드아웃...$"
	// §いだけど……ｎ
	// ボクの しんきょく きいてくれｐ
	// ルル §う §うｎ
	// どうして おまえは §うなんだｌ
	// どうして ボクは §うでは ないんだｌ
	// あ- ルルル §うと§いｌ
	// §いと§う ルル……ｐ
	// フェ-ドアウト……

MatchCall_PersonalizedText19:: @ 82ACFBE
	.string "캠핑의 달인\n"
	.string "{STR_VAR_1}{K_I}다!\p"
	.string "뭐 지난번에 내가 져버린 건\n"
	.string "내 전문이 캠핑이었으니까\l"
	.string "어쩔 수 없었던 거라구!\p"
	.string "이겨도 져도\n"
	.string "캠프에서 포켓몬 승부하는 게\l"
	.string "난 제일 좋아!\p"
	.string "다음에 또 상대를 부탁할게\n"
	.string "아 캠핑도 같이 하자!$"
	// キャンプの たつじんｎ
	// §い だ!ｐ
	// ま こないだ ぼくが まけちゃったのはｎ
	// ぼくの せんもんが キャンプだからねｌ
	// しかたが なかったのさ!ｐ
	// かっても まけてもｎ
	// キャンプで ポケモンしょうぶ するのｌ
	// ぼく だいすき なんだ!ｐ
	// またこんど あいてを たのむよｎ
	// あ キャンプも いっしょに しようぜ!

MatchCall_PersonalizedText20:: @ 82AD0AC
	.string "나야 나 {STR_VAR_1}!\p"
	.string "이야 나도 다른 산에\n"
	.string "올라가보고 싶은데 말이지-\l"
	.string "굴뚝산처럼\l"
	.string "예쁜 누나들이\l"
	.string "있는지 없는지 모르겠단 말이지-\p"
	.string "예쁜 누나들이 잔뜩 있는\n"
	.string "산이 있으면 알려주라!\p"
	.string "에헤헤헤 그럼 이만!$"
	// おれ おれ §い!ｐ
	// いやあ おれも ほかの やまにもｎ
	// のぼって みても いいんだけどさ-ｌ
	// えんとつやま みたいにｌ
	// きれいな おねいさん たちがｌ
	// いるか どうか わからんもんな-ｐ
	// きれいな おねいさんが いっぱいのｎ
	// やまが あったら おしえて くれよ!ｌ
	// えへへへ またなあ!

MatchCall_PersonalizedText21:: @ 82AD194
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "{STR_VAR_1}{K_I}야...\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "오늘은 그럼 이만...$"
	// …… …… ……ｎ
	// …… …… ……ｌ
	// §い です……ｐ
	// …… …… ……ｎ
	// …… …… ……ｌ
	// きょうは それだけ……

MatchCall_PersonalizedText22:: @ 82AD1DF
	.string "{STR_VAR_1}{K_I}야... 오늘은\n"
	.string "너하고 얘기하고 싶었어\p"
	.string "널 이기고 싶은 마음은\n"
	.string "날이 갈수록 강해질 뿐이야\l"
	.string "네게도 그런 상대가 있지?\l"
	.string "그게 나였으면 좋겠다\p"
	.string "얘기 들어줘서 고마워 또 봐!$"
	// §いだよ… きょうはｎ
	// きみと はなす きが してたんだｐ
	// きみに かちたい きもちはｎ
	// ひましに つよくなる ばかりだよｌ
	// きみ にも そんな あいてが いるだろ?ｌ
	// それが ぼくなら いいのになｐ
	// きいて くれて ありがと またな!

MatchCall_PersonalizedText23:: @ 82AD2A8
	.string "{STR_VAR_1}{K_I}야\p"
	.string "강한 트레이너가 근처에 있으면\n"
	.string "왠지 모르게 그 존재를\l"
	.string "느끼는 경우가 있어\p"
	.string "혹시 {PLAYER}{K_IGA}\n"
	.string "내 곁을 지나간 게 아닐까?\p"
	.string "만나러 와주길\n"
	.string "기다리고 있을게! 바-이!$"
	// §いですｐ
	// つよい トレ-ナ-が ちかくに いるとｎ
	// なんとなく その そんざいをｌ
	// かんじる ことが あるのｐ
	// もしかしたら §あ§おがｎ
	// わたしの そばを とおったの かもね?ｐ
	// あいに きて くれるのをｎ
	// まっているわ! バ-イ!

MatchCall_PersonalizedText24:: @ 82AD34F
	.string "{STR_VAR_1}입니다\n"
	.string "{PLAYER}{K_EUNNEUN} 건강한 것 같군요\p"
	.string "세계 각국을 돌아본 저지만\n"
	.string "이 지방이 매우 마음에 들어서\l"
	.string "당분간 머무를 생각입니다\p"
	.string "그렇게 됐으니\n"
	.string "또 만날 수 있을지도 모르겠군요\p"
	.string "당신의 훌륭한 기술\n"
	.string "잊지 못할 겁니다\p"
	.string "나중에 또 상대를 부탁드리죠$"
	// §いですｎ
	// §あ§おは げんきそう ですなｐ
	// せかい かっこくを まわった わたしですがｎ
	// この ちほうを たいへん きにいりましたｌ
	// とうぶん いる つもりですよｐ
	// そういう わけ ですからｎ
	// また あえるかも しれませんねｐ
	// あなたの みごとな わざｎ
	// わすれては おりませんよｌ
	// また おあいてを おねがいしますね

MatchCall_PersonalizedText25:: @ 82AD44E
	.string "훌쩍... {STR_VAR_1}...{K_I}야\n"
	.string "...훌쩍\p"
	.string "오늘 원규씨한테\n"
	.string "혼나버렸어\p"
	.string "그래도 내가 잘못한 거니까\n"
	.string "원규씨는 나한테\l"
	.string "제대로 가르쳐주시니까\l"
	.string "원망하지 않을 거야!\p"
	.string "내일도 또 가겠어\n"
	.string "트레이너스쿨! 에헤...\l"
	.string "그럼 또 봐!$"
	// グスン §い……ですｎ
	// ……グスンｐ
	// きょう ツツジさんにｎ
	// おこられ ちゃったｐ
	// でも ツツジさんはｎ
	// なんで ボクが わるいのかｌ
	// ちゃんと おしえて くれるからｌ
	// うらんだり しないよ!ｐ
	// あしたも また いくんだｎ
	// トレ-ナ-ズ スク-ル! えへ……ｌ
	// じゃ またね!

MatchCall_PersonalizedText26:: @ 82AD53A
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "어제 원규님하고\n"
	.string "승부했어!\p"
	.string "결과는 참담했지만...\n"
	.string "원규님이 내 상대를\l"
	.string "해주겠다고 하신 게\l"
	.string "무척 기뻤어!\l"
	.string "더욱더 동경하게 돼!\p"
	.string "지금부터 다시 공부할 거야!\n"
	.string "그러니까 안녕!$"
	// い です!ｐ
	// きのう ツツジさまにｎ
	// しょうぶ してもらったの!ｐ
	// けっかは さんざん だったけど……ｎ
	// ツツジさまが あたしの あいてをｌ
	// してくれた って いうことがｌ
	// すごく うれしいの!ｌ
	// ますます あこがれちゃうわ!ｐ
	// いまから また もうべんきょうよ!ｎ
	// だから さよなら!

MatchCall_PersonalizedText27:: @ 82AD642
	.string "미호야-!\n"
	.string "오늘도 후배인 리코하고 같이 있어\p"
	.string "정말! 리코도 포켓몬도\n"
	.string "귀여워서 어쩔 수 없다니까\l"
	.string "남동생이나 여동생처럼\l"
	.string "쭈-욱 돌봐주고 싶어!\p"
	.string "아 리코!\n"
	.string "빵 사온 거야?\p"
	.string "에? 뭐 뭐야\n"
	.string "심부름꾼처럼 부린 적 없어!\l"
	.string "포켓몬 승부에서 졌으니까\l"
	.string "벌칙으로 갔다 오기로 한 거잖아!\p"
	.string "귀여운 리코를\n"
	.string "내가 왜 부려먹겠어!\l"
	.string "그럼 지금부터 간식 먹을 거니까 끊을게!$"
	// ミホで-す!ｎ
	// きょうも こうはいの リコと いっしょだよｐ
	// もうね! リコも ポケモンもｎ
	// かわいくて しかたないのｌ
	// おとうとや いもうと みたいにｌ
	// ず-っと めんどう みて あげたいな!ｐ
	// あ リコ!ｎ
	// パン かってきて くれた?ｐ
	// え? な なによｎ
	// つかいっぱしり なんて させてないわよ!ｌ
	// ポケモン しょうぶで まけたからｌ
	// これは ばつゲ-ムなの!ｐ
	// かわいい リコをｎ
	// こきつかうわけ ないでしょ!ｌ
	// じゃ これから おやつだから バイバイ!

MatchCall_PersonalizedText28:: @ 82AD801
	.string "포켓몬 너무 좋아!\n"
	.string "애호가클럽의 {STR_VAR_1}{K_I}라네!\p"
	.string "드 들어보게나!\n"
	.string "내 포켓몬이 무려...!\l"
	.string "후훗 후후후훗\l"
	.string "이 이상은 비밀이라네!\l"
	.string "아- 너무 귀여워서 말로는 못 하겠군!\p"
	.string "아앗 {STR_VAR_2}{K_IGA}\n"
	.string "포켓몬스넥을 달라고 하잖아-!\l"
	.string "귀여워---!\p"
	.string "미안하지만 자네하고\n"
	.string "얘기하고 있을 때가 아니야!\l"
	.string "다음에 또 이어서 들어주게!$"
	// ポケモン だいすき!ｎ
	// だいすきクラブの §いです!ｐ
	// きっ きいて くださいよ!ｎ
	// わたしの ポケモンちゃんが なんと……!ｌ
	// ぐふ ぐふふふｌ
	// これいじょうは ひみつ!ｌ
	// も- かわいすぎて くちに できない!ｐ
	// ああっ §うちゃんがｎ
	// ポロックを おねだりしてる-!ｌ
	// かわいいぞ---っ!ｐ
	// わるいけど きみとｎ
	// はなしている ばあいじゃ ないぞ!ｌ
	// また こんど つづきを きいてくれ

MatchCall_PersonalizedText29:: @ 82AD92E
	.string "오호호!\p"
	.string "포켓몬을 자랑하고 싶어서 참을 수 없는\n"
	.string "{STR_VAR_1}{K_I}랍니다!\p"
	.string "당신 들어주세요\n"
	.string "제 {STR_VAR_2}...\l"
	.string "다른 사람이 안으면\l"
	.string "뿅 하고 도망쳐서\l"
	.string "제 품으로 뛰어든답니다!\p"
	.string "정말... 정말!\n"
	.string "이런 행복이 또 있을까요!\p"
	.string "아아 행복해요\n"
	.string "당신에게도 행복을\l"
	.string "나눠줄 수 있어서 다행이에요!\l"
	.string "그럼 실례할게요$"
	// おほほ!ｐ
	// ポケモンを じまん したくて しかたないｎ
	// §い ですわ!ｐ
	// あなた おききに なってｎ
	// あたくしの §うちゃん……ｌ
	// ほかの ひとに だっこされるとｌ
	// ピョンと にげだしてｌ
	// あたくしの むねに とびこんでくるの!ｐ
	// もう…… もう!ｎ
	// こんな しあわせって ほかに あるかしら!ｐ
	// ああ しあわせだわｎ
	// あなたにも しあわせを わけて あげられてｌ
	// よかったわ!ｌ
	// では しつれい するわね

MatchCall_PersonalizedText30:: @ 82ADA8F
	.string "난... {STR_VAR_1}{K_I}라네\p"
	.string "사람은 날 달인이라고 부르지\n"
	.string "하지만 난 알고 있네\l"
	.string "내 힘만으로는\l"
	.string "달인이 될 수 없다는 것을\p"
	.string "포켓몬의 힘이 있어야\n"
	.string "트레이너는 달인이 될 수 있어!\p"
	.string "음...! 나는 지금\n"
	.string "굉장히 좋은 말을 한 것 같군!\l"
	.string "기분이 좋으니 이대로 끊겠네!$"
	// わたしは…… §いだｐ
	// ひとは わたしを たつじんと よぶｎ
	// だが わたしは わかっているｌ
	// わたしだけの ちから ではｌ
	// たつじん には なれない ことをｐ
	// ポケモンの ちからが あってこそｎ
	// トレ-ナ-は たつじんに なれる!ｐ
	// うむ……! わたしは いまｎ
	// すごく いいことを いった きがする!ｌ
	// きもちがよい ままに わかれよう!

MatchCall_PersonalizedText31:: @ 82ADB9B
	.string "{STR_VAR_1}{K_I}라네\n"
	.string "온천에 들어가서 기분이 좋구먼\l"
	.string "이렇게 얘기할 수 있어서 기쁘다네!\p"
	.string "그때 이후로 몇 명 정도\n"
	.string "젊은 트레이너와 배틀해봤지만\l"
	.string "자네가 제일 강했구먼!\p"
	.string "분명 나이를 먹는다면\n"
	.string "달인이 될 게야!\l"
	.string "오호호호...$"
	// §い じゃよｎ
	// おんせんに つかって ごきげんだからねぇｌ
	// こうして おはなし できて うれしいよ!ｐ
	// あれから なんにんかｎ
	// わかい トレ-ナ-さんと たたかったがｌ
	// おまえさんが いちばん つよかったよ!ｐ
	// きっと としを とったらｎ
	// たつじんに なるじゃろうな!ｌ
	// おっほっほっほ……

MatchCall_PersonalizedText32:: @ 82ADC92
	.string "와아-! {STR_VAR_1}입니다-!\n"
	.string "잘 지내고 있어-?\p"
	.string "내가 포켓몬 승부에서 이겼을 때\n"
	.string "기분 탓일지도 모르지만\l"
	.string "반바지의 상태가 좋아!\p"
	.string "에 무슨 말이냐고?\n"
	.string "으-음 잘 설명은 못 하겠지만\l"
	.string "뭐라고 해야 할까...\l"
	.string "느낌이 보송보송해져!\p"
	.string "그리고 {PLAYER}하고 승부할 때는\n"
	.string "끈적끈적해진단 말이지...\p"
	.string "...... ...... ......\n"
	.string "내 얘길 믿은 거야?\l"
	.string "에헤헤헤 그럼 바이바이-!$"
	// わ-い! §いで-す!ｎ
	// げんき-?ｐ
	// ボクが ポケモン かてる ときってｎ
	// きのせいかも しれないけどｌ
	// たんパンの ちょうしが いいんだ!ｐ
	// え どういうこと かって?ｎ
	// う-ん うまく せつめい できないけどｌ
	// なんていう のかな……ｌ
	// はき ごこちが サラっと してるんだ!ｐ
	// で §あ§おと しょうぶの ときはｎ
	// だいたい ベタっと してるんだよね……ｐ
	// …… …… ……ｎ
	// ボクの はなし しんじた?ｌ
	// えへへへ じゃあね バイバ-イ!

MatchCall_PersonalizedText33:: @ 82ADE08
	.string "어-이!\n"
	.string "{STR_VAR_1}{K_I}야!\l"
	.string "오늘도 호쾌하게\l"
	.string "낚시를 즐기고 있다고-!\p"
	.string "바다나 강 말고도\n"
	.string "낚시할 수 있는 장소는 없을까-?\l"
	.string "어디서나 낚시를 하고 싶어서\l"
	.string "근질근질해-!\p"
	.string "이런 낚싯줄이 엉켰잖아!\n"
	.string "그럼 낚시할 수 있는 곳\l"
	.string "찾아봐 줘-! 또 보자-!$"
	// うお-い!ｎ
	// §いだぞ-っ!ｌ
	// きょうも ごうかいにｌ
	// つりを たのしんで いるぞ-っ!ｐ
	// うみ か かわ いがいにｎ
	// つりが できる ばしょって ないか-っ?ｌ
	// どこでも つりが したくってｌ
	// うずうずするんだ-っ!ｐ
	// おっと つりいとが からまった!ｎ
	// じゃ つりが できるところｌ
	// さがしといてくれ-っ! またな-っ!

MatchCall_PersonalizedText34:: @ 82ADF07
	.string "여어! {STR_VAR_1}인데\n"
	.string "느긋할 때 어떻게 지내?\p"
	.string "난 말이지 옛날부터\n"
	.string "초조해하거나 바쁜 게\l"
	.string "싫었거든\l"
	.string "그런데도 어째서인지\l"
	.string "트라이애슬리트를 하고 있지...\p"
	.string "인생은 뭐가 일어날지\n"
	.string "모른다는 거야! 하하\p"
	.string "너도 지금은 트레이너지만\n"
	.string "장래엔 선생님이라든지 화가라든지\l"
	.string "예상도 하지 못한 일을\l"
	.string "하고 있을지도 모르지!\p"
	.string "뭐- 느긋하게 해!\n"
	.string "그럼 또 봐-$"
	// やあ! §い だけどｎ
	// どう のんびり やっている かい?ｐ
	// ボクはさ むかしからｎ
	// あせったり いそいだり するのがｌ
	// にがて なんだよねｌ
	// それでも なぜか いまはｌ
	// トライアスリ-トを やっている……ｐ
	// じんせい なにが おこるかｎ
	// わからないって ヤツだな! ははｐ
	// キミも いまは トレ-ナ-だけどｎ
	// しょうらいは せんせい とか えかき とかｌ
	// よそうも つかない ことをｌ
	// やって いるの かもな!ｐ
	// ま- のんびり やれよ!ｎ
	// じゃあな-

MatchCall_PersonalizedText35:: @ 82AE0D9
	.string "{STR_VAR_1}{K_I}야!\n"
	.string "지금 자전거를 타고 있어!\p"
	.string "난 수영도 달리기도 좋아하지만\n"
	.string "자전거 타는 게 제일 좋아!\l"
	.string "왜냐하면 몸으로 바람을\l"
	.string "잔뜩 느낄 수 있잖아!\l"
	.string "공중날기처럼 기분이 좋단 말이지!\p"
	.string "좋-았어 오늘은 사이클링 로드에서\n"
	.string "신기록을 반드시 세울 거야!\l"
	.string "너도 도전하러 와!\l"
	.string "그럼 나중에 보자-$"
	// §いよ!ｎ
	// いま じてんしゃに のっているわ!ｐ
	// わたし すいえいも はしるのも すきだけどｎ
	// じてんしゃが いちばん すきなの!ｌ
	// だって からだに かぜをｌ
	// たくさん かんじる ことが できるでしょ?ｌ
	// そらをとぶ みたいで きもちいいのよ!ｐ
	// よ-し きょうこそ サイクリングロ-ドでｎ
	// しんきろくを だすわっ!ｌ
	// あなたも ちょうせん しに きなさいよ!ｌ
	// じゃあね-っ

MatchCall_PersonalizedText36:: @ 82AE1FD
	.string "요! 한창 트라이애슬리트를 하고 있는\n"
	.string "{STR_VAR_1}인데\l"
	.string "한번 잡담이라도 하자!\p"
	.string "포켓몬과 같이 땀을 흘리면\n"
	.string "엄청 기분이 좋다고!\l"
	.string "말은 할 수 없어도\l"
	.string "둘의 마음이 통하는\l"
	.string "그 기분은 감동적이란 말이지!\p"
	.string "하아하아... 달리면서 얘기하니까\n"
	.string "체력이 금방 닳네!\l"
	.string "하아하아 미안하지만 끊을게!$"
	// よお! トライアスロンの まっさいちゅうのｎ
	// §いだけどｌ
	// さくっと せけんばなし でも どうだい!ｐ
	// ポケモンと いっしょに あせを ながすとｎ
	// すごく きもちいいぜ!ｌ
	// ことばに ださなくったってｌ
	// ふたりの こころが つうじあうんだｌ
	// あれは ちょっと かんどう するなあ!ｐ
	// はあはあ… はしりながら はなしてたらｎ
	// たいりょくが なくなった!ｌ
	// はあはあ わるいけど こんどな!

MatchCall_PersonalizedText37:: @ 82AE327
	.string "안녕 {STR_VAR_1}{K_I}야\n"
	.string "지구력을 키우려면\l"
	.string "역시 높은 곳이 좋지!\p"
	.string "산꼭대기에서\n"
	.string "달리고 있으면\l"
	.string "금방 숨이 차!\p"
	.string "그래 나도 숨이 찰 것 같아\n"
	.string "그럼 또 보자!$"
	// こんにちは §いよｎ
	// じきゅうりょく を つけるにはｌ
	// やっぱり たかい ところが いいわね!ｐ
	// やまの てっぺん とかでｎ
	// はしり まわるとｌ
	// すぐに いきが きれるのよ!ｐ
	// ああ わたしも いきが きれそうｎ
	// じゃあ またね!

MatchCall_PersonalizedText38:: @ 82AE3DA
	.string "응 {STR_VAR_1}{K_I}야\n"
	.string "그로부터 꽤나 수영했는데도\l"
	.string "그랜드시티엔 아직 도착하지 못했어\p"
	.string "혹시 같은 곳을\n"
	.string "빙빙 돌고 있는 걸까\p"
	.string "아니 설마 그럴 리는 없겠지\n"
	.string "와하하하하\l"
	.string "그럼 또 봐!$"
	// ああ §い ですｎ
	// あれから だいぶ およいだけどｌ
	// サイユウシティには まだ つかないのかなあｐ
	// もしかして おなじ ところをｎ
	// ぐるぐる まわってるだけ だったりしてｐ
	// いや まさか そんなこと ないよなｎ
	// わははははｌ
	// じゃあ また!

MatchCall_PersonalizedText39:: @ 82AE489
	.string "네 {STR_VAR_1}입니...\n"
	.string "풍덩\p"
	.string "첨벙첨벙첨벙...\p"
	.string "푸악-\p"
	.string "털털\p"
	.string "...미 미안!\n"
	.string "지금 오일을 바르고\l"
	.string "포켓내비를 들었더니\l"
	.string "바다에 떨어뜨려 버렸어!\p"
	.string "바다에 떨어뜨려도 고장나지 않는다니\n"
	.string "데봉의 포켓내비는 굉장한걸-!\l"
	.string "그럼 일광욕을 계속해야 되니까\n"
	.string "다음에 얘기하자!$"
	// ああ §い ですけ……ｐ
	// ボチャンｐ
	// ブクブクブク………ｐ
	// ザバ-ｐ
	// ブンブンｐ
	// ……ごッ ごめん!ｎ
	// いま オイルを ぬった てでｌ
	// ポケナビを もってたらｌ
	// うみに おとして しまったんだ!ｐ
	// うみに おとしても こわれないなんてｎ
	// デボンの ポケナビって すげ-な!ｌ
	// じゃ にっこうよくの つづきを するんでｌ
	// またこんど はなそうぜ!

MatchCall_PersonalizedText40:: @ 82AE5CD
	.string "트라이애슬리트 중에서도\n"
	.string "수영을 제일 좋아하는 {STR_VAR_1}입니다\p"
	.string "하지만 너무 길게\n"
	.string "바다에 있으면\l"
	.string "몸이 불어나진 않을까\p"
	.string "역시 트라이애슬론은\n"
	.string "가혹한 레이스야!\l"
	.string "그럼 또 봐!$"
	// トライアスロンの なかでもｎ
	// すいえいが だいすきな §い ですｐ
	// でも あんまり ながいことｎ
	// うみに いるとｌ
	// からだが ふやけちゃわないかなあｐ
	// やっぱり トライアスロンはｎ
	// かこくな レ-スよね!ｌ
	// じゃ またね!

MatchCall_PersonalizedText41:: @ 82AE698
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "네 포켓몬의\n"
	.string "상태는 어때?\p"
	.string "내 드래곤포켓몬들도\n"
	.string "상태가 좋은가봐\l"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §いだｐ
	// きみの ポケモンのｎ
	// ちょうしは どうだい?ｐ
	// ぼくの ドラゴンポケモンたちもｎ
	// ちょうし よさそうだよｌ
	// じゃあ また

MatchCall_PersonalizedText42:: @ 82AE704
	.string "{STR_VAR_1}{K_I}야\n"
	.string "내 {STR_VAR_2}\l"
	.string "그때 이후로 한 단계 더 강해졌어!\p"
	.string "다음에 너와 승부할 때는\n"
	.string "지지 않을 거야!\p"
	.string "그럼 또 봐!$"
	// §いだｎ
	// おれの §うｌ
	// あれから いちだんと つよくなったぜ!ｐ
	// つぎ キミと しょうぶ するときはｎ
	// まけない からな!ｐ
	// じゃあ またな!

MatchCall_PersonalizedText43:: @ 82AE78F
	.string "{STR_VAR_1}{K_I}오\n"
	.string "숨는 방법의 연구를\l"
	.string "계속하고 있는데\p"
	.string "너무 잘 숨으면\n"
	.string "아무도 찾지 못한다네\l"
	.string "그건 조금 외롭단 말이지\p"
	.string "그럼 다음에 보세!$"
	// §いで ござるｎ
	// かくれかたの けんきゅうをｌ
	// つづけて いるんだけどｐ
	// うまく かくれすぎるとｎ
	// だれにも みつけて もらえないで ござるｌ
	// それは ちょっと さびしいで ござるなあｐ
	// それでは これにて どろん!

MatchCall_PersonalizedText44:: @ 82AE859
	.string "{STR_VAR_1}{K_I}야\n"
	.string "그때 이후로 수행을 거듭해서\p"
	.string "내 {STR_VAR_2}도\n"
	.string "제법 강해졌어\p"
	.string "역시 모래사장에서의 수행은\n"
	.string "효과적이야!\l"
	.string "그럼 또 봐!$"
	// いよｎ
	// あれから しゅぎょうを かさねてｐ
	// わたしの §うもｎ
	// けっこう つよく なってきたわよｐ
	// やっぱり すなはまでの しゅぎょうはｎ
	// こうかてき だわ!ｌ
	// じゃあ また!

MatchCall_PersonalizedText45:: @ 82AE8E6
	.string "안녕 {STR_VAR_1}{K_I}야\n"
	.string "화산재는 언제쯤\l"
	.string "그만 내릴까\p"
	.string "너무 쌓여버리면\n"
	.string "파라솔의 무늬가\l"
	.string "안 보이게 될 텐데...\p"
	.string "그럼 나중에\n"
	.string "만나자$"
	// こんにちは §いですｎ
	// かざんばい いつになったらｌ
	// おさまるの かしらｐ
	// あんまり つもっちゃうとｎ
	// パラソルの がらがｌ
	// みえなく なっちゃうのに……ｐ
	// それでは またｎ
	// おあい しましょう

MatchCall_PersonalizedText46:: @ 82AE998
	.string "{STR_VAR_1}입니다-\p"
	.string "있지 있지!\n"
	.string "바다는 수영장에 비해서\l"
	.string "뜨기 쉽다는 거 알고 있었어?\p"
	.string "이렇게 몸을 눕히면\n"
	.string "멋대로 뜬다\p"
	.string "하지만 너무 오래 떠있으면\n"
	.string "먼바다로 떠내려가니까\l"
	.string "조심해야 돼\p"
	.string "...어라? 여긴 어디지...\n"
	.string "그 그럼 또 보자!$"
	// §い で-すｐ
	// ねえねえ!ｎ
	// うみって プ-ルと くらべてｌ
	// うかびやすいって しってた?ｐ
	// こうやって からだを よこに すればｌ
	// かってに うくのよｐ
	// でも あんまり ながく うかんでるとｎ
	// おきに ながされるからｌ
	// きを つけないと だめよｐ
	// ……あれ? ここ どこかしら……ｎ
	// じゃ じゃあ またね!

MatchCall_PersonalizedText47:: @ 82AEA8F
	.string "아 {PLAYER} 안녕!\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "여긴 땅이 울퉁불퉁해서\n"
	.string "텐트를 칠 수가 없어...\l"
	.string "모처럼 산에 왔는데...\p"
	.string "아! 좋은 생각이 났다!\n"
	.string "포켓몬으로 여기를 평평하게\l"
	.string "만들면 되지 않을까?\p"
	.string "좋-았어 힘내야지!\n"
	.string "그럼 또 봐!$"
	// あ §あ§お こんにちは!ｎ
	// §い ですｐ
	// ここって じめんが でこぼこ してるからｎ
	// テント はれないのよね……ｌ
	// せっかく やまに きたのに……ｐ
	// あ! いいこと おもいついた!ｎ
	// ポケモンで ここを たいらにｌ
	// できないかしら?ｐ
	// よ-し がんばっちゃおう!ｎ
	// じゃあ またね!

MatchCall_PersonalizedText48:: @ 82AEB77
	.string "아 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "루미와 같이 힘내서\n"
	.string "포켓몬 키우고 있어!\p"
	.string "좀 더 힘내면\n"
	.string "제일 강해질 수 있겠지?\l"
	.string "그럼 또 봐-!$"
	// あ こんにちはｎ
	// §い で-すｐ
	// ルミと いっしょに がんばってｎ
	// ポケモン そだててるの!ｐ
	// もっと がんばったらｎ
	// いちばんに なれるかなあ?ｌ
	// じゃあ またね-!

MatchCall_PersonalizedText49:: @ 82AEBFA
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "이 몸은 선원이지만\n"
	.string "지금은 배에 안 타고 있지\p"
	.string "배를 타지 않는 선원은\n"
	.string "뭐라고 불러야 할까!\p"
	.string "바다를 보면서\n"
	.string "그런 생각들을 하고 있었어!\p"
	.string "그럼 또 보자!!$"
	// §いだ!ｐ
	// オレさまは ふなのり だがｎ
	// いまは ふねに のっていないｐ
	// ふねに のっていない ふなのりはｎ
	// なんと よべば いいだろうか!ｐ
	// うみを みながらｎ
	// そんな ことを かんがえて いるのだ!ｌ
	// じゃあ またな!!

MatchCall_PersonalizedText50:: @ 82AECC1
	.string "{STR_VAR_1}{K_I}야\n"
	.string "어때? 포켓몬 늘었어?\p"
	.string "새로운 포켓몬 잡으면\n"
	.string "또 보여주러 와\p"
	.string "안 징징거릴 테니까\n"
	.string "기다리고 있을게 또 보자$"
	// §い だよｎ
	// どう? ポケモン ふえた?ｐ
	// あたらしい ポケモン つかまえたらｎ
	// また みせに きてくれよｐ
	// ちょうだいって いわないからさｎ
	// まってるよ じゃあね

MatchCall_PersonalizedText51:: @ 82AED52
	.string "{STR_VAR_1}{K_I}야\n"
	.string "포켓몬 제대로 키우고 있어?\p"
	.string "여기는 공기도 깨끗해서\n"
	.string "포켓몬을 키우기에\l"
	.string "최고의 환경이란 말이지\p"
	.string "너도 포켓몬을 키우는 데\n"
	.string "전념할 때는\l"
	.string "{STR_VAR_2}{K_EU}로 와\l"
	.string "그럼 또 봐$"
	// §いだｎ
	// ポケモン ちゃんと そだててるか?ｐ
	// ここは くうきも きれいだしｎ
	// ポケモンを そだてるにはｌ
	// ぜっこうの かんきょう なんだよなｐ
	// きみも ポケモンを そだてる ことにｎ
	// せんねん する ときはｌ
	// §うに くると いいぞｌ
	// じゃあ またな

MatchCall_PersonalizedText52:: @ 82AEE35
	.string "{STR_VAR_1}입니다\n"
	.string "제 {STR_VAR_2}에게\p"
	.string "포켓몬스넥을 줬어요\n"
	.string "엄청 좋아하는 것 같더라구요\p"
	.string "포켓몬에 따라서\n"
	.string "좋아하는 포켓몬스넥이 다른가봐요\p"
	.string "재미있지 않나요?\n"
	.string "그럼 안녕히$"
	// §いですｎ
	// わたしの §うにｐ
	// ポロック あげたんですよｎ
	// とても よろこんでた みたいｐ
	// ポケモンに よってｎ
	// ポロックの すききらいが あるみたいなのｐ
	// おもしろい ですよねｎ
	// では ごきげんよう

MatchCall_PersonalizedText53:: @ 82AEEF4
	.string "{STR_VAR_1}{K_I}야\n"
	.string "포켓몬과 협력하면\l"
	.string "자연 속에서도\l"
	.string "쾌적하게 살 수 있어\p"
	.string "다들 그걸 깨닫고\n"
	.string "좀 더 포켓몬과\l"
	.string "협력하게 된다면\l"
	.string "좋을 텐데 말이지!\p"
	.string "넌 제법 좋은\n"
	.string "길을 걷고 있다고 생각해\l"
	.string "그럼 또 보자!$"
	// §いだｎ
	// ポケモンと きょうりょく すればｌ
	// しぜんの なかでもｌ
	// かいてきに くらせる ものだよｐ
	// みんな それに きが ついてｎ
	// もっと ポケモンとｌ
	// きょうりょく できるように なればｌ
	// いいのにな!ｐ
	// きみは けっこう いいセンｎ
	// いってると おもうよ!ｌ
	// じゃ またな!

MatchCall_PersonalizedText54:: @ 82AEFDA
	.string "언제나 모험의 준비를\n"
	.string "빠뜨리지 않는 {STR_VAR_1}{K_I}야!\p"
	.string "{PLAYER}의 도구는 충분해?\n"
	.string "포켓몬의 상태는 괜찮고?\p"
	.string "자신이 해야 할 일을\n"
	.string "항상 완벽하게 처리하는 게\l"
	.string "여행을 오래 이어가는 비결이야!\p"
	.string "나도 자신의 도구를\n"
	.string "확인하고 있어! 또 봐!$"
	// いつも ぼうけんの じゅんびをｎ
	// おこたらない §いよ!ｐ
	// §あ§お どうぐは たりてる?ｎ
	// ポケモンの たいちょうは バッチリ?ｐ
	// じぶんの みの まわりをｎ
	// つねに かんぺきに しておくことがｌ
	// たびを ながく つづける ひけつ よ!ｐ
	// わたしも じぶんの どうぐをｎ
	// かくにん するわ! またね!

MatchCall_PersonalizedText55:: @ 82AF0E7
	.string "{STR_VAR_1}{K_I}야 {STR_VAR_1}-!\p"
	.string "{STR_VAR_2}에는\n"
	.string "사람이 많이 지나가니까\l"
	.string "매일 여러 사람한테\l"
	.string "승부를 도전받게 돼!\p"
	.string "오늘은 있지 5명한테 이기고\n"
	.string "3명한테 졌어!\l"
	.string "네 쪽은 어때?\l"
	.string "다음에 들려줘! 나중에 보자$"
	// §いだよ §いだよ-!ｐ
	// §う ってｎ
	// ひとどおりが はげしいからｌ
	// まいにち いろんな ひとにｌ
	// しょうぶを もうしこまれるの!ｐ
	// きょうはねえ 5にんに かってｎ
	// 3にんに まけたわ!ｌ
	// あなたのほうは どうだった?ｌ
	// こんど きかせてねっ! じゃあね

MatchCall_PersonalizedText56:: @ 82AF1B8
	.string "벌레포켓몬을 잔뜩 가지고 있어서\n"
	.string "인기쟁이인 {STR_VAR_1}입니다!\p"
	.string "...오늘 학교에\n"
	.string "마음에 드는 벌레포켓몬을\l"
	.string "잔뜩 데려왔는데\l"
	.string "좋아하는 여자애가 울지 뭐야...\l"
	.string "으으 웃을 거면 웃어\p"
	.string "난 벌레포켓몬의 장점을\n"
	.string "그 애가 이해해줄 때까지\l"
	.string "힘낼 테니까!\p"
	.string "훌쩍 그럼 또 봐!$"
	// むしポケモンを いっぱい もっててｎ
	// にんきものの §い だけど!ｐ
	// ……きょう がっこうにｎ
	// おきにいりの むしポケモンをｌ
	// いっぱい つれて いったらｌ
	// すきな おんなのこに なかれ ちゃった……ｌ
	// うう わらいたければ わらって くれよｐ
	// ぼくは むしポケモンの よさをｎ
	// あのコに わかって もらえるまでｌ
	// がんばるんだ からね!ｐ
	// グッスン じゃ-な!

MatchCall_PersonalizedText57:: @ 82AF2C4
	.string "핫 핫 핫 홋\p"
	.string "여어! {STR_VAR_1}{K_I}라네! 핫 홋\p"
	.string "등산...하면서 얘기하는 것도\n"
	.string "제법... 핫 홋\l"
	.string "훈련이 되는구만\p"
	.string "훗 큭...\n"
	.string "산이 가파라지기 시작했군\l"
	.string "다 다음에... 천천히 얘기하자!\l"
	.string "핫 홋 핫...$"
	// はっ ほっ はっ ほっｐ
	// やあ! §いです! はっ ほっｐ
	// やま……のぼり しながらの おしゃべりもｎ
	// なかなか どうして…… はっ ほっｌ
	// トレ-ニングに なるなあｐ
	// ふっ くっ……ｎ
	// おっと のぼりが きつく なってきたｌ
	// ま また こんど…… ゆっくり はなそう!ｌ
	// はっ ほっ はっ……

MatchCall_PersonalizedText58:: @ 82AF371
	.string "아 아 안녕!\n"
	.string "지금 소영하고 보물찾기 하고 있어!\p"
	.string "어쩌면 보물이\n"
	.string "없을지도 모르지만...\p"
	.string "소영과 보물찾기를 둘이서\n"
	.string "한다는 게 중요한 거라구\p"
	.string "...아 어라 소영?\n"
	.string "왜 왜 화난 거야?\l"
	.string "정말 미안해\l"
	.string "물론 네가 제일 소중하지\l"
	.string "알고 있잖아?\p"
	.string "...그 그럼 안녕 {PLAYER}씨$"
	// や や どうも!ｎ
	// いま ナツと おたから さがしててさ!ｐ
	// おたから なんて もしかしたらｎ
	// ほんとうは ないのかも しれないけど……ｐ
	// ナツと おたからを ふたりで さがすｎ
	// って ことが だいじ なんだよねｐ
	// ……て あれ ナツ?ｎ
	// な なんで おこってるの?ｌ
	// ほっといて ゴメンねｌ
	// もちろん キミが いちばん だいじだよぉｌ
	// わかっている だろう?ｐ
	// じ じゃ…… §あさんさようなら

MatchCall_PersonalizedText59:: @ 82AF480
	.string "{STR_VAR_1}입니다!\n"
	.string "수업을 위해서 또\l"
	.string "무로마을의 포켓몬체육관에 갔다 왔어!\p"
	.string "체육관 관장인 철구는\n"
	.string "거센 파도를 맞으면서 강해졌어!\l"
	.string "근데 조금도 땀 냄새가 안 나고\l"
	.string "멋져서 솔직히 분해!\p"
	.string "동료인 시바라는 남자도\n"
	.string "분명 땀 냄새가 안 나고\l"
	.string "빅 웨이브 같은 말을\l"
	.string "하는 녀석이겠지!\p"
	.string "...질투는 추하구만!\n"
	.string "미안 잊어줘! 또 보자!$"
	// じぶんは §いだ!ｎ
	// しゅぎょうの ために またｌ
	// ムロの ポケモンジムに いってきた!ｐ
	// ジムリ-ダ-の トウキはｎ
	// あらなみに もまれ つよくなった!ｌ
	// なのに ちっとも あせくさく ないしｌ
	// もてもてで しょうじき くやしい!ｐ
	// なかまの シバ という おとこもｎ
	// きっと あせくさく なくてｌ
	// ビッグウェ-ブ だとか ボク だとかｌ
	// さわやかに いったり するのだろう!ｐ
	// ……やきもちは みぐるしいな!ｎ
	// すまん わすれて くれ! オスっ!

MatchCall_PersonalizedText60:: @ 82AF671
	.string "젊은 트레이너와\n"
	.string "얘기할 수 있어서 기쁘구먼\p"
	.string "자네도 물론\n"
	.string "몇 살이 되더라도 포켓몬을\l"
	.string "즐길 생각이겠지?\l"
	.string "그때는 나처럼\l"
	.string "누군가 상대가 있으면 좋을 걸세!\p"
	.string "뭐 {PLAYER}{K_EUNNEUN} 지금도\n"
	.string "포켓몬에게 신뢰를 받으면서\l"
	.string "쭉 힘내고 있으니까\p"
	.string "훌륭한 금혼식을 올릴\n"
	.string "소질은 충분하겠구먼!\l"
	.string "핫핫핫 힘내게나!$"
	// わかい トレ-ナ-さんとｎ
	// おはなし できて うれしい のうｐ
	// きみも もちろんｎ
	// なんさいに なっても ポケモンをｌ
	// がんばる つもり じゃろう?ｌ
	// その ときには わしらのようにｌ
	// だれか あいてが いると いいのう!ｐ
	// まあ §あ§おは いまだってｎ
	// ポケモンに しんらい されてｌ
	// ずっと がんばって おるからのうｐ
	// りっぱな きんこんしきに なれるｎ
	// そしつは バッチリじゃ!ｌ
	// はっはっはっ がんばるのじゃよ!

MatchCall_PersonalizedText61:: @ 82AF7D8
	.string "{STR_VAR_1}{K_I}야!\n"
	.string "아까 우리 웬일로\l"
	.string "수영팬티 형들을 이겼어!\l"
	.string "근데 멋있는 사람이어서...\p"
	.string "모처럼 연약한 모습을\n"
	.string "보이고 싶었는데!\p"
	.string "라면서 누나가 화내더라...\p"
	.string "어차피 이기든 지든\n"
	.string "나한테 화낼 거면서!\l"
	.string "{PLAYER}도 다음에\l"
	.string "뭐라고 말 좀 해주라!\p"
	.string "그럼 나중에 봐-!$"
	// §いです!ｎ
	// さっき ボクたち めずらしくｌ
	// かいパンの おにいさんに かったんだ!ｌ
	// でも かっこいい ひとだった から……ｐ
	// せっかく かよわい ところをｎ
	// みせようと したのに!ｐ
	// って ねえちゃんに おこられた……ｐ
	// ど-せ かっても まけてもｎ
	// おこられるんだ ボクは!ｌ
	// §あ§おも こんどｌ
	// なんとか いって やって!ｐ
	// じゃ またね-!

MatchCall_PersonalizedText62:: @ 82AF8F7
	.string "{STR_VAR_1}{K_I}라네 음...\n"
	.string "어제는 유적을 찾아서\l"
	.string "다른 바다로 나가려고 했는데\l"
	.string "길을 잃어버리고 말았네\p"
	.string "바다를 돌고 돌다가\n"
	.string "정신을 차려보니 또 원래 장소더군\p"
	.string "여전히 승부도 서툴고\n"
	.string "이젠 웃어도 좋네...\p"
	.string "뭐 난 포기 안 할 걸세\n"
	.string "언젠가 유적을 찾는다면\l"
	.string "내 시대가 오게 될 테니까!\p"
	.string "그런 고로\n"
	.string "오늘은 이만 끊겠네!$"
	// §いだよ うん……ｎ
	// きのうは いせきを もとめてｌ
	// ちがう うみに でようと したらｌ
	// みちに まよってしまったよｐ
	// うみを めぐり めぐってｎ
	// きがついたら また もとの ばしょさｐ
	// あいかわらず しょうぶも よわいしｎ
	// もう わらって くれよ……ｐ
	// まあ わしは あきらめんぞｎ
	// いつのひか いせきを みつけたらｌ
	// わしの じだいが くるだろう からな!ｐ
	// そういった わけでｎ
	// きょうは これで さらばだ!

MatchCall_PersonalizedText63:: @ 82AFA39
	.string "여어- 안녕-!\n"
	.string "{STR_VAR_1}{K_I}야-!\l"
	.string "난 지금-\l"
	.string "108번 수로에 와있어-!\p"
	.string "즉 평소와 똑같은 곳이라는 거지-!\p"
	.string "오늘은 눈앞을\n"
	.string "비키니 누나가 지나가서-\l"
	.string "큰소리로 깜짝 놀래켜봤어-!\p"
	.string "그랬더니 싫은 듯한 얼굴로 쳐다보더라-!\p"
	.string "이상 108번 수로에서\n"
	.string "{STR_VAR_1}{K_IGA} 전해드렸습니다-!$"
	// やあ- きみ-っ!ｎ
	// §いだ-!ｌ
	// わたしは いま-ｌ
	// 108ばんすいどうに きている-っ!ｐ
	// つまり いつもと おなじ ところだ-!ｐ
	// きょうは めの まえをｎ
	// ビキニのおねえさんが とおったから-っｌ
	// おおごえで おどかして みた-っ!ｐ
	// そしたら いやな かおを された-!ｐ
	// いじょう 108ばんすいどう からｎ
	// §いが おつたえ した-!

MatchCall_PersonalizedText64:: @ 82AFB26
	.string "{STR_VAR_1}{K_I}야!\n"
	.string "지금 바쁘지만\l"
	.string "오늘은 벌써\l"
	.string "5명의 트레이너를 쓰러뜨려서\l"
	.string "네게도 일단 보고하기로 했어!\p"
	.string "이 상태라면\n"
	.string "다음엔 아마도 널 이길 수 있을 거야!\l"
	.string "우린 좋은 라이벌이\l"
	.string "될 수 있을 것 같아...\l"
	.string "그럼 이만 바이!$"
	// §いよ!ｎ
	// いま いそがしいんだけどｌ
	// きょうは もうｌ
	// 5にんの トレ-ナ-を たおしたからｌ
	// あなたにも いちおう ほうこく するわ!ｐ
	// この ちょうし だとｎ
	// つぎは たぶん あなたに かてるわね!ｌ
	// わたしたち いい ライバルとしてｌ
	// やって いけそうね……ｌ
	// じゃあね バイ!

MatchCall_BattleFrontierStreakText1:: @ 82AFC07
	.string "안녕 {STR_VAR_1}{K_I}야!\n"
	.string "들었어!\p"
	.string "{STR_VAR_2}에서\n"
	.string "굉장한 활약을 했다면서?\p"
	.string "{STR_VAR_3}연승이라니 굉장한걸\n"
	.string "그럼 또 봐!$"
	// こんにちは §い です!ｎ
	// きいたよ!ｐ
	// §う でｎ
	// すごい かつやく したんだって?ｐ
	// §えれんしょう って すごいなあｎ
	// じゃあ またね!

MatchCall_BattleFrontierStreakText2:: @ 82AFC78
	.string "안녕 {STR_VAR_1}{K_I}야-\n"
	.string "{STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승을 했다고 들었어!\p"
	.string "굉장하다-! 나도 힘내야지!\n"
	.string "그럼 또 보자!$"
	// こんにちは §い で-すｎ
	// §う でｌ
	// §えれんしょう したって きいたわよ!ｐ
	// すっご-い! わたしも がんばろうっと!ｎ
	// じゃあ またね!

MatchCall_BattleFrontierStreakText3:: @ 82AFCFF
	.string "오우! {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "{STR_VAR_2}에서\n"
	.string "크게 날뛴 것 같던데!\p"
	.string "{STR_VAR_3}연승이라니\n"
	.string "굉장한 기록이잖아?\p"
	.string "나도 질 수 없지-!\n"
	.string "그럼 또 보자!$"
	// おう! §あ!ｎ
	// §いだぞ!ｐ
	// §う でｎ
	// おおあばれ したらしいな!ｐ
	// §えれんしょう ってｎ
	// すごい きろく なんだろ?ｐ
	// おれも まけられね-な!ｎ
	// じゃ またな!

MatchCall_BattleFrontierStreakText4:: @ 82AFDA7
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내?\p"
	.string "소문으로 들었는데\n"
	.string "너 {STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승을 했다면서?\p"
	.string "나도 힘내야겠다\n"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §い だけど げんき かい?ｐ
	// うわさで きいたんだけどｎ
	// きみ §うでｌ
	// §えれんしょうも したんだって?ｐ
	// ぼくも がんばらなきゃなｎ
	// じゃあ また

MatchCall_BattleFrontierStreakText5:: @ 82AFE3D
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승이나 했다며!\l"
	.string "굉장한걸\p"
	.string "나도 포켓몬 키워야지\n"
	.string "그럼 나중에 봐$"
	// §あ§お こんにちはｎ
	// §い だよｐ
	// §うでｎ
	// §えれんしょうも したんだってね!ｌ
	// すごいなあｐ
	// ぼくも ポケモン そだてなきゃｎ
	// じゃあ また

MatchCall_BattleFrontierStreakText6:: @ 82AFECA
	.string "{PLAYER}{K_I}니?\n"
	.string "안녕 {STR_VAR_1}{K_I}야\p"
	.string "그러고 보니 너\n"
	.string "{STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승이나 했다면서\p"
	.string "나도 힘내서\n"
	.string "포켓몬 키워야지$"
	// §あ§お かい?ｎ
	// こんにちは §い だｐ
	// そういえば きみｎ
	// §うでｌ
	// §えれんしょうも したんだってねｐ
	// おれも がんばってｎ
	// ポケモンを そだてるよ

MatchCall_BattleFrontierStreakText7:: @ 82AFF64
	.string "으-음 아 {PLAYER}?\n"
	.string "{STR_VAR_1}{K_I}야...\p"
	.string "그러고 보니 {STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다면서\p"
	.string "아! 지금 희귀한 포켓몬을\n"
	.string "찾았으니까 나중에 보자!$"
	// え-と あ §あ§お?ｎ
	// §い だ®®®ｐ
	// そういえば §う でｎ
	// §えれんしょう したんだってねｐ
	// あ! いま めずらしい ポケモンをｎ
	// みつけたから じゃあ また!

MatchCall_BattleFrontierStreakText8:: @ 82AFFF0
	.string "{PLAYER}씨 안녕하세요\n"
	.string "{STR_VAR_1}입니다\p"
	.string "상태는 어떤가요?\n"
	.string "그러고 보니 {STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승이나 했다면서요?\p"
	.string "굉장한데요!\n"
	.string "다음번에도 힘내세요$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// ちょうしは どうですか?ｎ
	// そういえば §うでｌ
	// §えれんしょうも したんですって?ｐ
	// すごいですね!ｎ
	// つぎも がんばってね

MatchCall_BattleFrontierStreakText9:: @ 82B00B5
	.string "어머 {PLAYER}!\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "들었어! {STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다며!\p"
	.string "굉장하다-\n"
	.string "나도 힘내야겠어$"
	// あら §あ§お!ｎ
	// こんにちは §いです!ｐ
	// きいたわよ! §うでｎ
	// §えれんしょうも したって!ｐ
	// すっごいね-ｎ
	// わたしも がんばらなくちゃ

MatchCall_BattleFrontierStreakText10:: @ 82B0129
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다면서?\p"
	.string "굉장한걸\n"
	.string "나도 힘내야겠다$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// §うでｎ
	// §えれんしょうも したんですって?ｐ
	// すごいわねえｎ
	// わたしも がんばらなくちゃ

MatchCall_BattleFrontierStreakText11:: @ 82B01A5
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "대활약하고 있는 거 같던데\l"
	.string "{STR_VAR_3}연승이나 했다면서?\p"
	.string "굉장한걸 나는\n"
	.string "몇 연승까지 가능하려나$"
	// やあやあ §あ§おｎ
	// §いだｐ
	// §うで だいかつやく らしいなあｎ
	// §えれんしょう したんだって?ｐ
	// すげえなあ おれだったらｎ
	// なんれんしょう できるのかな

MatchCall_BattleFrontierStreakText12:: @ 82B0232
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "소문으로 들었는데\n"
	.string "{STR_VAR_2}{K_I}라는 곳에서\l"
	.string "{STR_VAR_3}연승이나 했지?\p"
	.string "굉장한 얘기로구먼\n"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃが げんきかの?ｐ
	// ひとづてに きいたのじゃがｎ
	// §う とかいう ところでｌ
	// §えれんしょうも したらしいのう?ｐ
	// すごい はなし だのうｎ
	// では またの

MatchCall_BattleFrontierStreakText13:: @ 82B02D9
	.string "{PLAYER}{K_I}니?\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승이나 한 모양이던데\p"
	.string "건강해서 다행이구먼\n"
	.string "그럼 또 보세$"
	// §あ§お かい?ｎ
	// §い じゃが げんきかの?ｐ
	// §うでｎ
	// §えれんしょうも したそうじゃのうｐ
	// げんきで いいことじゃｎ
	// では またのう

MatchCall_BattleFrontierStreakText14:: @ 82B0366
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승이나 했다면서?\p"
	.string "굉장하다 나도 감탄했어!\n"
	.string "그럼 나중에 보자$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// きいたわよ!ｎ
	// §うでｌ
	// §えれんしょうも したんですって?ｐ
	// すごいわねえ かんしん しちゃうわ!ｎ
	// じゃあ またね

MatchCall_BattleFrontierRecordStreakText1:: @ 82B03E6
	.string "안녕 {STR_VAR_1}{K_I}야!\n"
	.string "들었어!\p"
	.string "{STR_VAR_2}에서\n"
	.string "굉장한 활약을 했다면서?\p"
	.string "{STR_VAR_3}연승이라니 굉장한걸\n"
	.string "그럼 또 봐!$"
	// こんにちは §い です!ｎ
	// きいたよ!ｐ
	// §う でｎ
	// すごい かつやく したんだって?ｐ
	// §えれんしょう って すごいなあｎ
	// じゃあ またね!

MatchCall_BattleFrontierRecordStreakText2:: @ 82B0457
	.string "안녕 {STR_VAR_1}{K_I}야-\n"
	.string "{STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승을 했다고 들었어!\p"
	.string "굉장하다-! 나도 힘내야지!\n"
	.string "그럼 또 보자!$"
	// こんにちは §い で-すｎ
	// §う でｌ
	// §えれんしょう したって きいたわよ!ｐ
	// すっご-い! わたしも がんばろうっと!ｎ
	// じゃあ またね!

MatchCall_BattleFrontierRecordStreakText3:: @ 82B04DE
	.string "오우! {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야!\p"
	.string "{STR_VAR_2}에서\n"
	.string "크게 날뛴 것 같던데!\p"
	.string "{STR_VAR_3}연승이라니\n"
	.string "굉장한 기록이잖아?\p"
	.string "나도 질 수 없지-!\n"
	.string "그럼 또 보자!$"
	// おう! §あ!ｎ
	// §いだぞ!ｐ
	// §う でｎ
	// おおあばれ したらしいな!ｐ
	// §えれんしょう ってｎ
	// すごい きろく なんだろ?ｐ
	// おれも まけられね-な!ｎ
	// じゃ またな!

MatchCall_BattleFrontierRecordStreakText4:: @ 82B0586
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내?\p"
	.string "소문으로 들었는데\n"
	.string "너 {STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승을 했다면서?\p"
	.string "나도 힘내야겠다\n"
	.string "그럼 또 봐$"
	// やあ §あ§おｎ
	// §い だけど げんき かい?ｐ
	// うわさで きいたんだけどｎ
	// きみ §うでｌ
	// §えれんしょうも したんだって?ｐ
	// ぼくも がんばらなきゃなｎ
	// じゃあ また

MatchCall_BattleFrontierRecordStreakText5:: @ 82B061C
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승이나 했다며!\l"
	.string "굉장한걸\p"
	.string "나? 나는 천천히 하는 중이지-\n"
	.string "그럼 나중에 보자$"
	// §あ§お こんにちはｎ
	// §い だよｐ
	// §うでｎ
	// §えれんしょうも したんだってね!ｌ
	// すごいなあｐ
	// おれ? おれは まあ ぼちぼちかな-ｎ
	// じゃあ またね

MatchCall_BattleFrontierRecordStreakText6:: @ 82B06A3
	.string "{PLAYER}{K_I}니?\n"
	.string "안녕 {STR_VAR_1}{K_I}야\p"
	.string "그러고 보니 너\n"
	.string "{STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승이나 했다면서\p"
	.string "나도 힘내야겠다!\n"
	.string "그럼 또 보자$"
	// §あ§お かい?ｎ
	// こんにちは §い だｐ
	// そういえば きみｎ
	// §うでｌ
	// §えれんしょうも したんだってねｐ
	// おれも がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_BattleFrontierRecordStreakText7:: @ 82B073B
	.string "으-음 아 {PLAYER}?\n"
	.string "{STR_VAR_1}{K_I}야...\p"
	.string "그러고 보니 {STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다면서\p"
	.string "아! 지금 희귀한 포켓몬을\n"
	.string "찾았으니까 나중에 보자!$"
	// え-と あ §あ§お?ｎ
	// §い だ®®®ｐ
	// そういえば §う でｎ
	// §えれんしょう したんだってねｐ
	// あ! いま めずらしい ポケモンをｎ
	// みつけたから じゃあ また!

MatchCall_BattleFrontierRecordStreakText8:: @ 82B07C7
	.string "{PLAYER}씨 안녕하세요\n"
	.string "{STR_VAR_1}입니다\p"
	.string "상태는 어떤가요?\n"
	.string "그러고 보니 {STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승이나 했다면서요?\p"
	.string "굉장한데요! 저도 힘내서\n"
	.string "포켓몬을 키워야겠어요$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// ちょうしは どうですか?ｎ
	// そういえば §うでｌ
	// §えれんしょうも したんですって?ｐ
	// すごいですね! わたしも がんばってｎ
	// ポケモンを そだてなきゃ

MatchCall_BattleFrontierRecordStreakText9:: @ 82B0894
	.string "어머 {PLAYER}!\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "들었어! {STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다며!\p"
	.string "굉장하다-\n"
	.string "나도 힘내야겠어$"
	// あら §あ§お!ｎ
	// こんにちは §いです!ｐ
	// きいたわよ! §うでｎ
	// §えれんしょうも したって!ｐ
	// すっごいね-ｎ
	// わたしも がんばらなくちゃ

MatchCall_BattleFrontierRecordStreakText10:: @ 82B0908
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다면서?\p"
	.string "굉장한걸\n"
	.string "나도 힘내야겠다$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// §うでｎ
	// §えれんしょうも したんですって?ｐ
	// すごいわねえｎ
	// わたしも がんばらなくちゃ

MatchCall_BattleFrontierRecordStreakText11:: @ 82B0984
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "대활약하고 있는 거 같던데\l"
	.string "{STR_VAR_3}연승이나 했다면서?\p"
	.string "굉장한걸 나는\n"
	.string "몇 연승까지 가능하려나$"
	// やあやあ §あ§おｎ
	// §いだｐ
	// §うで だいかつやく らしいなあｎ
	// §えれんしょう したんだって?ｐ
	// すげえなあ おれだったらｎ
	// なんれんしょう できるのかな

MatchCall_BattleFrontierRecordStreakText12:: @ 82B0A11
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "소문으로 들었는데\n"
	.string "{STR_VAR_2}{K_I}라는 곳에서\l"
	.string "{STR_VAR_3}연승이나 했지?\p"
	.string "굉장한 얘기로구먼\n"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃが げんきかの?ｐ
	// ひとづてに きいたのじゃがｎ
	// §う とかいう ところでｌ
	// §えれんしょうも したらしいのう?ｐ
	// すごい はなし だのうｎ
	// では またの

MatchCall_BattleFrontierRecordStreakText13:: @ 82B0AB8
	.string "{PLAYER}{K_I}니?\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승이나 한 모양이던데\p"
	.string "건강해서 다행이구먼\n"
	.string "그럼 또 보세$"
	// §あ§お かい?ｎ
	// §い じゃが げんきかの?ｐ
	// §うでｎ
	// §えれんしょうも したそうじゃのうｐ
	// げんきで いいことじゃｎ
	// では またのう

MatchCall_BattleFrontierRecordStreakText14:: @ 82B0B45
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\l"
	.string "{STR_VAR_3}연승이나 했다면서?\p"
	.string "굉장하다 나도 감탄했어!\n"
	.string "그럼 나중에 보자$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// きいたわよ!ｎ
	// §うでｌ
	// §えれんしょうも したんですって?ｐ
	// すごいわねえ かんしん しちゃうわ!ｎ
	// じゃあ またね

MatchCall_BattleDomeText1:: @ 82B0BC5
	.string "아! {PLAYER}?\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\p"
	.string "{STR_VAR_3}번이나\n"
	.string "우승했다면서?\p"
	.string "굉장하다! 나도 힘내야지!\n"
	.string "그럼 또 봐$"
	// あ! §あ?ｎ
	// こんにちは §い です!ｐ
	// きいたよ!ｎ
	// §う でｐ
	// §えかい もｎ
	// ゆうしょう したんだって?ｐ
	// すごいね! ぼくも がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_BattleDomeText2:: @ 82B0C4A
	.string "안녕 {STR_VAR_1}{K_I}야!\n"
	.string "들었어!\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}번이나\l"
	.string "우승했다면서?\p"
	.string "굉장한걸-\n"
	.string "나도 우승할 수 있을까?$"
	// こんにちは §い で-す!ｎ
	// きいたわよ!ｐ
	// §う でｎ
	// §えかい もｌ
	// ゆうしょう したんですって?ｐ
	// すごいわね-ｎ
	// わたしも ゆうしょう できるのかな?

MatchCall_BattleDomeText3:: @ 82B0CC7
	.string "요 {PLAYER}!\n"
	.string "{STR_VAR_1}인데 잘 지내-?\p"
	.string "{STR_VAR_2}에서 {STR_VAR_3}번이나\n"
	.string "우승했다고 들었어\p"
	.string "다음에도 힘내-\n"
	.string "그럼 또 보자$"
	// よう §あ!ｎ
	// §いだぞ げんきか-?ｐ
	// §うで §えかいもｎ
	// ゆうしょう したって きいたぞｐ
	// つぎも がんばれよな-ｎ
	// じゃあ またな

MatchCall_BattleDomeText4:: @ 82B0D4A
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서 {STR_VAR_3}번이나\n"
	.string "우승한 모양이던데\p"
	.string "열심히 하고 있나 보네\n"
	.string "나도 지지 않게 해야지$"
	// やあ §あ§おｎ
	// §い だｐ
	// §うで §えかいもｎ
	// ゆうしょう した らしいねｐ
	// がんばってる みたいだねｎ
	// ぼくも まけないように しなきゃ

MatchCall_BattleDomeText5:: @ 82B0DC8
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어 {STR_VAR_2}에서\n"
	.string "{STR_VAR_3}번이나 우승했다면서?\p"
	.string "나도 열심히 해야지\n"
	.string "그럼 또 봐$"
	// §あ§お こんにちはｎ
	// §い だよｐ
	// きいたよ §うでｎ
	// §えかいも ゆうしょう したんだって?ｐ
	// ぼくも がんばらなきゃｎ
	// じゃあ またね

MatchCall_BattleDomeText6:: @ 82B0E35
	.string "{PLAYER}{K_I}니?\n"
	.string "안녕 {STR_VAR_1}{K_I}야\p"
	.string "그러고 보니 너\n"
	.string "{STR_VAR_2}에서 {STR_VAR_3}번이나\l"
	.string "우승했다면서\p"
	.string "나도 지지 않도록\n"
	.string "포켓몬을 키워야겠다$"
	// §あ§お かい?ｎ
	// こんにちは §い だｐ
	// そういえば きみｎ
	// §うで §えかいもｌ
	// ゆうしょう したんだってねｐ
	// おれも まけないようにｎ
	// ポケモンを そだてなきゃな

MatchCall_BattleDomeText7:: @ 82B0ED1
	.string "{PLAYER}?\n"
	.string "어 {STR_VAR_1}인데\p"
	.string "{STR_VAR_2}에서 우승을\n"
	.string "{STR_VAR_3}번이나 했다며?\p"
	.string "헤- 그나저나 최근에\n"
	.string "희귀한 포켓몬 잡았어?\p"
	.string "아 그래?\n"
	.string "그럼 또 보자$"
	// §あ§お?ｎ
	// ああ §い だけどｐ
	// §うで ゆうしょうをｎ
	// §えかいも したんだって?ｐ
	// へ- ところで さいきんｎ
	// めずらしい ポケモン つかまえた?ｐ
	// あ そうｎ
	// じゃあ またね

MatchCall_BattleDomeText8:: @ 82B0F72
	.string "안녕하세요 {PLAYER}\n"
	.string "{STR_VAR_1}입니다\p"
	.string "잘 지내시나요?\n"
	.string "{STR_VAR_2}에서 {STR_VAR_3}번이나\l"
	.string "우승했다면서요?\p"
	.string "굉장하네요!\n"
	.string "저도 힘내서\p"
	.string "포켓몬을 키워야겠어요!\n"
	.string "그럼 나중에 봐요$"
	// こんにちは §あ§おｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// §うで §えかいもｌ
	// ゆうしょう したんですって?ｐ
	// すごいですね!ｎ
	// わたしも がんばってｐ
	// ポケモン そだてないと!ｎ
	// じゃあ またね

MatchCall_BattleDomeText9:: @ 82B102A
	.string "어머 {PLAYER}!\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}번이나 우승했다면서?\p"
	.string "굉장하다-\n"
	.string "나도 열심히 해야지$"
	// あら §あ§お!ｎ
	// こんにちは §いです!ｐ
	// §うでｎ
	// §えかいも ゆうしょう したんだって?ｐ
	// すっごいね-ｎ
	// わたしも がんばらなくちゃ

MatchCall_BattleDomeText10:: @ 82B10A7
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}연승을 했다면서?\p"
	.string "굉장하네\n"
	.string "나도 열심히 해야지$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// §うでｎ
	// §えれんしょうも したんですって?ｐ
	// すごいわねえｎ
	// わたしも がんばらなくちゃ

MatchCall_BattleDomeText11:: @ 82B1121
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "대활약하고 있는 거 같던데\l"
	.string "{STR_VAR_3}연승이나 했다며?\p"
	.string "굉장한걸 나도\n"
	.string "우승할 수 있을까\p"
	.string "...역시 안 되겠지?\n"
	.string "그럼 또 봐$"
	// やあやあ §あ§おｎ
	// §いだｐ
	// §うでｎ
	// だいかつやく らしいなあｌ
	// §えれんしょう したんだって?ｐ
	// すげえなあ おれでもｎ
	// ゆうしょう できるのかなｐ
	// ®®® むりかな?ｎ
	// じゃあ またな

MatchCall_BattleDomeText12:: @ 82B11D3
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}{K_I}라는 곳에서\n"
	.string "{STR_VAR_3}번 우승했다고 하던데?\p"
	.string "굉장한 얘기로구먼\n"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃが げんきかの?ｐ
	// §う とかいう ところでｎ
	// §えかい ゆうしょう したとな?ｐ
	// すごい はなし だのうｎ
	// では またの

MatchCall_BattleDomeText13:: @ 82B124D
	.string "{PLAYER}{K_I}니?\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}에서\n"
	.string "{STR_VAR_3}번 우승했다고 하던데?\p"
	.string "건강해서 다행이구먼\n"
	.string "그럼 또 보세$"
	// §あ§お かい?ｎ
	// §い じゃが げんきかの?ｐ
	// §う でｎ
	// §えかいも ゆうしょう とな?ｐ
	// げんきで いいことじゃｎ
	// では またのう

MatchCall_BattleDomeText14:: @ 82B12D0
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\p"
	.string "{STR_VAR_3}번이나\n"
	.string "우승했다면서?\p"
	.string "굉장하다 나 감탄했어!\n"
	.string "그럼 또 보자$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// きいたわよ!ｎ
	// §う でｐ
	// §えかいもｎ
	// ゆうしょう したんですって?ｐ
	// すごいわねえ かんしん しちゃうわ!ｎ
	// じゃあ またね

MatchCall_BattlePikeText1:: @ 82B1347
	.string "아! {PLAYER}?\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\p"
	.string "방을 {STR_VAR_3}개나\n"
	.string "돌파했다면서?\p"
	.string "굉장하다\n"
	.string "그럼 또 보자$"
	// あ! §あ?ｎ
	// こんにちは §い です!ｐ
	// きいたよ!ｎ
	// §う でｐ
	// §えも へやをｎ
	// とっぱ したんだって?ｐ
	// すごいなあｎ
	// じゃあ またね

MatchCall_BattlePikeText2:: @ 82B13B1
	.string "안녕 {STR_VAR_1}{K_I}야-!\n"
	.string "들었어!\p"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\n"
	.string "돌파했다며?\p"
	.string "나도 열심히 해야겠다!\n"
	.string "그럼 또 보자$"
	// こんにちは §い で-す!ｎ
	// きいたわよ!ｐ
	// §う で§えへやもｎ
	// かちぬいたんですって?ｐ
	// わたしも がんばらなきゃ!ｎ
	// じゃあ またね

MatchCall_BattlePikeText3:: @ 82B142B
	.string "요 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야 잘 지내-?\p"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\n"
	.string "돌파했다고 들었어\p"
	.string "다음에도 힘내-\n"
	.string "그럼 또 보자$"
	// よう §あ!ｎ
	// §いだぞ げんきか-?ｐ
	// §うで §えへやもｎ
	// とっぱ したって きいたぞｐ
	// つぎも がんばれよな-ｎ
	// じゃあ またな

MatchCall_BattlePikeText4:: @ 82B14B4
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\n"
	.string "돌파한 거 같던데\p"
	.string "나도 지지 않게\n"
	.string "포켓몬을 키워야겠다$"
	// やあ §あ§おｎ
	// §い だｐ
	// §うで §えへやもｎ
	// とっぱ した らしいねｐ
	// おれも まけないようにｎ
	// ポケモン そだてなきゃな

MatchCall_BattlePikeText5:: @ 82B1525
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어 {STR_VAR_2}에서\n"
	.string "방을 {STR_VAR_3}개나 돌파했다며?\p"
	.string "나도 힘내야지\n"
	.string "그럼 또 봐$"
	// §あ§お こんにちはｎ
	// §い だよｐ
	// きいたよ §うでｎ
	// §えへやも とっぱ したんだって?ｐ
	// ぼくも がんばらなきゃｎ
	// じゃあ またね

MatchCall_BattlePikeText6:: @ 82B158E
	.string "{PLAYER}{K_I}니?\n"
	.string "안녕 {STR_VAR_1}{K_I}야\p"
	.string "그러고 보니 너\n"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\l"
	.string "돌파했다고 들었어\p"
	.string "나도 지지 않도록\n"
	.string "포켓몬을 키워야겠다$"
	// §あ§お かい?ｎ
	// こんにちは §い だｐ
	// そういえば きみｎ
	// §うで §えへやもｌ
	// とっぱ したんだってねｐ
	// おれも まけないようにｎ
	// ポケモンを そだてなきゃな

MatchCall_BattlePikeText7:: @ 82B1622
	.string "{PLAYER}?\n"
	.string "응 {STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\n"
	.string "돌파했다면서?\p"
	.string "굉장한걸\p"
	.string "아 희귀한 포켓몬을 찾았으니까\n"
	.string "나중에 보자$"
	// §あ§お?ｎ
	// ああ §い だけどｐ
	// §うで §えへやもｎ
	// とっぱ したんだって?ｐ
	// すごいねえｎ
	// あ めずらしいポケモンを みつけたからｐ
	// じゃあ また

MatchCall_BattlePikeText8:: @ 82B169D
	.string "안녕하세요 {PLAYER}\n"
	.string "{STR_VAR_1}입니다\p"
	.string "잘 지내시나요?\n"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\l"
	.string "돌파했다면서요?\p"
	.string "굉장하네요!\n"
	.string "저도 열심히 해서\p"
	.string "포켓몬을 키워야겠어요!\n"
	.string "그럼 나중에 봐요$"
	// こんにちは §あ§おｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// §うで §えへやもｌ
	// とっぱ したんですって?ｐ
	// すごいですね!ｎ
	// わたしも がんばってｐ
	// ポケモン そだてないと!ｎ
	// じゃあ またね

MatchCall_BattlePikeText9:: @ 82B1775
	.string "어머 {PLAYER}!\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "{STR_VAR_2}에서 방을 {STR_VAR_3}개나\n"
	.string "돌파했다면서?\p"
	.string "굉장하다-\n"
	.string "나도 열심히 해야지$"
	// あら §あ§お!ｎ
	// こんにちは §いです!ｐ
	// §うで §えへやもｎ
	// とっぱ したんだって?ｐ
	// すっごいね-ｎ
	// わたしも がんばらなくちゃ

MatchCall_BattlePikeText10:: @ 82B17F8
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "방을 {STR_VAR_3}개나 돌파했다며?\p"
	.string "굉장하다\n"
	.string "나도 열심히 해야지$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// §うでｎ
	// §えへやも とっぱ したんですって?ｐ
	// すごいわねえｎ
	// わたしも がんばらなくちゃ

MatchCall_BattlePikeText11:: @ 82B1877
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "대활약하고 있는 모양이던데\l"
	.string "방을 {STR_VAR_3}개나 돌파했다며?\p"
	.string "굉장한걸 나도\n"
	.string "우승할 수 있을까?\p"
	.string "...역시 무리인가?\n"
	.string "그럼 또 보자$"
	// やあやあ §あ§おｎ
	// §いだｐ
	// §うでｎ
	// だいかつやく らしいなあｌ
	// §えへやも とっぱ したんだって?ｐ
	// すげえなあ おれでもｎ
	// ゆうしょう できるのかなｐ
	// ®®® むりかなあ?ｎ
	// じゃあ またな

MatchCall_BattlePikeText12:: @ 82B1946
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}{K_I}라는 곳에서\n"
	.string "방을 {STR_VAR_3}개나 돌파했다던데?\p"
	.string "굉장한 얘기로구먼\n"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃが げんきかの?ｐ
	// §う とかいう ところでｎ
	// §えへや とっぱ したとな?ｐ
	// すごい はなし だのうｎ
	// では またの

MatchCall_BattlePikeText13:: @ 82B19C7
	.string "{PLAYER}{K_I}니?\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}에서\n"
	.string "방을 {STR_VAR_3}개나 돌파했다던데?\p"
	.string "건강해서 다행이구먼\n"
	.string "그럼 또 보세$"
	// §あ§お かい?ｎ
	// §い じゃが げんきかの?ｐ
	// §うでｎ
	// §えへやも とっぱした とな?ｐ
	// げんきで いいことじゃｎ
	// では またのう

MatchCall_BattlePikeText14:: @ 82B1A4C
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\p"
	.string "방을 {STR_VAR_3}개나\n"
	.string "돌파했다면서?\p"
	.string "굉장하다 나 감탄했어!\n"
	.string "그럼 또 보자$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// きいたわよ!ｎ
	// §うでｐ
	// §えへやもｎ
	// とっぱ したんですって?ｐ
	// すごいわねえ かんしん しちゃうわ!ｎ
	// じゃあ またね

MatchCall_BattlePyramidText1:: @ 82B1ACA
	.string "아! {PLAYER}?\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\p"
	.string "층을 {STR_VAR_3}개나\n"
	.string "올라갔다면서?\p"
	.string "굉장하다- 나도 다음에\n"
	.string "도전해 볼까-$"
	// あ! §あ?ｎ
	// こんにちは §い です!ｐ
	// きいたよ!ｎ
	// §う でｐ
	// §えだん もｎ
	// のぼったんだって?ｐ
	// すごいね- ぼくも こんどｎ
	// ちょうせん してみようかな-

MatchCall_BattlePyramidText2:: @ 82B1B50
	.string "안녕 {STR_VAR_1}{K_I}야-!\n"
	.string "들었어!\p"
	.string "{STR_VAR_2}에서\n"
	.string "층을 {STR_VAR_3}개나\l"
	.string "올라갔다며?\p"
	.string "굉장해-! 내 포켓몬도\n"
	.string "열심히 키워야겠다$"
	// こんにちは §い で-す!ｎ
	// きいたわよ!ｐ
	// §う でｎ
	// §えだん もｌ
	// かちぬいたんですって?ｐ
	// すご-い! わたしの ポケモンもｎ
	// がんばって そだてなくちゃ

MatchCall_BattlePyramidText3:: @ 82B1BE4
	.string "요 {PLAYER}!\n"
	.string "{STR_VAR_1}{K_I}야 잘 지내-?\p"
	.string "{STR_VAR_2}에서 층을 {STR_VAR_3}개나\n"
	.string "올라갔다고 들었어\p"
	.string "다음에도 힘내-\n"
	.string "그럼 또 보자$"
	// よう §あ!ｎ
	// §いだぞ げんきか-?ｐ
	// §うで §えだんもｎ
	// のぼったって きいたぞｐ
	// つぎも がんばれよな-ｎ
	// じゃあ またな

MatchCall_BattlePyramidText4:: @ 82B1C6A
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서 층을 {STR_VAR_3}개나\n"
	.string "올라간 거 같던데\p"
	.string "나도 너한테 지지 않도록\n"
	.string "열심히 해야겠다$"
	// やあ §あ§おｎ
	// §い だｐ
	// §うで §えだんもｎ
	// のぼった らしいねｐ
	// ぼくも きみに まけないようにｎ
	// がんばらなきゃな

MatchCall_BattlePyramidText5:: @ 82B1CCF
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어 {STR_VAR_2}에서\n"
	.string "층을 {STR_VAR_3}개나 올라갔다며?\p"
	.string "나도 힘내야지\n"
	.string "그럼 또 봐$"
	// §あ§お こんにちはｎ
	// §い だよｐ
	// きいたよ §う でｎ
	// §えだんも のぼったんだって?ｐ
	// ぼくも がんばらなきゃｎ
	// じゃあ またね

MatchCall_BattlePyramidText6:: @ 82B1D38
	.string "{PLAYER}{K_I}니?\n"
	.string "안녕 {STR_VAR_1}{K_I}야\p"
	.string "그러고 보니 너\n"
	.string "{STR_VAR_2}에서 층을 {STR_VAR_3}개나\l"
	.string "올라갔다고 들었어\p"
	.string "나도 지지 않도록\n"
	.string "포켓몬을 키워야겠다$"
	// §あ§お かい?ｎ
	// こんにちは §い だｐ
	// そういえば きみｎ
	// §うで §えだんもｌ
	// かちぬいたんだってねｐ
	// おれも まけないようにｎ
	// ポケモンを そだてなきゃな

MatchCall_BattlePyramidText7:: @ 82B1DCD
	.string "{PLAYER}?\n"
	.string "응 {STR_VAR_1}인데\p"
	.string "{STR_VAR_2}에서 층을 {STR_VAR_3}개나\n"
	.string "올라갔다면서?\p"
	.string "헤-... 거기에\n"
	.string "희귀한 포켓몬은 없었어?\p"
	.string "그렇구나- 없구나-\n"
	.string "그럼 또 봐$"
	// §あ§お?ｎ
	// ああ §い だけどｐ
	// §うで §えだんもｎ
	// のぼったんだって?ｐ
	// へ-…… そこにｎ
	// めずらしい ポケモン いなかった?ｐ
	// そうか- いないか-ｎ
	// じゃあ また

MatchCall_BattlePyramidText8:: @ 82B1E4B
	.string "안녕하세요 {PLAYER}\n"
	.string "{STR_VAR_1}입니다\p"
	.string "잘 지내시나요?\n"
	.string "{STR_VAR_2}에서 층을 {STR_VAR_3}개나\l"
	.string "올라갔다면서요?\p"
	.string "굉장하네요!\n"
	.string "저도 열심히 해서\p"
	.string "포켓몬을 키워야겠어요!\n"
	.string "그럼 나중에 봐요$"
	// こんにちは §あ§おｎ
	// §い ですｐ
	// げんき ですか?ｎ
	// §うで §えだんもｌ
	// かちぬいたんですって?ｐ
	// すごいですね!ｎ
	// わたしも がんばってｐ
	// ポケモン そだてないと!ｎ
	// じゃあ またね

MatchCall_BattlePyramidText9:: @ 82B1F24
	.string "어머 {PLAYER}!\n"
	.string "안녕 {STR_VAR_1}{K_I}야!\p"
	.string "{STR_VAR_2}에서 층을 {STR_VAR_3}개나\n"
	.string "올라갔다면서?\p"
	.string "굉장하다-\n"
	.string "나도 열심히 해야지$"
	// あら §あ§お!ｎ
	// こんにちは §いです!ｐ
	// §うで §えだんもｎ
	// かちぬいたんだって?ｐ
	// すっごいね-ｎ
	// わたしも がんばらなくちゃ

MatchCall_BattlePyramidText10:: @ 82B1FA8
	.string "{PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "층을 {STR_VAR_3}개나 올라갔다며?\p"
	.string "굉장하다\n"
	.string "나도 열심히 해야지$"
	// §あ§お こんにちはｎ
	// §い ですｐ
	// §うでｎ
	// §えだんも のぼったんですって?ｐ
	// すごいわねえｎ
	// わたしも がんばらなくちゃ

MatchCall_BattlePyramidText11:: @ 82B2022
	.string "여어여어 {PLAYER}\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "{STR_VAR_2}에서\n"
	.string "대활약하고 있는 모양이던데\l"
	.string "층을 {STR_VAR_3}개나 올라갔다며?\p"
	.string "굉장한걸 나도\n"
	.string "우승할 수 있을까?\p"
	.string "...역시 무리인가?\n"
	.string "그럼 또 보자$"
	// やあやあ §あ§おｎ
	// §いだｐ
	// §うでｎ
	// だいかつやく らしいなあｌ
	// §えだんも のぼったんだって?ｐ
	// すげえなあ おれでもｎ
	// ゆうしょう できるのかなｐ
	// ®®® できない?ｎ
	// じゃあ またな

MatchCall_BattlePyramidText12:: @ 82B20F3
	.string "여어 {PLAYER}\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}{K_I}라는 곳에서\n"
	.string "층을 {STR_VAR_3}개나 올라갔다던데?\p"
	.string "굉장한 얘기로구먼\n"
	.string "그럼 또 보세$"
	// やあ §あ§おｎ
	// §い じゃが げんきかの?ｐ
	// §う とかいう ところでｎ
	// §えだんも かちぬいたとな?ｐ
	// すごい はなし だのうｎ
	// では またの

MatchCall_BattlePyramidText13:: @ 82B2175
	.string "{PLAYER}{K_I}니?\n"
	.string "{STR_VAR_1}인데 잘 지내는가?\p"
	.string "{STR_VAR_2}에서\n"
	.string "층을 {STR_VAR_3}개나 올라갔다던데?\p"
	.string "건강해서 다행이구먼\n"
	.string "그럼 또 보세$"
	// §あ§お かい?ｎ
	// §い じゃが げんきかの?ｐ
	// §うでｎ
	// §えだんも のぼったとな?ｐ
	// げんきで いいことじゃｎ
	// では またのう

MatchCall_BattlePyramidText14:: @ 82B21FC
	.string "어머 {PLAYER} 안녕\n"
	.string "{STR_VAR_1}{K_I}야\p"
	.string "들었어!\n"
	.string "{STR_VAR_2}에서\p"
	.string "층을 {STR_VAR_3}개나\n"
	.string "올라갔다면서?\p"
	.string "굉장하다 나 감탄했어!\n"
	.string "그럼 또 보자$"
	// あら §あ§お こんにちはｎ
	// §い よｐ
	// きいたわよ!ｎ
	// §うでｐ
	// §えだんもｎ
	// かちぬいたんですって?ｐ
	// すごいわねえ かんしん しちゃうわ!ｎ
	// じゃあ またね

MatchCall_Text_Mom1:: @ 82B227B
	.string "엄마: 아빠도 너도\n"
	.string "모두 포켓몬에 열심이구나\p"
	.string "포켓몬의 매력이란\n"
	.string "대체 뭘까...\p"
	.string "엄마는 어떻냐고?\n"
	.string "엄마는 집 청소를 도와주는\l"
	.string "포켓몬이 좋단다$"
	// ママ『パパも あなたもｎ
	// みんな ポケモンに むちゅう なのねｐ
	// ポケモンの みりょく ってｎ
	// なんなの かしら……ｐ
	// わたし?ｎ
	// わたしは いえの ようじを おてつだいｌ
	// してくれる ポケモンが すきだわ

MatchCall_Text_Mom2:: @ 82B2310
	.string "엄마: 어머 {PLAYER}!\n"
	.string "아빠라면 매일 등화도시의\l"
	.string "체육관에 틀어박혀 있어!\p"
	.string "가끔씩 집에 돌아오지만\n"
	.string "잔뜩 밥을 먹고 나서\l"
	.string "다시 출근한단다!\p"
	.string "너한테 진 게\n"
	.string "어지간히도 분했나봐!$"
	// ママ『あら §あｎ
	// パパなら まいにち トウカシティのｌ
	// ジムに こもってるわよ!ｐ
	// ときどき うちに かえってきてはｎ
	// たくさん ごはんを たべてｌ
	// また でかけて いくの!ｐ
	// あなたに まけたのがｎ
	// よっぽど くやしかった みたいね!

MatchCall_Text_Mom3:: @ 82B23F3
	.string "엄마: {PLAYER}...\p"
	.string "집은 걱정하지 않아도 되니까\n"
	.string "엄마가 준 러닝슈즈가\l"
	.string "너덜너덜해질 때까지 돌아다녀봐!$"
	// ママ『§あ……ｐ
	// おうちの ことなら きにしなくて いいからｎ
	// ママが あげた ランニングシュ-ズｌ
	// ボロボロに なるまで はいてちょうだいね!

MatchCall_Text_Roxanne1:: @ 82B2456
	.string "원규: 어머 {PLAYER}님!\p"
	.string "그때 이후로 다시 트레이닝 방식을\n"
	.string "고치고 있어요!\p"
	.string "체육관을 다시 열려면\n"
	.string "조금 더 시간이 걸리겠지만\p"
	.string "만약 체육관이 다시 열린다면\n"
	.string "부디 도전해 주세요...$"
	// ツツジ『あら §あさん!ｐ
	// あれから また トレ-ニングをｎ
	// やりなおして いるところ なんですよ!ｐ
	// また ジムを さいかい するためにはｎ
	// もうすこし じかんが かかりますがｐ
	// もし ジムを さいかい できたらｎ
	// ぜひまた ちょうせん してくださいね……

MatchCall_Text_Roxanne2:: @ 82B250E
	.string "원규: {PLAYER}님 축하해요!\n"
	.string "소문으로 들었습니다!\p"
	.string "이쪽은 체육관을 다시 열려면\n"
	.string "조금 더 시간이 걸리겠지만\p"
	.string "만약 체육관이 다시 열린다면\n"
	.string "부디 도전해 주세요...$"
	// ツツジ『§あさん おめでとう!ｎ
	// うわさは ききましたよ!ｐ
	// こちらは ジムを さいかい するためにはｎ
	// もうすこし じかんが かかりますがｐ
	// もし ジムを さいかい できたらｎ
	// ぜひまた ちょうせん してくださいね……

MatchCall_Text_Roxanne3:: @ 82B25C1
	.string "원규: {PLAYER}님!\n"
	.string "체육관 준비가 끝났습니다!\p"
	.string "언제든지 금탄도시를\n"
	.string "방문해 주세요!$"
	// ツツジ『§あさん!ｎ
	// ジムの じゅんびが できました!ｐ
	// いつでも カナズミ シティまでｎ
	// きてくださいな!

MatchCall_Text_Roxanne4:: @ 82B2607
	.string "원규: {PLAYER}님과\n"
	.string "승부한 건\l"
	.string "금탄체육관의 자랑이에요!$"
	// ツツジ『§あさんとｎ
	// しょうぶ できたことはｌ
	// カナズミ ジムの ほこりですよ!

MatchCall_Text_Brawly1:: @ 82B2659
	.string "철구: 안녕 {PLAYER}!\p"
	.string "너와의 승부에서\n"
	.string "정말 여러 가지를 배웠어!\p"
	.string "또 수행을 해서\n"
	.string "체육관을 다시 열 생각이야!\p"
	.string "체육관의 준비가 끝날 때까진\n"
	.string "조금 시간이 걸릴 것 같지만\p"
	.string "만약 체육관을 다시 연다면\n"
	.string "꼭 다시 도전하러 와줘...$"
	// トウキ『やあ §あ§お!ｐ
	// キミとの しょうぶでは いろんなことをｎ
	// まなばせて もらったよ!ｐ
	// また しゅぎょう しなおしてｎ
	// ジムを さいかいする つもりさ!ｐ
	// ジムの じゅんびが できるまではｎ
	// まだ じかんが かかりそう だけどｐ
	// もし ジムを さいかい できたらｎ
	// ぜひまた ちょうせん してくれよ……

MatchCall_Text_Brawly2:: @ 82B275D
	.string "철구: 안녕 {PLAYER}!\p"
	.string "네 소문은 바닷바람을 타고\n"
	.string "이 마을에까지 오고 있어!\p"
	.string "나는 아직 좀 더 수행을\n"
	.string "할 필요가 있을 거 같아\p"
	.string "체육관의 준비가 끝날 때까진\n"
	.string "조금 시간이 걸릴 것 같지만\p"
	.string "만약 체육관을 다시 연다면\n"
	.string "꼭 다시 도전하러 와줘...$"
	// トウキ『§あ§お おめでとう!ｐ
	// キミの うわさは しおかぜに のってｎ
	// このまちにも とどいて いるよ!ｐ
	// ボクのほうは まだまだ しゅぎょうをｎ
	// やりなおす ひつようが ありそうだｐ
	// ジムの じゅんびが できるまではｎ
	// まだ じかんが かかりそう だけどｐ
	// もし ジムを さいかい できたらｎ
	// ぜひまた ちょうせん してくれよ……

MatchCall_Text_Brawly3:: @ 82B286F
	.string "철구: 안녕 {PLAYER}!\n"
	.string "체육관의 준비가 끝났어!\p"
	.string "언제든지 무로마을에\n"
	.string "도전하러 와!$"
	// トウキ『§あ§お!ｎ
	// ジムの じゅんびが できたよ!ｐ
	// いつでも ムロ タウンまでｎ
	// ちょうせんしに きてくれよな!

MatchCall_Text_Brawly4:: @ 82B28D1
	.string "철구: {PLAYER} 너하곤\n"
	.string "아무리 승부를 해도 안 질려!$"
	// トウキ『§あ§お とはｎ
	// なんど しょうぶ しても あきないよ!

MatchCall_Text_Wattson1:: @ 82B2912
	.string "암페어: 오오 너였구나!\p"
	.string "난 그때 이후로 다시\n"
	.string "트레이닝을 하고 있단다!\p"
	.string "내 체육관을 다시 열려면\n"
	.string "조-금 시간이 걸릴 것 같거든!\p"
	.string "그때까지 기다리거라!\n"
	.string "와하하하핫!$"
	// テッセン『おう おまえさんか!ｐ
	// わしは あれから また トレ-ニングをｎ
	// やりなおして いるところ じゃよ!ｐ
	// わしの ジムを さいかいするにはｎ
	// まだ ち-と じかんが かかりそうじゃな!ｐ
	// それまで まっていて おくれ!ｎ
	// わっはははは!

MatchCall_Text_Wattson2:: @ 82B29CA
	.string "암페어: 와하하하핫!\p"
	.string "너 드디어 해냈구나!\n"
	.string "나도 소문을 들었단다!\p"
	.string "이쪽은 아직 좀 더 수행을\n"
	.string "할 필요가 있을 것 같구나\p"
	.string "내 체육관을 다시 열려면\n"
	.string "조-금 시간이 걸릴 것 같거든!\p"
	.string "그때까지 기다리거라!\n"
	.string "와하하하핫!$"
	// テッセン『わっははは!ｐ
	// おまえさん とうとう やったな!ｎ
	// うわさは わしの みみにも とどいとる!ｐ
	// こちらは まだまだ しゅぎょうをｎ
	// やりなおす ひつようが ありそうじゃｐ
	// わしの ジムを さいかいするにはｎ
	// まだ ち-と じかんが かかりそうじゃな!ｐ
	// それまで まっていて おくれ!ｎ
	// わっはははは!

MatchCall_Text_Wattson3:: @ 82B2AB6
	.string "암페어: 오오 너였구나!\n"
	.string "체육관의 준비가 끝났단다!\p"
	.string "언제든지 보라시티에\n"
	.string "오려무나! 와하하핫!$"
	// テッセン『おう おまえさんか!ｎ
	// ジムの じゅんびが できたぞい!ｐ
	// いつでも キンセツ シティまでｎ
	// くるがいいぞ! わっははは!

MatchCall_Text_Wattson4:: @ 82B2B01
	.string "암페어: 와하하핫!\p"
	.string "너하고 한 포켓몬 승부는\n"
	.string "찌리릿하구나!$"
	// テッセン『わっははは!ｐ
	// おまえさんとの ポケモン しょうぶはｎ
	// ビリビリと しげきてきじゃな!

MatchCall_Text_Flannery1:: @ 82B2B4D
	.string "민지: {PLAYER}...\p"
	.string "당신과의 승부에서 자신의\n"
	.string "미숙함을 배웠지만\l"
	.string "난 이렇게 끝나지 않을 거야!\p"
	.string "한 번 더 수행을 해서\n"
	.string "다시 체육관을 열겠어!\p"
	.string "그때가 온다면 {PLAYER}\n"
	.string "꼭 도전하러 와줘!$"
	// アスナ『§あさん……ｐ
	// あなたとの しょうぶで じぶんのｎ
	// みじゅくさを おもいしらされた けどｌ
	// わたしは これで おわったり しないよ!ｐ
	// もういちど しゅぎょうを しなおしてｎ
	// また ジムを さいかい するんだ!ｐ
	// そのときには §あさんｎ
	// ぜったい ちょうせんしに きてよね!

MatchCall_Text_Flannery2:: @ 82B2C0E
	.string "민지: {PLAYER} 축하해!\p"
	.string "당신의 소문은 화산의 열처럼\n"
	.string "나한테도 전해져오고 있어!\p"
	.string "이쪽도 순조롭게\n"
	.string "트레이닝이 진행되고 있지!\p"
	.string "체육관의 준비가 끝나면\n"
	.string "엔트리콜에서 이름이 있는 곳에\l"
	.string "표시가 나타날 거야!$"
	// アスナ『§あさん おめでとう!ｐ
	// あなたの うわさは かざんの ねつのようにｎ
	// わたしにも つたわって きてるよ!ｐ
	// こちらも じゅんちょうにｎ
	// トレ-ニングが すすんでるんだ!ｐ
	// ジムの じゅんびが できたらｎ
	// エントリ-コ-ルの なまえの ところにｌ
	// しるしが つくからね!

MatchCall_Text_Flannery3:: @ 82B2CF1
	.string "민지: 앗 {PLAYER}?\n"
	.string "체육관 준비는 이미 끝났어!\p"
	.string "온천에 들어가는 김에\n"
	.string "용암마을에 놀러와!$"
	// アスナ『あっ §あさん?ｎ
	// ジムの じゅんびは もうできてます!ｐ
	// おんせんに はいる ついでにｎ
	// フエン タウンまで きてくださいね!

MatchCall_Text_Flannery4:: @ 82B2D54
	.string "민지: {PLAYER}...\n"
	.string "포켓몬을 다루는 방식이\l"
	.string "점점 좋아지고 있는 것 같아!$"
	// アスナ『§あさん……ｎ
	// ポケモンの あつかいかたがｌ
	// どんどん うまくなってる きがするよ!

MatchCall_Text_Winona1:: @ 82B2DA4
	.string "은송: 안녕하세요 {PLAYER}님!\p"
	.string "당신과 승부했던 덕분에\n"
	.string "자신의 약점을 알 수 있었어요!\p"
	.string "언젠가 다시 체육관을 열 때는\n"
	.string "지지 않을 거예요!$"
	// ナギ『こんにちは §あさん!ｐ
	// あなたと しょうぶを したおかげでｎ
	// じぶんの じゃくてんが よくわかったわ!ｐ
	// いつか また ジムを さいかい できたらｎ
	// そのときは もう まけませんよ!

MatchCall_Text_Winona2:: @ 82B2E2B
	.string "은송: 해냈군요 {PLAYER}!\p"
	.string "새로운 챔피언이 탄생했다는 소문은\n"
	.string "검방울시티에도 돌고 있답니다!\p"
	.string "하지만... 다음에 승부할 때는\n"
	.string "지난번처럼은 안 될 거예요!$"
	// ナギ『やりましたね §あさん!ｐ
	// しんチャンピオン たんじょうの うわさはｎ
	// ヒワマキにも とどいて いますよ!ｐ
	// でも…… つぎに しょうぶ するときはｎ
	// このまえの ようには いきませんからね!

MatchCall_Text_Winona3:: @ 82B2EC2
	.string "은송: 저기 {PLAYER}님?\n"
	.string "체육관의 준비가 끝났어요!\p"
	.string "검방울시티에서 기다릴게요!$"
	// ナギ『ええと §あさん?ｎ
	// ジムの じゅんびが できましたよ!ｐ
	// ヒワマキ タウンで まってます!

MatchCall_Text_Winona4:: @ 82B2F16
	.string "은송: {PLAYER}님...\n"
	.string "승부에서 져도 제 날개는\l"
	.string "절대로 꺾이지 않아요!\p"
	.string "그래요 {PLAYER}님이\n"
	.string "꿈을 포기하지 않았던 것처럼!$"
	// ナギ『§あさん……ｎ
	// しょうぶに まけても わたしの つばさはｌ
	// けっして おれることは ないのです!ｐ
	// そう §あさんがｎ
	// ゆめを あきらめなかった ように!

MatchCall_Text_TateLiza1:: @ 82B2F97
	.string "풍: 앗 너는\n"
	.string "란: {PLAYER}{K_I}구나!\p"
	.string "풍: 우린 체육관을 다시 열기 위해\n"
	.string "란: 계속 수행하고 있어!\p"
	.string "풍: 체육관의 준비가 끝나면\n"
	.string "란: 체육관의 준비가 끝나면\p"
	.string "풍: 엔트리콜의 이름에\n"
	.string "란: 표시가 붙을 테니 참고해!$"
	// フウ『あっ あなたはｎ
	// ラン『§あさん ですね!ｐ
	// フウ『ぼくたち ジムを さいかい するためｎ
	// ラン『しゅぎょう しなおして いるんです!ｐ
	// フウ『ジムの じゅんびが できたらｎ
	// ラン『ジムの じゅんびが できたらｐ
	// フウ『エントリ-コ-ルの なまえにｎ
	// ラン『しるしが つくので わかるんです!

MatchCall_Text_TateLiza2:: @ 82B306E
	.string "풍: {PLAYER} 축하해!\n"
	.string "란: {PLAYER} 축하해!\p"
	.string "풍: 우리 둘은\n"
	.string "란: 아직 수행 중이야!\p"
	.string "풍: 조금 더 시간이 걸리겠지만\n"
	.string "란: 만약 체육관이 다시 열린다면\p"
	.string "풍: 엔트리콜의 이름에\n"
	.string "란: 표시가 붙을 테니 참고해!$"
	// フウ『§あさん おめでとう!ｎ
	// ラン『§あさん おめでとう!ｐ
	// フウ『ぼくたち ふたりはｎ
	// ラン『まだ しゅぎょうちゅう!ｐ
	// フウ『もうすこし じかんが かかるけどｎ
	// ラン『もし ジムを さいかい できたらｐ
	// フウ『エントリ-コ-ルの なまえにｎ
	// ラン『しるしが つくから わかりますよ!

MatchCall_Text_TateLiza3:: @ 82B3158
	.string "풍: {PLAYER}!\n"
	.string "란: {PLAYER}!\p"
	.string "풍: 체육관의 준비가 끝났어!\n"
	.string "란: 체육관의 준비가 끝났어!\p"
	.string "풍: 언제든지 이끼시티로\n"
	.string "란: 찾아와줘!$"
	// フウ『§あさん!ｎ
	// ラン『§あさん!ｐ
	// フウ『ジムの じゅんびが できました!ｎ
	// ラン『ジムの じゅんびが できました!ｐ
	// フウ『いつでも トクサネ シティまでｎ
	// ラン『きてくださいね!

MatchCall_Text_TateLiza4:: @ 82B31CD
	.string "풍: {PLAYER}{K_WAGWA}의 승부는\n"
	.string "란: 우리에게 소중한 경험이야\p"
	.string "풍: 언젠가 다시 세 명이서\n"
	.string "란: 승부할 수 있으면 좋겠다$"
	// フウ『§あさんとの しょうぶはｎ
	// ラン『わたしたちの だいじな けいけんｐ
	// フウ『いつか また 3にんでｎ
	// ラン『しょうぶが できると いいですね

MatchCall_Text_Juan1:: @ 82B3249
	.string "아단: 호오...\n"
	.string "{PLAYER}{KUN}...이었군요\p"
	.string "유와의 배틀은\n"
	.string "처음으로 윤진과 만났을 때를\l"
	.string "떠올리게 했습니다\p"
	.string "어쩌면 유는\n"
	.string "윤진을 넘어설 정도의 지니어스!\l"
	.string "즉 천재일지도 모릅니다$"
	// アダン『ほ……ｎ
	// §あ§お…… でしたねｐ
	// ユ-との たたかいはｎ
	// はじめて ミクリと であったときをｌ
	// おもいださせて くれましたよｐ
	// もしかすると ユ-はｎ
	// ミクリを こえるほどの ジ-ニアス!ｌ
	// すなわち てんさい かもしれません

MatchCall_Text_Juan2:: @ 82B32EC
	.string "아단: 후... {PLAYER}{KUN}\n"
	.string "마침내 해낸 모양이군요\p"
	.string "역시 제 사람 보는 눈은\n"
	.string "틀리지 않았습니다...\p"
	.string "강함을 갈고닦은 유와\n"
	.string "꼭 또 승부하고 싶군요$"
	// アダン『ふ…… §あ§おｎ
	// ついに やりとげた ようですねｐ
	// やはり わたくしの ひとを みるめはｎ
	// まちがって いなかった……ｐ
	// つよさを きわめた ユ-とはｎ
	// ぜひ また しょうぶ したい ものです

MatchCall_Text_Juan3:: @ 82B33AA
	.string "아단: 후후... {PLAYER}{KUN}\p"
	.string "제 루네시티 체육관이\n"
	.string "다시 오픈했습니다\p"
	.string "제 모습을 보고 싶다면\n"
	.string "뭐 언제든지 오시지요$"
	// アダン『ほっほ…… §あ§おｐ
	// わが ルネシティ ジムがｎ
	// ふたたび オ-プン したのですよｐ
	// わたくしの すがたを みたくなったらｎ
	// まあ いつでも おいでなさい

MatchCall_Text_Juan4:: @ 82B341E
	.string "아단: {PLAYER}{KUN}...\p"
	.string "유와 연주하는 포켓몬 승부는\n"
	.string "세련된 음악과도 같아서\l"
	.string "하트에 깊은 울림을 줍니다...\p"
	.string "눈을 감으면 멜로디에 맞춰\n"
	.string "우아하게 춤추는 유의 모습이...$"
	// アダン『§あ§お……ｐ
	// ユ-と かなでる ポケモン しょうぶはｎ
	// せんれんされた おんがくにも にてｌ
	// ハ-トに ふかく ひびいて きます……ｐ
	// めを とじれば メロディ-に あわせてｎ
	// ゆうがに まう ユ-の すがたが……

MatchCall_Text_Sidney:: @ 82B34CC
	.string "혁진: 여어 {PLAYER}!\p"
	.string "나와 포켓몬 승부하고 싶다면\n"
	.string "언제든지 포켓몬리그로 오라고!\p"
	.string "난 항상 여기 있을 테니까\n"
	.string "기다리고 있는다!$"
	// カゲツ『よお §あ!ｐ
	// おれと ポケモン しょうぶ したけりゃｎ
	// いつでも ポケモン リ-グに おいで!ｐ
	// おれは いつでも ここに いるからなｎ
	// じゃあ まってるぜ!

MatchCall_Text_Phoebe:: @ 82B3561
	.string "회연: 안-녕 {PLAYER}!\p"
	.string "너와 포켓몬의 유대감이\n"
	.string "얼마나 깊어졌는지\l"
	.string "가끔씩 여기로 보여주러 와!$"
	// フヨウ『ハ-イ §あ!ｐ
	// あなたと ポケモンの きずながｎ
	// どれぐらい ふかく なったかｌ
	// たまには ここまで みせに きてよね!

MatchCall_Text_Glacia:: @ 82B35E4
	.string "미혜: 안녕하세요 {PLAYER}\p"
	.string "당신은 그 강함에\n"
	.string "도취해 있진 않겠지요\p"
	.string "뜨거운 마음을 조금\n"
	.string "식히고 싶다면\l"
	.string "포켓몬리그로 오세요...$"
	// プリム『こんにちは §あｐ
	// あなたは その つよさにｎ
	// おぼれたり していない でしょうねｐ
	// あつい きもちを すこしだけｎ
	// ひやしたいと おもったらｌ
	// ポケモン リ-グに いらっしゃい……

MatchCall_Text_Drake:: @ 82B368B
	.string "권수: 이 목소린 {PLAYER}{K_I}인가\n"
	.string "건강한 모양이군...\p"
	.string "최근 포켓몬리그와는 별개로\n"
	.string "트레이너의 실력을 겨루는\l"
	.string "배틀프런티어라고 하는 시설이\l"
	.string "생긴 듯하지만...\p"
	.string "진정한 승부를 하고 싶다면\n"
	.string "역시 포켓몬리그가 최고지!\p"
	.string "너도 그리 생각하지 않나 {PLAYER}?$"
	// ゲンジ『そのこえは §あかｎ
	// げんきそう だな……ｐ
	// さいきん ポケモン リ-グとは べつにｎ
	// トレ-ナ-の うでを きそわせるｌ
	// バトル フロンティア とかいう しせつがｌ
	// あるらしいが……ｐ
	// ほんとうの しょうぶを したいのならｎ
	// やはり ポケモン リ-グだ!ｐ
	// なあ §あも そうおもう だろう?

MatchCall_Text_Wallace:: @ 82B3790
	.string "윤진: 안녕 {PLAYER}\n"
	.string "성호는 만나봤어?\p"
	.string "그는...\n"
	.string "사실 엄청 강하면서\p"
	.string "그다지 포켓몬 승부를 하지 않고\n"
	.string "희귀한 돌만 찾아다니는\l"
	.string "별난 사람이야\p"
	.string "어딘가의 동굴이나 바위산에\n"
	.string "틀어박혀 있는 게 아닐까\p"
	.string "희귀한 돌이라고 하면\n"
	.string "난 운석 정도밖에\l"
	.string "안 떠오르니까 말이지...$"
	// ミクリ『やあ §あ§おｎ
	// きみは ダイゴには あったかな?ｐ
	// かれって……ｎ
	// ほんとうは ものすごく つよいのにｐ
	// あまり ポケモン しょうぶを しないでｎ
	// めずらしい いしを さがして ばかりいるｌ
	// かわりもの なんだよｐ
	// どこかの どうくつか いわやまにｎ
	// もぐってるんじゃ ないかなｐ
	// めずらしい いし なんてｎ
	// わたしには いんせき ぐらいしかｌ
	// おもい うかばないんだけど……

MatchCall_Text_MayRayquazaCall: @ 82B38C1
	.string "...... ...... ......\n"
	.string "...... ...... ...... 삑!\p"
	.string "봄이: 앗 {PLAYER}!?\p"
	.string "나 있지 방금까지 황금마을에\n"
	.string "있었는데\l"
	.string "커다란 초록색 포켓몬이\l"
	.string "하늘을 날아가는 걸 봤어!\p"
	.string "나...\n"
	.string "그런 포켓몬은 본 적 없어!\p"
	.string "뭐였을까 혹시 이거\n"
	.string "대발견 아냐!?\p"
	.string "...... ...... ......\n"
	.string "...... ...... ...... 딸깍-$"
	// …… …… ……ｎ
	// …… …… …… ピッ!ｐ
	// ハルカ『あっ §あ§お!?ｐ
	// あたしね さっきまで キナギ タウンにｎ
	// いってたんだけどｌ
	// おおきな みどりいろの ポケモンがｌ
	// そらを とんで いくのを みたの!ｐ
	// あたし……ｎ
	// あんな ポケモン みたこと ない!ｐ
	// なんだろう もしかしたら これってｎ
	// だいはっけん!?ｐ
	// …… …… ……ｎ
	// …… …… …… ツ-

MatchCall_Text_BrendanRayquazaCall: @ 82B39C6
	.string "...... ...... ......\n"
	.string "...... ...... ...... 삑!\p"
	.string "휘웅: 오 {PLAYER}!?\p"
	.string "나 방금까지 황금마을에\n"
	.string "있었는데 말이지\l"
	.string "거대한 초록색 포켓몬이\l"
	.string "하늘을 날아가는 걸 봤어!\p"
	.string "그런 굉장한 녀석 본 적 없어\n"
	.string "{PLAYER}에게도 보여주고 싶었는데!\p"
	.string "...... ...... ......\n"
	.string "...... ...... ...... 딸깍-$"
	// …… …… ……ｎ
	// …… …… …… ピッ!ｐ
	// ユウキ『おっ §あ!?ｐ
	// オレ さっきまで キナギ タウンにｎ
	// いってたんだけどさｌ
	// でっかい みどりいろの ポケモンがｌ
	// そらを とんで いくのを みたんだ!ｐ
	// あんな すごいの みたこと ないよｎ
	// §あにも みせたかったなあ!ｐ
	// …… …… ……ｎ
	// …… …… …… ツ-

MatchCall_Text_May1:: @ 2B3AB3
	.string "봄이: 앗 {PLAYER}{K_AYA}!\p"
	.string "하기노인은\n"
	.string "선원에서 은퇴했지만\p"
	.string "가끔씩 피코와 함께\n"
	.string "바다로 나가는 걸 봤어\p"
	.string "분명 아직도 바다가 좋은 거겠지!$"
	// ハルカ『あっ §あ§お!ｐ
	// ハギろうじんはｎ
	// ふなのりを いんたい したけどｐ
	// ときどき ピ-コちゃんと いっしょにｎ
	// うみに でてるのを みかけるよｐ
	// きっと いまも うみが すきなんだね!

MatchCall_Text_May2:: @ 2B3B3F
	.string "봄이: 있지 있지 {PLAYER}{K_AYA}!\p"
	.string "등화나 무로같이\n"
	.string "조그만 마을에도 체육관이 있는데\p"
	.string "커다란 항구 도시인 잿빛에는\n"
	.string "어째선지 체육관이 없단 말이지\p"
	.string "언젠가 체육관이 생기면 나\n"
	.string "체육관 관장에 입후보해 볼까-$"
	// ハルカ『ねえねえ §あ§お!ｐ
	// トウカや ムロみたいなｎ
	// ちいさい まちに ジムが あるのにｐ
	// おおきな みなとまちの カイナにはｎ
	// なぜか ジムが ないのよねｐ
	// いつか ジムが できたら あたしｎ
	// ジムリ-ダ-に りっこうほ しよっかな-

MatchCall_Text_May3:: @ 2B3C13
	.string "봄이: 앗 {PLAYER}{K_AYA}!\p"
	.string "그러고 보니 금탄도시에\n"
	.string "풀베기아저씨라는 사람의\l"
	.string "집이 있었지?\p"
	.string "보라시티에는\n"
	.string "그 사람의 동생이 살고 있대!\p"
	.string "이름은 뭐인 줄 알아?\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\p"
	.string "바위깨기 아저씨라고 해!$"
	// ハルカ『あっ §あ§お!ｐ
	// そういえば カナズミシティにｎ
	// いあいぎりオヤジ っていう ひとのｌ
	// いえが あったでしょ?ｐ
	// キンセツシティにはｎ
	// その おとうとが すんでるんだって!ｐ
	// どんな なまえだと おもう?ｐ
	// …… …… ……ｎ
	// …… …… ……ｐ
	// いわくだきオヤジ っていうの!

MatchCall_Text_May4:: @ 2B3CF3
	.string "봄이: {PLAYER}{K_AYA}?\p"
	.string "금잔터널은\n"
	.string "금탄과 잔디를 이어주니까\l"
	.string "금잔터널이라고 이름붙인 거구나!$"
	// ハルカ『§あ§お?ｐ
	// カナシダトンネル ってｎ
	// カナズミと シダケを むすぶからｌ
	// カナシダトンネル って いうのよね!

MatchCall_Text_May5:: @ 2B3D4B
	.string "봄이: {PLAYER}{K_AYA} 잘 지내-?\p"
	.string "난 지금\n"
	.string "111번 도로에 와 있어!\p"
	.string "사막의 위쪽에 살고 있는\n"
	.string "할머니의 집에서\l"
	.string "하룻밤 자고 가려고!$"
	// ハルカ『§あ§お げんき-?ｐ
	// あたしは いまｎ
	// 111ばんどうろに きているの!ｐ
	// さばくの うえのほうに すんでるｎ
	// おばあさんの ところでｌ
	// ひとやすみ していく つもりよ!

MatchCall_Text_May6:: @ 2B3DD1
	.string "봄이: 앗 {PLAYER}{K_AYA}!\p"
	.string "사막에 환영탑이라고 하는 건물이\n"
	.string "서 있다는 거 알아?\p"
	.string "신기루처럼\n"
	.string "보였다 안 보였다 한대!\p"
	.string "나도 한번 보고 싶다-$"
	// ハルカ『あっ §あ§お!ｐ
	// さばくに げんえいのとう っていうのがｎ
	// たってるの しってる?ｐ
	// しんきろう みたいにｎ
	// みえたり みえなかったり するんだって!ｐ
	// あたしも みてみたいな-

MatchCall_Text_May7:: @ 2B3E69
	.string "봄이: {PLAYER}{K_AYA} 야호-!\p"
	.string "나는 지금\n"
	.string "119번 도로에 와 있어!\p"
	.string "이 주변엔 커다란 강이 있고\n"
	.string "비도 계속 내리니까\l"
	.string "흠뻑 젖어버렸지 뭐야!$"
	// ハルカ『§あ§お やっほ-!ｐ
	// あたしは いまｎ
	// 119ばんどうろに きているの!ｐ
	// このあたりは おおきな かわが あるしｎ
	// あめも しょっちゅう ふってるからｌ
	// ずぶぬれに なっちゃったよ!

MatchCall_Text_May8:: @ 2B3ECD
	.string "봄이: {PLAYER}{K_AYA}!\p"
	.string "송화산에는 수명이 다한\n"
	.string "포켓몬들이 잠들어 있어!\p"
	.string "그래서인지 출현하는 포켓몬도\n"
	.string "고스트타입이 많아!$"
	// ハルカ『§あ§お!ｐ
	// おくりびやまには じゅみょうを おえたｎ
	// ポケモンが まつられてるの!ｐ
	// そのせいか しゅつげんする ポケモンもｎ
	// ゴ-ストタイプが おおいのよ!

MatchCall_Text_May9:: @ 2B3F2B
	.string "봄이: 있지 있지 {PLAYER}{K_AYA}!\p"
	.string "나 다시 용암마을의\n"
	.string "온천에 가볼까 생각했는데\p"
	.string "울퉁불퉁산길에\n"
	.string "인상 나쁜 사람들이 바글바글해서\l"
	.string "왠지 불길한 느낌이었어!$"
	// ハルカ『ねえねえ §あ§お!ｐ
	// あたし また フエンタウンのｎ
	// おんせんに いこうと おもったんだけどｐ
	// デコボコさんどうにｎ
	// にんそうの わるいのが うろついていてｌ
	// なんか いや-な かんじ だったわ!

MatchCall_Text_May10:: @ 2B3FFB
	.string "봄이: 앗 {PLAYER}{K_AYA}!\p"
	.string "해양관장이 잠수정으로\n"
	.string "해저동굴을 발견했다고\l"
	.string "뉴스에 나왔던데 봤어?$"
	// ハルカ『あっ §あ§お!ｐ
	// クスノキかんちょうが せんすいていでｎ
	// かいていどうくつを はっけんした ってｌ
	// ニュ-スで やってたけど みた?

MatchCall_Text_May11:: @ 2B402B
	.string "봄이: 있지 있지 {PLAYER}{K_AYA}!\p"
	.string "배가 없어도 포켓몬의 기술로\n"
	.string "바다 위를 건널 수 있다니\l"
	.string "굉장하지!\p"
	.string "하지만 그것뿐만이 아니라\n"
	.string "포켓몬과 함께 해저로\l"
	.string "잠수하는 기술도 있대!$"
	// ハルカ『ねえねえ §あ§お!ｐ
	// ふねが なくても ポケモンの わざでｎ
	// うみのうえを わたって いけるってｌ
	// すごいよね!ｐ
	// でも それだけじゃなくてｎ
	// ポケモンと いっしょに うみのそこにｌ
	// もぐれちゃう わざも あるんだって!

MatchCall_Text_May12:: @ 2B414B
	.string "봄이: {PLAYER}{K_AYA} 고생이 많겠네!\p"
	.string "바다 위에선 보이는데 반대편으로\n"
	.string "갈 수 없는 곳들은\p"
	.string "어딘가에서 일단 잠수한 뒤\n"
	.string "해저의 길로 빠져나가서\l"
	.string "반대편의 수면으로 나오면 돼!$"
	// ハルカ『§あ§お おつかれ!ｐ
	// うみのうえで みえてるのに むこうがわへｎ
	// いけない ところ なんかはｐ
	// どこかから いったん もぐってｎ
	// かいていの みちを とおりぬけてｌ
	// むこうの すいめんに でれば いいの!

MatchCall_Text_May13:: @ 2B4228
	.string "봄이: 안-녕 {PLAYER}{K_AYA}\p"
	.string "어때? 도감은 순조롭게\n"
	.string "채우고 있어?\p"
	.string "있지 소문을 들었는데\n"
	.string "어딘가에 초 고대포켓몬이라는 게\l"
	.string "세 마리나 숨어있나 봐!\p"
	.string "으-음 한 마리라도 좋으니까\n"
	.string "한번 보고 싶다...$"
	// ハルカ『は-い §あ§おｐ
	// どう? ずかんは じゅんちょうにｎ
	// うまっていってる?ｐ
	// あのね うわさで きいたんだけどｎ
	// どこかに ちょうこだいポケモン というのがｌ
	// 3しゅるいも いるらしいの!ｐ
	// う-ん 1しゅるい だけでも いいからｎ
	// みてみたいなあ……

MatchCall_Text_May14:: @ 2B42E0
	.string "봄이: {PLAYER}{K_AYA}!\n"
	.string "소문은 들었어!\p"
	.string "루네의 체육관 관장도 이겼다면서?\n"
	.string "그럼 이제 얼마 안 남았네!$"
	// ハルカ『§あ§お!ｎ
	// うわさは きいたよ!ｐ
	// ルネの ジムリ-ダ-にも かったって?ｎ
	// ということは もうひといき だね!

MatchCall_Text_May15:: @ 2B4350
	.string "봄이: 이제 호연지방에서\n"
	.string "{PLAYER}{K_EULREUL} 모르는\l"
	.string "트레이너는 없어!\p"
	.string "내가 {PLAYER}하고\n"
	.string "친구라고 말하면\l"
	.string "다들 깜짝 놀란다니까!$"
	// ハルカ『もう ホウエンちほうでｎ
	// §あ§おを しらないｌ
	// トレ-ナ- なんて いないんだよ!ｐ
	// あたしが §あ§おとｎ
	// ともだちだ っていうとｌ
	// みんな ビックリ するんだから!

MatchCall_Text_Brendan1:: @ 2B43EF
	.string "휘웅: 오 {PLAYER}{K_AYA}!\p"
	.string "하기노인은\n"
	.string "선원에서 은퇴했지만\p"
	.string "가끔씩 피코와 함께\n"
	.string "바다로 나가는 걸 봤어\p"
	.string "분명 아직도 바다가 좋은 거겠지!$"
	// ユウキ『おっ §あ!ｐ
	// ハギろうじんはｎ
	// ふなのりを いんたい したけどｐ
	// ときどき ピ-コちゃんと いっしょにｎ
	// うみに でてるのを みかけるんだｐ
	// きっと いまも うみが すきなんだろうな!

MatchCall_Text_Brendan2:: @ 2B4486
	.string "휘웅: 안녕 {PLAYER}{K_AYA}!\p"
	.string "등화나 무로같이\n"
	.string "조그만 마을에도 체육관이 있는데\p"
	.string "커다란 항구 도시인 잿빛에는\n"
	.string "어째선지 체육관이 없단 말이지\p"
	.string "언젠가 체육관이 생기면 나\n"
	.string "체육관 관장에 입후보해 볼까$"
	// ユウキ『やあ §あ!ｐ
	// トウカや ムロみたいなｎ
	// ちいさい まちに ジムが あるのにｐ
	// おおきな みなとまちの カイナにはｎ
	// なぜか ジムが ないんだよなｐ
	// いつか ジムが できたら オレｎ
	// ジムリ-ダ-に りっこうほ しようかな

MatchCall_Text_Brendan3:: @ 2B4560
	.string "휘웅: 오 {PLAYER}{K_AYA}!\p"
	.string "그러고 보니 금탄도시에\n"
	.string "풀베기아저씨라는 사람의\l"
	.string "집이 있었잖아?\p"
	.string "보라시티에는\n"
	.string "그 사람의 동생이 살고 있대!\p"
	.string "이름이 뭐인 줄 알아?\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\p"
	.string "바위깨기 아저씨래!$"
	// ユウキ『おっ §あ!ｐ
	// そういえば カナズミシティにｎ
	// いあいぎりオヤジ っていう ひとのｌ
	// いえが あっただろう?ｐ
	// キンセツシティにはｎ
	// その おとうとが すんでるんだって!ｐ
	// どんな なまえだと おもう?ｐ
	// …… …… ……ｎ
	// …… …… ……ｐ
	// いわくだきオヤジ だってさ!

MatchCall_Text_Brendan4:: @ 2B463F
	.string "휘웅: 이 목소린 {PLAYER}?\p"
	.string "금잔터널은\n"
	.string "금탄과 잔디를 이어주니까\l"
	.string "금잔터널이라고 불리는 거야\p"
	.string "너... 알고 있었어?$"
	// ユウキ『そのこえは §あ?ｐ
	// カナシダトンネル ってｎ
	// カナズミと シダケを むすぶからｌ
	// カナシダトンネル なんだよｐ
	// おまえ…… しってたか?

MatchCall_Text_Brendan5:: @ 2B46B7
	.string "휘웅: {PLAYER}{K_AYA} 잘 지내?\p"
	.string "난 지금\n"
	.string "111번 도로에 와 있어!\p"
	.string "사막의 위쪽에 살고 있는\n"
	.string "할머니의 집에서\l"
	.string "하룻밤 자고 가려고!\p"
	.string "너도 한번 찾아와봐!$"
	// ユウキ『§あ げんきか?ｐ
	// オレは いまｎ
	// 111ばんどうろに きてるんだ!ｐ
	// さばくの うえのほうに すんでるｎ
	// ばあさんの ところでｌ
	// ひとやすみ していく つもりさ!ｐ
	// ちかくまで きたらｎ
	// おまえも よっていくと いいよ!

MatchCall_Text_Brendan6:: @ 2B4761
	.string "휘웅: 앗 {PLAYER}{K_AYA}!\p"
	.string "사막에 환영탑이라는 건물이\n"
	.string "서 있는 거 알아?\p"
	.string "신기루처럼\n"
	.string "보였다 안 보였다 한대!\p"
	.string "나도 한번 보고 싶다-$"
	// ユウキ『あっ §あ!ｐ
	// さばくに げんえいのとう っていうのがｎ
	// たってるの しってるか?ｐ
	// しんきろう みたいにｎ
	// みえたり みえなかったり するんだよ!ｐ
	// オレも みてみたいな-

MatchCall_Text_Brendan7:: @ 2B47F4
	.string "휘웅: 누구? {PLAYER}{K_I}야?\p"
	.string "난 지금\n"
	.string "119번 도로에 와 있어!\p"
	.string "이 주변은 커다란 강이 있고\n"
	.string "항상 비가 오니까\l"
	.string "흠뻑 젖어버렸어!$"
	// ユウキ『だれ? §あか?ｐ
	// オレは いまｎ
	// 119ばんどうろに きてるんだ!ｐ
	// このへんは でっかい かわが あるしｎ
	// いっつも あめが ふってるからｌ
	// ずぶぬれに なっちまったよ!

MatchCall_Text_Brendan8:: @ 2B4882
	.string "휘웅: {PLAYER}{K_AYA}!\p"
	.string "송화산에는 수명이 다한\n"
	.string "포켓몬들이 잠들어 있어!\p"
	.string "그래서인지 출현하는 포켓몬도\n"
	.string "고스트타입이 많단 말이지!$"
	// ユウキ『§あ!ｐ
	// おくりびやまには じゅみょうを おえたｎ
	// ポケモンが まつられてるんだ!ｐ
	// そのせいか しゅつげんする ポケモンもｎ
	// ゴ-ストタイプが おおいんだよな!

MatchCall_Text_Brendan9:: @ 2B4909
	.string "휘웅: 있지 있지 {PLAYER}{K_AYA}!\p"
	.string "나 다시 용암마을의\n"
	.string "온천에 가려고 했는데\p"
	.string "울퉁불퉁산길을 지나는 도중에\n"
	.string "인상 나쁜 사람들을 봤어!\p"
	.string "그거 마그마단... 아니었을까!?$"
	// ユウキ『なあなあ §あ!ｐ
	// オレ また フエンタウンのｎ
	// おんせんに いこうと おもったんだけどｐ
	// デコボコさんどうの とちゅうにｎ
	// にんそうの わるいのが いたんだよ!ｐ
	// あれって マグマだん…… だよな!?

MatchCall_Text_Brendan10:: @ 2B49C4
	.string "휘웅: 오 {PLAYER}{K_AYA}!\p"
	.string "해양관장이 잠수정으로\n"
	.string "해저동굴을 발견했다고\l"
	.string "뉴스에 나왔던데 봤어?$"
	// ユウキ『おっ §あ!ｐ
	// クスノキかんちょうが せんすいていでｎ
	// かいていどうくつを はっけんした ってｌ
	// ニュ-スで やってたけど みたか?

MatchCall_Text_Brendan11:: @ 2B4A44
	.string "휘웅: 있지 있지 {PLAYER}{K_AYA}!\p"
	.string "배가 없어도 포켓몬의 기술로\n"
	.string "바다 위를 건널 수 있다니\l"
	.string "왠지 굉장하지 않아!?\p"
	.string "게다가 포켓몬과 함께\n"
	.string "해저로 잠수할 수 있는 기술도 있대!\p"
	.string "포켓몬은 뭐든지 할 수 있구나-!$"
	// ユウキ『なあなあ §あ!ｐ
	// ふねが なくても ポケモンの わざでｎ
	// うみのうえを わたって いけるってｌ
	// なんだか すごくないか!?ｐ
	// しかも ポケモンと いっしょにｎ
	// うみのそこに もぐれる わざも あるって!ｐ
	// ポケモンって なんでも できるんだな-!

MatchCall_Text_Brendan12:: @ 2B4B28
	.string "휘웅: {PLAYER}{K_AYA} 고생이 많겠다!\p"
	.string "바다 위에선 보이는데 반대편으로\n"
	.string "갈 수 없는 곳들은\p"
	.string "어딘가에서 일단 잠수한 뒤\n"
	.string "해저의 길로 빠져나가서\l"
	.string "반대편의 수면으로 나오면 돼!$"
	// ユウキ『§あ おつかれ!ｐ
	// うみのうえで みえてるのに むこうがわへｎ
	// いけない ところ なんかはｐ
	// どこかから いったん もぐってｎ
	// かいていの みちを とおりぬけてｌ
	// むこうの すいめんに でれば いいんだ!

MatchCall_Text_Brendan13:: @ 2B4C15
	.string "휘웅: 안-녕 {PLAYER}{K_AYA}!\p"
	.string "어때? 도감은 순조롭게\n"
	.string "채우고 있어?\p"
	.string "있잖아 소문으로 들었는데\n"
	.string "어딘가에 초 고대포켓몬이라는 게\l"
	.string "세 마리나 숨어있나 봐!\p"
	.string "으-음 한 마리라도 좋으니까\n"
	.string "잡아보고 싶다...$"
	// ユウキ『お-す §あ!ｐ
	// どうだ? ずかんは じゅんちょうにｎ
	// うまっていってるか?ｐ
	// あのな うわさで きいたんだけどｎ
	// どこかに ちょうこだいポケモン ってのがｌ
	// 3しゅるいも いるらしいんだよ!ｐ
	// う-ん 1しゅるい だけでも いいからｎ
	// つかまえて みたいよなあ……

MatchCall_Text_Brendan14:: @ 2B4CD8
	.string "휘웅: {PLAYER}{K_AYA}!\n"
	.string "소문은 들었어!\p"
	.string "루네의 체육관 관장을 이겼다면서?\n"
	.string "굉장하다 이제 얼마 안 남았네!$"
	// ユウキ『§あ!ｎ
	// うわさは きいたよ!ｐ
	// ルネの ジムリ-ダ-にも かったって?ｎ
	// すげえなあ もうひといき だな!

MatchCall_Text_Brendan15:: @ 2B4D46
	.string "휘웅: 이제 호연지방에\n"
	.string "{PLAYER}{K_EULREUL} 모르는\l"
	.string "트레이너는 없어!\p"
	.string "내가 {PLAYER}하고\n"
	.string "친구라고 말하면\l"
	.string "다들 부러워한다고!$"
	// ユウキ『もう ホウエンちほうでｎ
	// §あのこと しらないｌ
	// トレ-ナ- なんて いないんだ!ｐ
	// オレが §あとｎ
	// ともだちだ っていうとｌ
	// みんな うらやましそうに するよ!

MatchCall_Text_Wally1:: @ 2B4DE2
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I've been getting healthier and\n"
	.string "more physically fit.\p"
	.string "I hope I can become a TRAINER like\n"
	.string "you soon, {PLAYER}!$"

MatchCall_Text_Wally2:: @ 2B4E57
	.string "WALLY: {PLAYER}, hello!\p"
	.string "After RUSTURF TUNNEL went\n"
	.string "through, WANDA's been very happy!$"

MatchCall_Text_Wally3:: @ 2B4EA5
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "I… I left my uncle's place in\n"
	.string "VERDANTURF without telling anyone.\p"
	.string "I wonder if he's furious with me…\p"
	.string "{PLAYER}, you understand how\n"
	.string "I feel, don't you?$"

MatchCall_Text_Wally4:: @ 2B4F41
	.string "WALLY: {PLAYER}?\n"
	.string "It's me, WALLY!\p"
	.string "The world of TRAINERS is amazing!\p"
	.string "When I have my POKéMON with me,\n"
	.string "all sorts of people say hi!\p"
	.string "It's as if everyone's getting\n"
	.string "connected through POKéMON!$"

MatchCall_Text_Wally5:: @ 2B4FF3
	.string "WALLY: {PLAYER}? It's awesome!\n"
	.string "That RALTS we caught together?\l"
	.string "It evolved, {PLAYER}!\p"
	.string "Maybe I'm talented…\p"
	.string "Oh, but I shouldn't get a big head\n"
	.string "like that!\p"
	.string "After all, it's the POKéMON that\n"
	.string "should be praised!$"

MatchCall_Text_Wally6:: @ 2B50B1
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "WALLY appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Wally7:: @ 2B5100
	.string "WALLY: Oh, {PLAYER}!\p"
	.string "Before I met you, I hardly ever\n"
	.string "left my house…\p"
	.string "But now, I'm on an adventure with\n"
	.string "my very own POKéMON…\p"
	.string "{PLAYER}…\n"
	.string "Thank you…$"

MatchCall_Text_Scott1:: @ 2B5184
	.string "SCOTT: Howdy, {PLAYER}{KUN}!\p"
	.string "You know how POKéMON can be found\n"
	.string "everywhere?\p"
	.string "Like in the mountains, in the sea,\n"
	.string "in tall grass anywhere?\p"
	.string "Just like POKéMON, you can find\n"
	.string "TRAINERS everywhere, too.\p"
	.string "As a result, I have to hurry\n"
	.string "everywhere, too. Busy, busy!$"

MatchCall_Text_Scott2:: @ 2B5275
	.string "SCOTT: I'm on ROUTE 119 right now.\n"
	.string "It's teeming with TRAINERS!\p"
	.string "It's also overgrown with tall grass\n"
	.string "everywhere, it seems.\p"
	.string "Walking around in shorts here\n"
	.string "makes me all ticklish!$"

MatchCall_Text_Scott3:: @ 2B5323
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Have you had the chance to climb\n"
	.string "MT. PYRE?\p"
	.string "The place is a memorial to POKéMON\n"
	.string "that have passed away.\p"
	.string "It's somewhere every TRAINER\n"
	.string "should climb to the top of once.$"

MatchCall_Text_Scott4:: @ 2B53DB
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "I've been hearing about these odd\n"
	.string "gangs being a nuisance.\p"
	.string "TEAM MAGMA and TEAM AQUA,\n"
	.string "I think they were.\p"
	.string "I would think there'd be some\n"
	.string "skilled TRAINERS among them.\p"
	.string "…But if they're thugs…$"

MatchCall_Text_Scott5:: @ 2B54A5
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Might there be tough TRAINERS\n"
	.string "at the bottom of the sea?\p"
	.string "I can't go check for myself.\n"
	.string "I can't swim, for one.\l"
	.string "And I don't raise POKéMON…$"

MatchCall_Text_Scott6:: @ 2B5541
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "You know that you can challenge\n"
	.string "the POKéMON LEAGUE when you've\l"
	.string "collected all the GYM BADGES?\p"
	.string "With your talent, becoming the\n"
	.string "CHAMPION isn't a pipe dream.\p"
	.string "But did you know?\n"
	.string "There's somewhere even better.\p"
	.string "But, that's all I'm willing to say\n"
	.string "for the time being.\p"
	.string "It's something you can look\n"
	.string "forward to.\p"
	.string "When you've won your way through\n"
	.string "the POKéMON LEAGUE into the HALL\l"
	.string "OF FAME!$"

MatchCall_Text_Scott7:: @ 2B56CA
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT appears to be out of\n"
	.string "the POKéNAV's service area…$"

MatchCall_Text_Norman1:: @ 82B5719
	.string "DAD: In RUSTBORO, there's a man\n"
	.string "that goes by the odd name of\l"
	.string "the CUTTER.\p"
	.string "If you're in the area, you should\n"
	.string "pay him a visit.$"

MatchCall_Text_Norman2:: @ 82B5795
	.string "DAD: Hm… Little by little, but also\n"
	.string "very surely, you're getting\l"
	.string "tougher, {PLAYER}.\p"
	.string "The stronger you get, the farther\n"
	.string "and higher you soar from Mother\l"
	.string "and me…\p"
	.string "This feeling is hard to explain.$"

MatchCall_Text_Norman3:: @ 82B584D
	.string "DAD: I see…\n"
	.string "You've collected four GYM BADGES…\p"
	.string "There's no avoiding it now.\n"
	.string "We will battle like I promised.\p"
	.string "Come anytime.\n"
	.string "We'll all be waiting for you!$"

MatchCall_Text_Norman4:: @ 82B58E3
	.string "DAD: {PLAYER}! You'd better go visit\n"
	.string "Mother every so often.\p"
	.string "I'm going to remain here and\n"
	.string "redouble my training.\p"
	.string "The way of battling is deep\n"
	.string "and unforgiving!$"

MatchCall_Text_Norman5:: @ 82B5979
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "What's that? MAGMA EMBLEM?\n"
	.string "I don't know what that's about.\p"
	.string "But with a name like that, it may\n"
	.string "be somehow linked to a volcano!$"

MatchCall_Text_Norman6:: @ 82B5A07
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "You caught me right in the middle\n"
	.string "of a POKéMON training session!$"

MatchCall_Text_Norman7:: @ 82B5A69
	.string "DAD: {PLAYER}!\p"
	.string "Who would've thought you'd become\n"
	.string "the POKéMON LEAGUE CHAMPION…\p"
	.string "Okay!\n"
	.string "I won't be left behind!$"

MatchCall_Text_Norman8:: @ 82B5ACF
	.string "DAD: Hm? {PLAYER}?\n"
	.string "What good timing!\p"
	.string "This time, I'm going to challenge\n"
	.string "you to battle.\p"
	.string "I'm waiting in the PETALBURG GYM.\n"
	.string "Accept my challenge anytime!$"

MatchCall_Text_Norman9:: @ 82B5B5E
	.string "DAD: …You amaze me, {PLAYER}.\n"
	.string "How much higher will you soar?$"

MatchCall_Text_Steven1:: @ 82B5B95
	.string "성호: 여어 {PLAYER}!\p"
	.string "보라시티에는 벌써 가봤어?\p"
	.string "마을에 있는 사이클숍에서\n"
	.string "마하자전거를 얻었다면\p"
	.string "한 번 더 바위 동굴 안쪽에\n"
	.string "가보도록 해!\p"
	.string "뭔가 새로운 발견이\n"
	.string "있을지도 몰라!$"
	// ダイゴ『やあ §あ§お!ｐ
	// もう キンセツシティには いったかな?ｐ
	// まちの サイクルショップでｎ
	// マッハじてんしゃを てにいれたらｐ
	// もういちど いしのどうくつの おくにｎ
	// いってみるのも いいね!ｐ
	// なにか あたらしい はっけんがｎ
	// あるかも しれないよ!

MatchCall_Text_Steven2:: @ 82B5C53
	.string "성호: 여어 {PLAYER}!\p"
	.string "난 여태까지 꽤나 다양한\n"
	.string "트레이너를 봐왔지만\p"
	.string "넌 누구와도 닮지 않은\n"
	.string "처음으로 보는 타입의 사람이야!$"
	// ダイゴ『やあ §あ§お!ｐ
	// ボクは これまでに ずいぶん いろいろなｎ
	// トレ-ナ-を みてきた けれどｐ
	// キミは だれにも にていないｎ
	// はじめて みる タイプの ひとだよ!

MatchCall_Text_Steven3:: @ 82B5CC9
	.string "성호: 여어 {PLAYER}!\p"
	.string "너는 포켓몬과 모험하면서\n"
	.string "어떤 기분을 느끼고 있니?\p"
	.string "강한 아군이라고 생각하니?\n"
	.string "재밌는 동료라고 생각하니?\p"
	.string "네가 어떻게 생각하느냐에 따라\n"
	.string "그 모험의 의미가 바뀔 거야!$"
	// ダイゴ『やあ §あ§お!ｐ
	// キミは ポケモンと ぼうけんを していてｎ
	// どんな きぶんに なる?ｐ
	// つよいみかた だと おもうかい?ｎ
	// たのしいなかま だと おもうかい?ｐ
	// キミが どう かんじるかに よってｎ
	// その ぼうけんの いみは かわるんだ!

MatchCall_Text_Steven4:: @ 82B5DB4
	.string "성호: 아아 {PLAYER}{K_I}니?\p"
	.string "지금 막 우주센터에서\n"
	.string "성가신 일이 일어났어\p"
	.string "미안하지만 나중에 보자!$"
	// ダイゴ『ああ §あ§お かい?ｐ
	// ちょっと いま うちゅうセンタ-でｎ
	// めんどうな ことが おきてるんだｐ
	// わるいけど また あとでね!

MatchCall_Text_Steven5:: @ 82B5E26
	.string "성호: 앗 {PLAYER}!\p"
	.string "아무 말 안 해도 돼!\n"
	.string "아무튼 지금은...\p"
	.string "네가 생각하는 대로 나아가!$"
	// ダイゴ『あっ §あ§お!ｐ
	// なにも いわなくて いいよ!ｎ
	// とにかく いまは……ｐ
	// キミが おもうように すすむんだ!

MatchCall_Text_Steven6:: @ 82B5EA2
	.string "...... ...... ......\p"
	.string "성호에게는 호출이\n"
	.string "닿지 않는 것 같다...$"
	// …… …… ……ｐ
	// ダイゴには よびだしがｎ
	// つうじていない ようだ……

MatchCall_Text_Steven7:: @ 82B5ED9
	.string "성호: {PLAYER}...\n"
	.string "전당등록 축하해\p"
	.string "...... ...... ......\n"
	.string "...... ...... ......\p"
	.string "또 언젠가 만나면 좋겠다!$"
	// ダイゴ『§あ§お……ｎ
	// でんどういり おめでとうｐ
	// …… …… ……ｎ
	// …… …… ……ｐ
	// また いつか あえると いいね!

MatchCall_Text_BirchRegisterCall: @ 82B5F52
	.string "털보박사: 오오 {PLAYER}{K_AYA}!\n"
	.string "얘기는 이미 들었단다!\p"
	.string "네 포켓내비에 엔트리콜이\n"
	.string "장착되었다고 하더구나!\p"
	.string "그렇다면 나도 등록해 두렴!\p"
	.string "이걸로 너와 떨어져 있어도\n"
	.string "바로 포켓몬 도감의 평가를\l"
	.string "해줄 수 있겠구나!\p"
	.string "...... ...... ......$"
	// オダマキ『おお §あ§お!ｎ
	// はなしは すでに きいて いるよ!ｐ
	// きみの ポケナビに エントリ-コ-ルがｎ
	// セットされた らしいな!ｐ
	// ならば わたしも とうろく しておこう!ｐ
	// これで きみと はなれていてもｎ
	// すぐに ポケモンずかんの ひょうかをｌ
	// してあげられる からね!ｐ
	// …… …… ……

MatchCall_Text_RegisteredBirch: @ 82B603A
	.string "털보박사를\n"
	.string "포켓내비에 등록했다!$"

MatchCall_Text_UnusedProfBirch:
	.string "털보박사: 도감과 포켓내비가 있으면\n"
	.string "포켓몬 조사도\l"
	.string "더욱 즐거워지겠구나!$"
	// オダマキ『ずかんと ポケナビが あればｎ
	// ポケモンの ちょうさもｌ
	// より いっそう たのしくなるな!

MatchCall_Text_MrStone1:: @ 82B60C0
	.string "나발명: 오! {PLAYER}인가?\p"
	.string "이렇게 나를 호출했다는 건\n"
	.string "포켓내비가 잘 작동한다는 뜻이구나!\p"
	.string "나 말고도 다양한 사람들이\n"
	.string "등록되어 갈 테니까 계속\l"
	.string "호출해서 얘기해 보거라!\p"
	.string "좋아 좋아!\n"
	.string "기분이 좋아 보이는구나!\p"
	.string "...응? 어떻게 아냐고?\p"
	.string "그건... 사장실 창문에서\n"
	.string "자네를 내려다보고 있으니까지!\p"
	.string "와하하하! 그럼 나중에 보자꾸나!$"
	// ツワブキ『おっ! §あ§おか?ｐ
	// こうして わしを よびだした ってことはｎ
	// ポケナビの ちょうしは よさそうだな!ｐ
	// わしの ほかにも いろんな ひとがｎ
	// とうろく されて いくから どんどんｌ
	// よびだして はなしを すると いいぞ!ｐ
	// けっこう! けっこう!ｎ
	// うれしそうに しとる ようだな!ｐ
	// ……ん? なんで わかるのかって?ｐ
	// それは…… しゃちょうしつの まどからｎ
	// きみを みおろして いるからだよ!ｐ
	// わははは! じゃあ またな!

MatchCall_Text_MrStone2:: @ 82B61E6
	.string "나발명: 오! {PLAYER}인가?\p"
	.string "왜 그러냐! 내가 부탁한 일이\n"
	.string "뭐였는지 까먹은 건가?\p"
	.string "우선 무로마을에서 성호에게\n"
	.string "편지를 전해주게나!\p"
	.string "그 후 잿빛도시의 해양관장에게\n"
	.string "우리 회사의 화물을 전달하면 된단다!\p"
	.string "자 기억했니?\n"
	.string "난 바쁜 사장이니\l"
	.string "이만 실례하마!$"
	// ツワブキ『おっ! §あ§おか?ｐ
	// どうした! わしが たのんだ しごとｎ
	// わすれちゃったの かな?ｐ
	// まずは ムロタウンで ダイゴにｎ
	// てがみを わたしてくれ!ｐ
	// そのあと カイナシティの クスノキくんにｎ
	// わがしゃの にもつを とどけるんだ!ｐ
	// な? おぼえたかな?ｎ
	// わしは いそがしい しゃちょう だからねｌ
	// これで しつれい するよ!

MatchCall_Text_MrStone3:: @ 82B6302
	.string "나발명: 오! {PLAYER}{K_AYA}!\p"
	.string "그래 성호에게 전해줬구나!\n"
	.string "좋-아 답례로 선물을 주마!\p"
	.string "금탄도시에 올 일이 있다면\n"
	.string "내 방에 찾아오거라!\p"
	.string "그럼 기다리고 있으마!$"
	// ツワブキ『おっ! §あ§お!ｐ
	// そうか ダイゴに あえたのか!ｎ
	// よ-し おれいに プレゼントを やろう!ｐ
	// カナズミに くることが あったらｎ
	// わしの へやに よっていって おくれ!ｐ
	// じゃあな まっとるぞ!

MatchCall_Text_MrStone4:: @ 82B63A0
	.string "나발명: 오오! {PLAYER}{K_AYA}!\p"
	.string "그래그래 금잔터널은\n"
	.string "우리 회사가 파고 있었는데\p"
	.string "그 주변에 서식하고 있는\n"
	.string "포켓몬을 보호하기 위해서\l"
	.string "공사를 중지했었단다\p"
	.string "뭐 인간의 편리함보다는\n"
	.string "포켓몬이 조용하게 사는 게\l"
	.string "중요하니까 말이지!$"
	// ツワブキ『おお! §あ§お!ｐ
	// そうそう カナシダトンネルはｎ
	// わがしゃが ほって いたんだけどねｐ
	// あの あたりに せいそく しているｎ
	// ポケモンを ほご するためにｌ
	// こうじは ちゅうし したんだよｐ
	// まあ にんげんの べんりさ よりはｎ
	// ポケモンが しずかに くらせるｌ
	// そのほうが だいじな ことだからね!

MatchCall_Text_MrStone5:: @ 82B64A2
	.string "나발명: 여어여어 {PLAYER}{K_AYA}!\p"
	.string "등화도시의 사람한테서 들었는데\n"
	.string "자네가 종길씨의 자식이었구만\p"
	.string "어쩐지 믿음직스럽다 했어!$"
	// ツワブキ『やあやあ §あ§お!ｐ
	// トウカシティの ひとから きいたんだけどｎ
	// きみは センリさんの こども なんだねｐ
	// どうりで たのもしいと おもったよ!

MatchCall_Text_MrStone6:: @ 82B6526
	.string "나발명: 에엑!\n"
	.string "자네가 자신의 아버지와\l"
	.string "포켓몬 승부를 해서 이겼다고?\p"
	.string "이거 놀랍군!\n"
	.string "나는 굉장한 사람과 친구가\l"
	.string "됐어! 와하하!$"
	// ツワブキ『ええっ!ｎ
	// きみは じぶんの おとうさんとｌ
	// ポケモンしょうぶを して かったのかい?ｐ
	// こりゃ びっくりだ!ｎ
	// わしは すごい ひとと ともだちにｌ
	// なっちゃったんだなあ! わはは!

MatchCall_Text_MrStone7:: @ 82B65BB
	.string "여보세요!\n"
	.string "데봉 코포레이션입니...\l"
	.string "아아 {PLAYER}씨였군요!\p"
	.string "사장님은 방금까지 계셨는데\n"
	.string "지금은 부재중이십니다!\p"
	.string "저희 사장님도 바쁘시지만\n"
	.string "{PLAYER}씨도 바쁜 것 같네요!$"
	// もしもし!ｎ
	// デボンコ-ポレ-ションで ございま……ｌ
	// ああ §あさん ですね!ｐ
	// しゃちょうは さっきまで いたんですけどｎ
	// いまは るすに してるんですよ!ｐ
	// うちの しゃちょうも いそがしいけどｎ
	// §あさんも いそがしそう ですね!

MatchCall_Text_MrStone8:: @ 82B6664
	.string "...에 ...무슨 일인가?\p"
	.string "그란... 뭐? ...돈?\p"
	.string "왠지 잘... 안 들리...\p"
	.string "지지지지직...... ...... ......$"
	// ……え ……なにかね?ｐ
	// グラ…… はい? ……ドン?ｐ
	// なんだか…… きこえな……ｐ
	// ザザザザザ…… …… ……

MatchCall_Text_MrStone9:: @ 82B66B1
	.string "...에 ...무슨 일인가?\p"
	.string "해저... 뭐? ...동굴?\p"
	.string "왠지 잘... 안 들리...\p"
	.string "지지지지직...... ...... ......$"
	// ……え ……なにかね?ｐ
	// かいて…… はい? ……どうくつ?ｐ
	// なんだか…… きこえな……ｐ
	// ザザザザザ…… …… ……

MatchCall_Text_MrStone10:: @ 82B6703
	.string "나발명: {PLAYER}! 나일세!\p"
	.string "왠지 여러 일이 있었던 것 같지만\n"
	.string "바쁜 나는 무슨 일이\l"
	.string "일어난 건지 전혀 모르겠네!\p"
	.string "아무튼 자네는 자신이 믿은\n"
	.string "길을 걸어나가게나!\p"
	.string "나도 뒤에서나마 응원할 테니!\n"
	.string "그럼 이만!$"
	// ツワブキ『§あ§お! わしだ!ｐ
	// なんだか いろいろ あった らしいがｎ
	// いそがしい わしにはｌ
	// なんの ことだか サッパリ わからん!ｐ
	// とにかく キミは じぶんの しんじたｎ
	// みちを あゆんで いきたまえ!ｐ
	// わしも カゲながら おうえん しとるぞ!ｎ
	// じゃあな!

MatchCall_Text_MrStone11:: @ 82B67ED
	.string "나발명: ...... ...... ......\n"
	.string "혹시 {PLAYER}인가?\p"
	.string "목소리에 자신감이 넘쳐서\n"
	.string "순간 다른 사람인 줄 알았네!\p"
	.string "그래! 가끔은 우리 회사에도\n"
	.string "놀러오게나!$"
	// ツワブキ『…… …… ……ｎ
	// もしかして §あ§お か?ｐ
	// こえに じしんが みなぎっていてｎ
	// いっしゅん ちがうひとかと おもったぞ!ｐ
	// うむ! たまには わがしゃにもｎ
	// あそびに きておくれ!
