@ Only contains a portion of the mauville_man text. The rest is in scripts/mauville_man.inc
gText_SoPretty:: @ 8294295
	.string " 아름답단 말이지!$"

gText_SoDarling:: @ 82942A1
	.string " 귀엽단 말이지!$"

gText_SoRelaxed:: @ 82942AE
	.string " 태평하단 말이지!$"

gText_SoSunny:: @ 82942BB
	.string " 따끈하단 말이지!$"

gText_SoDesirable:: @ 82942C6
	.string " 동경하게 돼!$"

gText_SoExciting:: @ 82942D5
	.string " 두근두근하지!$"

gText_SoAmusing:: @ 82942E3
	.string " 재밌단 말이지!$"

gText_SoMagical:: @ 82942F0
	.string " 신기하단 말이지!$"

gOtherText_Is:: @ 82942FD
	.string "{K_EUNNEUN}$"

gOtherText_DontYouAgree:: @ 8294301
	.string "\n"
	.string "그렇게 생각하지 않아?$"

gMauvilleManText_ISoWantToGoOnAVacation:: @ 8294313
	.string "여행 가고 싶은데\n"
	.string "혹시 어디 멋진 곳 알고 있어?$"

gMauvilleManText_IBoughtCrayonsWith120Colors:: @ 8294359
	.string "120색 크레파스 샀지롱-\n"
	.string "부럽지?$"

gMauvilleManText_WouldntItBeNiceIfWeCouldFloat:: @ 8294398
	.string "비눗방울을 타고 한번\n"
	.string "날아보고 싶어-$"

gMauvilleManText_WhenYouWriteOnASandyBeach:: @ 82943DA
	.string "모래해변 위에 적은 글자는\n"
	.string "금세 사라지니깐 슬퍼-$"

gMauvilleManText_WhatsTheBottomOfTheSeaLike:: @ 829441C
	.string "바다 깊은 곳은 어떨까?\n"
	.string "한 번이라도 좋으니깐 보고 싶어-$"

gMauvilleManText_WhenYouSeeTheSettingSunDoesIt:: @ 8294460
	.string "저녁 노을을 보면\n"
	.string "집에 돌아가고 싶지 않아?$"

gMauvilleManText_LyingBackInTheGreenGrass:: @ 82944A0
	.string "초록색 잔디 위에서 뒹굴뒹굴하면\n"
	.string "기분 좋지 않아?$"

gMauvilleManText_SecretBasesAreSoWonderful:: @ 82944D5
	.string "비밀기지는 정말 좋지!\n"
	.string "뭔가 두근거리지 않아?$"
