Mevent_Text_FillOutQuestionnaire:: @ 827339F
	.string "설문용 메모 용지가 있다\n"
	.string "설문 용지에 뭔가를 적겠습니까?$"
	@ アンケ-トようの メモようしが あるｎ
	@ アンケ-トに なにか かきますか?

Mevent_Text_QuestionnaireThankYou:: @ 82733D8
	.string "설문에 협력해 주셔서\n"
	.string "감사합니다!\p"
	.string "이 답변은 앞으로\n"
	.string "참고하도록 하겠습니다!$"
	@ アンケ-トに ごきょうりょくｎ
	@ いただき ありがとう ございます!ｐ
	@ この アンケ-トは こんごのｎ
	@ さんこうに させて いただきます!

Mevent_Text_YouKnowThoseWordsGift:: @ 8273446
	.string "...손님!\n"
	.string "그 말을 알고 계시는 건가요!\p"
	.string "그렇다면 이상한 소포를\n"
	.string "알고 계신 거군요!\p"
	.string "앞으로 당신에게도\n"
	.string "이상한 소포가\l"
	.string "오게 될 겁니다!$"
	@ …… おきゃくさま!ｎ
	@ そのことばを しってるの ですか!ｐ
	@ ということは ふしぎなおくりもの をｎ
	@ しって いらっしゃるの ですね!ｐ
	@ これからは あなたにもｎ
	@ ふしぎなおくりもの がｌ
	@ とどくように なるでしょう!

Mevent_Text_YouCanAccessMysteryGift:: @ 82734CC
	.string "리포트를 작성하면 이상한 소포를\n"
	.string "사용할 수 있게 됩니다$"
	@ レポ-トをかくと ふしぎなおくりもの がｎ
	@ つかえるように なります

Mevent_Text_YouKnowThoseWordsEvent:: @ 8273506
	.string "...손님!\n"
	.string "그 말을 알고 계시는 건가요!\p"
	.string "그렇다면 이상한 사건을\n"
	.string "알고 계신 거군요!$"
	@ …… おきゃくさま!ｎ
	@ そのことばを しってるの ですか!ｐ
	@ ということは ふしぎなできごと をｎ
	@ しって いらっしゃるの ですね!

Mevent_Text_YouCanAccessMysteryEvent:: @ 8273559
	.string "리포트를 작성하면 이상한 사건을\n"
	.string "사용할 수 있게 됩니다$"
	@ レポ-トをかくと ふしぎなできごと がｎ
	@ つかえるように なります

Mevent_Text_TheresATicketForYou:: @ 8273594
	.string "이상한 소포를 이용해 주셔서\n"
	.string "감사합니다!\l"
	.string "{PLAYER}님이시군요\p" 
	.string "손님 앞으로\n"
	.string "이 티켓이\l"
	.string "도착했습니다$"
	@ ふしぎなできごと を ごりようｎ
	@ いただき ありがとう ございます!ｌ
	@ §あさま ですねｐ
	@ あなたさま あてにｎ
	@ この チケットがｌ
	@ おくられて きました

Mevent_Text_TryUsingItAtLilycovePort:: @ 82735F2
	.string "해안시티의 선착장에서\n"
	.string "쓸 수 있는 모양이군요\p"
	.string "한번 이용해 보시는 게\n"
	.string "어떻겠습니까?$"
	@ ミナモシティの ふなつきば でｎ
	@ つかえる ようですねｐ
	@ ぜひ ごりよう してみてはｎ
	@ いかがでしょうか?
