MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce: @ 82C6E05
	.string "이 기술의 가르침을 받는 것은\n"
	.string "한 번뿐입니다만 괜찮겠습니까?$"
	// この わざを おしえて もらえるのはｎ
	// いちど だけですが いいですか?

MoveTutor_Text_SwaggerTeach: @ 82C6E37
	.string "흐흐-음\n"
	.string "내 포켓몬은 굉장하다구!\l"
	.string "어떤 포켓몬보다도 멋져!\p"
	.string "...라고 뽐냈는데\n"
	.string "회장님이 화냈어\p"
	.string "이제 뽐내지 않기로 했으니까\n"
	.string "대신 네 포켓몬에게\l"
	.string "뽐내기 기술을 알려줄게$"
	// ふふ-んｎ
	// おれの ポケモンは すごいのさ!ｌ
	// どの ポケモンよりも かっこいいのさ!ｐ
	// ……って いばってたらｎ
	// かいちょうに おこられちゃったｐ
	// もう いばらない ことに したからｎ
	// かわりに おまえの ポケモンにｌ
	// いばる わざを おしえて やってもいいぜ

MoveTutor_Text_SwaggerDeclined: @ 82C6F33
	.string "에-\n"
	.string "뭐야 붙임성 없네$"
	// え-ｎ
	// なんだよ つきあい わるいな

MoveTutor_Text_SwaggerWhichMon: @ 82C6F66
	.string "오우!\n"
	.string "어느 포켓몬이 뽐내고 싶대?$"
	// おう!ｎ
	// どの ポケモンが いばりたいんだ?

MoveTutor_Text_SwaggerTaught: @ 82C6F9E
	.string "다음부턴 뽐내지 말고\n"
	.string "자랑하는 걸로 끝내야겠다...$"
	// こんどっから いばる かわりにｎ
	// じまん するだけに しておくよ……

MoveTutor_Text_RolloutTeach: @ 82C6FDB
	.string "있지 여기서 저쪽을 향해서\n"
	.string "한 번도 방향을 바꾸지 않고 쭉\l"
	.string "걸어갈 수 있단 거 알았어?\l"
	.string "나라면 굴러갈 수 있을지도...!\p"
	.string "네 포켓몬도 굴러 볼래?\n"
	.string "구르기를 알려줄게$"
	// ねえ ここから あっちに むかってｎ
	// いちども まがらずに ず-っとｌ
	// あるいて いけるって しってた?ｌ
	// ぼく なら ころがって いけるかも……!ｐ
	// きみの ポケモンも ころがって みる?ｎ
	// ころがる なら おしえて あげられるよ

MoveTutor_Text_RolloutDeclined: @ 82C70C4
	.string "사양하지 않아도 되는데!\n"
	.string "데굴 데굴$"
	// えんりょ いらないのに!ｎ
	// ごろ ごろ

MoveTutor_Text_RolloutWhichMon: @ 82C70F3
	.string "에헤헤 좋아!\n"
	.string "나하고 똑 닮은 포켓몬이면 좋겠다$"
	// えへへ いいよ!ｎ
	// ぼく そっくりの ポケモンだと いいな

MoveTutor_Text_RolloutTaught: @ 82C7133
	.string "풀밭에서 구르면 행복해-\n"
	.string "데굴 데굴$"
	// くさに ねころがると しあわせだな-ｎ
	// ごろ ごろ

MoveTutor_Text_FuryCutterTeach: @ 82C7174
	.string "같은 기술을 말이야\n"
	.string "계속해서 몇 번이고 쓰면\l"
	.string "점점 강해지는 기술이 있어!\l"
	.string "게다가 벌레타입이라 멋있다구!\p"
	.string "연속자르기라고 하는데\n"
	.string "배우게 해 볼래?$"
	// おなじ わざをさｎ
	// つづけて なんども だすとｌ
	// どんどん つよくなる わざが あるの!ｌ
	// しかも むしタイプで かっこいいの!ｐ
	// れんぞくぎりって いうんだけどｎ
	// おぼえて みたい?

MoveTutor_Text_FuryCutterDeclined: @ 82C7221
	.string "마음이 안 맞았네$"
	// きが あわないねぇ

MoveTutor_Text_FuryCutterWhichMon: @ 82C7243
	.string "와-아!\n"
	.string "그럼 배우게 할 포켓몬을 알려줘$"
	// わ-い!ｎ
	// じゃ おぼえさせる ポケモンを おしえてね

MoveTutor_Text_FuryCutterTaught: @ 82C726E
	.string "연속으로 맞힐지 못할지\n"
	.string "스릴이 있어서 즐겁단 말이지$"
	// れんぞくして あたるか どうかのｎ
	// スリルが たのしいんだよねぇ

MoveTutor_MimicTeach: @ 82C72B6
	.string "오오 젊은이!\n"
	.string "나도 꼬맹이지만\l"
	.string "이 마을의 할아버지와 할머니의\l"
	.string "말투를 흉내내고 있다네\p"
	.string "어떤가? 젊은\n"
	.string "자네의 포켓몬에게 내가\l"
	.string "흉내내기를 가르쳐줄까?$"
	// おお おわかいの!ｎ
	// わしは こども じゃがｌ
	// このまちの じいちゃんや ばあちゃんのｌ
	// はなしかたを ものまね しておるのじゃ!ｐ
	// どうかね? おわかいのｎ
	// おぬしの ポケモンに わしがｌ
	// ものまねを おしえて やろうかね?

MoveTutor_MimicDeclined: @ 82C737F
	.string "쳇 뭐야-!\n"
	.string "난 흉내내기를 가르치고 싶은데!$"
	// ちぇっ な-んだ!ｎ
	// ボク ものまね おしえたいのにな!

MoveTutor_Text_MimicWhichMon: @ 82C73B1
	.string "허허! 알겠네!\n"
	.string "배우게 할 포켓몬을 보여주게나$"
	// ふぉっ ふぉっ! よかろう!ｎ
	// おしえさせる ポケモンを みせてみぃ

MoveTutor_Text_MimicTaught: @ 82C73F6
	.string "흉내내기는 내 비장의 기술이지!\n"
	.string "너... 아니 자네가 나처럼\l"
	.string "잘 쓸 수 있을까?$"
	// ものまねは おくの ふかい わざじゃ!ｎ
	// ボ… わしの ようにｌ
	// うまく できるかな?

MoveTutor_Text_MetronomeTeach: @ 82C7449
	.string "아-앙 갖고 싶은 게 너무 많아!\n"
	.string "하지만 용돈을 다 써버렸어...\p"
	.string "손가락을 흔들어서 마법으로\n"
	.string "용돈이 나오면 좋을 텐데-!\l"
	.string "농담이야 에헤헤...\p"
	.string "어쩔 수 없지\n"
	.string "네 포켓몬에게\l"
	.string "손가락흔들기라도 가르쳐줄까?$"
	// あ-ん ほしいものが いっぱい!ｎ
	// でも おこづかいは なくなっちゃったし……ｐ
	// ゆびを ふれば まほうでｎ
	// おこづかい でてくれば い-のにな!ｌ
	// なんてね エヘヘ……ｐ
	// しかたが ないからｎ
	// あなたの ポケモンにｌ
	// ゆびをふる でも おしえて あげよっか?

MoveTutor_Text_MetronomeDeclined: @ 82C7556
	.string "그래\n"
	.string "하고 싶다면 다시 와$"
	// そっかｎ
	// きが むいたら またおいでよ!

MoveTutor_Text_MetronomeWhichMon: @ 82C7582
	.string "응! 그럼 가르쳐줄게\n"
	.string "어느 애가 좋을까?$"
	// うん! じゃ おしえるねｎ
	// どのコが いいのかな?

MoveTutor_Text_MetronomeTaught: @ 82C75B5
	.string "손가락흔들기를 쓰면 근사한 일이\n"
	.string "잔뜩 일어나-!\p"
	.string "우리도 쓸 수 있다면 좋을 텐데!$"
	// ゆびをふると ステキな ことがｎ
	// いっぱい おきるんだよ-!ｐ
	// わたしたちも つかえたら い-のにね!

MoveTutor_Text_SleepTalkTeach: @ 82C7637
	.string "흥... 할멈도 참\n"
	.string "잠재파워 따위에\l"
	.string "의지하기는...\p"
	.string "나하고 같이 낮잠을 자고\n"
	.string "잠꼬대라도 하는 편이 즐거울 텐데\p"
	.string "이젠 네 포켓몬이라도 상관없다\n"
	.string "잠꼬대를 배우게 해보지 않겠나?$"
	// ふん…… ばあさんめｎ
	// めざめるパワ- などにｌ
	// たより おって……ｐ
	// ワシと いっしょに おひるね してｎ
	// ねごとでも いってたほうが たのしいのにｐ
	// もう あんたの ポケモンでも ええわｎ
	// ねごとを おぼえて つかってみんか?

MoveTutor_Text_SleepTalkDeclined: @ 82C76E2
	.string "그런가 그런가...\n"
	.string "다들 잠재파워가 좋은 거구먼$"
	// そうかい そうかい……ｎ
	// みんな めざめるパワ-が だいすきかい

MoveTutor_Text_SleepTalkWhichMon: @ 82C7721
	.string "오오! 뭘 좀 아는 꼬마구나!\n"
	.string "자 어느 포켓몬에게 가르칠 겐가?$"
	// むぉう! ものわかりの いい こどもよ!ｎ
	// さて ポケモンは どいつが いいかな?

MoveTutor_Text_SleepTalkTaught: @ 82C775A
	.string "난 할멈의 동전을\n"
	.string "한 번도 맞춘 적이 없다네...\l"
	.string "잠꼬대라도 좋으니 맞추면 좋겠구먼$"
	// ワシ ばあさんの コインｎ
	// いちども あてたことが なくてな……ｌ
	// ねごとでも ええから あたらんかな

MoveTutor_Text_SubstituteTeach: @ 82C77C6
	.string "후우\n"
	.string "이렇게 옥상에서\l"
	.string "넓은 세계를 보고 있자니...\p"
	.string "내가 몇 명 더 있으면\n"
	.string "다양한 인생을 살아볼 수 있을 텐데-!\l"
	.string "라는 생각이 드네!\l"
	.string "말도 안 되는 얘기지만 우후후\p"
	.string "맞다 네 포켓몬!\n"
	.string "대타출동 배워보지 않을래?$"
	// ふうｎ
	// こうやって おくじょうからｌ
	// ひろい せかいを みていると……ｐ
	// なんにんもの じぶんが いてｎ
	// いくつもの じんせいを たのしめたらな-ｌ
	// って おもうの!ｌ
	// ムリな はなしだけどね うふふｐ
	// そうだわ あなたの ポケモンちゃん!ｎ
	// みがわりの わざ おぼえてみない?

MoveTutor_Text_SubstituteDeclined: @ 82C78D1
	.string "어머 그래?\n"
	.string "포켓몬이라면 자신의 분신을\l"
	.string "만들 수 있는데$"
	// あら そう?ｎ
	// ポケモンなら じぶんの ぶんしんをｌ
	// つくる ことが できるのに

MoveTutor_Text_SubstituteWhichMon: @ 82C7911
	.string "우후후\n"
	.string "어느 포켓몬으로 할래?$"
	// うふふｎ
	// どの ポケモンちゃんが いいかしら?

MoveTutor_Text_SubstituteTaught: @ 82C794B
	.string "우리 인간은\n"
	.string "자신의 인생을\l"
	.string "마음껏 즐겨야 돼!\l"
	.string "너도 그럴 수 있길 빌게!$"
	// わたしたち にんげんはｎ
	// じぶんの じんせいをｌ
	// おもいきり たのしまなきゃ ね!ｌ
	// あなたも そうなるように いのってる!

MoveTutor_Text_DynamicPunchTeach: @ 82C79A6
	.string "더는 못 하겠다!\p"
	.string "절대 될 리가 없어!\p"
	.string "격투타입인 나는\n"
	.string "이끼체육관을\l"
	.string "제패할 수가 없다고!\p"
	.string "젠장-! 퍽퍽!\n"
	.string "퍽퍽! 퍽퍽!\p"
	.string "뭐야\n"
	.string "그런 눈으로 쳐다보지 마!\l"
	.string "땅을 때리고 있는 것뿐이잖아!\p"
	.string "아니면 네 포켓몬한테\n"
	.string "폭발펀치라도 가르쳐줘?$"
	// もう できんわ!ｐ
	// ぜったい ムリだわ!ｐ
	// かくとうタイプの オレはｎ
	// トクサネの ジムではｌ
	// ぜんぜん かてんわ!ｐ
	// ちきしょ-っ! ボカ ボカ!ｎ
	// ボカ ボカ! ボカ ボカ!ｐ
	// なんだよｎ
	// そんな めで みるなよ!ｌ
	// じめんを なぐってる だけだろ!ｐ
	// それとも おまえの ポケモンにｎ
	// ばくれつパンチを おしえて ほしいのかよ?

MoveTutor_Text_DynamicPunchDeclined: @ 82C7AD4
	.string "젠장- 너까지\n"
	.string "날 바보 취급하는 거냐!?\l"
	.string "퍽퍽!$"
	// ちきしょ- おまえまでｎ
	// オレを ばかに するかっ!?ｌ
	// ボカ ボカ!

MoveTutor_Text_DynamicPunchWhichMon: @ 82C7B0D
	.string "우오-! 정말이냐! 너 좋은 녀석이구나!\n"
	.string "어느 포켓몬에게 가르치면 돼?$"
	// うぉ-! ほんとか! いいやつだな!ｎ
	// どのポケモンに おしえれば いい?

MoveTutor_Text_DynamicPunchTaught: @ 82C7B4F
	.string "자 폭발펀치를 써서\n"
	.string "이끼체육관을 제패하고 와!$"
	// なあ ばくれつパンチ つかってｎ
	// トクサネジムで かって きてくれよ!

MoveTutor_Text_DoubleEdgeTeach: @ 82C7B8E
	.string "아-아\n"
	.string "루네시티의 체육관 관장은\l"
	.string "엄청 멋지니까\l"
	.string "라이벌이 많단 말이지-\p"
	.string "이 내가 이판사판으로 부딪혀\n"
	.string "봤는데도 실패였어!\p"
	.string "저기 너!\n"
	.string "모처럼이니까 이 나의\l"
	.string "비장의 기술인 이판사판태클을\l"
	.string "네 포켓몬에게 가르쳐줄게!$"
	// あ-あｎ
	// ルネシティの ジムリ-ダ-ってｌ
	// すっごく すてきだからｌ
	// ライバルが いっぱい なのよね-ｐ
	// この あたしが すてみで ぶつかってもｎ
	// ダメだったわ!ｐ
	// ねえ あなた!ｎ
	// せっかく だから この あたしのｌ
	// じきでんの すてみタックル!ｌ
	// あなたの ポケモンに おしえさせてよ!

MoveTutor_Text_DoubleEdgeDeclined: @ 82C7C7E
	.string "아 진짜!\n"
	.string "너한테도 차이는 거야 난?$"
	// うん もう!ｎ
	// あなたに まで ふられちゃったわ

MoveTutor_Text_DoubleEdgeWhichMon: @ 82C7C98
	.string "응 그럼\n"
	.string "어느 포켓몬으로 할지 정해줘$"
	// ん じゃあｎ
	// どの ポケモンが いいか きめてよ

MoveTutor_Text_DoubleEdgeTaught: @ 82C7CC8
	.string "이제 됐어!\n"
	.string "난 사랑을 버리고\l"
	.string "강한 여자가 될 거야!$"
	// もう いいわっ!ｎ
	// あたしも こいを すててｌ
	// つよい オンナに なってやるっ!

MoveTutor_Text_ExplosionTeach: @ 82C7CFA
	.string "난 이런 시골에서\n"
	.string "언제까지고 살 생각은\l"
	.string "전혀 없어-!\p"
	.string "두고 봐 언젠가 도시로 나가서\n"
	.string "콰광 하고 크게 터뜨릴 테니까!\p"
	.string "이봐! 너 들었다면\n"
	.string "활기차게 대폭발을 알려줄게!$"
	// ぼかぁ こんな イナカでｎ
	// いつまでも くすぶっとる つもりはｌ
	// まったく ないんじゃあ-!ｐ
	// みとれよ いつか トカイに でてｎ
	// ドッカ-ンと はでに やって やるわい!ｐ
	// おいっ! おまえ きいとったん ならｎ
	// けいきよく だいばくはつを おしえさせろ!

MoveTutor_Text_ExplosionDeclined: @ 82C7E04
	.string "야-!\n"
	.string "시골뜨기라고 거절하지 마!$"
	// が-っ!ｎ
	// イナカもん だからって ことわるなあ!

MoveTutor_Text_ExplosionWhichMon: @ 82C7E40
	.string "좋았어 콰광 하고 알려주지!\n"
	.string "어느 포켓몬한테 해줄까?$"
	// ぃよ-し ドッカ-ンと おぼえさせるか!ｎ
	// どの ポケモンが ぶちかますんか?

MoveTutor_Text_ExplosionTaught: @ 82C7E7A
	.string "언제나 포켓몬에게\n"
	.string "대폭발을 알려주지만\l"
	.string "정작 난 계속\l"
	.string "폭발하지 못하고 있지...\p"
	.string "이 마을에 계속 있고 싶으니까\n"
	.string "그런 걸지도 몰라...$"
	// いつも ポケモンに ばっかｎ
	// だいばくはつを おしえとってｌ
	// かんじんの ぼくは いつまでもｌ
	// ばくはつ できん……ｐ
	// でも ほんとはｎ
	// このまちに いつまでも いたいからｌ
	// かも しれん……
