gText_ObtainedTheItem:: @ 8272A78
	.string "{STR_VAR_2}{K_EULREUL} 손에 넣었다!$"

gText_TheBagIsFull:: @ 8272A89
	.string "가방이 가득 찼다...$"

gText_PutItemInPocket:: @ 8272A9A
	.string "{PLAYER}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n"
	.string "{STR_VAR_3} 포켓에 넣었다$"

gText_PlayerFoundOneItem:: @ 8272ABF
	.string "{PLAYER}{K_EUNNEUN}\n"
    .string "{STR_VAR_2}{K_EULREUL} 발견했다!$"

gText_TooBadBagIsFull:: @ 8272AD0
	.string "아쉽다!\n"
	.string "가방이 가득 찼다...$"

gText_PlayerPutItemInBag:: @ 8272AEA
	.string "{PLAYER}{K_EUNNEUN} {STR_VAR_2}{K_EULREUL}\n"
	.string "가방에 넣었다!$"
	@ {PLAYER}は {STR_VAR_2}をｎ
	@ バッグに しまった!

gText_ObtainedTheDecor:: @ 8272B09
	.string "{STR_VAR_2}{K_EULREUL} 손에 넣었다!$"

gText_NoRoomLeftForAnother:: @ 8272B1A
	.string "아쉽다! {STR_VAR_2}{K_EULREUL}\n"
	.string "넣을 공간이 없다...$"

gText_TheDecorWasTransferredToThePC:: @ 8272B48
	.string "{STR_VAR_2}{K_EUNNEUN}\n"
	.string "PC로 전송되었다!$"
