Text_BootUpPC: @ 827265A
	.string "{PLAYER}{K_EUNNEUN}\n"
	.string "PC 전원을 켰다!$"

gText_WhichPCShouldBeAccessed:: @ 827266F
	.string "어느 PC에 접속해서\n"
	.string "통신할까요?$"

gText_AccessedSomeonesPC:: @ 827268C
	.string "누군가의\n"
	.string "PC에 접속했다!$"

gText_StorageSystemOpened:: @ 82726A3
	.string "포켓몬 보관 시스템을\n"
	.string "불러왔습니다!$"

gText_AccessedPlayersPC:: @ 82726C2
	.string "{PLAYER}의\n"
	.string "PC에 접속했다!$"

gText_AccessedLanettesPC:: @ 82726D4
	.string "보은의\n"
	.string "PC에 접속했다!$"
