gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2}{B_TXT_EUNNEUN} 누군가의 PC\n"
	.string "“{STR_VAR_1}”{B_TXT_EU}로\l"
	.string "전송되었다!$"
	// §うは だれかのパソコンのｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_PkmnTransferredLanettesPC:: @ 8273256
	.string "{STR_VAR_2}{B_TXT_EUNNEUN} 유미의 PC\n"
	.string "“{STR_VAR_1}”{B_TXT_EU}로\l"
	.string "전송되었다!$"
	// §うは マユミのパソコンのｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_PkmnTransferredSomeonesPCBoxFull:: @ 8273296
	.string "누군가의 PC\n"
	.string "“{STR_VAR_3}”{B_TXT_EUNNEUN}\l"
	.string "가득 찼다!\p"
	.string "{STR_VAR_2}{B_TXT_EUNNEUN}\n"
	.string "“{STR_VAR_1}”{B_TXT_EU}로\l"
	.string "전송되었다!$"
	// だれかのパソコンのｎ
	// ボックス『§え』がｌ
	// いっぱいだ!!ｐ
	// §うはｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_PkmnTransferredLanettesPCBoxFull:: @ 82732D9
	.string "유미의 PC\n"
	.string "“{STR_VAR_3}”{B_TXT_EUNNEUN}\l"
	.string "가득 찼다!\p"
	.string "{STR_VAR_2}{B_TXT_EUNNEUN}\n"
	.string "“{STR_VAR_1}”{B_TXT_EU}로\l"
	.string "전송되었다!$"
	// マユミのパソコンのｎ
	// ボックス『§え』がｌ
	// いっぱいだ!!ｐ
	// §うはｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "포켓몬을 잡을 수 없습니다!\p"
	.string "박스가 가득 차서\n"
	.string "전송할 수 없습니다!$"
	// ポケモンを もちきれません!ｐ
	// ボックスも いっぱいでｎ
	// てんそう できません!

gText_NicknameThisPokemon:: @ 8273374
	.string "잡은 {STR_VAR_1}에게\n"
	.string "닉네임을 붙이겠습니까?$"
	// §いにｎ
	// ニックネ-ムを つけますか?
