gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2} was transferred to\n"
	.string "SOMEONE'S PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"
	// §うは だれかのパソコンのｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_PkmnTransferredLanettesPC:: @ 8273256
	.string "{STR_VAR_2} was transferred to\nLANETTE'S PC.\p"
	.string "It was placed in \n"
	.string "BOX “{STR_VAR_1}.”$"
	// §うは マユミのパソコンのｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_PkmnTransferredSomeonesPCBoxFull:: @ 8273296
	.string "BOX “{STR_VAR_3}” on\n"
	.string "SOMEONE'S PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"
	// だれかのパソコンのｎ
	// ボックス『§え』がｌ
	// いっぱいだ!!ｐ
	// §うはｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_PkmnTransferredLanettesPCBoxFull:: @ 82732D9
	.string "BOX “{STR_VAR_3}” on\n"
	.string "LANETTE'S PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "BOX “{STR_VAR_1}.”$"
	// マユミのパソコンのｎ
	// ボックス『§え』がｌ
	// いっぱいだ!!ｐ
	// §うはｎ
	// ボックス『§い』にｌ
	// てんそう された!

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "There's no more room for POKéMON!\p"
	.string "The POKéMON BOXES are full and\n"
	.string "can't accept any more!$"
	// ポケモンを もちきれません!ｐ
	// ボックスも いっぱいでｎ
	// てんそう できません!

gText_NicknameThisPokemon:: @ 8273374
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"
	// §いにｎ
	// ニックネ-ムを つけますか?
