	.align 2
gText_ConfirmSave::
	.string "지금까지의 활약을\n"
	.string "포켓몬 리포트로 작성할까요?$"
	@ ここまでの かつやくをｎ
	@ ポケモンレポ-トに かきこみますか?

gText_AlreadySavedFile::
	.string "전에 작성한 리포트에\n"
	.string "덮어써도 괜찮습니까?$"
	@ まえに かかれた レポ-トにｎ
	@ うえから かいても いいですか?

gText_SavingDontTurnOff::
	.string "포켓몬 리포트를 작성하고 있습니다\n"
	.string "전원을 끄지 않도록 해주십시오$"
	@ ポケモンレポ-トに かきこんでいますｎ
	@ でんげんを きらないで ください

gText_PlayerSavedGame::
	.string "{PLAYER}{K_EUNNEUN}\n"
    .string "리포트를 꼼꼼히 기록했다!$"
	@ §あ はｎ
	@ レポ-トに しっかり かきのこした!

gText_DifferentSaveFile::
	.string "주의!!\p"
	.string "“모험을 계속한다”로\n"
	.string "모험을 한 리포트가\l"
	.string "작성되어 있습니다!\p"
	.string "그쪽에서 플레이했던 모험이나\n"
	.string "모든 포켓몬 및 도구 등이\l"
	.string "사라집니다...\p"
	.string "정말로\n"
	.string "덮어쓰기를 하겠습니까?$"
	@ ちゅうい!!ｐ
	@ 『つづきから はじめる』でｎ
	@ ぼうけん していた レポ-トがｌ
	@ かかれています!ｐ
	@ そちらで プレイしていた ぼうけんやｎ
	@ すべての ポケモン どうぐ などがｌ
	@ きえてしまいます……ｐ
	@ ほんとうにｎ
	@ うえから かいても いいですか?

gText_SaveError::
	.string "리포트를 작성하지 못했습니다\p"
	.string "백업 카트리지를\n"
	.string "교환해 주십시오!$"
	@ レポ-トが かけませんでしたｐ
	@ バックアップカ-トリッジをｎ
	@ こうかんしてください!

gText_SavingDontTurnOffPower::
	.string "포켓몬 리포트를 작성하고 있습니다\n"
	.string "전원을 끄지 않도록 해주십시오$"
	@ ポケモンレポ-トに かきこんでいますｎ
	@ でんげんを きらないで ください
