SecretBase_Text_Trainer0Intro: @ 82748A0
    .string "넌 이미 비밀기지를 만들었니?\p"
	.string "난 이곳저곳 돌아다니다가\n"
	.string "드디어 이곳으로 정했어!\p"
	.string "모처럼 왔으니까\n"
	.string "포켓몬 승부하지 않을래?$"

SecretBase_Text_Trainer0AcceptBattle: @ 8274939
    .string "그럼 간다!$"

SecretBase_Text_Trainer0DeclineBattle: @ 827494D
    .string "엇 지금은 안 되는구나...$"

SecretBase_Text_Trainer0Defeated:: @ 8274966
    .string "우왓 너 정말로 강하구나-\n"
	.string "내가 진 건 비밀로 해 줘!$"

SecretBase_Text_Trainer0PostBattle: @ 82749AA
    .string "내 비밀기지는 어때-\n"
	.string "내일 또 놀러 와!$"

SecretBase_Text_Trainer0PreChampion: @ 82749ED
    .string "넌 이미 비밀기지를 만들었니?\p"
	.string "난 이곳저곳 돌아다니다가\n"
	.string "드디어 이곳으로 정했어!\p"
	.string "천천히 있다 가!$"

SecretBase_Text_Trainer5Intro: @ 8274A64
    .string "비밀기지를 만들 수 있는 곳은\n"
	.string "다른 곳도 많이 있지만\l"
	.string "여기가 제일 마음에 들어!\p"
	.string "봐! 근사하지!\p"
	.string "앗 혹시 괜찮다면\n"
	.string "포켓몬 승부하지 않을래?$"

SecretBase_Text_Trainer5AcceptBattle: @ 8274AFA
    .string "그럼 간다!$"

SecretBase_Text_Trainer5DeclineBattle: @ 8274B0B
    .string "그래 지금은 안 되는구나...$"

SecretBase_Text_Trainer5Defeated:: @ 8274B24
    .string "으-음 내 패배네...\n"
	.string "내가 진 건 비밀이야!$"

SecretBase_Text_Trainer5PostBattle: @ 8274B6C
    .string "이 근처에 오게 된다면\n"
	.string "또 놀러 와줘!$"

SecretBase_Text_Trainer5PreChampion: @ 8274BA2
    .string "비밀기지를 만들 수 있는 곳은\n"
	.string "다른 곳도 많이 있지만\l"
	.string "여기가 제일 마음에 들어!\p"
	.string "봐! 근사하지!$"

SecretBase_Text_Trainer1Intro: @ 8274C13
    .string "이곳은 인기가 많아서\n"
	.string "항상 차 있어-\p"
	.string "앗 혹시\n"
	.string "너도 여기를 쓰고 싶어?\p"
	.string "으-음 나한테 이긴다면\n"
	.string "이곳을 가져도 좋아!$"

SecretBase_Text_Trainer1AcceptBattle: @ 8274CB0
    .string "좋아!\n"
	.string "내 기지를 지킬 거야-!$"

SecretBase_Text_Trainer1DeclineBattle: @ 8274CDA
    .string "엇 이곳에 관심없어?\n"
	.string "그렇구나-$"

SecretBase_Text_Trainer1Defeated:: @ 8274D13
    .string "더는 안 되겠다!\n"
	.string "항-복!$"

SecretBase_Text_Trainer1PostBattle: @ 8274D34
    .string "알았어 내가 언젠가 이사하게 된다면\n"
	.string "이곳은 네 거야!$"

SecretBase_Text_Trainer1PreChampion: @ 8274D69
    .string "이곳은 인기가 많아서\n"
	.string "항상 차 있어-\p"
	.string "나도 계속 기다리다가\n"
	.string "드디어 쓸 수 있게 되었지!$"

SecretBase_Text_Trainer6Intro: @ 8274DD2
    .string "내 포켓몬 연구소에\n"
	.string "잘 왔어!\p"
	.string "여기서 포켓몬 승부에 대해\n"
	.string "몰래 공부를 하고 있지\p"
	.string "어때 내 실력을 보여줄까?$"

SecretBase_Text_Trainer6AcceptBattle: @ 8274E41
    .string "진심으로 간다!$"

SecretBase_Text_Trainer6DeclineBattle: @ 8274E5A
    .string "그럼 다음에 하자!$"

SecretBase_Text_Trainer6Defeated:: @ 8274E75
    .string "으-음 나도 멀었네-\n"
	.string "더 공부해야겠다!$"

SecretBase_Text_Trainer6PostBattle: @ 8274EB3
    .string "승부해 줘서 고마워!\n"
	.string "내일 또 놀러 와-$"

SecretBase_Text_Trainer6PreChampion: @ 8274EF1
    .string "내 포켓몬 연구소에\n"
	.string "잘 왔어!\p"
	.string "여기서 포켓몬 승부에 대해\n"
	.string "몰래 공부를 하고 있지$"

SecretBase_Text_Trainer2Intro: @ 8274F39
    .string "커다란 집도 좋지만\n"
	.string "나는 이런 곳이 좋아\p"
	.string "왜냐면 다양한 사람이\n"
	.string "놀러 와주니까-!\p"
	.string "어때 포켓몬 승부할래?$"

SecretBase_Text_Trainer2AcceptBattle: @ 8274FCA
    .string "그렇게 나와야지!$"

SecretBase_Text_Trainer2DeclineBattle: @ 8274FDA
    .string "준비가 됐으면\n"
	.string "언제든 말을 걸어 줘!$"

SecretBase_Text_Trainer2Defeated:: @ 8274FFE
    .string "당했다-!\n"
	.string "하지만 포켓몬 승부는 즐거워-!$"

SecretBase_Text_Trainer2PostBattle: @ 827502A
    .string "자 굿즈라도 사러 가볼까?\p"
    .string "내 비밀기지에서\n"
    .string "모두가 재밌게 놀 수 있도록 말이야!$"

SecretBase_Text_Trainer2PreChampion: @ 82750A4
    .string "커다란 집도 좋지만\n"
	.string "나는 이런 곳이 좋아\p"
	.string "왜냐면 다양한 사람이\n"
	.string "놀러 와주니까-!$"

SecretBase_Text_Trainer7Intro: @ 8275114
    .string "저는 굿즈 쇼핑을\n"
	.string "엄청 좋아해요!\p"
	.string "그리고 그만큼 포켓몬 키우기도\n"
	.string "엄청 좋아해요!\p"
	.string "혹시 괜찮다면 제 포켓몬과\n"
	.string "승부해 주실래요?$"

SecretBase_Text_Trainer7AcceptBattle: @ 82751AF
    .string "그럼 잘 부탁드립니다$"

SecretBase_Text_Trainer7DeclineBattle: @ 82751CA
    .string "그렇군요 아쉽네요...$"

SecretBase_Text_Trainer7Defeated:: @ 82751E1
    .string "졌습니다...$"

SecretBase_Text_Trainer7PostBattle: @ 82751EC
    .string "아아 즐거웠어요!\n"
	.string "다음은 쇼핑이나 할까$"

SecretBase_Text_Trainer7PreChampion: @ 8275226
    .string "저는 굿즈 쇼핑을\n"
	.string "엄청 좋아해요\p"
	.string "그리고 그만큼 포켓몬 키우기도\n"
	.string "엄청 좋아해요$"

SecretBase_Text_Trainer3Intro: @ 8275287
    .string "찾기 힘든 곳에\n"
	.string "비밀기지를 만드는 사람이 있는데\l"
	.string "몰래 숨어 있고 싶은 걸까...\p"
	.string "음 모처럼 찾아와 주었으니까\n"
	.string "포켓몬 승부하지 않을래?$"

SecretBase_Text_Trainer3AcceptBattle: @ 8275315
    .string "간단히 끝나진 않겠어!$"

SecretBase_Text_Trainer3DeclineBattle: @ 8275330
    .string "혹시 찾는 데 지쳐버린 거야?$"

SecretBase_Text_Trainer3Defeated:: @ 8275367
    .string "끝나버렸다...$"

SecretBase_Text_Trainer3PostBattle: @ 8275374
    .string "네 비밀기지는 어디야!\n"
	.string "다음에 놀러 가야지-$"

SecretBase_Text_Trainer3PreChampion: @ 82753AB
    .string "찾기 힘든 곳에\n"
	.string "비밀기지를 만드는 사람이 있는데\l"
	.string "몰래 숨어 있고 싶은 걸까$"

SecretBase_Text_Trainer8Intro: @ 8275405
    .string "굿즈를 손에 넣는 방법은\n"
	.string "여러 가지 있다고들 이야기해\p"
	.string "어느 쪽이 근사한 굿즈를\n"
	.string "손에 넣는지 경쟁하자!\p"
	.string "그리고 포켓몬 승부도 하지 않을래?$"

SecretBase_Text_Trainer8AcceptBattle: @ 82754B2
    .string "내 비밀기지에서 질 수는 없지!$"

SecretBase_Text_Trainer8DeclineBattle: @ 82754D8
    .string "언제라도 승부 기다릴게!$"

SecretBase_Text_Trainer8Defeated:: @ 82754F6
    .string "엇 설마 내 패배?$"

SecretBase_Text_Trainer8PostBattle: @ 827550C
    .string "굿즈 모으기는 지지 않을 거야!\n"
	.string "또 놀러 와!$"

SecretBase_Text_Trainer8PreChampion: @ 8275546
    .string "굿즈를 손에 넣는 방법은\n"
	.string "여러 가지 있다고들 이야기해\p"
	.string "어느 쪽이 근사한 굿즈를\n"
	.string "손에 넣는지 경쟁하자!$"

SecretBase_Text_Trainer4Intro: @ 82755D2
    .string "멋진 곳을 찾아서\n"
	.string "좋아하는 굿즈를 놓는다!\p"
	.string "좋아하는 포켓몬을 키워서\n"
	.string "나도 함께 강해진다\p"
	.string "그런 나와 승부하자!$"

SecretBase_Text_Trainer4AcceptBattle: @ 8275679
    .string "네 실력을 보여 줘!$"

SecretBase_Text_Trainer4DeclineBattle: @ 8275696
    .string "뭐 그럴 때도 있지!$"

SecretBase_Text_Trainer4Defeated:: @ 82756C7
    .string "네 실력은 충분히 알았어!$"

SecretBase_Text_Trainer4PostBattle: @ 82756EF
    .string "너도 나도 더 강해질 수 있어!\n"
	.string "서로 힘내자!$"

SecretBase_Text_Trainer4PreChampion: @ 827571E
    .string "멋진 곳을 찾아서\n"
	.string "좋아하는 굿즈를 놓는다!\p"
	.string "좋아하는 포켓몬을 키워서\n"
	.string "나도 함께 강해진다\p"
	.string "매일이 즐거워-$"

SecretBase_Text_Trainer9Intro: @ 82757B5
    .string "굿즈의 종류나 놓는 방법을 보면\n"
	.string "그 사람이 어떤 센스가 있는지\l"
	.string "자-알 알 수 있어!\p"
	.string "내 센스는 어떤 것 같아?\n"
	.string "우후후 아무 말도 안 하는구나!\p"
	.string "승부 센스도 시험해 볼래?$"

SecretBase_Text_Trainer9AcceptBattle: @ 8275884
    .string "있는 힘껏 간다!$"

SecretBase_Text_Trainer9DeclineBattle: @ 827589D
    .string "언제라도 내 센스를 보여줄게!$"

SecretBase_Text_Trainer9Defeated:: @ 82758CC
    .string "굉장한 재능이네!\n"
	.string "끝없는 강함을 느꼈어...$"

SecretBase_Text_Trainer9PostBattle: @ 8275909
    .string "내 센스 어땠어?\n"
	.string "더 센스를 갈고닦을 거야-$"

SecretBase_Text_Trainer9PreChampion: @ 8275944
    .string "굿즈의 종류나 놓는 방법을 보면\n"
	.string "그 사람이 어떤 센스가 있는지\l"
	.string "자-알 알 수 있어!\p"
	.string "내 센스는 어떤 것 같아?\n"
	.string "우후후 아무 말도 안 하는구나!$"
