Route102_Text_CalvinIntro:
	.string "포켓몬을 데리고 있다면\n"
	.string "너도 이제 어엿한 포켓몬 트레이너!\l"
	.string "내 도전을 받아줄 거지!?$"
	// ポケモン つれていればｎ
	// キミも りっぱな ポケモントレ-ナ-!ｌ
	// ボクの ちょうせん うけるよね!

Route102_Text_CalvinDefeated:
	.string "아아 졌다...\n"
	.string "더 키워둘 걸 그랬어$"
	// ああ まけた……ｎ
	// もっと そだてておけば よかったよ

Route102_Text_CalvinPostBattle:
	.string "너 강하면 강하다고\n"
	.string "처음부터 말을 해줬어야지!$"
	// キミ つよいなら つよいってｎ
	// さいしょから いって くれよな!

Route102_Text_CalvinRegister:
	.string "나 그 뒤로 열심히 노력했어!\n"
	.string "다음에도 배틀하고 싶으니까\l"
	.string "포켓내비에 등록해 주라!$"
	// ボク あれから がんばってるよ!ｎ
	// こんど たたかいたい からｌ
	// ポケナビ とうろく してよ!

Route102_Text_CalvinRegisterShort:
	.string "다음에 또 배틀하고 싶으니까\l"
	.string "포켓내비에 등록해 주라!$"
	// こんど また たたかいたい からｎ
	// ポケナビ とうろく してよ!

Route102_Text_CalvinRematchIntro:
	.string "너한테 지고 나서 필사적으로\n"
	.string "포켓몬을 키웠어! 당연히\l"
	.string "내 도전을 받아줄 거지!?$"
	// キミに まけてから ひっしにｎ
	// ポケモン そだてたんだ! もちろんｌ
	// ボクの ちょうせん うけるよね!

Route102_Text_CalvinRematchDefeated:
	.string "아아 졌다...\n"
	.string "키우는 방법이 잘못됐나$"
	// ああ まけた……ｎ
	// そだてかた わるいのかな

Route102_Text_CalvinRematchPostBattle:
	.string "네가 강해진다면\n"
	.string "나도 더욱 강해지겠어!$"
	// キミが つよくなるならｎ
	// ボクも もっと つよくなって みせるよ!

Route102_Text_AllenIntro:
	.string "이제 막 트레이너가 된 거야?\n"
	.string "우리 둘 다 초심자구나!$"
	// きみ トレ-ナ-に なったばかり?ｎ
	// おたがい しょしんしゃ だね!

Route102_Text_AllenDefeated:
	.string "이길 수 있을 거 같아서\n"
	.string "말을 걸었던 건데!$"
	// かてると おもったからｎ
	// こえを かけたのに!

Route102_Text_AllenPostBattle:
	.string "아직 한 번도 못 이겼어...\n"
	.string "빨리 이기고 싶다...$"
	// まだ 1かいも かってない……ｎ
	// はやく かちたいなあ……

Route102_Text_RickIntro:
	.string "앗! 눈이 마주쳤다!\n"
	.string "벌레포켓몬으로 상대해 주지!$"
	// おっと! めが あったな!ｎ
	// むしポケモンで あいてを するぜ!

Route102_Text_RickDefeated:
	.string "지고 말았다!$"
	// まけてしまった!

Route102_Text_RickPostBattle:
	.string "눈이 마주친 트레이너에게는\n"
	.string "승부를 거는 게 원칙이지!$"
	// めが あった トレ-ナ-にはｎ
	// しょうぶを いどむのが きまりさ!

Route102_Text_TianaIntro:
	.string "나는 계속 이겨서\n"
	.string "최강 트레이너가 될 거야!\p"
	.string "너도 협력해줘!$"
	// わたしは どんどん かちぬいてｎ
	// さいきょうの トレ-ナ-を めざすのよ!ｐ
	// あなたも きょうりょく してね!

Route102_Text_TianaDefeated:
	.string "내가 너한테\n"
	.string "협력하게 된 것 같네...$"
	// わたしが あなたにｎ
	// きょうりょく しちゃった みたいね……

Route102_Text_TianaPostBattle:
	.string "계속 이기기 위해선\n"
    .string "좀 더 포켓몬을\l"
	.string "잡아야 할 것 같아!$"
	// どんどん かちぬくにはｎ
	// もっと たくさん ポケモンをｌ
	// つかまえないと いけない みたいね!

Route103_Text_DaisyIntro:
	.string "마음이 편안해지는 향기에\n"
	.string "이끌려 온 거군요...$"
	// こころ やすらぐ かおりにｎ
	// あなたも さそわれたのですね……

Route103_Text_DaisyDefeated:
	.string "제 향기에\n"
	.string "넘어가지 않은 거군요...$"
	// わたくしの かおりにｎ
	// まどわされませんでしたね……

Route103_Text_DaisyPostBattle:
	.string "아로마란 향기를 뜻합니다...\n"
	.string "향기는 몸과 마음을 치유하죠$"
	// アロマとは かおりのこと……ｎ
	// かおりは こころと からだを いやすのです

Route103_Text_AmyIntro:
	.string "루비: 나는 루비!\n"
	.string "이쪽은 여동생 루미!\l"
	.string "둘이서 같이 승부할 거야!$"
	// クミ『あたしは クミ!ｎ
	// こっちは いもうとの ルミ!ｌ
	// ふたりで いっしょに たたかうのよ!

Route103_Text_AmyDefeated:
	.string "루비: 져버렸어...$"
	// クミ『まけっちゃったよぉ……

Route103_Text_AmyPostBattle:
	.string "루비: 두 명을 상대하려면\n"
	.string "여러 가지를 곰곰이 생각해야 해!$"
	// クミ『ふたりを あいてに するのってｎ
	// いろんな ことを かんがえるよね!

Route103_Text_AmyNotEnoughPokemon:
	.string "루비: 어라?\n"
	.string "포켓몬은 딱 1마리만 데리고 있구나!\l"
	.string "그럼 우리랑 배틀할 수 없어!$"
	// クミ『あら?ｎ
	// ポケモン 1ひきしか つれてないんだね!ｌ
	// それじゃあ あたしたちと たたかえないわ!

Route103_Text_LivIntro:
	.string "루미: 우리 둘은 하나\n"
	.string "같이 배틀할 거야!$"
	// ルミ『あたしたちは ふたりで ひとりｎ
	// いっしょに たたかうんだよ!

Route103_Text_LivDefeated:
	.string "루미: 져버렸어 언니...$"
	// ルミ『まけちゃったよぉ おねえちゃぁん……

Route103_Text_LivPostBattle:
	.string "루미: 언니랑 나는\n"
	.string "호흡이 딱 맞는데...\p"
	.string "져버렸어...$"
	// ルミ『おねえちゃんと あたしはｎ
	// いきが ぴったり あってるのに……ｐ
	// まけちゃったよぉ……

Route103_Text_AmyLivRegister:
	.string "루미: 우린 사실\n"
	.string "더 강하단 말이야...\l"
	.string "정말이야! 다음에 보여줄게!$"
	// ルミ『あたしたち ほんとはｎ
	// もっと つよいんだもん……ｌ
	// ほんとうだから! こんど みせるから!

Route103_Text_LivNotEnoughPokemon:
	.string "루미: 우리랑 배틀하고 싶으면\n"
	.string "포켓몬이 2마리 있어야 해!\l"
	.string "없으면 승부가 안 되니까!$"
	// ルミ『あたしたちと たたかいたいならｎ
	// ポケモンを 2ひき つれてないと ダメよ!ｌ
	// じゃないと しょうぶに ならないんだから!

Route103_Text_AmyRematchIntro:
	.string "루비: 나는 루비!\n"
	.string "이쪽은 여동생 루미!\l"
	.string "둘이서 같이 승부할 거야!$"
	// クミ『あたしは クミ!ｎ
	// こっちは いもうとの ルミ!ｌ
	// ふたりで いっしょに たたかうのよ!

Route103_Text_AmyRematchDefeated:
	.string "루비: 분해...\n"
	.string "또 져버렸어...$"
	// クミ『くやしい……ｎ
	// また かてなかったよぉ……

Route103_Text_AmyRematchPostBattle:
	.string "루비: 두 명을 상대하려면\n"
	.string "여러 가지를 고려해야 돼!$"
	// クミ『ふたりを あいてに するのってｎ
	// いろんな ことを かんがえるよね!

Route103_Text_AmyRematchNotEnoughPokemon:
	.string "루비: 어라?\n"
	.string "포켓몬을 1마리만 데리고 있네!\l"
	.string "그럼 우리랑 배틀할 수 없어!$"
	// クミ『あら?ｎ
	// ポケモン 1ひきしか つれてないんだね!ｌ
	// それじゃあ あたしたちと たたかえないわ!

Route103_Text_LivRematchIntro:
	.string "루미: 우리 둘은 하나\n"
	.string "항상 같이 승부하고 있어!$"
	// ルミ『あたしたちは ふたりで ひとりｎ
	// いつも いっしょに たたかうんだよ!

Route103_Text_LivRematchDefeated:
	.string "루미: 또 져버렸어\n"
	.string "언니...$"
	// ルミ『また まけちゃったよぉｎ
	// おねえちゃぁん……

Route103_Text_LivRematchPostBattle:
	.string "루미: 언니랑 나는\n"
	.string "호흡이 딱 맞는데...\p"
	.string "왜 또 져버렸을까?$"
	// ルミ『おねえちゃんと あたしはｎ
	// いきが ぴったり あってるのに……ｐ
	// どうして また まけちゃったの?

Route103_Text_LivRematchNotEnoughPokemon:
	.string "루미: 우리랑 배틀하고 싶으면\n"
	.string "포켓몬을 2마리 데리고 있어야 돼!\l"
	.string "안 그러면 승부가 안 되니까!$"
	// ルミ『あたしたちと たたかいたいならｎ
	// ポケモンを 2ひき つれてないと ダメよ!ｌ
	// じゃないと しょうぶに ならないんだから!

Route103_Text_AndrewIntro:
	.string "낚싯줄이 엉켜서 진짜 짜증 난다!\n"
	.string "에라잇! 승부다!$"
	// つりいとが からまって イライラする-っ!ｎ
	// ええいっ しょうぶだっ!

Route103_Text_AndrewDefeated:
	.string "졌다!\n"
	.string "괜히 더 짜증 난다-!$"
	// まけたっ!ｎ
	// よけいに イライラするぞ-っ!

Route103_Text_AndrewPostBattle:
	.string "아오 열 받아...!\n"
	.string "부글부글부글부글...$"
	// ええい はらだたしい……!ｎ
	// イライライライラ……

Route103_Text_MiguelIntro:
	.string "나의 엄청나게 귀여운\n"
	.string "포켓몬을 보고 가시지!$"
	// わたしの ポケモンちゃんｎ
	// すごく かわいいから みていきたまえ!

Route103_Text_MiguelDefeated:
	.string "으아아...\n"
	.string "나의 귀여운 포켓몬이!$"
	// あわわ……ｎ
	// わたしの ポケモンちゃん!

Route103_Text_MiguelPostBattle:
	.string "나의 귀여운 포켓몬은\n"
	.string "패배한 모습도 귀여워...$"
	// かわいい ポケモンちゃんはｎ
	// やられた すがたも かわいいな……

Route103_Text_MiguelRegister:
	.string "몇 번이든 귀여운 포켓몬을\n"
	.string "보러와 줘야 돼!$"
	// なんどでも かわいい ポケモンちゃんをｎ
	// みにきて もらうんだからね!

Route103_Text_MiguelRematchIntro:
	.string "너! 나의 귀여운 포켓몬이\n"
	.string "더 귀여워졌다고!$"
	// きみ! わたしの ポケモンちゃんｎ
	// さらに かわいく なったのだ!

Route103_Text_MiguelRematchDefeated:
	.string "아아!\n"
	.string "나의 귀여운 포켓몬이!$"
	// ああ!ｎ
	// わたしの ポケモンちゃん!

Route103_Text_MiguelRematchPostBattle:
	.string "같이 있으면 있을수록\n"
	.string "포켓몬이 귀여워져서 못 참겠어!$"
	// いっしょに いれば いるほどｎ
	// ポケモンが かわいくなって たまらん!

Route103_Text_PeteIntro:
	.string "이 정도 거리는\n"
	.string "헤엄치면 껌이지!$"
	// この くらいの きょりｎ
	// およいで わたれば い-のにさ!

Route103_Text_PeteDefeated:
	.string "오오 제법인데$"
	// おお やるじゃん

Route103_Text_PetePostBattle:
	.string "그렇군\p"
	.string "그 정도로 믿을 만한 포켓몬이라면\n"
	.string "생각 않고 파도타기를 쓰게 되지$"
	// な-るほどｐ
	// それ ほど たよれる ポケモンならｎ
	// おもわず なみのり したくなる ってもんだ

Route103_Text_IsabelleIntro:
	.string "꺄 부딪친다!\n"
	.string "위험해애!$"
	// きゃあ ぶつかるわ!ｎ
	// あぶないっ!

Route103_Text_IsabelleDefeated:
	.string "으음...$"
	// んん……

Route103_Text_IsabellePostBattle:
	.string "나 수영 못해서\n"
	.string "연습 중이었어...\l"
	.string "부딪쳐서 미안해$"
	// わたし およぎが へたでｎ
	// れんしゅう してたのよ……ｌ
	// ぶつかりそうに なって ゴメンね

Route103_Text_RhettIntro:
	.string "우와!\n"
	.string "이런 좁은 장소엔 왜!?$"
	// うぉっ!ｎ
	// なぜ こんな せまいところに!?

Route103_Text_RhettDefeated:
	.string "우와 좀 하네!$"
	// うぉっ できる!

Route103_Text_RhettPostBattle:
	.string "넌 이런 좁은 장소가\n"
	.string "좋은 거야?$"
	// せまい ところがｎ
	// すき なのかい きみは?

Route103_Text_MarcosIntro:
	.string "내 기타 소리에 이끌려\n"
	.string "찾아온 거구나-?$"
	// おれっちの ギタ-に さそわれてｎ
	// やって きたのか-い?

Route103_Text_MarcosDefeated:
	.string "내 원맨쇼는 망했어$"
	// おれっちの ひとりショ-が だいなしだよ

Route103_Text_MarcosPostBattle:
	.string "사람이 없는 곳에서\n"
	.string "기타를 연주하고 있었는데\l"
	.string "이렇게나 사람이 많이 모였어!\p"
	.string "프 프로를 노려볼까?$"
	// ひとの すくない ところでｎ
	// ギタ-を ひいていたのにｌ
	// こんなにも あつまって きたぜ!ｐ
	// ぷ プロを めざして みるか!

Route104_Text_GinaIntro:
	.string "치선: 좋-아!\n"
	.string "우리들의 포켓몬과 배틀하는 거예요!$"
	// ナオ『よ-し!ｎ
	// あたしたちの ポケモンと たたかうです!

Route104_Text_GinaDefeat:
	.string "치선: 져버려서 너무 분해요$"
	// ナオ『まけて すごく くやしいです

Route104_Text_GinaPostBattle:
	.string "치선: 우와- 당신 정말 강해요!\n"
	.string "우리 더 열심히 수행할 거예요$"
	// ナオ『うわ- §い つよいです!ｎ
	// あたしたち もっと しゅぎょう するです

Route104_Text_GinaNotEnoughMons:
	.string "치선: 어라? 포켓몬이 한 마리뿐이잖아요!?\n"
	.string "그럼 우리랑 배틀할 수 없어요!\p"
	.string "그야 한 마리뿐이면\n"
	.string "포켓몬이 외로워보여서 불쌍하니까요!$"
	// ナオ『あら? ポケモン 1ひき だけですか!ｎ
	// じゃあ あたしたち たたかわない です!ｐ
	// だって ポケモン 1ひき だけだとｎ
	// ポケモンが さびしそうで かわいそう です!

Route104_Text_MiaIntro:
	.string "우나: 우리들은 쌍둥이니까\n"
	.string "포켓몬 승부도 같이 하는 거예요!$"
	// ミオ『あたしたち ふたご だからｎ
	// ポケモンしょうぶも いっしょに するです!

Route104_Text_MiaDefeat:
	.string "우나: 둘이서 같이 승부했는데도\n"
	.string "져버렸어요...$"
	// ミオ『ふたりで しょうぶ したのにｎ
	// まけちゃったです……

Route104_Text_MiaPostBattle:
	.string "우나: 더 포켓몬을 키워서\n"
	.string "당신처럼 강해질 거예요!$"
	// ミオ『もっと ポケモン そだててｎ
	// §い みたいに つよく なるです!

Route104_Text_MiaNotEnoughMons:
	.string "우나: 우리랑 배틀하고 싶은가요?\p"
	.string "그럼 포켓몬을\n"
	.string "두 마리를 데리고 있어야 해요!\l"
	.string "왜냐면 우린 진짜 강하니까요!$"
	// ミオ『あたしたちと たたかうですか?ｐ
	// じゃあ ポケモンをｎ
	// 2ひき つれてないと ダメですよ!ｌ
	// だって あたしたち つよいもん!

Route104_Text_IvanIntro:
	.string "물포켓몬 전문가란\n"
	.string "바로 이 몸을 뜻하는 말이지!\p"
	.string "...응?\n"
	.string "모른다고?$"
	// みずポケモンの エキスパ-トとはｎ
	// なにを かくそう オレのこと!ｐ
	// ……え?ｎ
	// しらないの?

Route104_Text_IvanDefeat:
	.string "꽤 강하다고 생각했었는데\n"
	.string "나한테... 실망이야...$"
	// けっこう つよいと おもってたんだけどなｎ
	// じぶんのこと…… がっかり……

Route104_Text_IvanPostBattle:
	.string "낚시에 푹 빠져서\n"
	.string "포켓몬 키우는 걸 잊고 있었어...$"
	// つりに むちゅうに なっててｎ
	// ポケモン そだてるのを わすれてたよ……

Route104_Text_BillyIntro:
	.string "백사장에 발자국을 남기는 건\n"
	.string "진-짜 신-나!$"
	// すなはまに あしあと つけるのってｎ
	// たのし-よね-!

Route104_Text_BillyDefeat:
	.string "으엑-!\n"
	.string "신발에 모래가 들어가서 까끌까끌해!$"
	// うへ-っ!ｎ
	// クツに すなが はいって ジャリジャリする!

Route104_Text_BillyPostBattle:
	.string "백사장을 내 발자국으로\n"
	.string "가득 채우고 싶은데\l"
	.string "금방 사라져 버려$"
	// すなはまを ボクの あしあとでｎ
	// いっぱいに したいんだけどｌ
	// すぐに きえちゃうんだよなぁ

Route104_Text_HaleyIntro:
	.string "승부할까...\n"
	.string "그냥 하지 말까...\p"
	.string "에잇! 배틀해야지!$"
	// しょうぶ しようかな……ｎ
	// やめとこうかな……ｐ
	// え-い! たたかっちゃえ!

Route104_Text_HaleyDefeat:
	.string "배틀하지 말 걸 그랬어...$"
	// たたかわなければ よかったかな……

Route104_Text_HaleyPostBattle:
	.string "어느 쪽을 선택할지 망설여질 때\n"
	.string "스스로 결정하지 않고 남한테 맡기면\l"
	.string "결과와 상관없이 후회하게 돼...$"
	// どっちに しようか まよってる ときｎ
	// じぶんで きめないで たにんに まかせるとｌ
	// どっちに なっても こうかいするね……

Route104_Text_HaleyRegister1:
	.string "너 강한데\n"
	.string "포켓내비에 등록할까...\l"
	.string "하지 말까...\p"
	.string "에잇! 등록해야지!$"
	// あなた つよいけどｎ
	// ポケナビに とうろく しようかな……ｌ
	// やめとこうかな……ｐ
	// え-い! とうろくしちゃえ!

Route104_Text_HaleyRegister2:
	.string "너 강한데\n"
	.string "포켓내비에 등록할까...\l"
	.string "하지 말까...\p"
	.string "에잇! 등록해야지!$"
	// あなた つよいけどｎ
	// ポケナビに とうろく しようかな……ｌ
	// やめとこうかな……ｐ
	// え-い! とうろくしちゃえ!

Route104_Text_HaleyRematchIntro:
	.string "나랑 승부하자!$"
	// あたしと しょうぶ してもらうわよ!

Route104_Text_HaleyRematchDefeat:
	.string "으-으...\n"
	.string "이길 수 있을 거 같았는데$"
	// う-ん……ｎ
	// かてると おもったのにな

Route104_Text_HaleyPostRematch:
	.string "배틀하기로 스스로 결정했으니까\n"
	.string "졌어도 그냥 후련해!\p"
	.string "...물론 분하기도 하지만$"
	// たたかうって じぶんで きめたからｎ
	// まけても すっきり してるわ!ｐ
	// ……もちろん まけて くやしいけどね

Route104_Text_WinstonIntro:
	.string "내가 직접 상대해 주지\n"
	.string "돈이 많은 내가 말이야$"
	// ボクが あいてして あげるよｎ
	// この おかねもちの ボクがね

Route104_Text_WinstonDefeat:
	.string "왜 이길 수 없는 거지...!?$"
	// どうして かてないんだ……!?

Route104_Text_WinstonPostBattle:
	.string "돈으로는 이길 수 없는 것...\n"
	.string "그게 바로 포켓몬 승부...$"
	// おかねじゃ かてない ものが ある……ｎ
	// それが ポケモンなんだね……

Route104_Text_WinstonRegister1:
	.string "응? 너 포켓내비를 얻었구나!\p"
	.string "내가 등록시켜 줄게\n"
	.string "돈이 많은 내가 말이야$"
	// ん? きみ ポケナビを てにいれたね!ｐ
	// ボクが とうろくして あげようｎ
	// この おかねもちの ボクがね

Route104_Text_WinstonRegister2:
	.string "응? 너 포켓내비를 얻었구나!\p"
	.string "내가 등록시켜 줄게\n"
	.string "돈이 많은 내가 말이야$"
	// ん? きみ ポケナビを てにいれたね!ｐ
	// ボクが とうろくして あげようｎ
	// この おかねもちの ボクがね

Route104_Text_WinstonRematchIntro:
	.string "너한테 진 이후로 여러모로\n"
	.string "포켓몬을 많이 공부했어!$"
	// きみに まけてから いろいろｎ
	// ポケモンのこと べんきょう したんだ!

Route104_Text_WinstonRematchDefeat:
	.string "또 졌다...\n"
	.string "왜 이길 수 없는 거지...!?$"
	// また まけた……ｎ
	// どうして かてないんだ……!?

Route104_Text_WinstonPostRematch:
	.string "돈이 많은 내가\n"
	.string "포켓몬 승부에선 이길 수 없다니...\p"
	.string "얼마나 심오한 거야\n"
	.string "포켓몬 승부는...$"
	// おかねもちの ボク なのにｎ
	// なかなか ポケモンに かてない……ｐ
	// なんて おくが ふかいんだろうｎ
	// ポケモンって……

Route104_Text_CindyIntro:
	.string "당신과 만난 것도 뭔가의 인연이겠죠\n"
	.string "저와 승부해 주시겠어요?$"
	// あなたと であったのも なにかの ごえんｎ
	// おてあわせを おねがい できるかしら

Route104_Text_CindyDefeat:
	.string "어머!$"
	// まあ!

Route104_Text_CindyPostBattle:
	.string "만남은 이별의 시작...\n"
	.string "또 어딘가에서 만납시다$"
	// であいは わかれの はじまり……ｎ
	// また どこかで おあいしましょう

Route104_Text_CindyRegister1:
	.string "어머... 다시 만났군요\p"
	.string "뭔가의 인연이 있는 것 같네요\n"
	.string "포켓내비에 등록해 주세요$"
	// あら…… また おあい しましたわねｐ
	// こんなに ごえんが あるんですものｎ
	// ポケナビに とうろく して くださいませ

Route104_Text_CindyRegister2:
	.string "이 인연을 기념해\n"
	.string "포켓내비에 등록해 주세요$"
	// この ごえんを きねんしてｎ
	// ポケナビに とうろく して くださいませ

Route104_Text_CindyRematchIntro:
	.string "또 만났군요\n"
	.string "저와 승부해 주시겠어요?$"
	// また おあい しましたわねｎ
	// おてあわせ おねがい できるかしら

Route104_Text_CindyRematchDefeat:
	.string "어머...\n"
	.string "최선을 다했는데...$"
	// あら……ｎ
	// わたくし ベストを つくしましたのに……

Route104_Text_CindyPostRematch:
	.string "만남은 이별의 시작...\n"
	.string "또 어딘가에서 만납시다$"
	// であいは わかれの はじまり……ｎ
	// また どこかで おあいしましょう

Route104_Text_DarianIntro:
	.string "강해보이는 포켓몬을 낚았어!\n"
	.string "물고기의 왕이라는 느낌이야!\l"
	.string "분명히 강할 거라고!$"
	// つよそうな ポケモンが つれたっ!ｎ
	// さかなの おうさま って かんじだ!ｌ
	// これは つよそうだぞっ!

Route104_Text_DarianDefeat:
	.string "뭣이라$"
	// なっにい

Route104_Text_DarianPostBattle:
	.string "이름이 그러면서 왜 지는 건데\n"
	.string "내 잉어킹아!$"
	// おい なまえ まけ してるじゃないかｎ
	// おれの コイキングよ!

Route105_Text_FosterIntro:
	.string "이 근처에\n"
	.string "이상한 바위가 있다는데\l"
	.string "넌 뭐 아는 거 없나?$"
	// この あたりにｎ
	// ふしぎな いわが あるらしいがｌ
	// きみ しらないかい?

Route105_Text_FosterDefeated:
	.string "바위 생각만 하고 있었더니\n"
	.string "포켓몬은 생각하지 못했군...$"
	// いわのこと ばかり かんがえてｎ
	// ポケモン よわいまま だったか……

Route105_Text_FosterPostBattle:
	.string "멋진 바위는\n"
	.string "몇 시간을 보고 있어도 질리지 않지...$"
	// すてきな いわ だったらｎ
	// なんじかん みていても あきないよ……

Route105_Text_LuisIntro:
	.string "다행이야! 어린애가\n"
	.string "물에 빠진 줄 알고 걱정했어!\p"
	.string "멀쩡해 보이니 승부하자!$"
	// よかった! こどもがｎ
	// おぼれているのかと しんぱい したよ!ｐ
	// だいじょうぶ そうだから しょうぶ だな!

Route105_Text_LuisDefeated:
	.string "꼬륵꼬륵...$"
	// ゴボゴボ……

Route105_Text_LuisPostBattle:
	.string "해변 쪽으로 팔을 흔들면\n"
	.string "그게 물에 빠졌다는 신호야!$"
	// すなはまに むかって かたてを ふるのがｎ
	// おぼれたときの サインだぜ!

Route105_Text_DominikIntro:
	.string "새파란 바다에서 헤엄치고 있으면\n"
	.string "정말 기분 최고지!$"
	// あおい うみで およいでいるとｎ
	// さいこうの きぶん だな!

Route105_Text_DominikDefeated:
	.string "졌다...\n"
	.string "새파랗게 질린 기분...$"
	// まけた……ｎ
	// ブル-な きぶん……

Route105_Text_DominikPostBattle:
	.string "바다가 파란 이유!?\p"
	.string "잿빛도시에 있는 박물관에서 들었는데\n"
	.string "그런 건 잊어버렸어!$"
	// うみが あおい りゆう!?ｐ
	// カイナの はくぶつかんで きいたけどｎ
	// そんなの わすれちまったよ!

Route105_Text_BeverlyIntro:
	.string "물속에 들어오면 몸이 가벼워져서\n"
	.string "왠지 날씬해진 것 같은 기분이 들어!$"
	// みずに はいると からだが かるくなるわねｎ
	// なんだか スリムに なったみたい!

Route105_Text_BeverlyDefeated:
	.string "둥실둥실...$"
	// ぷかぷか……

Route105_Text_PostBattle:
	.string "물속에서는 체중이\n"
	.string "10분의 1 정도가 돼\p"
	.string "그럼 지금 난...\n"
	.string "안 돼! 내 몸무게가 들통날 거야!$"
	// みずの なかでは たいじゅうがｎ
	// 10ぶんの1 くらいに なるのよｐ
	// と すると いま わたしは……ｎ
	// いけない! たいじゅうが バレちゃうわ!

Route105_Text_ImaniIntro:
	.string "파란 하늘...\n"
	.string "넓은 바다...\l"
	.string "정말 편하고 느긋해...$"
	// あおい そら……ｎ
	// ひろい うみ……ｌ
	// のどか よね-……

Route105_Text_ImaniDefeated:
	.string "느긋하게 있다가\n"
	.string "져버렸어-!$"
	// なごんでいる うちにｎ
	// まけちゃったわ-っ!

Route105_Text_ImaniPostBattle:
	.string "너랑 같이 있으면\n"
	.string "편안해진다는 말을 듣고 싶어\l"
	.string "우후후후후!$"
	// あたしと いると なごむって いわれたいのｎ
	// うふふふふ!

Route105_Text_AndresIntro:
	.string "바다엔 뭔가가 있을 거라는\n"
	.string "확신이 든다!$"
	// うみに こそ なにかが あるとｎ
	// かくしんが ある!

Route105_Text_AndresDefeated:
	.string "맞아... 난\n"
	.string "승부를 잘 못해$"
	// うん…… わしｎ
	// しょうぶは よわいんだよ

Route105_Text_AndresPostBattle:
	.string "이 세상의 모든 바다에는\n"
	.string "아직도 비밀이 있을 게 분명해!\l"
	.string "몽땅 찾아내야지!$"
	// せかいじゅうの うみにはｎ
	// まだまだ ひみつが あるはずだ!ｌ
	// ぜんぶ さがしまくるぞ!

Route105_Text_AndresRegister:
	.string "응? 이런 약한 나를\n"
	.string "포켓내비에 등록해 주는 건가?$"
	// ん? こんな よわい わしでもｎ
	// ポケナビ とうろくして くれるのか?

Route105_Text_AndresRematchIntro:
	.string "승부엔 약하다고 했는데...\n"
	.string "나라도 괜찮은 건가?$"
	// しょうぶは よわいと いっているのに……ｎ
	// わし なんかで いいのか?

Route105_Text_AndresRematchDefeated:
	.string "음... 역시 못 이기겠군$"
	// うん…… やっぱり かてないな

Route105_Text_AndresRematchPostBattle:
	.string "승부에선 약하지만\n"
	.string "탐구심은 자네에게도 지지 않지!\l"
	.string "이 세상의 모든 바다를 탐험할 걸세!$"
	// しょうぶは よわいがｎ
	// たんきゅうしんは きみにも まけん!ｌ
	// せかいじゅうの うみを たび するぞ!

Route105_Text_JosueIntro:
	.string "안 하던 수영을 해서 지쳤어-\n"
	.string "기분 전환으로 포켓몬 승부를 하자!$"
	// なれない およぎで つかれた-ｎ
	// きばらしに ポケモンしょうぶ じゃい!

Route105_Text_JosueDefeated:
	.string "바다에서 승부해서 진거야$"
	// うみで たたかった から まけたんだ

Route105_Text_JosuePostBattle:
	.string "역시 나한테는\n"
	.string "바다보단 하늘이 잘 어울려$"
	// やっぱりさ おれにはｎ
	// うみより そらが にあってるんだよ

Route106_Text_ElliotIntro:
	.string "바다낚시와 민물낚시\n"
	.string "넌 어느 쪽이 더 좋냐?$"
	// うみづりと かわづりｎ
	// キミは どっちが すき?

Route106_Text_ElliotDefeated:
	.string "마치 바다낚시와 같은\n"
	.string "광활한 패배다!$"
	// まるで うみづりの ようにｎ
	// ごうかいに まけたぞ-っ!

Route106_Text_ElliotPostBattle:
	.string "바다든 강이든 낚시는 최고다!\n"
	.string "너도 그렇게 생각하지 않나!?$"
	// うみでも かわでも つりは サイコ-だ!ｎ
	// キミも そう おもうだろ!?

Route106_Text_ElliotRegister:
	.string "낚시도 좋지만 승부도 좋지!\n"
	.string "너 괜찮다면 또 부탁한다!$"
	// つりも いいけど しょうぶも いいな!ｎ
	// キミ よかったら また たのむよ!

Route106_Text_ElliotRematchIntro:
	.string "포켓몬을 왕창 낚았으니까\n"
	.string "엄청난 승부를 펼쳐주마-!$"
	// ポケモン つりまくったからねｎ
	// すごい しょうぶを してみせるぞ-!

Route106_Text_ElliotRematchDefeated:
	.string "또 광활한 패배다-!$"
	// また ごうかいに まけたぞ-っ!

Route106_Text_ElliotRematchPostBattle:
	.string "이기든 지든 포켓몬은 최고다!\n"
	.string "너도 그렇게 생각하지 않나!?$"
	// かっても まけても ポケモンは サイコ-だ!ｎ
	// キミも そう おもうだろ!?

Route106_Text_NedIntro:
	.string "화장실에 가고 싶을 때는\n"
	.string "다들 어떻게 하는 걸까...?\p"
	.string "화장실에 가 있는 동안\n"
	.string "월척이 걸릴지도 모른다고 생각하면...$"
	// トイレに いきたくなったときｎ
	// みんなは どうしてるんだろう……?ｐ
	// トイレに いっている あいだにｎ
	// もし おおものが かかったらと おもうと……

Route106_Text_NedDefeated:
	.string "화장실에 안 가고 참고 있어서\n"
	.string "진 걸 거야 분명히...$"
	// トイレを がまん してたからｎ
	// まけたんだよ きっと……

Route106_Text_NedPostBattle:
	.string "아앗!\n"
	.string "월척을 낚을 수 있을 듯한 예감이...!$"
	// ああっ!ｎ
	// おおものが つれそうな よかん……!

Route106_Text_DouglasIntro:
	.string "핫핫핫!\n"
	.string "육지에서는 빨리 달릴 수 없지만\l"
	.string "물속에서라면 지지 않는다!$"
	// はっはっはっ!ｎ
	// りくでは はやく はしれないがｌ
	// みずの なかなら まけないぞ!

Route106_Text_DouglasDefeated:
	.string "졌습니다-앗!$"
	// まいりました-っ!

Route106_Text_DouglasPostBattle:
	.string "수영이라면 안 질 텐데...$"
	// すいえいの きょうそうなら まけないのに……

Route106_Text_KylaIntro:
	.string "바다는 내 구역이야\n"
	.string "어린애라고 봐주지 않겠어!$"
	// うみは わたしの にわｎ
	// こども だからって てかげん しないわよ!

Route106_Text_KylaDefeated:
	.string "설마\n"
	.string "봐준 건 아니지?$"
	// ひょっとしてｎ
	// てかげん してないよね?

Route106_Text_KylaPostBattle:
	.string "파도에 몸을 싣고 떠도는 게 좋아\n"
	.string "너도 해볼래?$"
	// なみに ゆられて ただようのが だいすきｎ
	// あなたも やってみない?

Route107_Text_DarrinIntro:
	.string "흠냐흠냐...\p"
	.string "파도에 몸을 맡겼더니 기분이 좋아서\n"
	.string "깜빡 졸고 말았군!$"
	// むにゃむにゃ……ｐ
	// なみに ゆられてたら きもちよくなってｎ
	// うっかり ねてしまった!

Route107_Text_DarrinDefeated:
	.string "아하하... 졌다...\n"
	.string "다시 잠이나 잘까...$"
	// あはは まけた……ｎ
	// また ねますか……

Route107_Text_DarrinPostBattle:
	.string "바다 위에 떠서 파도에 몸을 맡기면\n"
	.string "푹신푹신한 침대에 누워 있는 느낌이야!$"
	// うみに うかんで なみに ゆられてるとｎ
	// ふかふかの ベッドで ねてる みたいだよ!

Route107_Text_TonyIntro:
	.string "바다는 내 구역이나 마찬가지다!\n"
	.string "승부하자!$"
	// うみは オレの にわ みたいな もの!ｎ
	// しょうぶ しようぜ!

Route107_Text_TonyDefeated:
	.string "홈그라운드에서 졌어...\n"
	.string "쇼크다!$"
	// ホ-ムグラウンドで まけた……ｎ
	// ショック!

Route107_Text_TonyPostBattle:
	.string "커다란 꿈을 가득 채우고-\n"
	.string "드넓은 바다를 한번 헤엄치지-\p"
	.string "자자 계속 헤엄칠 거다-!$"
	// おおきな ユメを いっぱい つめて-ｎ
	// でっかい うみを ひとおよぎ-ｐ
	// さぁて まだまだ およぐぞ-!

Route107_Text_TonyRegister:
	.string "쇼크를 받은 나를\n"
	.string "네가 잊지 못하도록...!$"
	// ショックを うけたオレをｎ
	// きみが わすれない ために……!

Route107_Text_TonyRematchIntro:
	.string "드넓은 바다를 헤엄치고 있었더니\n"
	.string "포켓몬이 엄청 강해졌다고-!$"
	// でっかい うみを およいでいたらｎ
	// ポケモンが すっごく つよくなったぞ-!

Route107_Text_TonyRematchDefeated:
	.string "쇼크다!!\p"
	.string "포켓몬은 강해졌지만\n"
	.string "트레이너인 난 약한 그대로인 건가!?$"
	// ショック!!ｐ
	// ポケモンは つよくなったがｎ
	// トレ-ナ-の おれが よわいまま!?

Route107_Text_TonyRematchPostBattle:
	.string "배틀 속에서 익힌 것들이\n"
	.string "트레이너로서의 강함으로 이어진다!\l"
	.string "드넓은 바다가 그렇게 말했다고-!$"
	// たたかいの なかで おぼえたことがｎ
	// トレ-ナ-としての つよさに つながる!ｌ
	// でっかい うみが そう いっていたぞ-!

Route107_Text_DeniseIntro:
	.string "무로마을이라는\n"
	.string "작은 마을을 알고 있니?$"
	// ムロタウン っていうｎ
	// ちいさな まちを しってる?

Route107_Text_DeniseDefeated:
	.string "아 정말 이게 뭐야-!$"
	// ヤダ も-っ!

Route107_Text_DenisePostBattle:
	.string "무로마을에 있는 집회소에서\n"
	.string "이상한 말이 유행하고 있어!$"
	// ムロタウンの しゅうかいじょでｎ
	// ふしぎな ことばが はやって いるのよ!

Route107_Text_BethIntro:
	.string "나랑 승부하고 싶은 거야?\n"
	.string "좋아! 상대해 줄게!$"
	// わたしと しょうぶが したいの?ｎ
	// いいわ! あいてに なって あげる!

Route107_Text_BethDefeated:
	.string "난 상대가 안 되는구나!$"
	// わたしじゃ あいてに ならなかったわ!

Route107_Text_BethPostBattle:
	.string "넌 앞으로도 계속 강해질 것 같아\n"
	.string "나도 열심히 해야지!$"
	// あなた まだまだ つよく なりそうねｎ
	// わたしも がんばろうっと!

Route107_Text_LisaIntro:
	.string "유미: 우리 남매 둘이서\n"
	.string "승부해 줄게!$"
	// ユミ『あたしたち きょうだい ふたりでｎ
	// しょうぶを させてもらうわ!

Route107_Text_LisaDefeated:
	.string "유미: 굉장해\n"
	.string "강함의 레벨이 달라$"
	// ユミ『すごいわｎ
	// つよさの レベルが ちがうのね

Route107_Text_LisaPostBattle:
	.string "유미: 넌 같이\n"
	.string "바다로 놀러갈 만한\l"
	.string "친구가 있니?$"
	// ユミ『あなたは いっしょにｎ
	// うみに あそびに いくようなｌ
	// おともだち いるのかしら?

Route107_Text_LisaNotEnoughPokemon:
	.string "유미: 우리랑 승부할 거면\n"
	.string "포켓몬을 더 데려오라고$"
	// ユミ『アタシたちと たたかうならｎ
	// ポケモン もっと つれてきなさいな

Route107_Text_RayIntro:
	.string "빈: 항상 둘이서\n"
	.string "포켓몬 승부를 하고 있어!\p"
	.string "...항상 내가 지고 있지만\n"
	.string "2대 2라면 널 이길 수 있어!$"
	// シン『いつも きょうだいでｎ
	// ポケモンしょうぶ してるんだ!ｐ
	// ……いっつも おれが まけるけどｎ
	// 2たい2なら きみに かてるよ!

Route107_Text_RayDefeated:
	.string "빈: 으아-\n"
	.string "강함의 레벨이 달라도 너무 다르다$"
	// シン『ひゃ-ｎ
	// つよさの レベルが ちがいすぎるや

Route107_Text_RayPostBattle:
	.string "빈: 내 포켓몬\n"
	.string "누나한테 받아서 키운\l"
	.string "나의 소중한 파트너야!$"
	// シン『おれの ポケモンｎ
	// ねえちゃんから もらって そだてたｌ
	// だいじな あいぼう なんだぜ!

Route107_Text_RayNotEnoughPokemon:
	.string "빈: 우리랑 배틀하고 싶으면\n"
	.string "더 포켓몬을 데려와!$"
	// シン『オレらと たたかうならｎ
	// もっと ポケモン つれてきてよ!

Route107_Text_CamronIntro:
	.string "트라이애슬론을 하는 도중이지만\n"
	.string "전혀 지치지 않았다구!$"
	// トライアスロンの とちゅう だがｎ
	// ぜんぜん つかれて いないぜ!

Route107_Text_CamronDefeated:
	.string "지금 배틀로 지쳤어$"
	// いまので つかれて しまった

Route107_Text_CamronPostBattle:
	.string "이 이거 뒤에 아직\n"
	.string "수영이랑 달리기가 남았는데\p"
	.string "괜찮겠지 나...?$"
	// こ このあと まだｎ
	// すいえい ランニングが のこっているぜｌ
	// だいじょうぶか おれ……?

Route108_Text_JeromeIntro:
	.string "내 꿈은 전 세계에 있는\n"
	.string "7곳의 바다를 모두 헤엄치는 거야!$"
	// オレの ユメは せかいに あるｎ
	// 7つのうみ すべてで およぐこと!

Route108_Text_JeromeDefeated:
	.string "이래서는\n"
	.string "7곳의 바다를 모두 헤엄칠 수 없어...$"
	// これじゃｎ
	// 7つのうみ すべてで およげない……

Route108_Text_JeromePostBattle:
	.string "바다 포켓몬과 노는 것도\n"
	.string "헤엄치고 있을 때의 즐거움 중 하나야!$"
	// うみの ポケモンと あそぶこともｎ
	// およいでいる ときの たのしみだね!

Route108_Text_MatthewIntro:
	.string "이봐 너!\n"
	.string "너도 버려진 배에 가는 거야?$"
	// なあ キミ!ｎ
	// キミも すてられた ふねに いくのかい?

Route108_Text_MatthewDefeated:
	.string "아아 내가 가라앉는다...\n"
	.string "꼬륵꼬륵...$"
	// ああ ぼくが しずむ……ｎ
	// ぶくぶく……

Route108_Text_MatthewPostBattle:
	.string "버려진 배 안으로\n"
	.string "들어가는 사람들도 있어!$"
	// すてられぶねの なかにｎ
	// はいっていく やつらが いるんだよ!

Route108_Text_TaraIntro:
	.string "거짓말쟁이 남자친구가 말했어\n"
	.string "비키니가 잘 어울려서 귀엽다고...$"
	// ウソつきな カレに いわれたのよｎ
	// ビキニが にあってて カワイイって……

Route108_Text_TaraDefeated:
	.string "싫다 져버렸어-!$"
	// いやん まけたわ-っ!

Route108_Text_TaraPostBattle:
	.string "거짓말이라도 귀엽다는 말을 듣고 싶은\n"
	.string "복잡한 여자의 마음...$"
	// ウソでも いいから カワイイって いわれたいｎ
	// ふくざつな おんなごころ……

Route108_Text_MissyIntro:
	.string "바다가 너무 좋아!\n"
	.string "헤엄치고 있으면\l"
	.string "슬픈 일들을 잊어버릴 수 있어!$"
	// うみって だいすき!ｎ
	// およいでいれば イヤなことも わすれるわ!

Route108_Text_MissyDefeated:
	.string "승부에서 지면\n"
	.string "스트레스가 쌓여-!$"
	// しょうぶに まけるとｎ
	// ストレスが たまる-っ!

Route108_Text_MissyPostBattle:
	.string "스트레스는 수영으로 발산할 거야!\n"
	.string "건강에도 최고지-!$"
	// ストレスは およいで はっさん!ｎ
	// けんこうてき よね-!

Route108_Text_CoryIntro:
	.string "물타입 포켓몬이 좋다-!\n"
	.string "다른 포켓몬도 좋다-!$"
	// みずポケモンが だいすきだ-!ｎ
	// ほかの ポケモンも だいすきだ-!

Route108_Text_CoryDefeated:
	.string "와-! 졌다-!\n"
	.string "와- 와-!$"
	// わ- まけた-!ｎ
	// わ-わ-!

Route108_Text_CoryPostBattle:
	.string "큰소리로 외치니\n"
	.string "시원하다-앗!$"
	// おおごえで さけべばｎ
	// スッキリ するなあ-っ!

Route108_Text_CoryRegister:
	.string "강한 트레이너도 좋다-!\n"
	.string "포켓내비에 등록해 줘-!$"
	// つよい トレ-ナ-も だいすきだ-!ｎ
	// ポケナビの とうろくを してくれ-!

Route108_Text_CoryRematchIntro:
	.string "이기든 지든\n"
	.string "바다에서 승부하는 게 좋다-!$"
	// かっても まけてもｎ
	// うみ での しょうぶが だいすきだ-!

Route108_Text_CoryRematchDefeated:
	.string "와-악 또 졌군!\n"
	.string "와- 와-!$"
	// わ-っ また まけた!ｎ
	// わ- わ-!

Route108_Text_CoryRematchPostBattle:
	.string "너도 고난에 부딪쳤다면\n"
	.string "바다를 향해 소리쳐봐라-앗!$"
	// きみも いきづまった ときはｎ
	// なにかを うみに むかって さけべ-っ!

Route108_Text_CarolinaIntro:
	.string "자랑스러운 포켓몬들로\n"
	.string "스피디한 배틀을 보여주지!$"
	// じまんの ポケモンたちでｎ
	// スピ-ディに たたかうわよ!

Route108_Text_CarolinaDefeated:
	.string "어머 센스 없기는!$"
	// あら かわいくないわね!

Route108_Text_CarolinaPostBattle:
	.string "이렇게 바다에 있으니까\n"
	.string "핑크색 탱탱한 비키니도\l"
	.string "살짝 입어보고 싶어졌어...$"
	// せっかくの うみ だしｎ
	// ピンクの フリフリの ビキニもｌ
	// ちょっと きてみたい……

Route109_Text_DavidIntro:
	.string "흐아아압-!!\n"
	.string "멋지게 갈라진 복근을 봐랏-!!$"
	// うりゃ-っ!!ｎ
	// みごとに われた ふっきんを みろ-っ!!

Route109_Text_DavidDefeated:
	.string "흐아아압-!!\n"
	.string "져버렸다-!!$"
	// うりゃ-っ!!ｎ
	// まけた-っ!!

Route109_Text_DavidPostBattle:
	.string "흐아아압-!!\p"
	.string "복근과 포켓몬 승부는\n"
	.string "아무런 상관이 없다앗-!!$"
	// うりゃ-っ!!ｐ
	// ふっきんと ポケモンの しょうぶはｎ
	// かんけい ないぞ-っ!!

Route109_Text_AliceIntro:
	.string "자외선 차단\n"
	.string "잘 하고 있니?$"
	// ひやけ たいさくｎ
	// あなたは してる?

Route109_Text_AliceDefeated:
	.string "앗뜨뜨뜨뜨거워!$"
	// あちちちちっ!

Route109_Text_AlicePostBattle:
	.string "볼 주변이 제일\n"
	.string "타기 쉬워!$"
	// ほっぺの あたりが いちばんｎ
	// ひやけ しやすい ばしょ なのよ!

Route109_Text_HueyIntro:
	.string "전 세계의 항구를 찾아가 봤지만\n"
	.string "잿빛도시는 최고의 항구도시다!$"
	// せかいじゅうの みなとを おとずれたがｎ
	// カイナは さいこ-の みなとまち だぜ!

Route109_Text_HueyDefeated:
	.string "너도 최고로군...$"
	// あんた さいこ- だぜ……

Route109_Text_HueyPostBattle:
	.string "최고의 항구에는\n"
	.string "최고의 트레이너가 있었어...$"
	// さいこ-の みなとまちにはｎ
	// さいこ-の トレ-ナ-が いたぜ……

Route109_Text_EdmondIntro:
	.string "으으으...\n"
	.string "지금 승부하려고? 나랑?$"
	// ううう……ｎ
	// しょうぶ するの? オレと?

Route109_Text_EdmondDefeated:
	.string "우웨에에엑...$"
	// げろげろ……

Route109_Text_EdmondPostBattle:
	.string "평소엔 좀 더 강하다고!\n"
	.string "뱃멀미 때문에 상태가 안 좋은 것뿐이야!\p"
	.string "선원이긴 하지만...$"
	// いつもは もっと つよいんだぞ!ｎ
	// ふなよいで ちょうしが わるいだけだ!ｐ
	// ふなのり だけど……

Route109_Text_RickyIntro:
	.string "목마르다...\n"
	.string "바다의 집에서\l"
	.string "미네랄사이다를 마시고 싶어...$"
	// のどが かわいたよ……ｎ
	// うみのいえで サイコソ-ダ のみたいな……

Route109_Text_RickyDefeated:
	.string "으-으...$"
	// う-ん……

Route109_Text_RickyPostBattle:
	.string "배도 고파오기 시작했어...\n"
	.string "튜브가 커다란 도넛으로 보여$"
	// おなかも へってきた……ｎ
	// うきわが おっきな ド-ナッツに みえるよ

Route109_Text_RickyRegister:
	.string "다음에 배고프지 않을 때\n"
	.string "한 번 더 승부하지 않을래?$"
	// こんど のどが かわいて ないときにｎ
	// もういっかい しょうぶ してくれる?

Route109_Text_RickyRematchIntro:
	.string "배는 고프지만\n"
	.string "승부하면 괜찮아지겠지!$"
	// おなか へってるけどｎ
	// しょうぶ するなら げんき だよ!

Route109_Text_RickyRematchDefeated:
	.string "졌다...\n"
	.string "배가 고파서 그래$"
	// まけた……ｎ
	// おなかが へってるからだ

Route109_Text_RickyRematchPostBattle:
	.string "백사장에서 먹으면\n"
	.string "뭐든지 맛있게 느껴져$"
	// すなはまで たべるとｎ
	// なんでも おいしく おもえるよね

Route109_Text_LolaIntro:
	.string "비치파라솔은\n"
	.string "커다란 꽃 같지-!$"
	// ビ-チパラソルってｎ
	// おおきな おはな みたいよね-!

Route109_Text_LolaDefeated:
	.string "엄마아-!$"
	// ママ-っ!

Route109_Text_LolaPostBattle:
	.string "하늘에서 모래 해변을 보면\n"
	.string "꽃밭처럼 보여!$"
	// おそらの うえから すなはまを みたらｎ
	// おはなばたけ みたいに みえるのよ!

Route109_Text_LolaRegister:
	.string "난\n"
	.string "매일 여기 있어!$"
	// わたし だったらｎ
	// まいにち ここに きているよ!

Route109_Text_LolaRematchIntro:
	.string "이제 너한테 안 질 거야!\n"
	.string "이기려고 튜브도 끼고 있거든!$"
	// もう あなたには まけません!ｎ
	// そのために うきわ してるんだから!

Route109_Text_LolaRematchDefeated:
	.string "엄마아-!$"
	// ママ-っ!

Route109_Text_LolaRematchPostBattle:
	.string "튜브를 가지고 있으면 포켓몬의\n"
	.string "귀여움이 뾰롱 하고 올라가!$"
	// うきわ もってると あたしと ポケモンのｎ
	// かわいさが ぐぐ-んと アップするの!

Route109_Text_AustinaIntro:
	.string "튜브가 없으면 헤엄칠 수 없지만\n"
	.string "포켓몬 승부라면 누구한테도 안 져!$"
	// うきわが ないと およげないけどｎ
	// ポケモンなら だれにも まけないよ!

Route109_Text_AustinaDefeated:
	.string "튜브가 있어서 진 걸까?$"
	// うきわが あるから まけちゃったのかな?

Route109_Text_AustinaPostBattle:
	.string "내 튜브는\n"
	.string "패션이라서 놓을 수가 없어$"
	// あたしの うきわｎ
	// オシャレだから てばなせないの

Route109_Text_GwenIntro:
	.string "거기 트레이너님!\n"
	.string "저랑 승부해 쥬세여!$"
	// そこの トレ-ナ-さんｎ
	// あたしと たたかう でちゅ!

Route109_Text_GwenDefeated:
	.string "너무 강했쪄여...$"
	// つよいでちゅね……

Route109_Text_GwenPostBattle:
	.string "어떻게 하면 그렇게\n"
	.string "강해질 쭈 있나여...?$"
	// どうしたら そんなにｎ
	// つよくなれる でちゅか……?

Route109_Text_CarterIntro:
	.string "으하하!\n"
	.string "아저씨가 월척을 낚는 걸 보라고!$"
	// わはは!ｎ
	// おじさん おおもの つっちゃうぞ!

Route109_Text_CarterDefeated:
	.string "아저씨가 지는 건 보지 마...$"
	// おじさん まけちゃったな……

Route109_Text_CarterPostBattle:
	.string "확실히 넌 진짜 월척이구나!\n"
	.string "분명 거물이 될 거야!$"
	// たしかに きみは おおもの だな!ｎ
	// いや きっと おおものに なるぞ!

Route109_Text_PaulIntro:
	.string "리키: 이야 이걸 어쩌지?\p"
	.string "둘만의 시간을\n"
	.string "방해받고 싶지 않았는데 말이야$"
	// リキ『やあ こまったなあｐ
	// ふたりっきりの じかんｎ
	// じゃま して ほしくないなあ

Route109_Text_PaulDefeated:
	.string "리키: 이야 이걸 어쩌지...$"
	// リキ『やあ まいったな……

Route109_Text_PaulPostBattle:
	.string "리키: 저기 우리가 여기 있다고\n"
	.string "아무한테도 말하지 말아줘!\l"
	.string "여긴 우리 둘만의 세계니까!$"
	// リキ『やあ ぼくたちが ここに いることｎ
	// だれにも いわないで くれよ!ｌ
	// ふたりっきりの せかい なんだからさ!

Route109_Text_PaulNotEnoughPokemon:
	.string "리키: 우리들은 러브러브니까\n"
	.string "우리들의 포켓몬도\l"
	.string "2마리가 같이 배틀하게 할 거야!$"
	// リキ『ぼくたち ラブラブ だからねｎ
	// ぼくたちの ポケモンもｌ
	// 2ひき いっしょに たたかわせるんだ!

Route109_Text_MelIntro:
	.string "지목: 우리들이 러브러브니까\n"
	.string "호연지방이 뜨거운 거야앙-!$"
	// シキ『あたしたちが ラブラブだからｎ
	// ホウエンは あっついのよお!

Route109_Text_MelDefeated:
	.string "지목: 나 때문에 졌어...\n"
	.string "이러다간 리키한테 미움받게 될 거야!$"
	// シキ『あたしの せいで まけたんだわ……ｎ
	// こんなんじゃ リキに きらわれちゃう!

Route109_Text_MelPostBattle:
	.string "지목: 저기 리키\n"
	.string "나한테 화났어?\l"
	.string "화내지 마 싫어-$"
	// シキ『ねえ リキｎ
	// あたしのこと おこってない?ｌ
	// おこっちゃ いやよ

Route109_Text_MelNotEnoughPokemon:
	.string "지목: 우리들은 러브러브니까\n"
	.string "우리들의 포켓몬도\l"
	.string "2마리가 같이 배틀하게 할 거야!$"
	// シキ『あたしたち ラブラブ だからねｎ
	// あたしたちの ポケモンもｌ
	// 2ひき いっしょに たたかわせるんだ!

Route109_Text_ChandlerIntro:
	.string "짜잔-!\n"
	.string "내 튜브는 둥글다고-!$"
	// じゃ-ん!ｎ
	// ボクの うきわ まるいでしょ-っ!

Route109_Text_ChandlerDefeated:
	.string "아-아! 유감이야!$"
	// あ-あ! ざんねん

Route109_Text_ChandlerPostBattle:
	.string "모처럼 내 둥근 튜브를\n"
	.string "보여줬는데 너무해$"
	// せっかく まるい うきわをｎ
	// みせて あげたのにさ

Route109_Text_HaileyIntro:
	.string "수영을 못해서\n"
	.string "하는 시늉만 내고 있어!$"
	// およげない からｎ
	// およぐ ふりを してるの!

Route109_Text_HaileyDefeated:
	.string "그럼 그렇지!\n"
	.string "못 이길 거라 생각했어$"
	// やっぱね!ｎ
	// かてないって おもってたんだ

Route109_Text_HaileyPostBattle:
	.string "수영을 다 배웠을 때는\n"
	.string "포켓몬도 강해져 있을 거라 생각해!$"
	// およげるように なったらｎ
	// ポケモンも つよく なると おもう!

Route109_Text_ElijahIntro:
	.string "마초맨 같은 나에겐\n"
	.string "이 포켓몬이 딱 맞아!$"
	// こうはの おれさまにはｎ
	// こんな ポケモンが おにあいだぜ!

Route109_Text_ElijahDefeated:
	.string "패배해도 멋지지 않아?$"
	// まけても カッコ いいだろ?

Route109_Text_ElijahPostBattle:
	.string "마초맨 같은 나에게\n"
	.string "항구도시는 완벽한 장소야!\p"
	.string "잿빛도시로 가야겠어$"
	// こうはの おれさまにはｎ
	// みなとまちが おにあいだぜ!ｌ
	// カイナシティに いってくるか

Route110_Text_JacobIntro:
	.string "어이쿠 위험했다!\n"
	.string "자전거 레이스에 익숙하지 않은 모양이군!$"
	// おっと あぶない!ｎ
	// バイク レ-スに なれてない ようだな!

Route110_Text_JacobDefeated:
	.string "끼익-!\n"
	.string "브레이크가 고장 났다!$"
	// キキ-ッ!ｎ
	// ブレ-キが こしょうした!

Route110_Text_JacobPostBattle:
	.string "타이어 펑크나\n"
	.string "브레이크 고장은 부상의 원인이야\l"
	.string "꼼꼼하게 점검해야 돼$"
	// タイヤの パンクやｎ
	// ブレ-キの こしょうは ケガのもとｌ
	// ちゃんと てんけん しないとな

Route110_Text_AnthonyIntro:
	.string "헤이 유-!\n"
	.string "내 스피드를 따라잡을 수 있을까!?$"
	// ヘイ ユ-!ｎ
	// ワタシの スピ-ドに ついてこれるかな!?

Route110_Text_AnthonyDefeated:
	.string "오 마이 갓-!$"
	// オ- マイ ガッ!

Route110_Text_AnthonyPostBattle:
	.string "스피드만으론 포켓몬 승부\n"
	.string "이길 수 없습니다-! 반성하겠습니다-!$"
	// スピ-ドだけじゃ ポケモンしょうぶｎ
	// かてませ-ん! ハンセイしま-す!

Route110_Text_BenjaminIntro:
	.string "자전거 스피드가 빨라져도\n"
	.string "서두르면 안 돼!$"
	// じてんしゃの スピ-ド でてもｎ
	// あせっちゃ いけないよ!

Route110_Text_BenjaminDefeated:
	.string "포켓몬 승부도\n"
	.string "서두르면 안 돼...$"
	// ポケモンしょうぶもｎ
	// あせっちゃ いけないな……

Route110_Text_BenjaminPostBattle:
	.string "서두르지 말고 여유를 가지자\n"
	.string "시간은 충분하니까!$"
	// あせらず のんびり いこうよｎ
	// じかんは たっぷり あるからね!

Route110_Text_BenjaminRegister:
	.string "서두르지 말고 힘내야지!\n"
	.string "괜찮다면 연락해줘$"
	// あせらずに また がんばるか!ｎ
	// よかったらさ れんらく くれよな

Route110_Text_BenjaminRematchIntro:
	.string "오! 스피드가 너무 빠른데?\n"
	.string "잠깐 느긋하게 승부하자고!$"
	// おっ! スピ-ド だしすぎ じゃない?ｎ
	// ちょっと のんびり しょうぶ しようよ!

Route110_Text_BenjaminRematchDefeated:
	.string "별로 서두르지도 않았는데\n"
	.string "어째선지 자꾸 져버리네...$"
	// べつに あせってないけどｎ
	// なぜだか まけて しまうな……

Route110_Text_BenjaminRematchPostBattle:
	.string "서두르지 말고 여유를 가지자\n"
	.string "시간은 충분하니까!$"
	// あせらず のんびり いこうよｎ
	// じかんは たっぷり あるからね!

Route110_Text_AbigailIntro:
	.string "트라이애슬론은 하드한 스포츠\n"
	.string "수영 자전거 마라톤\l"
	.string "3종목을 소화하는 운동이야!$"
	// トライアスロンは ハ-ドな スポ-ツｎ
	// すいえい じてんしゃ マラソンのｌ
	// 3しゅもくを こなすのよ!

Route110_Text_AbigailDefeated:
	.string "포켓몬 승부도 하드하네!$"
	// ポケモン しょうぶも ハ-ドだわ!

Route110_Text_AbigailPostBattle:
	.string "지쳤으니까 한숨 돌려야겠어\n"
	.string "휴식은 중요하다고$"
	// つかれたから ひとやすみｎ
	// きゅうけいは たいせつ なのよ

Route110_Text_AbigailRegister:
	.string "너 마음에 들었어!\n"
	.string "또 사이클링 로드에서 승부하자$"
	// あなた きにいったわ!ｎ
	// また サイクリングロ-ドで たたかいましょ

Route110_Text_AbigailRematchIntro:
	.string "자전거 타면서\n"
	.string "포켓몬 승부하는 것도 좋네!$"
	// じてんしゃに のりながらｎ
	// ポケモンしょうぶ ってのも いいものよね!

Route110_Text_AbigailRematchDefeated:
	.string "우와-\n"
	.string "어째서 그렇게 강한 거야?$"
	// うわ-ｎ
	// どうして そんなに つよいの?

Route110_Text_AbigailRematchPostBattle:
	.string "혹시 기록에\n"
	.string "도전하고 있었던 거야?\p"
	.string "그렇다면 방해해서 미안해-$"
	// ひょっとして きろくにｎ
	// ちょうせん していたのかしら?ｐ
	// だったら ジャマして ゴメンね-

Route110_Text_JasmineIntro:
	.string "자전거를 계속 밟아서\n"
	.string "허벅지가 딴딴해졌어$"
	// じてんしゃを こぎつづけてｎ
	// ふとももが パンパンに なっちゃった

Route110_Text_JasmineDefeated:
	.string "근육이 걱정이야...$"
	// きんにくつうが しんぱいだわ……

Route110_Text_JasminePostBattle:
	.string "체육관 배지를 가지고 있어?\n"
	.string "강한 게 당연한 거였네!$"
	// ジムの バッチを もってるの?ｎ
	// どうりで つよい はずだわ!

Route110_Text_EdwardIntro:
	.string "너의 작전은 전부 간파했다!\n"
	.string "내가 질 리가 없어!$"
	// おまえの さくせんは すべて みえた!ｎ
	// わたしが まけるはず ない!

Route110_Text_EdwardDefeated:
	.string "자신의 패배는 간파하지 못했나...!$"
	// じぶんの はいぼくは みえなかった……!

Route110_Text_EdwardPostBattle:
	.string "너의 미래를 간파했다...\p"
	.string "흐으음...\n"
	.string "아주 밝은 빛이 보이는군...!$"
	// おまえの みらいが みえる……ｐ
	// ふうむ……ｎ
	// あかるい ひかりが みえるぞ……!

Route110_Text_JaclynIntro:
	.string "오호호호홋!\n"
	.string "저의 미라클을 보여드리죠!$"
	// おほほほほっ!ｎ
	// わたくしの ミラクルを みせてあげるわ!

Route110_Text_JaclynDefeated:
	.string "미라클하게 졌다-앗!$"
	// ミラクルに まけた-っ!

Route110_Text_JaclynPostBattle:
	.string "저에게 이긴 것이 미라클...\n"
	.string "그래요 기적이라구요!\l"
	.string "언제나 이긴다고 생각하지 마세요!$"
	// わたくしに かったことが ミラクル……ｎ
	// そう きせき なのよ!ｌ
	// いつでも かてるなんて おもわないことね!

Route110_Text_EdwinIntro:
	.string "네 포켓몬을 보여주지 않을래?\n"
	.string "살짝 보기만 할 테니까 제발!$"
	// キミの ポケモン みせてくれない?ｎ
	// ひとめで いいから おねがい!

Route110_Text_EdwinDefeated:
	.string "도감을 완성하고 싶었는데...!$"
	// コンプリ-ト したかった……!

Route110_Text_EdwinPostBattle:
	.string "처음 보는 포켓몬을 만나면\n"
	.string "내 수집욕이 불타오르지!$"
	// みたことのない ポケモンに であうとｎ
	// ボクの コレクタ-だましいが もえるなぁ!

Route110_Text_EdwinRegister:
	.string "난 엔트리콜에 사람들을\n"
	.string "모으는 것도 좋아해!$"
	// ぼく エントリ-コ-ルもｎ
	// たくさん あつめたいんだよねぇ

Route110_Text_EdwinRematchIntro:
	.string "저기 있잖아\n"
	.string "새로운 포켓몬은 잡았니?\p"
	.string "괜찮다면 포켓몬을 보여주지 않을래?\n"
	.string "살짝 보기만 할 테니까 제발!$"
	// ねえ キミｎ
	// あたらしい ポケモン つかまえた?ｐ
	// よかったら ポケモン みせてくれない?ｎ
	// ひとめで いいから おねがい!

Route110_Text_EdwinRematchDefeated:
	.string "네 포켓몬\n"
	.string "부럽다...$"
	// キミの ポケモンｎ
	// うらやましいな……

Route110_Text_EdwinRematchPostBattle:
	.string "아-! 희귀한 포켓몬은\n"
	.string "무조건 몽땅 다 내 손에 넣고 싶어-!$"
	// ああ! とにかく めずらしい ポケモンｎ
	// ぜんぶ ボクの ものに したいよ-!

Route110_Text_DaleIntro:
	.string "에-잇!\n"
	.string "뒤에서 말 걸지 말라고-!$"
	// ええ-い!ｎ
	// うしろから はなしかけるな-!

Route110_Text_DaleDefeated:
	.string "졌닷!\n"
	.string "분하닷!!$"
	// まけたっ!ｎ
	// くやしいっ!!

Route110_Text_DalePostBattle:
	.string "수면에 뜬 낚시찌를 바라본다...\n"
	.string "집중력이 중요해$"
	// すいめんに うかぶ うきを じっと みる……ｎ
	// しゅうちゅうりょくが たいせつ なんだ

Route110_Text_IsabelIntro:
	.string "오호홋! 소중한 포켓몬을\n"
	.string "자랑하기 위해서라면 어디든 갈 수 있어요$"
	// おほほ! だいじな ポケモンをｎ
	// じまん するためなら どこにでも いきますわ

Route110_Text_IsabelDefeated:
	.string "어머 왜 이러니 싫다-$"
	// あら まあ イヤですわ

Route110_Text_IsabelPostBattle:
	.string "승부시키지 말고\n"
	.string "애호가클럽에서 자랑이나 할까?$"
	// しょうぶ させるよりもｎ
	// だいすきクラブで じまんして こようかしら

Route110_Text_IsabelRegister:
	.string "제 자랑은 이런 걸로\n"
	.string "끝나지 않아요!\l"
	.string "몇 번이고 어울려 주셔야겠어요!$"
	// わたしの じまんは こんなんじゃｎ
	// おわりませんわ!ｌ
	// なんかいも つきあって もらいますわよ!

Route110_Text_IsabelRematchIntro:
	.string "오호홋! 소중한 포켓몬이라면\n"
	.string "몇 번이든 계속 자랑하겠어요!$"
	// おほほ! だいじな ポケモンならｎ
	// なんどだって じまん しますわ!

Route110_Text_IsabelRematchDefeated:
	.string "어머 왜 이러니 싫다-$"
	// あら まあ イヤですわ

Route110_Text_IsabelRematchPostBattle:
	.string "포켓몬 자랑도 좋지만\n"
	.string "승부하는 것도 좋아해요!$"
	// ポケモンじまんも やめられないけどｎ
	// しょうぶ するのも すきなのよ!

Route110_Text_TimmyIntro:
	.string "이 주변 풀숲에서\n"
	.string "멋있는 포켓몬을 발견했어!$"
	// この あたりの くさむらでｎ
	// かっこいい ポケモン みつけたんだぜ!

Route110_Text_TimmyDefeated:
	.string "멋있기만 하면 안 되는 건가...$"
	// かっこいい だけじゃ だめかぁ……

Route110_Text_TimmyPostBattle:
	.string "방금 막 잡은 포켓몬으론\n"
	.string "배틀을 잘 할 수 없어!$"
	// つかまえた ばかりの ポケモンじゃｎ
	// うまく たたかえないや!

Route110_Text_AlyssaIntro:
	.string "사이클링 로드에서 떨어졌다!\n"
	.string "창피해... 승부로 마음을 달래야겠어!$"
	// サイクリングロ-ド から おちちゃった!ｎ
	// はずかしい…… しょうぶで まぎらわすわ!

Route110_Text_AlyssaDefeated:
	.string "히잉 지고 말았다!$"
	// ひぇ まけて しまったわ!

Route110_Text_AlyssaPostBattle:
	.string "떨어지고 지고\n"
	.string "너무 꼴사납잖아 나!$"
	// おっこちるは まけるはでｎ
	// はずかし すぎます! わたし!

Route110_Text_JosephIntro:
	.string "좋았어 달려보실까!\n"
	.string "안 따라오는 겁쟁이는 두고 간다!$"
	// よぉぉし とばして いくぜえェ!ｎ
	// ノリの わるいやつは おいてくぜェ!

Route110_Text_JosephDefeated:
	.string "잘 따라오네 너...$"
	// ノリが いいね あんた……

Route110_Text_JosephPostBattle:
	.string "이런 일론 기 안 죽어!\n"
	.string "난 패배함으로써 한 단계 더\l"
	.string "좋은 사나이가 된 거라고!$"
	// こんなこと では へこたれないぜェ!ｎ
	// おれは まけて またひとつｌ
	// いいオトコに なったぜェ!

Route110_Text_KalebIntro:
	.string "귀여운 포켓몬들이\n"
	.string "서로 돕는 모습은 너무 귀여워-!$"
	// かわいい ポケモンたちがｎ
	// たすけあう ところは かわいいぞ--っ!

Route110_Text_KalebDefeated:
	.string "너는 피도 눈물도 없구나$"
	// きみは ちも なみだも ないんだな

Route110_Text_KalebPostBattle:
	.string "그래 착하지 착하지\n"
	.string "잘했어 귀염둥이들$"
	// おう よしよしｎ
	// よくやったよ かわいい おまえたち

Route111_Text_DrewIntro:
	.string "오! 고고고글 잘 어울리네!\n"
	.string "하지만 내 쪽이 더 잘 어울리지?\l"
	.string "누가 더 잘 어울리는지 승부다!$"
	// おっ! ゴ-ゴ-ゴ-グル にあってるね!ｎ
	// でも ぼくの ほうが にあってるだろ?ｌ
	// どっちが にあうか しょうぶだよ!

Route111_Text_DrewDefeat:
	.string "고고고글 때문에 주변이\n"
	.string "잘 안 보였어$"
	// ゴ-ゴ-ゴ-グルで まわりがｎ
	// よく わからなかったよ

Route111_Text_DrewPostBattle:
	.string "고고고글이 있으면\n"
	.string "사막의 모래바람도 괜찮으니까\l"
	.string "그것만으로도 기뻐지지!$"
	// ゴ-ゴ-ゴ-グルが あるとｎ
	// さばくの すなあらしも へいき だからｌ
	// それだけで うれしくなるよ!

Route111_Text_HeidiIntro:
	.string "사막 한가운데에서도 피크닉!\p"
	.string "어떤 곳이라도 트레이너가 있으니까\n"
	.string "승부도 할 수 있어!$"
	// さばくの なかでも ピクニック!ｐ
	// どんな ところでも トレ-ナ- いるからｎ
	// しょうぶも できるもんね!

Route111_Text_HeidiDefeat:
	.string "아야-앙! 짓궂어-!$"
	// いや-ん いじわる-!

Route111_Text_HeidiPostBattle:
	.string "모래바람 속에서 배틀할 때는\n"
	.string "포켓몬의 체력을 신경 쓰지 않으면\l"
	.string "금방 기절하고 말 거야!$"
	// すなあらしの なかで たたかうならｎ
	// ポケモンの たいりょくに きを つけないとｌ
	// すぐに きぜつ しちゃうわよ!

Route111_Text_BeauIntro:
	.string "고고고글을 쓰고 있으면\n"
	.string "왠지 히어로가 된 기분이야!\l"
	.string "지금의 나라면 누구든 이길 수 있어!$"
	// ゴ-ゴ-ゴ-グルを つけてるとｎ
	// なんとなく ヒ-ロ-きぶん!ｌ
	// いまの ぼくなら だれにだって かてるさ!

Route111_Text_BeauDefeat:
	.string "기분만으로는 이길 수 없는 건가...$"
	// きぶん だけじゃ かてないか……

Route111_Text_BeauPostBattle:
	.string "언젠가는 진짜 히어로가 될 거야!\n"
	.string "그러려면 좀 더 힘내서\l"
	.string "포켓몬과 스스로를 단련해야겠지$"
	// いつかは ほんものの ヒ-ロ-に なる!ｎ
	// そのために もっと がんばってｌ
	// ポケモンと じぶんを きたえてみせるよ

Route111_Text_BeckyIntro:
	.string "사막에서 화석이 발견됐다고 들었는데\n"
	.string "어디에 있는 걸까?$"
	// さばくで カセキが みつかるって きいたけどｎ
	// どこに あるのかなあ?

Route111_Text_BeckyDefeat:
	.string "아직 부족해...$"
	// いまいち だわ……

Route111_Text_BeckyPostBattle:
	.string "사막에서 화석이 발견됐다는 건\n"
	.string "옛날에 여기가 바다였다는 거겠지!$"
	// さばくで カセキが みつかると いうことはｎ
	// むかし ここは うみ だったのね!

Route111_Text_DustyIntro:
	.string "유적 찾아 30년!\n"
	.string "그런 이 몸과 배틀하겠다고?$"
	// いせきを さがして 30ねん!ｎ
	// そんな わたしと たたかうのかね?

Route111_Text_DustyDefeat:
	.string "유적은 찾고 있었지만\n"
	.string "강한 포켓몬은 찾지 않았어$"
	// いせきを さがしてるけどｎ
	// つよい ポケモンは さがしてないんだ

Route111_Text_DustyPostBattle:
	.string "유적 찾아 30년!\p"
	.string "아니지 이제 40년인가?\n"
	.string "어라 몇 년이었더라?$"
	// いせきを さがして 30ねん!ｐ
	// いや もう 40ねん さがしているか?ｎ
	// あれ どうだったかな?

Route111_Text_DustyRegister:
	.string "강한 포켓몬은 못 찾았지만\n"
	.string "강한 트레이너는 찾았네!$"
	// つよい ポケモンは さがしてないけどｎ
	// なぜだか ポケナビは おきにいり なんだ!

Route111_Text_DustyRematchIntro:
	.string "유적 찾아 30년!\p"
	.string "아니지! 유적 찾아 40년!\n"
	.string "그런 이 몸과 배틀하겠다고?$"
	// いせきを さがして 30ねん!ｐ
	// いや いせきを さがして 40ねん!ｎ
	// そんな わたしと たたかうのかね?

Route111_Text_DustyRematchDefeat:
	.string "유적도 못 찾겠고\n"
	.string "강한 포켓몬도 못 찾겠다$"
	// いせきは みつからないｎ
	// つよい ポケモンも みつからない

Route111_Text_DustyPostRematch:
	.string "유적 찾아 30년!\p"
	.string "아니지 벌써 한 40년은 찾아다녔나?\p"
	.string "음 50년인 것 같기도 하고...\n"
	.string "어라 몇 년이었더라?$"
	// いせきを さがして 30ねん!ｐ
	// いや もう 40ねん さがしているか?ｐ
	// う-ん 50ねん だった きもする……ｎ
	// あれ どうだったかな?

Route111_Text_TravisIntro:
	.string "나도 힘이 넘치고!\n"
	.string "내 포켓몬도 힘이 넘친다!$"
	// ぼくも げんき いっぱい!ｎ
	// ポケモンも げんき いっぱい だよ!

Route111_Text_TravisDefeat:
	.string "포켓몬이 기진맥진해졌어$"
	// ポケモンの げんき なくなったよ

Route111_Text_TravisPostBattle:
	.string "힘이 넘쳐서 달려나가고 있는\n"
	.string "트레이너를 보면\l"
	.string "무심코 그쪽을 보게 되지!$"
	// げんき いっぱいに はしりまわるｎ
	// トレ-ナ-が いるとｌ
	// つい そっちを みちゃうよね!

Route111_Text_IreneIntro:
	.string "어디로 가고 있는지 모르겠지만\n"
	.string "잠깐 승부해보지 않을래?$"
	// どこに いくのか しらないけどｎ
	// ちょっと しょうぶ してみない?

Route111_Text_IreneDefeat:
	.string "얄미울 정도로 강하구나!?$"
	// にくらしいほど つよいのね!

Route111_Text_IrenePostBattle:
	.string "굴뚝산에 가볼까? 하고\n"
	.string "생각하고 있었는데\l"
	.string "이 주변 경치도 정말 좋아!$"
	// えんとつやまに いこうかな? ってｎ
	// おもって いるんだけどｌ
	// このあたりの けしきも いいのよね!

Route111_Text_DaisukeIntro:
	.string "자신을 단련시키기 위해\n"
	.string "만나는 모든 사람들에게\l"
	.string "승부를 걸고 있쑵니돠!$"
	// おのれを きたえるためｎ
	// であう にんげん すべてにｌ
	// しょうぶを もうしこんでるッス!

Route111_Text_DaisukeDefeat:
	.string "졌쑵니돠...!$"
	// まいったッス……!

Route111_Text_DaisukePostBattle:
	.string "당신처럼 강한 트레이너를\n"
	.string "이길 수 있을 때까지\l"
	.string "오직 수행만이 있을 뿐입니돠!$"
	// おぬしの ようにｎ
	// つよい トレ-ナ-に かてるまでｌ
	// しゅぎょう あるのみッス!

Route111_Text_WiltonIntro:
	.string "네가 포켓몬을 얼마나\n"
	.string "단련시키고 있는지 보여줘야겠다!$"
	// きみが ポケモンを どこまでｎ
	// きたえているか みせて もらおう!

Route111_Text_WiltonDefeat:
	.string "과연\n"
	.string "상당히 단련시켰군!$"
	// なるほどｎ
	// かなり きたえてるね!

Route111_Text_WiltonPostBattle:
	.string "포켓몬도 트레이너도\n"
	.string "배틀을 통해 많은 것을 배운다!\p"
	.string "중요한 건\n"
	.string "패배해도 포기하지 않는 것이지!$"
	// ポケモンも トレ-ナ-もｎ
	// たたかうことで いろんなことを まなぶ!ｐ
	// だいじ なのはｎ
	// まけても あきらめないことさ!

Route111_Text_WiltonRegister:
	.string "너의 단련법은 참고가 되는군!\n"
	.string "내킨다면 재대결을 해다오$"
	// きみの きたえかた さんこうに なるな!ｎ
	// きが むいたら さいど たたかってほしい

Route111_Text_WiltonRematchIntro:
	.string "우리들은 더욱 높은 곳을 목표로\n"
	.string "여기서 포켓몬을 단련시키고 있다\l"
	.string "너도 같이 수행하자고!$"
	// ぼくたちは さらなる たかみを めざしてｎ
	// ここで ポケモンを きたえているｌ
	// きみも いっしょに しゅぎょう しよう!

Route111_Text_WiltonRematchDefeat:
	.string "제법 하는군!$"
	// なかなか やるな!

Route111_Text_WiltonPostRematch:
	.string "그렇게 강하니까\n"
	.string "포켓몬리그에 도전해도 되겠어!$"
	// そんなに つよいならｎ
	// ポケモンリ-グを めざすと いいよ!

Route111_Text_BrookeIntro:
	.string "어머 네 포켓몬\n"
	.string "상당히 강해 보여!\l"
	.string "내 상대를 해주지 않을래?$"
	// あら あなたの ポケモンｎ
	// かなり つよそうだわ!ｌ
	// ぜひ おてあわせ してくれない?

Route111_Text_BrookeDefeat:
	.string "강해 보이는 게 아니라\n"
	.string "강하구나!$"
	// つよそう じゃなくてｎ
	// つよいのね!

Route111_Text_BrookePostBattle:
	.string "나도 더 노력해서\n"
	.string "포켓몬을 키우려고 하는데\l"
	.string "아직 해야 할 일이 산더미야!$"
	// あたしも がんばってｎ
	// ポケモン そだてた つもりだけどｌ
	// まだ やること いっぱい あるわね!

Route111_Text_BrookeRegister:
	.string "너 같은 강한 트레이너와\n"
	.string "친구가 되는 게 꿈이야!$"
	// あなた みたいな つよいひととｎ
	// おともだちに なりたいわ!

Route111_Text_BrookeRematchIntro:
	.string "포켓몬은 쓰는 기술에 따라\n"
	.string "강해지기도 하고 약해지기도 해!\p"
	.string "네 포켓몬은\n"
	.string "어떤 기술을 배우고 있니?$"
	// ポケモンは つかう わざによってｎ
	// つよくなったり よわくなったりも するわ!ｐ
	// あなたの ポケモンｎ
	// どんな わざを おぼえているの?

Route111_Text_BrookeRematchDefeat:
	.string "좋은 기술을 배우고 있구나!$"
	// いい わざを おぼえているのね!

Route111_Text_BrookePostRematch:
	.string "내 포켓몬은 진화시키지 말고\n"
	.string "먼저 기술을 배우게 하고 나서\l"
	.string "키우는 편이 좋았으려나?$"
	// あたしの ポケモン しんか させずにｎ
	// さきに わざを おぼえさせてからｌ
	// そだてた ほうが よかったかな?

Route111_Text_CeliaIntro:
	.string "이런 곳으로\n"
	.string "소풍 오는 게 아니었는데!$"
	// こんな ところでｎ
	// ピクニックを するんじゃ なかった!

Route111_Text_CeliaDefeat:
	.string "아-\n"
	.string "진짜 오는 게 아니었는데!$"
	// も-ｎ
	// ほんとに くるんじゃ なかった!

Route111_Text_CeliaPostBattle:
	.string "이런 모래폭풍이면\n"
	.string "고고고글을 쓰고 있어도\l"
	.string "도시락을 먹을 수가 없잖아...$"
	// この すなあらし じゃｎ
	// ゴ-ゴ-ゴ-グルを つけて いてもｌ
	// おべんとうが ひろげられないんだもん……

Route111_Text_BryanIntro:
	.string "네 강함은 어느 정도지?\n"
	.string "그 답을 밝혀내겠다!$"
	// きみの つよさは どのくらいか?ｎ
	// その ナゾを ときあかそう!

Route111_Text_BryanDefeat:
	.string "오오 그 강함!\n"
	.string "신비하기 짝이 없군!$"
	// おお そのつよさｎ
	// ナゾに みちておる!

Route111_Text_BryanPostBattle:
	.string "이 사막은 모래 속에\n"
	.string "신비를 간직하고 있다!$"
	// この さばくにはｎ
	// ナゾが おおい ですぞ-っ!

Route111_Text_BrandenIntro:
	.string "나에게 져주면\n"
	.string "샌드위치를 나눠줄게$"
	// ぼくに まけて くれたらｎ
	// サンドイッチ わけて あげるよ!

Route111_Text_BrandenDefeat:
	.string "쳇!\n"
	.string "샌드위치에 넘어올 거라고 생각했는데$"
	// ちぇっ!ｎ
	// サンドイッチに つられると おもったのに

Route111_Text_BrandenPostBattle:
	.string "내 모래두지는\n"
	.string "샌드위치를 엄청 먹어두지$"
	// ぼくの サンドもｎ
	// サンドイッチ だいすき なんだ

Route111_Text_TyronIntro:
	.string "난 이런 포켓몬을 좋아해!$"
	// ぼくは こんな ポケモンが すきなんだ!

Route111_Text_TyronDefeat:
	.string "잠깐만! 내 포켓몬\n"
	.string "제대로 봤어!?$"
	// ちょっと! ぼくの ポケモンｎ
	// ちゃんと みてくれてた!?

Route111_Text_TyronPostBattle:
	.string "승부할 때\n"
	.string "자신의 포켓몬을 보여주는\l"
	.string "즐거움이 분명 있단 말이지-$"
	// しょうぶを する ときってｎ
	// じぶんの ポケモンを みせびらかすｌ
	// たのしみが ゼッタイ あるよね-

Route111_Text_CelinaIntro:
	.string "우훗...\n"
	.string "날 두근거리게 만들어줘!$"
	// うふん……ｎ
	// わたくしを ドキドキ させてね!

Route111_Text_CelinaDefeat:
	.string "굉 ...장해\n"
	.string "얼마나 강한 거야$"
	// す ……ごいｎ
	// なんて つよいの

Route111_Text_CelinaPostBattle:
	.string "아 아직도 두근거리고 있어\n"
	.string "넌 참... 멋진 트레이너야$"
	// ま まだ ドキドキ しているわｎ
	// あなたって…… ステキな トレ-ナ-ね

Route111_Text_HaydenIntro:
	.string "난 지금 배가 고프니까\n"
	.string "적당히 하진 않을 거야!$"
	// おいらは いま はらが へっているｎ
	// だから ようしゃは しないぞ!

Route111_Text_HaydenDefeat:
	.string "꼬르륵...$"
	// ぐうぅ……

Route111_Text_HaydenPostBattle:
	.string "너무 배고파!\n"
	.string "나무열매라도 구워 먹을까?$"
	// はらが なった!ｎ
	// きのみでも やいて たべようかナ?

Route111_Text_BiancaIntro:
	.string "너 보라시티 방향에서 온 거야?\n"
	.string "그럼 아주 팔팔하겠네!$"
	// あなたは キンセツの ほうから きたの?ｎ
	// じゃ たいりょくも バッチリね!

Route111_Text_BiancaDefeat:
	.string "진짜 팔팔하구나-$"
	// あらら すごいんだ-

Route111_Text_BiancaPostBattle:
	.string "이 앞의 길은\n"
	.string "제법 기니까 조심해!$"
	// この さきの みちのりはｎ
	// けっこう ながいわよ!

Route112_Text_BriceIntro:
	.string "와핫핫!\n"
	.string "어떠냐?\l"
	.string "나와 승부하지 않겠나?\l"
	.string "와핫핫!$"
	// わっはっはっ!ｎ
	// どうだ?ｌ
	// オレと しょうぶ しないか?ｌ
	// わっはっはっ!

Route112_Text_BriceDefeat:
	.string "졌다...\n"
	.string "와핫핫!$"
	// まけた……ｎ
	// わっはっはっ!

Route112_Text_BricePostBattle:
	.string "알록달록한 버섯을 먹었더니...\n"
	.string "우 웃음이 멈추질 않아!\l"
	.string "와핫핫핫!$"
	// いろあざやかな キノコを たべたら……ｎ
	// わ わらいが とまらない!ｌ
	// わっはっはっ!

Route112_Text_TrentIntro:
	.string "등산으로 단련된 나의 다리와 허리는\n"
	.string "어지간해선 절대 무너지지 않는다!$"
	// やまのぼりで きたえた オレの あしこしｎ
	// ちょっとや そっとじゃ くじけないぜ!

Route112_Text_TrentDefeat:
	.string "아...\n"
	.string "다리에 쥐가 났다...$"
	// あ……ｎ
	// あしが つった……

Route112_Text_TrentPostBattle:
	.string "몇십 킬로나 되는 짐을 지고\n"
	.string "산길을 계속 걷는다\l"
	.string "몸이 튼튼해지지 않을 수가 없지!$"
	// なんじゅっキロも ある にもつを せおってｎ
	// やまみちを あるき つづけるんだｌ
	// からだが じょうぶに なるぞ!

Route112_Text_TrentRegister:
	.string "쥐가 난 다리가 아파...\n"
	.string "잠깐 내 배낭에서\l"
	.string "붕대 좀 꺼내줘\p"
	.string "아니 틀렸어 그건 포켓내비잖아!\n"
	.string "됐다 줘봐 등록이나 하게$"
	// つった あしが いたい……ｎ
	// ちょっと オレの リュックからｌ
	// ほうたいを だしてくれｐ
	// って ちがうよ それは ポケナビだろ!ｎ
	// もういいよ とうろく するから

Route112_Text_TrentRematchIntro:
	.string "등산으로 단련된 몸이니까\n"
	.string "엄청 파워풀하다고!$"
	// やまのぼりで きたえてるからなｎ
	// かなり パワフルだぞ!

Route112_Text_TrentRematchDefeat:
	.string "파워에서 진 건가?$"
	// パワ-で まけたか?

Route112_Text_TrentRematchPostBattle:
	.string "굴뚝산 위에는\n"
	.string "굉장한 트레이너가 있다고 하더군!\l"
	.string "다음에 승부하러 가볼 생각이다!$"
	// えんとつやまの うえにはｎ
	// すごい トレ-ナ-が いるらしいぞ!ｌ
	// こんど しょうぶに いくつもりだ!

Route112_Text_LarryIntro:
	.string "난 강해...\n"
	.string "져도 울지 않을 거야...!$"
	// ぼくは つよいんだ……ｎ
	// まけても ないたり しないぞ……!

Route112_Text_LarryDefeat:
	.string "으아---앙!$"
	// うわ---ん!

Route112_Text_LarryPostBattle:
	.string "엄마가 보고 싶은\n"
	.string "외로움에 우는 게 아니야!\l"
	.string "훌쩍...$"
	// おかあさんに あえなくてｎ
	// さみしいから ないてるんじゃ ないよ!ｌ
	// ぐすん……

Route112_Text_CarolIntro:
	.string "피크닉 하면 노래지!\n"
	.string "자 다 같이 노래합시다!$"
	// ピクニックと いえば うた!ｎ
	// さあ いっしょに うたいましょ!

Route112_Text_CarolDefeat:
	.string "이렇게나 강하다니...!$"
	// こんなに つよいなんて……!

Route112_Text_CarolPostBattle:
	.string "노래도 포켓몬 승부도\n"
	.string "잘하고 못하고는 상관없어!\p"
	.string "즐기는 게 이기는 거지!$"
	// うたも ポケモンしょうぶもｎ
	// うまい へた なんて かんけい ないよ!ｌ
	// たのしんだ ほうが かち なのよ!

Route112_Text_BryantIntro:
	.string "불꽃샛길에서 잡은\n"
	.string "뜨끈뜨끈한 포켓몬 보여줄게-!$"
	// ほのおの ぬけみちで つかまえたｎ
	// ホカホカの ポケモン みせてやろ-!

Route112_Text_BryantDefeat:
	.string "머리가 지끈지끈하다$"
	// おお ボコボコだ

Route112_Text_BryantPostBattle:
	.string "꽤나 멋진\n"
	.string "배틀을 하는데 너!$"
	// ナカナカ すてきなｎ
	// たたかいかたじゃ ないか きみぃ!

Route112_Text_ShaylaIntro:
	.string "어머! 멋진 트레이너님\n"
	.string "로맨틱한 승부를 부탁할게!\l"
	.string "난 제법 강하단다!$"
	// アラ! すてきな トレ-ナ-さんｎ
	// ロマンチックな しょうぶを おねがいね!ｌ
	// マアマア つよいわよ わたし!

Route112_Text_ShaylaDefeat:
	.string "어쩜 이리도 강할 수가\n"
	.string "나 깜짝 놀랐어!$"
	// なんて つよいのかしらｎ
	// おねえさん おどろいちゃった!

Route112_Text_ShaylaPostBattle:
	.string "저기 지금 바빠?\n"
	.string "그 만약 괜찮다면\l"
	.string "당장 2차전 하고 싶어서...\l"
	.string "응? 바쁘다면 어쩔 수 없지$"
	// ねえ いま いそがしいの?ｎ
	// えっと もし よかったらｌ
	// さっそく 2かいせん と おもって……ｌ
	// ん? いそがしいなら いいわ

Route113_Text_JaylenIntro:
	.string "이 근처가 비교적 시원한 이유가\n"
	.string "뭔지 아니?$"
	// この あたりが わりと すずしいのｎ
	// なんでか しってるかい?

Route113_Text_JaylenDefeat:
	.string "으아-!\n"
	.string "져버렸다-!$"
	// ぴゅ-っ!ｎ
	// まけた-っ!

Route113_Text_JaylenPostBattle:
	.string "화산재가 햇빛을\n"
	.string "가리고 있어서 서늘한 거야!\p"
	.string "더위를 잘 타는 나한텐 잘됐지만!$"
	// かざんばいが たいようの ひかりをｎ
	// さえぎってるから ひえるんだね!ｌ
	// あつがりの オレには たすかるよ!

Route113_Text_DillonIntro:
	.string "산의 분화는\n"
	.string "지구가 살아있다는 증거지!$"
	// やまの ふんかはｎ
	// ちきゅうが いきている しょうこ!

Route113_Text_DillonDefeat:
	.string "강하구나 너-!$"
	// つよいな おまえ-っ!

Route113_Text_DillonPostBattle:
	.string "콜록 커헉-!\n"
	.string "재가 폐에 들어갔어...\p"
	.string "멈추질 않아...\n"
	.string "추워... 부들부들...$"
	// ごほ がへっ!ｎ
	// はいが はいに はいった……ｐ
	// うけなかった……ｎ
	// さむい…… ブルブル……

Route113_Text_MadelineIntro:
	.string "제 둔타에게\n"
	.string "화산재가 떨어지지 않도록\l"
	.string "파라솔을 들고 있어요$"
	// あたしの ドンメルちゃんにｎ
	// かざんばいが かからないようにｌ
	// パラソルを さしているの

Route113_Text_MadelineDefeat:
	.string "하아 하아...\n"
	.string "지쳤어요...$"
	// はあ はあ……ｎ
	// つかれましたわ……

Route113_Text_MadelinePostBattle:
	.string "정말 강하군요\n"
	.string "저 감동받았어요$"
	// とても おつよいのねｎ
	// おねえさん かんしん しちゃったわ

Route113_Text_MadelineRegister:
	.string "저기 잠깐 파라솔로 들어와서\n"
	.string "포켓내비에 등록하고 가세요!$"
	// ね ちょっと パラソルに はいってｎ
	// ポケナビを とうろく していって!

Route113_Text_MadelineRematchIntro:
	.string "오랜만이에요\n"
	.string "괜찮다면 승부하시겠어요?$"
	// おひさしぶりねｎ
	// よろしかったら しょうぶ しません?

Route113_Text_MadelineRematchDefeat:
	.string "훌륭해요$"
	// おみごと ですわ

Route113_Text_MadelinePostRematch:
	.string "여전히 강하시군요\n"
	.string "정말 감동받았어요$"
	// あいかわらず おつよいのねｎ
	// おねえさん かんしん しちゃったわ

Route113_Text_LaoIntro:
	.string "재 속에서 짜자잔!!\n"
	.string "승부해 주시오!$"
	// はいの なかから ドロロンッ!!ｎ
	// しょうぶで ござる!

Route113_Text_LaoDefeat:
	.string "지고 말았소$"
	// まいったで ござる

Route113_Text_LaoPostBattle:
	.string "좀 더 숨는 방법을 연구해야지\n"
	.string "그럼 이만 실례하겠소$"
	// もっと かくれかたを けんきゅう しようｎ
	// それでは しつれいするで ござる

Route113_Text_LaoRegister:
	.string "이얍! 닌자 기술\n"
	.string "포켓내비에 등록하기!$"
	// やあ! にんぽうｎ
	// ポケナビ とうろくのじゅつで ござる!

Route113_Text_LaoRematchIntro:
	.string "재가 없어도 짜자자잔!!\n"
	.string "승부해 주시오!$"
	// はいの なかから ドロロロンッ!!ｎ
	// しょうぶで ござる!

Route113_Text_LaoRematchDefeat:
	.string "지고 말았소$"
	// まいったで ござる

Route113_Text_LaoPostRematch:
	.string "숨는 방법은 좋았지만\n"
	.string "승부 실력이 부족했어...\p"
	.string "그럼 이만 실례하겠소$"
	// かくれかたは よかったがｎ
	// しょうぶが いまいち だった……ｐ
	// それでは しつれいするで ござる

Route113_Text_LungIntro:
	.string "발견해 줘서 고마워!\n"
	.string "하지만 승부는 이야기가 다르지!$"
	// みつけてくれて ありがとう!ｎ
	// でも しょうぶは べつだよ!

Route113_Text_LungDefeat:
	.string "닌자 기술 화산재 속에 숨기!\p"
	.string "... 어 벌써 끝난 거야?$"
	// にんぽう かざんばい がくれ!ｐ
	// …… って もう おわり?

Route113_Text_LungPostBattle:
	.string "숨어 있으면 뭐가 걱정이냐고?\n"
	.string "아무도 지나가지 않으면 외롭지$"
	// かくれていて なにが しんぱいってｎ
	// だれも とおらないと さびしいんだよね

Route113_Text_ToriIntro:
	.string "나나: 둘이서 화산재 모으고 있어\n"
	.string "근데 포켓몬 승부도 할 거야!$"
	// ナナ『ふたりで かざんばい あつめてるよｎ
	// でも ポケモンしょうぶも するんだよ!

Route113_Text_ToriDefeat:
	.string "나나: 져버렸다\n"
	.string "재미없으니까 화산재 모아야지!$"
	// ナナ『まけちゃったｎ
	// つまんないから かざんばい あつめよ!

Route113_Text_ToriPostBattle:
	.string "나나: 화산재 얼마나 모였을까?\n"
	.string "하양비드로 만들면 좋을 텐데!$"
	// ナナ『かざんばい どれくらい たまったかな?ｎ
	// しろいビ-ドロ つくれると いいのにね!

Route113_Text_ToriNotEnoughMons:
	.string "나나: 우리는 2대 2로 싸우고 싶어\n"
	.string "그렇게 하지 않으면 져버리는걸!$"
	// ナナ『あたしたち 2たい2で たたかいたいのｎ
	// そうしないと まけちゃうもん!

Route113_Text_TiaIntro:
	.string "네네: 둘이서 화산재 모으고 있어\n"
	.string "근데 포켓몬 승부도 할 거야!$"
	// ネネ『ふたりで かざんばい あつめてるよｎ
	// でも ポケモンしょうぶも するんだよ!

Route113_Text_TiaDefeat:
	.string "네네: 이기지 못했어\n"
	.string "재미없으니까 화산재 모아야지!$"
	// ネネ『かてなかったｎ
	// つまんないから かざんばい あつめよ!

Route113_Text_TiaPostBattle:
	.string "네네: 화산재 꽤 모였어!\n"
	.string "이제 분명 하양비드로 만들 수 있어!$"
	// ネネ『かざんばい けっこう たまったよ!ｎ
	// もう しろいビ-ドロ つくれるよ きっと!

Route113_Text_TiaNotEnoughMons:
	.string "네네: 우리들은 2대 2로 싸우고 싶어\n"
	.string "그렇게 하지 않으면 져버리는걸!$"
	// ネネ『あたしたち 2たい2で たたかいたいのｎ
	// そうしないと かてないもん!

Route113_Text_CobyIntro:
	.string "너 같은 건 이 날개로\n"
	.string "날려버려 주지!$"
	// おまえ なんか この つばさでｎ
	// ふきとばして やるぜっ!

Route113_Text_CobyDefeat:
	.string "엇 어라?$"
	// え あれ?

Route113_Text_CobyPostBattle:
	.string "이렇게 쉽게 져버리면\n"
	.string "뭐라고 해야 할지 모르겠어...$"
	// そんなに あっさり かたれるとｎ
	// なにを いって いいか わからない……

Route113_Text_SophieIntro:
	.string "따뜻해서 졸리기 시작했어\n"
	.string "잠도 깰 겸 상대를 부탁할게!$"
	// あったかくて ねむく なっちゃうｎ
	// ねむけ ざましに あいてを してよ!

Route113_Text_SophieDefeat:
	.string "분명 이건 꿈일 거야...$"
	// きっと これは ユメなのよ……

Route113_Text_SophiePostBattle:
	.string "져서 잠이 더 오네\n"
	.string "그냥 여기서 자야지!\l"
	.string "쿨쿨$"
	// まけて くやしい からｎ
	// もう ここで フテね しちゃうわ!ｌ
	// ぐ-ぐ-

Route113_Text_LawrenceIntro:
	.string "여기서 화산재를\n"
	.string "모으는 중이야?$"
	// もしかして かざんばい あつめのｎ
	// とちゅう だった?

Route113_Text_LawrenceDefeat:
	.string "에헤헤 져버렸네$"
	// えへへ まけちゃったね

Route113_Text_LawrencePostBattle:
	.string "나도 재 속에 숨을까$"
	// ぼくも はいに もぐっちゃおう かしら

Route113_Text_WyattIntro:
	.string "저 저랑 배틀할 겁니까!\n"
	.string "방금 막 잡은 포켓몬인데!$"
	// ぼ ボクと たたかうって いうんですか!ｎ
	// まだ つかまえた ばかりなのに!

Route113_Text_WyattDefeat:
	.string "이 이겨서 기쁩니까!\n"
	.string "이런 저를 이겨서 기쁜 겁니까!$"
	// か かって うれしい ですか!ｎ
	// こんな ボクに かって うれしいですか!

Route113_Text_WyattPostBattle:
	.string "패 패배자한테 위로의 말을\n"
	.string "건네려는 겁니까!\l"
	.string "머 멋지군요! 흥!$"
	// はいしゃに こえを かけて くれるってｎ
	// いうんですか!ｌ
	// か カッコいい ですね! ふん!

Route114_Text_LennyIntro:
	.string "얏호-!\p"
	.string "......\p"
	.string "메아리 대신에\n"
	.string "얏호-! 라고 외쳐줘야지!$"
	// やっほ-っ!ｐ
	// ……ｐ
	// こだまの かわりにｎ
	// やっほ-! って いってくれよ!

Route114_Text_LennyDefeat:
	.string "얏호-!$"
	// やっほ-っ!

Route114_Text_LennyPostBattle:
	.string "어렸을 때는 메아리가\n"
	.string "건너편 산에 있는 성대모사 달인이\l"
	.string "얏호-! 라고 해주는 건 줄 알았어$"
	// こどものころ こだま ってｎ
	// むこうの やまにいる モノマネさんがｌ
	// やっほ-! って いってると おもってた

Route114_Text_LucasIntro:
	.string "준비를 게을리하는 자\n"
	.string "산에 오르지 마라!$"
	// じゅんびを おこたる ものｎ
	// やまに のぼるべからず!

Route114_Text_LucasDefeat:
	.string "산은 무서운 곳이다...$"
	// やまは こわい ところだ……

Route114_Text_LucasPostBattle:
	.string "겨울 산에서는 눈사태나 눈보라로\n"
	.string "조난을 당할 위험이 크다!$"
	// ふゆの やまは なだれや ふぶきでｎ
	// そうなんする きけんが おおいぞ!

Route114_Text_ShaneIntro:
	.string "캠핑의 즐거움은\n"
	.string "낚시와 불꽃놀이 그리고 담력 훈련!\p"
	.string "하지만 제일 즐거운 건\n"
	.string "포켓몬 승부지!$"
	// キャンプの たのしみと いえばｎ
	// つりに はなびに きもだめし!ｐ
	// だけど いちばんはｎ
	// ポケモンしょうぶ だね!

Route114_Text_ShaneDefeat:
	.string "너무 강하다-앗!$"
	// つよすぎる-っ!

Route114_Text_ShanePostBattle:
	.string "난 말이지 포켓몬과 같이\n"
	.string "캠핑을 할 수 있는 것만으로도 행복해$"
	// ぼくね ポケモンと いっしょにｎ
	// キャンプ できるだけで しあわせ だよ

Route114_Text_NancyIntro:
	.string "식후의 운동!\n"
	.string "나랑 승부하자!$"
	// しょくごの うんどう!ｎ
	// わたしと しょうぶ しましょうよ!

Route114_Text_NancyDefeat:
	.string "져버렸다-!$"
	// まけちゃった-!

Route114_Text_NancyPostBattle:
	.string "맛있는 밥도 먹었겠다\n"
	.string "왠지 잠이 오기 시작했어...$"
	// おいしい ごはんも たべたしｎ
	// なんだか ねむくなって きたわ……

Route114_Text_SteveIntro:
	.string "우후후후후후...\n"
	.string "내 포켓몬과 승부하지 않을래?$"
	// うふふふふふ……ｎ
	// ボクの ポケモンと しょうぶしない?

Route114_Text_SteveDefeat:
	.string "내 내 포켓몬이...$"
	// ボ ボクの ポケモン……

Route114_Text_StevePostBattle:
	.string "커다랗고 울퉁불퉁 딱딱한 몸에\n"
	.string "큰 뿔과 날카로운 엄니...\p"
	.string "우후후후후...\n"
	.string "그런 포켓몬을 가지고 싶어...$"
	// からだが おおきくて ゴツゴツ かたくてｎ
	// おおきな ツノと するどい キバ……ｌ
	// うふふふふ……ｌ
	// そんな ポケモンが ほしいなぁ……

Route114_Text_SteveRegister:
	.string "두 두고 봐라! ...아니다\n"
	.string "잊지 못하도록 이렇게 해줄게!$"
	// お おぼえてろっ! ……いやｎ
	// わすれられない ように こうしてやる!

Route114_Text_SteveRematchIntro:
	.string "우후후후후후...\n"
	.string "내 포켓몬과 승부하자$"
	// うふふふふふ……ｎ
	// ボクの ポケモンと しょうぶ しようよ

Route114_Text_SteveRematchDefeat:
	.string "아아 포켓몬을 볼 수 있어서\n"
	.string "행복했어...$"
	// ああ ポケモン みることが できてｎ
	// しあわせ だ……

Route114_Text_StevePostRematch:
	.string "우후후후후후...\p"
	.string "난 포켓몬이 승부하는 모습을\n"
	.string "보고 있으면 두근거려$"
	// うふふふふふ……ｐ
	// ポケモンの たたかっている すがたにｎ
	// ぞくぞく するんだ ボク

Route114_Text_BernieIntro:
	.string "캠프파이어나\n"
	.string "불꽃놀이를 할 때는\l"
	.string "물을 준비해 두라고!$"
	// キャンプファイヤ- するときｎ
	// はなびを するときｌ
	// みずを ようい しておけよ!

Route114_Text_BernieDefeat:
	.string "내 투지에 물을 뿌리다니\n"
	.string "소화기 같은 녀석!$"
	// しょうか かつどうｎ
	// ありがとう! ってか

Route114_Text_BerniePostBattle:
	.string "진짜 불조심만큼은 잊지 마!\n"
	.string "불을 만만하게 보면 안 돼!$"
	// ほんと ひのようじん だけは おこたるな!ｎ
	// ひを あまく みるんじゃないぜ!

Route114_Text_BernieRegister:
	.string "불타오른 마음을 가진 채로\n"
	.string "포켓내비에 서로를 등록하자!$"
	// もえあがった きもちの ままｎ
	// ポケナビに とうろく しあおう!

Route114_Text_BernieRematchIntro:
	.string "캠프파이어나\n"
	.string "불꽃놀이를 할 때\l"
	.string "물을 준비하고 있겠지!?$"
	// キャンプファイヤ- するときｎ
	// はなびを するときｌ
	// みずを ようい するように なったか!?

Route114_Text_BernieRematchDefeat:
	.string "불타오르기도 전에\n"
	.string "꺼버리다니!$"
	// もえあがる まえにｎ
	// けされた! ってか

Route114_Text_BerniePostRematch:
	.string "진짜 불조심만큼은 잊지 마!\n"
	.string "불을 만만하게 보면 안 돼!$"
	// ほんと ひのようじん だけは おこたるな!ｎ
	// ひを あまく みるんじゃないぜ!

Route114_Text_ClaudeIntro:
	.string "낚시로 승부하면\n"
	.string "네가 이길 가망이 없겠지\l"
	.string "포켓몬으로 승부를 내자고!$"
	// つりで しょうぶ するとｎ
	// きみには かちめが ないだろうｌ
	// ポケモンで かかってきなさい!

Route114_Text_ClaudeDefeat:
	.string "낚시였으면 이겼을 텐데...$"
	// つりの しょうぶなら かってた……

Route114_Text_ClaudePostBattle:
	.string "유성의 폭포에서\n"
	.string "월척이라도 낚아야겠어\l"
	.string "그 폭포에는 뭔가가 있을 것 같거든$"
	// りゅうせいのたきでｎ
	// おおものでも つると しようかなｌ
	// あそこの たきには なにか いそうだからね

Route114_Text_NolanIntro:
	.string "낚시도 좋지만\n"
	.string "승부도 좋지!\p"
	.string "승부 요청을 받으면\n"
	.string "낚시 중이더라도 거절할 수가 없어!$"
	// つりも すき だがｎ
	// しょうぶも すき!ｐ
	// しょうぶを いどまれたらｎ
	// つりの さいちゅうでも ことわらないよ!

Route114_Text_NolanDefeat:
	.string "승부는 좋아하지만\n"
	.string "잘하는 건 아니야...$"
	// しょうぶは すき だがｎ
	// つよい わけじゃ ないんだ……

Route114_Text_NolanPostBattle:
	.string "이번에야말로!\p"
	.string "라는 생각을 해버리니까\n"
	.string "낚시도 승부도 그만둘 수 없어$"
	// こんどこそ!ｐ
	// と おもっちゃうからｎ
	// つりも しょうぶも やめられない

Route114_Text_TyraIntro:
	.string "리세: 그래!\n"
	.string "왠지 기분이 좋으니까\l"
	.string "너한테도 포켓몬 승부를 가르쳐 줄게$"
	// カヨ『そうねｎ
	// なんとなく そんな きぶん だからｌ
	// あなたにも ポケモン おしえたげよっか

Route114_Text_TyraDefeat:
	.string "리세: 엄청난 전술이다!$"
	// カヨ『すごい たたかいかた!

Route114_Text_TyraPostBattle:
	.string "리세: 후배인 세리에게 내가\n"
	.string "포켓몬 승부를 가르쳐 줬어!$"
	// カヨ『コウハイの イヨに あたしがｎ
	// ポケモンを おしえて あげたの!

Route114_Text_TyraNotEnoughMons:
	.string "리세: 우후후!\n"
	.string "우리들이랑 승부하려면\l"
	.string "포켓몬 한 마리로는 어림도 없어!$"
	// カヨ『うふふ!ｎ
	// あたしたちと しょうぶ するならｌ
	// ポケモン いっぴきじゃ ダメなのよ!

Route114_Text_IvyIntro:
	.string "세리: 넌\n"
	.string "누구한테 포켓몬 승부 배웠니?$"
	// イヨ『あなたｎ
	// だれに ポケモン おそわったの

Route114_Text_IvyDefeat:
	.string "세리: 엄청난 전술이다!$"
	// イヨ『すごい たたかいかた!

Route114_Text_IvyPostBattle:
	.string "세리: 나는\n"
	.string "선배가 가르쳐 줘서\l"
	.string "포켓몬 승부를 시작하게 됐어!$"
	// イヨ『あたしがｎ
	// ポケモン はじめた きっかけはｌ
	// センパイが おしえてくれた からなの!

Route114_Text_IvyNotEnoughMons:
	.string "세리: 포켓몬이 한 마리뿐이야?\n"
	.string "왠지 외로워할 것 같아$"
	// イヨ『ポケモン いっぴき だけなの?ｎ
	// なんだか さみしい かんじ しちゃうね

Route114_Text_KaiIntro:
	.string "큰 거 낚았다 큰 거!$"
	// でっかいの つれたっ でっかいの!

Route114_Text_KaiDefeat:
	.string "어라-\n"
	.string "크기로 졌다고?$"
	// あれ-ｎ
	// おおきさで まけたんかな

Route114_Text_KaiPostBattle:
	.string "그래!\n"
	.string "더 큰 월척을 낚아야겠어!$"
	// よっしゃ-!ｎ
	// もっと おおきいの つるもんね!

Route114_Text_CharlotteIntro:
	.string "난!\n"
	.string "귀엽기만 한 게 아니거든!$"
	// あたし!ｎ
	// かわいい だけじゃ ないんだから!

Route114_Text_CharlotteDefeat:
	.string "귀엽지 않아-앗!$"
	// かわいく な-いっ!

Route114_Text_CharlottePostBattle:
	.string "귀엽기만 한 포켓몬은 별로야!\n"
	.string "귀엽고 기괴한 게 좋아!$"
	// かわいい だけの ポケモンなんて いや!ｎ
	// かわいくて ひとクセ あるコが すき!

Route114_Text_AngelinaIntro:
	.string "너 포켓몬을\n"
	.string "얼마나 많이 진화시켜 봤니?$"
	// あなたの ポケモンってｎ
	// どの くらい しんか させてる?

Route114_Text_AngelinaDefeat:
	.string "흐-음\n"
	.string "그렇군$"
	// ふ-んｎ
	// なるほどね

Route114_Text_AngelinaPostBattle:
	.string "진화시키면\n"
	.string "모습이 엄청 바뀌어서\l"
	.string "깜짝 놀라게 되는 포켓몬도 있지!$"
	// しんか させるとｎ
	// みためが ものすごく かわってｌ
	// ビックリする ポケモンが いるよね!

Route115_Text_TimothyIntro:
	.string "흐음...\n"
	.string "실력이 좋을 것 같군...\l"
	.string "내가 상대해주마!$"
	// ふむ……ｎ
	// なかなか できそうだな……ｌ
	// わたしが あいてを してあげよう!

Route115_Text_TimothyDefeat:
	.string "상상 이상의 강함이군...!$"
	// そうぞう いじょうの つよさだ……!

Route115_Text_TimothyPostBattle:
	.string "천재 같은 건 없다\n"
	.string "모든 것은 노력!\l"
	.string "이 몸은 그렇게 믿고 있다...$"
	// てんさい など いないｎ
	// すべては どりょく!ｌ
	// わたしは そう しんじている……

Route115_Text_TimothyRegister:
	.string "흠...\n"
	.string "이렇게 지는 것도 오래간만이군\l"
	.string "가능하다면 또 상대를 해다오$"
	// ふむ……ｎ
	// こんな まけかたも ひさかたぶりだｌ
	// できれば また あいてを してほしい

Route115_Text_TimothyRematchIntro:
	.string "흠...\n"
	.string "여전히 좋은 몸놀림이군\l"
	.string "내 상대를 부탁한다!$"
	// ふむ……ｎ
	// あいかわらずの みのこなしｌ
	// わたしの あいてを してもらおう!

Route115_Text_TimothyRematchDefeat:
	.string "여전한 강함이군...!$"
	// あいかわらずの つよさだ……!

Route115_Text_TimothyPostRematch:
	.string "오직 노력만이 있을 뿐!\p"
	.string "패배한 것은 아직\n"
	.string "노력이 부족하기 때문이다!$"
	// どりょく あるのみ!ｐ
	// まけたのは まだまだｎ
	// どりょくが たりないからだ!

Route115_Text_KoichiIntro:
	.string "나의!\p"
	.string "알통몬이!\p"
	.string "배틀을 원하고 있다!$"
	// おれのッ!ｐ
	// ワンリキ-がッ!ｐ
	// たたかいを のぞんでいるッ!

Route115_Text_KoichiDefeat:
	.string "아야야야얏!$"
	// いててててっ!

Route115_Text_KoichiPostBattle:
	.string "나의 알통몬들이!\p"
	.string "강함을 원하는 이상\p"
	.string "우리들은 끝없이 강해진다!$"
	// おれの ワンリキ- たちがッ!ｐ
	// つよさを のぞむかぎりｐ
	// おれたちは どこまでも つよくなるぜッ!

Route115_Text_NobIntro:
	.string "내 주특기는\n"
	.string "박치기로 벽돌을 부수는 거다!$"
	// オレの とくいわざはｎ
	// ずつきで レンガを くだく ことだ!

Route115_Text_NobDefeat:
	.string "으아-악!\n"
	.string "머리가 부서졌다-앗!$"
	// うが-っ!ｎ
	// あたまが くだけた-っ!

Route115_Text_NobPostBattle:
	.string "포켓몬에게 태권도를 가르치고 있다\n"
	.string "나보다 강해질 것 같아서\l"
	.string "살짝 기대가 되는군!$"
	// ポケモンに カラテを おしえてるんだがｎ
	// オレより つよく なりそうでｌ
	// ちょっと たのしみ なんだ!

Route115_Text_NobRegister:
	.string "너 굉장하군!\n"
	.string "단련이 끝나고 한 번 더 승부하자!$"
	// きみは すげえな!ｎ
	// きたえなおして もういちど しょうぶだ!

Route115_Text_NobRematchIntro:
	.string "네게 지고 난 후 열심히\n"
	.string "포켓몬과 자신을 다시 단련시켰다!\l"
	.string "자 다시 한 번 승부다!$"
	// きみに まけてから がんばってｎ
	// ポケモンと おのれを きたえなおしたぞ!ｌ
	// さあ もういちど しょうぶ!

Route115_Text_NobRematchDefeat:
	.string "으갸-악!\n"
	.string "또 졌다-앗!$"
	// うが-っ!ｎ
	// また まけた-っ!

Route115_Text_NobPostRematch:
	.string "내 포켓몬은 계속 강해질 거다!\n"
	.string "열심히 단련하겠어!$"
	// おれの ポケモンは まだまだ つよくなる!ｎ
	// がんばって きたえるぞ!

Route115_Text_CyndyIntro:
	.string "이 모래 해변은\n"
	.string "내 비밀 수행 장소야!\l"
	.string "마음대로 들어오지 말라고!$"
	// この すなはまは わたしのｎ
	// ヒミツの しゅぎょう ばしょ!ｌ
	// かってに はいって こないでよ!

Route115_Text_CyndyDefeat:
	.string "수행이 부족해...!$"
	// しゅぎょうが たりないわ……!

Route115_Text_CyndyPostBattle:
	.string "모래가 쿠션 역할을 하니까\n"
	.string "몸에 상처를 입지 않아\l"
	.string "최고의 수행 장소지!$"
	// すなが クッションに なるからｎ
	// からだを いためないのｌ
	// さいこうの しゅぎょう ばしょね!

Route115_Text_CyndyRegister:
	.string "좋아 네가 여기에 들어오는 걸\n"
	.string "인정해 주지!\l"
	.string "대신 또 상대를 부탁할게!$"
	// いいわ あなたが ここに はいるのｎ
	// みとめてあげる!ｌ
	// そのかわり また あいてを たのむわよ!

Route115_Text_CyndyRematchIntro:
	.string "자 포켓몬 승부 간다!$"
	// さあ ポケモンしょうぶ いくわよ!

Route115_Text_CyndyRematchDefeat:
	.string "나는 더 할 수 있지만\n"
	.string "포켓몬이...$"
	// わたしは たたかえるけどｎ
	// ポケモンが……

Route115_Text_CyndyPostRematch:
	.string "졌어도 살짝 즐거운 건\n"
	.string "정말로 포켓몬을 좋아해서일까?$"
	// まけても ちょっと たのしいのはｎ
	// ほんとうに ポケモンが すき だからかな?

Route115_Text_HectorIntro:
	.string "난 희귀한 포켓몬을 가지고 있어!\n"
	.string "괜찮으면 보여줄까?$"
	// ぼく めずらしい ポケモン もってるんだ!ｎ
	// よかったら みせて あげようか

Route115_Text_HectorDefeat:
	.string "너...\n"
	.string "내 포켓몬 가지고 싶지?$"
	// きみ……ｎ
	// ぼくの ポケモン ほしいでしょ?

Route115_Text_HectorPostBattle:
	.string "이렇게 희귀한 포켓몬을 가지고 있으니까\n"
	.string "그것만으로도 만족해!$"
	// こんなに めずらしい ポケモン もってるんだｎ
	// それだけで ぼくは まんぞく なのさ!

Route115_Text_KyraIntro:
	.string "달리면서 승부할 거야!\n"
	.string "너도 따라오라고-!$"
	// はしりながら しょうぶを するわよッ!ｎ
	// あなたも ついて きなさ-い!

Route115_Text_KyraDefeat:
	.string "하아 하아...$"
	// はぁ はぁ……

Route115_Text_KyraPostBattle:
	.string "달리면서 배틀하려고 했던 게\n"
	.string "잘못이었어!\l"
	.string "잠깐 달리고 머리나 식혀야겠다$"
	// はしりながら たたかおうと したのがｎ
	// まちがい だったわよ!ｌ
	// ひとっぱしり して アタマ ひやすかな

Route115_Text_JaidenIntro:
	.string "받아랏-\n"
	.string "닌자 기술 슈퍼포켓몬 어택!$"
	// くらえ-っｎ
	// にんぽう すごポケモンの じゅつ!

Route115_Text_JaidenDefeat:
	.string "흐-앙 실패했소!$"
	// わ-ん しっぱいだ!

Route115_Text_JaidenPostBattle:
	.string "그래도 내 포켓몬\n"
	.string "슈퍼 강하지 않았소?$"
	// でも ぼくの ポケモンｎ
	// すごポケモン だった でしょ?

Route115_Text_HeleneIntro:
	.string "후훗 내 포켓몬들의\n"
	.string "강함은 검은 띠 정도라고!$"
	// ふふっ あたしの ポケモンたちはｎ
	// くろおび クラスの つよさよ!

Route115_Text_HeleneDefeat:
	.string "너무 분해!$"
	// くやしすぎるわ!

Route115_Text_HelenePostBattle:
	.string "나보다 강한 녀석은\n"
	.string "만나본 적이 없는데...\p"
	.string "알았다!\n"
	.string "너 체육관 관장이지!$"
	// あたしより つよい ひとなんてｎ
	// めったに あわないのに……ｐ
	// わかった!ｎ
	// あなた ジムリ-ダ- でしょ!

Route115_Text_AlixIntro:
	.string "눈이 마주친 이상 놓치지 않겠어!$"
	// めが あったからには にがさないわよ!

Route115_Text_AlixDefeat:
	.string "큭... 꽤 하는데!$"
	// くっ…… なかなか!

Route115_Text_AlixPostBattle:
	.string "아-아!\n"
	.string "텔레포트 써서 집으로 돌아갈까$"
	// あ-あ!ｎ
	// テレポ-トで おうちに かえろうかしら

Route115_Text_MarleneIntro:
	.string "명상을 방해했겠다...\n"
	.string "벌을 줘야겠군!$"
	// めいそうの じゃまを したわね……ｎ
	// おしおき させて もらうわ!

Route115_Text_MarleneDefeat:
	.string "정신이 흐트러져 버려!$"
	// こころが みだれて しまう!

Route115_Text_MarlenePostBattle:
	.string "여기서 포켓몬들과\n"
	.string "명상을 하고 있어!\l"
	.string "하지만 별로 고요하지 않은 곳이야$"
	// ここで ポケモンたちとｎ
	// めいそうを していたの!ｌ
	// でも あまり おちつかない ところね

Route116_Text_ClarkIntro:
	.string "터널이 뚫리지 않았다면\n"
	.string "산을 넘어가면 되는 거다!$"
	// トンネルが つうじて いないならｎ
	// やまを こえて いけば いいのだ!

Route116_Text_ClarkDefeat:
	.string "허억... 허억...\n"
	.string "패배로 지쳐버렸다$"
	// ぜえ…… ぜえ……ｎ
	// まけて つかれて しまった

Route116_Text_ClarkPostBattle:
	.string "터널 따윈 없어도 상관없다\n"
	.string "등산가에겐 산이 곧 길이니까!$"
	// トンネルなど なくても かまわんｎ
	// やまおとこは やまが みち なのだ!

Route116_Text_JoeyIntro:
	.string "내 포켓몬은 강하다고-!\n"
	.string "한번 봐봐!$"
	// おれの ポケモン つえ-ぞ!ｎ
	// ちょっと みてみろよ!

Route116_Text_JoeyDefeat:
	.string "아야야야야얏! 상처가 생겼다!\n"
	.string "반창고 붙여야지!$"
	// あいたたたたっ! キズが できた!ｎ
	// バンソ-コ- はらなきゃ!

Route116_Text_JoeyPostBattle:
	.string "반창고는 남자의 훈장!\n"
	.string "또 하나가 늘었어!$"
	// バンソ-コ-は おとこの くんしょう!ｎ
	// また ひとつ ふえたぜ!

Route116_Text_JoseIntro:
	.string "내 벌레포켓몬은 강해!\n"
	.string "승부하자!$"
	// ぼくの むしポケモンは つよいよ!ｎ
	// しょうぶ しようよ!

Route116_Text_JoseDefeat:
	.string "졌다...!\n"
	.string "이길 거라고 생각했는데...!$"
	// まけた……!ｎ
	// かてると おもったのに……!

Route116_Text_JosePostBattle:
	.string "벌레포켓몬은 진화가 빨라서\n"
	.string "강해지는 것도 빨라!$"
	// むしポケモンは しんかが はやいからｎ
	// つよく なるのも はやい!

Route116_Text_JaniceIntro:
	.string "내 귀여운 포켓몬의 강함을\n"
	.string "천천히 알려줄게!$"
	// わたしの かわいい ポケモンの つよさｎ
	// じっくりと おしえて あげるわ!

Route116_Text_JaniceDefeat:
	.string "네가 한 수 위구나...$"
	// キミの ほうが いちまい うわてね……

Route116_Text_JanicePostBattle:
	.string "귀여움과 강함을 겸비한 포켓몬\n"
	.string "그게 내가 추구하는 이상이야!$"
	// かわいさと つよさを かねそなえた ポケモンｎ
	// それが わたしの りそうなの!

Route116_Text_JerryIntro:
	.string "트레이너스쿨에서\n"
	.string "많은 걸 공부했으니까\l"
	.string "실전에서 확인해 볼 거야!$"
	// トレ-ナ-ズ スク-ルでｎ
	// いろいろ べんきょう したからねｌ
	// じっせんで たしかめるよ!

Route116_Text_JerryDefeat:
	.string "공부는 안 하고 게으름을 피워서\n"
	.string "져버렸다$"
	// べんきょう さぼってたからｎ
	// まけちゃったよ

Route116_Text_JerryPostBattle:
	.string "트레이너스쿨에서\n"
	.string "다시 제대로 공부하지 않으면\l"
	.string "원규님에게 혼날 거야$"
	// トレ-ナ-ズ スク-ルでｎ
	// もういちど べんきょう しなおさなきゃｌ
	// ツツジさんに おこられちゃうよ

Route116_Text_JerryRegister1:
	.string "포켓내비에 트레이너를\n"
	.string "등록할 수 있다고\l"
	.string "트레이너스쿨에서 배웠어!\p"
	.string "잘 모르겠으니까 해보자!$"
	// ポケナビには トレ-ナ-がｎ
	// とうろく できるん だってｌ
	// トレ-ナ-ズ スク-ルで ならったんだ!ｐ
	// よく わからないから やってみてよ!

Route116_Text_JerryRegister2:
	.string "포켓내비에 트레이너를\n"
	.string "등록할 수 있다고\l"
	.string "트레이너스쿨에서 배웠어!\p"
	.string "잘 모르겠으니까 해보자!$"
	// ポケナビには トレ-ナ-がｎ
	// とうろく できるん だってｌ
	// トレ-ナ-ズ スク-ルで ならったんだ!ｐ
	// よく わからないから やってみてよ!

Route116_Text_JerryRematchIntro:
	.string "그 이후로 트레이너스쿨에서\n"
	.string "열심히 공부했으니까\l"
	.string "지난번처럼 지지는 않을 거야!$"
	// あれから トレ-ナ-ズ スク-ルでｎ
	// まじめに べんきょう したからねｌ
	// このまえ みたいに まけたりしないよ!

Route116_Text_JerryRematchDefeat:
	.string "어라-?\n"
	.string "분명히 제대로 공부했는데$"
	// あれ-?ｎ
	// きちんと べんきょう したのに

Route116_Text_JerryPostRematch:
	.string "트레이너스쿨에서\n"
	.string "다시 제대로 공부하지 않으면\l"
	.string "원규님에게 혼날 거야$"
	// トレ-ナ-ズ スク-ルでｎ
	// もういちど べんきょう しなおさなきゃｌ
	// ツツジさんに おこられちゃうよ

Route116_Text_KarenIntro:
	.string "학교에서도 공부\n"
	.string "하굣길에서도 공부!$"
	// スク-ルでも べんきょうｎ
	// かえりみち でも べんきょうよ!

Route116_Text_KarenDefeat:
	.string "쇼크야\n"
	.string "져버리다니$"
	// ショックｎ
	// まけちゃったよ

Route116_Text_KarenPostBattle:
	.string "으아앙! 이래서는 원규님 같은\n"
	.string "엘레강트한 트레이너가 될 수 없어!$"
	// ああん! これじゃ ツツジさまのようにｎ
	// エレガントな トレ-ナ-に なれないわ!

Route116_Text_KarenRegister1:
	.string "와! 그거 포켓내비구나!\n"
	.string "나도 있으니까 등록해줘!$"
	// あ-っ それ ポケナビね!ｎ
	// あたしも もってるから とうろくして!

Route116_Text_KarenRegister2:
	.string "와! 그거 포켓내비구나!\n"
	.string "나도 있으니까 등록해줘!$"
	// あ-っ それ ポケナビね!ｎあたしも もってるから とうろくして!

Route116_Text_KarenRematchIntro:
	.string "그 후로 엄청나게 공부했어!\n"
	.string "그 성과를 보여줄게!$"
	// あれから ものすっごく べんきょう したの!ｎ
	// その せいか みてもらうからね!

Route116_Text_KarenRematchDefeat:
	.string "쇼크야\n"
	.string "또 져버리다니$"
	// ショックｎ
	// また まけちゃったよ

Route116_Text_KarenPostRematch:
	.string "원규님을 이긴 적이 있다고?\n"
	.string "그럼 지금의 나는 널 이길 수 없겠네$"
	// ツツジさまに かったことが あるの?ｎ
	// それじゃ いまの あたしには かてないわ

Route116_Text_SarahIntro:
	.string "저는 여태까지\n"
	.string "다른 사람에게 뭔가로\l"
	.string "져 본 적이 없어요!$"
	// わたくし いままでｎ
	// ひとに なにかで まけた ことってｌ
	// ありませんの!

Route116_Text_SarahDefeat:
	.string "어머\n"
	.string "이런 건 처음이에요!$"
	// まあｎ
	// こんなの はじめてですわ!

Route116_Text_SarahPostBattle:
	.string "남부럽지 않게 살고 있지만\n"
	.string "포켓몬에 대해서만큼은\l"
	.string "생각대로 안 되는군요$"
	// なにふじゆう ない くらし ですけどｎ
	// ポケモンの ことだけはｌ
	// おもいどおりに なりません のね

Route116_Text_DawsonIntro:
	.string "내 포켓몬의\n"
	.string "아름다운 털에 넋을 잃어서\l"
	.string "너는 아무것도 못 할걸!$"
	// ぼくの ポケモンのｎ
	// うつくしい けなみに みとれてｌ
	// キミは なにも できない!

Route116_Text_DawsonDefeat:
	.string "이건 아니지 베이비$"
	// そりゃないぜ ベイビ-

Route116_Text_DawsonPostBattle:
	.string "아앗\n"
	.string "포켓몬의 털과\l"
	.string "내 머리가 엉망이야!\l"
	.string "미용실에 예약해야겠어$"
	// ああっｎ
	// ポケモンの けなみとｌ
	// ぼくの ヘア-が みだれた!ｌ
	// びよういん よやく しなきゃ

Route116_Text_DevanIntro:
	.string "쾅 하고 가볼까!$"
	// ガツンと いってみようかあ!

Route116_Text_DevanDefeat:
	.string "아아아\n"
	.string "이거 상대가 안 되는구만$"
	// あああｎ
	// しょうぶに ならんな こりゃ

Route116_Text_DevanPostBattle:
	.string "가끔은 다른 타입\n"
	.string "포켓몬도 잡아볼까?$"
	// たまには ほかの タイプのｎ
	// ポケモンも つかって みるかなあ?

Route116_Text_JohnsonIntro:
	.string "이 앞은 막다른 길이야\n"
	.string "심심하니까 승부해줘$"
	// この さきって いきどまりなんだｎ
	// つまんない から しょうぶ してね

Route116_Text_JohnsonDefeat:
	.string "졌지만 재미있었어!$"
	// まけた けど おもしろかったよ!

Route116_Text_JohnsonPostBattle:
	.string "져버렸으니까\n"
	.string "내 반바지 빌려 입어도 돼!$"
	// まけちゃった からｎ
	// ぼくの たんパン かしてあげても い-よ!

Route117_Text_IsaacIntro:
	.string "내가 키우고 있는 포켓몬과\n"
	.string "승부해 주지 않겠어?$"
	// オレが そだてている ポケモンとｎ
	// しょうぶ してくれないか?

Route117_Text_IsaacDefeat:
	.string "훌륭하게 키우고 있군...$"
	// みごとに そだててるね……

Route117_Text_IsaacPostBattle:
	.string "강함이 포켓몬의 전부가 아니야!\n"
	.string "포켓몬의 개성을 갈고닦는 것도\l"
	.string "즐거움의 하나지!$"
	// つよさ だけが ポケモンじゃないよ!ｎ
	// ポケモンの こせいを みがきあげるのもｌ
	// たのしみかたの ひとつ だね!

Route117_Text_IsaacRegister:
	.string "좋-았어 더욱더 열심히 키워야지!\n"
	.string "너 더 키우면 보러와 줄 거지?$"
	// よ-し ますます がんばって そだてるぞ!ｎ
	// きみ そしたら みにきて くれるだろ?

Route117_Text_IsaacRematchIntro:
	.string "내가 키우고 있는 포켓몬은\n"
	.string "변함없이 좋은 느낌이야!$"
	// オレが そだてている ポケモンｎ
	// あいかわらず いい かんじ だよ!

Route117_Text_IsaacRematchDefeat:
	.string "잘 키우고 있구나...\n"
	.string "네겐 브리더의 재능이 있을지도 몰라$"
	// いい そだてかた してるね……ｎ
	// きみには そだてやの さいのう あるかも

Route117_Text_IsaacPostRematch:
	.string "아주 잘 자라고 있네!\n"
	.string "해안시티의 포켓몬 콘테스트에\l"
	.string "참가하는 걸 추천할게!$"
	// いい ぐあいに そだってるね!ｎ
	// ミナモシティの ポケモンコンテストにｌ
	// でることを おすすめ するよ!

Route117_Text_LydiaIntro:
	.string "포켓몬을 제대로 키우고 있는지\n"
	.string "제가 확인해 드릴게요$"
	// ポケモンを ちゃんと そだててるかｎ
	// わたしが たしかめて あげますね

Route117_Text_LydiaDefeat:
	.string "제대로 키우고 있군요$"
	// ちゃんと そだってますね

Route117_Text_LydiaPostBattle:
	.string "포켓몬의 개성에도 신경 쓰면서\n"
	.string "키워 보세요$"
	// ポケモンの こせいにも きをくばってｎ
	// そだてて みて くださいね

Route117_Text_LydiaRegister:
	.string "뛰어난 트레이너님을 만나서 다행이에요!\n"
	.string "다음에도 잘 부탁드릴게요$"
	// よい トレ-ナ-さんに あえて よかった!ｎ
	// これからも よろしく おねがいしますね

Route117_Text_LydiaRematchIntro:
	.string "포켓몬을 제대로 키우고 있는지\n"
	.string "제가 또 확인해 드릴게요$"
	// ポケモンを ちゃんと そだててるかｎ
	// また わたしが たしかめて あげますね

Route117_Text_LydiaRematchDefeat:
	.string "훌륭하게 자라고 있군요$"
	// みごとに そだってますね

Route117_Text_LydiaPostRematch:
	.string "포켓몬의 성격에 따라\n"
	.string "좋아하는 포켓몬스넥이 다른가봐요$"
	// ポケモンの せいかくに よってｎ
	// すきな ポロックが あるみたいなの

Route117_Text_DylanIntro:
	.string "한창 트라이애슬론 중이긴 하지만\n"
	.string "잠깐 승부하자고!$"
	// トライアスロンの まっさいちゅう だけどｎ
	// さくっと しょうぶ しようじゃ ないか!

Route117_Text_DylanDefeat:
	.string "체력이 떨어졌다!$"
	// たいりょく なくなった!

Route117_Text_DylanPostBattle:
	.string "큰일이군...\p"
	.string "방금 승부하는 사이에\n"
	.string "꼴등이 된 걸지도...?$"
	// まいったな……ｐ
	// いまの しょうぶの あいだにｎ
	// ビリに なっちゃったかも……?

Route117_Text_DylanRegister:
	.string "포켓몬도 강하게 키워야 하나?\n"
	.string "너 말야 날 훈련시켜 줘!$"
	// ポケモンも つよく なくちゃ ダメか?ｎ
	// きみさ たまに ぼくを きたえてよ!

Route117_Text_DylanRematchIntro:
	.string "한창 트라이애슬론 중이긴 하지만\n"
	.string "나한텐 여유가 있으니까\l"
	.string "잠깐 승부하자고!$"
	// トライアスロンの まっさいちゅう だけどｎ
	// ぼくには よゆうが あるからねｌ
	// さくっと しょうぶ しようじゃ ないか!

Route117_Text_DylanRematchDefeat:
	.string "또 체력이 떨어졌다!$"
	// また たいりょく なくなった!

Route117_Text_DylanPostRematch:
	.string "수영과 자전거는 최고로 잘하지만\n"
	.string "포켓몬 승부는 아직 자신이 없어$"
	// およぎと じてんしゃでは トップだったけどｎ
	// ポケモンは いまいち じしんが ないよ

Route117_Text_MariaIntro:
	.string "트라이애슬론 연습을\n"
	.string "포켓몬과 같이 하고 있으니까\l"
	.string "스피드에는 자신이 있어!$"
	// トライアスロンの れんしゅうｎ
	// ポケモンと いっしょに してるからさｌ
	// スピ-ドに じしん あるよ!

Route117_Text_MariaDefeat:
	.string "연습이 부족했나?$"
	// れんしゅうが たりなかったかな?

Route117_Text_MariaPostBattle:
	.string "연습은 계속해야\n"
	.string "의미가 있는 거야\p"
	.string "좋-아! 다시 연습해야지\n"
	.string "내일부터!$"
	// れんしゅうは つづけてこそｎ
	// いみが あるのよねｐ
	// よ-し! また れんしゅうよｎ
	// あしたから!

Route117_Text_MariaRegister:
	.string "너도 연습하고 있어?\n"
	.string "괜찮으면 내가 상대가 되어줄게!$"
	// あなたは れんしゅう してる?ｎ
	// よかったら わたしが あいてになるわ!

Route117_Text_MariaRematchIntro:
	.string "어때 연습 계속하고 있니?\n"
	.string "나는 물론 계속하고 있어\l"
	.string "그 증거를 보여줄게!$"
	// どう れんしゅう つづけてる?ｎ
	// あたしは もちろん つづけてるわｌ
	// その しょうこ みせちゃうから!

Route117_Text_MariaRematchDefeat:
	.string "연습이 부족했나?$"
	// れんしゅうが たりなかったかな?

Route117_Text_MariaPostRematch:
	.string "내일부터 또 연습할 거니까\n"
	.string "괜찮으면 다시 승부해줘!$"
	// あしたから また れんしゅう するからｎ
	// よかったら また しょうぶ してね!

Route117_Text_DerekIntro:
	.string "어렸을 땐 곤충채집소년!\n"
	.string "지금은 곤충마니아!\p"
	.string "하지만 포켓몬을 사랑하는 마음은\n"
	.string "여전히 그대로다!$"
	// むかしは むしとりしょうねん!ｎ
	// いまは こんちゅうマニア!ｐ
	// でも ポケモンを あいする きもちはｎ
	// ずっと かわらないぜ!

Route117_Text_DerekDefeat:
	.string "포켓몬이 약한 것도 여전하군...$"
	// ポケモンの よわさも かわらない……

Route117_Text_DerekPostBattle:
	.string "좋아하는 것만 하다 보니\n"
	.string "어느샌가 마니아라고 불리게 됐어!\p"
	.string "뭐 벌레포켓몬을 잘 알고 있으니\n"
	.string "마니아라고 불리는 게 당연하겠지!$"
	// すきな ことばかり していたらｎ
	// いつのまにか マニアって よばれてるよ!ｐ
	// まあ むしポケモンに くわしいからねｎ
	// マニアと よばれて とうぜん なのさっ!

Route117_Text_AnnaIntro:
	.string "미호: 귀여운 후배 앞이니까\n"
	.string "멋진 모습을 보여 줄 거야!$"
	// ミホ『かわいい コウハイの まえ だもんｎ
	// いいところ みせちゃうんだから!

Route117_Text_AnnaDefeat:
	.string "미호: 정말!\n"
	.string "후배 앞이니까 좀 이기게 해줘!$"
	// ミホ『もう!ｎ
	// コウハイの まえ だから かたせてよ!

Route117_Text_AnnaPostBattle:
	.string "미호: 네 포켓몬\n"
	.string "상당히 좋은 콤비인걸!\p"
	.string "그래 우리들\n"
	.string "다음으로 대단하지 않을까?$"
	// ミホ『あなたの ポケモンｎ
	// なかなかの コンビネ-ション してる!ｐ
	// そうね あたしたちのｎ
	// つぎ ぐらいに すごいんじゃない?

Route117_Text_AnnaAndMegRegister:
	.string "미호: 우리는 져버린 채로\n"
	.string "물러날 수 없어!\l"
	.string "또 와줄 거지?$"
	// ミホ『まけっぱなしではｎ
	// ひきさがれない わたしたち!ｌ
	// また きて くれるわよね?

Route117_Text_AnnaNotEnoughMons:
	.string "미호: 우리랑 승부하고 싶으면\n"
	.string "포켓몬을 2마리 데려와!$"
	// ミホ『あたしたちと しょうぶ したいならｎ
	// ポケモンを 2ひきは もってきてね!

Route117_Text_MegIntro:
	.string "리코: 멋진 선배랑 둘이서\n"
	.string "널 쓰러뜨릴 거야!$"
	// リコ『すてきな センパイとの タッグでｎ
	// あなたを まかしちゃうから!

Route117_Text_MegDefeat:
	.string "리코: 꺄-\n"
	.string "선배 죄송해요!$"
	// リコ『や-んｎ
	// センパイ ごめんなさい!

Route117_Text_MegPostBattle:
	.string "리코: 나는 선배에게\n"
	.string "방해만 됐던 거야...\p"
	.string "아니면 넌 이길 수 없었다고!$"
	// リコ『あたしが センパイのｎ
	// あしを ひっぱっちゃったの……ｐ
	// そうでなきゃ あんた かってないわよ!

Route117_Text_MegNotEnoughMons:
	.string "리코: 포켓몬이 한 마리밖에 없어?\n"
	.string "그럼 승부할 수 없겠네\p"
	.string "우리는 2대 2로\n"
	.string "승부를 즐기고 싶으니까!$"
	// リコ『ポケモン 1ぴき しか いないの?ｎ
	// じゃあ しょうぶは できないわねｐ
	// あたしたち 2たい2のｎ
	// しょうぶを たのしみたいの!

Route117_Text_AnnaRematchIntro:
	.string "미호: 후배 앞에서\n"
	.string "계속 지기만 할 수는 없지$"
	// ミホ『コウハイの まえでｎ
	// なんども まけてられないのよね

Route117_Text_AnnaRematchDefeat:
	.string "미호: 컨디션이 별로였어$"
	// ミホ『ちょうしが でなかったのよ

Route117_Text_AnnaPostRematch:
	.string "미호: 네 포켓몬\n"
	.string "상당히 좋은 콤비인걸!\p"
	.string "그래 우리들\n"
	.string "다음으로 대단하지 않을까?$"
	// ミホ『あなたの ポケモンｎ
	// なかなかの コンビネ-ションしてる!ｐ
	// そうね あたしたちのｎ
	// つぎ ぐらいに すごいんじゃない?

Route117_Text_AnnaRematchNotEnoughMons:
	.string "미호: 우리랑 승부하고 싶으면\n"
	.string "포켓몬을 2마리 데려와!$"
	// ミホ『あたしたちと しょうぶ したいならｎ
	// ポケモンを 2ひきは もってきてね!

Route117_Text_MegRematchIntro:
	.string "리코: 이번에야말로 선배랑 둘이서\n"
	.string "널 쓰러뜨리겠어!$"
	// リコ『センパイとの タッグでｎ
	// こんどこそ あなたを まかしちゃうから!

Route117_Text_MegRematchDefeat:
	.string "리코: 너무 강해$"
	// リコ『つよすぎるわ

Route117_Text_MegPostRematch:
	.string "리코: 선배랑 같이 배틀했는데도\n"
	.string "져버리다니... 우울해!$"
	// リコ『センパイと いっしょに たたかったのにｎ
	// まけるだなんて…… おちこんじゃう!

Route117_Text_MegRematchNotEnoughMons:
	.string "리코: 포켓몬이 한 마리밖에 없어?\n"
	.string "그럼 승부할 수 없어\p"
	.string "우리는 2대 2로\n"
	.string "승부를 즐기고 싶으니까!$"
	// リコ『ポケモン 1ぴき しか いないの?ｎ
	// じゃあ しょうぶは できないわねｐ
	// あたしたち 2たい2のｎ
	// しょうぶを たのしみたいの!

Route117_Text_MelinaIntro:
	.string "근사한 꽃을 보면서\n"
	.string "승부하는 건 참 좋아!$"
	// すてきな おはなを みながらｎ
	// しょうぶする なんて すてきよね!

Route117_Text_MelinaDefeat:
	.string "헤-에 좋은 느낌이네 너!$"
	// へ-え いいカンジね あんた!

Route117_Text_MelinaPostBattle:
	.string "꽃을 보면서 달리면\n"
	.string "정말 기분 좋아!$"
	// おはなを みながら はしるとｎ
	// きもちいいわよ!

Route117_Text_BrandiIntro:
	.string "에스퍼 타입의\n"
	.string "숨겨진 힘을 보여드리죠!$"
	// エスパ-ポケモンにｎ
	// ひめられた ちからを おみせするわ!

Route117_Text_BrandiDefeat:
	.string "놀랐어요$"
	// おどろいたわ

Route117_Text_BrandiPostBattle:
	.string "에스퍼 타입 포켓몬은 대단해요\n"
	.string "당신도 한번 잡아보세요$"
	// エスパ-ポケモンは おくが ふかいのｎ
	// あなたも つかまえて ごらんなさい

Route117_Text_AishaIntro:
	.string "오직 승리만 생각하면서 배틀하겠어!$"
	// かつこと だけを かんがえて たたかうわ!

Route117_Text_AishaDefeat:
	.string "져도 화내지 말자!\n"
	.string "그럴 시간이 있으면 특훈해야지$"
	// まけても くやしがったり しない!ｎ
	// そんなひまが あったら とっくんよ

Route117_Text_AishaPostBattle:
	.string "지는 거 아냐? 라고 걱정하면\n"
	.string "더 지는 걸 상상하게 돼$"
	// まけるかな?と しんぱい するとｎ
	// よけいに まけちゃうと おもうのよね

Route118_Text_RoseIntro:
	.string "꽃의 향기엔 신비한 힘이 있어\n"
	.string "몸도 마음도 깨끗해지지$"
	// はなの かおりは ふしぎな ちからｎ
	// からだも こころも きれいに なるわ

Route118_Text_RoseDefeat:
	.string "어머머\n"
	.string "져버렸네$"
	// あららｎ
	// まけちゃったわね

Route118_Text_RosePostBattle:
	.string "꽃도 포켓몬도\n"
	.string "좋은 향기가 나는 게 좋아!\l"
	.string "이상한 냄새가 나는 건... 별로야$"
	// はなも ポケモンもｎ
	// いい かおりの ものが だいすき!ｌ
	// クサイにおいは…… かんべんね

Route118_Text_RoseRegister:
	.string "어머 이 냄새는 포켓내비잖아\n"
	.string "부디 등록하게 해줘!$"
	// あら その においは ポケナビねｎ
	// ぜひとも とうろく しあいましょう!

Route118_Text_RoseRematchIntro:
	.string "좋은 향기에\n"
	.string "이끌려서 온 건가?$"
	// いい かおりに さそわれてｎ
	// いらしたのかしら?

Route118_Text_RoseRematchDefeat:
	.string "향기의 효과...\n"
	.string "그다지 없었네$"
	// においの こうか……ｎ
	// あんまり きかなかったわね

Route118_Text_RosePostRematch:
	.string "달콤한향기를 잘 쓰면\n"
	.string "포켓몬이 향기에 이끌려서 찾아와$"
	// あまいかおりを うまく つかうとｎ
	// ポケモンが さそわれて やってくるわね

Route118_Text_PerryIntro:
	.string "화려하게 드넓은 하늘을 나는\n"
	.string "새포켓몬이 최고라고!$"
	// かれいに おおぞらを まうｎ
	// とりポケモンが さいこう だぜ!

Route118_Text_PerryDefeat:
	.string "으으... 졌다...$"
	// うう…… まけた……

Route118_Text_PerryPostBattle:
	.string "너도 좋은 포켓몬을 가지고 있구나!\n"
	.string "나도 지지 않고 키울 거야!$"
	// きみも いい ポケモンを もってるね!ｎ
	// ぼくも まけずに そだてよっと!

Route118_Text_ChesterIntro:
	.string "날아올라라!\n"
	.string "나의 새포켓몬!$"
	// はばたけ!ｎ
	// おいらの とりポケモン!

Route118_Text_ChesterDefeat:
	.string "날아올랐지만...$"
	// はばたいたけど……

Route118_Text_ChesterPostBattle:
	.string "더 강해진다면\n"
	.string "자유롭게 날 수 있을 텐데 말야!$"
	// もっと つよくなるとｎ
	// じゆうに とべるように なるのにな!

Route118_Text_BarnyIntro:
	.string "난 낚시꾼이지만 트레이너이기도 하지\n"
	.string "낚은 포켓몬을 제대로 키우고 있단다!$"
	// あたしゃ つりびとだが トレ-ナ-でもあるｎ
	// つった ポケモン ちゃんと そだててるよ!

Route118_Text_BarnyDefeat:
	.string "제대로 키웠을 텐데...?$"
	// そだてたはず なんだが……?

Route118_Text_BarnyPostBattle:
	.string "낚시를 하면서\n"
	.string "포켓몬을 키웠지만 이길 수 없었다...\l"
	.string "둘 다 어중간한 실력인 건가!?$"
	// つりを しながらｎ
	// ポケモン そだてても かてなかった……ｌ
	// どっちも はんぱ だったのか!?

Route118_Text_WadeIntro:
	.string "낚시꾼에게 중요한 건 도구다!\n"
	.string "트레이너에게 중요한 건\l"
	.string "물론 포켓몬과 마음이지!$"
	// つりびとに だいじ なのは どうぐ!ｎ
	// トレ-ナ-に だいじ なのはｌ
	// もちろん ポケモンと ハ-トだな!

Route118_Text_WadeDefeat:
	.string "마음의 승부에서 진 건가?$"
	// ハ-トの しょうぶで まけたのか?

Route118_Text_WadePostBattle:
	.string "낚시라는 것도\n"
	.string "사람과 포켓몬의\l"
	.string "진검승부라고!$"
	// つり というのもｎ
	// ひとと ポケモンとのｌ
	// しんけん しょうぶ だな!

Route118_Text_DaltonIntro:
	.string "나의 멜로디를\n"
	.string "당신의 마음속 깊은 곳에 전하겠어$"
	// ぼくの メロディｎ
	// あなたの こころに とどけるよ

Route118_Text_DaltonDefeat:
	.string "라- 라라라-$"
	// ル- ルルル-

Route118_Text_DaltonPostBattle:
	.string "전자 기타는\n"
	.string "그냥 시끄럽기만 한 악기가 아냐...\p"
	.string "이렇게 마음속에 스며드는\n"
	.string "멜로디도 연주할 수 있지...$"
	// エレキギタ-ってｎ
	// ただ うるさい だけじゃ ないんだ……ｐ
	// こうして こころに しみるｎ
	// メロディも かなでられるのさ……

Route118_Text_DaltonRegister:
	.string "더 나은 멜로디를 만들면\n"
	.string "들으러 오라고!$"
	// もっと いい メロディが できたらｎ
	// ききにおいでよ!

Route118_Text_DaltonRematchIntro:
	.string "나와 포켓몬의 멜로디를\n"
	.string "당신의 마음속 깊은 곳에 전하겠어$"
	// ぼくと ポケモンの メロディｎ
	// あなたの こころに とどけるよ

Route118_Text_DaltonRematchDefeat:
	.string "라- 라라라-$"
	// ル- ルルル-

Route118_Text_DaltonPostRematch:
	.string "연주하고 있는 나의 마음이\n"
	.string "전자 기타를 통해서\l"
	.string "당신에게 전해질 거야...$"
	// ひいてるときの ぼくの きもちがｎ
	// エレキギタ-を とおしてｌ
	// あなたに とどく はずなのさ……

Route118_Text_DeandreIntro:
	.string "가라 가라-!\n"
	.string "내 포켓몬 1호 2호 3호!$"
	// いけいけ-!ｎ
	// ボクの ポケモン 1ごう 2ごう 3ごう!

Route118_Text_DeandreDefeat:
	.string "아아 괜찮아!?\n"
	.string "내 포켓몬 1호 2호 3호!$"
	// ああ だいじょうぶか!?ｎ
	// ボクの ポケモン 1ごう 2ごう 3ごう!

Route118_Text_DeandrePostBattle:
	.string "내 포켓몬 팀\n"
	.string "완전 멋있지-!\l"
	.string "따라해도 좋아!$"
	// ボクの ポケモン せんたいｎ
	// カッコいい だろ-!ｌ
	// まね しても い-ぜ-!$

Route119_Text_BrentIntro:
	.string "우리는 흉내내기서클!\n"
	.string "너의 움직임을 흉내내겠어!$"
	// ボクらは モノマネサ-クル!ｎ
	// キミの うごきを マネするよ!

Route119_Text_BrentDefeat:
	.string "우와아 졌다-앗!$"
	// うわあ まけた-っ!

Route119_Text_BrentPostBattle:
	.string "흉내내는 게 뭐가 즐겁냐니...\p"
	.string "후후후...\n"
	.string "넌 이해 못 할 거야$"
	// マネを して なにが たのしいか……ｐ
	// ふふふ……ｎ
	// キミには わからない だろうよ

Route119_Text_DonaldIntro:
	.string "드디어 만났구나!\n"
	.string "내 벌레포켓몬이 상대해 줄 거야!$"
	// ようやく であえたね!ｎ
	// ぼくの むしポケモンが あいて するよ!

Route119_Text_DonaldDefeat:
	.string "만나지 않았으면 좋았을 텐데...$"
	// であわなければ よかった……

Route119_Text_DonaldPostBattle:
	.string "좀 더 널 흉내내고 싶어!\n"
	.string "자 빨리 움직여 봐!$"
	// もっと キミの マネを したい!ｎ
	// ほら はやく うごいてよ!

Route119_Text_TaylorIntro:
	.string "네가 앞으로 가면\n"
	.string "우리도 앞으로 가고\p"
	.string "네가 오른쪽으로 꺾으면\n"
	.string "우리도 꺾는다...$"
	// きみが まえに すすんだらｎ
	// ぼくらも すすむｐ
	// きみが みぎへ まがればｎ
	// ぼくらも まがる……

Route119_Text_TaylorDefeat:
	.string "네가 이겨도\n"
	.string "나는 진다...$"
	// キミが かってもｎ
	// ぼくは まける……

Route119_Text_TaylorPostBattle:
	.string "으-음 승부의 승패만큼은\n"
	.string "흉내낼 수 없구나...\l"
	.string "왠지 분한걸...$"
	// う-ん しょうぶの しょうはい だけはｎ
	// マネ できないよなあ……ｌ
	// なんか くやしい……

Route119_Text_DougIntro:
	.string "드디어 날 잡았구나!\n"
	.string "아니면 도망가려고 했던 건가?$"
	// やっと ボクを つかまえられたね!ｎ
	// それとも にげようと していたのかな?

Route119_Text_DougDefeat:
	.string "훌륭한 배틀이었어!$"
	// すばらしい たたかい だったな!

Route119_Text_DougPostBattle:
	.string "우리들은 흉내내기서클!\n"
	.string "승부는 즐거웠니?$"
	// ボクらは モノマネサ-クル!ｎ
	// たのしんで もらえたかな?

Route119_Text_GregIntro:
	.string "내가 누군지 모르지?\p"
	.string "...뭐 나도 네가 누군지 모르니까\n"
	.string "이렇게 배틀하는 거지만!$"
	// ボクが だれなのか わからないだろう?ｐ
	// ……まあ ボクも キミのこと しらないからｎ
	// こうして たたかうんだけどね!

Route119_Text_GregDefeat:
	.string "꽤 강하잖아!$"
	// けっこう つよい じゃんか!

Route119_Text_GregPostBattle:
	.string "네가 어딘가로 갈 때까지\n"
	.string "우리들은 계속 흉내를 낼 거야!$"
	// キミが どこかに いくまでｎ
	// ボクらは マネを つづけるよ!

Route119_Text_KentIntro:
	.string "흉내내기를 좋아하는 사람들이\n"
	.string "모여서 만든 흉내내기서클!\p"
	.string "만난 그 순간부터\n"
	.string "승부가 시작된다!$"
	// モノマネ だいすきな ひとがｎ
	// あつまって つくった モノマネサ-クル!ｐ
	// であった そのときｎ
	// しょうぶが はじまる!

Route119_Text_KentDefeat:
	.string "졌습니다-앗!$"
	// まいりました-っ!

Route119_Text_KentPostBattle:
	.string "너도 흉내내기서클에 들어올래?$"
	// キミも モノマネサ-クルに はいらない?

Route119_Text_JacksonIntro:
	.string "서바이벌에 필요한\n"
	.string "지식과 기술을 지닌 자!\l"
	.string "그게 바로 포켓몬 레인저다!$"
	// サバイバルに ひつようなｎ
	// ちしきと ぎじゅつを もつ もの!ｌ
	// それが ポケモンレンジャ-さ!

Route119_Text_JacksonDefeat:
	.string "포켓몬에 대한 지식은 부족했다...$"
	// ポケモンの ちしきは たらなかった……

Route119_Text_JacksonPostBattle:
	.string "문명에서 벗어나\n"
	.string "인간의 야성을 깨운다!\l"
	.string "그것이 우리들의 테마다!$"
	// ぶんめい から はなれてｎ
	// にんげんの やせいを めざめさせる!ｌ
	// それが オレたちの テ-マさ!

Route119_Text_JacksonRegister:
	.string "내 지식이 부족해도 비웃지 말고\n"
	.string "다음에 다시 상대해 줘야 돼$"
	// ちしきぶそくと わらわずにｎ
	// こんど また あいてを してやってくれよな

Route119_Text_JacksonRematchIntro:
	.string "포켓몬과 함께 있음으로써\n"
	.string "야성을 되찾는 거다!$"
	// ポケモンと いることでｎ
	// やせいを とりもどすのさ!

Route119_Text_JacksonRematchDefeat:
	.string "여전히 강하군!$"
	// あいかわらず つよいな!

Route119_Text_JacksonPostRematch:
	.string "일단 포켓몬을 믿고!\n"
	.string "자신을 믿어라!\l"
	.string "그러면 길은 열린다!$"
	// とにかく ポケモンを しんじろ!ｎ
	// じぶんを しんじろ!ｌ
	// そうすれば みちは ひらける!

Route119_Text_CatherineIntro:
	.string "어머 너...\n"
	.string "모험을 하고 있는 것치곤\l"
	.string "상당히 가벼운 복장이네!$"
	// あら あなた……ｎ
	// ぼうけんを している わりにはｌ
	// ずいぶん みがるな かっこうね!

Route119_Text_CatherineDefeat:
	.string "준비 부족은 사고의 원인...$"
	// じゅんび ぶそくは じこの もと……

Route119_Text_CatherinePostBattle:
	.string "상당히 가벼운 복장이지만\n"
	.string "필요한 도구는 가지고 있고\l"
	.string "기력도 체력도 충분하네!$"
	// ずいぶん みがるな かっこう だけどｎ
	// ひつような どうぐは もってるしｌ
	// きりょく たいりょく じゅうぶんね!

Route119_Text_CatherineRegister:
	.string "트레이너의 필수품 포켓내비는\n"
	.string "제대로 가지고 있어?\p"
	.string "앗 가지고 있구나! 등록하자$"
	// トレ-ナ-の ひつじゅひん ポケナビはｎ
	// ちゃんと もってる?ｐ
	// あっ もってるわね! とうろくしましょ

Route119_Text_CatherineRematchIntro:
	.string "포켓몬과 함께하는 모험은\n"
	.string "잘 하고 있어?$"
	// ポケモンと いっしょの ぼうけんはｎ
	// うまく いってるかしら?

Route119_Text_CatherineRematchDefeat:
	.string "아직 뭔가가\n"
	.string "부족했나봐...$"
	// まだ なにかがｎ
	// たりなかったわね……

Route119_Text_CatherinePostRematch:
	.string "트레이너인 네가\n"
	.string "포켓몬에게 의지하고 있듯이\l"
	.string "포켓몬도 너를 의지하고 있어!$"
	// トレ-ナ-の あなたがｎ
	// ポケモンを たよって いるようにｌ
	// ポケモンも あなたを たよっているのよ!

Route119_Text_HughIntro:
	.string "드넓은 하늘은 남자의 로망!\p"
	.string "자유롭게 하늘을 나는 상쾌한 기분은\n"
	.string "그 무엇과도 바꿀 수 없지!$"
	// おおぞらは おとこの ロマン!ｐ
	// じゆうに そらを とぶ きもちよさはｎ
	// なにごとにも かえがたい!

Route119_Text_HughDefeat:
	.string "졌다아-앗!$"
	// まけた-っ!

Route119_Text_HughPostBattle:
	.string "하늘을 날아다니는 꿈은\n"
	.string "새포켓몬 덕분에 이룰 수 있었어!$"
	// そらを とびまわる ユメはｎ
	// とりポケモンの おかげで かなえられたよ!

Route119_Text_PhilIntro:
	.string "내 새포켓몬의 실력을\n"
	.string "보여주겠어!$"
	// ぼくの とりポケモンの じつりょくをｎ
	// みせて あげるよ!

Route119_Text_PhilDefeat:
	.string "실력 부족이었어...$"
	// じつりょく ぶそく だった……

Route119_Text_PhilPostBattle:
	.string "나는 어렸을 때부터\n"
	.string "새포켓몬을 동경하고 있었어!$"
	// ぼくは ちいさい ころからｎ
	// とりポケモンに あこがれて いたんだ!

Route119_Text_YasuIntro:
	.string "그림자에 숨고 어둠에서 살아간다\n"
	.string "그것이 나의 운명...!\l"
	.string "자 포켓몬 승부다!$"
	// かげに ひそみ やみに いきるｎ
	// それが オレの さだめ……!ｌ
	// いざ ポケモンしょうぶ!

Route119_Text_YasuDefeat:
	.string "졌다...!$"
	// まいった……!

Route119_Text_YasuPostBattle:
	.string "승부에서 패배한 자는\n"
	.string "미련 없이 그림자로 돌아간다...\l"
	.string "이 또한 운명...$"
	// しょうぶに やぶれた ものはｎ
	// いさぎよく かげに もどる……ｌ
	// それも さだめ……

Route119_Text_TakashiIntro:
	.string "방심하고 있으면\n"
	.string "따끔한 맛을 보게 될 것이다!$"
	// ゆだん してるとｎ
	// いたい めに あうぜ!

Route119_Text_TakashiDefeat:
	.string "강하구나 너-언!$"
	// つよいな きみ-っ!

Route119_Text_TakashiPostBattle:
	.string "기습 작전은 실패였다...$"
	// きしゅう さくせんは シッパイだった……

Route119_Text_HideoIntro:
	.string "나무를 숨길 거라면 숲이 최고!$"
	// きを かくすなら もりのなか!

Route119_Text_HideoDefeat:
	.string "상당한 실력이로군$"
	// つわもので ござるな

Route119_Text_HideoPostBattle:
	.string "나무를 숨길 거라면 숲!\n"
	.string "포켓몬을 숨길 거려면 포켓몬 굴!\p"
	.string "딱히 의미는 없소$"
	// きを かくすなら もりのなか!ｎ
	// ポケモンを かくすなら ポケモンのなか!ｐ
	// とくに いみは ないでござる

Route119_Text_ChrisIntro:
	.string "나한테 말을 걸었다는 건...\n"
	.string "나한테 승부를 걸겠다 이거지!?\p"
	.string "좋았어! 파도타기 하면서\n"
	.string "낚아 올린 포켓몬으로 승부하겠다!$"
	// わたしに はなしかけた……ｎ
	// つまり しょうぶを いどむ つもりだな!ｐ
	// よ-し! なみのり しながらｎ
	// つりあげた ポケモンで たたかうぞ!

Route119_Text_ChrisDefeat:
	.string "이길 수 있는 포인트를\n"
	.string "전혀 모르겠다!$"
	// かつための ポイントがｎ
	// ちっとも わからん!

Route119_Text_ChrisPostBattle:
	.string "파도타기를 쓴다!\p"
	.string "포켓몬의 등에 타고\n"
	.string "낚시를 즐긴다!\p"
	.string "이 얼마나 우아한 한때인가!$"
	// なみのりを つかう!ｐ
	// ポケモンの せなかに のってｎ
	// つりを たのしむ!ｐ
	// なんて ゆうがな ひととき だろう!

Route119_Text_FabianIntro:
	.string "오예오예오예오예\n"
	.string "이긴다-아 우리-이 이긴다-아$"
	// デケデケデケデケｎ
	// かつぜ-ヘ おれたち-ヒ かつぜ-ヘ

Route119_Text_FabianDefeat:
	.string "졌다-아 깔끔히-이 졌다-아$"
	// まけたぜ-ヘ あっさり-ヒ まけたぜ-ヘ

Route119_Text_FabianPostBattle:
	.string "오예오예오예오예\n"
	.string "다시느-은 나한테-에 말 걸지 마-아$"
	// デケデケデケデケｎ
	// にどと-ホ おれに-ヒ かまうなよ-ホ

Route119_Text_DaytonIntro:
	.string "하하하!\n"
	.string "꼬맹이 트레이너가 좋아!\l"
	.string "아저씨랑 배틀하자!$"
	// ホッホッホ-!ｎ
	// こども トレ-ナ-は だいすきだぞ!ｌ
	// おじちゃんと たたかおうっ!

Route119_Text_DaytonDefeat:
	.string "제법인데- 하하하!$"
	// やるな- ホッホッホ!

Route119_Text_DaytonPostBattle:
	.string "하하하!\n"
	.string "꼬맹이 트레이너의 기세를\l"
	.string "본받아서 아저씨도 열심히 할게!$"
	// ホッホッホ-!ｎ
	// こども トレ-ナ-の げんきをｌ
	// みならって おじちゃん がんばるぞ!

Route119_Text_RachelIntro:
	.string "언제 어디서나\n"
	.string "파라솔을 놓지 않을 거야!$"
	// いつでも どこでもｎ
	// パラソルを てばなさないの!

Route119_Text_RachelDefeat:
	.string "아잉 이런 건 싫어$"
	// いやん そんなあ

Route119_Text_RachelPostBattle:
	.string "파라솔이 안 무겁냐고?\n"
	.string "네 가방이 더\l"
	.string "무거워 보이는데 뭘$"
	// パラソルが おもく ないかって?ｎ
	// キミの バッグの ほうがｌ
	// いっぱい はいってるじゃない

Route120_Text_ColinIntro:
	.string "하늘을 날고 있는 포켓몬에게\n"
	.string "데미지를 줄 수 있는 기술이 있니?$"
	// そらを とんでいる ポケモンにｎ
	// ダメ-ジを あたえる ワザを もってる?

Route120_Text_ColinDefeat:
	.string "네가 나보다\n"
	.string "한 수 위였어!$"
	// キミの ほうがｎ
	// いちまい うわて だった!

Route120_Text_ColinPostBattle:
	.string "공중날기라는 기술은 편리하군!\p"
	.string "하늘을 날고 있는 동안에는\n"
	.string "대부분의 기술에 맞지 않는 거지?$"
	// そらをとぶ って ワザは べんりだな!ｐ
	// そらを とんでいる あいだはｎ
	// ほとんどの ワザが あたらないだろ?

Route120_Text_RobertIntro:
	.string "내 포켓몬은 강하다!\n"
	.string "네 포켓몬은 어떨까?$"
	// ボクの ポケモンは つよいぜ!ｎ
	// キミの ポケモンは どうかな?

Route120_Text_RobertDefeat:
	.string "네 포켓몬이\n"
	.string "더 강했다...!$"
	// キミの ポケモンの ほうがｎ
	// つよかった……!

Route120_Text_RobertPostBattle:
	.string "점점 강해지는 포켓몬은\n"
	.string "정말 믿음직스럽지-!$"
	// どんどん つよくなる ポケモンはｎ
	// ほんと たよりに なるよな-!

Route120_Text_RobertRegister:
	.string "너는 장래가 기대되는걸-!\n"
	.string "포켓내비에 등록해 두고 싶어!$"
	// キミって きたい できそうだな-!ｎ
	// ポケナビに とうろく しておきたい!

Route120_Text_RobertRematchIntro:
	.string "점점 강해지는 포켓몬은\n"
	.string "정말 믿음직스럽지-!$"
	// どんどん つよくなる ポケモンはｎ
	// ほんと たよりに なるよな-!

Route120_Text_RobertRematchDefeat:
	.string "네 포켓몬은\n"
	.string "정말 강하구나...$"
	// キミの ポケモンｎ
	// ほんとうに つよいんだな……

Route120_Text_RobertPostRematch:
	.string "포켓몬이 강해지면\n"
	.string "나도 함께 강해져야겠지-!$"
	// ポケモンが つよくなるのと いっしょにｎ
	// おれも つよくならないとな-!

Route120_Text_LorenzoIntro:
	.string "너의 포켓몬\n"
	.string "조난당하지는 않을지 봐 주겠어!$"
	// きみの ポケモンｎ
	// そうなん しないか みてあげよう!

Route120_Text_LorenzoDefeat:
	.string "그렇게 강한 포켓몬이 함께라면\n"
	.string "조난당할 걱정은 없겠군!$"
	// そんなに つよい ポケモンと いっしょならｎ
	// そうなんの おそれは ないな!

Route120_Text_LorenzoPostBattle:
	.string "포켓몬과 함께 어디든 갈 수 있다\n"
	.string "그게 바로 트레이너로서의 기쁨이지!$"
	// ポケモンと いっしょに どこまでもいくｎ
	// トレ-ナ-の よろこびと いえるだろう!

Route120_Text_JennaIntro:
	.string "네 체력은 어때?\n"
	.string "체력이 부족하면\l"
	.string "여차하는 순간에 곤란해져!$"
	// あなたの たいりょく どう?ｎ
	// たいりょく ぶそくだとｌ
	// いざと いうとき こまるわよ!

Route120_Text_JennaDefeat:
	.string "체력은 있었는데...$"
	// たいりょく だけは あったのに……

Route120_Text_JennaPostBattle:
	.string "체력 만들기가 내 일과야\n"
	.string "매일 포켓몬과 달리기를 하지!$"
	// たいりょく づくりが わたしの にっかｎ
	// まいにち ポケモンと ランニングよ!

Route120_Text_JeffreyIntro:
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "승부할래...?$"
	// …… …… ……ｎ
	// …… …… ……ｌ
	// しょうぶ する……?

Route120_Text_JeffreyDefeat:
	.string "...... ...... ......\n"
	.string "졌다...$"
	// …… …… ……ｎ
	// まけた……

Route120_Text_JeffreyPostBattle:
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "힘내야지...$"
	// …… …… ……ｎ
	// …… …… ……ｌ
	// がんばろう……

Route120_Text_JeffreyRegister:
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "포켓내비 있어...?$"
	// …… …… ……ｎ
	// …… …… ……ｌ
	// ポケナビ もってる……?

Route120_Text_JeffreyRematchIntro:
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "또 승부할래...?$"
	// …… …… ……ｎ
	// …… …… ……ｌ
	// また しょうぶ する……?

Route120_Text_JeffreyRematchDefeat:
	.string "...... ...... ......\n"
	.string "또 졌다...$"
	// …… …… ……ｎ
	// また まけた……

Route120_Text_JeffreyPostRematch:
	.string "...... ...... ......\n"
	.string "...... ...... ......\l"
	.string "또 힘내야지...\l"
	.string "소중한 벌레포켓몬을 위해서...$"
	// …… …… ……ｎ
	// …… …… ……ｌ
	// また がんばろう……ｌ
	// だいじな むしポケモンの ために……

Route120_Text_JenniferIntro:
	.string "포켓몬에게는 많은 특성이 있어\n"
	.string "그걸 잘 생각해야만\l"
	.string "일류 트레이너가 될 수 있는 거야!$"
	// ポケモンには いろんな とくせいが あるｎ
	// それを かんがえてこそｌ
	// いちりゅうの トレ-ナ-に なれるのよ!

Route120_Text_JenniferDefeat:
	.string "꽤 잘 생각하고 있구나$"
	// なかなか かんがえてるのね

Route120_Text_JenniferPostBattle:
	.string "그래 포켓몬의 특성에 따라\n"
	.string "전술도 많이 바뀌게 되지!$"
	// そう ポケモンの とくせいに よってｎ
	// たたかいかたも いろいろ かわってくるわ!

Route120_Text_ChipIntro:
	.string "자넨 뭐 하러 온 거지?\p"
	.string "혹시 설마 있을지도\n"
	.string "모른다고 하는\l"
	.string "고대의 유적을 찾으러 온 겐가!?$"
	// なんだね きみは?ｐ
	// もしかして ひょっとするとｎ
	// あるかもしれない といわれるｌ
	// こだいの いせきを さがしに きたのかね!?

Route120_Text_ChipDefeat:
	.string "이거 곤란하게 됐군$"
	// まいったね こりゃ

Route120_Text_ChipPostBattle:
	.string "난 저 커다란 바위가\n"
	.string "유적이라고 믿고 싶지만\l"
	.string "그러기엔 입구를 찾을 수가 없네...$"
	// あの おおきな いわｎ
	// わたしは いせき だと おもいたいがｌ
	// それにしては いりぐちが ないね……

Route120_Text_ClarissaIntro:
	.string "내가 파라솔을 가지고 있는 이유?\p"
	.string "우후후 날 이기면\n"
	.string "가르쳐 줄까?$"
	// あたしが パラソルを もってる りゆう?ｐ
	// うふふ あたしに かてたらｎ
	// おしえて あげても いいかな?

Route120_Text_ClarissaDefeat:
	.string "파라솔로 포켓몬의 공격은\n"
	.string "막을 수 없구나...$"
	// パラソルで ポケモンの こうげきはｎ
	// しのげないのね……

Route120_Text_ClarissaPostBattle:
	.string "내 포켓몬들도\n"
	.string "뜨거운 햇볕에 약하다고 생각해\l"
	.string "그래서 파라솔을 들고 있는 거야$"
	// あたしの ポケモンたちもｎ
	// あつい ひざしは にがてだと おもうのｌ
	// だから こうして パラソルを もってるのよ

Route120_Text_AngelicaIntro:
	.string "나와 포켓몬과 파라솔\n"
	.string "셋 중 하나만 없어도\l"
	.string "아름다움에 금이 가고 말지$"
	// あたしと ポケモンと パラソルｎ
	// どれか ひとつ かけていてもｌ
	// うつくしさが そこなわれるんだわ

Route120_Text_AngelicaDefeat:
	.string "지킨 아름다움이\n"
	.string "깨져버리고 말았어...$"
	// うつくしさがｎ
	// だいなしに なっちゃったわ

Route120_Text_AngelicaPostBattle:
	.string "당신에게 파라솔은 어울리지 않아!\p"
	.string "그야 이런 걸 들고 있으면\n"
	.string "배틀에 엄청 방해될 거 같거든$"
	// あなたに パラソルは にあわないわ!ｐ
	// だって こんなの もっていたらｎ
	// すっごく ジャマに なりそう なんだもの

Route120_Text_KeigoIntro:
	.string "포켓몬의 움직임을 접목시켜\n"
	.string "새로운 닌자 기술을 만들어 내겠어!$"
	// ポケモンの うごきを とりいれてｎ
	// あたらしい にんぽうを あみだすんだ!

Route120_Text_KeigoDefeat:
	.string "새로운 닌자 기술은\n"
	.string "완성까지 먼 것 같군$"
	// あたらしい にんぽうｎ
	// かんせいまで まだまだ かかりそうだ

Route120_Text_KeigoPostBattle:
	.string "닌자 스승을 찾아서\n"
	.string "제자로 들어가 볼까?$"
	// ニンジャの せんせいを さがしてｎ
	// でしいり しようかな?

Route120_Text_RileyIntro:
	.string "우리 닌자놀이의 위장술!\n"
	.string "어디 있는지 몰랐겠지!$"
	// ぼくたち ニンジャごっこの かくれぬの!ｎ
	// どこに いるのか わからなかっただろ!

Route120_Text_RileyDefeat:
	.string "졌다!\n"
	.string "위장술로 숨길 수 있나?$"
	// まけた!ｎ
	// かくれぬので かくれるか?

Route120_Text_RileyPostBattle:
	.string "우리 닌자놀이의 위장술!\n"
	.string "이건 직접 손으로 만들었다고!$"
	// ぼくたち ニンジャごっこの かくれぬの!ｎ
	// これって てづくり なんだぜ!

Route120_Text_CallieIntro:
	.string "방심하다간 다치게 될걸!$"
	// よそみ してると ケガするよ!

Route120_Text_CallieDefeat:
	.string "다친 건 내 쪽이었네$"
	// いたいめに あったのは あたしのほうか

Route120_Text_CalliePostBattle:
	.string "역시 진화시키지 말까?\n"
	.string "난 이 모습이 귀여워서 좋은데$"
	// やっぱり しんか させようかな?ｎ
	// このままでも かわいい けど

Route120_Text_LeonelIntro:
	.string "네가 가지고 있는 포켓몬\n"
	.string "타입은 다양해?$"
	// きみの てもち ポケモンｎ
	// いろんな タイプが そろって いるか?

Route120_Text_LeonelDefeat:
	.string "네 승부 방식 잘 봤어!$"
	// きみの こだわり みせてもらったよ!

Route120_Text_LeonelPostBattle:
	.string "좋아하는 포켓몬만 데리고 있어도\n"
	.string "강한 게 진짜 멋진 거지$"
	// すきな ポケモン だけでｎ
	// つよいって いうのが さいこうだね

Route121_Text_VanessaIntro:
	.string "너무너무 예쁜\n"
	.string "내 포켓몬을 귀여워해 줘!$"
	// あたしの とっても プリティなｎ
	// ポケモンを かわいがってよ!

Route121_Text_VanessaDefeat:
	.string "귀여워해 달랬잖아!$"
	// かわいがるの いみが ちがうわ!

Route121_Text_VanessaPostBattle:
	.string "해안시티의 콘테스트에 갈 거야\n"
	.string "내 포켓몬이라면\l"
	.string "마스터랭크도 문제없겠지!$"
	// ミナモの コンテストに いくのよｎ
	// あたしの ポケモンならｌ
	// マスタ- ランクでも らくしょうよ!

Route121_Text_WalterIntro:
	.string "세계 각국을\n"
	.string "포켓몬과 함께 여행해 왔지요\p"
	.string "조금은 실력에 자신이 있습니다!$"
	// せかい かっこくをｎ
	// ポケモンと いっしょに まわってきたｐ
	// すこしは うでに じしんが ありますよ!

Route121_Text_WalterDefeat:
	.string "훌륭합니다$"
	// おみごと ですな

Route121_Text_WalterPostBattle:
	.string "또 포켓몬과 함께\n"
	.string "세계를 여행하고 싶군요$"
	// また ポケモンと いっしょにｎ
	// せかいを まわってみたい ものです

Route121_Text_WalterRegister:
	.string "당신의 실력은 놀랍군요\n"
	.string "부디 기념으로 등록을...$"
	// あなたの うでまえは たいしたものだｎ
	// ぜひ きねんに とうろくを……

Route121_Text_WalterRematchIntro:
	.string "세계 각국을\n"
	.string "포켓몬과 함께 여행해 왔지요\p"
	.string "조금은 실력에 자신이 있습니다!$"
	// せかい かっこくをｎ
	// ポケモンと いっしょに まわってきたｐ
	// すこしは うでに じしんが ありますよ!

Route121_Text_WalterRematchDefeat:
	.string "정말 훌륭합니다!$"
	// おみごと ですな!

Route121_Text_WalterPostRematch:
	.string "당신과 그 포켓몬이라면\n"
	.string "외국에서도 강하다는 말을 들을 테죠!$"
	// あなたと その ポケモンならｎ
	// がいこくでも つよいと いわれるでしょう!

Route121_Text_TammyIntro:
	.string "세상에는 신비한 힘이\n"
	.string "많이 있어...$"
	// よの なかには ふしぎな ちからがｎ
	// いっぱい あるの……

Route121_Text_TammyDefeat:
	.string "나 진 거구나...$"
	// あたし まけたのね……

Route121_Text_TammyPostBattle:
	.string "송화산...\n"
	.string "그곳에 신비한 힘이 있어...$"
	// おくりびやま……ｎ
	// あそこに ふしぎな ちからが あるの……

Route121_Text_KateIntro:
	.string "마나: 둘이 모이면 무서울 게 없지!\n"
	.string "우리들의 강함을 보여 주겠어!$"
	// マナ『ふたり そろえば こわいもの なし!ｎ
	// あたしたちの つよさ みせつけちゃうから!

Route121_Text_KateDefeat:
	.string "마나: 후배 앞에서 이런 꼴을 당하다니...$"
	// マナ『コウハイの まえで かっこわるいわ……

Route121_Text_KatePostBattle:
	.string "마나: 나는 누군가가 의지하면\n"
	.string "나도 모르게 내 멋진 모습을\l"
	.string "더 보여주고 싶어져...$"
	// マナ『あたしって たよられちゃうとｎ
	// つい かっこいい ところｌ
	// みせたく なっちゃうのよね……

Route121_Text_KateNotEnoughMons:
	.string "마나: 포켓몬이 한 마리밖에 없구나\n"
	.string "그럼 승부할 수 없어!\p"
	.string "약자를 괴롭힐 수는 없으니까$"
	// マナ『ポケモン 1ぴき しか いないのねｎ
	// じゃあ しょうぶは できないわ!ｐ
	// だって よわいもの いじめに なるもの

Route121_Text_JoyIntro:
	.string "유이: 둘이 모이면 무서울 게 없지!\n"
	.string "우리들의 힘을 보여 주겠어!$"
	// ユイ『ふたり そろえば こわいもの なし!ｎ
	// あたしたちの つよさ みせつけちゃうから!

Route121_Text_JoyDefeat:
	.string "유이: 선배님 죄송합니다-!$"
	// ユイ『センパイ ごめんなさ-い

Route121_Text_JoyPostBattle:
	.string "유이: 에헷!\n"
	.string "또 선배님이랑 같이 특훈이다!$"
	// ユイ『えへっ!ｎ
	// また センパイと いっしょに とっくんね!

Route121_Text_JoyNotEnoughMons:
	.string "유이: 우리들에게 도전하려면\n"
	.string "포켓몬이 2마리는 필요하다고!$"
	// ユイ『あたしたちに しょうぶを いどむならｎ
	// ポケモン 2ひきは ひつよう だからね!

Route121_Text_JessicaIntro:
	.string "내 소중한 포켓몬을\n"
	.string "좀 봐 줘!$"
	// あたくしの だいじな ポケモンｎ
	// ちょっと みなさいよ!

Route121_Text_JessicaDefeat:
	.string "흥흥!\n"
	.string "뭐야 좀 봐주란 말이야!$"
	// ぷんぷん!ｎ
	// なによ ほんき だしちゃって!

Route121_Text_JessicaPostBattle:
	.string "사파리에서 새로운 포켓몬을\n"
	.string "잡아볼까?$"
	// サファリで あたらしい ポケモンｎ
	// つかまえようかな?

Route121_Text_JessicaRegister:
	.string "오늘은 봐준 거야\n"
	.string "다음에는 이렇게 안 될걸!$"
	// きょうは てかげん してあげたのよｎ
	// つぎは こうは いかないからね!

Route121_Text_JessicaRematchIntro:
	.string "내 소중한 포켓몬이 많이 성장했어!\n"
	.string "좀 보고 가라고!$"
	// だいじな ポケモン そだったのよ!ｎ
	// ちょっと みていきなさいよ!

Route121_Text_JessicaRematchDefeat:
	.string "흥흥!\n"
	.string "또 인정사정 안 봐주는구나!$"
	// ぷんぷん!ｎ
	// また てかげん してくれないのね!

Route121_Text_JessicaPostRematch:
	.string "사파리에서 새로운 포켓몬을\n"
	.string "잡아볼까?$"
	// サファリで あたらしい ポケモンｎ
	// つかまえようかな?

Route121_Text_CristinIntro:
	.string "하루에 5명씩\n"
	.string "쓰러뜨리는 게 일과야!\l"
	.string "네가 그 마지막이지!$"
	// 1にちに 5にんずつｎ
	// たおす ことが にっかよ!ｌ
	// あなたが その 5にんめ!

Route121_Text_CristinDefeat:
	.string "싫엇 너무해!$"
	// いやっ ひどいわ!

Route121_Text_CristinPostBattle:
	.string "이렇게 쉽게 질 줄이야...\n"
	.string "다음엔 내가 이길 거야!$"
	// こんなに あっさり まけるなんて……ｎ
	// つぎは わたしが かつから!

Route121_Text_CristinRegister:
	.string "굴욕적이야\n"
	.string "널 잊지 않도록...\l"
	.string "포켓내비 줘봐!$"
	// くつじょく てき だわ!ｎ
	// あなたの こと わすれないんだから……ｌ
	// ポケナビを かしなさい!

Route121_Text_CristinRematchIntro:
	.string "하루에 10명씩\n"
	.string "쓰러뜨리는 게 일과야!\l"
	.string "네가 그 마지막이지!$"
	// 1にちに 10にんずつｎ
	// たおす ことが にっかよ!ｌ
	// あなたが その 10にんめ!

Route121_Text_CristinRematchDefeat:
	.string "아니 야...\n"
	.string "너무해 다시 해 이거!$"
	// ちょっ……ｎ
	// ひどい やりなおしてよ!

Route121_Text_CristinPostRematch:
	.string "이 정도로 이기기 힘든 상대가 있다니...\n"
	.string "훌쩍 믿을 수 없어$"
	// こんなに かてない あいてが いるなんて……ｎ
	// グスっ しんじられない

Route121_Text_CaleIntro:
	.string "지금 물건이 너무 많단 말이지!\n"
	.string "이런데도 배틀하고 싶어?$"
	// いま にもつが いっぱい なんですけど!ｎ
	// こんな じょうたいで たたかえと?

Route121_Text_CaleDefeat:
	.string "당연히 질 수밖에 없지\n"
	.string "양손이 꽉 찼는데$"
	// そりゃ まけますよｎ
	// りょうてが ふさがってるんだもん

Route121_Text_CalePostBattle:
	.string "이 앞의 해안백화점에서\n"
	.string "물건을 너무 많이 샀어!\l"
	.string "너처럼 가방이 있으면 좋을 텐데$"
	// この さきの ミナモデパ-トでｎ
	// かいもの しすぎたんだ!ｌ
	// きみの みたいな バッグが ほしいな

Route121_Text_MylesIntro:
	.string "다른 사람이 키운 포켓몬을\n"
	.string "보고 싶어--엇!$"
	// みんなの そだてた ポケモンがｎ
	// みてみた--い!

Route121_Text_MylesDefeat:
	.string "굉--장해!$"
	// すご--い!

Route121_Text_MylesPostBattle:
	.string "너의 포켓몬! 좋은걸--!\n"
	.string "어떻게 키우고 있는 거야?$"
	// いいな--! きみの ポケモン!ｎ
	// どうやって そだてているの?

Route121_Text_PatIntro:
	.string "내가 키운 포켓몬들을\n"
	.string "모두에게 보여 주고 싶어!$"
	// わたしの そだてた ポケモンたちｎ
	// みんなに みてほしいの!

Route121_Text_PatDefeat:
	.string "굉장하다아!$"
	// すごいなァ!

Route121_Text_PatPostBattle:
	.string "어떤 포켓몬이든 나는 똑같이\n"
	.string "사랑으로 키워!$"
	// どんな ポケモンでも おなじようにｎ
	// かわいがって そだてているの!

Route121_Text_MarcelIntro:
	.string "내 포켓몬은 진 적이 없어!\n"
	.string "이번에도 이기면 다음은 콘테스트다!$"
	// わたしの ポケモンは まけしらず!ｎ
	// こんど かったら つぎは コンテストだ!

Route121_Text_MarcelDefeat:
	.string "앗 무슨 일이 일어난 거지?$"
	// あっと どうしたことだ?

Route121_Text_MarcelPostBattle:
	.string "콘테스트에 참가하기 전에\n"
	.string "좀 더 훈련시켜야겠네$"
	// コンテストの まえにｎ
	// もうすこし きたえないと ダメかな

Route123_Text_WendyIntro:
	.string "당신의 실력이\n"
	.string "어느 정도인지...\l"
	.string "내가 확인해 줄게!$"
	// あなたの じつりょくがｎ
	// どれほどの ものか……ｌ
	// わたしが たしかめて あげる!

Route123_Text_WendyDefeat:
	.string "훌륭해...!$"
	// すばらしいわ……!

Route123_Text_WendyPostBattle:
	.string "날 이기다니...\n"
	.string "당신의 실력도 상당하구나!$"
	// わたしに かつなんて……ｎ
	// あなたの じつりょくも そうとうな もの!

Route123_Text_BraxtonIntro:
	.string "체육관의 배지를\n"
	.string "잔뜩 가지고 있나 보네!\p"
	.string "정말로 그만큼 강한지\n"
	.string "확인해 주겠어!$"
	// たくさん ジムの バッジをｎ
	// もっている みたいだね!ｐ
	// ほんとうに それだけの ちからが あるかｎ
	// たしかめさせて もらうよ!

Route123_Text_BraxtonDefeat:
	.string "확실히 강하긴 강하군!$"
	// たしかに ちからは ある!

Route123_Text_BraxtonPostBattle:
	.string "체육관 배지가 부끄럽지 않은\n"
	.string "배틀이었어!$"
	// ジムバッジに はじないｎ
	// たたかい だったよ!

Route123_Text_VioletIntro:
	.string "즐거운 일이 있을 때는\n"
	.string "좋은 냄새로 가득 차$"
	// たのしい ことが あるとき ってｎ
	// いい においで いっぱいに なってるのね

Route123_Text_VioletDefeat:
	.string "아아\n"
	.string "슬픈 냄새야...$"
	// あぁｎ
	// かなしみの におい だわ……

Route123_Text_VioletPostBattle:
	.string "나무열매 명인의 꽃밭은\n"
	.string "엄청나게 좋은 냄새로 가득해!$"
	// きのみ めいじんの はなばたけｎ
	// すっごく いいかんじの においで いっぱい!

Route123_Text_CameronIntro:
	.string "초능력은 마음의 힘...\p"
	.string "그래 나는 누구에게도 지지 않겠다고\n"
	.string "마음먹고 있으니까 강한 거야!$"
	// サイキックとは きもちの つよさ……ｐ
	// そう ぼくは だれにも まけないとｎ
	// おもっているから つよいよ!

Route123_Text_CameronDefeat:
	.string "히잉...$"
	// しょんぼり……

Route123_Text_CameronPostBattle:
	.string "초능력은 마음의 힘\n"
	.string "네겐 지지 않겠다고 마음먹었는데...$"
	// サイキックとは きもちの つよさｎ
	// きみには まけないと おもっていたのに……

Route123_Text_CameronRegister:
	.string "난 알 수 있어!\n"
	.string "난 너와 또 승부하게 돼!\l"
	.string "이길 수 있을진 모르겠지만...\p"
	.string "포켓내비 빌려줘!$"
	// ぼくには わかる!ｎ
	// ぼくと きみとは また しょうぶする!ｌ
	// かてるか わかんない けど……ｐ
	// ポケナビを だして!

Route123_Text_CameronRematchIntro:
	.string "나는 이제 누구에게도 지지 않겠다고\n"
	.string "마음먹고 있으니까 강한 거야!!$"
	// ぼくは もう だれにも まけないとｎ
	// おもっているから つよいよ!!

Route123_Text_CameronRematchDefeat:
	.string "히잉...$"
	// しょんぼり……

Route123_Text_CameronPostRematch:
	.string "송화산에서 수행이라도 할까\n"
	.string "이대론 계속 널 이길 수 없어$"
	// おくりびやまで しゅぎょうでも しようかなｎ
	// このままじゃ ずっと きみに かてないよ

Route123_Text_JackiIntro:
	.string "포켓몬도 초능력도\n"
	.string "쓸 수 있는 것만으로는 의미가 없어\l"
	.string "단련해야 진짜가 되는 거야$"
	// ポケモンも ちょうのうりょくもｎ
	// つかえるだけじゃ いみ ないわｌ
	// きたえてこそ ほんものに なるのよ

Route123_Text_JackiDefeat:
	.string "굉장해!$"
	// すごい!

Route123_Text_JackiPostBattle:
	.string "누구나 초능력을 가지고 있어\n"
	.string "그저 쓰는 법을 잊어버린 것뿐이야$"
	// だれでも ちょうのうりょくを もっているのｎ
	// ただ つかいかたを わすれている だけよ

Route123_Text_JackiRegister:
	.string "다시 만났으면 좋겠다!\n"
	.string "너도 그렇지?$"
	// もういちど しょうぶして みたいわ!ｎ
	// いいでしょう?

Route123_Text_JackiRematchIntro:
	.string "어때? 당신 안의\n"
	.string "초능력 눈떴어?$"
	// どう? あなたの なかのｎ
	// ちょうのうりょく めばえたり した?

Route123_Text_JackiRematchDefeat:
	.string "굉장해!$"
	// すごいわ!

Route123_Text_JackiPostRematch:
	.string "당신의 강함\n"
	.string "그것도 초능력일 수 있어$"
	// あなたの つよさｎ
	// それも ちょうのうりょく かもね

Route123_Text_MiuIntro:
	.string "아영: 트레이너님의 포켓몬들\n"
	.string "져도 울지는 마세요!$"
	// ミウ『トレ-ナ-さんの ポケモンｎ
	// まけても なかないで くださいね!

Route123_Text_MiuDefeat:
	.string "아영: 져버렸네요...$"
	// ミウ『まけちゃったね……

Route123_Text_MiuPostBattle:
	.string "아영: 트레이너님의 포켓몬들은\n"
	.string "사이가 좋아서 강한 거군요!$"
	// ミウ『トレ-ナ-さんの ポケモンｎ
	// なかが いいから つよいんですね!

Route123_Text_MiuNotEnoughMons:
	.string "아영: 포켓몬이 두 마리는 있어야\n"
	.string "배틀을 해도 재미가 있지!$"
	// ミウ『ポケモンさん 2ひきは いないとｎ
	// たたかっても つまらないもん!

Route123_Text_YukiIntro:
	.string "희아: 좋-았어!\n"
	.string "트레이너님의 포켓몬을 해치우겠어요!$"
	// ユキ『よ-し!ｎ
	// トレ-ナ-さんの ポケモン やっつけます!

Route123_Text_YukiDefeat:
	.string "희아: 져버렸네요...$"
	// ユキ『まけちゃったね……

Route123_Text_YukiPostBattle:
	.string "희아: 왜- 그렇게 강한 거예요?\n"
	.string "우리들 승부에서 진 건 처음이에요!$"
	// ユキ『ど-して そんなに つよいの?ｎ
	// あたちたち たたかって まけたの はじめて!

Route123_Text_YukiNotEnoughMons:
	.string "희아: 포켓몬이 두 마리는 있어야\n"
	.string "승부를 해도 재미가 있죠!$"
	// ユキ『ポケモンさん 2ひきは いないとｎ
	// たたかっても つまらないもん!

Route123_Text_KindraIntro:
	.string "송화산은...\n"
	.string "포켓몬의 혼이 잠드는 곳...\l"
	.string "당신의 포켓몬도 잠들래?$"
	// おくりびやまは……ｎ
	// ポケモンの たましいが ねむるところ……ｌ
	// あなたの ポケモンも ねむる……?

Route123_Text_KindraDefeat:
	.string "아주 건강하네...$"
	// げんき いっぱいね……

Route123_Text_KindraPostBattle:
	.string "송화산은...\n"
	.string "포켓몬의 영혼이 잠드는 곳...\p"
	.string "분명 영혼을 달래는\n"
	.string "힘이 넘쳐흐르는 걸 거야...$"
	// おくりびやまは……ｎ
	// ポケモンの たましいが ねむるところ……ｐ
	// きっと たましいを なぐさめるｎ
	// ちからに あふれてるのよ……

Route123_Text_FernandoIntro:
	.string "한 곡 연주하는 사이에\n"
	.string "파바밧 쓰러뜨려 주지!$"
	// いっきょく かなでる あいだにｎ
	// パッと たおしちゃうゼ!

Route123_Text_FernandoDefeat:
	.string "이봐이봐 이제 막 시작했다고!$"
	// おいおい まだ イントロだゼ!

Route123_Text_FernandoPostBattle:
	.string "너 제법인걸\n"
	.string "너에 대한 곡을 만들어보고 싶어$"
	// きみ やるじゃんｎ
	// きみの きょくを つくって みたいよ

Route123_Text_FernandoRegister:
	.string "다음에 만났을 때에는\n"
	.string "완전한 곡을 들어 줘!$"
	// こんど あった ときにはｎ
	// フルコ-ラス きいて くれヨ!

Route123_Text_FernandoRematchIntro:
	.string "좋았어 오늘은 반드시!\n"
	.string "1절을 부르는 사이에\l"
	.string "파밧 쓰러뜨려 주지!$"
	// よし きょうこそ!ｎ
	// 1ばんを うたっている あいだにｌ
	// サッと たおしちゃうゼ!

Route123_Text_FernandoRematchDefeat:
	.string "이봐이봐 아직 후렴도 못 갔다고!$"
	// おいおい まだ サビまで いってないゼ!

Route123_Text_FernandoPostRematch:
	.string "내 곡에 홀려서\n"
	.string "질 거라고 생각했는데$"
	// オレの うたに ききほれてｎ
	// まけちゃう って おもってたんだけど

Route123_Text_DavisIntro:
	.string "내 형이 잡아준\n"
	.string "자랑스러운 벌레포켓몬이야!$"
	// ぼくの おにいちゃんに とってもらったｎ
	// じまんの むしポケモンだよ!

Route123_Text_DavisDefeat:
	.string "으-앙 이 바보-!$"
	// わ-ん バカ-っ!

Route123_Text_DavisPostBattle:
	.string "진 거\n"
	.string "우리 형한텐 비밀이야!$"
	// まけちゃった ことｎ
	// ぼくの おにいちゃんには ひみつ だよ!

Route123_Text_JazmynIntro:
	.string "딱 봐도 강한 트레이너인 당신을\n"
	.string "쓰러뜨리면 자신감이 생기겠지!$"
	// みるからに つよそうな あなたをｎ
	// たおせば じしんが つくわね!

Route123_Text_JazmynDefeat:
	.string "자신감이 없어져버렸어...$"
	// じしん なくしました……

Route123_Text_JazmynPostBattle:
	.string "사람을 외모로 판단하지 말라는데\n"
	.string "생긴 대로 노는 사람도 제법 있어$"
	// ヒトは みためには よらないと いうけどｎ
	// けっこう みためどおりの ことも あるわね

Route123_Text_FrederickIntro:
	.string "안녕 꼬마야\n"
	.string "할아버지랑 놀래?$"
	// おい きみきみｎ
	// じいちゃんと ちょっと あそぼうか

Route123_Text_FrederickDefeat:
	.string "강한 꼬마구나\n"
	.string "용돈 좀 줄까?$"
	// つよいこ じゃなｎ
	// こづかいを やるか

Route123_Text_FrederickPostBattle:
	.string "뭣 용돈 말이냐?\n"
	.string "상금으로 충분하잖니!$"
	// え こづかい?ｎ
	// しょうきんを もらったから いいじゃろ!

Route123_Text_AlbertoIntro:
	.string "난 새포켓몬이 정말 좋아!\n"
	.string "새 멋져! 새 최고!$"
	// オレ マジ とりポケモンが すき!ｎ
	// とりイカス! とりサイコ-!

Route123_Text_AlbertoDefeat:
	.string "졌지만 새포켓몬은 멋져!$"
	// まけた とりポケモンも イカス!

Route123_Text_AlbertoPostBattle:
	.string "승부 중에 떨어진\n"
	.string "새포켓몬의 깃털을 모아서\l"
	.string "모자를 만들어야지!$"
	// しょうぶの あいだに ちらばったｎ
	// とりポケモンの ハネを あつめてｌ
	// ぼうしを つくる つもりなんだ!

Route123_Text_EdIntro:
	.string "트레이너가 없을 때는\n"
	.string "내 포켓몬들끼리\l"
	.string "싸우는 걸 바라보고 있어$"
	// トレ-ナ-が いない ときはｎ
	// じぶんの ポケモンどうしをｌ
	// たたかわせて ながめて いるぞぅ

Route123_Text_EdDefeat:
	.string "네 포켓몬도 맘에 드네$"
	// きみの ポケモンも いいねぃ

Route123_Text_EdPostBattle:
	.string "헤헤헤 네 승부 방식을\n"
	.string "따라해야지!\l"
	.string "강해질 수 있을 것 같아$"
	// へへへ きみの たたかいかたのｎ
	// アイディア いただき!ｌ
	// つよく なれそう だよぅ

Route123_Text_JonasIntro:
	.string "숨어서 기다리고 있었더니\n"
	.string "트레이너가 걸렸소!$"
	// まちぶせ していたらｎ
	// トレ-ナ-が かかったで ござる!

Route123_Text_JonasDefeat:
	.string "져주지 않는다면\n"
	.string "닌자놀이를 할 수가 없소$"
	// まけて くれなきゃｎ
	// ニンジャごっこ できないよ

Route123_Text_JonasPostBattle:
	.string "다음에는 더 약한 트레이너를\n"
	.string "숨어서 기다려야겠소$"
	// つぎは もっと よわそうな トレ-ナ-をｎ
	// まちぶせ してみるで ござるよ

Route123_Text_KayleyIntro:
	.string "방금 막 구매한 이 파라솔로\n"
	.string "내 귀여움이 3배는 올라갔겠지!$"
	// かった ばかりの パラソルでｎ
	// わたしも 3わりましで かわいい はず!

Route123_Text_KayleyDefeat:
	.string "나보다 5배는 귀엽잖아!$"
	// わたしの 5ばい くらい つよいわね

Route123_Text_KayleyPostBattle:
	.string "도구 사용도 꾸미기의 비결이야!$"
	// こもの づかいも おしゃれの ひけつよ!

Route124_Text_SpencerIntro:
	.string "오 길을 잃은 건가?\p"
	.string "내 포켓몬을 이기면\n"
	.string "물길을 안내해줄 수도 있다고?$"
	// おっと みちに まよったのか?ｐ
	// わたしの ポケモンに かてたらｎ
	// みずさき あんないにんに なってあげようか?

Route124_Text_SpencerDefeat:
	.string "싸우는 감각을 잃어버렸다...$"
	// たたかいかたを まよってしまった……

Route124_Text_SpencerPostBattle:
	.string "바다에서 길을 잃는 사람은 많지!\p"
	.string "그런 사람은 포켓내비로\n"
	.string "맵을 확인하면서 움직이는 편이 좋아!$"
	// うみで まよってしまう ひとは おおい!ｐ
	// そんな ひとは ポケナビでｎ
	// マップを たしかめながら すすむと いい!

Route124_Text_RolandIntro:
	.string "흥! 스스로 헤엄치지 않고\n"
	.string "포켓몬에 타고 있다니...\p"
	.string "완전 부러운데!$"
	// むっ! じぶんで およがずにｎ
	// ポケモンに のっている……ｐ
	// なんて うらやましいんだ!

Route124_Text_RolandDefeat:
	.string "아아!\n"
	.string "틀렸어...!$"
	// ああ!ｎ
	// ダメだ……!

Route124_Text_RolandPostBattle:
	.string "몸이 차가워지기 시작했어...\n"
	.string "오랫동안 물속에 있어서 그런가\p"
	.string "너처럼 포켓몬에 타고 싶다$"
	// からだが ひえてきた……ｎ
	// ながいこと みずの なかに いるからだｐ
	// きみのように ポケモンに のりたいよ

Route124_Text_JennyIntro:
	.string "이렇게 바다에 떠 있으면\n"
	.string "포켓몬들이 놀러 와!$"
	// こうして うみに うかんでいるとｎ
	// ポケモンたちが あそびに くるのよ!

Route124_Text_JennyDefeat:
	.string "아-아\n"
	.string "져버렸어...$"
	// あ-あｎ
	// まけちゃった……

Route124_Text_JennyPostBattle:
	.string "바다에서 헤엄치고 있으면\n"
	.string "습격해오는 포켓몬도 있고\l"
	.string "그냥 보고만 있는 포켓몬도 있어\p"
	.string "포켓몬에게도 개성이 있는 거지!$"
	// うみを およいでいるとｎ
	// おそってくる ポケモンとｌ
	// ただ みているだけの ポケモンが いるのｐ
	// ポケモンにも こせいが あるのね!

Route124_Text_JennyRegister:
	.string "왠지 모르겠지만\n"
	.string "포켓내비에 등록해 주면 좋겠어...$"
	// なんとなく だけどｎ
	// ポケナビ とうろく してもらおうかな……

Route124_Text_JennyRematchIntro:
	.string "이렇게 바다에 떠 있으면\n"
	.string "트레이너가 배틀을 걸어와!$"
	// こうして うみに うかんでいるとｎ
	// トレ-ナ-が いどんで くるのよね!

Route124_Text_JennyRematchDefeat:
	.string "이상하네\n"
	.string "또 져버렸어...$"
	// おかしいなあｎ
	// また まけちゃった……

Route124_Text_JennyPostRematch:
	.string "왠지 모르겠지만\n"
	.string "미궁의 대저택에 가보는 게 좋겠어...$"
	// なんとなく だけどｎ
	// カラクリやしきに いってみようかな……

Route124_Text_GraceIntro:
	.string "수영도 슬슬 질렸으니...\n"
	.string "나랑 승부하자!$"
	// およぐのにも あきた ところだし……ｎ
	// わたしと しょうぶ しようよ!

Route124_Text_GraceDefeat:
	.string "이렇게 강할 줄은\n"
	.string "전혀 예상도 못 했어!$"
	// こんなに つよいなんてｎ
	// おもいも しなかったわ!

Route124_Text_GracePostBattle:
	.string "꾸준히 열심히 해온 날들이\n"
	.string "너의 실력이 된 거구나...!$"
	// ずっと がんばって きたことがｎ
	// あなたの つよさなのね……!

Route124_Text_ChadIntro:
	.string "우후후후\n"
	.string "나는 잠수 전문 스위머다\l"
	.string "잠수는 나의 특기 중의 특기지!$"
	// うふふふふｎ
	// オレは モグリの スイマ-ｌ
	// もぐりは とくいちゅうの とくいだぜ!

Route124_Text_ChadDefeat:
	.string "꼬륵꼬륵꼬륵...\n"
	.string "가라앉는다...$"
	// ゴボゴボゴボ……ｎ
	// しずんでいく……

Route124_Text_ChadPostBattle:
	.string "바닷속으로 잠수할 수 있는 포인트가\n"
	.string "이 근처에 있는 것 같다!\l"
	.string "잠수 전문가의 피가 끓어오르는군...$"
	// うみの そこに もぐれる ポイントがｎ
	// この あたりには あるらしいぜ!ｌ
	// モグリの ちが さわぐなあ……

Route124_Text_LilaIntro:
	.string "나미: 하-아\p"
	.string "모처럼 바다에 왔는데\n"
	.string "동생이랑 같이 있다니...\p"
	.string "너 기분 전환할 겸 포켓몬 승부할래!?$"
	// カコ『は-あｐ
	// せっかくの うみ なのにｎ
	// いっしょに いるのが おとうと なんて……ｐ
	// あなた きばらしに ポケモン しようか!?

Route124_Text_LilaDefeat:
	.string "나미: 홍이 때문에 졌잖아!\n"
	.string "나중에 혼날 줄 알아!!$"
	// カコ『コウの せいで まけたのよ!ｎ
	// あとで おしおき だかんね!!

Route124_Text_LilaPostBattle:
	.string "나미: 하-아\p"
	.string "옆에 있는 게 동생이 아니라\n"
	.string "멋진 남자친구라면 좋을 텐데...$"
	// カコ『は-あｐ
	// となりに いるのが おとうと じゃなくてｎ
	// すてきな かれし だったら いいのに……

Route124_Text_LilaNotEnoughMons:
	.string "나미: 우리랑 승부할 거야?\n"
	.string "포켓몬 2마리가 없으면 안 돼$"
	// カコ『あたしたちと たたかう つもり?ｎ
	// ポケモン 2ひき いないと ダメよ

Route124_Text_RoyIntro:
	.string "홍이: 우리 누나는\n"
	.string "포켓몬 승부에 엄청 강해!\l"
	.string "지고 나서 엉엉 울지 말라고!$"
	// コウ『オレの ねえちゃんｎ
	// ポケモン つよいぞ!ｌ
	// まけて ないたり するなよ!

Route124_Text_RoyDefeat:
	.string "홍이: 으아앙...\n"
	.string "나중에 누나한테 혼날 거야...$"
	// コウ『うわぁ……ｎ
	// あとで ねえちゃんに おこられる……

Route124_Text_RoyPostBattle:
	.string "홍이: 우리 누나는\n"
	.string "화나면 엄청 무서워...\p"
	.string "그래서 남자친구가 없어...$"
	// コウ『オレの ねえちゃんｎ
	// おこると むちゃくちゃ こわいんだ……ｐ
	// だから こいびと いないんだぜ……

Route124_Text_LilaRoyRegister:
	.string "홍이: 다음에 또 승부해 줘\n"
	.string "...그때는 봐줘야 돼!$"
	// コウ『また こんど しょうぶしてよｎ
	// ……そのときは てかげんして くれよ!

Route124_Text_RoyNotEnoughMons:
	.string "홍이: 우리랑 승부하려고?\n"
	.string "그럼 포켓몬을 2마리 데려와!$"
	// コウ『オレらと たたかう つもり?ｎ
	// ポケモン 2ひき つれてきなよ!

Route124_Text_LilaRematchIntro:
	.string "나미: 하-아\p"
	.string "모처럼 바다에 왔는데\n"
	.string "동생이랑 같이 있다니...\p"
	.string "어머? 너 오랜만이다?\n"
	.string "기분 전환으로 포켓몬 승부할래!?$"
	// カコ『は-あｐ
	// せっかくの うみ なのにｎ
	// いっしょに いるのが おとうと なんて……ｐ
	// あら あなた ひさしぶりねｎ
	// きばらしに ポケモン しようか!?

Route124_Text_LilaRematchDefeat:
	.string "나미: 홍이 너!\n"
	.string "너 때문에 또 졌잖아!\l"
	.string "넌 오늘부터 특훈이야!!$"
	// カコ『コウったら!ｎ
	// あんたの せいで また まけたでしょ!ｌ
	// あとで とっくん だかんね!!

Route124_Text_LilaPostRematch:
	.string "나미: 하-아\p"
	.string "나한테 멋진 남자친구가 있었으면\n"
	.string "멋진 콤비네이션으로\l"
	.string "어떤 상대라도 이길 수 있을 텐데$"
	// カコ『は-あｐ
	// あたしに すてきな かれしが いたらなぁｎ
	// すてきな コンビネ-ションでｌ
	// どんな あいてにでも かっちゃうのに

Route124_Text_LilaRematchNotEnoughMons:
	.string "나미: 우리랑 승부할 거야?\n"
	.string "포켓몬 2마리가 없으면 안 돼$"
	// カコ『あたしたちと たたかう つもり?ｎ
	// ポケモン 2ひき いないと ダメよ

Route124_Text_RoyRematchIntro:
	.string "홍이: 지면 내가 혼나니까\n"
	.string "완전 진심으로 할 거야!$"
	// コウ『まけたら オレが おこられるからｎ
	// むちゃくちゃ ほんきで がんばるぞ!

Route124_Text_RoyRematchDefeat:
	.string "홍이: 으아앙...\n"
	.string "또 누나한테 혼날 거야...$"
	// コウ『うわぁ……ｎ
	// また ねえちゃんに おこられる……

Route124_Text_RoyPostRematch:
	.string "홍이: 우리 누나는\n"
	.string "화나면 엄청 무서워...\p"
	.string "이제 내일부터 나는 누나랑\n"
	.string "포켓몬 맹훈련이야...$"
	// コウ『オレの ねえちゃんｎ
	// おこると むちゃくちゃ こわいんだ……ｐ
	// あとで オレと ポケモンｎ
	// もうとっくん だよ……

Route124_Text_RoyRematchNotEnoughMons:
	.string "홍이: 우리랑 승부하려고?\n"
	.string "그럼 포켓몬을 2마리 데려와!$"
	// コウ『オレらと たたかう つもり?ｎ
	// ポケモン 2ひき つれてきなよ!

Route124_Text_DeclanIntro:
	.string "이렇게 예쁜 바다에서\n"
	.string "홀로 수영하고 있는 나!\l"
	.string "솔직히 너무 외로워!$"
	// こんな きれいな うみでｎ
	// ひとりで およいでいる オレ!ｌ
	// はっきりいって かなしすぎます!

Route124_Text_DeclanDefeat:
	.string "슬프다\n"
	.string "하늘이 파란 게 슬퍼$"
	// かなしいｎ
	// そらの あおさが かなしい

Route124_Text_DeclanPostBattle:
	.string "비키니 아가씨를 꼬셔서\n"
	.string "수영하는 모습을 뽐내볼까?$"
	// ビキニのおねえさんを さそってｎ
	// えんえいと しゃれこんで みようかな?

Route124_Text_IsabellaIntro:
	.string "파도타기 트레이너에겐 안 질 거야!$"
	// なみのりトレ-ナ- なんかに まけないわ!

Route124_Text_IsabellaDefeat:
	.string "으흑 뚝뚝\n"
	.string "이 이건 땀이야! 운 거 아니거든!$"
	// ううっ ポタポタｎ
	// こ これは すいてきよ! ないてないわよ!

Route124_Text_IsabellaPostBattle:
	.string "색이 이쁜 조각을\n"
	.string "이 주변에서 찾을 수 있을 거야$"
	// きれいな いろの カケラがｎ
	// この あたりで みつかることが あるわよ

Route125_Text_NolenIntro:
	.string "네가 오는 소리를 듣고\n"
	.string "기다리고 있었어!$"
	// キミが やってくる おとがｎ
	// きこえて いたから まってたよ!

Route125_Text_NolenDefeat:
	.string "내 패배야...!$"
	// まいりました……!

Route125_Text_NolenPostBattle:
	.string "소리가 전달되는 속도는\n"
	.string "공기 중에서보다\l"
	.string "수중에서 더 빨라!$"
	// くうきちゅう よりもｎ
	// すいちゅうの ほうが おとの つたわるｌ
	// スピ-ドが はやいんだよ!

Route125_Text_StanIntro:
	.string "이야-압!\n"
	.string "내 귀여운 포켓몬이다-!!$"
	// おら-っ!!ｎ
	// おれの かわいい ポケモンだ-!!

Route125_Text_StanDefeat:
	.string "큰일이군...!$"
	// まいったぜ……!

Route125_Text_StanPostBattle:
	.string "쏘드라의 매력에 빠져서\n"
	.string "나도 헤엄치게 되었다-!$"
	// タッツ-の みりょくに まいってｎ
	// おれも およぐように なったんだ-!

Route125_Text_TanyaIntro:
	.string "수영하다가 지쳐버렸어!\n"
	.string "나랑 한번 승부 어때?$"
	// およぎ つかれちゃった!ｎ
	// わたしと ひとしょうぶ どう?

Route125_Text_TanyaDefeat:
	.string "넌 너무 강해!$"
	// あんた つよすぎ!

Route125_Text_TanyaPostBattle:
	.string "후우... 후우...\n"
	.string "이끼시티는 어느 쪽이었지?$"
	// ふう ふう……ｎ
	// トクサネシティは どっち だったっけ?

Route125_Text_SharonIntro:
	.string "내가 키운 물포켓몬과\n"
	.string "승부해 볼래?$"
	// わたしの そだてた みずポケモンとｎ
	// たたかって みない?

Route125_Text_SharonDefeat:
	.string "졌다...$"
	// まけた……

Route125_Text_SharonPostBattle:
	.string "넌 진짜 강하구나!\n"
	.string "깜짝 놀랐어!$"
	// あなたの つよさは ホンモノね!ｎ
	// おどろいたわ!

Route125_Text_ErnestIntro:
	.string "나는야 듬직한 선원!\n"
	.string "전 세계의 바다를 건너는 남자지!$"
	// オレさまは たくましい ふなのり!ｎ
	// せかいの うみを わたりあるく おとこ!

Route125_Text_ErnestDefeat:
	.string "크아아악-!\n"
	.string "이길 수 없다...!$"
	// ぐおおお-っ!ｎ
	// かてねえ……!

Route125_Text_ErnestPostBattle:
	.string "여울의 동굴은 시간에 따라\n"
	.string "바닷물이 차고 빠지는 걸 반복한다!\p"
	.string "참고로 밀물에서 썰물까지\n"
	.string "약 6시간이 걸린다고! 알고 있었나?$"
	// あさせのほらあな は じかんによってｎ
	// しおが みちたり ひいたり するんだ!ｐ
	// ちなみに みちしお から ひきしお までｎ
	// およそ 6じかんだぞ! しっていたか?

Route125_Text_ErnestRegister:
	.string "포켓내비에 등록해 주면\n"
	.string "좋은 걸 가르쳐 주마!$"
	// ポケナビ とうろく して くれたらｎ
	// いいことを おしえて やるよ!

Route125_Text_ErnestRematchIntro:
	.string "오! 여기서 100년을 기다렸다고!\n"
	.string "일단 무조건 포켓몬 승부다!$"
	// おっと ここで あったが 100ねんめ!ｎ
	// とにかく ポケモンしょうぶ だっ!

Route125_Text_ErnestRematchDefeat:
	.string "이길 수 없어\n"
	.string "절대 이길 수가 없다!$"
	// かてねえｎ
	// ちっとも かてねえよ!

Route125_Text_ErnestRematchPostBattle:
	.string "여울의 동굴...\p"
	.string "바닷물의 밀물 썰물에 따라\n"
	.string "갈 수 있는 곳과\l"
	.string "갈 수 없는 곳이 있다\p"
	.string "참고로 밀물에서 썰물까지\n"
	.string "약 6시간이 걸린다고! 기억해둬!$"
	// あさせのほらあな……ｐ
	// しおの みちひきに よってｎ
	// いけたり いけなかったり するｌ
	// ばしょが あるんだよなｐ
	// ちなみに みちしお から ひきしお までｎ
	// およそ 6じかんだぞ! おぼえておけよ!

Route125_Text_KimIntro:
	.string "매희: 여울의 동굴에\n"
	.string "이상한 할아버지가 있대!\l"
	.string "너도 만나러 가는 중이니?$"
	// マホ『あさせのほらあなにｎ
	// へんな じいさんが いるんだって!ｌ
	// あなたも あいにいく とちゅう?

Route125_Text_KimDefeat:
	.string "매희: 이길 수 있다고 생각했는데$"
	// マホ『かてると おもったのに

Route125_Text_KimPostBattle:
	.string "매희: 여울의 동굴에\n"
	.string "이상한 할아버지가 있는 거지?\p"
	.string "자 나호야 빨리 만나러 가자!$"
	// マホ『あさせのほらあなにｎ
	// へんな じいさんが いるんでしょ?ｐ
	// さっ ナホちゃん あいに いくよ!

Route125_Text_KimNotEnoughMons:
	.string "매희: 안 된다니까!\n"
	.string "포켓몬이 2마리 없으면 안 된다고!$"
	// マホ『ダメだって!ｎ
	// ポケモン 2ひき いないと ダメだって!

Route125_Text_IrisIntro:
	.string "나호: 선배님\n"
	.string "이런 곳에 뭐가 있다는 거죠?$"
	// ナホ『センパイｎ
	// こんな ところに なにが あるんですかぁ?

Route125_Text_IrisDefeat:
	.string "나호: 도중에 역전할 수 있었는데$"
	// ナホ『とちゅう おしいところ あったのに

Route125_Text_IrisPostBattle:
	.string "나호: 선배... 정말로\n"
	.string "여울의 동굴에 들어가려고요?\l"
	.string "옷이 다 젖을 텐데요?$"
	// ナホ『センパイ…… ほんとにｎ
	// あさせのほらあなに はいりますぅ?ｌ
	// ぬれちゃいますよぉ?

Route125_Text_IrisNotEnoughMons:
	.string "나호: 2대 1로 승부하다니\n"
	.string "우리들은 그런 짓 할 수 없어$"
	// ナホ『2たい1で しょうぶ なんてｎ
	// そんな まね あたしたちに できないわ

Route125_Text_PresleyIntro:
	.string "새 조련사인 내가\n"
	.string "왜 바다에 있냐면...$"
	// とりつかいの ボクがｎ
	// なぜ うみにまで きているかと いうと……

Route125_Text_PresleyDefeat:
	.string "알았어\n"
	.string "왜 여기에 있는지 알려 줄게$"
	// わかったｎ
	// なんで ここに いるか おしえてやるよ

Route125_Text_PresleyPostBattle:
	.string "편지를 병에 넣어서\n"
	.string "방금 바다에 던졌거든!\p"
	.string "분명 귀여운 비키니 걸이\n"
	.string "주워줬을 거야!!$"
	// あきビンに メ-ルを いれてｎ
	// さっき うみに ながしたんだ!ｐ
	// きっと かわいい ビキニの おんなのコがｎ
	// ひろって くれるぜ!

Route125_Text_AuronIntro:
	.string "이보게-!\n"
	.string "바다에 쓰레기를 버린 건 자네인가?$"
	// こら-ッ! おぬしかッｎ
	// うみに ゴミを すてたのは!

Route125_Text_AuronDefeat:
	.string "자네가 아니었던 건가$"
	// おぬしでは なかったか

Route125_Text_AuronPostBattle:
	.string "방금 이 근처에서\n"
	.string "더러운 병을 주웠다네!\l"
	.string "바다에 쓰레기를 버리다니 괘씸한 것!$"
	// さっき この あたりでｎ
	// こきたない ビンを ひろったんじゃ!ｌ
	// うみに ゴミを すてるとは なっとらん!

Route126_Text_BarryIntro:
	.string "수영은 전신 운동!\n"
	.string "체력을 늘어난다고-!$"
	// すいえいは ぜんしん うんどう!ｎ
	// たいりょくが つくぞ-!

Route126_Text_BarryDefeat:
	.string "졌습니다-앗!$"
	// まけました-っ!

Route126_Text_BarryPostBattle:
	.string "보아라! 이 근육을!!\n"
	.string "매일 헤엄치고 있는 덕분이다!$"
	// まいにち およいでる おかげでｎ
	// みよ! この きんにくっ!!

Route126_Text_DeanIntro:
	.string "여기 솟아 있는 하얀 바위산이\n"
	.string "바로 루네시티다-!$"
	// この しろく そびえる いわやまがｎ
	// ルネシティ なんだぜ-!

Route126_Text_DeanDefeat:
	.string "당한 건가!?$"
	// やられたか!?

Route126_Text_DeanPostBattle:
	.string "루네시티의 입구를 못 찾겠다!\n"
	.string "어디 있는 거지?$"
	// ルネシティの いりぐちが みつからん!ｎ
	// どこに あるんだ?

Route126_Text_NikkiIntro:
	.string "오호호호홋\n"
	.string "나는 인어야!$"
	// おほほほっｎ
	// わたしは にんぎょ!

Route126_Text_NikkiDefeat:
	.string "거품이 되어 사라져 간다...\n"
	.string "보글보글보글...$"
	// アワと なって きえていく……ｎ
	// ぶくぶくぶく……

Route126_Text_NikkiPostBattle:
	.string "호되게 당했어...\n"
	.string "거품 속으로 도망치고 싶다...$"
	// こっぴどく やられちゃったわ……ｎ
	// アワくって にげだしたい きぶん……

Route126_Text_BrendaIntro:
	.string "저기 너 말이야\n"
	.string "나랑 승부하지 않을래?$"
	// ねえ ねえｎ
	// おねえさんと しょうぶ しない?

Route126_Text_BrendaDefeat:
	.string "안 돼-앵!$"
	// いや-んっ!

Route126_Text_BrendaPostBattle:
	.string "이렇게 포켓몬과\n"
	.string "바다에서 노는 게 제일 좋아!$"
	// こうして ポケモンとｎ
	// うみで あそぶのが だいすきなの!

Route126_Text_PabloIntro:
	.string "태권왕보다 더 딴딴한\n"
	.string "이 근육질 몸을 봐라!$"
	// からておう より たくましいｎ
	// この にくたいびを みよ!

Route126_Text_PabloDefeat:
	.string "오옷 강하잖아\n"
	.string "좋아 좋아!$"
	// おわっ つよいなｎ
	// いいね! いいね!

Route126_Text_PabloPostBattle:
	.string "패배가 좋은 자극이 됐다!\n"
	.string "몸도 포켓몬도 더 단련하겠어$"
	// まけて いい しげきに なったよ!ｎ
	// からだも ポケモンも もっと きたえるぜ

Route126_Text_PabloRegister:
	.string "이야- 대단한데!\n"
	.string "부디 친하게 지내줬으면 해!$"
	// いや- いいね!ｎ
	// ぜひとも おちかづきに なっておきたいね!

Route126_Text_PabloRematchIntro:
	.string "비키니 아가씨보다도 아름다운\n"
	.string "이 몸을 봐라!$"
	// ビキニのおねえさん より うつくしいｎ
	// この にくたいびを みよ!

Route126_Text_PabloRematchDefeat:
	.string "우왓 완전 강하잖아\n"
	.string "좋아 좋아!$"
	// おわっ ほんと つよいなｎ
	// いいね! いいね!

Route126_Text_PabloPostRematch:
	.string "좋아 더 열심히 단련하겠어!\n"
	.string "너는 좋은 자극이 되니까\l"
	.string "다음에 다시 와줘!$"
	// よし もっともっと きたえるぜ!ｎ
	// きみは いい しげきに なるからｌ
	// また きてくれよ!

Route126_Text_LeonardoIntro:
	.string "작년까지만 해도 수영은 못했는데\n"
	.string "지금은 수영팬티소년이 됐어\l"
	.string "지금은 뭐든지 할 수 있을 거 같아!$"
	// きょねん まで およげなかった オレもｎ
	// かいパンやろうに なれたんだｌ
	// いまなら なんでも できる きがする!

Route126_Text_LeonardoDefeat:
	.string "에헷 이래서 욕심내면 안 돼$"
	// てへっ よくばりすぎちゃ ダメだよな

Route126_Text_LeonardoPostBattle:
	.string "뭐든지 연습을 하면\n"
	.string "점점 잘하게 돼!\p"
	.string "너도 아직 어리니까\n"
	.string "다양한 경험을 해 봐!$"
	// なんでも れんしゅう すればｎ
	// うまく なるんだ!ｐ
	// キミも わかい うちからｎ
	// いろいろ やっておけよ!

Route126_Text_IsobelIntro:
	.string "바닷물이 코로 들어오면\n"
	.string "엄청 괴롭지?$"
	// はなに かいすいが はいるとｎ
	// すっごく つらいよね?

Route126_Text_IsobelDefeat:
	.string "아앗!\n"
	.string "부 분하다... 어푸!$"
	// ああっ!ｎ
	// く くやし……ごほッ!

Route126_Text_IsobelPostBattle:
	.string "바닷물을 조금 마셔버렸어...!\n"
	.string "짜- 너무 짜-!$"
	// かいすいを ちょっと のんじゃった……!ｎ
	// からい-ッ にがい-ッ!

Route126_Text_SiennaIntro:
	.string "나의 전력을 부딪쳐 주지!$"
	// わたしの ハ-トを ぶつけるわ!

Route126_Text_SiennaDefeat:
	.string "부딪쳐서 졌어!$"
	// ハ-トで まけたわ!

Route126_Text_SiennaPostBattle:
	.string "뜨거워지고 말았네\n"
	.string "잠깐 다이빙이나 해볼까$"
	// あつく なっちゃったｎ
	// ちょっと もぐって こようかな

Route127_Text_CamdenIntro:
	.string "나랑 승부하고 싶다고\n"
	.string "네 얼굴에 써 있다고!$"
	// オレと しょうぶ したいってｎ
	// かおに かいてあるぜ!

Route127_Text_CamdenDefeat:
	.string "으아아아아...$"
	// あわわわわ……

Route127_Text_CamdenPostBattle:
	.string "좋은 승부를 한 뒤에는\n"
	.string "시원한 기분이 들지-$"
	// いい しょうぶを した あとはｎ
	// すがすがしい きもちに なるな-

Route127_Text_DonnyIntro:
	.string "지고 싶지 않다고 생각하는\n"
	.string "라이벌이 너에게는 있니?$"
	// あいつには まけたくない ってｎ
	// ライバル きみには いるの?

Route127_Text_DonnyDefeat:
	.string "아아 무척 분해!$"
	// あぁ すっごく くやしい!

Route127_Text_DonnyPostBattle:
	.string "라이벌이 있으면\n"
	.string "강해지고 싶다는 기분이\l"
	.string "점점 넘쳐흐르지$"
	// ライバルが いるとｎ
	// つよくなりたい って きもちがｌ
	// どんどん あふれて くるよね

Route127_Text_JonahIntro:
	.string "낚시로 얻은\n"
	.string "온화한 마음...\l"
	.string "그 마음을 보여드리겠습니다...$"
	// つりを することで てにいれたｎ
	// おだやかな こころ……ｌ
	// それを みせて あげましょう……

Route127_Text_JonahDefeat:
	.string "...졌지만\n"
	.string "마음만은 온화합니다$"
	// …… まけてもｎ
	// こころは おだやかです

Route127_Text_JonahPostBattle:
	.string "낚이지 않아도 괜찮습니다\n"
	.string "계속 낚싯줄을 드리우고 있는 겁니다...$"
	// つれなくても かまいませんｎ
	// ずっと いとを たらしているのです……

Route127_Text_HenryIntro:
	.string "어이쿠!? 파도타기를 쓰고 있는\n"
	.string "포켓몬을 낚아 올리고 말았나?$"
	// おっと!? なみのり しているｎ
	// ポケモンを つりあげて しまったか?

Route127_Text_HenryDefeat:
	.string "이길 수가 없다!$"
	// かなわん!

Route127_Text_HenryPostBattle:
	.string "네 포켓몬은 강해 보이니\n"
	.string "낚아 올리면 아주 보람이 느껴지겠어!$"
	// きみの ポケモン つよそうだからｎ
	// つりあげたら かなりの てごたえ だろうな!

Route127_Text_RogerIntro:
	.string "좋-았어!\n"
	.string "포켓몬광과 낚시광의 대결이다!$"
	// よ-し!ｎ
	// ポケモンずきと つりずきの たいけつだ!

Route127_Text_RogerDefeat:
	.string "으악! 낚싯줄이 엉켰다!\n"
	.string "채비를 잘해둘 걸 그랬군!$"
	// わあ! いとが からまった!ｎ
	// まさに あとの まつり

Route127_Text_RogerPostBattle:
	.string "낚시에서 낚싯줄이 엉키는 걸\n"
	.string "채비 엉킴이라고 하지$"
	// つりでは いとが からまることをｎ
	// マツリ と いうんだよ

Route127_Text_AidanIntro:
	.string "새포켓몬은 눈이 엄청나게 좋다!\n"
	.string "드넓은 하늘에서 먹잇감을 찾아낸다고!$"
	// とりポケモンは すごく めが いい!ｎ
	// おおぞら たかくから えものを みつけるぜ!

Route127_Text_AidanDefeat:
	.string "후... 곤란한데$"
	// ふぅ…… まいったぜ

Route127_Text_AidanPostBattle:
	.string "잠수할 수 있을 것 같은 곳이\n"
	.string "이 주변엔 굉장히 많군!\p"
	.string "하늘에서 보면\n"
	.string "바다의 색이 달라서 잘 보인다!$"
	// この ちかくには いっぱいｎ
	// もぐれそうな ところが あるな!ｐ
	// そらから みてるとｎ
	// うみの いろが ちがうから よくわかる!

Route127_Text_KojiIntro:
	.string "맨발로 뛰고 있으면\n"
	.string "발바닥이 튼튼해져!$"
	// はだしで かけまわるとｎ
	// あしの うらが きたえられるぞ!

Route127_Text_KojiDefeat:
	.string "아야!\n"
	.string "발톱 사이에 조약돌이...$"
	// いってェ!ｎ
	// ツメの あいだに こいしが……

Route127_Text_KojiPostBattle:
	.string "맨발 최고!\n"
	.string "하지만 네 운동화도 좋아보이네!$"
	// はだし さいこう!ｎ
	// だが おまえの その ズックも いいな!

Route127_Text_KojiRegister:
	.string "날 이긴 녀석에겐 이거다-앗!\n"
	.string "다음 승부도 잘 부탁해!$"
	// おれに かったり するやつは こうだ-っ!ｎ
	// また よろしくおねがいします!

Route127_Text_KojiRematchIntro:
	.string "오늘도 맨발로 돌아다녀서\n"
	.string "내 발바닥은 완전 튼튼하다고!$"
	// きょうも はだしで かけまわってｎ
	// あしの うらを きたえまくりだ!

Route127_Text_KojiRematchDefeat:
	.string "아야!\n"
	.string "발바닥에 조약돌이...$"
	// いってェ!ｎ
	// つちふまずに ジャリが……

Route127_Text_KojiPostRematch:
	.string "잠깐 네 운동화하고\n"
	.string "내 맨발하고 교환하지 않을래?$"
	// しばらく おまえの ズックとｎ
	// おれの はだし こうかん してみないか?

Route127_Text_AthenaIntro:
	.string "느긋하고 차분하게 승부하자\n"
	.string "잘 부탁해!$"
	// じっくり ゆっくり しょうぶしましょうｎ
	// よろしくね!

Route127_Text_AthenaDefeat:
	.string "전략을 쓸 틈도 없었네$"
	// せんりゃくを ねる ひまも なかったわ

Route127_Text_AthenaPostBattle:
	.string "파란색으로 둘러싸여 있으면\n"
	.string "시간이 지나가는 걸\l"
	.string "느긋하게 느낄 수 있어$"
	// あおい いろに かこまれているとｎ
	// じかんが すぎるのがｌ
	// ゆっくりに かんじられる のよ

Route128_Text_IsaiahIntro:
	.string "그랜드시티까지는 아직 멀었죠...$"
	// サイユウシティは まだ とおい……

Route128_Text_IsaiahDefeat:
	.string "제 첫 승리도 아직 멀었군요...$"
	// ボクの はつしょうりも とおい……

Route128_Text_IsaiahPostBattle:
	.string "계속 지기만 하는 인생이지만\n"
	.string "절대로 포기하지 않을 겁니다...!$"
	// まけつづけている じんせい ですがｎ
	// けっして あきらめませんよ……!

Route128_Text_IsaiahRegister:
	.string "이런 저지만\n"
	.string "언젠가는 이길 수 있을 거 같아요!\l"
	.string "포켓내비에 등록해 주세요...!$"
	// こんな ボク ですけどｎ
	// いつかは かてると おもうんですｌ
	// ポケナビの とうろくを してください……!

Route128_Text_IsaiahRematchIntro:
	.string "아직 힘이 남아 있으니\n"
	.string "그랜드시티를 목표로 헤엄칠 겁니다!$"
	// まだまだ げんき ですからねｎ
	// サイユウシティ めざして およぎますよ!

Route128_Text_IsaiahRematchDefeat:
	.string "또 첫 승리를 얻지 못했다...$"
	// また はつしょうり ならず……

Route128_Text_IsaiahPostRematch:
	.string "포기하지 않으면 언젠가는 이길 수 있다\n"
	.string "그랜드시티에도 도착할 수 있어...!$"
	// あきらめなきゃ いつかは かてるｎ
	// サイユウシティにも たどりつく……!

Route128_Text_KatelynIntro:
	.string "트라이애슬론은\n"
	.string "수영 자전거 마라톤\p"
	.string "3개의 종목을 연이어 겨루는\n"
	.string "가혹한 레이스야!$"
	// トライアスロンはｎ
	// すいえい じてんしゃ マラソンｐ
	// 3つの しゅもくを つづけて こなすｎ
	// かこくな レ-スなの!

Route128_Text_KatelynDefeat:
	.string "포켓몬 승부도 가혹하네...$"
	// ポケモンしょうぶも かこく よね……

Route128_Text_KatelynPostBattle:
	.string "다음은 자전거 경주인데...\n"
	.string "마음이 꺾일 거 같아...$"
	// つぎは じてんしゃ だけど……ｎ
	// くじけそうだわ……

Route128_Text_KatelynRegister:
	.string "뭐 모처럼 만났으니까\n"
	.string "또 언젠가 승부하자!$"
	// まあ せっかく だしｎ
	// またいつか しょうぶを しましょうよ!

Route128_Text_KatelynRematchIntro:
	.string "트라이애슬론도 길지만\n"
	.string "포켓몬 챔피언을 노리는 것도\l"
	.string "먼 길이구나!$"
	// トライアスロンも ながいけどｎ
	// ポケモン チャンピオンを めざすのもｌ
	// ながい みちのり なのね!

Route128_Text_KatelynRematchDefeat:
	.string "정말\n"
	.string "포켓몬 승부는 가혹해...$"
	// ほんとっｎ
	// ポケモンしょうぶ って きびしい……

Route128_Text_KatelynPostRematch:
	.string "슬슬 챔피언 로드에\n"
	.string "도전해 보는 건 어때?$"
	// そろそろ チャンピオンロ-ドにｎ
	// ちょうせん してみるのも あり かな?

Route128_Text_AlexaIntro:
	.string "포켓몬리그에 도전하기 위해\n"
	.string "여태까지 노력해 왔어...\p"
	.string "여기서 질 수는 없다고!$"
	// ポケモンリ-グに ちょうせん するためｎ
	// いままで がんばって きた……ｐ
	// ここで まけるわけには いかないわ!

Route128_Text_AlexaDefeat:
	.string "아앗!\n"
	.string "이럴 수가!$"
	// ああっ!ｎ
	// なんてこと

Route128_Text_AlexaPostBattle:
	.string "여기까지 왔잖아\n"
	.string "한 번 졌다고 포기하지 않을 거야$"
	// ここまで きたんですものｎ
	// いちど まけたからって あきらめない

Route128_Text_RubenIntro:
	.string "나처럼 강한\n"
	.string "포켓몬 트레이너는 달리 없을 거다!$"
	// わたしの ように つよいｎ
	// ポケモントレ-ナ-は ほかに いない!

Route128_Text_RubenDefeat:
	.string "어떻게 된 거지...!$"
	// なんて ことだ……!

Route128_Text_RubenPostBattle:
	.string "너처럼 강한\n"
	.string "포켓몬 트레이너는 달리 없을 거다!$"
	// きみの ように つよいｎ
	// ポケモントレ-ナ-は ほかに いないだろう!

Route128_Text_WayneIntro:
	.string "그랜드시티에 가고 싶어서\n"
	.string "폭포오르기를 배운\l"
	.string "포켓몬을 낚았어!$"
	// サイユウに いってみたいからｎ
	// たきのぼりを おぼえたｌ
	// ポケモンを つりあげたんだよ!

Route128_Text_WayneDefeat:
	.string "그 기세는\n"
	.string "마치 폭포오르기 같아!$"
	// その いきおいｎ
	// まさに たきのぼり!

Route128_Text_WaynePostBattle:
	.string "큰일 났다!\p"
	.string "폭포오르기를 배운 포켓몬을 낚았지만\n"
	.string "루네시티의 체육관 배지가 없어!$"
	// しまった!ｐ
	// たきのぼりを おぼえた ポケモン つってもｎ
	// ルネの ジムバッジ もってない!

Route128_Text_HarrisonIntro:
	.string "너도 강해 보이네!\n"
	.string "나 이길 수 있을까?$"
	// きみが また つよそ-だもんね!ｎ
	// オレ かてっかな?

Route128_Text_HarrisonDefeat:
	.string "아이고\n"
	.string "역시 못 이기네$"
	// あっひゃｎ
	// やっぱ かてんわな

Route128_Text_HarrisonPostBattle:
	.string "그랜드시티 주변에는\n"
	.string "강한 트레이너가 많이 있어!\l"
	.string "너도 그곳으로 갈 거야?$"
	// サイユウシティの まわりはｎ
	// つよそ-な トレ-ナ-が いっぱいだぜ!ｌ
	// オレ ばちがいじゃ ないよな?

Route128_Text_CarleeIntro:
	.string "이 근처는 햇살이\n"
	.string "너무 강해!$"
	// この へんは ひざしがｎ
	// いちだんと つよいわねえ!

Route128_Text_CarleeDefeat:
	.string "눈부셔서 잘 안 보였어!$"
	// まぶしくて よく みえなかったの!

Route128_Text_CarleePostBattle:
	.string "슬슬 돌아가서\n"
	.string "자외선 차단제를 다시 발라야지$"
	// そろそろ もどってｎ
	// ひやけどめ ぬりなおさなきゃ

Route129_Text_ChaseIntro:
	.string "나는 초보 트라이애슬리트지\n"
	.string "첫 레이스에 긴장하고 있다!$"
	// オレは しょしんしゃ トライアスリ-トｎ
	// はじめての レ-スで きんちょう!

Route129_Text_ChaseDefeat:
	.string "으아-!\n"
	.string "져버렸다-앗!$"
	// うお-!ｎ
	// まけてしまった-っ!

Route129_Text_ChasePostBattle:
	.string "긴장하고 있으면\n"
	.string "제 실력을 발휘할 수 없어!$"
	// きんちょう していたらｎ
	// じつりょくが だせないよな!

Route129_Text_AllisonIntro:
	.string "트라이애슬론에 도전 중이지만...\n"
	.string "포켓몬 승부 한판 하자고!$"
	// トライアスロンの とちゅう だけど……ｎ
	// ポケモンしょうぶを しようよ!

Route129_Text_AllisonDefeat:
	.string "이길 줄 알았는데-!$"
	// かてると おもったのに-っ!

Route129_Text_AllisonPostBattle:
	.string "대자연을 상대로\n"
	.string "자신의 힘을 시험하는 것도\l"
	.string "트라이애슬론의 묘미지!$"
	// だいしぜんを あいてにｎ
	// じぶんの ちからを ためす こともｌ
	// トライアスロンの だいごみ!

Route129_Text_ReedIntro:
	.string "이봐 이봐!\n"
	.string "얼른 승부하자고!$"
	// ホラホラ!ｎ
	// とっとと しょうぶ しようぜ!

Route129_Text_ReedDefeat:
	.string "졌네 졌어\n"
	.string "얼른 끝내자고!$"
	// まけた まけたよｎ
	// とっとと おわろうぜ!

Route129_Text_ReedPostBattle:
	.string "졌으면 아무것도 없어\n"
	.string "얼른 집에 가야지!$"
	// まけたら なにも ないさｎ
	// とっとと かえると するか!

Route129_Text_TishaIntro:
	.string "느긋-하게 천-천히 할까요?$"
	// の-んびり の-んびり やりましょうか?

Route129_Text_TishaDefeat:
	.string "어머머\n"
	.string "더 느긋하게 하고 싶었는데$"
	// あららｎ
	// もっと のんびり したかったなあ

Route129_Text_TishaPostBattle:
	.string "서두르다가 실수하는 건 싫잖아요?\n"
	.string "느긋하게 하기로 했어요$"
	// あせって ミスを するのって イヤでしょ?ｎ
	// のんびり やることに してるのよ

Route129_Text_ClarenceIntro:
	.string "파도타기도 제법 어렵지?$"
	// なみのりも けっこう たいへんだろ?

Route129_Text_ClarenceDefeat:
	.string "이기는 건 어렵네$"
	// かつのって むずかしいなあ

Route129_Text_ClarencePostBattle:
	.string "포켓몬리그로 향하는 거야?\n"
	.string "힘내라 힘!$"
	// ポケモンリ-グを めざしてるのか?ｎ
	// がんばれ がんばれよ!

Route130_Text_RodneyIntro:
	.string "바다 한가운데에서\n"
	.string "트레이너를 만나다니 별일이 다 있군\l"
	.string "승부나 한판 해볼까!?$"
	// うみの ドまんなかでｎ
	// トレ-ナ-に であうとは めずらしいなｌ
	// イッパツ しょうぶ するか!?

Route130_Text_RodneyDefeat:
	.string "뭐 이렇게 강한 꼬마가...$"
	// なんて つよい こどもだ……

Route130_Text_RodneyPostBattle:
	.string "격렬한 배틀을 헤쳐 나온\n"
	.string "멋진 눈빛이다!$"
	// きびしい たたかいを くぐりぬけてきたｎ
	// いい めを しているぜ!

Route130_Text_KatieIntro:
	.string "파란 바다에\n"
	.string "블루한 마음이\l"
	.string "치유되는 것 같아...$"
	// あおい うみｎ
	// ブル-な こころｌ
	// いやされる……

Route130_Text_KatieDefeat:
	.string "바다가 넓듯\n"
	.string "포켓몬의 세계\l"
	.string "또한 넓디넓도다...$"
	// うみ ひろくｎ
	// ポケモン せかいｌ
	// また ひろし……

Route130_Text_KatiePostBattle:
	.string "어린이들은 모두\n"
	.string "포켓몬 챔피언을\l"
	.string "목표로 하고 있지...$"
	// こどもたちｎ
	// ポケモン チャンプｌ
	// めざしてる……

Route130_Text_SantiagoIntro:
	.string "아무것도 없는 바다에 떠있으면...\n"
	.string "기분이 너무 평화로워$"
	// なにも ない うみに うかんでると……ｎ
	// へいわだなあ-……

Route130_Text_SantiagoDefeat:
	.string "평화에 취해서 졌다!$"
	// へいわボケ してて まけました!

Route130_Text_SantiagoPostBattle:
	.string "수영도 하고 승부도 하고...\n"
	.string "난 행복한 사람이야-...$"
	// こうして およいだり しょうぶしたり……ｎ
	// オレ しあわせだなあ-……

Route131_Text_RichardIntro:
	.string "바다에는 포켓몬들이 잔뜩 있어서\n"
	.string "헤엄쳐서 건너기도 힘들어$"
	// うみには ポケモンが たくさん いるからねｎ
	// およいで わたるのも くろう するよ!

Route131_Text_RichardDefeat:
	.string "트레이너의 손으로 키운 포켓몬은\n"
	.string "정말 강하구나...$"
	// トレ-ナ-の そだてた ポケモンはｎ
	// ホントに つよいなぁ……

Route131_Text_RichardPostBattle:
	.string "허억허억... 지쳤어...\n"
	.string "올 때는 좋았지만 돌아가는 게 문제야...\l"
	.string "돌아갈 체력이 남아 있을까...$"
	// ひいひい…… つかれた……ｎ
	// いきは よいよい かえりは こわい……ｌ
	// かえりの たいりょく のこってるかなあ……

Route131_Text_HermanIntro:
	.string "바다 바다 바다...\n"
	.string "둘러봐도 온통 바다뿐...\l"
	.string "바다는 이제 질렸다고-!$"
	// うみ うみ うみ……ｎ
	// みわたす かぎり うみ……ｌ
	// うみは もう あきたぞ-っ!

Route131_Text_HermanDefeat:
	.string "히에에에에엑!$"
	// ひょえええええっ!

Route131_Text_HermanPostBattle:
	.string "바다에 질려도\n"
	.string "계속 헤엄칠 수밖에 없나\p"
	.string "이런 말을 하는 나도\n"
	.string "뿌리부터 스위머군...$"
	// うみに あきてもｎ
	// およぎ つづけるしか ないのかｐ
	// そんな オレはｎ
	// ねっからの スイマ-……

Route131_Text_SusieIntro:
	.string "잠깐 너\n"
	.string "나랑 승부하자!$"
	// ちょっと あんたｎ
	// わたしと しょうぶ しましょ!

Route131_Text_SusieDefeat:
	.string "겉보기와는 다르게\n"
	.string "강하네-!$"
	// みかけに よらずｎ
	// つよいわね-っ!

Route131_Text_SusiePostBattle:
	.string "저쪽에 바다는 질렸다고\n"
	.string "하는 남자 있지?\p"
	.string "그거 말만 그런 거야\n"
	.string "실은 바다가 좋아서 어쩔 줄 모르는 거라고!$"
	// あっちで うみは あきた とか いってるｎ
	// おとこが いるでしょ?ｐ
	// アレ くちだけ なのよｎ
	// ホントは うみが すきで しょうがないの!

Route131_Text_KaraIntro:
	.string "왜 남자들은\n"
	.string "비키니를 좋아하는 걸까!?\p"
	.string "다들 나를\n"
	.string "빤히 쳐다봐!$"
	// なんで オトコってｎ
	// ビキニが すき なのかしらね!ｐ
	// みんな わたしの ことｎ
	// ジロジロ みるのよ!

Route131_Text_KaraDefeat:
	.string "실력이 달라도 너무 다르잖아...!$"
	// じつりょくが ちがい すぎるわ……!

Route131_Text_KaraPostBattle:
	.string "다들 비키니를 보는 게 아니라\n"
	.string "내 미모를 감상하고 있는 건가...?$"
	// みんな ビキニを みてるんじゃなくてｎ
	// わたしの びぼうが げんいん かしら……?

Route131_Text_ReliIntro:
	.string "애미: 남매가 힘을 합쳐서\n"
	.string "한번 열심히 해볼까!?$"
	// アミ『きょうだい ちからを あわせてｎ
	// がんばっちゃおうかな!?

Route131_Text_ReliDefeat:
	.string "애미: 남매가 힘을 합쳐도\n"
	.string "이길 수 없었어$"
	// アミ『きょうだいで ちからを あわせてもｎ
	// かてなかったわ

Route131_Text_ReliPostBattle:
	.string "애미: 황금마을 사람은\n"
	.string "태어났을 때부터\l"
	.string "바다랑 포켓몬과 함께야$"
	// アミ『キナギの にんげんはｎ
	// うまれた ときからｌ
	// うみと ポケモンと いっしょ なんだ

Route131_Text_ReliNotEnoughMons:
	.string "애미: 포켓몬 2마리가 없어?\n"
	.string "포켓몬 승부를 즐길 수 없겠는걸$"
	// アミ『ポケモン 2ひき いないの?ｎ
	// ポケモンしょうぶ たのしめないわね

Route131_Text_IanIntro:
	.string "승우: 남매끼리 힘을 합쳐서\n"
	.string "열심히 해보겠습니다-!!$"
	// カツ『きょうだい ちからを あわせてｎ
	// がんばりま-す!!

Route131_Text_IanDefeat:
	.string "승우: 누나랑 열심히 했는데도\n"
	.string "이길 수 없었어...$"
	// カツ『あねきと がんばったのにｎ
	// かてなかったよ……

Route131_Text_IanPostBattle:
	.string "승우: 황금마을은 바다 위에\n"
	.string "떠 있는 마을이잖아?\p"
	.string "그러니까 바다가 끝이 없듯이\n"
	.string "황금마을도 끝이 없는 거야!$"
	// カツ『キナギって うみの うえにｎ
	// うかんでる まち だろ?ｐ
	// だから うみが つづくかぎりｎ
	// そこは キナギ なんだよ!

Route131_Text_IanNotEnoughMons:
	.string "승우: 포켓몬이 2마리 있으면\n"
	.string "포켓몬 승부 해줄게!$"
	// カツ『ポケモン 2ひき いたらｎ
	// ポケモンしょうぶ してやるよ!

Route131_Text_TaliaIntro:
	.string "나를 이기면\n"
	.string "엄청난 정보를 알려 줄게!$"
	// わたしに かてたらｎ
	// すごい じょうほう おしえてあげる!

Route131_Text_TaliaDefeat:
	.string "어라 져버렸네$"
	// あら まけちゃったのね

Route131_Text_TaliaPostBattle:
	.string "여기 근처에 이상한 장소가 있어\n"
	.string "거대한 탑이 솟아 있다구!\l"
	.string "한번 가보는 게 어때?$"
	// この そばに ふしぎな ばしょが あるわよｎ
	// たかい とうが そびえているの!ｌ
	// みてきたら どうかしら?

Route131_Text_KevinIntro:
	.string "황금마을 사람들은 정말 친절해!\n"
	.string "절대로 화를 내는 법이 없지\l"
	.string "물론 나도 황금마을 사람이야!$"
	// キナギには おおらかな やつ ばかりだぜ!ｎ
	// ぜったい おこったり しないんだｌ
	// もちろん オレもな

Route131_Text_KevinDefeat:
	.string "앗...$"
	// あ……っ

Route131_Text_KevinPostBattle:
	.string "쳇! ...이 아니라\n"
	.string "나 화 안났어 안났다고!\p"
	.string "...하하 강하다 너!\n"
	.string "핫핫하!$"
	// ちっ! ……じゃ なかったｎ
	// お おこってない おこってないよ!ｐ
	// ……ハハ つよいね きみは!ｎ
	// はっハッは!

Route132_Text_GilbertIntro:
	.string "어렸을 때는 툭하면 감기에 걸렸는데\n"
	.string "수영을 시작하고 나선 이렇게 튼튼해졌어!$"
	// ちいさい ころは よく カゼを ひいたけどｎ
	// すいえいを はじめて こんなに じょうぶ!

Route132_Text_GilbertDefeat:
	.string "더 강해지고 싶어...!$"
	// もっと つよくなりたい……!

Route132_Text_GilbertPostBattle:
	.string "포켓몬 트레이너도\n"
	.string "산과 들을 걸어 다니니\l"
	.string "정말 건강할 것 같아-!$"
	// ポケモン トレ-ナ-もｎ
	// のやまを あるき まわるからｌ
	// とっても けんこうてき だよね-!

Route132_Text_DanaIntro:
	.string "물살이 거센 곳에서는\n"
	.string "헤엄치지 않으려고 해$"
	// ながれの つよい ところではｎ
	// およがないように しているのよ

Route132_Text_DanaDefeat:
	.string "꺄아아아아아앙-!$"
	// いやああああんっ!

Route132_Text_DanaPostBattle:
	.string "물살에 떠밀리면 내가 어디 있는지\n"
	.string "알 수 없게 돼버려...$"
	// ながされると じぶんが どこに いるのかｎ
	// わからなく なっちゃうの……

Route132_Text_RonaldIntro:
	.string "이길 것인가 질 것인가\n"
	.string "승부하면 알게 되겠지!$"
	// かつか まけるかｎ
	// やれば わかることだろ!

Route132_Text_RonaldDefeat:
	.string "으앙-\n"
	.string "져버렸다-$"
	// わ-んｎ
	// まけて しまった

Route132_Text_RonaldPostBattle:
	.string "뻔히 이길 승부는 하지 않는다!\n"
	.string "이길 것인가 질 것인가\l"
	.string "그런 아슬아슬한 느낌이 좋거든!$"
	// かてると わかる しょうぶは しない!ｎ
	// かつか まけるかｌ
	// その ギリギリの かんじが いいんだ!

Route132_Text_KiyoIntro:
	.string "24시간 포켓몬만 생각하고 있는\n"
	.string "이 몸을 이길 수 있을 것 같나!?$"
	// 24じかん ポケモンのこと かんがえてるｎ
	// そんな おれに かてると おもうか!?

Route132_Text_KiyoDefeat:
	.string "졌다\n"
	.string "너에게 져버렸다$"
	// まけたｎ
	// おまえさんには まけたわ

Route132_Text_KiyoPostBattle:
	.string "크윽...\n"
	.string "너도 포켓몬밖에 모르는군!\p"
	.string "24시간 오로지\n"
	.string "포켓몬 생각밖에 안 하고 있구나!$"
	// くう……ｎ
	// おまえも ポケモンばか だな!ｐ
	// 24じかん ポケモンのこと ばかりｎ
	// かんがえて いるんだろ!

Route132_Text_MakaylaIntro:
	.string "항상 같이 있던 영감이\n"
	.string "없어져도 이길 수 있네!$"
	// いつも いっしょの じいさんがｎ
	// いなくても かてるわい!

Route132_Text_MakaylaDefeat:
	.string "이런 역시 안 되는구먼$"
	// あら やっぱり ダメかね

Route132_Text_MakaylaPostBattle:
	.string "저쪽 젊은이는\n"
	.string "젊었을 때의 영감을 꼭 닮았구먼\l"
	.string "호호호...$"
	// あの わかい おとこのこｎ
	// じいさんの わかい ころに そっくりじゃｌ
	// ポッ……

Route132_Text_JonathanIntro:
	.string "아까부터 이상한 시선이\n"
	.string "느껴지는데 혹시 너야?$"
	// さっき から へんな しせんをｎ
	// かんじると おもったら キミか?

Route132_Text_JonathanDefeat:
	.string "헤에! 강하잖아!$"
	// へえ! つよいね!

Route132_Text_JonathanPostBattle:
	.string "자꾸 누가 날\n"
	.string "쳐다보고 있어서 집중할 수가 없어!$"
	// だれかが ぼくの ことをｎ
	// みているきが して おちつかないっ!

Route132_Text_PaxtonIntro:
	.string "언제나 함께였던 할멈은 어디 있지?\n"
	.string "혼자서 이길 수 있으려나$"
	// いつも いっしょの ばあさんは どこかな?ｎ
	// ひとりで かてるじゃろか

Route132_Text_PaxtonDefeat:
	.string "아아 역시 안 되는군$"
	// ああ やっぱり ダメかね

Route132_Text_PaxtonPostBattle:
	.string "할멈이 날 찾고 있을 거라네\n"
	.string "당장 찾으러 가야겠군$"
	// ばあさんも わしを さがしてるじゃろｎ
	// はよう みつけて やらんと

Route132_Text_DarcyIntro:
	.string "홀로 여기서\n"
	.string "수행하는 게 좋은데\l"
	.string "왜 자꾸 찾아오고 난리야!$"
	// ひとりで この ばしょでｎ
	// しゅぎょう するのが すきだったのに!ｌ
	// おおぜい やって くるんだもの ひどい!

Route132_Text_DarcyDefeat:
	.string "알았어\n"
	.string "다 같이 쓰면 되잖아$"
	// わかったわよｎ
	// みんなで つかえば いいんでしょ

Route132_Text_DarcyPostBattle:
	.string "우선 저기 어르신과 팀을 맺어서\n"
	.string "다른 팀에게 도전이나 해볼까?$"
	// とりあえず そこの おじいさんと くんでｎ
	// むこうの チ-ムに いどんで みようかな?

Route133_Text_FranklinIntro:
	.string "너도 물살에 떠밀려 왔니?\n"
	.string "이것도 어떻게 보면 인연이구나\l"
	.string "승부하자!$"
	// キミも しおに ながされて きたの?ｎ
	// これも なにかの えんだねｌ
	// しょうぶ しようよ!

Route133_Text_FranklinDefeat:
	.string "강해!\n"
	.string "너무 강해!$"
	// つよい!ｎ
	// つよすぎっ!

Route133_Text_FranklinPostBattle:
	.string "너 같은 강한 트레이너가\n"
	.string "떠밀려 오다니...\l"
	.string "나도 참 운이 없는걸...$"
	// キミみたいな つよい トレ-ナ-がｎ
	// ながされて くるなんて……ｌ
	// オレも ツキが ないなぁ……

Route133_Text_DebraIntro:
	.string "나는 불쌍한 여자...\n"
	.string "휩쓸리다가 여기까지 왔어...$"
	// わたしは かなしい おんな……ｎ
	// ながれ ながれて ここまで きたの……

Route133_Text_DebraDefeat:
	.string "졌어...$"
	// まけたぁ……

Route133_Text_DebraPostBattle:
	.string "휩쓸리기만 하는 인생이라니...\n"
	.string "이젠 싫엇!$"
	// ながされる だけの じんせい なんて……ｎ
	// もう イヤっ!

Route133_Text_LindaIntro:
	.string "어서 오세요-옷!\n"
	.string "기다리고 있었습니다!$"
	// いらっしゃ-い!ｎ
	// おまち してましたわ!

Route133_Text_LindaDefeat:
	.string "싫어-!$"
	// いや-ん!

Route133_Text_LindaPostBattle:
	.string "어린 트레이너가 이렇게 강하다니...\n"
	.string "다 큰 어른으로서 부끄러워욧!$"
	// つよい こどもの トレ-ナ-なんて……ｎ
	// おねえさん こまっちゃうぅ!

Route133_Text_WarrenIntro:
	.string "이기고 싶다고 해서\n"
	.string "남들과 똑같이 키우고 싶진 않아!$"
	// かちたいから ってｎ
	// ひとと おなじように そだては しないぜ!

Route133_Text_WarrenDefeat:
	.string "젠장-!\n"
	.string "내 방식이 너무 어설펐나!$"
	// くそ-!ｎ
	// おれの やりかたは まだまだ あまい!

Route133_Text_WarrenPostBattle:
	.string "남이랑 똑같이 하는 것보다는\n"
	.string "내가 하고 싶은 대로 하는 게\l"
	.string "당연히 더 즐겁지!$"
	// ひとと おなじこと するよりｎ
	// じぶんの したいこと したほうがｌ
	// たのしいに きまってるだろ!

Route133_Text_BeckIntro:
	.string "새포켓몬과 함께\n"
	.string "이런 곳까지 와버렸습니다$"
	// とりポケモンと いっしょにｎ
	// こんな ところまで きました

Route133_Text_BeckDefeat:
	.string "너...\n"
	.string "어떻게 그렇게 멋있을 수 있지!?$"
	// きみ……ｎ
	// なんて かっこいいんだ!

Route133_Text_BeckPostBattle:
	.string "슬슬 검방울시티로 돌아가고 싶지만\n"
	.string "어째선지 여기가 마음에 드는걸!?$"
	// そろそろ ヒワマキに かえりたいけどｎ
	// なんとなく ここ すきに なっちゃったぞ!?

Route133_Text_MollieIntro:
	.string "여태까지 수천 번은\n"
	.string "포켓몬 승부를 한 것 같은데$"
	// いままでに なんぜんかいｎ
	// ポケモン しょうぶを したかねえ

Route133_Text_MollieDefeat:
	.string "수천 번을 졌지만\n"
	.string "분한 건 분한 법이구먼$"
	// なんぜんかい まけてもｎ
	// くやしい もんは くやしいでね

Route133_Text_MolliePostBattle:
	.string "나와 영감 같은\n"
	.string "달인을 목표로 힘내게나$"
	// わたいや じいさんのようなｎ
	// たつじんを めざして がんばんなせえ

Route133_Text_ConorIntro:
	.string "젊은 것들은\n"
	.string "흘러가는 대로 살던데 한심하군!$"
	// わかい やつらはｎ
	// ながされて ばっかりで なさけねぇ!

Route133_Text_ConorDefeat:
	.string "자네는 확실한 목표가 있군$"
	// きみは しっかりしとるな

Route133_Text_ConorPostBattle:
	.string "주변에 휩쓸리지 않는\n"
	.string "굳센 어른이 되거라!$"
	// まわりに ながされずｎ
	// しっかりした おとなに なんなさい!

Route134_Text_JackIntro:
	.string "헤엄치는 게 특기인 포켓몬도\n"
	.string "휩쓸릴 정도로 이곳의 물살은 거세지!$"
	// およぎの とくいな ポケモンだってｎ
	// ながされる しおの ながれだ!

Route134_Text_JackDefeat:
	.string "히에-엣!$"
	// ひえ-っ!

Route134_Text_JackPostBattle:
	.string "포켓몬들은 이 물살을\n"
	.string "즐기고 있는 것 같아!$"
	// ポケモンたちは この ながれをｎ
	// たのしんでる みたいだよ!

Route134_Text_LaurelIntro:
	.string "내 사랑동이들과\n"
	.string "즐겁게 승부하자!$"
	// わたしの ラブカスたちとｎ
	// たのしく しょうぶ しましょうよ!

Route134_Text_LaurelDefeat:
	.string "어머머머머멋!$"
	// あらららららっ!

Route134_Text_LaurelPostBattle:
	.string "어딘가에 있는 마니아가\n"
	.string "사랑동이의 비늘을 모으고 있어-$"
	// どこかの マニアがｎ
	// ラブカスの ウロコを あつめてるのよね-

Route134_Text_AlexIntro:
	.string "오케-이! 휴식 끝!\n"
	.string "포켓몬 승부다!$"
	// よ-しっ! きゅうけい おわり!ｎ
	// ポケモンしょうぶ しようぜ!

Route134_Text_AlexDefeat:
	.string "또 지쳤다...$"
	// また バテた……

Route134_Text_AlexPostBattle:
	.string "내 새포켓몬들은...\n"
	.string "조금만 오래 날면 금방 지치고 말아$"
	// オレの とりポケモンたち……ｎ
	// ながいあいだ とぶと すぐに バテるんだ

Route134_Text_HitoshiIntro:
	.string "포켓몬 트레이너라면\n"
	.string "묵묵히 포켓몬 승부다!$"
	// ポケモントレ-ナ-ならｎ
	// だまって ポケモンしょうぶ!

Route134_Text_HitoshiDefeat:
	.string "...... ...... ......\n"
	.string "...... ...... ......$"
	// …… …… ……ｎ
	// …… …… ……

Route134_Text_HitoshiPostBattle:
	.string "스스로 승부를 걸어 놓고\n"
	.string "져버리다니... 너무 부끄럽다...$"
	// じぶんから しょうぶを いどんでおいてｎ
	// まけるとは…… はずかしすぎる……

Route134_Text_AaronIntro:
	.string "이곳의 격렬한 물살!\n"
	.string "이 또한 우리를 단련시켜 주지!$"
	// このあたりの はげしい しおの ながれ!ｎ
	// それもまた おれたちを きたえてくれる!

Route134_Text_AaronDefeat:
	.string "솔직하게 패배를 인정하겠다$"
	// すなおに まけを みとめよう

Route134_Text_AaronPostBattle:
	.string "유성의 폭포에서\n"
	.string "다시 수행하겠다!\p"
	.string "괜찮으면 너도 가보도록\n"
	.string "분명 지금보다 강해질 거다!$"
	// りゅうせいのたきでｎ
	// しゅぎょう しなおすと しよう!ｐ
	// よければ きみも いってみたまえｎ
	// きっと いまより つよくなる!

Route134_Text_KelvinIntro:
	.string "보 보트가\n"
	.string "조류에 떠내려갔어요$"
	// ふ ふねがｎ
	// ながされて しまったんです

Route134_Text_KelvinDefeat:
	.string "으어어어어\n"
	.string "멈춰줘요 멈춰!$"
	// あわわわわｎ
	// やめてください やめてくださいよ!

Route134_Text_KelvinPostBattle:
	.string "이 위에서 파도타기도 못 하면\n"
	.string "집으로 못 돌아가잖아요!\p"
	.string "...뭐 기절해도 파도타기는 쓸 수 있지만\n"
	.string "기분이 안 좋다고요$"
	// このうえ なみのり まで できなかったらｎ
	// かえれないじゃ ないですか!ｐ
	// ……まあ ひんしでも なみのり できますけどｎ
	// きぶんてきに よろしくなくて

Route134_Text_MarleyIntro:
	.string "재빠른 공격을 피할 수 있나요?$"
	// すばやい こうげきを かわせますこと?

Route134_Text_MarleyDefeat:
	.string "그런 기술이 있을 줄이야...!\n"
	.string "완패로군요$"
	// そんな てが あるなんて……!ｎ
	// かんぱい ですわ

Route134_Text_MarleyPostBattle:
	.string "속도는 포기 못 해요\n"
	.string "그러니까 더 열심히 할 겁니다!$"
	// すばやさへの こだわりは すてきれないのｎ
	// もっと がんばって みますわ!

Route134_Text_ReynaIntro:
	.string "내 포켓몬은\n"
	.string "쉽게 쓰러뜨리지 못할걸!$"
	// あたいの ポケモンはｎ
	// ちょっとや そっとじゃ たおせないよ!

Route134_Text_ReynaDefeat:
	.string "말도 안 돼!\n"
	.string "내가 질 줄이야!$"
	// うっそだろ!ｎ
	// あたいが まけるなんて!

Route134_Text_ReynaPostBattle:
	.string "하핫 너는 못 당하겠다!\p"
	.string "저쪽에 있는 트레이너를 쓰러뜨려서\n"
	.string "다시 처음부터 수행해야겠어!$"
	// ははっ あんたにゃ まけたよ!ｐ
	// そこらへんの トレ-ナ-でも たおしてｎ
	// いちから しゅぎょう しなおすよ!

Route134_Text_HudsonIntro:
	.string "저기 이 주변에서\n"
	.string "다른 선원을 본 적 없어?$"
	// なあ このへんでｎ
	// もうひとり ふなのりを みなかった?

Route134_Text_HudsonDefeat:
	.string "오- 굉장한데$"
	// お- すごいな

Route134_Text_HudsonPostBattle:
	.string "우리 보트가 조류에 떠내려갔거든!\p"
	.string "그 녀석은 좀 소심해서\n"
	.string "많이 걱정되네$"
	// おれたちの ふねが ながされちゃってさ!ｐ
	// あいぼうが きの よわい やつだからｎ
	// しんぱい してるんだ
