gTrickHouse_Mechadoll_Oddish:: @ 27ECBC
	.string "뚜벅쵸$"

gTrickHouse_Mechadoll_Poochyena:: @ 27ECC3
	.string "포챠나$"

gTrickHouse_Mechadoll_Taillow:: @ 27ECCD
	.string "테일로$"

gTrickHouse_Mechadoll_Azurill:: @ 27ECD5
	.string "루리리$"

gTrickHouse_Mechadoll_Lotad:: @ 27ECDD
	.string "연꽃몬$"

gTrickHouse_Mechadoll_Wingull:: @ 27ECE3
	.string "갈모매$"

gTrickHouse_Mechadoll_Dustox:: @ 27ECEB
	.string "독케일$"

gTrickHouse_Mechadoll_Zubat:: @ 27ECF2
	.string "주뱃$"

gTrickHouse_Mechadoll_Nincada:: @ 27ECF8
	.string "토중몬$"

gTrickHouse_Mechadoll_Ralts:: @ 27ED00
	.string "랄토스$"

gTrickHouse_Mechadoll_Zigzagoon:: @ 27ED06
	.string "지그제구리$"

gTrickHouse_Mechadoll_Slakoth:: @ 27ED10
	.string "게을로$"

gTrickHouse_Mechadoll_Poochyena2:: @ 27ED18
	.string "포챠나$"

gTrickHouse_Mechadoll_Shroomish:: @ 27ED22
	.string "버섯꼬$"

gTrickHouse_Mechadoll_Zigzagoon2:: @ 27ED2C
	.string "지그제구리$"

gTrickHouse_Mechadoll_Poochyena3:: @ 27ED36
	.string "포챠나$"

gTrickHouse_Mechadoll_Zubat2:: @ 27ED40
	.string "주뱃$"

gTrickHouse_Mechadoll_Carvanha:: @ 27ED46
	.string "샤크니아$"

gTrickHouse_Mechadoll_BurnHeal:: @ 27ED4F
	.string "화상치료제$"

gTrickHouse_Mechadoll_HarborMail:: @ 27ED59
	.string "항구메일$"

gTrickHouse_Mechadoll_SamePrice:: @ 27ED65
	.string "같은 가격$"

gTrickHouse_Mechadoll_60Yen:: @ 27ED70
	.string "60원$"

gTrickHouse_Mechadoll_55Yen:: @ 27ED74
	.string "55원$"

gTrickHouse_Mechadoll_Nothing:: @ 27ED78
	.string "남지 않는다$"

gTrickHouse_Mechadoll_CostMore:: @ 27ED80
	.string "비싸다$"

gTrickHouse_Mechadoll_CostLess:: @ 27ED95
	.string "싸다$"

gTrickHouse_Mechadoll_SamePrice2:: @ 27EDAA
	.string "같은 가격$"

gTrickHouse_Mechadoll_Male:: @ 27EDB5
	.string "남성$"

gTrickHouse_Mechadoll_Female:: @ 27EDBA
	.string "여성$"

gTrickHouse_Mechadoll_Neither:: @ 27EDC1
	.string "둘 다 아니다$"

gTrickHouse_Mechadoll_ElderlyMen:: @ 27EDC9
	.string "할아버지$"

gTrickHouse_Mechadoll_ElderlyLadies:: @ 27EDD5
	.string "할머니$"

gTrickHouse_Mechadoll_SameNumber:: @ 27EDE4
	.string "같은 가격$"

gTrickHouse_Mechadoll_None:: @ 27EDF0
	.string "없다$"

gTrickHouse_Mechadoll_One:: @ 27EDF5
	.string "한 명$"

gTrickHouse_Mechadoll_Two:: @ 27EDF7
	.string "두 명$"

gTrickHouse_Mechadoll_Two2:: @ 27EDF9
	.string "두 마리$"

gTrickHouse_Mechadoll_Three:: @ 27EDFB
	.string "세 마리$"

gTrickHouse_Mechadoll_Four:: @ 27EDFD
	.string "네 마리$"

gTrickHouse_Mechadoll_Six:: @ 27EDFF
	.string "6채$"

gTrickHouse_Mechadoll_Seven:: @ 27EE01
	.string "7채$"

gTrickHouse_Mechadoll_Eight:: @ 27EE03
	.string "8채$"

gTrickHouse_Mechadoll_Six2:: @ 27EE05
	.string "여섯 명$"

gTrickHouse_Mechadoll_Seven2:: @ 27EE07
	.string "일곱 명$"

gTrickHouse_Mechadoll_Eight2:: @ 27EE09
	.string "여덟 명$"
