LilycoveCity_ContestLobby_Text_InterviewRequest: @ 827EF15
	.string "으음? 당신 포켓몬 콘테스트에\n"
	.string "참가했었군요!\l"
	.string "그 포켓몬을 보면 안다구요!\p"
	.string "전 포켓몬 콘테스트에 대해\n"
	.string "기사를 쓰고 있는데\p"
	.string "괜찮다면 잠깐 감상을\n"
	.string "들려주실 수 있을까요?$"
	@ おや? あなた ポケモンコンテストにｎ
	@ さんかして いましたね!ｌ
	@ その ポケモンを みれば わかりますよ!ｐ
	@ わたくし ポケモンコンテストに ついてｎ
	@ きじを かいて いるのですがｐ
	@ できれば すこし かんそうをｎ
	@ きかせて くれませんかね?

LilycoveCity_ContestLobby_Text_DescribeContest: @ 827EFE7
	.string "정말요!?\n"
	.string "감사합니다\p"
	.string "그럼 지금 했던 콘테스트에 대한 감상을\n"
	.string "한마디로 부탁할게요!$"
	@ ほんとう ですか!ｎ
	@ ありがとう ございますｐ
	@ それでは いまの コンテストの かんそうをｎ
	@ ひとことで おねがいします!

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX: @ 827F03E
	.string "으-음 그렇군요!\p"
	.string "어떤 콘테스트였는지\n"
	.string "잘 알 수 있는 한마디였습니다!\p"
	.string "...마지막으로\n"
	.string "살짝 물어보고 싶습니다만\p"
	.string "당신이 상상하는 {STR_VAR_2}{K_I}란\n"
	.string "대체 어떤 것인가요?$"
	@ う-ん なるほど!ｐ
	@ どんな コンテストだったかｎ
	@ よくわかる ひとこと ですね!ｐ
	@ ……さいごにｎ
	@ ちょっと おききしたいの ですがｐ
	@ あなたが イメ-ジする §うってｎ
	@ いったい どんなもの ですかね?

LilycoveCity_ContestLobby_Text_ThatsAllForInterview: @ 827F0EC
	.string "그렇군요!\p"
	.string "그게 당신이 상상하는\n"
	.string "{STR_VAR_2}인 거군요!\p"
	.string "여러모로 참고가 됐습니다!\p"
	.string "콘테스트에 대한\n"
	.string "좋은 기사를 쓸 수 있을 것 같네요\p"
	.string "어쩌면 TV에서 이 내용을\n"
	.string "방송할지도 모르니까\l"
	.string "기대하고 있어주세요!$"
	@ なるほど!ｐ
	@ それが あなたの イメ-ジするｎ
	@ §う なんですね!ｐ
	@ いろいろ さんこうに なりました!ｐ
	@ コンテストに ついてｎ
	@ いい きじが かけそう ですよｐ
	@ もしかしたら テレビで このことがｎ
	@ ながれるかも しれないのでｌ
	@ たのしみに してくださいね!

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe: @ 827F1EF
	.string "그렇습니까...\p"
	.string "다음에 재미있는 일이 생기면\n"
	.string "들려주세요$"
	@ そうですか……ｐ
	@ こんど おもしろいことが あればｎ
	@ きかせて くださいね

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest: @ 827F23F
	.string "다음 포켓몬 콘테스트도\n"
	.string "기대하고 있겠습니다!$"
	@ こんどの ポケモンコンテストもｎ
	@ たのしみに してますよ!

gTVBravoTrainerText00:: @ 0827F275
	.string "이야-!\n"
	.string "“브라보 파트너”의 시간이야!\p"
	.string "오늘은 {STR_VAR_3} 클래스의\n"
	.string "{STR_VAR_2}{K_EULREUL} 자랑하는\l"
	.string "{STR_VAR_1}씨의 포켓몬!$"
	@ イヤ-!ｎ
	@ 『ブラボ- トレ-ナ-』の じかんだ!ｐ
	@ きょうは §え3クラスのｎ
	@ §う2を ほこるｌ
	@ §い1さんの ポケモン!

gTVBravoTrainerText01:: @ 0827F304
	.string "{STR_VAR_1} “{STR_VAR_2}”의\n"
	.string "소개 시간이야-!\p"
	.string "“{STR_VAR_2}”인가...\p"
	.string "이미 닉네임부터\n"
	.string "{STR_VAR_3}{K_IGA} 드러나는걸!$"
	@ §い の 「§う」のｎ
	@ しょうかいだ-!ｐ
	@ 「§う」か……ｐ
	@ もう ニックネ-ム からしてｎ
	@ §えが にじみ でているぜ!
	
gTVBravoTrainerText02:: @ 0827F361
	.string "그런데 그 {STR_VAR_1}씨가\n"
	.string "포켓몬 콘테스트에 참가했을 때\p"
	.string "자신의 포켓몬에 대해서\n"
	.string "열정적으로 얘기해 줬어!$"
	@ さ-て この §いさんがｎ
	@ ポケモンコンテストに さんか したときｐ
	@ じぶんの ポケモンに ついてｎ
	@ あつく はなして くれたぞ!

gTVBravoTrainerText03:: @ 0827F3E4
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물어보니\l"
	.string "엄청 기쁜 듯이\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었지!\p"
	.string "뭐 콘테스트에서는\n" 
	.string "{STR_VAR_3}번이었으니까 말이지-!\p"
	.string "지금의 {STR_VAR_1}씨에게\n"
	.string "정말 딱 맞는 대사였다고 생각해!$"
	@ コンテストを したあとのｎ
	@ かんそうを きくとｌ
	@ すごく うれしそうにｐ
	@ 「§う」ってｎ
	@ こたえて くれたぞ!ｐ
	@ まあ コンテストではｎ
	@ §えばん でした からね-!ｐ
	@ いまの §いさんにはｎ
	@ ぴったりの セリフだよ まったく!

gTVBravoTrainerText04:: @ 0827F49F
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물어보니\l"
	.string "미묘하게 분해하면서\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었지!\p"
	.string "뭐 콘테스트에선\n"
	.string "{STR_VAR_3}번이었으니까 말이지-!\p"
	.string "이 대사에 {STR_VAR_1}씨의\n"
	.string "분함이 보일 듯 말 듯하네-$"
	@ コンテストを したあとのｎ
	@ かんそうを きくとｌ
	@ びみょうに くやしがり ながらｐ
	@ 「§う」ってｎ
	@ こたえて くれたぞ!ｐ
	@ まあ コンテストではｎ
	@ §えばん でした からね-!ｐ
	@ この ことばに §いさんのｎ
	@ くやしさが みえかくれ するね-

gTVBravoTrainerText05:: @ 0827F565
	.string "그런데 {STR_VAR_1}씨가 목표로 하는\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 대체 뭘까?\l"
	.string "들어보고 싶은걸-!\p"
	.string "물론 물어봤다고!\p"
	.string "이 한마디에 그\n"
	.string "모든 것이 담겨있지!\p"
	.string "바로 “{STR_VAR_3}!”\p"
	.string "그것이야말로 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}의 모든 것인 거야!$"
	@ ところで §いさんの めざしてるｎ
	@ §うって いったい なんだろう?ｌ
	@ きいて みたいね-!ｐ
	@ もちろん きいて きました!ｐ
	@ それは つぎの ひとことにｎ
	@ すべてが つまって います!ｐ
	@ それは 「§え!」ｐ
	@ それこそ §いさんのｎ
	@ §うの すべて なんです!

gTVBravoTrainerText06:: @ 0827F624
	.string "마지막으로 {STR_VAR_1}{K_IGA}\n"
	.string "썼던 {STR_VAR_2}도\l"
	.string "모두 “{STR_VAR_3}”인 거래!$"
	@ さいごに §いがｎ
	@ つかった §うもｌ
	@ すべて 「§え」 なんです!

gTVBravoTrainerText07:: @ 0827F65C
	.string "브라보! {STR_VAR_1}!\n"
	.string "브라보!! {STR_VAR_2}!\p"
	.string "다음번 {STR_VAR_1}씨의 활약에\n"
	.string "기대가 되는걸-!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자구-!$"
	@ ブラボ-! §いｎ
	@ ブラボ-!! §うｐ
	@ こんごの §いさんの かつやくにｎ
	@ きたい したいね-!ｐ
	@ それじゃあ また じかいのｎ
	@ ほうそうで あいましょ-!

gTVBravoTrainerText08:: @ 0827F6E6
	.string "{STR_VAR_1}{K_EULREUL} 소개할 시간이야-!$"
	@ §い の しょうかいだ-!

BattleFrontier_BattleTowerLobby_Text_InterviewRequest:: @ 0827F704
	.string "아! 지금 막 배틀이 끝난\n"
	.string "트레이너분이시군요!\p"
	.string "저는 지금 여러 트레이너의\n"
	.string "이야기를 들으면서 돌아다니고 있는데\p"
	.string "배틀이 끝난 감상을\n"
	.string "조금만 들려주실 수 있을까요?$"
	@ あ! いま たたかっていたｎ
	@ トレ-ナ-の かたですね!ｐ
	@ わたし いま いろんな トレ-ナ-のｎ
	@ はなしを きいて まわってるんだけどｐ
	@ たたかいおわった かんそうをｎ
	@ すこしだけ きかせて もらえませんか?

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut:: @ 0827F7BA
	.string "정말인가요!?\n"
	.string "감사합니다!\l"
	.string "으음 그럼...\p"
	.string "이번 배틀타워의\n"
	.string "대전은 어땠나요?\p"
	.string "만족하셨습니까!?\n"
	.string "아니면 불만이신가요!?$"
	@ ほんと!?ｎ
	@ ありがとう!ｌ
	@ えっと それじゃあねぇ……ｐ
	@ こんかいの バトルタワ-のｎ
	@ たいせんは どうでしたかｐ
	@ まんぞく でしたか!ｎ
	@ それとも ふまん ですか!?

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou:: @ 0827F84C
	.string "아아!\n"
	.string "죄송합니다\p"
	.string "그럼 다음에 또 배틀타워에 온다면\n"
	.string "들려주세요$"
	@ あぁ!ｎ
	@ ごめんなさいｐ
	@ じゃあ またこんど バトルタワ-に きたらｎ
	@ きかせて くださいね

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle:: @ 0827F8AE
	.string "역시나!\p"
	.string "그 만족한 얼굴을 보면\n"
	.string "얼마나 좋은 시합이었는지가\l"
	.string "보인단 말이죠!$"
	@ さっすが!ｐ
	@ その まんぞくした かおを みればｎ
	@ どんなに いいしあいだったかｌ
	@ わかりますよ!

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned:: @ 0827F921
	.string "으-음 그렇습니까...\p"
	.string "생각한 것처럼 승부하는 건\n"
	.string "꽤나 어려운 일이니 말이죠...$"
	@ う-ん そうですか……ｐ
	@ おもいどおりに しょうぶを するのってｎ
	@ なかなか むずかしい ですからね……

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle:: @ 0827F97A
	.string "아앗 그리고\n"
	.string "하나만 더 괜찮을까요?\p"
	.string "이번 배틀의 감상을\n"
	.string "한마디로 딱 들려주세요!$"
	@ あぁっ あとｎ
	@ もう ひとつだけ いいですか?ｐ
	@ この たたかいの かんそうをｎ
	@ ひとことで ビシッと きかせてください!

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine:: @ 0827F9FD
	.string "멋있어요-!!\p"
	.string "좋은 마무리 대사네요\n"
	.string "다음 배틀도 기대하고 있겠습니다\p"
	.string "그럼 다음에 또 봐요!$"
	@ かっこい-!!ｐ
	@ いい きめゼリフ ですねｎ
	@ つぎの たたかいも きたい してますよｐ
	@ それでは また!

BattleFrontier_BattleTowerLobby_Text_SilentType:: @ 0827FA6F
	.string "그렇습니까...\p"
	.string "하지만 아무 할 말이 없는 것\n"
	.string "또한 멋있네요!\p"
	.string "그럼 다음 기회에\n"
	.string "감상을 들려주세요!$"
	@ そうですか……ｐ
	@ でも なにも いわないのもｎ
	@ また かっこいいですね!ｐ
	@ それじゃあ またの きかいにｎ
	@ かんそうを きかせて ください!

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle:: @ 0827FAF3
	.string "다음 배틀도\n"
	.string "기대하고 있다구요$"
	@ つぎの たたかいもｎ
	@ きたい してますよ

gTVBravoTrainerBattleTowerText00:: @ 0827FB20
	.string "이야-!\n"
	.string "“브라보 파트너”의 시간이야!\p"
	.string "오늘은 배틀타워에 도전했던\n"
	.string "{STR_VAR_1}씨를 소개할게-!\p"
	.string "{STR_VAR_1}씨는 {STR_VAR_2}{K_EULREUL}\n"
	.string "사용한 배틀을 해서$"
	@ イヤ-!ｎ
	@ 『ブラボ- トレ-ナ-』の じかんだ!ｐ
	@ きょうは バトルタワ-に ちょうせんしたｎ
	@ §いさんの しょうかいだ-!ｐ
	@ §いさんは §うをｎ
	@ つかった たたかいをして

gTVBravoTrainerBattleTowerText01:: @ 0827FBB3
	.string "무려 {STR_VAR_1}의 방에서\n"
	.string "{STR_VAR_2}연승이라는\l"
	.string "기록을 세웠다고!$"
	@ なんと §いの へやでｎ
	@ §うれんしょう というｌ
	@ きろくを うちたてたぞ!

gTVBravoTrainerBattleTowerText02:: @ 0827FC04
	.string "아깝게도 {STR_VAR_2}번째로 싸웠던\n"
	.string "{STR_VAR_1}씨에게 져버렸지만 말야\l"
	.string "으-음! 안타까워\p"
	.string "이렇게 빨리 {STR_VAR_1}씨와\n"
	.string "마주친 건 운이 없었다고밖에 할 수 없지\p"
	.string "자 그럼 그 {STR_VAR_1}씨와\n"
	.string "승부한 감상을 물어봤는데$"
	@ おしくも §うにんめで たたかったｎ
	@ §いさんに まけて しまいましたｌ
	@ う-ん! ざんねんだねぇｐ
	@ でも こんなはじめに §いさんにｎ
	@ あたるとは うんがないとしか いえないよｐ
	@ さて その §いさんとのｎ
	@ しょうぶの かんそうを きいたところ

gTVBravoTrainerBattleTowerText03:: @ 0827FCD1
	.string "마지막에는 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}{K_EULREUL} 훌륭히 쓰러뜨려서\l"
	.string "승리했다고\p"
	.string "이야 {STR_VAR_1}씨를 이기다니\n"
	.string "굉장하다는 말밖에 안 나와 참\p"
	.string "자 그럼 그 승리를 붙잡은\n"
	.string "순간의 감상을 물어봤는데$"
	@ さいごには §いさんのｎ
	@ §うを みごとに たおしてｌ
	@ しょうり したんですねぇｐ
	@ いや §いさんに かつなんてｎ
	@ すごいとしか いいようがないよ まったくｐ
	@ さて そのしょうりを つかんだｎ
	@ しゅんかんの かんそうを きいたところ

gTVBravoTrainerBattleTowerText04:: @ 0827FD91
	.string "하지만 마지막으로 등장한\n"
	.string "{STR_VAR_1}씨의 {STR_VAR_2}에게\l"
	.string "결국 져버리고 말았지\p"
	.string "뭐 “{STR_VAR_1}의 {STR_VAR_2}” 하면\n"
	.string "유명한 콤비니까\p"
	.string "...자 그럼 그 유명인과\n"
	.string "승부한 감상을 물어봤는데$"
	@ しかし さいごに とうじょうしたｎ
	@ §いさんの §うにｌ
	@ ついに まけて しまったんですねぇｐ
	@ まあ 「§いの §う」ｎ
	@ といえば ゆうめいな コンビ ですからねｐ
	@ ……さて その ゆうめいじんとのｎ
	@ しょうぶの かんそうを きいたところ

gTVBravoTrainerBattleTowerText05:: @ 0827FE93
	.string "“만족했다!!”\p"
	.string "라고 시원하게 답해줬어\n"
	.string "역시!\p"
	.string "만족스러운 배틀이 가능하다니\n"
	.string "정말로 굉장하지 참!\p"
	.string "그 만족감은 이 한마디를\n"
	.string "들었을 때 전부 이해했어$"
	@ まんぞく した!!ｐ
	@ と すがすがしく こたえてくれたよｎ
	@ さすがだぜ!ｐ
	@ まんぞくいく たたかいが できるなんてｎ
	@ ほんと すごいよねぇ まったく!ｐ
	@ その まんぞくかんは つぎの ひとことをｎ
	@ きいたとき すべて わかったよ

gTVBravoTrainerBattleTowerText06:: @ 0827FF89
	.string "불만이었다...\p"
	.string "라고 미묘하게 우울해하면서\n"
	.string "대답해줬어\p"
	.string "...뭐 만족스러운 배틀은\n"
	.string "자주 겪을 수 있는 게 아니니까-\p"
	.string "그때의 분함은\n"
	.string "이 한마디가 잘 드러내고 있어$"
	@ ふまんだった……ｐ
	@ と びみょうに おちこみながらｎ
	@ こたえて くれたよｐ
	@ ……まあ まんぞくいく たたかいってｎ
	@ なかなかできる もんじゃないからね-ｐ
	@ そのときの くやしさはｎ
	@ つぎの ひとことが よくあらわしてるよ

gTVBravoTrainerBattleTowerText07:: @ 0828009C
	.string "없음$"

gTVBravoTrainerBattleTowerText08:: @ 082800A1
	.string "없음$"

gTVBravoTrainerBattleTowerText09:: @ 082800A6
	.string "없음$"

gTVBravoTrainerBattleTowerText10:: @ 082800AB
	.string "없음$"

gTVBravoTrainerBattleTowerText11:: @ 082800B0
	.string "그 말은\n"
	.string "“{STR_VAR_1}!”$"

gTVBravoTrainerBattleTowerText12:: @ 082800B6
	.string "“{STR_VAR_1}!”\n"
	.string "으-음 좋은 말인걸!!\p"
	.string "{STR_VAR_2}씨의 기쁨을\n"
	.string "이 말이 잘 드러내고 있어!\p"
	.string "확실히 {STR_VAR_3}씨와의 배틀은\n"
	.string "그야말로 “{STR_VAR_1}”인\l"
	.string "느낌의 배틀이었지!$"
	@ 「§い!」ｎ
	@ う-ん  いい ことばだねぇ!!ｐ
	@ §うさんの うれしさをｎ
	@ このことばが よく あらわしているよ!ｐ
	@ たしかに §えさんとの たたかいはｎ
	@ まさに 「§い」 というｌ
	@ かんじ だったからねぇ!

gTVBravoTrainerBattleTowerText13:: @ 0828013D
	.string "“{STR_VAR_1}!”\n"
	.string "과연 그렇구나\p"
	.string "확실히 {STR_VAR_3}씨와의 배틀은\n"
	.string "“{STR_VAR_1}”라고밖에 할 수 없는\l"
	.string "배틀이었으니까\p"
	.string "{STR_VAR_2}씨의 분함이\n"
	.string "잘 전해져오네! 크-!$"
	@ 「§い!」ｎ
	@ なるほどねぇｐ
	@ たしかに §えさんとの たたかいはｎ
	@ 「§い」 としか いいようがないｌ
	@ たたかい でしたからねぇｐ
	@ §うさんの くやしさがｎ
	@ よく つたわってくるよ! く-!

gTVBravoTrainerBattleTowerText14:: @ 082801E6
	.string "브라보! {STR_VAR_1}!\n"
	.string "브라보!! {STR_VAR_2}!\p"
	.string "다음번 {STR_VAR_1}씨의 활약에\n"
	.string "기대가 되는걸!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자구-!$"
	@ ブラボ-! §いｎ
	@ ブラボ-!! §うｐ
	@ こんごの §いさんの かつやくにｎ
	@ きたい したいねぇ!ｐ
	@ それじゃあ また じかいのｎ
	@ ほうそうで あいましょ-!

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName: @ 08280270
	.string "와아!\p"
	.string "너 그 {STR_VAR_1}{K_EULREUL} 무척\n"
	.string "소중히 여기는 모양이구나!\p"
	.string "{STR_VAR_2}{K_I}라고 하는구나...\p"
	.string "맞다!\p"
	.string "지금 나 TV 취재로\n"
	.string "포켓몬에 대한 설문을 하고 있는데\p"
	.string "잠깐 질문에\n"
	.string "답해줄 수 있을까?$"
	@ わあ!ｐ
	@ きみ その §いを とてもｎ
	@ だいじに している みたいね!ｐ
	@ §う って いうんだ……ｐ
	@ そうだ!ｐ
	@ いま わたし テレビの しゅざいでｎ
	@ ポケモンの アンケ-トを してるんだけどｐ
	@ すこしだけ しつもんにｎ
	@ こたえて くれないかな?

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers: @ 0828034F
	.string "고마워!\p"
	.string "그럼 물을게\n"
	.string "딱 한마디로 대답해줘!$"
	@ ありがとう!ｐ
	@ じゃあ きくねｎ
	@ ずばり ひとことで こたえて!

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon: @ 08280393
	.string "네가 {STR_VAR_1}하고\n"
	.string "만났을 때\p"
	.string "무슨 느낌이었어?\n"
	.string "어떻게 생각했는지 알려줘!$"
	@ きみが §いとｎ
	@ であったときってｐ
	@ なにか かんじた?ｎ
	@ どう おもったか おしえて!

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike: @ 082803EF
	.string "네가 귀여워하는 {STR_VAR_1}!\p"
	.string "만약 무엇인가 좋아하는 것에 비유하자면\n"
	.string "뭐라고 생각해?$"
	@ きみの かわいがってる §い!ｐ
	@ もし なにか すきなものに たとえるとｎ
	@ すれば なんだと おもう?

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon: @ 08280454
	.string "네가 귀여워하는 {STR_VAR_1}!\n"
	.string "넌 {STR_VAR_1}의 어디에\n"
	.string "이끌린 거야?$"
	@ きみの かわいがってる §い!ｐ
	@ きみは §いの どこにｎ
	@ ひかれたの?

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou: @ 082804AC
	.string "으-음 그렇구나\p"
	.string "그럼 다음은 살짝\n"
	.string "어려운 질문을 할게!\p"
	.string "그럼...\p"
	.string "네게 있어 포켓몬이란\n"
	.string "한마디로 뭐라고 생각해?$"
	@ う-ん なるほどねｐ
	@ じゃあ つぎは ちょっとｎ
	@ むずかしい しつもんを するね!ｐ
	@ じゃあ……ｐ
	@ きみに とって ポケモンってｎ
	@ ひとことで いうと なんだと おもう?

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview: @ 08280523
	.string "그렇구나-!\p"
	.string "흐음흐음...\p"
	.string "아!\n"
	.string "협력해줘서 고마워!\p"
	.string "여러 얘기를 들어서\n"
	.string "재밌었어\p"
	.string "이 얘기 어쩌면 TV에\n"
	.string "나올지도 모르니까 기대해줘\p"
	.string "그럼 이만\n"
	.string "바이바이!$"
	@ なるほど-!ｐ
	@ ふむふむ……ｐ
	@ あ!ｎ
	@ きょうりょく ありがとうね!ｐ
	@ いろいろ はなしが きけてｎ
	@ おもしろ かったよｐ
	@ このはなし もしかしたら テレビでｎ
	@ ながすかも しれないから きたい しててねｐ
	@ じゃあねｎ
	@ バイバイ!

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe: @ 082805E2
	.string "그렇구나...\p"
	.string "그럼 또 포켓몬에 대해서\n"
	.string "얘기하고 싶어지면 언제든지 와줘$"
	@ そっか……ｐ
	@ じゃあ また ポケモンの ことをｎ
	@ はなしたく なったら いつでも きてね

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews: @ 0828062E
	.string "여기에 있으면 여러 포켓몬의\n"
	.string "이야기를 들을 수 있어서 재밌어$"
	@ ここに いると いろんな ポケモンのｎ
	@ はなしが きけるから おもしろいわ

SlateportCity_PokemonFanClub_Text_InterviewRequest: @ 08280674
	.string "너 그 {STR_VAR_1}{K_WAGWA}\n"
	.string "무척 사이가 좋은 모양이네\p"
	.string "맞다! 지금 나\n"
	.string "TV 취재로\p"
	.string "여러 포켓몬의 이야기를\n"
	.string "들으면서 돌아다니고 있는데\p"
	.string "괜찮다면 네 {STR_VAR_1}의\n"
	.string "이야기를 들려줄 수 있을까?$"
	@ きみの その §いとｎ
	@ とても なかが よさそうねｐ
	@ そうだ! いま わたしｎ
	@ テレビの しゅざいでｐ
	@ いろんな ポケモンの はなしをｎ
	@ きいて まわってるんだけどｐ
	@ よかったら きみの §いのｎ
	@ はなしを きかせて くれないかな?

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon: @ 0828073B
	.string "와아!\n"
	.string "고마워!\p"
	.string "그럼 {STR_VAR_1}의 이야기를\n"
	.string "아무거나 좋으니까 들려줘!$"
	@ わあ!ｎ
	@ ありがとう!ｐ
	@ じゃあ §いの はなしｎ
	@ なんでも いいので きかせてよ!

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2: @ 08280789
	.string "헤에-...\n"
	.string "재밌는 이야기였어!\p"
	.string "넌 정말로 {STR_VAR_1}{K_WAGWA}\n"
	.string "사이가 좋구나\p"
	.string "으-음 왠지 이 이야기로\n"
	.string "좋은 방송이 만들어질 것 같아!\p"
	.string "분명 재미있는 방송이\n"
	.string "될 테니까 기대하고 있어줘\p"
	.string "그럼 고마웠어\n"
	.string "바이바이!$"
	@ へ-……ｎ
	@ おもしろい はなし だね!ｐ
	@ きみは ほんとうに §いとｎ
	@ なかが いいんだねｐ
	@ う-ん なんか このはなしでｎ
	@ いい ばんぐみが できそうな よかん!ｐ
	@ きっと おもしろい ばんぐみにｎ
	@ するから たのしみに まっててねｐ
	@ じゃあ ありがとうねｎ
	@ バイバイ!

gTVFanClubOpinionsText00:: @ 08280886
	.string "“우리들!\n"
	.string "포켓몬 애호가클럽!”\p"
	.string "네 시작했습니다!\p"
	.string "이 방송은 여러분의\n"
	.string "의견을 바로 제가\l"
	.string "대신 외쳐드리는!\l"
	.string "굉장한 방송이죠!!\p"
	.string "자 오늘은 포켓몬 애호가클럽에\n"
	.string "가서 여러 이야기를 들어본\l"
	.string "리포터로부터 들어온 정보입니다!\p"
	.string "자 그럼 오늘의\n"
	.string "포켓몬 애호가는?\p"
	.string "음-...\p"
	.string "{STR_VAR_1}씨다-!!\p"
	.string "그럼 자신의 포켓몬\p"
	.string "{STR_VAR_2} “{STR_VAR_3}”에\n"
	.string "대한 뜨거운 기분을\p"
	.string "바로 제가 대신 TV를\n"
	.string "통해 외쳐드리겠습니다!\p"
	.string "우-!!\p"
	.string "렛츠 샤우트!!!$"
	@ 『ぼくたち!ｎ
	@ ポケモン だいすきクラブ!』ｐ
	@ はい はじまりました!ｐ
	@ このばんぐみは みなさんのｎ
	@ いけんを このわたしがｌ
	@ かわりに さけんで しまおう!ｌ
	@ という すごい ばんぐみ!!ｐ
	@ さて きょうは ポケモンだいすきクラブ にｎ
	@ いって いろんな はなしを きいてきたｌ
	@ リポ-タ-からの じょうほうだ!ｐ
	@ さて きょうのｎ
	@ ポケモンだいすき にんげんは?ｐ
	@ ん-……ｐ
	@ §いさんだ-!!ｐ
	@ それでは ごじぶんの ポケモンｐ
	@ §うの 「§え」にｎ
	@ ついての あつい きもちをｐ
	@ かわりに この わたくしが テレビにｎ
	@ むかって さけんで あげましょう!ｐ
	@ う-!!ｐ
	@ レッツ シャウト!!!

gTVFanClubOpinionsText01:: @ 08280A44
	.string "자 그럼 {STR_VAR_1}씨가 처음으로\n"
	.string "{STR_VAR_2}{K_WAGWA} 만났을 때 직관적으로\l"
	.string "생각한 것은...\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 좋은 외침입니다!\p"
	.string "마치 그때의 추억이\n"
	.string "되살아나는 듯하군요-!!$"
	@ さて §いさんが はじめてｎ
	@ §うと あったとき ちょっかんてきにｌ
	@ おもった ことは……ｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ ん- いい さけびだ!ｐ
	@ まるで そのときの おもいでがｎ
	@ よみがえる ようだ-!!

gTVFanClubOpinionsText02:: @ 08280AFC
	.string "자 그럼 {STR_VAR_1}씨가 매우 좋아하는\n"
	.string "{STR_VAR_2}{K_EULREUL} 뭔가에 비유한다면\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 굉장한 발상이군요!!\p"
	.string "격렬한 {STR_VAR_2}{K_EULREUL} 향한 생각이\n"
	.string "느껴지네요-!$"
	@ さて §いさんの だいすきなｎ
	@ §うを なにかに たとえると したらｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ ん- すごい はっそうだ!!ｐ
	@ はげしい §うへの おもいこみがｎ
	@ かんじられるね-!

gTVFanClubOpinionsText03:: @ 08280BC4
	.string "자 그럼 {STR_VAR_1}씨가 {STR_VAR_2}에게\n"
	.string "이끌린 이유는...\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "오-!! 엄청난 의견이군요-!\p"
	.string "{STR_VAR_2}{K_EULREUL} 얼마나 좋아하는지\n"
	.string "팍팍 전해져 옵니다-!$"
	@ さて §いさんが §うにｎ
	@ ひかれた りゆうは……ｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ お-!! すんばらしい いけんだ-!ｐ
	@ §うを どんなに すきかｎ
	@ ビンビン つたわって くるね-!

gTVFanClubOpinionsText04:: @ 08280C7A
	.string "음-? 아직 더 남아있네요-\n"
	.string "불러봅시다!\p"
	.string "으-음...\p"
	.string "{STR_VAR_1}씨에게 있어 포켓몬을\n"
	.string "한마디로 비유하자면 그것은!\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "브라보!!\p"
	.string "몇 번이고 외치고 싶어지는 말이군요-!\p"
	.string "그럼 좋은 외침도 들었으니\n"
	.string "다음에 또 봅시다!\p"
	.string "마지막으로 한 번 더\n"
	.string "다 같이 외쳐보죠!\p"
	.string "“{STR_VAR_3}!!”$"
	@ ん-? まだ つづきが ありますね-ｎ
	@ よんで みましょう!ｐ
	@ え-と……ｐ
	@ §いさんに とって ポケモンをｎ
	@ ひとことで たとえると すれば それは!ｌ
	@ ……ｐ
	@ 「§え!!」ｐ
	@ ブラボ-!!ｐ
	@ いままでの なかで いちばんｎ
	@ いい さけび だった-!ｐ
	@ 「§え!!」ｐ
	@ なんども さけびたくなる ことばだね-!ｐ
	@ それでは いいさけびと であった ところでｎ
	@ また じかい おあいしましょう!ｐ
	@ さいごに もういちどｎ
	@ みんなで さけびましょう!ｐ
	@ 「§え!!」

gTVFanClubText00:: @ 08280DEE
	.string "“우리들!\n"
	.string "포켓몬 애호가클럽!”\p"
	.string "네 시작했습니다!\p"
	.string "그럼 오늘은\n"
	.string "포켓몬 설문 코너!\p"
	.string "수많은 포켓몬과 트레이너의\n"
	.string "사연 중에서\p"
	.string "오늘은 어떤 이야기가\n"
	.string "튀어나올까요!?\l"
	.string "자 그럼 오늘의 사연은?\p"
	.string "음-...\p"
	.string "이거다!\p"
	.string "그럼 편지의 내용을 소개하겠습니다!!\n"
	.string "{STR_VAR_2}에게 보내는\n"
	.string "{STR_VAR_1}씨의 편지네요-\p"
	.string "그럼 얼마나 {STR_VAR_2}{K_EULREUL} 향한\n"
	.string "뜨거운 마음이 담겨있는지\l"
	.string "읽어보도록 합시다!\l"
	.string "음 그럼-...$"
	@ 『ぼくたち!ｎ
	@ ポケモン だいすきクラブ!』ｐ
	@ はい はじまりました!ｐ
	@ じゃあ きょうは ポケモンアンケ-トのｎ
	@ コ-ナ-から!ｐ
	@ かずある ポケモンと トレ-ナ-のｎ
	@ はなしの なかからｐ
	@ きょうは どんな はなしがｎ
	@ とびだして くるのでしょうか!?ｌ
	@ さて きょうの はなしは?ｐ
	@ ん-……ｐ
	@ これだ!ｐ
	@ では てがみの しょうかい から!!ｐ
	@ §うの ことに ついてｎ
	@ §いさん からの おてがみだ-ｐ
	@ では どれだけ §うへのｎ
	@ あつい いけんが かいてあるかｌ
	@ よませて もらいましょう!ｌ
	@ え-と……

gTVFanClubText01:: @ 08280F69
	.string "오-!!\n"
	.string "정말 굉장한 편지네요!!$"
	@ お-!!ｎ
	@ なんて すばらしい てがみなんだ!!

gTVFanClubText02:: @ 08280F88
	.string "마음에 들었으니 다시 한 번!$"
	@ きにいったから もういちど!

gTVFanClubText03:: @ 08280FA9
	.string "좋은 편지는\n"
	.string "몇 번이고 읽어도 좋네요-!!$"
	@ いい てがみはｎ
	@ なんど きいても いいね-!!

gTVFanClubText04:: @ 08280FD5
	.string "“{STR_VAR_3}”{K_I}라는 말\n"
	.string "덕분에 두근 하고 마음에 전해지는\l"
	.string "좋은 편지군요-!!$"
	@ 「§え」 っていう ことばのｎ
	@ おかげで グッと こころに つたわってくるｌ
	@ いい てがみに なっているね-!!

gTVFanClubText05:: @ 08281040
	.string "특히 “{STR_VAR_3}” 여기 이 부분!\p"
	.string "“{STR_VAR_3}”{K_I}라고 하는 부분이\n"
	.string "마음에 든다구요-!$"
	@ とくに「§え」って ところ!ｐ
	@ 「§え」っていう ところがｎ
	@ きにいったぞ-!

gTVFanClubText06:: @ 08281073
	.string "그런데 딱히 상관은 없지만\n"
	.string "“{STR_VAR_3}”{K_EUNNEUN} 참 좋은 말이죠\p"
	.string "실은 저도 “{STR_VAR_3}”{K_I}라고\n"
	.string "자주 말하고 다니거든요$"
	@ ところで あんまり かんけい ないけどｎ
	@ 「§え」って いいことば だよねｐ
	@ じつは おれも 「§え」ってｎ
	@ ことば さいきん よく つかうんだよね

gTVFanClubText07:: @ 082810E7
	.string "이 편지 저는\n"
	.string "{STR_VAR_3}점을 주고 싶네요-!\p"
	.string "다음은 좀 더 좋은 편지를\n"
	.string "기대하고 있을게요! {STR_VAR_1}씨!\p"
	.string "어이쿠 이제 시간이 다 됐군요!\n"
	.string "그럼 또 모두\l"
	.string "다음 방송에서 봅시다!!$"
	@ このてがみ じぶんてきにはｎ
	@ §えてん ていう かんじかな-!ｐ
	@ つぎは もっと いい てがみをｎ
	@ きたい してるよ! §いさん!!ｐ
	@ おっと もう こんなじかんだ!ｎ
	@ それでは また じかいｌ
	@ みなさま おあい しましょう!!

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest: @ 082811A0
	.string "으음?\n"
	.string "당신도 포켓몬을 좋아하시나요?\p"
	.string "전 방송국 사람인데\n"
	.string "최근 일어난\p"
	.string "트레이너와 포켓몬의 사건을\n"
	.string "들으면서 돌아다니고 있어요\p"
	.string "만약 괜찮다면 뭔가\n"
	.string "얘기를 들려주실 수 있나요?$"
	@ おや?ｎ
	@ あなたも ポケモンのことが おすきで?ｐ
	@ わたくし テレビきょくの ものでｎ
	@ さいきん おきたｐ
	@ トレ-ナ-と ポケモンの できごとをｎ
	@ きいて まわって いるのですｐ
	@ もし よければ なにかｎ
	@ はなしを きかせて くれませんかね?

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort: @ 0828126D
	.string "지금 최근 일어난\n"
	.string "트레이너와 포켓몬의 사건을\l"
	.string "들으면서 돌아다니고 있는데\p"
	.string "만약 괜찮다면 뭔가\n"
	.string "얘기를 들려주실 수 있을까요?$"
	@ いま さいきん おきたｎ
	@ トレ-ナ-と ポケモンの できごとをｌ
	@ きいて まわって いるのですがｐ
	@ もし よければ なにかｎ
	@ はなしを きかせて くれませんかね?

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon: @ 082812F2
	.string "오오 들려주시는 거군요!\n"
	.string "정말 감사합니다\p"
	.string "그럼 최근 일어난 거라면\n"
	.string "뭐든지 좋으니까\l"
	.string "이야기를 들려주세요!$"
	@ おお きかせて くれますか!ｎ
	@ ありがとう ございますｐ
	@ では さいきん おきたこと ならｎ
	@ なんでも よいのでｌ
	@ はなしを きかせて ください!

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory: @ 08281367
	.string "그렇습니까...\p"
	.string "그럼 또 뭔가 재밌는 이야기가\n"
	.string "있다면 들려주세요$"
	@ そうですか……ｐ
	@ では また なにか おもしろい はなしがｎ
	@ あったら きかせて くださいね

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview: @ 082813B9
	.string "...오오\n"
	.string "정말 좋은 이야기네요!\p"
	.string "이 이야기는 TV 방송에서\n"
	.string "쓰도록 하겠습니다!\p"
	.string "언젠가 방송할지도 모르니\n"
	.string "기대하면서 기다리고 있어주세요$"
	@ ……おおｎ
	@ なんて いいはなしだ!ｐ
	@ このはなし テレビでｎ
	@ つかわせて いただきます!ｐ
	@ いつか ほうそう するかも しれないのでｎ
	@ たのしみに まっていて くださいね

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory: @ 0828144D
	.string "으-음\n"
	.string "좋은 TV 방송이 만들어질 것 같네요!\p"
	.string "서둘러서 정리해야겠어요!$"
	@ う-んｎ
	@ いい テレビばんぐみが できそうだ!ｐ
	@ いそいで まとめないと!

gTVRecentHappeningsText00:: @ 0828149E
	.string "“최근의 사건”\p"
	.string "포켓몬 트레이너에겐\n"
	.string "매일이 하나의 이야기입니다\l"
	.string "그 이야기를 조금이라도\l"
	.string "소개할 수 있다면 좋겠지요\p"
	.string "자 그럼 오늘은 트레이너인\n"
	.string "{STR_VAR_1}씨의 이야기입니다\p"
	.string "{STR_VAR_1}씨 최근\n"
	.string "어떤 일이 있었던 걸까요?\l"
	.string "바로 봐보도록 합시다\p"
	.string "으-음...$"
	@ 『さいきんの できごと』ｐ
	@ ポケモントレ-ナ-に とってｎ
	@ まいにちが ものがたりですｌ
	@ その ものがたりを すこしでもｌ
	@ しょうかい できたら うれしいですねｐ
	@ さて きょうは トレ-ナ-のｎ
	@ §いさんの おはなしですｐ
	@ §いさん さいきんｎ
	@ どんなことが あったんで しょうか?ｌ
	@ さっそく みてみることに しましょうｐ
	@ え-と……

gTVRecentHappeningsText01:: @ 082815AF
	.string "과연 그렇군요 {STR_VAR_1}씨의\n"
	.string "주변에서 최근 일어나고 있는 일이\l"
	.string "손에 잡히듯이 알 것 같습니다$"
	@ なるほど §いさんのｎ
	@ まわりで さいきん おきている ことがｌ
	@ てに とるように わかりますね

gTVRecentHappeningsText02:: @ 08281636
	.string "“{STR_VAR_3}”{K_I}라는 말이\n"
	.string "이야기에 재미를 더해주네요$"
	@ 「§え」という ことばがｎ
	@ おはなしに スト-リ-を かんじさせますね

gTVRecentHappeningsText03:: @ 08281666
	.string "“{STR_VAR_3}”{K_I}라는 말\n"
	.string "덕분에 마치 광경이\l"
	.string "떠오르는 듯합니다$"
	@ 「§え」という ことばのｎ
	@ おかげで まるで じょうけいがｌ
	@ うかんで くるようですね

gTVRecentHappeningsText04:: @ 082816BA
	.string "이 이야기는 “{STR_VAR_3}”{K_I}라고 하는\n"
	.string "부분이 무척 인상적이었네요$"
	@ このおはなしは 「§え」というｎ
	@ ぶぶんが とても いんしょうてき ですね

gTVRecentHappeningsText05:: @ 082816EB
	.string "{STR_VAR_1}씨는 정말 좋은\n"
	.string "이야기를 들려주셨습니다\p"
	.string "이걸로 당신의 마음에도\n"
	.string "{STR_VAR_1}씨라고 하는 스토리가\l"
	.string "새겨진 것이겠지요\p"
	.string "그러면 이만\n"
	.string "다음 방송에서 만납시다$"
	@ §いさんは とても いいｎ
	@ おはなしを きかせて くれましたねｐ
	@ これで あなたの こころにもｎ
	@ §いさん という スト-リ-がｌ
	@ きざみ こまれましたよｐ
	@ それでは また じかいのｎ
	@ ほうそうで おあいしましょう

gTVMassOutbreakText00:: @ 0828178A
	.string "안녕하세요\n"
	.string "“포켓몬 뉴스”의 시간입니다\p"
	.string "보기 힘든 중요한 뉴스가\n"
	.string "들어왔습니다\p"
	.string "{STR_VAR_1}에서\n"
	.string "{STR_VAR_2}{K_IGA} 대량발생했다는\l"
	.string "보고가 있었습니다!\p"
	.string "{STR_VAR_2}{K_I}라고 하면\n"
	.string "제법 발견하기가 힘든\l"
	.string "포켓몬으로 유명했지요\p"
	.string "당신도 이 신비한\n"
	.string "{STR_VAR_2}의 대량발생을\l"
	.string "보고 오는 게 어떻겠습니까?\p"
	.string "이상으로\n"
	.string "“포켓몬 뉴스”였습니다$"
	@ こんにちはｎ
	@ 『ポケモン ニュ-ス』の じかんですｐ
	@ たいへん めずらしい ニュ-スがｎ
	@ はいって きましたｐ
	@ §いでｎ
	@ §うが たいりょうはっせい したｌ
	@ という ほうこくが ありました!ｐ
	@ §うと いえばｎ
	@ なかなか みつけることが むずかしいｌ
	@ ポケモンとしても ゆうめい ですねｐ
	@ あなたも このしんぴてきなｎ
	@ §うの たいりょうはっせいをｌ
	@ みにいっては いかが でしょうか?ｐ
	@ いじょうｎ
	@ 『ポケモン ニュ-ス』でした

gTV3CheersForPokeblocksText00:: @ 082818F4
	.string "사회자: 잘 지내셨나요?\n"
	.string "“포켓몬스넥 만세”의 시간입니다\p"
	.string "오늘의 포켓몬스넥은\n"
	.string "{STR_VAR_1}씨와 그 동료분들이\l"
	.string "블렌드한 포켓몬스넥입니다\p"
	.string "바로 제 미식가 포켓몬\n"
	.string "꼴깍몬에게 먹여보도록 하죠!\p"
	.string "...... ...... ...... ......\n"
	.string "...... ...... ...... ......$"
	@ しかい『ごきげん いかがですか?ｎ
	@ 『ポロック バンザイ!』の おじかんですｐ
	@ きょうの ポロックはｎ
	@ §いさんと その おなかまがｌ
	@ ブレンドした ポロックですｐ
	@ さっそく わたしの グルメな ポケモンｎ
	@ ゴクリンちゃんに たべさせて みましょう!ｐ
	@ …… …… …… ……ｎ
	@ …… …… …… ……

gTV3CheersForPokeblocksText01:: @ 082819C7
	.string "꼴깍몬: 꼴깍! 꼴깍!\p"
	.string "사회자: 오오! 무척 {STR_VAR_1}{K_I}라서\n"
	.string "“{STR_VAR_2}!”{K_I}라고 말하고 있네요\p"
	.string "분명 이건 {STR_VAR_3}씨가\n"
	.string "힘내서 돌린 덕분이겠죠!\p"
	.string "{STR_VAR_3}씨!\n"
	.string "잘 먹었습니다!$"
	@ ゴクリン『グビィ! グビィ!ｐ
	@ しかい『おお! とっても §いくてｎ
	@ 「§う!」と いってますねｐ
	@ きっと これは §えさんがｎ
	@ がんばって まわした おかげですね!ｐ
	@ §えさん!ｎ
	@ ごちそうさま でした!

gTV3CheersForPokeblocksText02:: @ 08281A2F
	.string "다음엔 조금 아쉬웠던\n"
	.string "{STR_VAR_1}씨가\l"
	.string "좀 더 잘 돌리면\l"
	.string "더욱 맛있어질지도 모르겠네요!$"
	@ こんかい いまいち だったｎ
	@ §いさんがｌ
	@ もっと じょうずに まわすことが できればｌ
	@ さらに おいしく なるかも しれませんよ!

gTV3CheersForPokeblocksText03:: @ 08281AAC
	.string "꼴깍몬: 꼴깍! 꼴깍!\p"
	.string "사회자: 으-음... 조금 {STR_VAR_1}{K_I}라서\n"
	.string "“{STR_VAR_2}!”{K_I}라고 말하고 있네요\p"
	.string "역시 {STR_VAR_3}씨의 실패가\n"
	.string "컸던 모양입니다...$"
	@ ゴクリン『グビィ! グビィ!ｐ
	@ しかい『う-ん…… ちょっと §いすぎてｎ
	@ 「§う!」と いってますね……ｐ
	@ やっぱり §えさんの しっぱいがｎ
	@ いたかった ですね……

gTV3CheersForPokeblocksText04:: @ 08281B28
	.string "이번에 가장 열심히 했던\n"
	.string "{STR_VAR_1}씨가 불쌍하네요...\p"
	.string "...{STR_VAR_2}씨!\n"
	.string "다음엔 열심히 해주세요!$"
	@ こんかい いちばん がんばっていたｎ
	@ §いさんが かわいそうです……ｐ
	@ ……§うさん!ｎ
	@ つぎは がんばって ください!

gTV3CheersForPokeblocksText05:: @ 08281B93
	.string "그럼 또 봅시다!\n"
	.string "표어는 “포켓몬스넥 만세!”$"
	@ では また おあいしましょう!ｎ
	@ あいことばは 『ポロック バンザイ!』

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer:: @ 8281BCB
	.string "여어!\p"
	.string "나 {STR_VAR_1}의 팬인데\n"
	.string "{STR_VAR_1}{K_EULREUL} 어떻게 생각해?$"
	@ やあ!ｐ
	@ ボク §いの ファン なんだけどｎ
	@ §い って どう おもう?

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink:: @ 8281C06
	.string "과연-\n"
	.string "그런 식으로 생각하고 있구나!$"
	@ なるほどね-ｎ
	@ そんな ふうに おもっているんだね!

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer:: @ 8281C3D
	.string "{STR_VAR_1}{K_EULREUL}\n"
	.string "잊어버린 거야...?$"
	@ §いの ことｎ
	@ わすれちゃったの……?

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2:: @ 8281C65
	.string "나 {STR_VAR_1}의 팬인데\n"
	.string "{STR_VAR_1}{K_EULREUL} 어떻게 생각해?$"
	@ ボク §いの ファン なんだけどｎ
	@ §い って どうおもう?

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer:: @ 8281C95
	.string "그럼 이번엔\n"
	.string "{STR_VAR_1}의 강함을\l"
	.string "점수로 평가해줄래?$"
	@ じゃあ こんどはｎ
	@ §いの つよさをｌ
	@ てんすうで おしえてくれる?

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2:: @ 8281CCD
	.string "{STR_VAR_1}{K_EULREUL}\n"
	.string "잊어버린 거야...?$"
	@ §いの ことｎ
	@ わすれちゃったの……?

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer:: @ 8281CF5
	.string "그렇구나!\n"
	.string "다음에 {STR_VAR_1}{K_EULREUL} 만나봐!\l"
	.string "너도 분명 팬이 되어버릴걸!$"
	@ そっか!ｎ
	@ こんど §いに あってみてよ!ｌ
	@ きみも きっと ファンに なっちゃうよ!

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo:: @ 8281D40
	.string "그렇구나-!\p"
	.string "고마워!\n"
	.string "무척 참고가 됐어!\p"
	.string "바로 {STR_VAR_1}의 팬끼리 함께\n"
	.string "그거에 대해서 얘기해볼게!$"
	@ そうなんだ-!ｐ
	@ ありがとう!ｎ
	@ とっても さんこうに なったよ!ｐ
	@ さっそく §いの ファン みんなでｎ
	@ この ことに ついて はなしあって みるよ!

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial:: @ 8281DB4
	.string "이제 곧 {STR_VAR_1}에 대한\n"
	.string "TV 방송이 나올 거야!\p"
	.string "너도 꼭 보도록 해!$"
	@ もうすぐ §いに ついてのｎ
	@ テレビ ばんぐみが ほうそう されるんだ!ｐ
	@ きみも ぜひ みてね!

gTVTrainerFanClubSpecialText00:: @ 08281DFB
	.string "“트레이너 팬클럽\n"
	.string "  {STR_VAR_1} 스페셜!”\p"
	.string "호연 각지에 계신\n"
	.string "{STR_VAR_1}팬 여러분\l"
	.string "오래 기다리셨습니다!\p"
	.string "오늘은 {STR_VAR_1}씨가\n"
	.string "“사람들에게 어떻게 보이고 있는지”를\l"
	.string "함께 생각해 봅시다!\p"
	.string "다른 트레이너를 대표해서\n"
	.string "{STR_VAR_2}씨로부터 의견을\l"
	.string "받아봤습니다!\p"
	.string "우선 {STR_VAR_1}씨를\n"
	.string "한마디로 표현하자면...\p"
	.string "“{STR_VAR_3}”\p"
	.string "역시 {STR_VAR_2}씨!\n"
	.string "정확한 말씀이군요!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}!”\n"
	.string "좋네요-\p"
	.string "계속해서 {STR_VAR_1}씨의 강함에\n"
	.string "점수를 매기자면...$"
	@ 『トレ-ナ- ファンクラブｎ
	@  §い スペシャル!』ｐ
	@ ホウエン かくちに いらっしゃるｎ
	@ §いファンの みなさまｌ
	@ おまたせしました!ｐ
	@ きょうは §いさんがｎ
	@ 「どのように おもわれているか?」をｌ
	@ いっしょに かんがえて いきましょう!ｐ
	@ ほかの トレ-ナ-さんを だいひょうしてｎ
	@ §うさん から ごいけんをｌ
	@ いただきました!ｐ
	@ まず §いさんをｎ
	@ ひとことで いい あらわすと……ｐ
	@ 「§え」ｐ
	@ さすが §うさん!ｎ
	@ よく みて いらっしゃいますね!ｐ
	@ 「§え §い!」ｎ
	@ いいですね-ｐ
	@ つづいて §いさんの つよさにｎ
	@ てんすうを つけると……

gTVTrainerFanClubSpecialText01:: @ 08281F90
	.string "“{STR_VAR_3}점!”\p"
	.string "굉장히 높은 점수네요\n"
	.string "{STR_VAR_2}씨는 {STR_VAR_1}씨를\l"
	.string "무척 존경하고 있는 거군요$"
	@ 「§えてん!」ｐ
	@ すごい こうとくてん ですねｎ
	@ §うさんは §いさんをｌ
	@ とっても そんけい していますね

gTVTrainerFanClubSpecialText02:: @ 08281FFA
	.string "“{STR_VAR_3}점!”\p"
	.string "좋은 점수네요\n"
	.string "{STR_VAR_2}씨는 {STR_VAR_1}씨를\l"
	.string "라이벌로 여기고 있는 거군요$"
	@ 「§えてん!」ｐ
	@ いい てんすう ですねｎ
	@ §うさんは §いさんをｌ
	@ ライバル として みていますね

gTVTrainerFanClubSpecialText03:: @ 08282052
	.string "“{STR_VAR_3}점!”\p"
	.string "좀 별로인 점수네요\n"
	.string "{STR_VAR_2}씨는 {STR_VAR_1}씨를\l"
	.string "자기보다 아래라고 보고 있는 거군요$"
	@ 「§えてん!」ｐ
	@ ちょっと いまいち ですねｎ
	@ §うさんは §いさんをｌ
	@ じぶんの こぶん として みていますね

gTVTrainerFanClubSpecialText04:: @ 082820B2
	.string "“{STR_VAR_3}점!”\p"
	.string "너무 짠 점수네요\n"
	.string "{STR_VAR_2}씨는 {STR_VAR_1}씨를\l"
	.string "조무래기로 보고 있는 거군요$"
	@ 「§えてん!」ｐ
	@ ひどい てんすう ですねｎ
	@ §うさんは §いさんをｌ
	@ したっぱ として みていますね

gTVTrainerFanClubSpecialText05:: @ 0828210E
	.string "이야- 그렇군요!\p"
	.string "{STR_VAR_1}씨에 대해\n"
	.string "새로운 발견이 있었습니다!\p"
	.string "그럼 마지막으로 {STR_VAR_2}씨의\n"
	.string "말로 끝내보도록 하겠습니다!\p"
	.string "{STR_VAR_1} {STR_VAR_3}!$"
	@ いや- なるほど!ｐ
	@ §いさんに ついてｎ
	@ あたらしい はっけんが ありましたね!ｐ
	@ では さいごに §うさんのｎ
	@ ことばで おわかれ しましょう!ｐ
	@ §い §え!

gTVNameRaterText00:: @ 0828218A
	.string "“이름 평가”의\n"
	.string "시간이 돌아왔습니다\p"
	.string "당신이 붙인 닉네임에서\n"
	.string "포켓몬의 미래를\l"
	.string "점쳐 드립니다\p"
	.string "조금이라도 어드바이스가\n"
	.string "된다면 좋을 것 같군요\p"
	.string "오늘은 {STR_VAR_1}씨의 포켓몬\n"
	.string "{STR_VAR_2} “{STR_VAR_3}”의\l"
	.string "닉네임을 점쳐 보겠습니다\p"
	.string "흐음흐음...\p"
	.string "흐-음\n"
	.string "이 닉네임은...$"
	@ 『せいめい はんだん』のｎ
	@ じかんが やって まいりましたｐ
	@ あなたの つけた ニックネ-ムからｎ
	@ ポケモンの ことをｌ
	@ うらなって さしあげますｐ
	@ すこしでも アドバイスにｎ
	@ なれば よいと おもいますなｐ
	@ きょうは §いさんの ポケモンｎ
	@ §うの 「§え」のｌ
	@ ニックネ-ムを うらなって みますかなｐ
	@ ふむふむ……ｐ
	@ う-むｎ
	@ この ニックネ-ムは……

gTVNameRaterText01:: @ 0828229E
	.string "여러 가지 분야에서 재능을\n"
	.string "발휘할 수 있는 닉네임이군요!\p"
	.string "앞으로 여러 일에\n"
	.string "도전하면 좋을 거라고 생각합니다$"
	@ いろいろな ところで さいのうをｎ
	@ はっき できる ニックネ-ム ですなぁ!ｐ
	@ こんご いろいろな ことにｎ
	@ チャレンジ すると よいと おもいますよ

gTVNameRaterText02:: @ 08282317
	.string "{STR_VAR_1}씨와의 궁합이\n"
	.string "무척 좋은 닉네임이군요!\p"
	.string "서로 잘 맞는\n"
	.string "좋은 콤비가 될 거라고 생각합니다$"
	@ §いさん との あいしょうがｎ
	@ とても よい ニックネ-ム ですなぁ!ｐ
	@ いきの ぴったり あったｎ
	@ よい コンビに なると おもいますよ

gTVNameRaterText03:: @ 0828239D
	.string "무척 개성적인 포켓몬이\n"
	.string "되는 닉네임이군요!\p"
	.string "제대로 키운다면 그 개성이\n"
	.string "커다란 꽃을 피울 거라고 생각합니다$"
	@ とても こせいてきな ポケモンにｎ
	@ なる ニックネ-ム ですなぁ!ｐ
	@ きちんと そだてて やれば その こせいがｎ
	@ おおきく はな ひらくと おもいますよ

gTVNameRaterText04:: @ 08282418
	.string "무척 배려심 있는\n"
	.string "포켓몬이 되는 닉네임이군요!\p"
	.string "제대로 키운다면\n"
	.string "그에 응해줄 거라고 생각합니다$"
	@ とても おもいやりの あるｎ
	@ ポケモンに なる ニックネ-ム ですなぁ!ｐ
	@ きちんと そだてて やればｎ
	@ それに こたえて くれると おもいますよ

gTVNameRaterText05:: @ 082824A6
	.string "장래에 거물이 되는\n"
	.string "무척 좋은 닉네임이군요!\p"
	.string "장래가 매우\n"
	.string "기대가 되는 포켓몬입니다$"
	@ しょうらい おおものに なるｎ
	@ とても よい ニックネ-ム ですなぁ!ｐ
	@ しょうらいが とてもｎ
	@ たのしみな ポケモン ですな

gTVNameRaterText06:: @ 08282522
	.string "무척 건강한 포켓몬이\n"
	.string "되는 닉네임이군요!\p"
	.string "언제나 건강하게\n"
	.string "있어줄 겁니다$"
	@ とても けんこうてきな ポケモンにｎ
	@ なる よい ニックネ-ム ですなぁ!ｐ
	@ いつまでも げんきでｎ
	@ いて くれる でしょう

gTVNameRaterText07:: @ 082825A1
	.string "무척 활동적인 포켓몬이\n"
	.string "되는 좋은 닉네임이군요!\p"
	.string "포켓몬 승부에서\n"
	.string "큰 활약을 할 거라고 생각합니다$"
	@ とても かつどうてきな ポケモンにｎ
	@ なる よい ニックネ-ム ですなぁ!ｐ
	@ ポケモンしょうぶ ではｎ
	@ おおいに かつやく すると おもいますよ

gTVNameRaterText08:: @ 08282623
	.string "무척 애교가 많은\n"
	.string "포켓몬이 되는 닉네임이군요!\p"
	.string "포켓몬 콘테스트에서\n"
	.string "매우 큰 활약을 할 거라고 생각합니다$"
	@ とても あいきょうの あるｎ
	@ ポケモンになる ニックネ-ム ですなぁ!ｐ
	@ ポケモンコンテスト ではｎ
	@ とても かつやく できると おもいますよ

gTVNameRaterText09:: @ 082826B4
	.string "이 “{STR_VAR_1}”{K_I}라는 닉네임은\n"
	.string "“{STR_VAR_3}” 문자를 중심으로\l"
	.string "여기에 “{STR_VAR_2}”{K_IGA} 붙어서\p"
	.string "묵직한 느낌을 주는\n"
	.string "좋은 닉네임이 되었군요$"
	@ この 「§い」という ニックネ-ムはｎ
	@ 「§え」の もじを ちゅうしん としてｌ
	@ これに 「§う」が つくことでｐ
	@ どっしり としたｎ
	@ よい ニックネ-ムに なっていますな

gTVNameRaterText10:: @ 0828274D
	.string "이 “{STR_VAR_1}”{K_I}라는 닉네임은\n"
	.string "매우 형태가 좋은\l"
	.string "닉네임이군요\p"
	.string "닉네임에 “{STR_VAR_2}”{K_WAGWA} “{STR_VAR_3}”{K_IGA}\n"
	.string "들어가 있는 게 아주 좋습니다!$"
	@ この 「§い」という ニックネ-ムはｎ
	@ とても かたちの よいｌ
	@ ニックネ-ム ですなぁｐ
	@ ニックネ-ムに 「§う」と 「§え」がｎ
	@ はいって いるのが とても よい!

gTVNameRaterText11:: @ 082827CB
	.string "이 “{STR_VAR_1}”{K_I}라는 닉네임은\n"
	.string "무척 울림이 좋은\l"
	.string "닉네임이군요\p"
	.string "“{STR_VAR_2}”{K_I}라는 문자 뒤에\n"
	.string "“{STR_VAR_3}”{K_IGA} 오는 게 아주 좋습니다!$"
	@ この 「§い」という ニックネ-ムはｎ
	@ とても ながれの よいｌ
	@ ニックネ-ム ですなぁｐ
	@ 「§う」の もじの あとにｎ
	@ 「§え」がくる ながれが とても よい!

gTVNameRaterText12:: @ 08282849
	.string "...자 그럼 그 밖에\n"
	.string "좋은 닉네임의 예시로서$"
	@ ……さて そのほかにｎ
	@ よい ニックネ-ムの れい として

gTVNameRaterText13:: @ 08282883
	.string "트레이너 {STR_VAR_1}씨의\n"
	.string "이름을 따서\p"
	.string "“{STR_VAR_2}{STR_VAR_3}”{K_I}라고 하는 것도\l"
	.string "무척 좋은 닉네임이 되겠군요$"
	@ トレ-ナ-の §いさんのｎ
	@ なまえを もってきてｐ
	@ 「§う§え」と いうのもｎ
	@ とても よい ニックネ-ム ですなぁ

gTVNameRaterText14:: @ 082828E4
	.string "아니면 “{STR_VAR_2}{STR_VAR_3}”도\n"
	.string "좋은 닉네임이 될 테고요$"
	@ もしくは 「§う§え」とｎ
	@ いうのも よい ニックネ-ム ですな

gTVNameRaterText15:: @ 08282912
	.string "원래 포켓몬의 이름인\n"
	.string "{STR_VAR_2}에서 살짝 따와서\l"
	.string "{STR_VAR_1}{STR_VAR_3}{K_I}나$"
	@ もとの ポケモンの なまえｎ
	@ §うから すこし もらってｐ
	@ 「§い§え」や

gTVNameRaterText16:: @ 0828296C
	.string "“{STR_VAR_1}{STR_VAR_3}”도\n"
	.string "좋은 닉네임이 되겠군요$"
	@ 「§い§え」と いうのもｎ
	@ よい ニックネ-ム ですなぁ

gTVNameRaterText17:: @ 08282996
	.string "무슨 일이 있어도 다른 포켓몬의 이름\n"
	.string "예를 들어 {STR_VAR_2}의 이름을 붙여\p"
	.string "“{STR_VAR_1}{STR_VAR_3}” 같은\n"
	.string "닉네임으로 지으면 안 됩니다$"
	@ まちがっても ほかの ポケモンの なまえｎ
	@ たとえば §うの なまえを つけてｐ
	@ 「§い§え」の ようなｎ
	@ ニックネ-ムに しては いけませんな

gTVNameRaterText18:: @ 08282A36
	.string "으음 그건 그렇고 {STR_VAR_1}{K_EUNNEUN}\n"
	.string "제법 좋은 닉네임이군요\p"
	.string "앞으로도 “{STR_VAR_1}”{K_EULREUL}\n"
	.string "소중하게 여겨주십시오\p"
	.string "그럼 인연이 있으면\n"
	.string "또 보지요$"
	@ うむ それにしても 「§い」はｎ
	@ なかなか よい ニックネ-ム ですなｐ
	@ これからも 「§い」の ことをｎ
	@ たいせつに して ほしい ものですなぁｐ
	@ それでは またｎ
	@ ごえんが あれば

gTVPokemonAnglerText00:: @ 08282ACF
	.string "“{STR_VAR_2}{K_EULREUL} 낚다”\p"
	.string "아나운서: 안녕하세요! 오늘은\n"
	.string "{STR_VAR_2} 낚시를 배우러 왔습니다\p"
	.string "그럼 선생님 {STR_VAR_2}{K_EULREUL} 낚는 데\n"
	.string "필요한 요령이 있나요?\p"
	.string "선생님: 음?\n"
	.string "{STR_VAR_2}{K_EULREUL} 낚는 요령 말인가\l"
	.string "그건 차분히 기다리는 것이라네\p"
	.string "저기 있는 {STR_VAR_1}씨를 보게나\n"
	.string "이 얼마나 훌륭한 모습인가?\p"
	.string "이미 이것도 저것도...\n"
	.string "{STR_VAR_3}번은 놓쳤지만\p"
	.string "포기하지 않고 계속 기다리고 있네\n"
	.string "저 모습이 {STR_VAR_2} 낚기의 극의인 게야\p"
	.string "아나운서: 그렇군요...\p"
	.string "아! {STR_VAR_1}씨\n"
	.string "드디어 {STR_VAR_2}{K_EULREUL} 낚았습니다!\l"
	.string "울 거 같은 표정으로 기뻐하고 있어요!\p"
	.string "...저도 저런 기뻐하는 듯한\n"
	.string "표정을 봤더니 낚시하고 싶어졌습니다!\p"
	.string "여러분들도 이 방송을 계기로\n"
	.string "{STR_VAR_2} 낚기를 해보면 어떨까요?\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만납시다$"
	@ 『§うを つる』ｐ
	@ アナウンサ-「こんにちは! きょうはｎ
	@ §うつりを おそわりに きましたｐ
	@ さて せんせい §うを つるにはｎ
	@ どんな コツが いるのですか?ｐ
	@ せんせい「ん?ｎ
	@ §うを つる コツかいｌ
	@ それはね じ-っと まつことだねｐ
	@ ほら あそこにいる §いさんｎ
	@ なんて いい みほん じゃないか?ｐ
	@ もう かれこれ……ｎ
	@ §えかいは にげられて いるけどｐ
	@ あきらめず じ-っと まちつづけて いるよｎ
	@ あれが §うつりの ごくいだねｐ
	@ アナウンサ-「なるほど……ｐ
	@ あ! §いさんｎ
	@ やっと §うを つりました!ｌ
	@ なきそうな かおして よろこんで ますよ!ｐ
	@ …わたしも あんな うれしそうなｎ
	@ かおを みたら つりをしたく なりました!ｐ
	@ みなさんも これを きに §うつりをｎ
	@ してみては いかがですか?ｐ
	@ それでは また じかいのｎ
	@ ほうそうで あいましょう

gTVPokemonAnglerText01:: @ 08282D7C
	.string "“{STR_VAR_2}{K_EULREUL} 낚다”\p"
	.string "인터뷰어: 안녕하세요! 오늘은\n"
	.string "{STR_VAR_2} 낚시를 배우러 왔습니다\p"
	.string "그럼 선생님 {STR_VAR_2}{K_EULREUL} 낚는 데\n"
	.string "필요한 요령이 있나요?\p"
	.string "선생님: 음?\n"
	.string "{STR_VAR_2}{K_EULREUL} 낚는 요령 말인가\l"
	.string "그건 낚싯대를 폭풍같이\l"
	.string "다루는 것이라네!\p"
	.string "자 저기 있는 {STR_VAR_1}씨의\n"
	.string "낚싯대 다루는 실력을 보게나!\p"
	.string "벌써 {STR_VAR_3}마리를 연속으로\n"
	.string "낚고 있다네!\p"
	.string "인터뷰어: 괴 굉장해요!\n"
	.string "그야말로 폭풍처럼...\p"
	.string "...저렇게 굉장한 기술을 봤더니\n"
	.string "저도 낚시하고 싶어졌습니다!\p"
	.string "여러분들도 이 방송을 계기로\n"
	.string "{STR_VAR_2} 낚기를 해보면 어떨까요?\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만납시다$"
	@ 『§うを つる』ｐ
	@ インタビュア-『こんにちは! きょうはｎ
	@ §うつりを おそわりに きましたｐ
	@ さて せんせい §うを つるにはｎ
	@ どんな コツが いるのですか?ｐ
	@ せんせい『ん?ｎ
	@ §うを つる コツかいｌ
	@ それはね つりざおを あらしの ごとくｎ
	@ あつかう ことだね!ｐ
	@ ほら あそこにいる §いさんのｎ
	@ つりざお さばきを みてみなさい!ｐ
	@ もう §えひきは れんぞくでｎ
	@ つって いるぞ!ｐ
	@ インタビュア-『すっ すごい!ｎ
	@ まさに あらしの ようね……ｐ
	@ ……あんなに すごい わざを みたらｎ
	@ わたしも つりを したくなって きました!ｐ
	@ みなさんも これを きに §うつりをｎ
	@ してみては いかがですか?ｐ
	@ それでは また じかいのｎ
	@ ほうそうで あいましょう

gTVPokemonTodayFailedText00:: @ 08282F9B
	.string "안녕-!\p"
	.string "“오늘의 포켓몬”의\n"
	.string "시간이야-!!\p"
	.string "누님: 안녕 다들 잘 지내지?\n"
	.string "오늘은 {STR_VAR_1}씨의 포켓몬\l"
	.string "{STR_VAR_2}{K_EULREUL} 소개할게!\p"
	.string "형님: 소개할게-!$"
	@ こんにちは-!ｐ
	@ 『きょうの ポケモン』のｎ
	@ じかんだよ-!!ｐ
	@ おねえさん『こんにちは みんな げんき!ｎ
	@ きょうは §いさんの ポケモンｌ
	@ §うの しょうかいを するよ!ｐ
	@ おにいさん『するぞ-!

gTVPokemonTodayFailedText01:: @ 0828304D
	.string "아!\n"
	.string "{STR_VAR_1}씨라면...\p"
	.string "누님 지난번에\n"
	.string "나 봐버렸다고!!\p"
	.string "누님: 봐버렸다니\n"
	.string "뭘 봐버렸는데?\p"
	.string "형님: 지난번에\n"
	.string "{STR_VAR_2}에 갔을 때\l"
	.string "{STR_VAR_1}씨를 봤거든\p"
	.string "마침 {STR_VAR_3}{K_EULREUL}\n"
	.string "잡는 중인 것 같았는데...$"
	@ あ!ｎ
	@ §いさん といえば……ｐ
	@ おねえさん このまえｎ
	@ ぼく みちゃった!!ｐ
	@ おねえさん『みちゃった ってｎ
	@ なにを みちゃったの?ｐ
	@ おにいさん『このまえｎ
	@ §うに でかけたときｌ
	@ §いさんを みかけたんだｐ
	@ ちょうど §えを つかまえてるｎ
	@ ところ だったん だけど……

gTVPokemonTodayFailedText02:: @ 08283135
	.string "도중에 포켓몬이\n"
	.string "도망쳐버렸어!!\p"
	.string "몬스터볼을 {STR_VAR_2}개나 던졌는데도\n"
	.string "소용없었지...\p"
	.string "포켓몬이 도망쳤을 때\n"
	.string "{STR_VAR_1}씨가 지은 분한 표정은\l"
	.string "정말 엄청났어...$"
	@ とちゅうで ポケモンにｎ
	@ にげられ ちゃったんだよ!!ｐ
	@ ボ-ルを §うこも なげたのにｎ
	@ ぜんぶ むだ……ｐ
	@ ポケモンに にげられた ときのｎ
	@ §いさんの くやしがった かおｌ
	@ すごかったなぁ……

gTVPokemonTodayFailedText03:: @ 082831DF
	.string "도중에 실수로 포켓몬을\n"
	.string "쓰러뜨리고 말았어!!\p"
	.string "몬스터볼을 {STR_VAR_2}개나 던졌는데도\n"
	.string "소용없었지...\p"
	.string "포켓몬을 쓰러뜨렸을 때의\n"
	.string "{STR_VAR_1}씨가 아연실색한 표정은\l"
	.string "정말 말할 수 없을 정도였지...$"
	@ とちゅうで まちがって ポケモンをｎ
	@ たおし ちゃったんだよ!!ｐ
	@ ボ-ルを §うこも なげたのにｎ
	@ ぜんぶ むだ……ｐ
	@ ポケモンを たおしちゃった ときのｎ
	@ §いさんの あぜんと した かおｌ
	@ なんとも いえなかったなぁ……

gTVPokemonTodayFailedText04:: @ 08283294
	.string "누님: 야야!\n"
	.string "남의 불행에 웃으면 안 되지\p"
	.string "아아 {STR_VAR_1}씨\n"
	.string "엄청 불쌍하다...\p"
	.string "형님: 그러게!\n"
	.string "웃어서 죄-송합니다$"
	@ おねえさん『こらこらっ!ｎ
	@ たにんの ふこうを わらっちゃ だめだよｐ
	@ あぁ §いさんｎ
	@ とっても かわいそう……ｐ
	@ おにいさん『は-い!ｎ
	@ わらって すいませ-ん

gTVPokemonTodayFailedText05:: @ 08283337
	.string "누님: 풉!\p"
	.string "형님: 아! 지금\n"
	.string "웃은 거지!?\p"
	.string "누님: 뭐!?\p"
	.string "안 웃었거든\n"
	.string "안 웃었어!\p"
	.string "아아 {STR_VAR_1}씨\n"
	.string "정말 불쌍하다...\p"
	.string "형님: ...$"
	@ おねえさん『プッ!ｐ
	@ おにいさん『あ! いまｎ
	@ わらったでしょ!?ｐ
	@ おねえさん『え!?ｐ
	@ わらってないｎ
	@ わらってないよ!ｐ
	@ あぁ §いさんｎ
	@ とっても かわいそう……ｐ
	@ おにいさん『……

gTVPokemonTodayFailedText06:: @ 082833C6
	.string "누님: 그럼 분위기를 전환해서\n"
	.string "포켓몬을 소개...\p"
	.string "어?\n"
	.string "벌써 시간 다 됐어?\p"
	.string "나 참! 포켓몬을\n"
	.string "소개하지도 못했잖아!\p"
	.string "형님: 다음 시간에 또 보자고!\p"
	.string "누님: 멋대로 끝내지 마-!!$"
	@ おねえさん『じゃあ きを とりなおしてｎ
	@ ポケモンの しょうかいを……ｐ
	@ え?ｎ
	@ もう じかんが ない?ｐ
	@ もう! ポケモンの しょうかいがｎ
	@ できなかった じゃない!ｐ
	@ おにいさん『また じかい あおうぜ!ｐ
	@ おねえさん『かってに しめるな-!!

gTVPokemonTodaySuccessfulText00:: @ 082834A0
	.string "안녕-!\p"
	.string "“오늘의 포켓몬”의\n"
	.string "시간이야-!!\p"
	.string "누님: 안녕 다들 잘 지내지?\n"
	.string "오늘은 {STR_VAR_1}씨의 포켓몬\l"
	.string "{STR_VAR_2}{K_EULREUL} 소개할게!\p"
	.string "형님: 소개할게-!$"
	@ こんにちは-!ｐ
	@ 『きょうの ポケモン』のｎ
	@ じかんだよ-!!ｐ
	@ おねえさん『こんにちは みんな げんき!ｎ
	@ きょうは §いさんの ポケモンｌ
	@ §うの しょうかいを するよ!ｐ
	@ おにいさん『するぞ-!

gTVPokemonTodaySuccessfulText01:: @ 08283552
	.string "누님: {STR_VAR_1}씨는\n"
	.string "{STR_VAR_2}에게 “{STR_VAR_3}”{K_I}라고\p"
	.string "닉네임을 붙여서 소중하게\n"
	.string "키우고 있대!$"
	@ おねえさん『§いさんはｎ
	@ §うに 「§え」ってｐ
	@ ニックネ-ムを つけて たいせつにｎ
	@ そだてて るんだって!

gTVPokemonTodaySuccessfulText02:: @ 082835AE
	.string "형님: 참고로\n"
	.string "몬스터볼을 총 {STR_VAR_3}개 던져서\p"
	.string "마지막에는 {STR_VAR_2}{K_EU}로\n"
	.string "잡았다는 소문도 있어!$"
	@ おにいさん『ちなみにｎ
	@ ボ-ルを ぜんぶで §えこ なげてｐ
	@ さいごは §うでｎ
	@ つかまえたって うわさだよ!

gTVPokemonTodaySuccessfulText03:: @ 0828361F
	.string "누님: 그렇게 간단하게\n"
	.string "포획하다니\p"
	.string "{STR_VAR_1}씨와 {STR_VAR_2}의\l"
	.string "만남은 분명 운명적이었을 거야!$"
	@ おねえさん『そんなに かんたんにｎ
	@ つかまえる なんてｐ
	@ §いさんと §うのｎ
	@ であいは きっと うんめい だったのよ!

gTVPokemonTodaySuccessfulText04:: @ 08283685
	.string "누님: 고생해서 겨우\n"
	.string "잡은 포켓몬은\l"
	.string "소중히 여기게 된다고도 하고!$"
	@ おねえさん『くろうして やっとｎ
	@ つかまえた ポケモンはｌ
	@ だいじに されるって いうしね!

gTVPokemonTodaySuccessfulText05:: @ 0828370C
	.string "누님: {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 소중한 마스터볼을\p"
	.string "써서 겨우 잡은\n"
	.string "추억의 포켓몬이래!\p"
	.string "형님: 오-! 굉장한걸-!\p"
	.string "누님: {STR_VAR_1}씨 정말로\n"
	.string "{STR_VAR_2}{K_EULREUL} 잡고 싶었구나!$"
	@ おねえさん『§いさんのｎ
	@ §うは だいじな マスタ-ボ-ルをｐ
	@ つかって やっと つかまえたｎ
	@ おもいでの ポケモン なんだって!ｐ
	@ おにいさん『え-! すごいね-!ｐ
	@ おねえさん『§いさん ほんとうにｎ
	@ §うを つかまえ たかったんだね!

gTVPokemonTodaySuccessfulText06:: @ 082837C2
	.string "형님: 그럼 그\n"
	.string "{STR_VAR_2}에게 “{STR_VAR_3}”{K_I}라는\p"
	.string "닉네임을 붙여준\n"
	.string "{STR_VAR_1}씨의 센스가 이해가 되네!\p"
	.string "누님: 그렇네-$"
	@ おにいさん『でも そのｎ
	@ §うに 「§え」ってｐ
	@ ニックネ-ムを つけるあたりｎ
	@ §いさんの センスが わかるね!ｐ
	@ おねえさん『そうだね-

gTVPokemonTodaySuccessfulText07:: @ 08283848
	.string "나라면 {STR_VAR_3} 같은 거에\n"
	.string "그 닉네임을 짓겠지만!\p"
	.string "형님: 오-!\n"
	.string "그건 또 새로운걸!$"
	@ わたしなら §え とかにｎ
	@ そのニックネ-ムを つけちゃう けどね!ｐ
	@ おにいさん『お-!ｎ
	@ それ なかなか あたらしいかも!

gTVPokemonTodaySuccessfulText08:: @ 082838C2
	.string "“{STR_VAR_2}”{K_I}라-\n"
	.string "정말 {STR_VAR_1}{K_I}라는 느낌이네!\p"
	.string "봐봐! 문자의 분위기가 왠지 모르게\n"
	.string "{STR_VAR_1} 같은 느낌이 나잖아!\p"
	.string "형님: ...그렇네$"
	@ 「§う」か-ｎ
	@ まさに §いって かんじよね!ｐ
	@ ほら! もじの ふんいきとか なんとなくｎ
	@ §いって かんじが するもの!ｐ
	@ おにいさん『……そうだね

gTVPokemonTodaySuccessfulText09:: @ 0828394A
	.string "내가 아는 한 {STR_VAR_1}에게\n"
	.string "“{STR_VAR_2}”{K_I}라는 닉네임을\l"
	.string "지은 트레이너는 없어!\p"
	.string "형님: 그만큼 닉네임을 짓는\n"
	.string "센스가 좋다는 거겠지!$"
	@ わたしの しってるかぎり §いにｎ
	@ 「§う」って ニックネ-ムをｌ
	@ つけている トレ-ナ-なんて いないよ!ｐ
	@ おにいさん『それだけ ニックネ-ムをつけるｎ
	@ センスが いいって ことだよ!

gTVPokemonTodaySuccessfulText10:: @ 082839EA
	.string "나도 다음에 포켓몬을 잡으면\n"
	.string "“{STR_VAR_2}”{K_I}라고 지어볼까?\p"
	.string "형님: 뭐? 그럼 나도\n"
	.string "“{STR_VAR_2}”{K_I}라고 지어야지-!$"
	@ わたしも こんど ポケモンを つかまえたらｎ
	@ 「§う」って つけて みようかな?ｐ
	@ おにいさん『え? じゃあ ぼくもｎ
	@ 「§う」って つけよ-!

gTVPokemonTodaySuccessfulText11:: @ 08283A5F
	.string "누님: 아! 벌써 시간 다 됐네!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자\p"
	.string "형님: 다음엔 당신의 포켓몬을\n"
	.string "소개할지도 모른다고!$"
	@ おねえさん『あ! もう こんなじかん!ｐ
	@ それでは また じかいのｎ
	@ ほうそうで おあいしましょうｐ
	@ おにいさん『つぎは あなたの ポケモンをｎ
	@ しょうかい するかもよ!

gTVTodaysSmartShopperText00:: @ 08283B05
	.string "안녕하세요\p"
	.string "“오늘의 쇼핑 전문가”의\n"
	.string "시간입니다\p"
	.string "인터뷰어: 여러분 잘 지내셨나요?\p"
	.string "오늘은 {STR_VAR_2}의\n"
	.string "가게에 와 있습니다\p"
	.string "최근 무엇이 팔리고 있는지\n"
	.string "체크해 봅시다!$"
	@ こんにちはｐ
	@ 『きょうの かいもの じょうず』のｎ
	@ じかん ですｐ
	@ インタビュア-『みなさん おげんきですか?ｐ
	@ きょうは §うのｎ
	@ おみせに きていますｐ
	@ さいきん なにが うれているのかｎ
	@ チェック してみましょう!

gTVTodaysSmartShopperText01:: @ 08283BAF
	.string "그럼 점원씨를\n"
	.string "인터뷰해 봅시다\l"
	.string "어떻습니까 장사는 잘 되시나요?\p"
	.string "점원: 네 덕분에요\p"
	.string "특히 {STR_VAR_2}{K_IGA}\n"
	.string "지금 잘 팔리고 있습니다\p"
	.string "지난번에도 {STR_VAR_1}씨라는 분이\n"
	.string "{STR_VAR_3}개나 사가셨지요$"
	@ それでは てんいんさんにｎ
	@ インタビュ- してみましょうｌ
	@ どうですか うれて いますか?ｐ
	@ てんいん『はい おかげさまでｐ
	@ とくに §うがｎ
	@ いま うれて いるんですよｐ
	@ このまえも §いさん というｎ
	@ かたが §えこも かって いかれました

gTVTodaysSmartShopperText02:: @ 08283C81
	.string "인터뷰어: {STR_VAR_2}{K_EULREUL}\n"
	.string "{STR_VAR_3}개나 사다니 굉장하군요!\p"
	.string "어쩌면 {STR_VAR_1}씨는\n"
	.string "앞으로 먼 곳까지 가기 위해서\l"
	.string "여행 준비를 했던 걸지도 모르겠네요\p"
	.string "역시 여행에는 {STR_VAR_2}{K_IGA} 최고죠!$"
	@ インタビュア-『§うをｎ
	@ §えこも かうなんて すごいですね!ｐ
	@ もしかしたら §いさんはｎ
	@ これから とおくまで いくためのｌ
	@ たびじたくを していたのかも しれませんねｐ
	@ やっぱり たびには §うですね!

gTVTodaysSmartShopperText03:: @ 08283D32
	.string "인터뷰어: {STR_VAR_2}{K_I}라고 하니\n"
	.string "저 어째선지 지난번에\l"
	.string "{STR_VAR_3}개나 사버렸어요!\p"
	.string "{STR_VAR_2}{K_EUNNEUN} 좋으니까요-!$"
	@ インタビュア-『§う といえばｎ
	@ わたし なんか このまえｌ
	@ §えこも かいましたよ!ｐ
	@ §うって いいですからね-!

gTVTodaysSmartShopperText04:: @ 08283D99
	.string "인터뷰어: {STR_VAR_2}{K_EULREUL}!!\n"
	.string "{STR_VAR_3}개나요!?\p"
	.string "...그렇게 사는 사람이\n"
	.string "있다니 몰랐어요\p"
	.string "저는 한두 개 정도\n"
	.string "사는 게 다인데...$"
	@ インタビュア-『§うを!!ｎ
	@ §えこも!?ｐ
	@ ……そんなに かうひとがｎ
	@ いるなんて しらなかったわｐ
	@ わたし なんか せいぜい 1こか 2こしかｎ
	@ かわないから……

gTVTodaysSmartShopperText05:: @ 08283E28
	.string "인터뷰어: 저도 옛날에\n"
	.string "{STR_VAR_2}{K_EULREUL} 잔뜩 샀던 적이\l"
	.string "있었지만\p"
	.string "나중에 너무 남아서\n"
	.string "후회했던 적이 있어요...\p"
	.string "그 이후로는 딱\n"
	.string "필요한 양만큼만 사고 있죠...\p"
	.string "아차!\p"
	.string "제 얘기를 할 때가\n"
	.string "아닌데 말이죠!$"
	@ インタビュア-『わたしも むかしｎ
	@ §うを たくさん かったことがｌ
	@ あったん ですけどｐ
	@ あまって しまってｎ
	@ こうかい したわ……ｐ
	@ それからと いうもの ひつようなｎ
	@ ぶんだけ かうように してるの……ｐ
	@ おっと!ｐ
	@ わたしの ことを はなしてもｎ
	@ しょうがない ですね!

gTVTodaysSmartShopperText06:: @ 08283F01
	.string "점원: {STR_VAR_1}씨는 그 외에도\n"
	.string "{STR_VAR_2} {STR_VAR_3}개를\l"
	.string "한꺼번에 사가셨습니다\p"
	.string "인터뷰어: 오- {STR_VAR_2}도\n"
	.string "제법 좋은 물건이죠!$"
	@ てんいん『§いさんは そのほかにもｎ
	@ §うを §えこｌ
	@ まとめて かわれましたよｐ
	@ インタビュア-『お- §うもｎ
	@ なかなか よい ですもんね!

gTVTodaysSmartShopperText07:: @ 08283F72
	.string "점원: 참고로 {STR_VAR_2}도\n"
	.string "{STR_VAR_3}개 사갔어요$"
	@ てんいん『ついでに §うもｎ
	@ §えこ かわれて いきました

gTVTodaysSmartShopperText08:: @ 08283FA9
	.string "점원: 심지어 할인하고 있을 때였으니까\n"
	.string "역시 굉장하죠!$"
	@ てんいん『しかも おおやすうりの ときｎ
	@ ですから さすが ですよね!

gTVTodaysSmartShopperText09:: @ 08283FE7
	.string "인터뷰어: 으-음...\n"
	.string "{STR_VAR_1}씨는 꽤나\l"
	.string "알뜰하게 사는 타입일지도 모르겠네요!\p"
	.string "이걸로 합계는...\p"
	.string "{STR_VAR_2}원!?\n"
	.string "정말 엄청나네요!\p"
	.string "어이쿠 그럼 또 다음\n"
	.string "방송에서 만나요!$"
	@ インタビュア-『う-ん……ｎ
	@ §いさんって かなりのｌ
	@ かいものじょうず なのかも しれませんね!ｐ
	@ これで ごうけいは……ｐ
	@ §うえん!?ｎ
	@ さすが ですね!ｐ
	@ おっと それでは またじかいのｎ
	@ ほうそうで おあい しましょう!

gTVTodaysSmartShopperText10:: @ 0828409E
	.string "점원: {STR_VAR_1}씨는 정말로\n"
	.string "소중한 고객님이라구요$"
	@ てんいん『§いさんは ほんとうにｎ
	@ だいじな おきゃくさま ですよ

gTVTodaysSmartShopperText11:: @ 082840CE
	.string "그럼 점원씨를\n"
	.string "인터뷰해 봅시다\l"
	.string "어떻습니까 장사는 잘 되시나요?\p"
	.string "점원: 네 덕분에요\n"
	.string "너무 잘돼서 곤란할 정도라구요!\p"
	.string "지난번에 {STR_VAR_1}씨라는 분이\n"
	.string "{STR_VAR_2}{K_EULREUL} 잔뜩 사가셔서\p"
	.string "가게 안에 {STR_VAR_2}{K_IGA}\n"
	.string "없어질 뻔했다니까요!\p"
	.string "저도 {STR_VAR_2}{K_EULREUL} 그렇게\n"
	.string "많이 사는 고객님이 계실 줄은\l"
	.string "꿈에도 상상 못 했습니다!\p"
	.string "인터뷰어: 그러면...\n"
	.string "100개나 200개 정도를 사가신 건가요?\p"
	.string "점원: 아뇨 더 많았습니다!\p"
	.string "인터뷰어: 우와-!\n"
	.string "{STR_VAR_1}씨는 굉장하네요!\p"
	.string "점원: {STR_VAR_1}씨는 정말로\n"
	.string "소중한 고객님이라구요$"
	@ それでは てんいんさんにｎ
	@ インタビュ- して みましょうｌ
	@ どうですか うれて ますか?ｐ
	@ てんいん『はい おかげさまでｎ
	@ うれてうれて こまって ますよ!ｐ
	@ このまえ §いさん というかたがｎ
	@ §うを たくさん かわれましてｐ
	@ みせのなかに §うがｎ
	@ なくなって しまいそう だったんですよ!ｐ
	@ わたくしも §うを そんなにｎ
	@ かう おきゃくさまが いるなんてｌ
	@ ゆめにも おもいません でした からね!ｐ
	@ インタビュア-『と いうことは……ｎ
	@ 100こ とか 200こ とか ですか?ｐ
	@ てんいん『いや もっと でしたよ!ｐ
	@ インタビュア-『うひゃ-!ｎ
	@ §いさんって すごい ですね!ｐ
	@ てんいん『§いさんは ほんとうにｎ
	@ だいじな おきゃくさま ですよ

gTVTodaysSmartShopperText12:: @ 082842E6
	.string "인터뷰어: 으-음 굉장하네요\p"
	.string "근데 왜 그렇게\n"
	.string "많이 사간 걸까요?\p"
	.string "...\p"
	.string "수수께끼는 깊어져만 가지만\n"
	.string "시간이 다 된 듯하니\l"
	.string "또 다음 방송에서 만나요!\p"
	.string "그건 그렇고\n"
	.string "{STR_VAR_1}씨는 정말 신기하군요...$"
	@ インタビュア-『う-ん すごい ですねｐ
	@ でも なんで そんなにｎ
	@ いっぱい かったので しょう?ｐ
	@ ……ｐ
	@ なぞは ふかまる ばかりですがｎ
	@ じかんの ようなのでｌ
	@ またじかい おあい しましょう!ｐ
	@ それに してもｎ
	@ §いさんって なぞだわ……

gTVWorldOfMastersText00:: @ 082843BA
	.string "“명인의 세계”\p"
	.string "여러분 안녕하십니까\p"
	.string "여러분은 {STR_VAR_1}씨라는\n"
	.string "트레이너를 알고 계신가요?\p"
	.string "{STR_VAR_1}씨는 포켓몬 잡기의\n"
	.string "명인으로 유명하답니다\p"
	.string "{STR_VAR_1}씨의 포켓몬 찾기는\n"
	.string "돌아다니는 것에서부터 시작됩니다\p"
	.string "저번에는 포켓몬을 찾기 위해서\n"
	.string "하루에 {STR_VAR_2}걸음 이상을 걸었고\p"
	.string "잡은 포켓몬의 수는\n"
	.string "무려 {STR_VAR_3}마리라고 하더군요!$"
	@ 『めいじんの せかい』ｐ
	@ みなさん こんにちはｐ
	@ みなさんは §いさん というｎ
	@ トレ-ナ-を しってますか?ｐ
	@ §いさんは ポケモンを つかまえるｎ
	@ めいじん として ゆうめい なんですｐ
	@ §いさんの ポケモンさがしはｎ
	@ あるきまわる ところから はじまりますｐ
	@ このまえは ポケモンを さがすためにｎ
	@ 1にちで §うほ いじょうも あるきｐ
	@ つかまえた ポケモンの かずはｎ
	@ なんと §え ひきにも なったとか!

gTVWorldOfMastersText01:: @ 082844FD
	.string "분명 파트너인 {STR_VAR_1}{K_WAGWA}\n"
	.string "서로 신뢰하고 있기에\l"
	.string "이런 대단한 일이 가능한 거겠죠$"
	@ きっと あいぼうの §いとｎ
	@ しんらい しあっている からこそｌ
	@ こんな すごいことが できるんですね

gTVWorldOfMastersText02:: @ 0828455B
	.string "명인은 마지막에\n"
	.string "{STR_VAR_2}{K_EU}로\l" 
	.string "{STR_VAR_3}{K_EULREUL} 잡아서\p"
	.string "기념비적인 포켓몬으로 소중히\n"
	.string "키우고 있는 모양입니다\p"
	.string "자신 있는 트레이너는 이 기록에\n"
	.string "도전해 보는 게 어떨까요?\p"
	.string "그럼 또\n"
	.string "다음에 만납시다$"
	@ めいじんは さいごにｎ
	@ §うでｌ
	@ §えを つかまえｐ
	@ きねんの ポケモンとして だいじにｎ
	@ している らしいですよｐ
	@ じしんのある トレ-ナ-は このきろくにｎ
	@ ちょうせんして みては いかがですか?ｐ
	@ それでは またｎ
	@ じかい おあいしましょう

gTVTodaysRivalTrainerText00:: @ 08284641
	.string "“오늘의 라이벌 트레이너”\p"
	.string "포켓몬 트레이너 여러분!\n"
	.string "잘 지내셨습니까?\p"
	.string "오늘은 여러분의 라이벌들의\n"
	.string "근황에 대해 전해 드리겠습니다!$"
	@ 『きょうの ライバル トレ-ナ-』ｐ
	@ ポケモン トレ-ナ-の みなさん!ｎ
	@ ごきげん いかがですか?ｐ
	@ きょうも みなさんの ライバルたちのｎ
	@ ようすに ついて おつたえします!

gTVTodaysRivalTrainerText07:: @ 082846D2
	.string "이번 트레이너는\n"
	.string "현재 {STR_VAR_3}에\l"
	.string "있는 {STR_VAR_1}씨입니다!\p"
	.string "{STR_VAR_1}씨는\n"
	.string "포켓몬 도감에 {STR_VAR_2}마리를\l"
	.string "등록시킨 상태군요-!$"
	@ こんかいの トレ-ナ-はｎ
	@ げんざい §えにｌ
	@ いらっしゃる §いさん です!ｐ
	@ §いさんはｎ
	@ ポケモン ずかんを §うひきｌ
	@ とうろく されていますね-!

gTVTodaysRivalTrainerText08:: @ 08284738
	.string "이번 트레이너는\n"
	.string "현재 비밀기지에\l"
	.string "있는 {STR_VAR_1}씨입니다!\p"
	.string "{STR_VAR_1}씨는\n"
	.string "포켓몬 도감에 {STR_VAR_2}마리를\l"
	.string "등록시킨 상태군요-!$"
	@ こんかいの トレ-ナ-はｎ
	@ げんざい ひみつきちにｌ
	@ いらっしゃる §いさん です!ｐ
	@ §いさんはｎ
	@ ポケモン ずかんを §うひきｌ
	@ とうろく されていますね-!

gTVTodaysRivalTrainerText09:: @ 082847A5
	.string "이번 트레이너는\n"
	.string "{STR_VAR_1}씨입니다!\p"
	.string "현재 {STR_VAR_1}씨는\n"
	.string "포켓몬 도감에 {STR_VAR_2}마리를\l"
	.string "등록시킨 상태군요-!$"
	@ こんかいの トレ-ナ-はｎ
	@ §いさん です!ｐ
	@ げんざい §いさんはｎ
	@ ポケモン ずかんを §うひきｌ
	@ とうろく されていますね-!

gTVTodaysRivalTrainerText10:: @ 082847F7
	.string "이번 트레이너는\n"
	.string "현재 연락선에 타고 있는\l"
	.string "{STR_VAR_1}씨입니다!\p"
	.string "{STR_VAR_1}씨는\n"
	.string "포켓몬 도감에 {STR_VAR_2}마리를\l"
	.string "등록시킨 상태군요-!$"
	@ こんかいの トレ-ナ-はｎ
	@ げんざい れんらくせんに のっているｌ
	@ §いさん です!ｐ
	@ §いさんはｎ
	@ ポケモン ずかんを §うひきｌ
	@ とうろく されていますね-!

gTVTodaysRivalTrainerText01:: @ 0828485F
	.string "배지는 {STR_VAR_1}개\n"
	.string "획득한 상태입니다-!$"
	@ バッジは §いこｎ
	@ かくとく されていますよ-!

gTVTodaysRivalTrainerText02:: @ 0828489A
	.string "배지는 아직 1개도\n"
	.string "획득하지 못한 상태입니다-!$"
	@ バッジは まだ 1こもｎ
	@ かくとく されていませんね-!

gTVTodaysRivalTrainerText03:: @ 082848CC
	.string "배틀프런티어의 심볼은\n"
	.string "1개도 획득하지 못했습니다-!$"
	@ バトルフロンティアの シンボルはｎ
	@ 1こも かくとく されていませんね-!

gTVTodaysRivalTrainerText04:: @ 0828490B
	.string "배틀프런티어의 심볼은\n"
	.string "금심볼을 {STR_VAR_1}개\l"
	.string "은심볼을 {STR_VAR_2}개\l"
	.string "획득한 상태입니다-!$"
	@ バトルフロンティアの シンボルはｎ
	@ ゴ-ルドシンボルを §いこｌ
	@ シルバ-シンボルを §うこｌ
	@ かくとく されていますね-!

gTVTodaysRivalTrainerText05:: @ 0828496B
	.string "배틀프런티어에서의\n"
	.string "배틀포인트는 현재\l"
	.string "{STR_VAR_1}BP 모았네요-!$"
	@ バトルフロンティアでのｎ
	@ バトルポイントは げんざいｌ
	@ §い BP あつめていますね-!

gTVTodaysRivalTrainerText06:: @ 082849AE
	.string "{STR_VAR_1}씨의 근황은\n"
	.string "여러분과 비교해서 어땠나요?\p"
	.string "아직도 모험은 계속된답니다\p"
	.string "트레이너 여러분!\p"
	.string "라이벌들한테 지지 않게\n"
	.string "열심히 해주세요-!$"
	@ §いさんの ようすはｎ
	@ みなさんと くらべて いかが でしたか?ｐ
	@ まだまだ ぼうけんは つづきますｐ
	@ トレ-ナ-の みなさん!ｐ
	@ ライバルたちに まけずにｎ
	@ がんばって くださいね-!

gTVDewfordTrendWatcherNetworkText00:: @ 08284A3E
	.string "“무로마을\n"
	.string "  유행 정보국”\p"
	.string "사회자: 자 오늘도 무로마을의\n"
	.string "유행을 빠르게 전해 드리겠습니다\p"
	.string "게스트는 무로마을에서 제일\n"
	.string "박식하다고 하는 이 영감님입니다!\p"
	.string "노인: ...흐음 잘 부탁하네\p"
	.string "사회자: 갑작스럽지만 무로마을에서\n"
	.string "지금 유행하고 있는 것에 대해...\p"
	.string "노인: {STR_VAR_1} {STR_VAR_2}\p"
	.string "사회자: {STR_VAR_1} {STR_VAR_2}\n"
	.string "...인가요?\p"
	.string "노인: ...아니!\n"
	.string "{STR_VAR_1} {STR_VAR_2}{K_EUNNEUN}\l"
	.string "전혀 유행하지 않고 있네...\l"
	.string "이 이야기를 듣고 싶나...?\p"
	.string "사회자: 아뇨 지금 유행하는 걸...$"
	@ 『ムロタウンｎ
	@  りゅうこう じょうほうきょく』ｐ
	@ しかい『さあ きょうも ムロタウンのｎ
	@ りゅうこうを いちはやく おとどけしますｐ
	@ ゲストは ムロタウン いちｎ
	@ ものしり という この おじいさんです!ｐ
	@ ろうじん『……ふむ よろしくじゃｐ
	@ しかい『さっそく ですが ムロタウンでｎ
	@ いま はやっている ことと いえば……ｐ
	@ ろうじん『§い §うｐ
	@ しかい『§い §うｎ
	@ ……ですか?ｐ
	@ ろうじん『……いいや!ｎ
	@ §い §う はｌ
	@ まったく はやらんかった のじゃ……ｌ
	@ この はなし ききたいか のう……?ｐ
	@ しかい『いや いまの りゅうこうを……

gTVDewfordTrendWatcherNetworkText01:: @ 08284C55
	.string "노인: {STR_VAR_1} {STR_VAR_2}{K_EUNNEUN}\n"
	.string "미로마을에서 온 {STR_VAR_3}군이\l"
	.string "알려주었는데 말이지...$"
	@ ろうじん『§い §う はｎ
	@ ミシロから きた §えくんがｌ
	@ おしえて くれたの じゃがのう……

gTVDewfordTrendWatcherNetworkText02:: @ 08284C9B
	.string "노인: {STR_VAR_1} {STR_VAR_2}{K_EUNNEUN}\n"
	.string "미로마을에서 온 {STR_VAR_3}양이\l"
	.string "알려주었는데 말이지...$"
	@ ろうじん『§い §う はｎ
	@ ミシロから きた §えちゃんがｌ
	@ おしえて くれたの じゃがのう……

gTVDewfordTrendWatcherNetworkText03:: @ 08284CE1
	.string "완전 대실패였네...\p"
	.string "{STR_VAR_1} {STR_VAR_2} 축제!\p"
	.string "{STR_VAR_1} {STR_VAR_2} 대회!\p"
	.string "나도 모두에게 열심히\n"
	.string "알려주었지만...\p"
	.string "“{STR_VAR_1}”{K_IGA} 싫었던 걸까...\p"
	.string "사회자: ...죄송하지만\n"
	.string "지금 유행을...$"
	@ まったく ダメ じゃった……ｐ
	@ §い §う まつり!ｐ
	@ §い §う たいかい!ｐ
	@ わしも みんなに いっしょうけんめいｎ
	@ おしえたの じゃがのう……ｐ
	@ 「§い」が わるかったのか のう……ｐ
	@ しかい『……すいませんがｎ
	@ いまの りゅうこうを……

gTVDewfordTrendWatcherNetworkText04:: @ 08284DB6
	.string "노인: {STR_VAR_3}군!\n"
	.string "{STR_VAR_1} {STR_VAR_2}보다\l"
	.string "대단한 말을 또 알려주게-$"
	@ ろうじん『§えくん!ｎ
	@ §い §う よりｌ
	@ すごい こと また おしえて おくれ-

gTVDewfordTrendWatcherNetworkText05:: @ 08284DF5
	.string "노인: {STR_VAR_3}양!\n"
	.string "{STR_VAR_1} {STR_VAR_2}보다\l"
	.string "대단한 말을 또 알려주게-$"
	@ ろうじん『§えちゃん!ｎ
	@ §い §う よりｌ
	@ すごい こと また おしえて おくれ-

gTVDewfordTrendWatcherNetworkText06:: @ 08284E34
	.string "사회자: ...으-음 ...네! 그럼\n"
	.string "{STR_VAR_1} {STR_VAR_2}{K_EUNNEUN}...\l"
	.string "무로마을에서 유행하지 못했단 거군요!\p"
	.string "...이상이 전달드린 내용이었습니다\p"
	.string "노인: {STR_VAR_1} {STR_VAR_2}$"
	@ しかい『……え-と ……はい! ということでｎ
	@ §い §う は……ｌ
	@ ムロタウンで はやらなかった!ｐ
	@ ……いじょうを おつたえしましたｐ
	@ ろうじん『§い §う

gTVHoennTreasureInvestigatorsText00:: @ 08284EDF
	.string "“호연 보물 탐정단!”\p"
	.string "얘들아-!\n"
	.string "숨겨진 아이템 찾고 있어-!?\p"
	.string "오늘도 각지에서 목격된\n"
	.string "비밀 정보를 소개할게!\p"
	.string "오늘의 편지는\n"
	.string "“{STR_VAR_1} 발견!”에\l"
	.string "대해서야-!!$"
	@ 『ホウエン おたから たんていだん!』ｐ
	@ みんな-!ｎ
	@ かくしアイテム みつけてる-!?ｐ
	@ きょうも かくちで もくげき されたｎ
	@ ひみつの じょうほうを しょうかい するよ!ｐ
	@ きょうの おてがみはｎ
	@ 「§い はっけん!」にｌ
	@ ついてだよ-!!

gTVHoennTreasureInvestigatorsText01:: @ 08284FA1
	.string "바로 불러볼게-!\p"
	.string "...탐정단 여러분 안녕\p"
	.string "지난번에 {STR_VAR_2}씨가\n"
	.string "“{STR_VAR_3}”에서 무려!\l"
	.string "“{STR_VAR_2}”{K_EULREUL} 발견했어\l"
	.string "정말 엄청나게 부러운걸\p"
	.string "...해냈구나! {STR_VAR_2}씨!\p"
	.string "TV 앞에 있는 여러분도 지지 말고\n"
	.string "다우징머신을 써서 찾아봐!\p"
	.string "너도 엄청난 보물을\n"
	.string "찾아내길 기다릴게-!$"
	@ さっそく よんでみるね-!ｐ
	@ ……たんていだんの みなさん こんにちはｐ
	@ この あいだ §うさんがｎ
	@ 「§え」で なんと!ｌ
	@ 「§い」を みつけて いましたｌ
	@ もう とっても うらやましかったですｐ
	@ ……やったね! §うさん!ｐ
	@ テレビの まえの みんなも まけずにｎ
	@ ダウジングマシンを つかって さがしてね!ｐ
	@ きみの とっておきの じょうほうｎ
	@ まってるよ-!

gTVHoennTreasureInvestigatorsText02:: @ 082850F5
	.string "바로 불러볼게-!\p"
	.string "...탐정단 여러분 안녕\p"
	.string "지난번에 {STR_VAR_2}씨가\n"
	.string "“연락선”에서 무려!\l"
	.string "“{STR_VAR_2}”{K_EULREUL} 발견했어\l"
	.string "정말 엄청나게 부러운걸\p"
	.string "...해냈구나! {STR_VAR_2}씨!\p"
	.string "TV 앞에 있는 여러분도 지지 말고\n"
	.string "다우징머신을 써서 찾아봐!\p"
	.string "너도 엄청난 보물을\n"
	.string "찾아내길 기다릴게-!$"
	@ さっそく よんでみるね-!ｐ
	@ ……たんていだんの みなさん こんにちはｐ
	@ この あいだ §うさんがｎ
	@ 「れんらくせん」で なんと!ｌ
	@ 「§い」を みつけて いましたｌ
	@ もう とっても うらやましかったですｐ
	@ ……やったね! §うさん!ｐ
	@ テレビの まえの みんなも まけずにｎ
	@ ダウジングマシンを つかって さがしてね!ｐ
	@ きみの とっておきの じょうほうｎ
	@ まってるよ-!

gTVFindThatGamerText00:: @ 08285240
	.string "“갬블러를 찾아라-!”\p"
	.string "여러분-!\n"
	.string "{STR_VAR_2} 빙빙 돌리고 계신가요-?\p"
	.string "자 오늘도 게임코너에서\n"
	.string "굉장했던 트레이너님을\l"
	.string "발표하도록 하겠습니다!\p"
	.string "오늘의 넘버원 갬블러는...\n"
	.string "{STR_VAR_1}님입니다!$"
	@ 『ギャンブラ-を さがせ-!』ｐ
	@ みなさ-ん!ｎ
	@ §う ガンガン まわしてますか-?ｐ
	@ さあ きょうも ゲ-ムコ-ナ-でｎ
	@ すごかった トレ-ナ-さんをｌ
	@ はっぴょう させて いただきますよ!ｐ
	@ きょうの ナンバ-1 ギャンブラ-は……ｌ
	@ §いさん です!

gTVFindThatGamerText01:: @ 082852F4
	.string "{STR_VAR_1}씨는 {STR_VAR_2}{K_EU}로\n"
	.string "무려 {STR_VAR_3}개나\l"
	.string "코인을 얻은 모양입니다!\p"
	.string "“{STR_VAR_1}씨가 오면\n"
	.string "  적자를 각오해야 한다!”\p"
	.string "...라는 말이 점원들 사이에서\n"
	.string "떠도는 것 같습니다!\p"
	.string "TV 앞의 여러분도\n"
	.string "{STR_VAR_1}씨처럼 {STR_VAR_2}{K_EU}로\l"
	.string "놀아보시는 건 어떤가요?\p"
	.string "이상으로\n"
	.string "호연 제일의 두근두근 스폿!\l"
	.string "게임코너에서 전해 드렸습니다$"
	@ §いさんは §うでｎ
	@ なんと §えまいもｌ
	@ コインを だした そうです!ｐ
	@ 「§いさんが きたらｎ
	@  あかじ かくご!」ｐ
	@ ……という ことばが てんいんたちのｎ
	@ あいだで ささやかれた そうです!ｐ
	@ テレビの まえの みなさんもｎ
	@ §いさんの ように §うでｌ
	@ あそんで みては いかがでしょうか?ｐ
	@ いじょうｎ
	@ ホウエン いち ドキドキの スポット!ｌ
	@ ゲ-ムコ-ナ- より おおくりしました

gTVFindThatGamerText02:: @ 08285463
	.string "{STR_VAR_1}씨는 {STR_VAR_2}{K_EU}로\n"
	.string "무려 {STR_VAR_3}개나\l"
	.string "코인을 잃은 모양입니다!\p"
	.string "“{STR_VAR_1}씨가 오면\n"
	.string "  매출 2배!”\p"
	.string "...라는 말이 점원들 사이에서\n"
	.string "떠도는 것 같습니다$"
	@ §いさんは §うでｎ
	@ なんと §えまいもｌ
	@ まけてしまった そうです!ｐ
	@ 「§いさんが きたらｎ
	@  うりあげ 2ばい!」ｐ
	@ ……という ことばが てんいんたちのｎ
	@ あいだで ささやかれた そうです

gTVFindThatGamerText03:: @ 08285500
	.string "TV 앞의 여러분은\n"
	.string "{STR_VAR_1}씨처럼 되지 않도록\l"
	.string "{STR_VAR_2}{K_EU}로\l"
	.string "놀아보시는 건 어떤가요?\p"
	.string "이상으로\n"
	.string "호연 제일의 두근두근 스폿!\l"
	.string "게임코너에서 전해 드렸습니다$"
	@ テレビの まえの みなさんはｎ
	@ §いさん みたいに ならないようにｌ
	@ §うで あそんでみてはｌ
	@ いかがで しょうか?ｐ
	@ いじょうｎ
	@ ホウエン いち ドキドキの スポット!ｌ
	@ ゲ-ムコ-ナ- より おおくりしました

gTVBreakingNewsText00:: @ 082855BF
	.string "...긴급 스페셜 TV!!$"
	@ ……きんきゅう スペシャル テレビ!!

gTVBreakingNewsText01:: @ 082855D1
	.string "“{STR_VAR_1}씨 레어 {STR_VAR_2}{K_EULREUL}\n"
	.string "  잡다---!!”\p"
	.string "...네!\n"
	.string "이쪽은 {STR_VAR_3}입니다!\p"
	.string "방금 {STR_VAR_1}씨가\n"
	.string "레어 {STR_VAR_2}{K_EULREUL} 잡는 데\l"
	.string "성공했습니다!$"
	@ 『§いさん レア §うをｎ
	@  つかまえる---!!』ｐ
	@ ……はい!ｎ
	@ こちら §え です!ｐ
	@ さきほど §いさんがｎ
	@ レア §うを つかまえる ことにｌ
	@ せいこう しました!

gTVBreakingNewsText02:: @ 0828563C
	.string "레어 {STR_VAR_2}{K_EULREUL} 만난\n"
	.string "{STR_VAR_1}씨는\l"
	.string "{STR_VAR_3}{K_EULREUL} 배틀에 내보냈습니다!\p"
	.string "그리고...$"
	@ レア §うに であったｎ
	@ §いさんはｌ
	@ §えで たたかいを いどみました!ｐ
	@ そして……

gTVBreakingNewsText03:: @ 08285682
	.string "볼을 {STR_VAR_1}번 던져서\n"
	.string "훌륭히 {STR_VAR_2} 안에\l"
	.string "잡았습니다!$"
	@ ボ-ルを §いかい なげてｎ
	@ みごと §うの なかにｌ
	@ つかまえた のです!

gTVBreakingNewsText04:: @ 08285705
	.string "그 순간 {STR_VAR_2}에는\n"
	.string "{STR_VAR_1}씨의 환호성이\l"
	.string "울려 퍼진 모양입니다!\p"
	.string "이야- {STR_VAR_1}씨!\n"
	.string "정말 부럽네요!\l"
	.string "저도 같이 환호하고 싶군요!\p"
	.string "...이상으로\n"
	.string "기쁨으로 가득한 현장에서\l"
	.string "보내드렸습니다!$"
	@ その しゅんかん §うにはｎ
	@ §いさんの よろこびの おたけびがｌ
	@ ひびき わたった そうです!ｐ
	@ いや- §いさん!ｎ
	@ うらやましいです!ｌ
	@ わたしも いっしょに さけびたいです!ｐ
	@ ……いじょうｎ
	@ よろこび いっぱいの げんばよりｌ
	@ おつたえ しました!

gTVBreakingNewsText05:: @ 082857B0
	.string "“{STR_VAR_1}씨 레어 {STR_VAR_2}{K_EULREUL}\n"
	.string "  놓치다---!!”\p"
	.string "...네!\n"
	.string "이쪽은 {STR_VAR_3}입니다!\p"
	.string "방금 {STR_VAR_1}씨가\n"
	.string "레어 {STR_VAR_2}{K_EULREUL} 잡는 데\l"
	.string "실패했습니다!$"
	@ 『§いさん レア §うをｎ
	@  とりにがす---!!』ｐ
	@ ……はい!ｎ
	@ こちら §えです!ｐ
	@ さきほど §いさんがｎ
	@ レア §うを つかまえることにｌ
	@ しっぱい しました!

gTVBreakingNewsText06:: @ 08285824
	.string "레어 {STR_VAR_2}{K_EULREUL} 만난\n"
	.string "{STR_VAR_1}씨는\l"
	.string "{STR_VAR_3}{K_EULREUL} 배틀에 내보냈습니다$"
	@ レア §うに であったｎ
	@ §いさんはｌ
	@ §えで たたかいを いどみました

gTVBreakingNewsText07:: @ 0828586A
	.string "그리고...\p"
	.string "{STR_VAR_2}에게 {STR_VAR_1} 등을\n"
	.string "명령하다 보니\l"
	.string "어느새 쓰러뜨려 버린 겁니다...$"
	@ そして……ｐ
	@ §うに §い などをｎ
	@ めいれい している うちにｌ
	@ きが つくと たおしていた のです……

gTVBreakingNewsText12:: @ 082858D0
	.string "하지만...\p"
	.string "레어 {STR_VAR_2}에 놀라서\n"
	.string "혼란스러웠던 {STR_VAR_1}씨는\l"
	.string "영문도 모른 채\l"
	.string "{STR_VAR_3}에게 명령을 내려서\l"
	.string "어느새 쓰러뜨려 버린 겁니다...$"
	@ しかし……ｐ
	@ レア §うに おどろいてｎ
	@ こんらんした §いさんはｌ
	@ わけも わからないままｌ
	@ §えに めいれいを してしまいｌ
	@ きが つくと たおしていた のです……

gTVBreakingNewsText08:: @ 0828596F
	.string "그 순간 {STR_VAR_2}에는\n"
	.string "{STR_VAR_1}씨의 절규가\l"
	.string "울려 퍼진 모양입니다...$"
	@ その しゅんかん §うにはｎ
	@ §いさんの かなしみの さけびがｌ
	@ ひびき わたった そうです……

gTVBreakingNewsText09:: @ 082859AC
	.string "하지만...\p"
	.string "볼이 없었던 건지 그 후에\n"
	.string "{STR_VAR_2}한테서 도망쳐 버렸습니다\p"
	.string "그 순간 {STR_VAR_3}에는\n"
	.string "{STR_VAR_1}씨의 절규가\l"
	.string "울려 퍼진 모양입니다...$"
	@ しかし……ｐ
	@ ボ-ルが なかったのか このあとｎ
	@ §うから にげてしまった のですｐ
	@ その しゅんかん §えにはｎ
	@ §いさんの かなしみの さけびがｌ
	@ ひびき わたった そうです……

gTVBreakingNewsText10:: @ 08285A50
	.string "하지만...\p"
	.string "{STR_VAR_2}{K_EUNNEUN} 눈 깜짝할 사이에\n"
	.string "도망쳐 버렸습니다\p"
	.string "그 순간 {STR_VAR_3}에는\n"
	.string "{STR_VAR_1}씨의 절규가\l"
	.string "울려 퍼진 모양입니다...$"
	@ しかし……ｐ
	@ §うは あっというまにｎ
	@ にげてしまった のですｐ
	@ その しゅんかん §えにはｎ
	@ §いさんの かなしみの さけびがｌ
	@ ひびき わたった そうです……

gTVBreakingNewsText11:: @ 08285AB3
	.string "이야- {STR_VAR_1}씨!\n"
	.string "정말 안타깝네요...!\l"
	.string "저도 함께 절규하고 싶군요\p"
	.string "...이상으로\n"
	.string "슬픔으로 가득한 현장에서\l"
	.string "보내드렸습니다!$"
	@ いや- §いさん!ｎ
	@ ざんねん でした……ｌ
	@ わたしも いっしょに さけびたいですｐ
	@ ……いじょうｎ
	@ かなしみ いっぱいの げんばよりｌ
	@ おつたえ しました……!

gTVSecretBaseVisitText00:: @ 08285B27
	.string "여러분 안녕하세요!\n"
	.string "“비밀기지 방문!”의 시간입니다\p"
	.string "오늘은 {STR_VAR_1}씨의 비밀기지에\n"
	.string "찾아가 보도록 하겠습니다\p"
	.string "{STR_VAR_1}씨의 기지는 어떤\n"
	.string "모양을 하고 있을까요?\p"
	.string "바로 들어가 봅시다!\n"
	.string "......... ......... .........$"
	@ みなさん こんにちは!ｎ
	@ 『ひみつきち ほうもん!』の じかんですｐ
	@ きょうは §いさんの ひみつきちにｎ
	@ おじゃま させて いただきますｐ
	@ §いさんの きちは どんなｎ
	@ おへやに なっている のでしょうか?ｐ
	@ さっそく はいって みましょう!ｎ
	@ ……… ……… ……… ………

gTVSecretBaseVisitText01:: @ 08285BCA
	.string "오오-!\p"
	.string "이런 곳에 “{STR_VAR_2}”{K_IGA}가!\n"
	.string "굉장하네요-$"
	@ おお-!ｐ
	@ こんな ところに 「§う」が!ｎ
	@ すばらしい ですね-

gTVSecretBaseVisitText02:: @ 08285C13
	.string "오오-!\p"
	.string "이럴 수가!\n"
	.string "아무런 굿즈도 없습니다!\p"
	.string "평범한 사람은 흉내낼 수 없는\n"
	.string "이 대담함!\p"
	.string "심플하면서도\n"
	.string "넘쳐흐르는 이 와일드함!\p"
	.string "이야-\n"
	.string "역시 {STR_VAR_1}씨네요-$"
	@ おお-!ｐ
	@ なんと!ｎ
	@ グッズが なにも ありません!ｐ
	@ ふつうの ひとには まね できないｎ
	@ この だいたんさ!ｐ
	@ シンプルで ありながらｎ
	@ あふれでる この ワイルドさ!ｐ
	@ いや-ｎ
	@ さすが §いさん ですね-

gTVSecretBaseVisitText03:: @ 08285CFF
	.string "아아-! 과연!\p"
	.string "여기에 “{STR_VAR_2}”입니까!\n"
	.string "이거 참 효과적이네요-$"
	@ ああ-! なるほど!ｐ
	@ ここに 「§う」 ですか!ｎ
	@ これは こうかてき ですね-

gTVSecretBaseVisitText04:: @ 08285D5D
	.string "아아-! 과연!\p"
	.string "여기에는 일부러 굿즈를 놓지 않고\n"
	.string "열어둔 거군요-\p"
	.string "이거 참 효과적이네요-$"
	@ ああ-! なるほど!ｐ
	@ ここには わざと グッズを おかずにｎ
	@ あけて いるのですね-ｐ
	@ これは こうかてき ですね-

gTVSecretBaseVisitText05:: @ 08285DE0
	.string "우와-!\p"
	.string "“{STR_VAR_2}”{K_WAGWA}\n"
	.string "“{STR_VAR_3}”의 조합!\p"
	.string "꿈에서만 그리던 합체군요-$"
	@ ふぇ-!ｐ
	@ 「§う」とｎ
	@ 「§え」の くみあわせ!ｐ
	@ ゆめの がったいに なっていますね-

gTVSecretBaseVisitText06:: @ 08285E3B
	.string "우와-!\p"
	.string "여기에 “{STR_VAR_2}” 입니까!\n"
	.string "비밀기지 전체에 존재감이 퍼지네요-$"
	@ ふぇ-!ｐ
	@ ここに 「§う」ですか!ｎ
	@ ひみつきち ぜんたいに きいていますね-

gTVSecretBaseVisitText07:: @ 08285E9D
	.string "우와-!\p"
	.string "여기에는 아무것도 안 놓여져 있군요\p"
	.string "이야- 이 아무것도 없는 공간이\n"
	.string "비밀기지 전체에 좋은 느낌을 주네요$"
	@ ふぇ-!ｐ
	@ ここには なにも おいていませんｐ
	@ いや- この なにもない スペ-スがｎ
	@ ひみつきち ぜんたいに きいてますね-

gTVSecretBaseVisitText08:: @ 08285EFE
	.string "앗!\n"
	.string "{STR_VAR_1}씨가 있군요!\l"
	.string "바로 대전해 보겠습니다!\p"
	.string "...... ...... ...... ......\n"
	.string "...... ...... ...... ......$"
	@ あっ!ｎ
	@ §いさんが いらっしゃいます!ｌ
	@ さっそく たいせん してみましょう!ｐ
	@ …… …… …… ……ｎ
	@ …… …… …… ……

gTVSecretBaseVisitText09:: @ 08285F46
	.string "하아-!\n"
	.string "역시 {STR_VAR_1}씨네요\p"
	.string "챔피언이라 부르기에 걸맞은\n"
	.string "강함을 지닌 포켓몬이었습니다\p"
	.string "{STR_VAR_1}씨의 강함이\n"
	.string "무척 잘 드러나더군요\p"
	.string "특히 {STR_VAR_2}에\n"
	.string "“{STR_VAR_3}” 조합이라니\l"
	.string "{STR_VAR_1}씨다워요-\p"
	.string "이야- 정말 공부가 됐습니다$"
	@ はぁ-!ｎ
	@ さすが §いさん ですｐ
	@ チャンピオンと よぶに ふさわしいｎ
	@ つよさの ポケモン でしたｐ
	@ §いさんの ちからづよさがｎ
	@ とっても でていましたよｐ
	@ とくに §うにｎ
	@ 「§え」 なんてｌ
	@ §いさん らしいですね-ｐ
	@ いや- べんきょう させて いただきました

gTVSecretBaseVisitText10:: @ 08286049
	.string "좋았어요-!\n"
	.string "역시 {STR_VAR_1}씨군요\p"
	.string "엄청나게 강한 포켓몬이었습니다\p"
	.string "{STR_VAR_1}씨의 노력이\n"
	.string "잘 드러나더군요\p"
	.string "특히 {STR_VAR_2}에\n"
	.string "“{STR_VAR_3}” 조합이라니\l"
	.string "{STR_VAR_1}씨다워요-\p"
	.string "이야- 정말 공부가 됐습니다$"
	@ ひぃ-!ｎ
	@ さすが §いさん ですｐ
	@ ものすごく つよい ポケモン でしたよｐ
	@ §いさんの がんばりやさんなｎ
	@ ところが でていましたよｐ
	@ とくに §うにｎ
	@ 「§え」 なんてｌ
	@ §いさん らしいですね-ｐ
	@ いや- べんきょう させて いただきました

gTVSecretBaseVisitText11:: @ 0828613A
	.string "우와-!\n"
	.string "역시 {STR_VAR_1}씨군요\p"
	.string "밸런스 있게\n"
	.string "육성된 포켓몬이었습니다\p"
	.string "{STR_VAR_1}씨의 섬세함이\n"
	.string "잘 드러나더군요\p"
	.string "특히 {STR_VAR_2}에\n"
	.string "“{STR_VAR_3}” 조합이라니\l"
	.string "{STR_VAR_1}씨다워요-\p"
	.string "이야- 정말 공부가 됐습니다$"
	@ ふぇ-!ｎ
	@ さすが §いさん ですｐ
	@ バランスよくｎ
	@ そだてられた ポケモン でしたよｐ
	@ §いさんの きくばり じょうずなｎ
	@ ところが でていましたよｐ
	@ とくに §うにｎ
	@ 「§え」 なんてｌ
	@ §いさん らしいですね-ｐ
	@ いや- べんきょう させて いただきました

gTVSecretBaseVisitText12:: @ 08286248
	.string "호오-!\n"
	.string "역시 {STR_VAR_1}씨군요\p"
	.string "이후의 성장이\n"
	.string "기대되는 포켓몬이었습니다\p"
	.string "{STR_VAR_1}씨의 꿈과 희망이\n"
	.string "잘 드러나더군요\p"
	.string "특히 {STR_VAR_2}에\n"
	.string "“{STR_VAR_3}” 조합이라니\l"
	.string "{STR_VAR_1}씨다워요-\p"
	.string "이야-\n"
	.string "정말 공부가 됐습니다$"
	@ ほぉ-!ｎ
	@ さすが §いさん ですｐ
	@ しょうらいの せいちょうがｎ
	@ たのしみな ポケモン でしたよｐ
	@ §いさんの ゆめと きぼうがｎ
	@ でていましたよｐ
	@ とくに §うにｎ
	@ 「§え」 なんてｌ
	@ §いさん らしいですね-ｐ
	@ いや-ｎ
	@ べんきょう させて いただきました

gTVSecretBaseVisitText13:: @ 08286340
	.string "이야-\n"
	.string "굉장한 방이었습니다-\p"
	.string "여러분도 한번 {STR_VAR_1}씨의\n"
	.string "비밀기지를 방문해 보시는 건\l"
	.string "어떤가요?\p"
	.string "그럼 또 다음에 봅시다!\n"
	.string "바이바이!$"
	@ いや-ｎ
	@ すばらしい おへや でしたね-ｐ
	@ みなさんも いちど §いさんのｎ
	@ ひみつきちを ごほうもん されてみてはｌ
	@ いかが でしょうか?ｐ
	@ では また じかい おあいしましょう!ｎ
	@ さようなら!

gTVPokemonLotteryWinnerFlashReportText00:: @ 082863CC
	.string "“두근두근! 쿵쾅쿵쾅!\n"
	.string "  ID 추첨센터 당첨자 속보!”\p"
	.string "안녕하세요!\n"
	.string "이쪽은 해안백화점 1층\l"
	.string "ID 추첨센터의 카운터입니다!\p"
	.string "오늘도 한 명의 럭키 트레이너가\n"
	.string "나타났습니다!\p"
	.string "그 사람의 이름은...\n"
	.string "{STR_VAR_1}씨입니다!\p"
	.string "{STR_VAR_1}{K_EUNNEUN}\n"
	.string "멋지게 {STR_VAR_2}등을 하여\l"
	.string "{STR_VAR_3}{K_EULREUL} 획득했습니다!\p"
	.string "{STR_VAR_1}씨!\n"
	.string "정말 축하드립니다!\p"
	.string "TV 앞에 계신 여러분도 꼭\n"
	.string "해안백화점에 들러보세요!\l"
	.string "저희 점원 일동이 기다리고 있습니다!\p"
	.string "이상으로\n"
	.string "호연지방 제일의 가게\l"
	.string "해안백화점에서 전해드렸습니다!$"
	@ 『ドキドキ! ワクワク!ｎ
	@  ポケモンくじ とうせんしゃ そくほう!』ｐ
	@ こんにちは!ｎ
	@ こちらは ミナモデパ-ト 1かいｌ
	@ ポケモンくじ うりば です!ｐ
	@ きょうも ひとりの ラッキ-トレ-ナ-がｎ
	@ あらわれました!ｐ
	@ その かたの おなまえは……ｌ
	@ §いさん です!ｐ
	@ §いさんはｎ
	@ みごと §うとうを あててｌ
	@ §えを かくとく しました!ｐ
	@ §いさん!ｎ
	@ おめでとう ございました!ｐ
	@ テレビの まえの みなさんも ぜひｎ
	@ ミナモデパ-トへ ごらいてん ください!ｌ
	@ てんいん いちどう おまち しております!ｐ
	@ いじょうｎ
	@ ホウエン いちの しなぞろえｌ
	@ ミナモデパ-ト より おおくり しました!

gTVThePokemonBattleSeminarText00:: @ 08286616
	.string "“포켓몬 배틀 강좌!”\p"
	.string "오늘도 여러분과 함께\n"
	.string "배틀을 공부하도록 하겠습니다\p"
	.string "오늘의 문제는\n"
	.string "{STR_VAR_1}씨의 배틀에 대해서입니다\p"
	.string "{STR_VAR_1}씨는 {STR_VAR_2}{K_EU}로\n"
	.string "{STR_VAR_3}{K_WAGWA} 배틀했습니다만...$"
	@ 『ポケモン バトル こうざ!』ｐ
	@ きょうも みなさんと ごいっしょにｎ
	@ バトルに ついて べんきょう しましょうｐ
	@ きょうの もんだいはｎ
	@ §いさんの バトルに ついてですｐ
	@ §いさんは §うでｎ
	@ §えと たたかったの ですが……

gTVThePokemonBattleSeminarText01:: @ 082866B6
	.string "{STR_VAR_2}에게\n"
	.string "“{STR_VAR_3}”{K_EULREUL} 써버렸습니다...\p"
	.string "으-음... {STR_VAR_1}씨!\n"
	.string "이러시면 안 되죠...$"
	@ §うに たいしてｎ
	@ 「§え」を やってしまいました……ｐ
	@ う-ん…… §いさん!ｎ
	@ これは いけませんね……

gTVThePokemonBattleSeminarText02:: @ 08286700
	.string "{STR_VAR_1}{K_EUNNEUN} 그 외에도...$"
	@ §いは そのほかに……

gTVThePokemonBattleSeminarText03:: @ 0828673B
	.string "“{STR_VAR_1}” “{STR_VAR_2}”\n"
	.string "“{STR_VAR_3}” ...같은 기술이 있었습니다$"
	@ 「§い」 「§う」ｎ
	@ 「§え」 ……を おぼえていました

gTVThePokemonBattleSeminarText04:: @ 08286755
	.string "“{STR_VAR_1}” “{STR_VAR_2}”\n"
	.string "...같은 기술이 있었습니다$"
	@ 「§い」 「§う」ｎ
	@ ……を おぼえていました

gTVThePokemonBattleSeminarText05:: @ 0828676A
	.string "“{STR_VAR_2}”\n"
	.string "...같은 기술이 있었습니다$"
	@ 「§う」ｎ
	@ ……を おぼえていました

gTVThePokemonBattleSeminarText06:: @ 08286777
	.string "이 중에서 가장 좋은 것은\n"
	.string "........................\p"
	.string "바로 “{STR_VAR_1}”입니다!\p"
	.string "“{STR_VAR_2}”보단\n"
	.string "역시 “{STR_VAR_1}”{K_I}죠\p"
	.string "TV 앞에 있는 여러분도\n"
	.string "자-알 생각하고 배틀하도록 합시다!\p"
	.string "그럼 안녕히!$"
	@ この なかで いちばん よいのはｎ
	@ …………………………………………ｐ
	@ 「§い」 ですね!ｐ
	@ 「§う」よりｎ
	@ ぜったい 「§い」ですｐ
	@ テレビの まえの みなさんもｎ
	@ よ-く かんがえて バトルを しましょう!ｐ
	@ それでは さようなら!

gTVTrainerFanClubText00:: @ 08286866
	.string "하나 둘!\n"
	.string "“트레이너 애호가클럽!!”\p"
	.string "사회자: 다들 잘 지내셨어-!?\n"
	.string "오늘은 지금 대인기인 트레이너\l"
	.string "{STR_VAR_1}씨의 팬들을\l"
	.string "모셔 봤다구!\p"
	.string "팬: 와아아아아아아아아아---!\p"
	.string "팬: {STR_VAR_1}님----!\p"
	.string "사회자: 자 다들-!\n"
	.string "{STR_VAR_1}씨를 좋아해-?\p"
	.string "팬: 완전 좋아해-!!\p"
	.string "사회자: 어떤 점이 좋길래-?$"
	@ せ-の!ｎ
	@ 『トレ-ナ- だいすき クラブ!!』ｐ
	@ しかい『みんな- げんきか-い!?ｎ
	@ きょうは いま だいにんきの トレ-ナ-ｌ
	@ §いさんの ファンにｌ
	@ あつまって もらったよ!ｐ
	@ ファン『ワアアアアアアアアア---!ｐ
	@ ファン『§いさま----!ｐ
	@ しかい『みんな-!ｎ
	@ §いさんの ことは すきかい-?ｐ
	@ ファン『だいすき-!!ｐ
	@ しかい『どんな ところが-?

gTVTrainerFanClubText01:: @ 0828695E
	.string "팬: 몬스터볼을 던지는 포즈가\n"
	.string "멋진 거!!$"
	@ ファン『モンスタ-ボ-ルを なげる しぐさがｎ
	@ かっこいい ところ!!

gTVTrainerFanClubText02:: @ 0828698B
	.string "팬: 달리는 모습이\n"
	.string "귀여운 거!!$"
	@ ファン『はしる すがたがｎ
	@ かわいい ところ!!

gTVTrainerFanClubText03:: @ 082869B0
	.string "팬: 포켓몬 배틀을\n"
	.string "엄청 잘하는 거!!$"
	@ ファン『ポケモンバトルでｎ
	@ ここ いちばんに つよい ところ!!

gTVTrainerFanClubText04:: @ 082869ED
	.string "팬: 포켓몬에 대해서\n"
	.string "잘 아는 거!!$"
	@ ファン『ポケモンの ことに ついてｎ
	@ くわしい ところ!!

gTVTrainerFanClubText05:: @ 08286A17
	.string "팬: 포켓몬에게\n"
	.string "언제나 친절한 거!!$"
	@ ファン『ポケモンに たいしてｎ
	@ いつも やさしい ところ!!

gTVTrainerFanClubText06:: @ 08286A48
	.string "팬: 자전거를 다루는\n"
	.string "테크닉이 굉장한 거!!$"
	@ ファン『じてんしゃを あやつるｎ
	@ テクニックが すごい ところ!!

gTVTrainerFanClubText07:: @ 08286A7C
	.string "팬: 아이템을 사는 방식이\n"
	.string "대담한 거!!$"
	@ ファン『アイテムの かいかたがｎ
	@ ごうかいな ところ!!

gTVTrainerFanClubText08:: @ 08286AAE
	.string "팬: 포켓몬에게 붙이는 별명이\n"
	.string "재치 있는 거!!$"
	@ ファン『ポケモンに つける ニックネ-ムがｎ
	@ おちゃめな ところ!!

gTVTrainerFanClubText09:: @ 08286AE6
	.string "팬: 비밀기지를 꾸미는 센스가\n"
	.string "좋은 거!!$"
	@ ファン『ひみつきちの センスがｎ
	@ いい ところ!!

gTVTrainerFanClubText10:: @ 08286B23
	.string "팬: 기술머신을 쓰는 방식이\n"
	.string "대담한 거!!$"
	@ ファン『わざマシンの つかい かたがｎ
	@ だいたんな ところ!!

gTVTrainerFanClubText11:: @ 08286B4F
	.string "사회자: 그런 핫한\n"
	.string "{STR_VAR_1}씨의 팬 사이에서는\l"
	.string "특별한 암호가 있다고-!\p"
	.string "사회자: {STR_VAR_1}{K_I}라고 하면...\p"
	.string "사회자: {STR_VAR_2}!\p"
	.string "팬: {STR_VAR_3}!\p"
	.string "사회자: {STR_VAR_2}!\p"
	.string "팬: {STR_VAR_3}!\p"
	.string "사회자: {STR_VAR_1}{K_I}라고 하면...\n"
	.string "{STR_VAR_2} {STR_VAR_3}\l"
	.string "으-음! 좋은 울림인걸-!\p"
	.string "{STR_VAR_1}씨의 팬이\n"
	.string "되는 게 이해가 되네-!\p"
	.string "좋-았어! TV 앞에 있는 모두도\n"
	.string "같이 말해 보자-!!\p"
	.string "사회자: {STR_VAR_1}{K_I}라고 하면...\p"
	.string "사회자: {STR_VAR_2}!\p"
	.string "팬: {STR_VAR_3}!\p"
	.string "사회자: {STR_VAR_2}!\p"
	.string "팬: {STR_VAR_3}!\p"
	.string "사회자: {STR_VAR_1}씨의 팬들\n"
	.string "모-두 고마워---!!\l"
	.string "그-럼 다음에 봐-!!\p"
	.string "사회자: {STR_VAR_1}{K_I}라고 하면...\p"
	.string "사회자: {STR_VAR_2}!\p"
	.string "팬: {STR_VAR_3}!$"
	@ しかい『そんな ホットなｎ
	@ §いさん ファンの あいだにはｌ
	@ とくべつな あいことばが あるんだよ-!ｐ
	@ しかい『§い といえば……ｐ
	@ しかい『§う!ｐ
	@ ファン『§え!ｐ
	@ しかい『§う!ｐ
	@ ファン『§え!ｐ
	@ しかい『§い といえば……ｎ
	@ §う §えｌ
	@ う-ん! いい ひびきだね-!ｐ
	@ §いさんの ファンにｎ
	@ なっちゃうのも わかる きが するよ-!ｐ
	@ よ-し! テレビの まえの みんなもｎ
	@ いっしょに いってみよ-!!ｐ
	@ しかい『§い といえば……ｐ
	@ しかい『§う!ｐ
	@ ファン『§え!ｐ
	@ しかい『§う!ｐ
	@ ファン『§え!ｐ
	@ しかい『§いさん ファンのｎ
	@ みんな- ありがと---!!ｌ
	@ それじゃ- またね-!!ｐ
	@ しかい『§い といえば……ｐ
	@ しかい『§う!ｐ
	@ ファン『§え!

gTVCutiesText00:: @ 08286D8F
	.string "“멋진 발견!\n"
	.string "  리본이 달린 포켓몬!!”\p"
	.string "...하아-\p"
	.string "포켓몬에게 리본이라니\n"
	.string "정말 멋지단 말이죠-\p"
	.string "오늘도 마을에서 본\n"
	.string "멋진 포켓몬을\l"
	.string "여러분께 소개하겠습니다\p"
	.string "오늘의 포켓몬은\n"
	.string "{STR_VAR_1}씨의 {STR_VAR_2}입니다$"
	@ 『ステキに はっけん!ｎ
	@  リボンを つけた ポケモンちゃん!!』ｐ
	@ ……はぁ-ｐ
	@ ポケモンちゃんに リボンってｎ
	@ ほんと ステキ ざますね-ｐ
	@ きょうも まちで みかけたｎ
	@ ステキな ポケモンちゃんをｌ
	@ みなさまに ごしょうかい するざますｐ
	@ きょうの ポケモンちゃんはｎ
	@ §いさんの §う ざます

gTVCutiesText01:: @ 08286E9D
	.string "{STR_VAR_2}{K_EUNNEUN} 무려!\n"
	.string "리본을 {STR_VAR_3}개 달고 있습니다\p"
	.string "{STR_VAR_1}씨의 사랑이\n"
	.string "느껴지네요-$"
	@ §うは なんと!ｎ
	@ リボンを §えこ つけている ざますよｐ
	@ §いさんの あいをｎ
	@ かんじる ざますね-

gTVCutiesText02:: @ 08286EFC
	.string "{STR_VAR_2}{K_EUNNEUN} 놀랍게도!\n"
	.string "리본을 {STR_VAR_3}개나 달고 있습니다\p"
	.string "{STR_VAR_1}씨의 집념이\n"
	.string "느껴지네요-$"
	@ §うは ビックリ ざます!ｎ
	@ リボンを §えこも つけている ざますよｐ
	@ §いさんの しゅうねんをｎ
	@ かんじる ざますね-

gTVCutiesText03:: @ 08286F54
	.string "{STR_VAR_2}{K_EUNNEUN} 굉장하게도!\n"
	.string "리본을 {STR_VAR_3}개나 달고 있습니다\p"
	.string "{STR_VAR_1}씨의 수집가 정신이\n"
	.string "느껴지네요-$"
	@ §うは すごい ざます!ｎ
	@ リボンを §えこも つけている ざますよｐ
	@ §いさんの コレクタ-だましいをｎ
	@ かんじる ざますね-

gTVCutiesText04:: @ 08286FAA
	.string "자 그럼 {STR_VAR_2}{K_IGA} 잔뜩\n"
	.string "달고 있는 리본 중에서...$"
	@ さて §うに ついているｎ
	@ たくさんの リボン ざますが……

gTVCutiesText05:: @ 08286FE4
	.string "특히 전당등록 기념으로 받은\n"
	.string "챔피언리본이 어울리네요\p"
	.string "{STR_VAR_2}의 용감함이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 챔피언리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに でんどういりの きねんで もらったｎ
	@ チャンプリボンが おにあい ざますねｐ
	@ §うの ゆうかんさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに チャンプリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText06:: @ 082870A3
	.string "특히 근사함콘테스트에서 받은\n"
	.string "쿨리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 근사함이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 쿨리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに かっこよさ コンテストで もらったｎ
	@ ク-ルリボンが おにあい ざますねｐ
	@ §うの かっこよさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに ク-ルリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText07:: @ 0828715A
	.string "특히 아름다움콘테스트에서 받은\n"
	.string "뷰티리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 아름다움이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 뷰티리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに うつくしさ コンテストで もらったｎ
	@ ビュ-ティリボンが おにあい ざますねｐ
	@ §うの うつくしさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに ビュ-ティリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText08:: @ 08287215
	.string "특히 귀여움콘테스트에서 받은\n"
	.string "큐트리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 귀여움이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 큐트리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに かわいさ コンテストで もらったｎ
	@ キュ-トリボンが おにあい ざますねｐ
	@ §うの かわいさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに キュ-トリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText09:: @ 082872CC
	.string "특히 슬기로움콘테스트에서 받은\n"
	.string "지니어스리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 슬기로움이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 지니어스리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに かしこさ コンテストで もらったｎ
	@ ジ-ニアスリボンが おにあい ざますねｐ
	@ §うの かしこさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに ジ-ニアスリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText10:: @ 08287387
	.string "특히 강인함콘테스트에서 받은\n"
	.string "파워풀리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 강인함이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 파워풀리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに たくましさ コンテストで もらったｎ
	@ パワフルリボンが おにあい ざますねｐ
	@ §うの たくましさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに パワフルリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText11:: @ 08287442
	.string "특히 배틀타워에서 받은\n"
	.string "위닝리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 강함이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 위닝리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに バトルタワ-で もらったｎ
	@ ウイニングリボンが おにあい ざますねｐ
	@ §うの つよさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに ウイニングリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText12:: @ 08287508
	.string "특히 배틀타워에서 받은\n"
	.string "빅토리리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 강함이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 빅토리리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに バトルタワ-で もらったｎ
	@ ビクトリ-リボンが おにあい ざますねｐ
	@ §うの ものすごい つよさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに ビクトリ-リボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText13:: @ 082875D9
	.string "특히 화가에게서 받은\n"
	.string "브로마이드리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 아이돌스러움이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 브로마이드리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに えかきさん から もらったｎ
	@ プロマイドリボンが おにあい ざますねｐ
	@ §うの アイドルらしさをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに プロマイドリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText14:: @ 082876A1
	.string "특히 노력가에게서 받은\n"
	.string "노력리본이 잘 어울리네요\p"
	.string "{STR_VAR_2}의 노력이\n"
	.string "무척 잘 드러납니다-\p"
	.string "{STR_VAR_2}에게 노력리본!\n"
	.string "효과가 굉장하네요!$"
	@ とくに がんばりやで もらったｎ
	@ がんばリボンが おにあい ざますねｐ
	@ §うの がんばりぶりをｎ
	@ とっても ひきたたせている ざますよ-ｐ
	@ §うに がんばリボン!ｎ
	@ こうかは ばつぐん ざます!

gTVCutiesText15:: @ 08287779
	.string "...하아-\p"
	.string "포켓몬에게 리본이라니...\n"
	.string "정말로 좋네요!\p"
	.string "벌써 시간이 이렇게 됐으니\n"
	.string "다음 시간에 봐요-!$"
	@ ……はぁ-ｐ
	@ ポケモンに リボンって……ｎ
	@ ホントに いい ざますね!ｐ
	@ ウットリ したところでｎ
	@ さよなら ざます-!

gTVPokemonNewsBattleFrontierText00:: @ 082877DE
	.string "안녕하세요!\n"
	.string "“포켓몬 뉴스”의 시간입니다\p"
	.string "배틀프런티어로부터\n"
	.string "기쁜 뉴스가 들어왔습니다!$"
	@ こんにちは!ｎ
	@ 『ポケモン ニュ-ス』の じかんですｐ
	@ バトルフロンティアからｎ
	@ うれしい ニュ-スが はいって きました!

gTVPokemonNewsBattleFrontierText01:: @ 0828783D
	.string "배틀타워 싱글 배틀룸에\n"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルタワ- シングル バトルル-ムにｎ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText02:: @ 082878B3
	.string "배틀타워 더블 배틀룸에\n"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルタワ- ダブル バトルル-ムにｎ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText03:: @ 08287929
	.string "배틀타워 멀티 배틀룸에\n"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルタワ- マルチ バトルル-ムにｎ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText04:: @ 0828799E
	.string "배틀타워\n"
	.string "통신멀티 배틀룸에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルタワ-ｎ
	@ つうしん マルチ バトルル-ムにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText05:: @ 08287A18
	.string "배틀돔\n"
	.string "싱글 배틀토너먼트에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연패로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルド-ムｎ
	@ シングル バトルト-ナメントにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんぱでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText06:: @ 08287A97
	.string "배틀돔\n"
	.string "더블 배틀토너먼트에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연패로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルド-ムｎ
	@ ダブル バトルト-ナメントにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんぱでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText07:: @ 08287B16
	.string "배틀팩토리\n"
	.string "배틀트레이드 싱글에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルファクトリ-ｎ
	@ バトルトレ-ド シングルにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText08:: @ 08287B8E
	.string "배틀팩토리\n"
	.string "배틀트레이드 더블에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルファクトリ-ｎ
	@ バトルトレ-ド ダブルにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText09:: @ 08287C06
	.string "배틀튜브에서\n"
	.string "배틀게임에 도전했던\l"
	.string "{STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}개의 방을 돌파해서\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルチュ-ブでｎ
	@ バトルゲ-ムに ちょうせんしたｌ
	@ §いさんがｌ
	@ §う へや とっぱでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText10:: @ 08287C7D
	.string "배틀아레나에서\n"
	.string "연승팀배틀에 도전했던\l"
	.string "{STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}명을 이겨서\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルアリ-ナでｎ
	@ かちぬきチ-ムバトルに ちょうせんしたｌ
	@ §いさんがｌ
	@ §う にんぬきでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText11:: @ 08287CF3
	.string "배틀팰리스\n"
	.string "싱글 배틀홀에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルパレスｎ
	@ シングル バトルホ-ルにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText12:: @ 08287D6A
	.string "배틀팰리스\n"
	.string "더블 배틀홀에\l"
	.string "도전했던 {STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}연승으로\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルパレスｎ
	@ ダブル バトルホ-ルにｌ
	@ ちょうせんした §いさんがｌ
	@ §う れんしょうでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText13:: @ 08287DE1
	.string "배틀피라미드에서\n"
	.string "배틀어드벤처에 도전했던\l"
	.string "{STR_VAR_1}씨가\l"
	.string "{STR_VAR_2}단을 제패해서\l"
	.string "기록을 경신했습니다!\p"
	.string "...{STR_VAR_1}씨!$"
	@ バトルピラミッドでｎ
	@ バトルアドベンチャ-に ちょうせんしたｌ
	@ §いさんがｌ
	@ §う だん せいはでｌ
	@ きろくを こうしん しました!ｐ
	@ ……§いさん!

gTVPokemonNewsBattleFrontierText14:: @ 08287E5B
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}{K_WAGWA}\n"
	.string "{STR_VAR_3} 3마리의 포켓몬들!\p"
	.string "기록 경신\n"
	.string "축하합니다!!$"
	@ §いと §うとｎ
	@ §えの 3ひきの ポケモンたち!ｐ
	@ きろく こうしんｎ
	@ おめでとう ございました!!

gTVPokemonNewsBattleFrontierText15:: @ 08287EBB
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_2}\n"
	.string "2마리의 포켓몬들!\p"
	.string "기록 경신\n"
	.string "축하합니다!!$"
	@ §いと §うのｎ
	@ 2ひきの ポケモンたち!ｐ
	@ きろく こうしんｎ
	@ おめでとう ございました!!

gTVPokemonNewsBattleFrontierText16:: @ 08287F14
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"
	@ §い!ｐ
	@ §う!ｐ
	@ §え!

gTVPokemonNewsBattleFrontierText17:: @ 08287F39
	.string "그리고 {STR_VAR_1}까지\n"
	.string "4마리의 포켓몬들!\p"
	.string "기록 경신\n"
	.string "축하합니다!!$"
	@ そして §いのｎ
	@ 4ひきの ポケモンたち!ｐ
	@ きろく こうしんｎ
	@ おめでとう ございました!!

gTVPokemonNewsBattleFrontierText18:: @ 08287F77
	.string "{STR_VAR_1}씨의 포켓몬들의\n"
	.string "다음 도전을 기대하고 있겠습니다!\p"
	.string "이상으로\n"
	.string "“포켓몬 뉴스”였습니다!$"
	@ §いさんと ポケモンたちのｎ
	@ つぎの チャレンジに きたい しましょう!ｐ
	@ いじょうｎ
	@ 『ポケモン ニュ-ス』 でした!

gTVWhatsNo1InHoennTodayText00:: @ 08287FE0
	.string "“호연 오늘의\n"
	.string "  뭐든지 넘버1!!”\p"
	.string "TV 앞에 계신 여러분\n"
	.string "잘 지내고 있으신가요-?\p"
	.string "오늘도 하루를 가장 열심히 보낸\n"
	.string "트레이너를 소개하겠습니다!\p"
	.string "...자\n"
	.string "오늘의 넘버1 트레이너는...\l"
	.string "{STR_VAR_1}씨입니다!!$"
	@ 『ホウエン きょうのｎ
	@  なんでも ナンバ-1!!』ｐ
	@ テレビの まえの みなさんｎ
	@ がんばってますか-?ｐ
	@ きょうも いちにちで いちばん がんばったｎ
	@ トレ-ナ-を しょうかい しますよ!ｐ
	@ ……さあｎ
	@ きょうの ナンバ-1 トレ-ナ-は……ｌ
	@ §いさんです!!

gTVWhatsNo1InHoennTodayText01:: @ 082880C0
	.string "{STR_VAR_1}씨는 게임코너의\n"
	.string "슬롯을 하루에\l"
	.string "{STR_VAR_2}번 돌렸습니다!\p"
	.string "{STR_VAR_1}씨는 놀고 있을 때\n"
	.string "“슬롯이 멈춘 것처럼 보인다...!”라고\l"
	.string "왠지 무섭게\l"
	.string "중얼거렸다고 합니다!$"
	@ §いさんは ゲ-ムコ-ナ-のｎ
	@ スロットを いちにちでｌ
	@ §う かい まわしました!ｐ
	@ §いさんは あそんで いるときにｎ
	@ 「スロットが とまって みえる……!」とｌ
	@ ブツブツ ぶきみにｌ
	@ つぶやいていた そうですよ!

gTVWhatsNo1InHoennTodayText02:: @ 0828815F
	.string "{STR_VAR_1}씨는 게임코너의\n"
	.string "룰렛을 하루에\l"
	.string "{STR_VAR_2}번 돌렸습니다!\p"
	.string "{STR_VAR_1}씨는 놀고 있을 때\n"
	.string "“공의 움직임이 보인다...!”라고\l"
	.string "눈을 새빨갛게 물들이면서\l"
	.string "굉장한 얼굴로\l"
	.string "외쳤다고 합니다!$"
	@ §いさんは ゲ-ムコ-ナ-のｎ
	@ ル-レットを いちにちでｌ
	@ §う かい まわしました!ｐ
	@ §いさんは あそんで いるときｎ
	@ 「ボ-ルの うごきが よめた……!」とｌ
	@ めを まっかにしてｌ
	@ それは すごい かおでｌ
	@ さけんでいた そうですよ!

gTVWhatsNo1InHoennTodayText03:: @ 0828821A
	.string "{STR_VAR_1}씨는 야생 포켓몬과\n"
	.string "하루에 {STR_VAR_2}번 싸웠습니다!\p"
	.string "{STR_VAR_1}씨의 포켓몬들은\n"
	.string "이전과 전혀 비교할 수 없을 정도로\l"
	.string "강해진 것 같군요...\p"
	.string "누군가와 포켓몬 승부를 하고 싶어서\n"
	.string "참을 수 없는 것 같습니다!$"
	@ §いさんは やせい ポケモンとｎ
	@ いちにちで §う かい たたかいました!ｐ
	@ §いさんの ポケモンたちはｎ
	@ いぜんと くらべものに ならないほどｌ
	@ つよくなった らしく……ｐ
	@ だれかと ポケモンしょうぶが したくてｎ
	@ たまらない そうですよ!

gTVWhatsNo1InHoennTodayText04:: @ 082882BE
	.string "{STR_VAR_1}씨는 나무열매블렌더를\n"
	.string "하루에 {STR_VAR_2}번 돌렸습니다!\p"
	.string "역시 마지막에는\n"
	.string "{STR_VAR_1}씨의 눈도\l"
	.string "빙글빙글 돌아버려서\l"
	.string "마치 얼루기처럼\l"
	.string "되어버렸다고 합니다!$"
	@ §いさんは きのみブレンダ-をｎ
	@ いちにちで §う かい まわしました!ｐ
	@ さすがに さいごの ほうではｎ
	@ §いさんの めもｌ
	@ くるくる まわってしまいｌ
	@ まるで パッチ-ルの ようにｌ
	@ なってしまった そうですよ!

gTVWhatsNo1InHoennTodayText05:: @ 08288355
	.string "{STR_VAR_1}씨는 나무열매를\n"
	.string "하루에 {STR_VAR_2}개 심었습니다!\p"
	.string "{STR_VAR_1}씨의\n"
	.string "옷은 새까맣게 되어버렸지만...\p"
	.string "나무열매를 심은 곳에는\n"
	.string "예쁜 꽃이 잔뜩 피어나\l"
	.string "보는 사람의 마음을\l"
	.string "달래고 있다고 합니다!$"
	@ §いさんは きのみをｎ
	@ いちにちで §う こ うえました!ｐ
	@ §いさんのｎ
	@ ふくは まっくろに なりましたが……ｐ
	@ きのみを うえた ところにはｎ
	@ きれいな はなが たくさん さきほこりｌ
	@ みる ひとの こころをｌ
	@ なごませている そうですよ!

gTVWhatsNo1InHoennTodayText06:: @ 0828842B
	.string "{STR_VAR_1}씨는 나무열매를 하루에\n"
	.string "{STR_VAR_2}개 땄습니다\p"
	.string "{STR_VAR_1}씨의 가방은\n"
	.string "나무열매로 가득 차서\l"
	.string "걷는 데 힘들었다고 합니다!$"
	@ §いさんは きのみを いちにちでｎ
	@ §う こ とりましたｐ
	@ §いさんの バックはｎ
	@ きのみで いっぱいに なりｌ
	@ あるくのも たいへんだった そうですよ!

gTVWhatsNo1InHoennTodayText07:: @ 082884A5
	.string "{STR_VAR_1}씨는 하루에\n"
	.string "배틀포인트를\l"
	.string "{STR_VAR_2}BP 모았습니다!\p"
	.string "{STR_VAR_1}씨는\n"
	.string "모은 배틀포인트로\l"
	.string "굉장한 굿즈를 살까...\l"
	.string "굉장한 아이템을 살까...\l"
	.string "히죽히죽 웃으면서\l"
	.string "계속 고민했다고 합니다!$"
	@ §いさんは いちにちでｎ
	@ バトルポイントをｌ
	@ §う BP ためました!ｐ
	@ §いさんは ｎ
	@ たまった バトルポイントでｌ
	@ すごい グッズを もらうべきか……ｌ
	@ すごい アイテムを もらうべきか……とｌ
	@ ニタニタ しながらｌ
	@ ずっと なやんでいた そうですよ!

gTVWhatsNo1InHoennTodayText08:: @ 0828858B
	.string "이야- 굉장하네요!\p"
	.string "{STR_VAR_1}씨!\n"
	.string "당신이 오늘의 넘버1입니다!!\p"
	.string "TV 앞에 계신 여러분도\n"
	.string "{STR_VAR_1}씨에게 지지 않게\l"
	.string "하루를 더 열심히 보냅시다!$"
	@ いや- すごい ですね!ｐ
	@ §いさん!ｎ
	@ あなたが きょうの ナンバ-1です!!ｐ
	@ テレビの まえの みなさんもｎ
	@ §いさんに まけずにｌ
	@ いちにち がんばりましょうね!

TVSecretBaseSecrets_Text_Intro:: @ 08288608
	.string "“비밀기지의 비밀-!”\p"
	.string "비밀기지에서 트레이너는 대체\n"
	.string "어떤 행동을 할까요?\p"
	.string "오늘은\n"
	.string "{STR_VAR_1}씨의 비밀기지입니다\p"
	.string "...자 {STR_VAR_2}씨가\n"
	.string "놀러온 모양이군요!\p"
	.string "바로 엿봐봅시다!\p"
	.string "우선 {STR_VAR_2}씨는...$"
	@ 『ひみつきちの ヒミツ-!』ｐ
	@ ひみつきちで トレ-ナ-は いったいｎ
	@ どんな こうどうを とる のでしょうか?ｐ
	@ きょうはｎ
	@ §いさんの ひみつきちですｐ
	@ ……さあ §うさんがｎ
	@ あそびに いらした ようですね!ｐ
	@ さっそく のぞいてみましょう!ｐ
	@ まず §うさんは……

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1:: @ 082886C8
	.string "{STR_VAR_2}씨는 다음에...$"
	@ §うさんは つぎに……

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2:: @ 082886DE
	.string "이 다음에\n"
	.string "{STR_VAR_2}씨는...$"
	@ この あとｎ
	@ §うさんは……

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving:: @ 082886F8
	.string "... 같은 느낌으로\n"
	.string "{STR_VAR_2}씨는\l"
	.string "{STR_VAR_1}씨의 기지를\l"
	.string "{STR_VAR_3}보 걷다 돌아갔습니다$"
	@ ……と いうような かんじでｎ
	@ §うさんはｌ
	@ §いさんの きちをｌ
	@ §えほ あるいて かえりました

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer:: @ 08288739
	.string "...으-음\p"
	.string "아무래도 {STR_VAR_2}씨는\n"
	.string "{STR_VAR_1}씨의 비밀기지에\l"
	.string "흥미가 없었던 모양입니다...$"
	@ ……う-んｐ
	@ どうやら §うさんはｎ
	@ §いさんの ひみつきちにｌ
	@ きょうみが わかなかった ようですね……

TVSecretBaseSecrets_Text_PlayerEnjoyedBase:: @ 08288777
	.string "{STR_VAR_2}씨는\n"
	.string "{STR_VAR_1}씨의 비밀기지를\l"
	.string "무척 잘 즐긴 모양입니다$"
	@ §うさんはｎ
	@ §いさんの ひみつきちをｌ
	@ とっても たのしんだ ようですね

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase:: @ 082887AF
	.string "{STR_VAR_2}씨는\n"
	.string "{STR_VAR_1}씨의 비밀기지마니아가\l"
	.string "된 모양입니다$"
	@ §うさんはｎ
	@ §いさんの ひみつきちマニアにｌ
	@ なった ようですね

TVSecretBaseSecrets_Text_Outro:: @ 082887E9
	.string "TV 앞에 계신 여러분도\n"
	.string "{STR_VAR_1}씨의 비밀기지를\l"
	.string "방문해 보시는 건 어떨까요?\p"
	.string "그럼 또 누군가의 비밀기지에서\n"
	.string "만납시다! 그럼 안녕히!$"
	@ テレビの まえの みなさんもｎ
	@ §いさんの ひみつきちをｌ
	@ たずねて みては いかがでしょうか?ｐ
	@ それでは また だれかの ひみつきちでｎ
	@ おあいしましょう! さようなら!

TVSecretBaseSecrets_Text_StoppedMoving1:: @ 08288868
	.string "...멈춰 버렸습니다!\p"
	.string "전혀 움직이질 않습니다!\p"
	.string "{STR_VAR_1}씨의 비밀기지가\n"
	.string "마음에 들지 않았던 걸까요?$"
	@ ……たちどまって しまいました!ｐ
	@ ぜんぜん うごきません!ｐ
	@ §いさんの ひみつきちがｎ
	@ きに いらなかった のでしょうか?

TVSecretBaseSecrets_Text_StoppedMoving2:: @ 082888CA
	.string "...멈춰 버렸습니다!\p"
	.string "전혀 움직이질 않습니다!\p"
	.string "...지쳤던 걸까요?$"
	@ ……たちどまって しまいました!ｐ
	@ ぜんぜん うごきません!ｐ
	@ ……つかれちゃった のでしょうか?

TVSecretBaseSecrets_Text_UsedChair:: @ 08288930
	.string "의자에 앉았습니다-!\p"
	.string "무척 기쁜 것 같습니다\p"
	.string "착석감이\n"
	.string "좋았던 걸까요?$"
	@ いすに すわりました-!ｐ
	@ とっても うれしそうですｐ
	@ すわりごこちがｎ
	@ よかった のでしょうか?

TVSecretBaseSecrets_Text_UsedBalloon:: @ 082889C0
	.string "풍선으로 돌격-!\p"
	.string "터져버렸습니다-!\p"
	.string "살짝 소리에\n"
	.string "놀란 모양입니다$"
	@ ふうせんに とつげきだ-!ｐ
	@ わっちゃいました!ｐ
	@ ちょっと おとにｎ
	@ ビックリ しています

TVSecretBaseSecrets_Text_UsedTent:: @ 08288A3A
	.string "텐트에 들어갔습니다-!\p"
	.string "돌아다니고 있습니다!\p"
	.string "날뛰고 있습니다!\p"
	.string "텐트의 크기에\n"
	.string "깜짝 놀란 모양입니다!!$"
	@ テントに はいった-!ｐ
	@ はしりまわって います!ｐ
	@ あばれまわって います!ｐ
	@ テントの おおきさにｎ
	@ びっくり しています!!

TVSecretBaseSecrets_Text_UsedPlant:: @ 08288ACA
	.string "화분을 관찰하고 있습니다!\p"
	.string "의외로 어른스러운 취미를\n"
	.string "가지고 있군요...$"
	@ はちうえを かんさつ しています!ｐ
	@ いがいに アダルトな しゅみをｎ
	@ もっていますね……

TVSecretBaseSecrets_Text_UsedGoldShield:: @ 08288B1E
	.string "금상패를 보고 있습니다!\p"
	.string "눈을 반짝반짝\n"
	.string "빛내고 있네요$"
	@ きんのたてを みています!ｐ
	@ キラキラと めをｎ
	@ かがやかせて いますね

TVSecretBaseSecrets_Text_UsedSilverShield:: @ 08288B7A
	.string "은상패를 보고 있습니다!\p"
	.string "눈을 동그랗게 뜨고 있네요$"
	@ ぎんのたてを みています!ｐ
	@ めを まる-く していますね

TVSecretBaseSecrets_Text_UsedGlassOrnament:: @ 08288BC9
	.string "글라스오브제를 보고 있습니다...\p"
	.string "앗!\p"
	.string "만져 버렸습니다...\p"
	.string "지문을 덕지덕지 묻히고 있네요$"
	@ ガラスのオブジェを みています……ｐ
	@ あっ!ｐ
	@ さわっちゃいました……ｐ
	@ しもんを ペタペタ つけています

TVSecretBaseSecrets_Text_UsedTV:: @ 08288C40
	.string "TV를 보고 있습니다!\p"
	.string "상당한 TV광인 것 같네요-$"
	@ テレビを みています!ｐ
	@ かなりの テレビっこ みたいですね-

TVSecretBaseSecrets_Text_UsedMudBall:: @ 08288C88
	.string "진흙경단을 짓밟았습니다-!\p"
	.string "무척 기뻐 보이네요$"
	@ どろだんごを ふみつけました-!ｐ
	@ とっても うれしそうです

TVSecretBaseSecrets_Text_UsedBag:: @ 08288CC8
	.string "...으음?\p"
	.string "갑자기 가방의 내용물을\n"
	.string "바스락바스락 만지기 시작했는데요!\p"
	.string "그리고 {STR_VAR_2}{K_EULREUL}\n"
	.string "꺼냈습니다-!\p"
	.string "{STR_VAR_2}{K_EULREUL} 가지고\n"
	.string "스마일! 스마일!!\p"
	.string "TV 광고 같군요-!$"
	@ ……おや?ｐ
	@ とつぜん バッグの なかみをｎ
	@ ガサガサと いじりだしましたよ!ｐ
	@ そして §うをｎ
	@ とりだした-!ｐ
	@ §うを もってｎ
	@ スマイル! スマイル!!ｐ
	@ テレビの コマ-シャル みたいだ-!

TVSecretBaseSecrets_Text_UsedCushion:: @ 08288D7F
	.string "쿠션을 잡고...$"
	@ クッションを つかんで……

TVSecretBaseSecrets_Text_HitCushion:: @ 08288DA0
	.string "때렸습니다!\p"
	.string "꽤나 스트레스가\n"
	.string "쌓여 있었던 걸까요?$"
	@ たたいてます!ｐ
	@ だいぶ ストレスがｎ
	@ たまっている のでしょうか?

TVSecretBaseSecrets_Text_HuggedCushion:: @ 08288DDA
	.string "안았습니다-!\p"
	.string "무슨 좋은 일이라도 있었던 걸까요?$"
	@ だきついた-!ｐ
	@ なにか いいことでも あった のでしょうか?

TVSecretBaseSecrets_Text_BattledWon:: @ 08288E1E
	.string "{STR_VAR_1}씨와 얘기하고 있습니다!\p"
	.string "아무래도 포켓몬 배틀을 할 모양이군요\p"
	.string "그리고...\p"
	.string "이겼습니다-!!\p"
	.string "기뻐하고 있네요$"
	@ §いさんと はなしています!ｐ
	@ どうやら ポケモンバトルを やるようですｐ
	@ そして……ｐ
	@ かった-!!ｐ
	@ うれしがっています

TVSecretBaseSecrets_Text_BattledLost:: @ 08288EC9
	.string "{STR_VAR_1}씨와 얘기하고 있습니다!\p"
	.string "아무래도 포켓몬 배틀을 할 모양이군요\p"
	.string "그리고...\p"
	.string "졌습니다-!!\p"
	.string "실망하고 있네요$"
	@ §いさんと はなしています!ｐ
	@ どうやら ポケモンバトルを やるようですｐ
	@ そして……ｐ
	@ まけた-!!ｐ
	@ がっかり しています

TVSecretBaseSecrets_Text_DeclinedBattle:: @ 08288F58
	.string "{STR_VAR_1}씨와 얘기하고 있습니다!\p"
	.string "아무래도 포켓몬 배틀을 할 모양이군요\p"
	.string "그리고...\p"
	.string "아니 거절했습니다!\p"
	.string "대전을 거절했습니다!\p"
	.string "{STR_VAR_1}씨가\n"
	.string "마음에 들지 않았던 걸까요?$"
	@ §いさんと はなしています!ｐ
	@ どうやら ポケモンバトルを やるようですｐ
	@ そして……ｐ
	@ いや ことわった!ｐ
	@ たいせんを ことわりました!ｐ
	@ §いさんの ことがｎ
	@ きに いらなかった のでしょうか?

TVSecretBaseSecrets_Text_UsedPoster:: @ 08289011
	.string "포스터를 빤히 보고 있습니다!\p"
	.string "마음에 들었던 걸까요?\p"
	.string "...근데\n"
	.string "눈빛이 좀 위험하네요-$"
	@ ポスタ-を じ-っと みつめています!ｐ
	@ きに いった のでしょうか?ｐ
	@ ……でもｎ
	@ ちょっと めつきが やばいですね-

TVSecretBaseSecrets_Text_UsedNoteMat:: @ 082890A4
	.string "음표매트를 밟았습니다-!\p"
	.string "...으-음\n"
	.string "이상한 곡을 만들고 있네요...$"
	@ おんぷマットに のった-!ｐ
	@ ……う-んｎ
	@ ふしぎな きょくを つくっちゃいました……

TVSecretBaseSecrets_Text_BattledDraw:: @ 082890F0
	.string "{STR_VAR_1}씨와 얘기하고 있습니다!\p"
	.string "아무래도 포켓몬 배틀을 할 모양이군요\p"
	.string "그리고...\p"
	.string "무승부입니다-!!\p"
	.string "둘 다 실망하고 있네요$"

TVSecretBaseSecrets_Text_UsedSpinMat:: @ 08289193
	.string "뱅그르매트를 밟았습니다-!\p"
	.string "눈이 도는 모양이군요!\p"
	.string "어질어질한 상태네요$"
	@ くるっとマットに のった-!ｐ
	@ めが まわった ようです!ｐ
	@ クラクラ しています

TVSecretBaseSecrets_Text_UsedSandOrnament:: @ 08289204
	.string "모래장식품에 손을 대려고...\p"
	.string "앗!\p"
	.string "부서져 버렸습니다-!\p"
	.string "얼굴이 조금 굳어졌네요$"
	@ すなのおきものに てを ふれて……ｐ
	@ あっ!ｐ
	@ こわしちゃいました-!ｐ
	@ かおが すこし ひきつっています

TVSecretBaseSecrets_Text_UsedDesk:: @ 0828927C
	.string "책상 위를\n"
	.string "손가락으로 만지고 있습니다!\p"
	.string "아무래도 먼지가\n"
	.string "신경 쓰이는 것 같군요!\p"
	.string "이야-\n"
	.string "의외로 섬세하네요-$"
	@ つくえの うえをｎ
	@ ゆびで さわっています!ｐ
	@ どうやら ほこりがｎ
	@ きに なっている みたいです!ｐ
	@ いや-ｎ
	@ いがいに こまかい ですね-

TVSecretBaseSecrets_Text_UsedBrick:: @ 08289313
	.string "벽돌을 빤히 바라보고 있습니다!\p"
	.string "이 벽돌에 맞는 굿즈라도\n"
	.string "생각하고 있는 걸까요?$"
	@ レンガを じ-っと みつめています!ｐ
	@ この レンガにあう グッズの ことでもｎ
	@ かんがえている のでしょうか?

TVSecretBaseSecrets_Text_UsedSolidBoard:: @ 08289375
	.string "단단한 판자 위를 걷고 있습니다!\p"
	.string "조금 밑을 신경 쓰고 있군요\p"
	.string "의외로 소심한 성격이네요-$"
	@ じょうぶないたの うえを あるいています!ｐ
	@ ちょっと したを きにしていますｐ
	@ いがいに きが ちっちゃいですね-

TVSecretBaseSecrets_Text_UsedFence:: @ 082893FF
	.string "울타리를 빤히 바라보고 있습니다!\p"
	.string "새로운 트랩이라도\n"
	.string "떠오른 걸까요?$"
	@ さくを じ-っと ながめています!ｐ
	@ あたらしい トラップでもｎ
	@ ひらめいた のでしょうか?

TVSecretBaseSecrets_Text_UsedGlitterMat:: @ 08289465
	.string "반짝반짝매트를 밟았습니다-!\p"
	.string "다양한 포즈를 취하고 있군요!\p"
	.string "아이돌이 된 기분일까요?$"
	@ きらきらマットに のった-!ｐ
	@ いろんな ポ-ズを きめています!ｐ
	@ きぶんは アイドル でしょうか?

TVSecretBaseSecrets_Text_UsedTire:: @ 082894F2
	.string "타이어를 빤히 바라보고 있습니다!\p"
	.string "이 타이어로 달리는 자동차라도\n"
	.string "생각하고 있었던 걸까요?$"
	@ タイヤを じ-っと みつめています!ｐ
	@ この タイヤで はしる くるまの ことでもｎ
	@ かんがえている のでしょうか?

TVSecretBaseSecrets_Text_UsedStand:: @ 08289564
	.string "큰 받침대에 올라갔습니다!\p"
	.string "{STR_VAR_1}씨의 기지를\n"
	.string "위에서 내다보고 있군요!\p"
	.string "...그리고\p"
	.string "소리를 질렀습니다-!$"
	@ おおきなだいに のぼりました!ｐ
	@ §いさんの きちをｎ
	@ うえから みわたしています!ｐ
	@ ……そしてｐ
	@ さけんだ-!

TVSecretBaseSecrets_Text_BrokeDoor:: @ 082895EB
	.string "부서지는 도어를 향해 돌격-!\p"
	.string "웃고 있습니다...$"
	@ やぶれるドアに むかって とつげき-!ｐ
	@ わらっています……

TVSecretBaseSecrets_Text_UsedDoll:: @ 08289645
	.string "인형에게 말을 걸고 있습니다!\p"
	.string "조금 무섭네요...$"
	@ ぬいぐるみに はなし かけています!ｐ
	@ ちょっと こわい ですね……

TVSecretBaseSecrets_Text_UsedSlide:: @ 0828967E
	.string "미끄럼대의 사다리를 올라갔습니다!\p"
	.string "...그리고\p"
	.string "미끄러졌군요-!\p"
	.string "무척 즐거워 보이네요!$"
	@ すべりだいの はしごを のぼりました!ｐ
	@ ……そしてｐ
	@ すべった-!ｐ
	@ とっても たのしそうだ!

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown:: @ 082896FC
	.string "미끄럼대의 사다리를 올라갔습니다!\p"
	.string "...그리고\p"
	.string "돌아왔군요-!\p"
	.string "사다리에서 내려와 되돌려 놨습니다!\p"
	.string "무서웠던 걸까요?$"
	@ すべりだいの はしごを のぼりました!ｐ
	@ ……そしてｐ
	@ もどった-!ｐ
	@ ハシゴを おりて ひきかえしました!ｐ
	@ こわくなった のでしょうか?

TVSecretBaseSecrets_Text_UsedJumpMat:: @ 0828977D
	.string "점프매트를 밟았습니다-!\p"
	.string "점프를 1번!\p"
	.string "점프를 2번!\p"
	.string "착지 성공!\p"
	.string "...혼자서 스스로에게\n"
	.string "박수를 보내고 있네요$"
	@ ジャンプマットに のった-!ｐ
	@ ジャンプを 1かい!ｐ
	@ ジャンプを 2かい!ｐ
	@ ちゃくち せいこう!ｐ
	@ ……ひとりで じぶんにｎ
	@ はくしゅを おくっています

gTVSafariFanClubText00:: @ 08289813
	.string "사파리존 애호가클럽!”\p"
	.string "리포터: 사파리볼 던지고 계신가요?\n"
	.string "저는 지금 희귀한 포켓몬이\l"
	.string "잔뜩 있는 사파리존에 와 있습니다\p"
	.string "바로 담당자분께\n"
	.string "말을 걸어보도록 하죠!\p"
	.string "...사파리존에 와 있는 트레이너의\n"
	.string "모습은 어떤가요?$"
	@ 『サファリ だいすき クラブ!』ｐ
	@ レポ-タ-『サファリボ-ル なげてますか?ｎ
	@ わたしは いま めずらしい ポケモンがｌ
	@ いっぱいの サファリゾ-ンに きていますｐ
	@ さっそく かかりいんさんにｎ
	@ おはなしを うかがって みましょう!ｐ
	@ ……サファリに きている トレ-ナ-たちのｎ
	@ ようすは いかがですか?

gTVSafariFanClubText01:: @ 0828992F
	.string "담당자: 다들 열심히 하고 있지요\p"
	.string "특히 {STR_VAR_1}씨는\n"
	.string "대단합니다\p"
	.string "지난번에 무려 {STR_VAR_2}마리나\n"
	.string "잡았다니까요!$"
	@ かかりいん『みんな がんばってますよｐ
	@ とくに §いさん なんてｎ
	@ すごいですｐ
	@ この あいだ なんて §うひきもｎ
	@ つかまえたんですよ!

gTVSafariFanClubText02:: @ 0828999D
	.string "{STR_VAR_2}개의 포켓몬스넥을\n"
	.string "효율적으로 쓰고 있었습니다!$"
	@ §うこの ポロックをｎ
	@ じょうずに つかっていました!

gTVSafariFanClubText03:: @ 082899DC
	.string "게다가 포켓몬스넥을 1개도\n"
	.string "쓰지 않았지요!\p"
	.string "이야- 정말 굉장한 실력이에요$"
	@ しかも ポロックを 1こもｎ
	@ つかって いないんです!ｐ
	@ いや- すごい うで でしたよ

gTVSafariFanClubText04:: @ 08289A29
	.string "리포터: 그렇습니까-\p"
	.string "{STR_VAR_1}씨는\n"
	.string "사파리의 명인이었군요\p"
	.string "담당자: 또 와서\n"
	.string "그 굉장한 기술을 보여 줬으면 합니다$"
	@ レポ-タ-『そうですか-ｐ
	@ §いさんはｎ
	@ サファリの めいじん ですねｐ
	@ かかりいん『また おとずれてｎ
	@ あの すごい わざを みせて ほしいです

gTVSafariFanClubText05:: @ 08289AC2
	.string "담당자: 다들 많이 부족한 것 같네요...\p"
	.string "특히 {STR_VAR_1}씨는\n"
	.string "심했습니다\p"
	.string "지난번에는 겨우 {STR_VAR_2}마리밖에\n"
	.string "잡지 못했다고요$"
	@ かかりいん『みんな いまいち ですね……ｐ
	@ とくに §いさんはｎ
	@ ひどかった ですねｐ
	@ この あいだ なんて §うひき しかｎ
	@ つかまえられません でしたから

gTVSafariFanClubText06:: @ 08289B42
	.string "담당자: 다들 많이 부족한 것 같네요...\p"
	.string "특히 {STR_VAR_1}씨는\n"
	.string "심했습니다\p"
	.string "지난번에는 겨우 1마리밖에\n"
	.string "잡지 못했으니까요...$"
	@ かかりいん『みんな いまいち ですね……ｐ
	@ とくに §いさんはｎ
	@ ひどかった ですねｐ
	@ この あいだ なんて 1ひきもｎ
	@ つかまえられません でしたから……

gTVSafariFanClubText07:: @ 08289BC5
	.string "일단 포켓몬스넥을 {STR_VAR_2}개\n"
	.string "썼지만 말이죠\p"
	.string "조금만 더\n"
	.string "실력을 올렸으면 하네요-$"
	@ いちおう ポロックは §うこｎ
	@ つかって いましたけどねｐ
	@ もう ちょっとｎ
	@ うでを あげて ほしいですね-

gTVSafariFanClubText08:: @ 08289C3B
	.string "1개도 쓰지 않았던\n"
	.string "포켓몬스넥을 쓸 수 있게 되면\l"
	.string "잘될 거라 생각하는데 말이죠...$"
	@ 1こも つかってなかったｎ
	@ ポロックを つかうように なればｌ
	@ よくなると おもうんですがね……

gTVSafariFanClubText09:: @ 08289C99
	.string "리포터: 그렇습니까-\p"
	.string "{STR_VAR_1}씨는\n"
	.string "사파리 특훈을 해야 할 것 같군요\p"
	.string "담당자: 몇 번이고 와서\n"
	.string "요령을 깨우치길 바라는 마음입니다$"
	@ レポ-タ-『そうですか-ｐ
	@ §いさん にはｎ
	@ サファリを とっくんして ほしいですねｐ
	@ かかりいん『なんども おとずれてｎ
	@ コツを つかんで ほしいです

gTVSafariFanClubText10:: @ 08289D33
	.string "리포터: 그렇군요!\n"
	.string "도전은 중요한 법이니까요\p"
	.string "TV 앞에 계신 여러분도 몇 번이고\n"
	.string "사파리에 도전해 보세요!\p"
	.string "그럼 안녕히!$"
	@ レポ-タ-『そうです!ｎ
	@ チャレンジは たいせつですｐ
	@ テレビの まえの みなさんも なんどでもｎ
	@ サファリに チャレンジ しましょう!ｐ
	@ では また!

ContestLiveUpdates_Text_Intro:: @ 08289DD6
	.string "“포켓몬 콘테스트\n"
	.string "  결과 속보!”\p"
	.string "사회자: ...네!\n"
	.string "이쪽은 방금 막 끝난\l"
	.string "{STR_VAR_1}콘테스트 회장입니다\p"
	.string "회장에는 아직 수많은\n"
	.string "관객들이 남아 있네요\p"
	.string "관객: {STR_VAR_2}---!\p"
	.string "관객: {STR_VAR_3}---!\p"
	.string "사회자: ...지금 막 여러분이 들으신 대로\n"
	.string "우승한 포켓몬은\l"
	.string "{STR_VAR_3}씨의 {STR_VAR_2}입니다!\p"
	.string "관객: {STR_VAR_2}! 최고다-!\p"
	.string "관객: {STR_VAR_3}! 멋지다-!\p"
	.string "사회자: 그럼... 관객분들에게\n"
	.string "잠깐 감상을 들어보도록 하죠!$"
	@ 『ポケモン コンテストｎ
	@  けっか そくほう!』ｐ
	@ しかい『……はい!ｎ
	@ こちら さきほど おわりましたｌ
	@ §い コンテストの かいじょうですｐ
	@ かいじょうには まだ たくさんのｎ
	@ おきゃくさんが のこっていますｐ
	@ かんきゃく『§う---!ｐ
	@ かんきゃく『§え---!ｐ
	@ しかい『……と みなさんが おっしゃるｎ
	@ とおりに ゆうしょう ポケモンはｌ
	@ §えさんの §う でした!ｐ
	@ かんきゃく『§う! さいこ-!ｐ
	@ かんきゃく『§え! えらい-!ｐ
	@ しかい『それでは…… おきゃくさんにｎ
	@ ちょっと かんそうを きいて みましょう!

ContestLiveUpdates_Text_WonBothRounds:: @ 08289F53
	.string "관객: 1차 심사도 2차 심사도\n"
	.string "단독으로 1등이었습니다-!\l"
	.string "{STR_VAR_2}{K_EUNNEUN} 다음에도 우승할 거예요!$"
	@ かんきゃく『1じ しんさも 2じ しんさもｎ
	@ だんとつで 1ばん でした-!ｌ
	@ §う つぎも ゆうしょうだ-!

ContestLiveUpdates_Text_BetterRound2:: @ 08289FB0
	.string "관객: 1차 심사에서는 부진했었는데\n"
	.string "2차 심사에서 대역전했어요!\l"
	.string "미라클 {STR_VAR_2} 만세--!$"
	@ かんきゃく『1じ しんさが だめ だったのにｎ
	@ 2じ しんさで だいぎゃくてん!ｌ
	@ ミラクル §う ばんざい--!

ContestLiveUpdates_Text_EqualRounds:: @ 0828A047
	.string "관객: 1차 심사도 2차 심사도\n"
	.string "평범했었는데...\p"
	.string "{STR_VAR_2}에 {STR_VAR_3}씨!\n"
	.string "자네들 범상치 않구먼...$"
	@ かんきゃく『1じ しんさも 2じ しんさもｎ
	@ あんてい しておったのう……ｐ
	@ §うに §えさん!ｎ
	@ あんたら ただものでは ないのう……

ContestLiveUpdates_Text_BetterRound1:: @ 0828A0C6
	.string "관객: {STR_VAR_2}의\n"
	.string "그 {STR_VAR_1}{K_EUNNEUN} 격이 달랐죠!\l"
	.string "다음엔 더 어필 힘내-!$"
	@ かんきゃく『§うのｎ
	@ あの §いは ケタちがい でしたね!ｌ
	@ つぎは もっと アピ-ルを がんばって-!

ContestLiveUpdates_Text_GotNervous:: @ 0828A132
	.string "관객: {STR_VAR_2}{K_IGA}\n"
	.string "긴장했을 때 무심코\l"
	.string "힘내라고 외쳐버렸네요\p"
	.string "{STR_VAR_2} 다행이다 우승 축하해!$"
	@ かんきゃく『§うがｎ
	@ きんちょう したとき おもわずｌ
	@ がんばれ- って さけんじゃいましたｐ
	@ §う よかったね おめでとう!

ContestLiveUpdates_Text_StartledFoes:: @ 0828A1BE
	.string "관객: {STR_VAR_2}의 어필에\n"
	.string "무심코 저도 놀라고 말았어요!\p"
	.string "{STR_VAR_2}! 넌 대단해!$"
	@ かんきゃく『§うの アピ-ルでｎ
	@ おもわず ボクも おどろいちゃった!ｐ
	@ §う! きみは スゴイ!

ContestLiveUpdates_Text_UsedCombo:: @ 0828A202
	.string "관객: {STR_VAR_2}의\n"
	.string "그 콤보 어필!\l"
	.string "아아 정말 황홀했어요...$"
	@ かんきゃく『§うのｎ
	@ あの コンボでの アピ-ル!ｌ
	@ ああ もう ウットリ……

ContestLiveUpdates_Text_ExcitingAppeal:: @ 0828A24E
	.string "관객: {STR_VAR_2}의 어필에\n"
	.string "그만 불타올라 버렸어요!$"
	@ かんきゃく『§うの アピ-ルにｎ
	@ もう もえあがっちゃいました!

ContestLiveUpdates_Text_WasCool:: @ 0828A288
	.string "{STR_VAR_2}!\n"
	.string "근사했어-!$"
	@ §う!ｎ
	@ かっこよかった よ-!

ContestLiveUpdates_Text_WasBeautiful:: @ 0828A29B
	.string "{STR_VAR_2}!\n"
	.string "아름다웠어-!$"
	@ §うｎ
	@ うつくしかった よ-!

ContestLiveUpdates_Text_WasCute:: @ 0828A2B3
	.string "{STR_VAR_2}!\n"
	.string "귀여웠어-!$"
	@ §うｎ
	@ かわいかった よ-!

ContestLiveUpdates_Text_WasSmart:: @ 0828A2C6
	.string "{STR_VAR_2}!\n"
	.string "슬기로웠어-!$"
	@ §う!ｎ
	@ かしこかった よ-!

ContestLiveUpdates_Text_WasTough:: @ 0828A2DA
	.string "{STR_VAR_2}!\n"
	.string "강인했어-!$"
	@ §う!ｎ
	@ たくましかった よ-!

ContestLiveUpdates_Text_VeryExcitingAppeal:: @ 0828A2EE
	.string "관객: {STR_VAR_2}의 어필에\n"
	.string "그만 두근거리고 말았어요!$"
	@ かんきゃく『§うの アピ-ルにｎ
	@ もう もえつきちゃい ました!

ContestLiveUpdates_Text_VeryCool:: @ 0828A32E
	.string "{STR_VAR_2}!\n"
	.string "최고로 근사했어-!$"
	@ §う!ｎ
	@ さいこうに かっこいい-!

ContestLiveUpdates_Text_VeryBeautiful:: @ 0828A350
	.string "{STR_VAR_2}!\n"
	.string "최고로 아름다웠어-!$"
	@ §う!ｎ
	@ さいこうに うつくしい-!

ContestLiveUpdates_Text_VeryCute:: @ 0828A36F
	.string "{STR_VAR_2}!\n"
	.string "최고로 귀여웠어-!$"
	@ §う!ｎ
	@ さいこうに かわいい-!

ContestLiveUpdates_Text_VerySmart:: @ 0828A38D
	.string "{STR_VAR_2}!\n"
	.string "최고로 슬기로웠어-!$"
	@ §う!ｎ
	@ さいこうに かしこい-!

ContestLiveUpdates_Text_VeryTough:: @ 0828A3B6
	.string "{STR_VAR_2}!\n"
	.string "최고로 강인했어-!$"
	@ §う!ｎ
	@ さいこうに たくましい-!

ContestLiveUpdates_Text_TookBreak:: @ 0828A3DC
	.string "관객: {STR_VAR_2}{K_IGA} 중간에\n"
	.string "어필을 쉬었을 때도...\l"
	.string "계-속 {STR_VAR_2}만 보고 있었어요!\p"
	.string "전 이미 {STR_VAR_2}의 포로예요...$"
	@ かんきゃく『§うが とちゅうでｎ
	@ アピ-ルを やすんだ ときも……ｌ
	@ ず-っと §うだけ みてました!ｐ
	@ もう §うの とりこ です……

ContestLiveUpdates_Text_GotStartled:: @ 0828A455
	.string "관객: {STR_VAR_2}{K_IGA} 다른\n"
	.string "포켓몬의 어필에 놀랐을 때는\l"
	.string "그만 울어버릴 것 같았어요!\p"
	.string "{STR_VAR_2}\n"
	.string "열심히 했구나-! 대단해!$"
	@ かんきゃく『§うが ほかのｎ
	@ ポケモンの アピ-ルに おどろいた ときはｌ
	@ もう なきそうに なっちゃいました!ｐ
	@ §うｎ
	@ がんばったね-! えらい!

ContestLiveUpdates_Text_MoveWonderful:: @ 0828A4CF
	.string "관객: 아아...\n"
	.string "{STR_VAR_2}의 {STR_VAR_3}!\l"
	.string "{STR_VAR_2}의 {STR_VAR_3}!\l"
	.string "{STR_VAR_2}의 {STR_VAR_3}!\l"
	.string "넌 왜 그렇게 멋진 거니-!$"
	@ かんきゃく『ああ……ｎ
	@ §うの §え!ｌ
	@ §うの §え!ｌ
	@ §うの §え!ｌ
	@ なんで あんなに ステキなんだ-!

ContestLiveUpdates_Text_TalkAboutAnotherMon:: @ 0828A51C
	.string "사회자: ...이야- 굉장하네요\n"
	.string "{STR_VAR_1}의 팬들로 가득한데요\p"
	.string "다른 트레이너와 포켓몬 중에서\n"
	.string "제 인상에 남은 건...\l"
	.string "{STR_VAR_2}씨의 {STR_VAR_3}{K_I}군요\p"
	.string "{STR_VAR_2}씨의 {STR_VAR_3}{K_EUNNEUN}...$"
	@ しかい『……いや- すごいですねｎ
	@ §いファン いっしょくですｐ
	@ その ほかの トレ-ナ-さんと ポケモンでｎ
	@ わたしの いんしょうに のこったのは……ｌ
	@ §うさんと §えですねｐ
	@ §うさんの §えは……

ContestLiveUpdates_Text_FailedToAppeal:: @ 0828A5AC
	.string "긴장해서 2차 심사에서 한 번도\n"
	.string "어필을 하지 못했습니다\p"
	.string "다음엔 한 번만이라도 {STR_VAR_1}의\n"
	.string "어필을 보고 싶네요$"
	@ きんちょうして 2じしんさで 1かいもｎ
	@ アピ-ルが できませんでしたｐ
	@ つぎは 1かい だけでも §いのｎ
	@ アピ-ルを みたいものです

ContestLiveUpdates_Text_LastInBothRounds:: @ 0828A638
	.string "1차 심사도 2차 심사도\n"
	.string "단연 꼴찌였습니다\p"
	.string "{STR_VAR_1}씨가 {STR_VAR_2}{K_EULREUL}\n"
	.string "다시 단련시켜서\l"
	.string "꼴찌에서 벗어났으면 하네요$"
	@ 1じしんさも 2じしんさもｎ
	@ ダントツで ビリでしたｐ
	@ §いさんには §うをｎ
	@ きたえ なおしてｌ
	@ ビリから ぬけだして ほしいです

ContestLiveUpdates_Text_NotExcitingEnough:: @ 0828A6CF
	.string "회장이 불타오르고 있을 때에\n"
	.string "걸맞은 어필을 하지 못했었죠\p"
	.string "{STR_VAR_1}씨가 흐름을 읽고\n"
	.string "다음엔 회장을 익사이트시켜서\l"
	.string "최고로 불타오르게 했으면 하네요$"
	@ かいじょうが もりあがっている ときにｎ
	@ ふさわしい アピ-ルが できません でしたｐ
	@ §いさんには ながれを よんでｎ
	@ つぎこそ かいじょうを エキサイト させてｌ
	@ さいこうに もりあげて ほしいです

ContestLiveUpdates_Text_LostAfterWinningRound1:: @ 0828A797
	.string "1차 심사에서 1등이었는데\n"
	.string "2차 심사의 어필이 부족해서\l"
	.string "역전패를 당하고 말았지요\p"
	.string "분명 지금쯤 {STR_VAR_1}씨는\n"
	.string "어필에 대해서\l"
	.string "공부하고 있을 거라고 생각합니다$"
	@ 1じしんさで いちばん だったのにｎ
	@ 2じしんさの アピ-ルが うまくいかずｌ
	@ ぎゃくてん まけを してしまいましたｐ
	@ きっと いまごろ §いさんはｎ
	@ アピ-ルに ついてｌ
	@ べんきょう していると おもいます

ContestLiveUpdates_Text_NeverExciting:: @ 0828A86D
	.string "2차 심사의 어필에서 한 번도\n"
	.string "관객을 흥분시키지 못했지요\p"
	.string "다른 포켓몬을 신경 쓰지 말고\n"
	.string "좀 더 관객을 향해서\l"
	.string "어필을 해 주었으면 합니다$"
	@ 2じ しんさの アピ-ルで 1どもｎ
	@ かんきゃくが もりあがり ませんでしたｐ
	@ ほかの ポケモンの ことは きにせずｎ
	@ もっと かんきゃくに むかってｌ
	@ アピ-ルをして ほしいです

ContestLiveUpdates_Text_LostBySmallMargin:: @ 0828A920
	.string "{STR_VAR_1}씨의 {STR_VAR_2}{K_WAGWA}\n"
	.string "간발의 차로 지고 말았지요\p"
	.string "조금만 더 잘했으면 우승이었는데\n"
	.string "무척 유감입니다\p"
	.string "지금쯤 {STR_VAR_3}씨는\n"
	.string "울고 있을 거라고 생각해요$"
	@ §いさんの §うとｎ
	@ ちょっとの さで まけて しまいましたｐ
	@ あと すこしで ゆうしょう だったのにｎ
	@ とっても ざんねんですｐ
	@ いまごろ §えさんはｎ
	@ ないていると おもいます

ContestLiveUpdates_Text_RepeatedAppeals:: @ 0828A9CC
	.string "같은 어필을 계속해서 심사위원을\n"
	.string "실망시키고 말았었죠\p"
	.string "콘테스트에서 하면 안 되는\n"
	.string "실수를 한 것이 뼈아팠네요\p"
	.string "지금쯤 {STR_VAR_1}씨는\n"
	.string "자신을 탓하고 있을 거라고 생각합니다$"
	@ おなじ アピ-ルを つづけて しんさいんにｎ
	@ がっかりされて しまいましたｐ
	@ コンテストで やっては いけないｎ
	@ ミスを したのが いたかったですねｐ
	@ いまごろ §いさんはｎ
	@ じぶんを せめていると おもいます

ContestLiveUpdates_Text_ValiantEffortButLost:: @ 0828AA74
	.string "{STR_VAR_1}씨가 시키는 대로 열심히\n"
	.string "했지만...\p"
	.string "결과적으로는 꼴찌가 되어버렸습니다\p"
	.string "{STR_VAR_1}씨가 진 이유를\n"
	.string "분석해 발판으로 삼았으면 좋겠네요$"
	@ §いさん なりに がんばってｎ
	@ いたのですが……ｐ
	@ けっかてきに ビリに なってしまいましたｐ
	@ §いさんには まけた りゆうをｎ
	@ かんがえて つぎに つなげて ほしいです

ContestLiveUpdates_Text_Outro:: @ 0828AB01
	.string "그럼 마지막으로 다 같이\n"
	.string "{STR_VAR_1}씨와 {STR_VAR_2}에게\l"
	.string "한마디 전하도록 하겠습니다\p"
	.string "사회자: 여러분 준비됐나요-? 하나 둘\p"
	.string "모두: {STR_VAR_1}씨! {STR_VAR_2}!\n"
	.string "콘테스트 우승 축하해-!$"
	@ それでは さいごに みなさんと ごいっしょにｎ
	@ §いさんと §うにｌ
	@ ひとこと おくりたいと おもいますｐ
	@ しかい『みなさん いいですか-? せ-のｐ
	@ みんな『§いさん! §う!ｎ
	@ コンテスト ゆうしょう おめでとう-!

gTVPokemonBattleUpdateText00:: @ 0828ABCC
	.string "“포켓몬 대전 속보!”\p"
	.string "방금 전에 일어난 포켓몬 배틀의\n"
	.string "결과를 전해 드립니다$"
	@ 『ポケモン たいせん そくほう!』ｐ
	@ さきほど おこなわれた ポケモンバトルのｎ
	@ けっかを おつたえします

gTVPokemonBattleUpdateText01:: @ 0828AC22
	.string "{STR_VAR_1}씨 VS\n"
	.string "{STR_VAR_2}씨의 {STR_VAR_3}배틀은...\p"
	.string "{STR_VAR_1}씨의\n"
	.string "승리로 끝났습니다!$"
	@ §いさん たいｎ
	@ §うさんの §えバトルは……ｐ
	@ §いさんがｎ
	@ しょうり しました!

gTVPokemonBattleUpdateText02:: @ 0828AC7E
	.string "배틀에선 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}{K_IGA} {STR_VAR_3}{K_EULREUL} 써서\l"
	.string "대활약했습니다!$"
	@ バトルは §いさんのｎ
	@ §うが §えを つかってｌ
	@ だいかつやく しました!

gTVPokemonBattleUpdateText03:: @ 0828ACB6
	.string "{STR_VAR_1}씨에게 있어선\n"
	.string "{STR_VAR_2}{K_IGA} 걸림돌이었던 게\l"
	.string "뼈아팠던 모양입니다$"
	@ §いさんに とってはｎ
	@ §うが ブレ-キ だったのがｌ
	@ いたかった ようです

gTVPokemonBattleUpdateText04:: @ 0828ACE3
	.string "승리를 쟁취한\n"
	.string "{STR_VAR_1}씨!\l"
	.string "축하합니다!\p"
	.string "무너지고 만\n"
	.string "{STR_VAR_2}씨!\l"
	.string "다음엔 열심히 해주세요!\p"
	.string "이상으로\n"
	.string "“포켓몬 대전 속보!”였습니다$"
	@ しょうりを おさめたｎ
	@ §いさん!ｌ
	@ おめでとう ございました!ｐ
	@ やぶれて しまったｎ
	@ §うさん!ｌ
	@ つぎは がんばって ください!ｐ
	@ いじょうｎ
	@ 『ポケモン たいせん そくほう!』 でした

gTVPokemonBattleUpdateText05:: @ 0828AD80
	.string "{STR_VAR_1}씨 팀 VS\n"
	.string "{STR_VAR_2}씨 팀\l"
	.string "멀티배틀의 결과는...\p"
	.string "{STR_VAR_1}씨 팀의\n"
	.string "승리로 끝났습니다$"
	@ §いさん チ-ム たいｎ
	@ §うさん チ-ムのｌ
	@ マルチバトルの けっかは……ｐ
	@ §いさん チ-ムがｎ
	@ しょうり しました

gTVPokemonBattleUpdateText06:: @ 0828ADE2
	.string "배틀에선 {STR_VAR_1}씨 팀의\n"
	.string "{STR_VAR_2}{K_IGA} {STR_VAR_3}{K_EULREUL} 써서\l"
	.string "대활약했습니다!$"
	@ バトルは §いさん チ-ムのｎ
	@ §うが §えを つかってｌ
	@ だいかつやく しました!

gTVPokemonBattleUpdateText07:: @ 0828AE26
	.string "{STR_VAR_2}씨 팀에게 있어선\n"
	.string "{STR_VAR_3}{K_IGA} 걸림돌이었던 게\l"
	.string "뼈아팠던 모양입니다\p"
	.string "승리를 쟁취한\n"
	.string "{STR_VAR_1}씨 팀!\l"
	.string "축하합니다!\p"
	.string "무너지고 만\n"
	.string "{STR_VAR_2}씨 팀!\l"
	.string "다음엔 열심히 해주세요!\p"
	.string "이상으로\n"
	.string "“포켓몬 대전 속보!”였습니다$"
	@ §うさん チ-ムに とってはｎ
	@ §えが ブレ-キ だったのがｌ
	@ いたかった ようですｐ
	@ しょうりを おさめたｎ
	@ §いさん チ-ム!ｌ
	@ おめでとう ございました!ｐ
	@ やぶれて しまったｎ
	@ §うさん チ-ム!ｌ
	@ つぎこそ がんばって ください!ｐ
	@ いじょうｎ
	@ 『ポケモン たいせん そくほう!』 でした

GabbyAndTy_Text_GabbyPreFirstBattle: @ 0828AF05
	.string "마리: 오 이런 곳에서\n"
	.string "강해보이는 트레이너 발견!\p"
	.string "좋-아 카메라 돌리고\n"
	.string "인터뷰 시작이야!$"
	@ マリ『おっ こんなところにｎ
	@ つよそうな トレ-ナ- はっけん!ｐ
	@ よ-し カメラを まわしてｎ
	@ インタビュ- かいしよ!

GabbyAndTy_Text_GabbyIntro: @ 0828AF7D
	.string "마리: 아! 당신은\n"
	.string "지난번 배틀했던 {PLAYER}씨!\p"
	.string "좋-아 얼마나 강해졌는지\n"
	.string "바로 인터뷰 시작이야!$"
	@ マリ『あ! あなたはｎ
	@ このあいだの §あさん!ｐ
	@ よ-し どのくらい つよく なったかｎ
	@ さっそく インタビュ- かいしよ!

GabbyAndTy_Text_GabbyDefeatFirstTime: @ 0828B000
	.string "마리: 내 눈은 틀리지 않았어\n"
	.string "엄청난 트레이너를 발견한 거야!$"
	@ マリ『わたしの めに くるいはないわｎ
	@ すごい トレ-ナ-の はっけんよ!

GabbyAndTy_Text_WhoAreYouInterview: @ 0828B042
	.string "마리: 굉장해! 정말 굉장해!\n"
	.string "당신 대체 뭐 하는 사람이야!?\p"
	.string "역시 우리가\n"
	.string "눈독들일 만해!\p"
	.string "...앗 사실 우린\n"
	.string "다양한 장소의 다양한 트레이너를\l"
	.string "인터뷰하면서 돌아다니고 있거든\p"
	.string "그러니까 잠깐만\n"
	.string "인터뷰에 응해줄 수 있을까?$"
	@ マリ『すごい! すごい!ｎ
	@ あなた いったい なにもの!?ｐ
	@ さすが わたしたちがｎ
	@ めを つけただけ あるわ!ｐ
	@ ……あっ じつは わたしたちｎ
	@ いろんな ばしょの いろんな トレ-ナ-をｌ
	@ インタビュ-して まわっているのよｐ
	@ だから すこしだけｎ
	@ インタビュ- させて もらえないかな?

GabbyAndTy_Text_QuoteFromLastInterview: @ 0828B137
	.string "마리: “{STR_VAR_1}!”\p"
	.string "기억나? 전에 배틀했을 때\n"
	.string "당신이 말한 마무리 대사야\p"
	.string "우린 제대로\n"
	.string "기억하고 있다고!$"
	@ マリ『「§い!」ｐ
	@ おぼえてる? まえに たたかった ときｎ
	@ あなたが いった きめゼリフよｐ
	@ わたしたち ちゃ-んとｎ
	@ おぼえてるん だからね!

GabbyAndTy_Text_YouStompedUsInterviewAgain: @ 0828B1B3
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "손도 발도 못 썼었지...\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	@ そうそう まえに たたかった ときはｎ
	@ ても あしも でなかった のよねぇ……ｐ
	@ ところで どう?ｎ
	@ また インタビュ- うけてみる?

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain: @ 0828B23D
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "우리한테 몬스터볼을 던졌었지...\p"
	.string "정말 깜짝 놀라서 다른 사람들한테\n"
	.string "떠들고 다녔다니까!\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	@ そうそう まえに たたかった ときはｎ
	@ ボ-ルを なげられ たんだっけ……ｐ
	@ もう びっくりして みんなにｎ
	@ いいふらし ちゃったわよ!ｐ
	@ ところで どう?ｎ
	@ また インタビュ- うけてみる?

GabbyAndTy_Text_CleverItemSkillsInterviewAgain: @ 0828B2FA
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "도구를 잘 써서\l"
	.string "우리를 이겼었지\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	@ そうそう まえに たたかった ときはｎ
	@ どうぐを うまく つかわれてｌ
	@ まけちゃった のよねｐ
	@ ところで どう?ｎ
	@ また インタビュ- うけてみる?

GabbyAndTy_Text_WeLookedRespectableInterviewAgain: @ 0828B379
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "제법 좋은 승부를 했었지...\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	@ そうそう まえに たたかった ときはｎ
	@ けっこう いいしょうぶ だったんだよね……ｐ
	@ ところで どう?ｎ
	@ また インタビュ- うけてみる?

GabbyAndTy_Text_InterviewAgain: @ 0828B3F3
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	@ ところで どう?ｎ
	@ また インタビュ- うけてみる?

GabbyAndTy_Text_DescribeYourFeelings: @ 0828B433
	.string "정말!?\n"
	.string "고마워!\p"
	.string "그럼 배틀한 뒤의\n"
	.string "감상을 팍 하고 한마디로\l"
	.string "말해줘!$"
	@ ほんと!?ｎ
	@ ありがとう!ｐ
	@ じゃあ たたかいの あとのｎ
	@ かんそうを ビシッと ひとことでｌ
	@ どうぞ!

GabbyAndTy_Text_PerfectWellBeSeeingYou: @ 0828B4AB
	.string "마리: 음-!\n"
	.string "최고의 마무리 대사야\p"
	.string "왠지 좋은 TV 방송이\n"
	.string "될 것 같은 예감이 들어!\p"
	.string "어쩌면 이 인터뷰를\n"
	.string "TV로 방송하게 될지도 모르니까\l"
	.string "TV 체크하는 거 잊지 마!\p"
	.string "그럼\n"
	.string "또 어딘가에서 보자!$"
	@ マリ『ん-!ｎ
	@ さいこうの きめゼリフねｐ
	@ なんか いいテレビばんぐみがｎ
	@ できそうな よかん!ｐ
	@ もしかしたら このことをｎ
	@ テレビで ほうそうするかも しれないからｌ
	@ テレビの チェックを わすれないでね!ｐ
	@ それじゃあｎ
	@ また どこかで!

GabbyAndTy_Text_DontGiveUpKeepingEyeOut: @ 0828B577
	.string "마리: 그래...\p"
	.string "그래도 앞으로도 힘내!\n"
	.string "당신을 주목하고 있을 거야!$"
	@ マリ『そう……ｐ
	@ でも これからも がんばってね!ｎ
	@ あなたのこと ちゅうもく してるわ!

GabbyAndTy_Text_KeepingAnEyeOutForYou: @ 0828B5C0
	.string "마리: 당신을\n"
	.string "주목하고 있을 거야!$"
	@ マリ『あなたの ことｎ
	@ ちゅうもく してるわ!

GabbyAndTy_Text_GabbyNotEnoughMons: @ 0828B5EC
	.string "마리: 포켓몬을 잔뜩 데리고 있는\n"
	.string "강한 트레이너 어디 없을까?$"
	@ マリ『ポケモンを いっぱい つれてるｎ
	@ つよい トレ-ナ-って いない かしら?

GabbyAndTy_Text_GiveUsAnInterviewThisTime: @ 0828B62D
	.string "마리: 음- 역시나!\p"
	.string "전에 배틀했을 때보다\n"
	.string "훨씬 강해졌어!\p"
	.string "역시 우리가 찾아낸\n"
	.string "트레이너야!\p"
	.string "그래서 어때?\n"
	.string "이번에야말로 인터뷰를\l"
	.string "받아보지 않을래?$"
	@ マリ『う-ん さすがね!ｐ
	@ まえに たたかった ときよりｎ
	@ ずっと つよく なってる!ｐ
	@ やっぱり わたしたちが みつけたｎ
	@ トレ-ナ- よね!ｐ
	@ ところで どう?ｎ
	@ こんどこそ インタビュ-をｌ
	@ うけて もらえないかな?

GabbyAndTy_Text_GabbyDefeat: @ 0828B719
	.string "마리: 굉장한 배틀이었어!\n"
	.string "이봐 제대로 카메라에 담았지!?$"
	@ マリ『すごい たたかいだったわ!ｎ
	@ ほら ちゃんと カメラにとった!?

GabbyAndTy_Text_TyPreFirstBattle: @ 0828B75C
	.string "다이: 오 이런 곳에서\n"
	.string "강해보이는 트레이너 발견!\l"
	.string "바로 녹화 개시다!$"
	@ ダイ『おっ こんなところにｎ
	@ つよそうな トレ-ナ- はっけん!ｌ
	@ さっそく ろくが かいしだ!

GabbyAndTy_Text_TyIntro: @ 0828B7B1
	.string "다이: 넌 지난번의 그 애잖아!\p"
	.string "좋-아 이 배틀을\n"
	.string "모두 카메라에 담아주겠어$"
	@ ダイ『きみは このあいだの!ｐ
	@ よ-し この たたかいをｎ
	@ すべて カメラに おさめてやる

GabbyAndTy_Text_TyPostBattle: @ 0828B805
	.string "다이: 역시나!\n"
	.string "좋은 영상을 얻을 수 있었어!$"
	@ ダイ『さすがだな!ｎ
	@ いい えいぞうを とることが できたよ!

GabbyAndTy_Text_TyNotEnoughMons: @ 0828B841
	.string "다이: 넌 1마리밖에 포켓몬을\n"
	.string "안 데리고 다니는 거야?\p"
	.string "포켓몬이 잔뜩 있어야\n"
	.string "좋은 영상이 나올 텐데...$"
	@ ダイ『きみは 1ぴきしか ポケモンをｎ
	@ もって ないのかい?ｐ
	@ ポケモンが いっぱい いたほうがｎ
	@ いい えいぞうに なるんだが……

GabbyAndTy_Text_TyDefeatFirstTime: @ 0828B8B1
	.string "다이: 굉장한 트레이너를 발견했어\n"
	.string "이건 대특종이야!$"
	@ ダイ『すごい トレ-ナ-の はっけんだｎ
	@ これは だいスク-プだぞ!

GabbyAndTy_Text_TyDefeat: @ 0828B8F6
	.string "다이: 지금 한 배틀의 모든 게\n"
	.string "이 카메라에 담겨 있어!$"
	@ ダイ『いまの たたかいの すべてがｎ
	@ この カメラのなかに!

gTVInSearchOfTrainersText00:: @ 0828B92C
	.string "“트레이너를 찾아서”\p"
	.string "마리: 네-에! 저는 지금\n"
	.string "{STR_VAR_1}에 와 있습니다!\p"
	.string "오늘은 여기서 새로운 재능을\n"
	.string "발굴할 생각입니다!\p"
	.string "오늘 제가 주목한\n"
	.string "트레이너는 {PLAYER}씨!\p"
	.string "저는 이 트레이너에게서\n"
	.string "뭔가가 느껴집니다!$"
	@ 『トレ-ナ-を もとめて』ｐ
	@ マリ『は-い わたしは いまｎ
	@ §いに きています!ｐ
	@ きょうは ここで あたらしい さいのうをｎ
	@ はっくつ しようと おもいます!ｐ
	@ きょう わたしが ちゅうもく したｎ
	@ トレ-ナ-は §あさん!ｐ
	@ わたしは この トレ-ナ-にｎ
	@ なにかを かんじます!

gTVInSearchOfTrainersText01:: @ 0828BA20
	.string "{PLAYER}씨와는 전에\n"
	.string "배틀해본 적이 있습니다만\p"
	.string "확실히 전보다\n"
	.string "강해진 느낌이 듭니다!\p"
	.string "역시 제가\n"
	.string "주목하는 트레이너예요!$"
	@ §あさんとは まえにｎ
	@ たたかった ことが あるのですがｐ
	@ かくじつに まえよりｎ
	@ つよく なっている かんじが します!ｐ
	@ さっすが わたしのｎ
	@ ちゅうもく した トレ-ナ-!

gTVInSearchOfTrainersText02:: @ 0828BAC8
	.string "자 그럼 트레이너의 실력을\n"
	.string "보려면...\p"
	.string "배틀하는 게 제일 빠르죠!\n"
	.string "바로 조사를 개시하겠습니다!\p"
	.string "......\p"
	.string "그렇게 일단\n"
	.string "배틀을 해봤습니다만\p"
	.string "완전히 엉망진창으로 당했습니다!\n"
	.string "{PLAYER}씨는 역시 강하네요...\p"
	.string "그래서 배틀한 감상을\n"
	.string "말해 보자면$"
	@ さて トレ-ナ-の じつりょくをｎ
	@ みるには…ｐ
	@ たたかって みるのが いちばん はやい!ｎ
	@ さっそく ちょうさを かいし します!ｐ
	@ ……ｐ
	@ と いうわけでｎ
	@ たたかって みたの ですがｐ
	@ みごとに ボコボコに されました!ｎ
	@ §あさん やたら つよいですね……ｐ
	@ で たたかった かんそうをｎ
	@ いわせて もらいますと

gTVInSearchOfTrainersText03:: @ 0828BC18
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_3}의\n"
	.string "콤비는 최고였습니다!\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_3}{K_IGA} 서로\n"
	.string "도와가며 싸우는 모습...\p"
	.string "아아 이 얼마나\n"
	.string "굉장한 광경인가요!\p"
	.string "저희와의 승부에서\n"
	.string "마지막으로 썼던 “{STR_VAR_2}”도\p"
	.string "{STR_VAR_1}{K_WAGWA} {STR_VAR_3}의 우정의\n"
	.string "“{STR_VAR_2}”인 거군요!$"
	@ §いと §えのｎ
	@ コンビが さいこう でしたね!ｐ
	@ §いと §えが おたがいｎ
	@ たすけあって たたかう すがた……ｐ
	@ あぁ なんてｎ
	@ すばらしいんでしょう!ｐ
	@ わたしたちとの しょうぶでｎ
	@ さいごに つかった 「§う」もｐ
	@ §いと §えの ゆうじょうのｎ
	@ 「§う」なんですね!

gTVInSearchOfTrainersText04:: @ 0828BD20
	.string "...저 제정신을\n"
	.string "잃을 뻔했네요\p"
	.string "한 번 공격할 틈도 없이\n"
	.string "바로 져버리고 말았습니다\l"
	.string "아아 훌쩍...\p"
	.string "그래도 {PLAYER}씨의 배틀은\n"
	.string "볼 가치가 있었어요!\p"
	.string "자신 있는 트레이너는 한번\n"
	.string "배틀해보는 걸 추천드리겠습니다!$"
	@ ……わたくし じしんをｎ
	@ なくして しまいましたｐ
	@ いっかいも こうげきする ひまもなくｎ
	@ すぐに まけて しまいましたｌ
	@ ああ グスン……ｐ
	@ でも §あさんの たたかいはｎ
	@ いっけんのかち あり です!ｐ
	@ じしんの ある トレ-ナ-は いちどｎ
	@ たたかって みることを おすすめ しますよ!

gTVInSearchOfTrainersText05:: @ 0828BE01
	.string "트레이너와 배틀하고 있을 때는\n"
	.string "몬스터볼을 던지지 마!\l"
	.string "라고 말하고 싶네요\p"
	.string "{PLAYER}씨는 승부에 강하지만\n"
	.string "기본이 안 되어 있군요!\p"
	.string "TV를 보고 계신 여러분!\p"
	.string "{PLAYER}씨를 만나면\n"
	.string "주의를 주세요!$"
	@ トレ-ナ-と たたかって いるときはｎ
	@ モンスタ-ボ-ルを なげるな!ｌ
	@ という ことですｐ
	@ §あさん しょうぶは つよいのにｎ
	@ きほんが なって ませんよ!ｐ
	@ もう テレビを みてる みんな!ｐ
	@ §あさんに あったらｎ
	@ ちゅういして やってね!

gTVInSearchOfTrainersText06:: @ 0828BEEE
	.string "{PLAYER}씨는 상대의 행동을\n"
	.string "굉장히 잘 읽더라고요!\p"
	.string "도구를 쓰는 타이밍 등이\n"
	.string "상당히 좋았습니다!$"
	@ §あさん あいての こうどうをｎ
	@ よむのが とても うまいです!ｐ
	@ どうぐを つかう タイミング なんかｎ
	@ なかなかの ものでしたよ!

gTVInSearchOfTrainersText07:: @ 0828BF50
	.string "솔직히 제가 꽤\n"
	.string "강한 건 아닐까 하는 생각이 들었습니다-!\p"
	.string "마지막엔 결국 져버렸지만\n"
	.string "좋은 시합이었어요-\p"
	.string "하지만 저한테 고전하는 정도라니\n"
	.string "아직 갈 길이 멀군요 {PLAYER}씨!$"
	@ しょうじき わたしも なかなかｎ
	@ つよいかも と おもっちゃい ました-!ｐ
	@ さいごは けっきょく まけちゃった けどｎ
	@ いい しあい だったな-ｐ
	@ でも わたしに くせん してるようじゃｎ
	@ まだまだ ですよ §あさん!

gTVInSearchOfTrainersText08:: @ 0828C011
	.string "대전 후 {PLAYER}씨에게\n"
	.string "지금 대전한 감상을 물어보니\p"
	.string "“{STR_VAR_1}”{K_I}라고\n"
	.string "대답해 주었습니다\p"
	.string "{PLAYER}씨의 포켓몬인\n"
	.string "{STR_VAR_2}{K_WAGWA} {STR_VAR_3}\l"
	.string "그리고 “{STR_VAR_1}”...\p"
	.string "음-!!\n"
	.string "뭔가 의미 깊은 말이네요!\p"
	.string "역시 좋은 트레이너는\n"
	.string "좋은 말을 하는 법이죠\p"
	.string "자 그럼 또\n"
	.string "다음 방송에서 봅시다!$"
	@ たいせんの あと §あさんにｎ
	@ いまの たいせんの かんそうを きくとｐ
	@ 「§い」ってｎ
	@ こたえて くれましたｐ
	@ §あさんの ポケモンのｎ
	@ §うと §えｌ
	@ そして 「§い」……ｐ
	@ ん-!!ｎ
	@ なんか いみのふかい ことば よね!ｐ
	@ やはり いい トレ-ナ-はｎ
	@ いいことを いって くれますねｐ
	@ さて それじゃあ またｎ
	@ じかいの ほうそうで おあい しましょう!

gTVPokemonContestLiveUpdates2Text00:: @ 0828C137
	.string "“포켓몬 콘테스트 결과 속보”\p"
	.string "사회자: 여러분 정말 죄송합니다!\p"
	.string "오늘은 {STR_VAR_1}콘테스트가\n"
	.string "지금 막 종료된 이곳\l"
	.string "회장에서 전해드리겠습니다!\p"
	.string "관객: ?---!!\p"
	.string "사회자: 어이쿠 아무래도\n"
	.string "콘테스트 참가자들이\l"
	.string "이쪽으로 오는 모양이네요!\p"
	.string "전 바로 돌격 취재를\n"
	.string "해볼까 합니다!\p"
	.string "관객: ?---!! ?---!!$"
	@ 『ポケモン コンテスト けっか そくほう』ｐ
	@ しかい『みなさん きょうしゅく です!ｐ
	@ ほんじつは §いさ コンテストがｎ
	@ しゅうりょうした ばかりの こちらのｌ
	@ かいじょう から おおくり します!ｐ
	@ かんきゃく『?---!!ｐ
	@ しかい『おおっと どうやらｎ
	@ コンテスト さんかしゃ たちがｌ
	@ こちらに むかって くるようですっ!ｐ
	@ わたくし さっそく とつげき しゅざいをｎ
	@ おこないたいと おもいます!ｐ
	@ かんきゃく『?---!! ?---!!

gTVPokemonContestLiveUpdates2Text01:: @ 0828C28C
	.string "사회자: 실례합니다!\p"
	.string "우승 축하드려요!\n"
	.string "이번 승리의 열쇠가 된 건\l"
	.string "뭐라고 생각하시나요?\p"
	.string "아가씨: 저도 {STR_VAR_2}도\n"
	.string "엄청 열심히 했어요!\p"
	.string "하지만 분명 콘테스트에 나갈 때까지\n"
	.string "협력해 준 사람들 덕분에\l"
	.string "여기까지 올 수 있었다고 생각합니다!\p"
	.string "사회자: 그럼 이 기쁨을\n"
	.string "가장 전하고 싶은 사람을 향해서\l"
	.string "한마디 메시지를 부탁드립니다!\p"
	.string "아가씨: 야-호!\p"
	.string "{STR_VAR_3}씨-! 보고 있지-!?\n"
	.string "우리 해냈어-!\l"
	.string "정말 고마워-!$"
	@ しかい『きょうしゅく です!ｐ
	@ ゆうしょう おめでとう ございます!ｎ
	@ こんかいの きめてに なったのはｌ
	@ どんな ところ なので しょうか?ｐ
	@ おねえさん『あたしも §うもｎ
	@ とっても がんばりました!ｐ
	@ だけど きっと コンテストに でるまでにｎ
	@ きょうりょくして くれた ひとたちのｌ
	@ おかげだと おもいますっ!ｐ
	@ しかい『では この よろこびをｎ
	@ いちばん つたえたい かたに むけてｌ
	@ ひとこと メッセ-ジを おねがい します!ｐ
	@ おねえさん『お-いっ!ｐ
	@ §えさ-ん! みてる-っ!?ｎ
	@ あたしたち やったよ-っ!ｌ
	@ どうも ありがと-っ!

gTVPokemonContestLiveUpdates2Text02:: @ 0828C45B
	.string "사회자: 실례합니다!\p"
	.string "이번에는 정말 아까웠네요!\n"
	.string "한마디 부탁드립니다!\p"
	.string "아가씨: 정말 참담해요...\n"
	.string "저도 {STR_VAR_2}도 열심히 했는데\l"
	.string "응원해준 사람들에게\l"
	.string "뭐라고 해야 할지...\p"
	.string "사회자: 으-음 확실히 윤기가\n"
	.string "조금 부족한 느낌이긴 했죠-\p"
	.string "아가씨: ...{STR_VAR_3}씨 미안해\n"
	.string "다음엔 열심히 할 테니까...\l"
	.string "... ... 흑 ... 으아-앙!\p"
	.string "관객: 수군수군 수군수군\p"
	.string "사회자: 아아아아.... 저질렀다...\p"
	.string "그 그럼 이쯤에서\n"
	.string "끝낼게요! 여러분 안녕히 계세요-!$"
	@ しかい『きょうしゅく です!ｐ
	@ しかし こんかいは ざんねん でしたね!ｎ
	@ なにか コメントを おねがい します!ｐ
	@ おねえさん『ざんねんでした……ｎ
	@ あたしも §うも がんばったけどｌ
	@ おうえん してくれた ひとたちにｌ
	@ もうしわけ ないです……ｐ
	@ しかい『う-ん たしかに けづやがｎ
	@ ちょっと いまいちな かんじ ですね-ｐ
	@ おねえさん『……§えさん ごめんねｎ
	@ こんどは がんばるから……ｌ
	@ …… …… うっ …… うわ-ん!ｐ
	@ かんきゃく『ガヤガヤ ガヤガヤｐ
	@ しかい『あわぁぁ…… しまった……ｐ
	@ そっ それでは このあたりでｎ
	@ おわかれです! みなさん さようなら-!

gTVPokemonContestLiveUpdates2Text03:: @ 0828C662
	.string "사회자: 실례합니다!\p"
	.string "이번 콘테스트는 어떠셨나요?\p"
	.string "아가씨: 완전 대실패였어요...\n"
	.string "제 {STR_VAR_2}{K_EUNNEUN} 어째선지\l"
	.string "인기가 없는 것 같아서...\p"
	.string "사회자: 으-음 확실히 윤기가\n"
	.string "부족한 느낌이긴 했죠-\p"
	.string "아가씨: ...... ...... ...... ......\n"
	.string "... 흑 ... 으흑 으아-앙!\p"
	.string "관객: 수군수군 수군수군\p"
	.string "사회자: 아아아아.... 저질렀다...\p"
	.string "그 그럼 이쯤에서\n"
	.string "끝낼게요! 여러분 안녕히 계세요-!$"
	@ しかい『きょうしゅく です!ｐ
	@ こんかいの コンテスト いかが でした?ｐ
	@ おねえさん『ぜんぜん だめでした……ｎ
	@ あたしの §うは なんだかｌ
	@ にんきが なかった みたいで……ｐ
	@ しかい『う-ん たしかに けづやがｎ
	@ ちょっと いまいちな かんじ ですね-ｐ
	@ おねえさん『…… …… …… ……ｎ
	@ …… うっ …… うっ うわ-ん!ｐ
	@ かんきゃく『ガヤガヤ ガヤガヤｐ
	@ しかい『あわぁぁ…… しまった……ｐ
	@ そっ それでは このあたりでｎ
	@ おわかれです! みなさん さようなら-!
