LilycoveCity_ContestLobby_Text_InterviewRequest: @ 827EF15
	.string "으음? 당신 포켓몬 콘테스트에\n"
	.string "참가했었군요!\l"
	.string "그 포켓몬을 보면 안다구요!\p"
	.string "전 포켓몬 콘테스트에 대해\n"
	.string "기사를 쓰고 있는데\p"
	.string "괜찮다면 잠깐 감상을\n"
	.string "들려주실 수 있을까요?$"
	// おや? あなた ポケモンコンテストにｎ
	// さんかして いましたね!ｌ
	// その ポケモンを みれば わかりますよ!ｐ
	// わたくし ポケモンコンテストに ついてｎ
	// きじを かいて いるのですがｐ
	// できれば すこし かんそうをｎ
	// きかせて くれませんかね?

LilycoveCity_ContestLobby_Text_DescribeContest: @ 827EFE7
	.string "정말요!?\n"
	.string "감사합니다\p"
	.string "그럼 지금 했던 콘테스트에 대한 감상을\n"
	.string "한마디로 부탁할게요!$"
	// ほんとう ですか!ｎ
	// ありがとう ございますｐ
	// それでは いまの コンテストの かんそうをｎ
	// ひとことで おねがいします!

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX: @ 827F03E
	.string "으-음 그렇군요!\p"
	.string "어떤 콘테스트였는지\n"
	.string "잘 알 수 있는 한마디였습니다!\p"
	.string "...마지막으로\n"
	.string "살짝 물어보고 싶습니다만\p"
	.string "당신이 상상하는 {STR_VAR_2}{K_I}란\n"
	.string "대체 어떤 것인가요?$"
	// う-ん なるほど!ｐ
	// どんな コンテストだったかｎ
	// よくわかる ひとこと ですね!ｐ
	// ……さいごにｎ
	// ちょっと おききしたいの ですがｐ
	// あなたが イメ-ジする §うってｎ
	// いったい どんなもの ですかね?

LilycoveCity_ContestLobby_Text_ThatsAllForInterview: @ 827F0EC
	.string "그렇군요!\p"
	.string "그게 당신이 상상하는\n"
	.string "{STR_VAR_2}인 거군요!\p"
	.string "여러모로 참고가 됐습니다!\p"
	.string "콘테스트에 대한\n"
	.string "좋은 기사를 쓸 수 있을 것 같네요\p"
	.string "어쩌면 TV에서 이 내용을\n"
	.string "방송할지도 모르니까\l"
	.string "기대하고 있어주세요!$"
	// なるほど!ｐ
	// それが あなたの イメ-ジするｎ
	// §う なんですね!ｐ
	// いろいろ さんこうに なりました!ｐ
	// コンテストに ついてｎ
	// いい きじが かけそう ですよｐ
	// もしかしたら テレビで このことがｎ
	// ながれるかも しれないのでｌ
	// たのしみに してくださいね!

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe: @ 827F1EF
	.string "그렇습니까...\p"
	.string "다음에 재미있는 일이 생기면\n"
	.string "들려주세요$"
	// そうですか……ｐ
	// こんど おもしろいことが あればｎ
	// きかせて くださいね

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest: @ 827F23F
	.string "다음 포켓몬 콘테스트도\n"
	.string "기대하고 있겠습니다!$"
	// こんどの ポケモンコンテストもｎ
	// たのしみに してますよ!

gTVBravoTrainerText00:: @ 0827F275
	.string "이야-!\n"
	.string "“브라보 파트너”의 시간이야!\p"
	.string "오늘은 {STR_VAR_3} 클래스의\n"
	.string "{STR_VAR_2}{K_EULREUL} 자랑하는\l"
	.string "{STR_VAR_1}씨의 포켓몬!$"
	// イヤ-!ｎ
	// 『ブラボ- トレ-ナ-』の じかんだ!ｐ
	// きょうは §え3クラスのｎ
	// §う2を ほこるｌ
	// §い1さんの ポケモン!

gTVBravoTrainerText01:: @ 0827F304
	.string "{STR_VAR_1} “{STR_VAR_2}”의\n"
	.string "소개 시간이야-!\p"
	.string "“{STR_VAR_2}”인가...\p"
	.string "이미 닉네임부터\n"
	.string "{STR_VAR_3}{K_IGA} 드러나는걸!$"
	// §い の 「§う」のｎ
	// しょうかいだ-!ｐ
	// 「§う」か……ｐ
	// もう ニックネ-ム からしてｎ
	// §えが にじみ でているぜ!
	
gTVBravoTrainerText02:: @ 0827F361
	.string "그런데 그 {STR_VAR_1}씨가\n"
	.string "포켓몬 콘테스트에 참가했을 때\p"
	.string "자신의 포켓몬에 대해서\n"
	.string "열정적으로 얘기해 줬어!$"
	// さ-て この §いさんがｎ
	// ポケモンコンテストに さんか したときｐ
	// じぶんの ポケモンに ついてｎ
	// あつく はなして くれたぞ!

gTVBravoTrainerText03:: @ 0827F3E4
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물어보니\l"
	.string "엄청 기쁜 듯이\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었지!\p"
	.string "뭐 콘테스트에서는\n" 
	.string "{STR_VAR_3}번이었으니까 말이지-!\p"
	.string "지금의 {STR_VAR_1}씨에게\n"
	.string "정말 딱 맞는 대사였다고 생각해!$"
	// コンテストを したあとのｎ
	// かんそうを きくとｌ
	// すごく うれしそうにｐ
	// 「§う」ってｎ
	// こたえて くれたぞ!ｐ
	// まあ コンテストではｎ
	// §えばん でした からね-!ｐ
	// いまの §いさんにはｎ
	// ぴったりの セリフだよ まったく!

gTVBravoTrainerText04:: @ 0827F49F
	.string "콘테스트를 한 뒤의\n"
	.string "감상을 물어보니\l"
	.string "미묘하게 분해하면서\p"
	.string "“{STR_VAR_2}”{K_I}라고\n"
	.string "대답해 주었지!\p"
	.string "뭐 콘테스트에선\n"
	.string "{STR_VAR_3}번이었으니까 말이지-!\p"
	.string "이 대사에 {STR_VAR_1}씨의\n"
	.string "분함이 보일 듯 말 듯하네-$"
	// コンテストを したあとのｎ
	// かんそうを きくとｌ
	// びみょうに くやしがり ながらｐ
	// 「§う」ってｎ
	// こたえて くれたぞ!ｐ
	// まあ コンテストではｎ
	// §えばん でした からね-!ｐ
	// この ことばに §いさんのｎ
	// くやしさが みえかくれ するね-

gTVBravoTrainerText05:: @ 0827F565
	.string "그런데 {STR_VAR_1}씨가 목표로 하는\n"
	.string "{STR_VAR_2}{K_EUNNEUN} 대체 뭘까?\l"
	.string "들어보고 싶은걸-!\p"
	.string "물론 물어봤다고!\p"
	.string "이 한마디에 그\n"
	.string "모든 것이 담겨있지!\p"
	.string "바로 “{STR_VAR_3}!”\p"
	.string "그것이야말로 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}의 모든 것인 거야!$"
	// ところで §いさんの めざしてるｎ
	// §うって いったい なんだろう?ｌ
	// きいて みたいね-!ｐ
	// もちろん きいて きました!ｐ
	// それは つぎの ひとことにｎ
	// すべてが つまって います!ｐ
	// それは 「§え!」ｐ
	// それこそ §いさんのｎ
	// §うの すべて なんです!

gTVBravoTrainerText06:: @ 0827F624
	.string "마지막으로 {STR_VAR_1}{K_IGA}\n"
	.string "썼던 {STR_VAR_2}도\l"
	.string "모두 “{STR_VAR_3}”인 거래!$"
	// さいごに §いがｎ
	// つかった §うもｌ
	// すべて 「§え」 なんです!

gTVBravoTrainerText07:: @ 0827F65C
	.string "브라보! {STR_VAR_1}!\n"
	.string "브라보!! {STR_VAR_2}!\p"
	.string "다음번 {STR_VAR_1}씨의 활약에\n"
	.string "기대가 되는걸-!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자구-!$"
	// ブラボ-! §いｎ
	// ブラボ-!! §うｐ
	// こんごの §いさんの かつやくにｎ
	// きたい したいね-!ｐ
	// それじゃあ また じかいのｎ
	// ほうそうで あいましょ-!

gTVBravoTrainerText08:: @ 0827F6E6
	.string "{STR_VAR_1}{K_EULREUL} 소개할 시간이야-!$"
	// §い の しょうかいだ-!

BattleFrontier_BattleTowerLobby_Text_InterviewRequest:: @ 0827F704
	.string "아! 지금 막 배틀이 끝난\n"
	.string "트레이너분이시군요!\p"
	.string "저는 지금 여러 트레이너의\n"
	.string "이야기를 들으면서 돌아다니고 있는데\p"
	.string "배틀이 끝난 감상을\n"
	.string "조금만 들려주실 수 있을까요?$"
	// あ! いま たたかっていたｎ
	// トレ-ナ-の かたですね!ｐ
	// わたし いま いろんな トレ-ナ-のｎ
	// はなしを きいて まわってるんだけどｐ
	// たたかいおわった かんそうをｎ
	// すこしだけ きかせて もらえませんか?

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut:: @ 0827F7BA
	.string "정말인가요!?\n"
	.string "감사합니다!\l"
	.string "으음 그럼...\p"
	.string "이번 배틀타워의\n"
	.string "대전은 어땠나요?\p"
	.string "만족하셨습니까!?\n"
	.string "아니면 불만이신가요!?$"
	// ほんと!?ｎ
	// ありがとう!ｌ
	// えっと それじゃあねぇ……ｐ
	// こんかいの バトルタワ-のｎ
	// たいせんは どうでしたかｐ
	// まんぞく でしたか!ｎ
	// それとも ふまん ですか!?

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou:: @ 0827F84C
	.string "아아!\n"
	.string "죄송합니다\p"
	.string "그럼 다음에 또 배틀타워에 온다면\n"
	.string "들려주세요$"
	// あぁ!ｎ
	// ごめんなさいｐ
	// じゃあ またこんど バトルタワ-に きたらｎ
	// きかせて くださいね

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle:: @ 0827F8AE
	.string "역시나!\p"
	.string "그 만족한 얼굴을 보면\n"
	.string "얼마나 좋은 시합이었는지가\l"
	.string "보인단 말이죠!$"
	// さっすが!ｐ
	// その まんぞくした かおを みればｎ
	// どんなに いいしあいだったかｌ
	// わかりますよ!

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned:: @ 0827F921
	.string "으-음 그렇습니까...\p"
	.string "생각한 것처럼 승부하는 건\n"
	.string "꽤나 어려운 일이니 말이죠...$"
	// う-ん そうですか……ｐ
	// おもいどおりに しょうぶを するのってｎ
	// なかなか むずかしい ですからね……

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle:: @ 0827F97A
	.string "아앗 그리고\n"
	.string "하나만 더 괜찮을까요?\p"
	.string "이번 배틀의 감상을\n"
	.string "한마디로 딱 들려주세요!$"
	// あぁっ あとｎ
	// もう ひとつだけ いいですか?ｐ
	// この たたかいの かんそうをｎ
	// ひとことで ビシッと きかせてください!

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine:: @ 0827F9FD
	.string "멋있어요-!!\p"
	.string "좋은 마무리 대사네요\n"
	.string "다음 배틀도 기대하고 있겠습니다\p"
	.string "그럼 다음에 또 봐요!$"
	// かっこい-!!ｐ
	// いい きめゼリフ ですねｎ
	// つぎの たたかいも きたい してますよｐ
	// それでは また!

BattleFrontier_BattleTowerLobby_Text_SilentType:: @ 0827FA6F
	.string "그렇습니까...\p"
	.string "하지만 아무 할 말이 없는 것\n"
	.string "또한 멋있네요!\p"
	.string "그럼 다음 기회에\n"
	.string "감상을 들려주세요!$"
	// そうですか……ｐ
	// でも なにも いわないのもｎ
	// また かっこいいですね!ｐ
	// それじゃあ またの きかいにｎ
	// かんそうを きかせて ください!

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle:: @ 0827FAF3
	.string "다음 배틀도\n"
	.string "기대하고 있다구요$"
	// つぎの たたかいもｎ
	// きたい してますよ

gTVBravoTrainerBattleTowerText00:: @ 0827FB20
	.string "이야-!\n"
	.string "“브라보 파트너”의 시간이야!\p"
	.string "오늘은 배틀타워에 도전했던\n"
	.string "{STR_VAR_1}씨를 소개할게-!\p"
	.string "{STR_VAR_1}씨는 {STR_VAR_2}{K_EULREUL}\n"
	.string "사용한 배틀을 해서$"
	// イヤ-!ｎ
	// 『ブラボ- トレ-ナ-』の じかんだ!ｐ
	// きょうは バトルタワ-に ちょうせんしたｎ
	// §いさんの しょうかいだ-!ｐ
	// §いさんは §うをｎ
	// つかった たたかいをして

gTVBravoTrainerBattleTowerText01:: @ 0827FBB3
	.string "무려 {STR_VAR_1}의 방에서\n"
	.string "{STR_VAR_2}연승이라는\l"
	.string "기록을 세웠다고!$"
	// なんと §いの へやでｎ
	// §うれんしょう というｌ
	// きろくを うちたてたぞ!

gTVBravoTrainerBattleTowerText02:: @ 0827FC04
	.string "아깝게도 {STR_VAR_2}번째로 싸웠던\n"
	.string "{STR_VAR_1}씨에게 져버렸지만 말야\l"
	.string "으-음! 안타까워\p"
	.string "이렇게 빨리 {STR_VAR_1}씨와\n"
	.string "마주친 건 운이 없었다고밖에 할 수 없지\p"
	.string "자 그럼 그 {STR_VAR_1}씨와의\n"
	.string "승부한 감상을 물어봤는데$"
	// おしくも §うにんめで たたかったｎ
	// §いさんに まけて しまいましたｌ
	// う-ん! ざんねんだねぇｐ
	// でも こんなはじめに §いさんにｎ
	// あたるとは うんがないとしか いえないよｐ
	// さて その §いさんとのｎ
	// しょうぶの かんそうを きいたところ

gTVBravoTrainerBattleTowerText03:: @ 0827FCD1
	.string "마지막에는 {STR_VAR_1}씨의\n"
	.string "{STR_VAR_2}{K_EULREUL} 훌륭히 쓰러뜨려서\l"
	.string "승리했다고\p"
	.string "이야 {STR_VAR_1}씨를 이기다니\n"
	.string "굉장하다는 말밖에 안 나와 참\p"
	.string "자 그럼 그 승리를 붙잡은\n"
	.string "순간의 감상을 물어봤는데$"
	// さいごには §いさんのｎ
	// §うを みごとに たおしてｌ
	// しょうり したんですねぇｐ
	// いや §いさんに かつなんてｎ
	// すごいとしか いいようがないよ まったくｐ
	// さて そのしょうりを つかんだｎ
	// しゅんかんの かんそうを きいたところ

gTVBravoTrainerBattleTowerText04:: @ 0827FD91
	.string "하지만 마지막으로 등장한\n"
	.string "{STR_VAR_1}씨의 {STR_VAR_2}에게\l"
	.string "결국 져버리고 말았지\p"
	.string "뭐 “{STR_VAR_1}의 {STR_VAR_2}” 하면\n"
	.string "유명한 콤비니까\p"
	.string "...자 그럼 그 유명인과\n"
	.string "승부한 감상을 물어봤는데$"
	// しかし さいごに とうじょうしたｎ
	// §いさんの §うにｌ
	// ついに まけて しまったんですねぇｐ
	// まあ 「§いの §う」ｎ
	// といえば ゆうめいな コンビ ですからねｐ
	// ……さて その ゆうめいじんとのｎ
	// しょうぶの かんそうを きいたところ

gTVBravoTrainerBattleTowerText05:: @ 0827FE93
	.string "“만족했다!!”\p"
	.string "라고 시원하게 답해줬어\n"
	.string "역시!\p"
	.string "만족스러운 배틀이 가능하다니\n"
	.string "정말로 굉장하지 참!\p"
	.string "그 만족감은 이 한마디를\n"
	.string "들었을 때 전부 이해했어$"
	// まんぞく した!!ｐ
	// と すがすがしく こたえてくれたよｎ
	// さすがだぜ!ｐ
	// まんぞくいく たたかいが できるなんてｎ
	// ほんと すごいよねぇ まったく!ｐ
	// その まんぞくかんは つぎの ひとことをｎ
	// きいたとき すべて わかったよ

gTVBravoTrainerBattleTowerText06:: @ 0827FF89
	.string "불만이었다...\p"
	.string "라고 미묘하게 우울해하면서\n"
	.string "대답해줬어\p"
	.string "...뭐 만족스러운 배틀은\n"
	.string "자주 겪을 수 있는 게 아니니까-\p"
	.string "그때의 분함은\n"
	.string "이 한마디가 잘 드러내고 있어$"
	// ふまんだった……ｐ
	// と びみょうに おちこみながらｎ
	// こたえて くれたよｐ
	// ……まあ まんぞくいく たたかいってｎ
	// なかなかできる もんじゃないからね-ｐ
	// そのときの くやしさはｎ
	// つぎの ひとことが よくあらわしてるよ

gTVBravoTrainerBattleTowerText07:: @ 0828009C
	.string "없음$"

gTVBravoTrainerBattleTowerText08:: @ 082800A1
	.string "없음$"

gTVBravoTrainerBattleTowerText09:: @ 082800A6
	.string "없음$"

gTVBravoTrainerBattleTowerText10:: @ 082800AB
	.string "없음$"

gTVBravoTrainerBattleTowerText11:: @ 082800B0
	.string "그 말은\n"
	.string "“{STR_VAR_1}!”$"

gTVBravoTrainerBattleTowerText12:: @ 082800B6
	.string "“{STR_VAR_1}!”\n"
	.string "으-음 좋은 말인걸!!\p"
	.string "{STR_VAR_2}씨의 기쁨을\n"
	.string "이 말이 잘 드러내고 있어!\p"
	.string "확실히 {STR_VAR_3}씨와의 배틀은\n"
	.string "그야말로 “{STR_VAR_1}”인\l"
	.string "느낌의 배틀이었지!$"
	// 「§い!」ｎ
	// う-ん  いい ことばだねぇ!!ｐ
	// §うさんの うれしさをｎ
	// このことばが よく あらわしているよ!ｐ
	// たしかに §えさんとの たたかいはｎ
	// まさに 「§い」 というｌ
	// かんじ だったからねぇ!

gTVBravoTrainerBattleTowerText13:: @ 0828013D
	.string "“{STR_VAR_1}!”\n"
	.string "과연 그렇구나\p"
	.string "확실히 {STR_VAR_3}씨와의 배틀은\n"
	.string "“{STR_VAR_1}”라고밖에 할 수 없는\l"
	.string "배틀이었으니까\p"
	.string "{STR_VAR_2}씨의 분함이\n"
	.string "잘 전해져오네! 크-!$"
	// 「§い!」ｎ
	// なるほどねぇｐ
	// たしかに §えさんとの たたかいはｎ
	// 「§い」 としか いいようがないｌ
	// たたかい でしたからねぇｐ
	// §うさんの くやしさがｎ
	// よく つたわってくるよ! く-!

gTVBravoTrainerBattleTowerText14:: @ 082801E6
	.string "브라보! {STR_VAR_1}!\n"
	.string "브라보!! {STR_VAR_2}!\p"
	.string "다음번 {STR_VAR_1}씨의 활약에\n"
	.string "기대가 되는걸!\p"
	.string "그럼 또 다음\n"
	.string "방송에서 만나자구-!$"
	// ブラボ-! §いｎ
	// ブラボ-!! §うｐ
	// こんごの §いさんの かつやくにｎ
	// きたい したいねぇ!ｐ
	// それじゃあ また じかいのｎ
	// ほうそうで あいましょ-!

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName: @ 08280270
	.string "와아!\p"
	.string "너 그 {STR_VAR_1}{K_EULREUL} 무척\n"
	.string "소중히 여기는 모양이구나!\p"
	.string "{STR_VAR_2}{K_I}라고 하는구나...\p"
	.string "맞다!\p"
	.string "지금 나 TV 취재로\n"
	.string "포켓몬에 대한 설문을 하고 있는데\p"
	.string "잠깐 질문에\n"
	.string "답해줄 수 있을까?$"
	// わあ!ｐ
	// きみ その §いを とてもｎ
	// だいじに している みたいね!ｐ
	// §う って いうんだ……ｐ
	// そうだ!ｐ
	// いま わたし テレビの しゅざいでｎ
	// ポケモンの アンケ-トを してるんだけどｐ
	// すこしだけ しつもんにｎ
	// こたえて くれないかな?

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers: @ 0828034F
	.string "고마워!\p"
	.string "그럼 물을게\n"
	.string "딱 한마디로 대답해줘!$"
	// ありがとう!ｐ
	// じゃあ きくねｎ
	// ずばり ひとことで こたえて!

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon: @ 08280393
	.string "네가 {STR_VAR_1}하고\n"
	.string "만났을 때\p"
	.string "무슨 느낌이었어?\n"
	.string "어떻게 생각했는지 알려줘!$"
	// きみが §いとｎ
	// であったときってｐ
	// なにか かんじた?ｎ
	// どう おもったか おしえて!

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike: @ 082803EF
	.string "네가 귀여워하는 {STR_VAR_1}!\p"
	.string "만약 무엇인가 좋아하는 것에 비유하자면\n"
	.string "뭐라고 생각해?$"
	// きみの かわいがってる §い!ｐ
	// もし なにか すきなものに たとえるとｎ
	// すれば なんだと おもう?

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon: @ 08280454
	.string "네가 귀여워하는 {STR_VAR_1}!\n"
	.string "넌 {STR_VAR_1}의 어디에\n"
	.string "이끌린 거야?$"
	// きみの かわいがってる §い!ｐ
	// きみは §いの どこにｎ
	// ひかれたの?

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou: @ 082804AC
	.string "으-음 그렇구나\p"
	.string "그럼 다음은 살짝\n"
	.string "어려운 질문을 할게!\p"
	.string "그럼...\p"
	.string "네게 있어 포켓몬이란\n"
	.string "한마디로 뭐라고 생각해?$"
	// う-ん なるほどねｐ
	// じゃあ つぎは ちょっとｎ
	// むずかしい しつもんを するね!ｐ
	// じゃあ……ｐ
	// きみに とって ポケモンってｎ
	// ひとことで いうと なんだと おもう?

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview: @ 08280523
	.string "그렇구나-!\p"
	.string "흐음흐음...\p"
	.string "아!\n"
	.string "협력해줘서 고마워!\p"
	.string "여러 얘기를 들어서\n"
	.string "재밌었어\p"
	.string "이 얘기 어쩌면 TV에\n"
	.string "나올지도 모르니까 기대해줘\p"
	.string "그럼 이만\n"
	.string "바이바이!$"
	// なるほど-!ｐ
	// ふむふむ……ｐ
	// あ!ｎ
	// きょうりょく ありがとうね!ｐ
	// いろいろ はなしが きけてｎ
	// おもしろ かったよｐ
	// このはなし もしかしたら テレビでｎ
	// ながすかも しれないから きたい しててねｐ
	// じゃあねｎ
	// バイバイ!

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe: @ 082805E2
	.string "그렇구나...\p"
	.string "그럼 또 포켓몬에 대해서\n"
	.string "얘기하고 싶어지면 언제든지 와줘$"
	// そっか……ｐ
	// じゃあ また ポケモンの ことをｎ
	// はなしたく なったら いつでも きてね

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews: @ 0828062E
	.string "여기에 있으면 여러 포켓몬의\n"
	.string "이야기를 들을 수 있어서 재밌어$"
	// ここに いると いろんな ポケモンのｎ
	// はなしが きけるから おもしろいわ

SlateportCity_PokemonFanClub_Text_InterviewRequest: @ 08280674
	.string "너 그 {STR_VAR_1}{K_WAGWA}\n"
	.string "무척 사이가 좋은 모양이네\p"
	.string "맞다! 지금 나\n"
	.string "TV 취재로\p"
	.string "여러 포켓몬의 이야기를\n"
	.string "들으면서 돌아다니고 있는데\p"
	.string "괜찮다면 네 {STR_VAR_1}의\n"
	.string "이야기를 들려줄 수 있을까?$"
	// きみの その §いとｎ
	// とても なかが よさそうねｐ
	// そうだ! いま わたしｎ
	// テレビの しゅざいでｐ
	// いろんな ポケモンの はなしをｎ
	// きいて まわってるんだけどｐ
	// よかったら きみの §いのｎ
	// はなしを きかせて くれないかな?

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon: @ 0828073B
	.string "와아!\n"
	.string "고마워!\p"
	.string "그럼 {STR_VAR_1}의 이야기를\n"
	.string "아무거나 좋으니까 들려줘!$"
	// わあ!ｎ
	// ありがとう!ｐ
	// じゃあ §いの はなしｎ
	// なんでも いいので きかせてよ!

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2: @ 08280789
	.string "헤에-...\n"
	.string "재밌는 이야기였어!\p"
	.string "넌 정말로 {STR_VAR_1}{K_WAGWA}\n"
	.string "사이가 좋구나\p"
	.string "으-음 왠지 이 이야기로\n"
	.string "좋은 방송이 만들어질 것 같아!\p"
	.string "분명 재미있는 방송이\n"
	.string "될 테니까 기대하고 있어줘\p"
	.string "그럼 고마웠어\n"
	.string "바이바이!$"
	// へ-……ｎ
	// おもしろい はなし だね!ｐ
	// きみは ほんとうに §いとｎ
	// なかが いいんだねｐ
	// う-ん なんか このはなしでｎ
	// いい ばんぐみが できそうな よかん!ｐ
	// きっと おもしろい ばんぐみにｎ
	// するから たのしみに まっててねｐ
	// じゃあ ありがとうねｎ
	// バイバイ!

gTVFanClubOpinionsText00:: @ 08280886
	.string "“우리들!\n"
	.string "포켓몬 애호가클럽!”\p"
	.string "네 시작했습니다!\p"
	.string "이 방송은 여러분의\n"
	.string "의견을 바로 제가\l"
	.string "대신 외쳐드리는!\l"
	.string "굉장한 방송이죠!!\p"
	.string "자 오늘은 포켓몬 애호가클럽에\n"
	.string "가서 여러 이야기를 들어본\l"
	.string "리포터로부터 들어온 정보입니다!\p"
	.string "자 그럼 오늘의\n"
	.string "포켓몬 애호가는?\p"
	.string "음-...\p"
	.string "{STR_VAR_1}씨다-!!\p"
	.string "그럼 자신의 포켓몬\p"
	.string "{STR_VAR_2} “{STR_VAR_3}”에\n"
	.string "대한 뜨거운 기분을\p"
	.string "바로 제가 대신 TV를\n"
	.string "통해 외쳐드리겠습니다!\p"
	.string "우-!!\p"
	.string "렛츠 샤우트!!$"
	// 『ぼくたち!ｎ
	// ポケモン だいすきクラブ!』ｐ
	// はい はじまりました!ｐ
	// このばんぐみは みなさんのｎ
	// いけんを このわたしがｌ
	// かわりに さけんで しまおう!ｌ
	// という すごい ばんぐみ!!ｐ
	// さて きょうは ポケモンだいすきクラブ にｎ
	// いって いろんな はなしを きいてきたｌ
	// リポ-タ-からの じょうほうだ!ｐ
	// さて きょうのｎ
	// ポケモンだいすき にんげんは?ｐ
	// ん-……ｐ
	// §いさんだ-!!ｐ
	// それでは ごじぶんの ポケモンｐ
	// §うの 「§え」にｎ
	// ついての あつい きもちをｐ
	// かわりに この わたくしが テレビにｎ
	// むかって さけんで あげましょう!ｐ
	// う-!!ｐ
	// レッツ シャウト!!!

gTVFanClubOpinionsText01:: @ 08280A44
	.string "자 그럼 {STR_VAR_1}씨가 처음으로\n"
	.string "{STR_VAR_2}{K_WAGWA} 만났을 때 직관적으로\l"
	.string "생각한 것은...\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 좋은 외침입니다!\p"
	.string "마치 그때의 추억이\n"
	.string "되살아나는 듯하군요-!!$"
	// さて §いさんが はじめてｎ
	// §うと あったとき ちょっかんてきにｌ
	// おもった ことは……ｌ
	// ……ｐ
	// 「§え!!」ｐ
	// ん- いい さけびだ!ｐ
	// まるで そのときの おもいでがｎ
	// よみがえる ようだ-!!

gTVFanClubOpinionsText02:: @ 08280AFC
	.string "자 그럼 {STR_VAR_1}씨가 매우 좋아하는\n"
	.string "{STR_VAR_2}{K_EULREUL} 뭔가에 비유한다면\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "음- 굉장한 발상이군요!!\p"
	.string "격렬한 {STR_VAR_2}{K_EULREUL} 향한 생각이\n"
	.string "느껴지네요-!$"
	// さて §いさんの だいすきなｎ
	// §うを なにかに たとえると したらｌ
	// ……ｐ
	// 「§え!!」ｐ
	// ん- すごい はっそうだ!!ｐ
	// はげしい §うへの おもいこみがｎ
	// かんじられるね-!

gTVFanClubOpinionsText03:: @ 08280BC4
	.string "자 그럼 {STR_VAR_1}씨가 {STR_VAR_2}에게\n"
	.string "이끌린 이유는...\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "오-!! 엄청난 의견이군요-!\p"
	.string "{STR_VAR_2}{K_EULREUL} 얼마나 좋아하는지\n"
	.string "팍팍 전해져 옵니다-!$"
	// さて §いさんが §うにｎ
	// ひかれた りゆうは……ｌ
	// ……ｐ
	// 「§え!!」ｐ
	// お-!! すんばらしい いけんだ-!ｐ
	// §うを どんなに すきかｎ
	// ビンビン つたわって くるね-!

gTVFanClubOpinionsText04:: @ 08280C7A
	.string "음-? 아직 더 남아있네요-\n"
	.string "불러봅시다!\p"
	.string "으-음...\p"
	.string "{STR_VAR_1}씨에게 있어 포켓몬을\n"
	.string "한마디로 비유하자면 그것은!\l"
	.string "......\p"
	.string "“{STR_VAR_3}!!”\p"
	.string "브라보!!\p"
	.string "몇 번이고 외치고 싶어지는 말이군요-!\p"
	.string "그럼 좋은 외침도 들었으니\n"
	.string "다음에 또 봅시다!\p"
	.string "마지막으로 한 번 더\n"
	.string "다 같이 외쳐보죠!\p"
	.string "“{STR_VAR_3}!!”$"
	// ん-? まだ つづきが ありますね-ｎ
	// よんで みましょう!ｐ
	// え-と……ｐ
	// §いさんに とって ポケモンをｎ
	// ひとことで たとえると すれば それは!ｌ
	// ……ｐ
	// 「§え!!」ｐ
	// ブラボ-!!ｐ
	// いままでの なかで いちばんｎ
	// いい さけび だった-!ｐ
	// 「§え!!」ｐ
	// なんども さけびたくなる ことばだね-!ｐ
	// それでは いいさけびと であった ところでｎ
	// また じかい おあいしましょう!ｐ
	// さいごに もういちどｎ
	// みんなで さけびましょう!ｐ
	// 「§え!!」

gTVFanClubText00:: @ 08280DEE
	.string "“우리들!\n"
	.string "포켓몬 애호가클럽!”\p"
	.string "네 시작했습니다!\p"
	.string "그럼 오늘은\n"
	.string "포켓몬 설문 코너!\p"
	.string "수많은 포켓몬과 트레이너의\n"
	.string "사연 중에서\p"
	.string "오늘은 어떤 이야기가\n"
	.string "튀어나올까요!?\l"
	.string "자 그럼 오늘의 사연은?\p"
	.string "음-...\p"
	.string "이거다!\p"
	.string "그럼 편지의 내용을 소개하겠습니다!!\n"
	.string "{STR_VAR_2}에게 보내는\n"
	.string "{STR_VAR_1}씨의 편지네요-\p"
	.string "그럼 얼마나 {STR_VAR_2}{K_EULREUL} 향한\n"
	.string "뜨거운 마음이 담겨있는지\l"
	.string "읽어보도록 합시다!\l"
	.string "음 그럼-...$"
	// 『ぼくたち!ｎ
	// ポケモン だいすきクラブ!』ｐ
	// はい はじまりました!ｐ
	// じゃあ きょうは ポケモンアンケ-トのｎ
	// コ-ナ-から!ｐ
	// かずある ポケモンと トレ-ナ-のｎ
	// はなしの なかからｐ
	// きょうは どんな はなしがｎ
	// とびだして くるのでしょうか!?ｌ
	// さて きょうの はなしは?ｐ
	// ん-……ｐ
	// これだ!ｐ
	// では てがみの しょうかい から!!ｐ
	// §うの ことに ついてｎ
	// §いさん からの おてがみだ-ｐ
	// では どれだけ §うへのｎ
	// あつい いけんが かいてあるかｌ
	// よませて もらいましょう!ｌ
	// え-と……

gTVFanClubText01:: @ 08280F69
	.string "오-!!\n"
	.string "정말 굉장한 편지네요!$"
	// お-!!ｎ
	// なんて すばらしい てがみなんだ!!

gTVFanClubText02:: @ 08280F88
	.string "마음에 들었으니 다시 한 번!$"
	// きにいったから もういちど!

gTVFanClubText03:: @ 08280FA9
	.string "좋은 편지는\n"
	.string "몇 번이고 읽어도 좋네요-!!$"
	// いい てがみはｎ
	// なんど きいても いいね-!!

gTVFanClubText04:: @ 08280FD5
	.string "“{STR_VAR_3}”{K_I}라는 말\n"
	.string "덕분에 두근 하고 마음에 전해지는\l"
	.string "좋은 편지군요-!!$"
	// 「§え」 っていう ことばのｎ
	// おかげで グッと こころに つたわってくるｌ
	// いい てがみに なっているね-!!

gTVFanClubText05:: @ 08281040
	.string "특히 “{STR_VAR_3}” 여기 이 부분!\p"
	.string "“{STR_VAR_3}”{K_I}라고 하는 부분이\n"
	.string "마음에 든다구요-!$"
	// とくに「§え」って ところ!ｐ
	// 「§え」っていう ところがｎ
	// きにいったぞ-!

gTVFanClubText06:: @ 08281073
	.string "그런데 딱히 상관은 없지만\n"
	.string "“{STR_VAR_3}”{K_EUNNEUN} 참 좋은 말이죠\p"
	.string "실은 저도 “{STR_VAR_3}”{K_I}라고\n"
	.string "자주 말하고 다니거든요$"
	// ところで あんまり かんけい ないけどｎ
	// 「§え」って いいことば だよねｐ
	// じつは おれも 「§え」ってｎ
	// ことば さいきん よく つかうんだよね

gTVFanClubText07:: @ 082810E7
	.string "이 편지 저는\n"
	.string "{STR_VAR_3}점을 주고 싶네요-!\p"
	.string "다음은 좀 더 좋은 편지를\n"
	.string "기대하고 있을게요! {STR_VAR_1}씨!\p"
	.string "어이쿠 이제 시간이 다 됐군요!\n"
	.string "그럼 또 모두\l"
	.string "다음 방송에서 봅시다!!$"
	// このてがみ じぶんてきにはｎ
	// §えてん ていう かんじかな-!ｐ
	// つぎは もっと いい てがみをｎ
	// きたい してるよ! §いさん!!ｐ
	// おっと もう こんなじかんだ!ｎ
	// それでは また じかいｌ
	// みなさま おあい しましょう!!

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest: @ 082811A0
	.string "Oh?\n"
	.string "Do you perhaps like POKéMON?\p"
	.string "I'm on assignment with the TV network.\p"
	.string "I'm gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don't mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort: @ 0828126D
	.string "I'm gathering stories on POKéMON and\n"
	.string "TRAINERS that occurred recently.\p"
	.string "If you don't mind, could you tell me\n"
	.string "something about yourself?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon: @ 082812F2
	.string "Oh, you will?\n"
	.string "Thank you!\p"
	.string "Then, please, tell me anything of\n"
	.string "interest that you experienced recently\l"
	.string "involving POKéMON.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory: @ 08281367
	.string "Oh, I see…\p"
	.string "Well, if you do have an interesting\n"
	.string "story to tell, please let me know.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview: @ 082813B9
	.string "Oh, what an uplifting story!\p"
	.string "I'll be sure to get your story told\n"
	.string "on television.\p"
	.string "It should be aired sometime, I think,\n"
	.string "so please look forward to it.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory: @ 0828144D
	.string "Hmmm…\n"
	.string "I've got a good story for a TV program.\p"
	.string "I'd better write it up in a hurry!$"

gTVRecentHappeningsText00:: @ 0828149E
	.string "Hello, it's time for RECENT HAPPENINGS.\p"
	.string "For POKéMON TRAINERS, every day\n"
	.string "is a storybook tale.\p"
	.string "What we want to do is to introduce you\n"
	.string "to some of these POKéMON tales.\p"
	.string "Today, we bring you the story\n"
	.string "of the TRAINER {STR_VAR_1}.\p"
	.string "What did {STR_VAR_1} experience recently?\n"
	.string "Let's find out.\p"
	.string "Let's see…$"

gTVRecentHappeningsText01:: @ 082815AF
	.string "Wasn't that enlightening?\p"
	.string "The story gives you a clear idea of what\n"
	.string "{STR_VAR_1} has experienced recently.\l"
	.string "It's as if we were there as witnesses!$"

gTVRecentHappeningsText02:: @ 08281636
	.string "“{STR_VAR_3}.” That\n"
	.string "accents the tale and gives it depth.$"

gTVRecentHappeningsText03:: @ 08281666
	.string "“{STR_VAR_3}.”\n"
	.string "That gives the tale a sense of place.\l"
	.string "It lets us envision the tale's setting.$"

gTVRecentHappeningsText04:: @ 082816BA
	.string "The “{STR_VAR_3}”\n"
	.string "section of the tale is very expressive.$"

gTVRecentHappeningsText05:: @ 082816EB
	.string "{STR_VAR_1} has recounted a wonderful\n"
	.string "tale involving POKéMON.\p"
	.string "And now {STR_VAR_1}'s tale is indelibly\n"
	.string "etched into your soul, too.\p"
	.string "That's it for today.\n"
	.string "Please tune in next time.$"

gTVMassOutbreakText00:: @ 0828178A
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We've just received word of a very\n"
	.string "rare occurrence.\p"
	.string "There have been reports of a mass\n"
	.string "outbreak of {STR_VAR_2} in the vicinity\l"
	.string "of {STR_VAR_1}.\p"
	.string "{STR_VAR_2}, as you're probably aware,\n"
	.string "is known as a POKéMON that's rare\l"
	.string "and hard to find.\p"
	.string "It sounds like a rare opportunity to\n"
	.string "see the mystifying outbreak of\l"
	.string "{STR_VAR_2} in the wild.\p"
	.string "That's the news on POKéMON NEWS.$"

gTV3CheersForPokeblocksText00:: @ 082818F4
	.string "MC: We hope you're in good cheer,\n"
	.string "“3 CHEERS FOR {POKEBLOCK}S” is here!\p"
	.string "Today, we examine the {POKEBLOCK} blended\n"
	.string "by {STR_VAR_1} and associates.\p"
	.string "Without any delay, let me feed it\n"
	.string "to my gourmet POKéMON GULPIN.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01:: @ 082819C7
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: And the verdict is very {STR_VAR_1}!\n"
	.string "GULPIN says it tastes “{STR_VAR_2}!”\p"
	.string "Thank you so much, {STR_VAR_3}!$"

gTV3CheersForPokeblocksText02:: @ 08281A2F
	.string "{STR_VAR_1}'s blending performance\n"
	.string "left something to be desired.\p"
	.string "If this TRAINER could blend better,\n"
	.string "the {POKEBLOCK} would be much tastier.$"

gTV3CheersForPokeblocksText03:: @ 08281AAC
	.string "GULPIN: Gubi! Gubii!\p"
	.string "MC: Hmm… It's too {STR_VAR_1}.\n"
	.string "GULPIN says it tastes “{STR_VAR_2}!”\p"
	.string "It looks like {STR_VAR_3}'s errors\n"
	.string "hurt the blending quality…$"

gTV3CheersForPokeblocksText04:: @ 08281B28
	.string "It's too bad that {STR_VAR_1}'s\n"
	.string "leading effort went to waste.\p"
	.string "Let's hope {STR_VAR_2} can turn in\n"
	.string "a better showing next time!$"

gTV3CheersForPokeblocksText05:: @ 08281B93
	.string "Tune in next time!\n"
	.string "Our slogan is “3 CHEERS FOR {POKEBLOCK}S!”$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer:: @ 8281BCB
	.string "Hi, there!\p"
	.string "I'm a big fan of {STR_VAR_1}.\n"
	.string "What's your opinion of {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink:: @ 8281C06
	.string "I see, I see. That's what you think\n"
	.string "about the TRAINER.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer:: @ 8281C3D
	.string "Have you completely forgotten\n"
	.string "about {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2:: @ 8281C65
	.string "I'm a big fan of {STR_VAR_1}.\n"
	.string "What's your opinion of {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer:: @ 8281C95
	.string "How strong would you rate {STR_VAR_1}\n"
	.string "on a scale of one hundred?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2:: @ 8281CCD
	.string "Have you completely forgotten\n"
	.string "about {STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer:: @ 8281CF5
	.string "Oh, I see!\n"
	.string "You should meet {STR_VAR_1} sometime.\l"
	.string "I'm sure you'll become a fan, too!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo:: @ 8281D40
	.string "I see, I see.\p"
	.string "Thank you!\n"
	.string "That's very useful to know.\p"
	.string "I'll share this information with other\n"
	.string "{STR_VAR_1} fans and discuss it.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial:: @ 8281DB4
	.string "There's going to be a TV special on\n"
	.string "{STR_VAR_1} very soon.\p"
	.string "I hope you catch it!$"

gTVTrainerFanClubSpecialText00:: @ 08281DFB
	.string "TRAINER FAN CLUB\n"
	.string "{STR_VAR_1} SPECIAL!\p"
	.string "This is a special presentation for\n"
	.string "the fans of {STR_VAR_1} all over HOENN!\p"
	.string "Today, we ask the question, “What do\n"
	.string "people think of {STR_VAR_1}?”\p"
	.string "We posed the question to {STR_VAR_2}\n"
	.string "as the TRAINER representative.\p"
	.string "We asked, “In one word, how would\n"
	.string "you describe {STR_VAR_1}?”\p"
	.string "The reply: “{STR_VAR_3}.”\p"
	.string "Kudos to {STR_VAR_2}!\n"
	.string "What a perceptive opinion!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.”\n"
	.string "It has such a nice ring to it!\p"
	.string "{STR_VAR_2} also scored {STR_VAR_1}'s\n"
	.string "strength from 0 to 100.$"

gTVTrainerFanClubSpecialText01:: @ 08281F90
	.string "The score was {STR_VAR_3} points!\n"
	.string "That is a very high score indeed!\p"
	.string "{STR_VAR_2} must obviously hold\n"
	.string "{STR_VAR_1} in very high esteem.$"

gTVTrainerFanClubSpecialText02:: @ 08281FFA
	.string "The score was {STR_VAR_3} points!\n"
	.string "That is quite a good score.\p"
	.string "{STR_VAR_2} must consider\n"
	.string "{STR_VAR_1} to be a rival.$"

gTVTrainerFanClubSpecialText03:: @ 08282052
	.string "The score was {STR_VAR_3} points!\n"
	.string "That's a rather weak score.\p"
	.string "{STR_VAR_2} must consider\n"
	.string "{STR_VAR_1} to be a mere sidekick.$"

gTVTrainerFanClubSpecialText04:: @ 082820B2
	.string "The score was {STR_VAR_3} point(s)!\n"
	.string "That's a terrible score.\p"
	.string "{STR_VAR_2} must consider\n"
	.string "{STR_VAR_1} to be an underling.$"

gTVTrainerFanClubSpecialText05:: @ 0828210E
	.string "There you have it, folks!\p"
	.string "I think we all learned something\n"
	.string "new about {STR_VAR_1}.\p"
	.string "In closing, I'll leave you with\n"
	.string "{STR_VAR_2}'s words.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00:: @ 0828218A
	.string "And now, it's time for…\n"
	.string "THE NAME RATER SHOW.\p"
	.string "I tell your POKéMON's fortune from\n"
	.string "the nickname you've bestowed.\p"
	.string "Advice is what I have to give, and it is\n"
	.string "helpful advice that I offer.\p"
	.string "Today, I shall do a reading of\n"
	.string "the nickname {STR_VAR_3} of {STR_VAR_1}'s\l"
	.string "POKéMON {STR_VAR_2}.\p"
	.string "Hmhm…\p"
	.string "Hmm…\n"
	.string "This nickname is…$"

gTVNameRaterText01:: @ 0828229E
	.string "A nickname that hints at talent in many\n"
	.string "different ways.\p"
	.string "I urge this TRAINER to take courage\n"
	.string "and take on many challenges.$"

gTVNameRaterText02:: @ 08282317
	.string "A nickname that perfectly complements\n"
	.string "{STR_VAR_1}, the TRAINER's name.\p"
	.string "It suggests that you will forge a fine\n"
	.string "partnership with precise timing.$"

gTVNameRaterText03:: @ 0828239D
	.string "A nickname fit for a unique individual\n"
	.string "of a POKéMON!\p"
	.string "If raised properly, this POKéMON's\n"
	.string "uniqueness will bloom excessively!$"

gTVNameRaterText04:: @ 08282418
	.string "A nickname that will nurture the caring\n"
	.string "and compassionate side of POKéMON.\p"
	.string "If raised properly, this POKéMON will\n"
	.string "come to exhibit real warmth!$"

gTVNameRaterText05:: @ 082824A6
	.string "A very fine nickname that hints at\n"
	.string "greatness to come.\p"
	.string "I am intrigued about what the future\n"
	.string "holds in store for this POKéMON.$"

gTVNameRaterText06:: @ 08282522
	.string "A good nickname that should make the\n"
	.string "POKéMON hale and hearty!\p"
	.string "That POKéMON should remain fit and\n"
	.string "robust for a long, long time.$"

gTVNameRaterText07:: @ 082825A1
	.string "A good nickname that should make the\n"
	.string "POKéMON very active!\p"
	.string "I should think that this POKéMON will be\n"
	.string "a strong performer in battles.$"

gTVNameRaterText08:: @ 08282623
	.string "An appealing nickname that should make\n"
	.string "the POKéMON very charming!\p"
	.string "I don't doubt that this POKéMON will be\n"
	.string "quite the charmer in POKéMON CONTESTS.$"

gTVNameRaterText09:: @ 082826B4
	.string "The nickname {STR_VAR_1} is rooted by\n"
	.string "the letter “{STR_VAR_3}.”\p"
	.string "That letter is supported by the first\n"
	.string "letter “{STR_VAR_2},” which gives it a solid sense\l"
	.string "of presence as a nickname.$"

gTVNameRaterText10:: @ 0828274D
	.string "The nickname {STR_VAR_1} is very\n"
	.string "shapely in a pleasing manner.\p"
	.string "The presence of the letters “{STR_VAR_2}” and\n"
	.string "“{STR_VAR_3}”--now that is remarkably good!$"

gTVNameRaterText11:: @ 082827CB
	.string "The nickname {STR_VAR_1}--it has a\n"
	.string "sublime, flowing feel to it.\p"
	.string "The flow from the initial letter “{STR_VAR_2}” to\n"
	.string "“{STR_VAR_3}” is especially wonderful.$"

gTVNameRaterText12:: @ 08282849
	.string "Let's examine other examples of fine\n"
	.string "nicknames, shall we?$"

gTVNameRaterText13:: @ 08282883
	.string "Try this example. Take a part of the\n"
	.string "TRAINER name of {STR_VAR_1}, and end\l"
	.string "up with the fine nickname {STR_VAR_2}{STR_VAR_3}.$"

gTVNameRaterText14:: @ 082828E4
	.string "The nickname {STR_VAR_2}{STR_VAR_3} would also work\n"
	.string "quite well.$"

gTVNameRaterText15:: @ 08282912
	.string "The POKéMON's species name of\n"
	.string "{STR_VAR_2} could be used as the basis\l"
	.string "for making the nickname {STR_VAR_1}{STR_VAR_3}.$"

gTVNameRaterText16:: @ 0828296C
	.string "{STR_VAR_1}{STR_VAR_3} would also be an effective\n"
	.string "nickname.$"

gTVNameRaterText17:: @ 08282996
	.string "What should always be avoided is using\n"
	.string "another POKéMON species name.\p"
	.string "For instance, avoid taking the name of\n"
	.string "{STR_VAR_2} to make the nickname {STR_VAR_1}{STR_VAR_3}.\l"
	.string "That is unacceptable.$"

gTVNameRaterText18:: @ 08282A36
	.string "I must say that {STR_VAR_1} is quite\n"
	.string "a good nickname.\p"
	.string "I hope that the TRAINER will continue\n"
	.string "to treat {STR_VAR_1} with love.\p"
	.string "That's it for today's show.\n"
	.string "May we meet again.$"

gTVPokemonAnglerText00:: @ 08282ACF
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANNOUNCER: Hello! Today, we'll get tips\n"
	.string "on fishing for {STR_VAR_2}.\p"
	.string "GURU, what advice can you give for\n"
	.string "catching {STR_VAR_2}?\p"
	.string "GURU: Hm? Catching {STR_VAR_2}?\n"
	.string "Well, let me tell you, be patient and\l"
	.string "wait. That's the bottom line.\p"
	.string "Do you see {STR_VAR_1} over there?\n"
	.string "That TRAINER makes a good example.\p"
	.string "That TRAINER's already had\n"
	.string "{STR_VAR_3} POKéMON get away.\p"
	.string "But there {STR_VAR_1} waits. No giving up.\n"
	.string "That's the law for catching {STR_VAR_2}.\p"
	.string "ANNOUNCER: I see…\p"
	.string "Oh! {STR_VAR_1} has finally landed an\n"
	.string "elusive {STR_VAR_2}!\p"
	.string "The TRAINER appears close to tears\n"
	.string "out of sheer joy!\p"
	.string "Seeing that elated look, I'm getting\n"
	.string "the itch to go fishing, too!\p"
	.string "Viewers, why not take this as a cue to\n"
	.string "try some {STR_VAR_2} fishing?\p"
	.string "Until our next broadcast, farewell and\n"
	.string "good fishing to you all!$"

gTVPokemonAnglerText01:: @ 08282D7C
	.string "{STR_VAR_2} ANGLER\p"
	.string "ANNOUNCER: Hello! Today, we'll get tips\n"
	.string "on fishing for {STR_VAR_2}.\p"
	.string "GURU, what advice can you give for\n"
	.string "catching {STR_VAR_2}?\p"
	.string "GURU: Hm? Catching {STR_VAR_2}?\n"
	.string "Well, let me tell you, use your fishing\l"
	.string "ROD with vigor!\p"
	.string "Do you see {STR_VAR_1} over there?\n"
	.string "See how the ROD is handled?\p"
	.string "That TRAINER's already caught\n"
	.string "{STR_VAR_3} in a row.\p"
	.string "ANNOUNCER: It's incredible!\n"
	.string "It looks like a storm…\p"
	.string "Seeing technique of that caliber, I'm\n"
	.string "getting the itch to go fishing, too.\p"
	.string "Viewers, why not take this as a cue to\n"
	.string "try some {STR_VAR_2} fishing?\p"
	.string "Until our next broadcast, farewell and\n"
	.string "good fishing to you all!$"

gTVPokemonTodayFailedText00:: @ 08282F9B
	.string "Hello!\p"
	.string "It's time for POKéMON TODAY!\p"
	.string "BIG SIS: Hi! Is everyone peachy and\n"
	.string "perky today?\p"
	.string "Today, we're going to look at {STR_VAR_1}'s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "BIG BRO: Yeah! That's what we're going\n"
	.string "to do!$"

gTVPokemonTodayFailedText01:: @ 0828304D
	.string "Oh!\n"
	.string "Speaking of {STR_VAR_1}…\p"
	.string "BIG SIS, I saw the TRAINER with my very\n"
	.string "own eyes!\p"
	.string "BIG SIS: Oh, what did you see?\p"
	.string "BIG BRO: Well, I had to go on a trip to\n"
	.string "{STR_VAR_2}.\p"
	.string "That's when I happened to come across\n"
	.string "{STR_VAR_1}, who was trying to catch the\l"
	.string "POKéMON {STR_VAR_3}, but…$"

gTVPokemonTodayFailedText02:: @ 08283135
	.string "The POKéMON managed to get away!\p"
	.string "It ended up wasting this many\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "You should have seen the expression\n"
	.string "of frustration on {STR_VAR_1}'s face when\l"
	.string "the POKéMON took off!$"

gTVPokemonTodayFailedText03:: @ 082831DF
	.string "But {STR_VAR_1} goofed and made the\n"
	.string "POKéMON faint!\p"
	.string "It ended up wasting this many\n"
	.string "POKé BALLS: {STR_VAR_2}!\p"
	.string "You should have seen the expression\n"
	.string "of stunned dismay on {STR_VAR_1}'s face\l"
	.string "when the POKéMON fainted!$"

gTVPokemonTodayFailedText04:: @ 08283294
	.string "BIG SIS: Hey, there!\n"
	.string "That's not nice!\p"
	.string "You shouldn't be laughing at other\n"
	.string "people's misfortune!\p"
	.string "Oh, poor {STR_VAR_1}.\n"
	.string "What a shame!\p"
	.string "BIG BRO: That's true!\n"
	.string "Sorry for laughing.$"

gTVPokemonTodayFailedText05:: @ 08283337
	.string "BIG SIS: Bufufu…\p"
	.string "BIG BRO: Hey!\n"
	.string "You just laughed, too!\p"
	.string "BIG SIS: Huh?!\p"
	.string "I didn't laugh!\n"
	.string "Honestly, I didn't!\p"
	.string "Oh, poor {STR_VAR_1}.\n"
	.string "What a shame!\p"
	.string "BIG BRO: …$"

gTVPokemonTodayFailedText06:: @ 082833C6
	.string "BIG SIS: That's enough silliness!\n"
	.string "Let's look at today's POKéMON…\p"
	.string "Huh?\n"
	.string "We're out of time already?\p"
	.string "Aww!\n"
	.string "We couldn't profile a POKéMON today!\p"
	.string "BIG BRO: See you again next time!\p"
	.string "BIG SIS: Hey, don't end the show\n"
	.string "without me!$"

gTVPokemonTodaySuccessfulText00:: @ 082834A0
	.string "Hello!\p"
	.string "It's time for POKéMON TODAY!\p"
	.string "BIG SIS: Hi! Is everyone peachy and\n"
	.string "perky today?\p"
	.string "Today, we're going to look at {STR_VAR_1}'s\n"
	.string "POKéMON {STR_VAR_2}!\p"
	.string "BIG BRO: Yeah! That's what we're going\n"
	.string "to do!$"

gTVPokemonTodaySuccessfulText01:: @ 08283552
	.string "BIG SIS: {STR_VAR_1} gave the nickname\n"
	.string "{STR_VAR_3} to the {STR_VAR_2}!\p"
	.string "It sounds like {STR_VAR_3} is getting\n"
	.string "good, loving care!$"

gTVPokemonTodaySuccessfulText02:: @ 082835AE
	.string "BIG BRO: The TRAINER had to throw this\n"
	.string "many POKé BALLS to catch it: {STR_VAR_3}!\p"
	.string "It finally took a single {STR_VAR_2}\n"
	.string "to catch it!$"

gTVPokemonTodaySuccessfulText03:: @ 0828361F
	.string "BIG SIS: If it was that easy to catch,\n"
	.string "it must have been destiny that brought\l"
	.string "{STR_VAR_1} and the {STR_VAR_2} together!$"

gTVPokemonTodaySuccessfulText04:: @ 08283685
	.string "BIG SIS: Wow! That's so neat!\p"
	.string "But you know what they say, a POKéMON\n"
	.string "that takes a lot of effort to catch\l"
	.string "earns the love of its TRAINER!$"

gTVPokemonTodaySuccessfulText05:: @ 0828370C
	.string "BIG SIS: {STR_VAR_1}'s {STR_VAR_2} is a\n"
	.string "memorable POKéMON because it took an\l"
	.string "invaluable MASTER BALL to catch!\p"
	.string "BIG BRO: Wow! That's mega-awesome!\p"
	.string "BIG SIS: {STR_VAR_1} must have really\n"
	.string "wanted that {STR_VAR_2}, for sure!$"

gTVPokemonTodaySuccessfulText06:: @ 082837C2
	.string "BIG BRO: Then to give the nickname\n"
	.string "{STR_VAR_3} to that {STR_VAR_2}…\p"
	.string "You really get a good idea about\n"
	.string "{STR_VAR_1}'s TRAINER sense.\p"
	.string "BIG SIS: I second that notion!$"

gTVPokemonTodaySuccessfulText07:: @ 08283848
	.string "If it were me, I'd give that nickname\n"
	.string "to something like this {STR_VAR_3}!\p"
	.string "BIG BRO: Whoa! That could be the start\n"
	.string "of something new!$"

gTVPokemonTodaySuccessfulText08:: @ 082838C2
	.string "{STR_VAR_2} the {STR_VAR_1}?\n"
	.string "Doesn't that sound perfect?\p"
	.string "The letters and everything--they\n"
	.string "sound just right for the POKéMON\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: Yeah, true, that!$"

gTVPokemonTodaySuccessfulText09:: @ 0828394A
	.string "As far as I know, no TRAINER has ever\n"
	.string "given the nickname {STR_VAR_2} to their\l"
	.string "{STR_VAR_1}!\p"
	.string "BIG BRO: That just goes to show what\n"
	.string "great taste the TRAINER has in picking\l"
	.string "nicknames!$"

gTVPokemonTodaySuccessfulText10:: @ 082839EA
	.string "The next time I catch a POKéMON,\n"
	.string "I should give it the name {STR_VAR_2}.\p"
	.string "BIG BRO: Huh? Me, too!\n"
	.string "I'll use the nickname {STR_VAR_2}, too!$"

gTVPokemonTodaySuccessfulText11:: @ 08283A5F
	.string "BIG SIS: Oh, no!\n"
	.string "Look at the time!\p"
	.string "Well, gang, this is it for today.\n"
	.string "See you again next time!\p"
	.string "BIG BRO: Remember, it could be your\n"
	.string "POKéMON in the spotlight next time!$"

gTVTodaysSmartShopperText00:: @ 08283B05
	.string "Hello!\p"
	.string "It's time for TODAY'S SMART SHOPPER.\p"
	.string "INTERVIEWER: How are you, viewers?\p"
	.string "Today we're visiting a shop\n"
	.string "in {STR_VAR_2}.\p"
	.string "Let's check on what the hot sellers\n"
	.string "have been recently.$"

gTVTodaysSmartShopperText01:: @ 08283BAF
	.string "Let's interview the clerk to get the\n"
	.string "lowdown.\p"
	.string "Hi, how's your business?\p"
	.string "CLERK: Oh, we're doing excellent.\p"
	.string "Recently, {STR_VAR_2} has been\n"
	.string "selling especially strongly.\p"
	.string "Why, just the other day a TRAINER\n"
	.string "named {STR_VAR_1} bought {STR_VAR_3}.$"

gTVTodaysSmartShopperText02:: @ 08283C81
	.string "INTERVIEWER: The TRAINER bought\n"
	.string "{STR_VAR_3} {STR_VAR_2}S? That's a haul!\p"
	.string "If I may say so, {STR_VAR_1} must have\n"
	.string "been stocking up for a long journey\l"
	.string "to far-off places.\p"
	.string "For traveling, {STR_VAR_2}S are so\n"
	.string "important!$"

gTVTodaysSmartShopperText03:: @ 08283D32
	.string "INTERVIEWER: Speaking of the item\n"
	.string "{STR_VAR_2}, I just bought {STR_VAR_3} of\l"
	.string "them recently.\p"
	.string "After all, {STR_VAR_2}'s a great item!$"

gTVTodaysSmartShopperText04:: @ 08283D99
	.string "INTERVIEWER: {STR_VAR_2}?!\n"
	.string "But {STR_VAR_3} of them?!\p"
	.string "I didn't think there would be anyone\n"
	.string "buying that many.\p"
	.string "My goodness, I can only afford one or\n"
	.string "two at a time…$"

gTVTodaysSmartShopperText05:: @ 08283E28
	.string "INTERVIEWER: One time, I bought\n"
	.string "a whole lot of the item {STR_VAR_2}.\p"
	.string "But it turned out to be too many.\n"
	.string "I ended up regretting it…\p"
	.string "Since then, I only buy strictly what\n"
	.string "I absolutely need…\p"
	.string "Oops!\p"
	.string "There's no point talking about me!$"

gTVTodaysSmartShopperText06:: @ 08283F01
	.string "CLERK: {STR_VAR_1} also bought the item\n"
	.string "{STR_VAR_2} in bulk, taking {STR_VAR_3}.\p"
	.string "INTERVIEWER: Oh, that's smart.\n"
	.string "{STR_VAR_2}'s a very good item, too.$"

gTVTodaysSmartShopperText07:: @ 08283F72
	.string "CLERK: And, the TRAINER also bought\n"
	.string "{STR_VAR_3} of the item {STR_VAR_2}.$"

gTVTodaysSmartShopperText08:: @ 08283FA9
	.string "CLERK: Plus, it was during a big sale.\n"
	.string "That's smart shopping.$"

gTVTodaysSmartShopperText09:: @ 08283FE7
	.string "INTERVIEWER: Hmm… {STR_VAR_1} sounds like\n"
	.string "quite the shrewd bargain hunter!\p"
	.string "In total, {STR_VAR_1}'s purchases came to…\p"
	.string "¥{STR_VAR_2}?!\n"
	.string "What an amazing sum!\p"
	.string "Oops! We're out of time!\n"
	.string "See you on our next broadcast!$"

gTVTodaysSmartShopperText10:: @ 0828409E
	.string "CLERK: {STR_VAR_1} is a VIP customer,\n"
	.string "no doubt about it.$"

gTVTodaysSmartShopperText11:: @ 082840CE
	.string "Let's interview the clerk to get the\n"
	.string "lowdown.\p"
	.string "Hi, how's your business?\p"
	.string "CLERK: Oh, we're doing unbelievable\n"
	.string "business. It's almost overwhelming.\p"
	.string "Recently, a TRAINER named {STR_VAR_1}\n"
	.string "bought the item {STR_VAR_2} in bulk.\p"
	.string "The TRAINER almost cleared out our\n"
	.string "entire stock of {STR_VAR_2}S.\p"
	.string "I never dreamt that any customer\n"
	.string "would ever need so many {STR_VAR_2}S.\l"
	.string "It's just unheard of!\p"
	.string "INTERVIEWER: So that would be like 100\n"
	.string "or 200 sold?\p"
	.string "CLERK: Oh, no, much more than that!\p"
	.string "INTERVIEWER: Oh, my goodness!\n"
	.string "{STR_VAR_1} must be a special shopper!\p"
	.string "CLERK: {STR_VAR_1} is a VIP customer,\n"
	.string "no doubt about it.$"

gTVTodaysSmartShopperText12:: @ 082842E6
	.string "INTERVIEWER: Hmm…\n"
	.string "That is amazing.\p"
	.string "But why would the TRAINER need to buy\n"
	.string "so many?\p"
	.string "… …\p"
	.string "The mystery deepens, but this is all\n"
	.string "the time we have today.\l"
	.string "See you on our next broadcast!\p"
	.string "Still, {STR_VAR_1} is certainly an enigma…$"

gTVWorldOfMastersText00:: @ 082843BA
	.string "THE WORLD OF MASTERS\p"
	.string "Hello, viewers.\p"
	.string "Perhaps you are aware of a TRAINER\n"
	.string "named {STR_VAR_1}.\p"
	.string "{STR_VAR_1} is famous as a master at\n"
	.string "catching POKéMON.\p"
	.string "{STR_VAR_1}'s quest for POKéMON depends\n"
	.string "entirely on a careful search on foot.\p"
	.string "On one memorable day, the TRAINER\n"
	.string "walked some {STR_VAR_2} steps.\p"
	.string "The total number of POKéMON caught\n"
	.string "that day reached an impressive {STR_VAR_3}!$"

gTVWorldOfMastersText01:: @ 082844FD
	.string "That remarkable feat must have been\n"
	.string "possible because of the trust between\l"
	.string "the TRAINER and {STR_VAR_1}.$"

gTVWorldOfMastersText02:: @ 0828455B
	.string "The master caught the day's last\n"
	.string "{STR_VAR_3} near {STR_VAR_2}.\p"
	.string "That POKéMON apparently enjoys\n"
	.string "a special status as a record holder.\p"
	.string "Skilled TRAINERS should be encouraged\n"
	.string "to challenge this fine record.\p"
	.string "That's all for today.\n"
	.string "Please tune in next time.$"

gTVTodaysRivalTrainerText00:: @ 08284641
	.string "TODAY'S RIVAL TRAINER!\p"
	.string "Hello, fellow POKéMON TRAINERS!\n"
	.string "How are we all doing today?\p"
	.string "Today, like every other day,\n"
	.string "we'll examine one of our rivals!$"

gTVTodaysRivalTrainerText07:: @ 082846D2
	.string "Today's rival TRAINER is {STR_VAR_1},\n"
	.string "who's around {STR_VAR_3} now.\p"
	.string "{STR_VAR_1} has so far registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

gTVTodaysRivalTrainerText08:: @ 08284738
	.string "Today's rival TRAINER is {STR_VAR_1},\n"
	.string "who's in a SECRET BASE now.\p"
	.string "{STR_VAR_1} has so far registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

gTVTodaysRivalTrainerText09:: @ 082847A5
	.string "Today's rival TRAINER is {STR_VAR_1}.\p"
	.string "So far, {STR_VAR_1} has registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

gTVTodaysRivalTrainerText10:: @ 082847F7
	.string "Today's rival TRAINER is {STR_VAR_1},\n"
	.string "who's on a ferry now.\p"
	.string "{STR_VAR_1} has so far registered\n"
	.string "{STR_VAR_2} POKéMON in the POKéDEX.$"

	.string "$"

gTVTodaysRivalTrainerText01:: @ 0828485F
	.string "And how many BADGES does our rival\n"
	.string "have? The number is {STR_VAR_1}!$"

gTVTodaysRivalTrainerText02:: @ 0828489A
	.string "But our rival hasn't obtained\n"
	.string "a single BADGE yet!$"

gTVTodaysRivalTrainerText03:: @ 082848CC
	.string "Our rival hasn't obtained a single\n"
	.string "BATTLE FRONTIER Symbol yet.$"

gTVTodaysRivalTrainerText04:: @ 0828490B
	.string "Let's see how many BATTLE FRONTIER\n"
	.string "Symbols our rival has.\p"
	.string "Gold Symbols: {STR_VAR_1}!\n"
	.string "Silver Symbols: {STR_VAR_2}!$"

gTVTodaysRivalTrainerText05:: @ 0828496B
	.string "Our rival has collected {STR_VAR_1} Battle\n"
	.string "Point(s) at the BATTLE FRONTIER.$"

gTVTodaysRivalTrainerText06:: @ 082849AE
	.string "So, how did you measure up in\n"
	.string "comparison to {STR_VAR_1}?\p"
	.string "The adventure rolls on!\p"
	.string "Fellow TRAINERS!\p"
	.string "Let's all keep moving forward\n"
	.string "and ahead of our rivals!$"

gTVDewfordTrendWatcherNetworkText00:: @ 08284A3E
	.string "DEWFORD TREND-WATCHER NETWORK!\p"
	.string "MC: Wassup?\n"
	.string "We'll keep it real with the latest on\l"
	.string "what's hip and happening in DEWFORD.\p"
	.string "Our guest today is this old cat whose\n"
	.string "claim to fame is being the authority\l"
	.string "on all things in DEWFORD.\p"
	.string "Old man: Glad to be here.\p"
	.string "MC: Let's cut to the chase, right on.\p"
	.string "What's your word on what's groovin'\n"
	.string "the good folks of DEWFORD?\p"
	.string "Old man: {STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC: {STR_VAR_1} {STR_VAR_2},\n"
	.string "you say?\p"
	.string "Old man: No.\p"
	.string "{STR_VAR_1} {STR_VAR_2} never\n"
	.string "did get popular at all.\p"
	.string "Would you like to hear about it?\p"
	.string "MC: Uh, no. What we want to know is\n"
	.string "what's the in thing of the moment…$"

gTVDewfordTrendWatcherNetworkText01:: @ 08284C55
	.string "Old man: {STR_VAR_1} {STR_VAR_2}\n"
	.string "was what {STR_VAR_3} from LITTLEROOT\l"
	.string "taught me as being trendy…$"

gTVDewfordTrendWatcherNetworkText02:: @ 08284C9B
	.string "Old man: {STR_VAR_1} {STR_VAR_2}\n"
	.string "was what {STR_VAR_3} from LITTLEROOT\l"
	.string "taught me as being trendy…$"

gTVDewfordTrendWatcherNetworkText03:: @ 08284CE1
	.string "But it was utterly hopeless.\p"
	.string "{STR_VAR_1} {STR_VAR_2} festival!\p"
	.string "{STR_VAR_1} {STR_VAR_2} contest!\p"
	.string "I tried teaching everyone the best\n"
	.string "I could, but…\p"
	.string "Perhaps the {STR_VAR_1} part just\n"
	.string "wasn't right…\p"
	.string "MC: Uh, excuse me, compadre, I need\n"
	.string "to hear about what's in now…$"

gTVDewfordTrendWatcherNetworkText04:: @ 08284DB6
	.string "Old man: {STR_VAR_3}!\n"
	.string "Please, tell me something bigger than\l"
	.string "that {STR_VAR_1} {STR_VAR_2}!$"

gTVDewfordTrendWatcherNetworkText05:: @ 08284DF5
	.string "Old man: {STR_VAR_3}!\n"
	.string "Please, tell me something bigger than\l"
	.string "that {STR_VAR_1} {STR_VAR_2}!$"

gTVDewfordTrendWatcherNetworkText06:: @ 08284E34
	.string "MC: …Uh… So, there you have it,\n"
	.string "all you trendy, hep cats out there!\p"
	.string "{STR_VAR_1} {STR_VAR_2}…uh…\n"
	.string "Didn't get hip or happening in DEWFORD!\p"
	.string "My time is up. Catch you on the fly!\p"
	.string "Old man: {STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00:: @ 08284EDF
	.string "HOENN TREASURE INVESTIGATORS!\p"
	.string "Hi, gang!\n"
	.string "Score any secret items lately?\p"
	.string "As always, we'll examine eyewitness\n"
	.string "reports of secrets from all over!\p"
	.string "Let's start with a letter.\n"
	.string "It says, “{STR_VAR_1} discovered!”$"

gTVHoennTreasureInvestigatorsText01:: @ 08284FA1
	.string "Wow, we'd better check this letter\n"
	.string "out! Let me read it to you.\p"
	.string "…Dear INVESTIGATORS,\n"
	.string "I hope you are well.\p"
	.string "I recently saw {STR_VAR_2} somewhere\n"
	.string "around {STR_VAR_3}.\p"
	.string "The TRAINER found the item\n"
	.string "{STR_VAR_1}. It made me envious.\p"
	.string "…Well, good going, {STR_VAR_2}!\p"
	.string "Viewers, let that motivate you to\n"
	.string "fire up your ITEMFINDERS and search!\p"
	.string "I'll be waiting for exciting news\n"
	.string "from all of you!$"

gTVHoennTreasureInvestigatorsText02:: @ 082850F5
	.string "Wow, we'd better check this letter\n"
	.string "out! Let me read it to you.\p"
	.string "…Dear INVESTIGATORS,\n"
	.string "I hope you are well.\p"
	.string "I recently saw {STR_VAR_2} on a ferry.\p"
	.string "The TRAINER found the item\n"
	.string "{STR_VAR_1}. It made me envious.\p"
	.string "…Well, good going, {STR_VAR_2}!\p"
	.string "Viewers, let that motivate you to\n"
	.string "fire up your ITEMFINDERS and search!\p"
	.string "I'll be waiting for exciting news\n"
	.string "from all of you!$"

gTVFindThatGamerText00:: @ 08285240
	.string "FIND THAT GAMER!\p"
	.string "Hey, all you gamers!\n"
	.string "How's your {STR_VAR_2} spinning?\p"
	.string "Like always, we'll cast our spotlight\n"
	.string "on a rare TRAINER who's visited the\l"
	.string "GAME CORNER!\p"
	.string "Today, our no. 1 gamer is…\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01:: @ 082852F4
	.string "{STR_VAR_1} played the {STR_VAR_2} game\n"
	.string "and won a rare {STR_VAR_3} COINS.\p"
	.string "“When {STR_VAR_1} comes, we need to\n"
	.string "make sure we have enough COINS.”\p"
	.string "That's what the GAME CORNER clerks\n"
	.string "mutter when our gamer is in play!\p"
	.string "Viewers, it's best to watch your COINS\n"
	.string "like {STR_VAR_1} if you visit the GAME\l"
	.string "CORNER and play the {STR_VAR_2} game.\p"
	.string "This is live from the GAME CORNER--\n"
	.string "where you can feel the excitement!\p"
	.string "That's all for today!$"

gTVFindThatGamerText02:: @ 08285463
	.string "{STR_VAR_1} played the {STR_VAR_2} game\n"
	.string "and lost {STR_VAR_3} COINS.\p"
	.string "“When {STR_VAR_1} comes, our COIN\n"
	.string "sales seem to increase.”\p"
	.string "That's what the GAME CORNER clerks\n"
	.string "say when our gamer is in play!$"

gTVFindThatGamerText03:: @ 08285500
	.string "Viewers, it's best to watch your COINS\n"
	.string "like {STR_VAR_1} if you visit the GAME\l"
	.string "CORNER and play the {STR_VAR_2} game.\p"
	.string "This is live from the GAME CORNER--\n"
	.string "where you can feel the excitement!\p"
	.string "That's all for today!$"

gTVBreakingNewsText00:: @ 082855BF
	.string "BREAKING NEWS TV!$"

gTVBreakingNewsText01:: @ 082855D1
	.string "Rare {STR_VAR_2} caught by\n"
	.string "{STR_VAR_1}!\p"
	.string "We're live from the vicinity of\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1} successfully captured\n"
	.string "a rare {STR_VAR_2} earlier here!$"

gTVBreakingNewsText02:: @ 0828563C
	.string "When {STR_VAR_1} encountered the rare\n"
	.string "{STR_VAR_2}, the TRAINER sent out\l"
	.string "the POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText03:: @ 08285682
	.string "In the battle, the number of POKé\n"
	.string "BALLS thrown by the TRAINER was {STR_VAR_1}.\p"
	.string "Ultimately, the rare POKéMON was\n"
	.string "caught by the {STR_VAR_2} used last.$"

gTVBreakingNewsText04:: @ 08285705
	.string "In that instant, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s roars of\l"
	.string "triumphant joy.\p"
	.string "I must say I'm a little envious of\n"
	.string "{STR_VAR_1}. I'd love to roar, too.\p"
	.string "…That ends the live feed from\n"
	.string "the happy scene!$"

gTVBreakingNewsText05:: @ 082857B0
	.string "{STR_VAR_1} fails to capture a rare\n"
	.string "{STR_VAR_2}!\p"
	.string "We're live from the vicinity of\n"
	.string "{STR_VAR_3}!\p"
	.string "It was here that {STR_VAR_1} failed\n"
	.string "to capture a rare {STR_VAR_2}!$"

gTVBreakingNewsText06:: @ 08285824
	.string "When {STR_VAR_1} encountered the rare\n"
	.string "{STR_VAR_2}, the TRAINER sent out\l"
	.string "the POKéMON {STR_VAR_3}.$"

gTVBreakingNewsText07:: @ 0828586A
	.string "The TRAINER made the {STR_VAR_2}\n"
	.string "use the move {STR_VAR_1}.\p"
	.string "Without meaning to, the TRAINER\n"
	.string "made the rare POKéMON faint…$"

gTVBreakingNewsText12:: @ 082858D0
	.string "However, {STR_VAR_1} panicked at\n"
	.string "the sight of the rare {STR_VAR_2}.\p"
	.string "In confusion, the TRAINER ordered\n"
	.string "{STR_VAR_3} to attack.\p"
	.string "Without meaning to, the TRAINER\n"
	.string "made the rare POKéMON faint.$"

gTVBreakingNewsText08:: @ 0828596F
	.string "In that instant, {STR_VAR_2}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText09:: @ 082859AC
	.string "However, {STR_VAR_1} seemed to run\n"
	.string "out of POKé BALLS.\p"
	.string "The TRAINER had to break off\n"
	.string "the battle with the rare {STR_VAR_2}.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText10:: @ 08285A50
	.string "However, the {STR_VAR_2} fled without\n"
	.string "warning.\p"
	.string "In that instant, {STR_VAR_3}\n"
	.string "echoed with {STR_VAR_1}'s shrieks of\l"
	.string "frustration…$"

gTVBreakingNewsText11:: @ 08285AB3
	.string "I must say I feel for {STR_VAR_1}.\n"
	.string "Why, it makes me want to shriek, too.\p"
	.string "…That ends the live feed from\n"
	.string "the melancholy scene!$"

gTVSecretBaseVisitText00:: @ 08285B27
	.string "Hello, folks!\n"
	.string "It's time again for\l"
	.string "a SECRET BASE VISIT.\p"
	.string "Today, we visit the SECRET BASE\n"
	.string "of {STR_VAR_1}.\p"
	.string "How has {STR_VAR_1} personalized\n"
	.string "the SECRET BASE?\p"
	.string "Let's find out!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01:: @ 08285BCA
	.string "Oh!\n"
	.string "How marvelous!\p"
	.string "This {STR_VAR_2}…\n"
	.string "It's not what one would expect to\l"
	.string "find here!$"

gTVSecretBaseVisitText02:: @ 08285C13
	.string "Oh!\n"
	.string "How remarkable!\p"
	.string "There isn't a single piece\n"
	.string "of furniture or interior goods!\p"
	.string "Mere mortals couldn't hope to\n"
	.string "imitate this bold statement!\p"
	.string "It's simple, but it bursts, yes,\n"
	.string "bursts with wildness!\p"
	.string "My hat's off to you, {STR_VAR_1}.\n"
	.string "It had to be you!$"

gTVSecretBaseVisitText03:: @ 08285CFF
	.string "Oh! I see!\n"
	.string "With perfect clarity, I see it!\p"
	.string "This {STR_VAR_2} being here…\n"
	.string "It sends an effective message!$"

gTVSecretBaseVisitText04:: @ 08285D5D
	.string "Oh! I see!\n"
	.string "With perfect clarity, I see it!\p"
	.string "This space is kept deliberately\n"
	.string "clear of interior items!\p"
	.string "It sends an effective message!$"

gTVSecretBaseVisitText05:: @ 08285DE0
	.string "Wheeew!\p"
	.string "The pairing of the {STR_VAR_2}\n"
	.string "with the {STR_VAR_3}!\p"
	.string "It's a dream combination if there\n"
	.string "ever was one!$"

gTVSecretBaseVisitText06:: @ 08285E3B
	.string "Wheeew!\p"
	.string "The placement of this {STR_VAR_2}\n"
	.string "right here…\p"
	.string "It has a presence that fills\n"
	.string "the entire SECRET BASE!$"

gTVSecretBaseVisitText07:: @ 08285E9D
	.string "Wheeew!\p"
	.string "There's nothing in place here.\p"
	.string "This empty space has an effect on\n"
	.string "the entire SECRET BASE.$"

gTVSecretBaseVisitText08:: @ 08285EFE
	.string "Oh!\n"
	.string "Here comes {STR_VAR_1}!\l"
	.string "Let's challenge the TRAINER!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09:: @ 08285F46
	.string "Sigh…\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON were truly\n"
	.string "worthy of the CHAMPION's title.\p"
	.string "They gave ample proof of {STR_VAR_1}'s\n"
	.string "toughness as a TRAINER.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText10:: @ 08286049
	.string "Aiyeeh!\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON were\n"
	.string "monstrously tough!\p"
	.string "They gave ample proof of {STR_VAR_1}'s\n"
	.string "tenacity as a TRAINER.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText11:: @ 0828613A
	.string "Wheeew!\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON were clearly\n"
	.string "raised in a well-balanced manner.\p"
	.string "They gave ample proof of {STR_VAR_1}'s\n"
	.string "thoughtfulness as a TRAINER.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText12:: @ 08286248
	.string "Well, well!\n"
	.string "I've got to hand it to {STR_VAR_1}.\p"
	.string "The TRAINER's POKéMON showed\n"
	.string "great promise for future growth.\p"
	.string "They represented {STR_VAR_1}'s\n"
	.string "hopes and dreams.\p"
	.string "That the {STR_VAR_2} knew the move\n"
	.string "{STR_VAR_3}…\p"
	.string "It shows you what sort of a TRAINER\n"
	.string "{STR_VAR_1} is.\p"
	.string "Certainly, it was quite a lesson!$"

gTVSecretBaseVisitText13:: @ 08286340
	.string "I must say, what a superb SECRET BASE\n"
	.string "it was!\p"
	.string "Viewers, if you have the chance,\n"
	.string "do visit {STR_VAR_1}'s SECRET BASE.\p"
	.string "Until next time, I bid you adieu!$"

gTVPokemonLotteryWinnerFlashReportText00:: @ 082863CC
	.string "It's exciting!\n"
	.string "It's dramatic!\p"
	.string "It's the POKéMON LOTTERY\n"
	.string "WINNER FLASH REPORT!\p"
	.string "Hello! We're coming at you live from\n"
	.string "the POKéMON LOTTERY CORNER on\l"
	.string "the ground floor of the LILYCOVE\l"
	.string "DEPARTMENT STORE!\p"
	.string "Like it always happens, another\n"
	.string "lucky TRAINER appeared today!\p"
	.string "That TRAINER's name…\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1} won the {STR_VAR_2} prize\n"
	.string "and took home the {STR_VAR_3}!\p"
	.string "{STR_VAR_1}!\n"
	.string "Congratulations!\p"
	.string "Viewers, don't just watch,\n"
	.string "get in on the action!\p"
	.string "All of us at the LILYCOVE DEPARTMENT\n"
	.string "STORE look forward to your next visit!\p"
	.string "This has been a live broadcast from\n"
	.string "the LILYCOVE DEPARTMENT STORE,\l"
	.string "offering you the greatest selection\l"
	.string "in all HOENN!$"

gTVThePokemonBattleSeminarText00:: @ 08286616
	.string "THE POKéMON BATTLE SEMINAR!\p"
	.string "We examine battles to see what\n"
	.string "lessons we may learn from others.\p"
	.string "Today's case study is on {STR_VAR_1}'s\n"
	.string "battle.\p"
	.string "{STR_VAR_1}'s {STR_VAR_2} was\n"
	.string "battling one {STR_VAR_3}…$"

gTVThePokemonBattleSeminarText01:: @ 082866B6
	.string "And it used the move {STR_VAR_3}\n"
	.string "on the {STR_VAR_2}…\p"
	.string "Hmm… {STR_VAR_1}!\n"
	.string "That's the wrong thing to do!$"

gTVThePokemonBattleSeminarText02:: @ 08286700
	.string "In addition to the doomed move,\n"
	.string "the TRAINER's {STR_VAR_1} also knew$"

gTVThePokemonBattleSeminarText03:: @ 0828673B
	.string "the moves {STR_VAR_1}, {STR_VAR_2},\n"
	.string "and {STR_VAR_3}.$"

gTVThePokemonBattleSeminarText04:: @ 08286755
	.string "the moves {STR_VAR_1} and\n"
	.string "{STR_VAR_2}.$"

gTVThePokemonBattleSeminarText05:: @ 0828676A
	.string "the move {STR_VAR_2}.$"

gTVThePokemonBattleSeminarText06:: @ 08286777
	.string "So, in this situation, what should\n"
	.string "the TRAINER have used?\p"
	.string "… … … … … …\n"
	.string "The move {STR_VAR_1}!\p"
	.string "The move {STR_VAR_1} would have been\n"
	.string "absolutely better than {STR_VAR_2}.\p"
	.string "Viewers, I urge you to learn from this\n"
	.string "case and battle with intelligence!\p"
	.string "Until next time, farewell!$"

gTVTrainerFanClubText00:: @ 08286866
	.string "All together now!\n"
	.string "TRAINER FAN CLUB!\p"
	.string "MC: How's everyone groovin'?\n"
	.string "Today, we've rounded up the fans of\l"
	.string "the hyper-popular TRAINER {STR_VAR_1}!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS: {STR_VAR_1}!\p"
	.string "MC: Everyone!\n"
	.string "How do you like {STR_VAR_1}?!\p"
	.string "FANS: We love {STR_VAR_1}!\p"
	.string "MC: What do you love about\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01:: @ 0828695E
	.string "FANS: Their cool way of throwing\n"
	.string "POKé BALLS!$"

gTVTrainerFanClubText02:: @ 0828698B
	.string "FANS: Their adorable way of running!$"

gTVTrainerFanClubText03:: @ 082869B0
	.string "FANS: How the TRAINER turns tough\n"
	.string "when the going gets tough!$"

gTVTrainerFanClubText04:: @ 082869ED
	.string "FANS: The TRAINER's knowledge of\n"
	.string "POKéMON!$"

gTVTrainerFanClubText05:: @ 08286A17
	.string "FANS: The TRAINER's kindness toward\n"
	.string "all POKéMON!$"

gTVTrainerFanClubText06:: @ 08286A48
	.string "FANS: The TRAINER's amazing\n"
	.string "BIKE-riding techniques!$"

gTVTrainerFanClubText07:: @ 08286A7C
	.string "FANS: The TRAINER's impressive\n"
	.string "item-buying style!$"

gTVTrainerFanClubText08:: @ 08286AAE
	.string "FANS: The TRAINER's charming way\n"
	.string "of nicknaming POKéMON!$"

gTVTrainerFanClubText09:: @ 08286AE6
	.string "FANS: The TRAINER's nifty style of\n"
	.string "decorating a SECRET BASE!$"

gTVTrainerFanClubText10:: @ 08286B23
	.string "FANS: The TRAINER's bold ways of\n"
	.string "using TMs!$"

gTVTrainerFanClubText11:: @ 08286B4F
	.string "MC: As you've just seen, {STR_VAR_1}\n"
	.string "is hot! Like, too hot to touch, yow!\p"
	.string "Among {STR_VAR_1}'s FANS\n"
	.string "there's a special slogan!\p"
	.string "MC: When I say {STR_VAR_1},\n"
	.string "you say…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: That's right, when someone says,\n"
	.string "“{STR_VAR_1}”…\p"
	.string "Come back with, “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!”\p"
	.string "That has such a unique ring to it!\n"
	.string "I can see why people become FANS\l"
	.string "of {STR_VAR_1}!\p"
	.string "Okay, you, in front of the TV, join us!\n"
	.string "All together now!\p"
	.string "MC: When I say {STR_VAR_1},\n"
	.string "you say…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!\p"
	.string "MC: Thanks for joining us, all you\n"
	.string "wild FANS of {STR_VAR_1}!\l"
	.string "That's the show! See you again!\p"
	.string "MC: When I say {STR_VAR_1},\n"
	.string "you say…\p"
	.string "FANS: {STR_VAR_2}!\p"
	.string "FANS: {STR_VAR_3}!$"

gTVCutiesText00:: @ 08286D8F
	.string "SPOT THE CUTIES!\n"
	.string "POKéMON IN RIBBONS!\p"
	.string "Hello, my sweet viewers!\p"
	.string "I just know you'll agree, but a POKéMON\n"
	.string "wearing RIBBONS is simply divine!\p"
	.string "Today, I want to share with you\n"
	.string "a lovely POKéMON I spotted while\l"
	.string "out on a stroll in town.\p"
	.string "Today's featured pretty POKéMON\n"
	.string "is {STR_VAR_1}'s {STR_VAR_2}.$"

gTVCutiesText01:: @ 08286E9D
	.string "The number of RIBBONS that\n"
	.string "{STR_VAR_2} wears is {STR_VAR_3}.\p"
	.string "It says a lot about how much\n"
	.string "{STR_VAR_1} adores the POKéMON.$"

gTVCutiesText02:: @ 08286EFC
	.string "{STR_VAR_2} wears an amazing\n"
	.string "{STR_VAR_3} RIBBONS!\p"
	.string "It speaks volumes about {STR_VAR_1}'s\n"
	.string "commitment to the POKéMON!$"

gTVCutiesText03:: @ 08286F54
	.string "{STR_VAR_2} wears an incredible\n"
	.string "{STR_VAR_3} RIBBONS!\p"
	.string "It shows you {STR_VAR_1}'s total\n"
	.string "dedication as a collector!$"

gTVCutiesText04:: @ 08286FAA
	.string "Let us take a closer look at the many\n"
	.string "RIBBONS worn by {STR_VAR_2}.$"

gTVCutiesText05:: @ 08286FE4
	.string "The CHAMPION RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it upon entering\n"
	.string "the HALL OF FAME.\p"
	.string "It verily draws out the bravery\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the CHAMP RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText06:: @ 082870A3
	.string "The COOL RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a COOL CONTEST.\p"
	.string "It verily draws out the coolness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the COOL RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText07:: @ 0828715A
	.string "The BEAUTY RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a BEAUTY CONTEST.\p"
	.string "It verily draws out the beauty\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the BEAUTY RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText08:: @ 08287215
	.string "The CUTE RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a CUTE CONTEST.\p"
	.string "It verily draws out the cuteness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the CUTE RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText09:: @ 082872CC
	.string "The SMART RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a SMART CONTEST.\p"
	.string "It verily draws out the smartness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the SMART RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText10:: @ 08287387
	.string "The TOUGH RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for winning\n"
	.string "a TOUGH CONTEST.\p"
	.string "It verily draws out the toughness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the TOUGH RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText11:: @ 08287442
	.string "The WINNING RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for its feats\n"
	.string "at the BATTLE TOWER.\p"
	.string "It verily draws out the mightiness\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the WINNING RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText12:: @ 08287508
	.string "The VICTORY RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for its feats\n"
	.string "at the BATTLE TOWER.\p"
	.string "It verily draws out the incredible\n"
	.string "mightiness of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the VICTORY RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText13:: @ 082875D9
	.string "The ARTIST RIBBON is especially\n"
	.string "fetching.\p"
	.string "{STR_VAR_2} received it for being\n"
	.string "the model for an artist.\p"
	.string "It verily draws out the pop-star charm\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the ARTIST RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText14:: @ 082876A1
	.string "The Hard Worker RIBBON is\n"
	.string "especially fetching.\p"
	.string "{STR_VAR_2} received it for being\n"
	.string "an especially dedicated worker.\p"
	.string "It verily draws out the determination\n"
	.string "of {STR_VAR_2}.\p"
	.string "{STR_VAR_2} and the Hard Worker RIBBON!\n"
	.string "The combination is super effective!$"

gTVCutiesText15:: @ 08287779
	.string "…Sigh…\p"
	.string "RIBBONS and POKéMON…\n"
	.string "They go so wonderfully together!\p"
	.string "Before I swoon,\n"
	.string "I bid you all farewell!$"

gTVPokemonNewsBattleFrontierText00:: @ 082877DE
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We've got some uplifting news from\n"
	.string "the BATTLE FRONTIER.$"

gTVPokemonNewsBattleFrontierText01:: @ 0828783D
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's SINGLE BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02:: @ 082878B3
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's DOUBLE BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03:: @ 08287929
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's MULTI BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04:: @ 0828799E
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE TOWER's LINK MULTI BATTLE\l"
	.string "ROOM challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05:: @ 08287A18
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-championship-streak record\l"
	.string "competing in the BATTLE DOME's\l"
	.string "SINGLE BATTLE Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06:: @ 08287A97
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-championship-streak record\l"
	.string "competing in the BATTLE DOME's\l"
	.string "DOUBLE BATTLE Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07:: @ 08287B16
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE FACTORY's Battle\l"
	.string "Swap Single challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08:: @ 08287B8E
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE FACTORY's Battle\l"
	.string "Swap Double challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09:: @ 08287C06
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "record of clearing {STR_VAR_2} rooms\l"
	.string "while on the BATTLE PIKE's Battle\l"
	.string "Choice challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10:: @ 08287C7D
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while\l"
	.string "competing in the BATTLE ARENA's\l"
	.string "Set KO Tournaments.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11:: @ 08287CF3
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE PALACE's SINGLE BATTLE\l"
	.string "HALL challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12:: @ 08287D6A
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "{STR_VAR_2}-win-streak record while on\l"
	.string "the BATTLE PALACE's DOUBLE BATTLE\l"
	.string "HALL challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13:: @ 08287DE1
	.string "The TRAINER {STR_VAR_1} set a new\n"
	.string "record of clearing {STR_VAR_2} floors\l"
	.string "while on the BATTLE PYRAMID's\l"
	.string "Battle Quest challenge.\p"
	.string "Here's to {STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14:: @ 08287E5B
	.string "And to the three POKéMON, {STR_VAR_1},\n"
	.string "{STR_VAR_2}, and {STR_VAR_3}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText15:: @ 08287EBB
	.string "And to the two POKéMON, {STR_VAR_1}\n"
	.string "and {STR_VAR_2}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText16:: @ 08287F14
	.string "And to the four POKéMON: {STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17:: @ 08287F39
	.string "And {STR_VAR_1}!\p"
	.string "Congratulations for your\n"
	.string "record-breaking performance!$"

gTVPokemonNewsBattleFrontierText18:: @ 08287F77
	.string "Let's hope for more record-setting\n"
	.string "feats from {STR_VAR_1} and the loyal\l"
	.string "POKéMON!\p"
	.string "That's the news on POKéMON NEWS!$"

gTVWhatsNo1InHoennTodayText00:: @ 08287FE0
	.string "WHAT'S NO. 1 IN HOENN TODAY?\n"
	.string "Yes, it's that time again!\p"
	.string "Hello, viewers! Are you giving your\n"
	.string "best at whatever you do?\p"
	.string "Let's have a look at the TRAINER\n"
	.string "who did the very best today!\p"
	.string "Today's no. 1 TRAINER is none other\n"
	.string "than {STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01:: @ 082880C0
	.string "In one day, {STR_VAR_1} spun the SLOTS\n"
	.string "at the GAME CORNER {STR_VAR_2} times.\p"
	.string "While playing, {STR_VAR_1} was heard\n"
	.string "murmuring, “For me, the reels don't\l"
	.string "even move…”\l"
	.string "Isn't that interesting?$"

gTVWhatsNo1InHoennTodayText02:: @ 0828815F
	.string "In one day, {STR_VAR_1} played\n"
	.string "the ROULETTE game at the GAME\l"
	.string "CORNER {STR_VAR_2} times.\p"
	.string "While playing, {STR_VAR_1} shouted,\n"
	.string "“Let the balls decide!”\p"
	.string "The TRAINER's eyes were focused and\n"
	.string "the face showed concentration.$"

gTVWhatsNo1InHoennTodayText03:: @ 0828821A
	.string "In one day, {STR_VAR_1} battled\n"
	.string "wild POKéMON {STR_VAR_2} times!\p"
	.string "Apparently, {STR_VAR_1}'s POKéMON\n"
	.string "have grown incomparably stronger.\p"
	.string "They appear eager to battle anywhere,\n"
	.string "anytime, and anyhow!$"

gTVWhatsNo1InHoennTodayText04:: @ 082882BE
	.string "In just one day, {STR_VAR_1} spun\n"
	.string "the BERRY BLENDER {STR_VAR_2} times!\p"
	.string "Toward the end, even {STR_VAR_1}\n"
	.string "seemed to get dizzy.\p"
	.string "The TRAINER appeared to totter\n"
	.string "around like a SPINDA!$"

gTVWhatsNo1InHoennTodayText05:: @ 08288355
	.string "In just one day, {STR_VAR_1} planted\n"
	.string "{STR_VAR_2} BERRIES!\p"
	.string "As a result, {STR_VAR_1}'s clothes\n"
	.string "became filthy with dirt.\p"
	.string "Where the TRAINER planted, countless\n"
	.string "flowers have burst into bloom.\p"
	.string "The flowers are said to soothe\n"
	.string "the emotions of people.$"

gTVWhatsNo1InHoennTodayText06:: @ 0828842B
	.string "In just one day, {STR_VAR_1} picked\n"
	.string "{STR_VAR_2} BERRIES!\p"
	.string "{STR_VAR_1}'s BAG became so filled\n"
	.string "with BERRIES, the TRAINER had trouble\l"
	.string "walking afterward!$"

gTVWhatsNo1InHoennTodayText07:: @ 082884A5
	.string "In just one day, {STR_VAR_1} obtained\n"
	.string "{STR_VAR_2} Battle Points!\p"
	.string "{STR_VAR_1} was later seen wrestling\n"
	.string "with the choice of exchanging\l"
	.string "the Battle Points for a cool item or\l"
	.string "a nifty interior decoration.\p"
	.string "The TRAINER reportedly was grinning\n"
	.string "while mulling options.$"

gTVWhatsNo1InHoennTodayText08:: @ 0828858B
	.string "Well, isn't that something!\p"
	.string "{STR_VAR_1}!\n"
	.string "You're today's no. 1 TRAINER!\p"
	.string "Viewers, take heart from {STR_VAR_1}!\n"
	.string "You, too, can be no. 1 every day!$"

TVSecretBaseSecrets_Text_Intro:: @ 08288608
	.string "SECRET BASE SECRETS!\p"
	.string "What do TRAINERS do in the secrecy\n"
	.string "of SECRET BASES?\p"
	.string "Today, we investigate {STR_VAR_1}'s\n"
	.string "SECRET BASE.\p"
	.string "Oh? It looks like {STR_VAR_2} has come\n"
	.string "for a visit.\p"
	.string "Let's have a peek!\p"
	.string "What will {STR_VAR_2} do?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1:: @ 082886C8
	.string "What will {STR_VAR_2} do next?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2:: @ 082886DE
	.string "And now, what will {STR_VAR_2} do?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving:: @ 082886F8
	.string "In the end, {STR_VAR_2} took {STR_VAR_3} steps\n"
	.string "in {STR_VAR_1}'s SECRET BASE before\l"
	.string "leaving.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer:: @ 08288739
	.string "Hmm…\p"
	.string "It appears as if {STR_VAR_1}'s SECRET\n"
	.string "BASE failed to interest {STR_VAR_2}…$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase:: @ 08288777
	.string "{STR_VAR_2} appears to have enjoyed\n"
	.string "{STR_VAR_1}'s SECRET BASE thoroughly.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase:: @ 082887AF
	.string "{STR_VAR_2} appears to have become\n"
	.string "a huge fan of {STR_VAR_1}'s\l"
	.string "SECRET BASE.$"

TVSecretBaseSecrets_Text_Outro:: @ 082887E9
	.string "Viewers may want to check out\n"
	.string "{STR_VAR_1}'s SECRET BASE, too.\p"
	.string "Tune in next time as we visit another\n"
	.string "SECRET BASE! Thanks for joining us!$"

TVSecretBaseSecrets_Text_StoppedMoving1:: @ 08288868
	.string "The visitor has stopped!\p"
	.string "The visitor isn't moving at all!\p"
	.string "Was {STR_VAR_1}'s SECRET BASE\n"
	.string "that unimpressive?$"

TVSecretBaseSecrets_Text_StoppedMoving2:: @ 082888CA
	.string "The visitor has stopped!\p"
	.string "The visitor isn't moving at all!\p"
	.string "Is it fatigue?\n"
	.string "Has the visitor grown weary?$"

TVSecretBaseSecrets_Text_UsedChair:: @ 08288930
	.string "The visitor sat down on a chair!\n"
	.string "The visitor is seated!\p"
	.string "Look at that look of delight!\p"
	.string "That chair must be very comfortable\n"
	.string "to get that response!$"

TVSecretBaseSecrets_Text_UsedBalloon:: @ 082889C0
	.string "The visitor charged at a balloon!\p"
	.string "It burst!\n"
	.string "Oh, my goodness, it popped!\p"
	.string "The visitor appears startled by\n"
	.string "the sudden noise!$"

TVSecretBaseSecrets_Text_UsedTent:: @ 08288A3A
	.string "The visitor entered a TENT!\p"
	.string "The visitor is running around!\p"
	.string "Oh, my, the visitor is frolicking!\p"
	.string "The visitor appears surprised by\n"
	.string "the TENT's size!$"

TVSecretBaseSecrets_Text_UsedPlant:: @ 08288ACA
	.string "The visitor is examining\n"
	.string "a potted plant!\p"
	.string "The visitor has surprisingly\n"
	.string "mature taste!$"

TVSecretBaseSecrets_Text_UsedGoldShield:: @ 08288B1E
	.string "The visitor is examining\n"
	.string "a GOLD SHIELD!\p"
	.string "The visitor's eyes appear to be\n"
	.string "lit up with wonder!$"

TVSecretBaseSecrets_Text_UsedSilverShield:: @ 08288B7A
	.string "The visitor is examining\n"
	.string "a SILVER SHIELD!\p"
	.string "The visitor appears to be wide-eyed!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament:: @ 08288BC9
	.string "The visitor is examining\n"
	.string "a GLASS ORNAMENT!\p"
	.string "Oh, no!\p"
	.string "The visitor is touching it!\p"
	.string "It's getting covered with\n"
	.string "fingerprints…$"

TVSecretBaseSecrets_Text_UsedTV:: @ 08288C40
	.string "The visitor is watching television!\p"
	.string "Looks like we have a big fan of TV!$"

TVSecretBaseSecrets_Text_UsedMudBall:: @ 08288C88
	.string "The visitor stomped on a MUD BALL!\p"
	.string "The visitor looks delighted!$"

TVSecretBaseSecrets_Text_UsedBag:: @ 08288CC8
	.string "…Oh?\p"
	.string "The visitor is reaching for their own\n"
	.string "BAG and rummaging about in it!\p"
	.string "The visitor pulled out\n"
	.string "one {STR_VAR_2}!\p"
	.string "Look at the visitor smile while\n"
	.string "holding up the {STR_VAR_2}!\p"
	.string "It's like a TV commercial!$"

TVSecretBaseSecrets_Text_UsedCushion:: @ 08288D7F
	.string "The visitor grabs a cushion and…$"

TVSecretBaseSecrets_Text_HitCushion:: @ 08288DA0
	.string "…begins hitting it!\p"
	.string "Is the visitor under a lot of stress?$"

TVSecretBaseSecrets_Text_HuggedCushion:: @ 08288DDA
	.string "…hugs it tight!\p"
	.string "Could the visitor be feeling happy\n"
	.string "about something?$"

TVSecretBaseSecrets_Text_BattledWon:: @ 08288E1E
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "It's the visitor!\n"
	.string "The visitor won an away match!\p"
	.string "The visitor is doing\n"
	.string "a victory dance!$"

TVSecretBaseSecrets_Text_BattledLost:: @ 08288EC9
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "It's {STR_VAR_1}!\n"
	.string "The visitor has lost!\p"
	.string "The visitor looks dejected!$"

TVSecretBaseSecrets_Text_DeclinedBattle:: @ 08288F58
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "No, the visitor has refused!\p"
	.string "There won't be a battle after all!\p"
	.string "Did the visitor find {STR_VAR_1}\n"
	.string "unappealing?$"

TVSecretBaseSecrets_Text_UsedPoster:: @ 08289011
	.string "The visitor is staring intently\n"
	.string "at a poster!\p"
	.string "Is the poster to the visitor's\n"
	.string "liking?\p"
	.string "…But… There's something disturbing\n"
	.string "about the visitor's stares.$"

TVSecretBaseSecrets_Text_UsedNoteMat:: @ 082890A4
	.string "The visitor stepped on a NOTE MAT!\p"
	.string "…Hmm…\n"
	.string "The visitor composed a funny tune!$"

TVSecretBaseSecrets_Text_BattledDraw:: @ 082890F0
	.string "The visitor is chatting with\n"
	.string "{STR_VAR_1}!\p"
	.string "It looks like they're going to\n"
	.string "have a battle!\p"
	.string "And…\p"
	.string "It's a draw!\n"
	.string "Nothing's resolved!\p"
	.string "Both TRAINERS appear to be very\n"
	.string "disappointed!$"

TVSecretBaseSecrets_Text_UsedSpinMat:: @ 08289193
	.string "The visitor stepped on\n"
	.string "a SPIN MAT!\p"
	.string "It looks like the visitor is dizzy!\p"
	.string "The visitor is tottering about!\n"
	.string "Look out!$"

TVSecretBaseSecrets_Text_UsedSandOrnament:: @ 08289204
	.string "The visitor is reaching for\n"
	.string "a SAND ORNAMENT!\p"
	.string "Oh!\p"
	.string "It crumbled!\n"
	.string "It's fallen apart!\p"
	.string "The visitor looks sheepish\n"
	.string "and guilty!$"

TVSecretBaseSecrets_Text_UsedDesk:: @ 0828927C
	.string "The visitor is rubbing a desktop\n"
	.string "with their finger!\p"
	.string "Apparently, the visitor disapproves\n"
	.string "of dust!\p"
	.string "The visitor is surprisingly concerned\n"
	.string "about neatness!$"

TVSecretBaseSecrets_Text_UsedBrick:: @ 08289313
	.string "The visitor is staring at a BRICK!\p"
	.string "Perhaps the visitor is thinking about\n"
	.string "the object on the BRICK.$"

TVSecretBaseSecrets_Text_UsedSolidBoard:: @ 08289375
	.string "The visitor is walking across\n"
	.string "the SOLID BOARD.\p"
	.string "The visitor keeps looking down.\p"
	.string "The visitor appears to be surprisingly\n"
	.string "timid and cautious!$"

TVSecretBaseSecrets_Text_UsedFence:: @ 082893FF
	.string "The visitor is looking intently\n"
	.string "at a FENCE!\p"
	.string "Has a new idea for a trap popped\n"
	.string "into the visitor's head?$"

TVSecretBaseSecrets_Text_UsedGlitterMat:: @ 08289465
	.string "The visitor stepped on\n"
	.string "a GLITTER MAT!\p"
	.string "The visitor is striking a variety\n"
	.string "of poses!\p"
	.string "The visitor appears to be fantasizing\n"
	.string "about being an idol!$"

TVSecretBaseSecrets_Text_UsedTire:: @ 082894F2
	.string "The visitor is staring intently\n"
	.string "at a TIRE!\p"
	.string "Could the visitor be thinking about\n"
	.string "the kind of car that would use it?$"

TVSecretBaseSecrets_Text_UsedStand:: @ 08289564
	.string "The visitor climbed a STAND!\p"
	.string "The visitor is looking out across\n"
	.string "{STR_VAR_1}'s BASE from high up!\p"
	.string "And…\p"
	.string "Lets loose a roar!\n"
	.string "The visitor is roaring!$"

TVSecretBaseSecrets_Text_BrokeDoor:: @ 082895EB
	.string "The visitor charged headlong into\n"
	.string "a BREAKABLE DOOR!\p"
	.string "The visitor is laughing uproariously!$"

TVSecretBaseSecrets_Text_UsedDoll:: @ 08289645
	.string "The visitor is talking to a DOLL!\p"
	.string "…It's a little creepy…$"

TVSecretBaseSecrets_Text_UsedSlide:: @ 0828967E
	.string "The visitor is climbing the ladder\n"
	.string "on a SLIDE!\p"
	.string "And…\p"
	.string "The visitor slid down!\p"
	.string "Looks like the visitor is having\n"
	.string "a grand old time!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown:: @ 082896FC
	.string "The visitor is climbing the ladder\n"
	.string "on a SLIDE!\p"
	.string "And…\p"
	.string "The visitor went back down\n"
	.string "the ladder!\p"
	.string "Did the visitor suddenly chicken out?$"

TVSecretBaseSecrets_Text_UsedJumpMat:: @ 0828977D
	.string "The visitor stepped on\n"
	.string "a JUMP MAT!\p"
	.string "The visitor jumped once!\p"
	.string "Jumped twice!\p"
	.string "And a successful landing!\p"
	.string "The visitor is clapping!\n"
	.string "What a solo performance!$"

gTVSafariFanClubText00:: @ 08289813
	.string "SAFARI FAN CLUB!\p"
	.string "REPORTER: All right, mates!\n"
	.string "Tossing them SAFARI BALLS, are you?\p"
	.string "You can bet I am here in the SAFARI\n"
	.string "ZONE chock-full of amazing POKéMON!\p"
	.string "Let's get with it and have a chat with\n"
	.string "this good fellow of a SAFARI GUIDE!\p"
	.string "All right, mate, how are the visiting\n"
	.string "TRAINERS looking?$"

gTVSafariFanClubText01:: @ 0828992F
	.string "GUIDE: Everyone seems to be going\n"
	.string "hard at it.\p"
	.string "{STR_VAR_1} is doing especially well.\p"
	.string "Why, before, {STR_VAR_1} caught\n"
	.string "{STR_VAR_2} POKéMON.$"

gTVSafariFanClubText02:: @ 0828999D
	.string "The TRAINER is clever with {POKEBLOCK}S.\n"
	.string "Used {STR_VAR_2} that time, I think.$"

gTVSafariFanClubText03:: @ 082899DC
	.string "The TRAINER didn't use a single\n"
	.string "{POKEBLOCK}! Not a one!\p"
	.string "There's an expert for you.$"

gTVSafariFanClubText04:: @ 08289A29
	.string "REPORTER: Is that right, then?\p"
	.string "Sounds like our mate {STR_VAR_1}\n"
	.string "is a stout SAFARI master!\p"
	.string "GUIDE: I hope the TRAINER comes back\n"
	.string "and shows us that great technique.$"

gTVSafariFanClubText05:: @ 08289AC2
	.string "GUIDE: No one seems to be doing\n"
	.string "very well.\p"
	.string "{STR_VAR_1} had it especially bad.\p"
	.string "Why, before, the TRAINER only\n"
	.string "managed to catch {STR_VAR_2} POKéMON.$"

gTVSafariFanClubText06:: @ 08289B42
	.string "GUIDE: No one seems to be doing\n"
	.string "very well.\p"
	.string "{STR_VAR_1} had it especially bad.\p"
	.string "Why, before, the TRAINER didn't\n"
	.string "catch one POKéMON. Not a one!$"

gTVSafariFanClubText07:: @ 08289BC5
	.string "The TRAINER does use {POKEBLOCK}S.\n"
	.string "Used {STR_VAR_2} that time, I think.\p"
	.string "But, boy, I wish the TRAINER would\n"
	.string "get a bit better at this.$"

gTVSafariFanClubText08:: @ 08289C3B
	.string "I think the TRAINER would have better\n"
	.string "luck using {POKEBLOCK}S, which weren't\l"
	.string "used at all that time.$"

gTVSafariFanClubText09:: @ 08289C99
	.string "REPORTER: Is that right, then?\p"
	.string "Sounds like our mate {STR_VAR_1}\n"
	.string "needs more SAFARI seasoning.\p"
	.string "GUIDE: I hope the TRAINER visits\n"
	.string "over and over to get the hang of it.$"

gTVSafariFanClubText10:: @ 08289D33
	.string "REPORTER: Quite right, it is!\n"
	.string "Facing up to challenges is important!\p"
	.string "Viewers, come on down to the SAFARI\n"
	.string "and make the challenge yourself!\p"
	.string "Until next time, cheerio!$"

ContestLiveUpdates_Text_Intro:: @ 08289DD6
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "MC: Thanks for joining us!\p"
	.string "We're live from the just-ended\n"
	.string "{STR_VAR_1} site.\p"
	.string "The hall is still filled with\n"
	.string "an audience unwilling to leave.\p"
	.string "Spectator: {STR_VAR_2}!\p"
	.string "Spectator: {STR_VAR_3}!\p"
	.string "MC: As you've just heard, the CONTEST\n"
	.string "was won by the POKéMON {STR_VAR_2}\l"
	.string "of {STR_VAR_3}.\p"
	.string "Spectator: {STR_VAR_2}!\n"
	.string "You're the best!\p"
	.string "Spectator: {STR_VAR_3}!\n"
	.string "Way to go!\p"
	.string "MC: Let's hear what the fans have\n"
	.string "to say about this CONTEST.$"

ContestLiveUpdates_Text_WonBothRounds:: @ 08289F53
	.string "Spectator: The {STR_VAR_2} was tops in\n"
	.string "both primary and secondary judging!\p"
	.string "That {STR_VAR_2} will keep winning!$"

ContestLiveUpdates_Text_BetterRound2:: @ 08289FB0
	.string "Spectator: The {STR_VAR_2} didn't do\n"
	.string "well in the primary judging, but it\l"
	.string "cleaned up in the secondary judging!\p"
	.string "It was a miraculous comeback\n"
	.string "for that {STR_VAR_2}. Yippee!$"

ContestLiveUpdates_Text_EqualRounds:: @ 0828A047
	.string "Spectator: The {STR_VAR_2} remained\n"
	.string "consistent throughout both primary\l"
	.string "and secondary judging.\p"
	.string "{STR_VAR_3} and the {STR_VAR_2},\n"
	.string "they're no ordinary combo!$"

ContestLiveUpdates_Text_BetterRound1:: @ 0828A0C6
	.string "Spectator: In terms of being {STR_VAR_1},\n"
	.string "that {STR_VAR_2} was outstanding.\p"
	.string "I hope it makes better appeals\n"
	.string "next time, though.$"

ContestLiveUpdates_Text_GotNervous:: @ 0828A132
	.string "Spectator: When the {STR_VAR_2} got\n"
	.string "nervous, I couldn't stop myself from\l"
	.string "shouting encouragement.\p"
	.string "I'd like to say this to that\n"
	.string "{STR_VAR_2}, “Congratulations!”$"

ContestLiveUpdates_Text_StartledFoes:: @ 0828A1BE
	.string "Spectator: That {STR_VAR_2}'s appeal\n"
	.string "startled even me!\p"
	.string "{STR_VAR_2}, you were awesome!$"

ContestLiveUpdates_Text_UsedCombo:: @ 0828A202
	.string "Spectator: That {STR_VAR_2}'s combo\n"
	.string "appeal was stunning!\p"
	.string "It's shaken me to the core!$"

ContestLiveUpdates_Text_ExcitingAppeal:: @ 0828A24E
	.string "Spectator: The winning {STR_VAR_2}'s\n"
	.string "appeal got my heart pounding!$"

ContestLiveUpdates_Text_WasCool:: @ 0828A288
	.string "{STR_VAR_2}!\n"
	.string "You were cool!$"

ContestLiveUpdates_Text_WasBeautiful:: @ 0828A29B
	.string "{STR_VAR_2}!\n"
	.string "You were beautiful!$"

ContestLiveUpdates_Text_WasCute:: @ 0828A2B3
	.string "{STR_VAR_2}!\n"
	.string "You were cute!$"

ContestLiveUpdates_Text_WasSmart:: @ 0828A2C6
	.string "{STR_VAR_2}!\n"
	.string "You were smart!$"

ContestLiveUpdates_Text_WasTough:: @ 0828A2DA
	.string "{STR_VAR_2}!\n"
	.string "You were tough!$"

ContestLiveUpdates_Text_VeryExcitingAppeal:: @ 0828A2EE
	.string "Spectator: The winning {STR_VAR_2}'s\n"
	.string "appeal still has my heart pounding!$"

ContestLiveUpdates_Text_VeryCool:: @ 0828A32E
	.string "{STR_VAR_2}!\n"
	.string "You're the last word in cool!$"

ContestLiveUpdates_Text_VeryBeautiful:: @ 0828A350
	.string "{STR_VAR_2}!\n"
	.string "You're the most beautiful!$"

ContestLiveUpdates_Text_VeryCute:: @ 0828A36F
	.string "{STR_VAR_2}!\n"
	.string "You're simply the cutest!$"

ContestLiveUpdates_Text_VerySmart:: @ 0828A38D
	.string "{STR_VAR_2}!\n"
	.string "You're the smartest among the smart!$"

ContestLiveUpdates_Text_VeryTough:: @ 0828A3B6
	.string "{STR_VAR_2}!\n"
	.string "You're the toughest of the tough!$"

ContestLiveUpdates_Text_TookBreak:: @ 0828A3DC
	.string "Spectator: Even when the {STR_VAR_2}\n"
	.string "took a break from making appeals,\l"
	.string "I couldn't take my eyes off it.\p"
	.string "I'm captivated by that {STR_VAR_2}.$"

ContestLiveUpdates_Text_GotStartled:: @ 0828A455
	.string "Spectator: When the {STR_VAR_2} was\n"
	.string "startled by another POKéMON's appeal,\l"
	.string "I was close to tears.\p"
	.string "{STR_VAR_2}, you were resilient!\n"
	.string "Way to go!$"

ContestLiveUpdates_Text_MoveWonderful:: @ 0828A4CF
	.string "Spectator: Oh…\n"
	.string "That {STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "{STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "{STR_VAR_2}'s {STR_VAR_3}!\l"
	.string "How could it be so wonderful?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon:: @ 0828A51C
	.string "MC: Well, there you have it. This place\n"
	.string "is full of the {STR_VAR_1}'s fans!\p"
	.string "I should also mention that another\n"
	.string "POKéMON, {STR_VAR_2}'s {STR_VAR_3}, \l"
	.string "caught my eye.\p"
	.string "{STR_VAR_2}'s {STR_VAR_3}…$"

ContestLiveUpdates_Text_FailedToAppeal:: @ 0828A5AC
	.string "It failed to make a single appeal during\n"
	.string "secondary judging out of nervousness.\p"
	.string "Next time, I would like to see this\n"
	.string "{STR_VAR_1} make even one appeal.$"

ContestLiveUpdates_Text_LastInBothRounds:: @ 0828A638
	.string "It came dead last in both primary\n"
	.string "and secondary judging.\p"
	.string "I hope that {STR_VAR_1} will retrain this\n"
	.string "{STR_VAR_2} and erase the shame of\l"
	.string "this undisputed last-place finish.$"

ContestLiveUpdates_Text_NotExcitingEnough:: @ 0828A6CF
	.string "It failed to take advantage of\n"
	.string "the audience's excitement and make\l"
	.string "an appropriate appeal.\p"
	.string "We hope {STR_VAR_1} will learn how to get\n"
	.string "a feel for the audience and whip their\l"
	.string "excitement to a fever pitch next time.$"

ContestLiveUpdates_Text_LostAfterWinningRound1:: @ 0828A797
	.string "While finishing first in the primary\n"
	.string "judging, its appeals in the secondary\l"
	.string "judging failed to click.\p"
	.string "It suffered a humiliating come-from-\n"
	.string "behind loss.\p"
	.string "I'm sure {STR_VAR_1} is studying how to\n"
	.string "make more effective appeals now.$"

ContestLiveUpdates_Text_NeverExciting:: @ 0828A86D
	.string "The audience never got excited by its\n"
	.string "appeals during the secondary judging.\p"
	.string "We hope it will stop worrying about\n"
	.string "other POKéMON and learn to pitch\l"
	.string "its appeals to the audience more.$"

ContestLiveUpdates_Text_LostBySmallMargin:: @ 0828A920
	.string "It lost to {STR_VAR_1}'s {STR_VAR_2}\n"
	.string "by only a small margin.\p"
	.string "It must be heartbreaking to come\n"
	.string "so close to victory only to fail.\p"
	.string "I wouldn't be surprised if {STR_VAR_3}\n"
	.string "were weeping over this outcome.$"

ContestLiveUpdates_Text_RepeatedAppeals:: @ 0828A9CC
	.string "It disappointed the JUDGE by\n"
	.string "repeating the same appeals.\p"
	.string "It's an unforgivable error in any\n"
	.string "CONTEST, and the POKéMON paid.\p"
	.string "{STR_VAR_1} should feel guilty for\n"
	.string "this sorry showing.$"

ContestLiveUpdates_Text_ValiantEffortButLost:: @ 0828AA74
	.string "{STR_VAR_1} turned in a valiant effort,\n"
	.string "but…\p"
	.string "It was all for naught, finishing last.\p"
	.string "{STR_VAR_1} should learn from this loss\n"
	.string "and put the knowledge to good use.$"

ContestLiveUpdates_Text_Outro:: @ 0828AB01
	.string "I'd like to end this program with our\n"
	.string "usual farewell to the winners.\p"
	.string "This time, it's {STR_VAR_1} and\n"
	.string "the {STR_VAR_2}!\p"
	.string "MC: Is everyone ready?\n"
	.string "All together now!\p"
	.string "Audience: {STR_VAR_1}! {STR_VAR_2}!\n"
	.string "Congratulations!\l"
	.string "You're the CONTEST winner!$"

gTVPokemonBattleUpdateText00:: @ 0828ABCC
	.string "“POKéMON BATTLE UPDATE!”\p"
	.string "Bringing you the results of POKéMON\n"
	.string "battles as they come in!$"

gTVPokemonBattleUpdateText01:: @ 0828AC22
	.string "The TRAINERS {STR_VAR_1} and\n"
	.string "{STR_VAR_2} faced each other in\l"
	.string "a {STR_VAR_3} BATTLE.\p"
	.string "This match ended in victory for\n"
	.string "{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02:: @ 0828AC7E
	.string "In the battle, {STR_VAR_1}'s\n"
	.string "{STR_VAR_2} was a formidable force\l"
	.string "using {STR_VAR_3}!$"

gTVPokemonBattleUpdateText03:: @ 0828ACB6
	.string "{STR_VAR_1}'s {STR_VAR_2} had a weak\n"
	.string "showing that really hurt.$"

gTVPokemonBattleUpdateText04:: @ 0828ACE3
	.string "Congratulations on your victory,\n"
	.string "{STR_VAR_1}!\p"
	.string "And for the defeated {STR_VAR_2},\n"
	.string "we hope for a better result next time!\p"
	.string "This concludes this episode of\n"
	.string "“POKéMON BATTLE UPDATE!”$"

gTVPokemonBattleUpdateText05:: @ 0828AD80
	.string "The teams of TRAINERS {STR_VAR_1} and\n"
	.string "{STR_VAR_2} met in a MULTI BATTLE.\p"
	.string "This match ended in victory for\n"
	.string "{STR_VAR_1}'s team.$"

gTVPokemonBattleUpdateText06:: @ 0828ADE2
	.string "In the battle, the {STR_VAR_2} on\n"
	.string "{STR_VAR_1}'s team was a formidable\l"
	.string "force using {STR_VAR_3}.$"

gTVPokemonBattleUpdateText07:: @ 0828AE26
	.string "The weak showing by the {STR_VAR_3}\n"
	.string "on {STR_VAR_2}'s team really hurt.\p"
	.string "Congratulations on your team's\n"
	.string "victory, {STR_VAR_1}!\p"
	.string "As for the defeated {STR_VAR_2}'s team,\n"
	.string "we hope for a better result next time!\p"
	.string "이상\n"
	.string "“포켓몬 대전 속보!”였습니다$"
	// §うさん チ-ムに とってはｎ
	// §えが ブレ-キ だったのがｌ
	// いたかった ようですｐ
	// しょうりを おさめたｎ
	// §いさん チ-ム!ｌ
	// おめでとう ございました!ｐ
	// やぶれて しまったｎ
	// §うさん チ-ム!ｌ
	// つぎこそ がんばって ください!ｐ
	// いじょうｎ
	// 『ポケモン たいせん そくほう!』 でした

GabbyAndTy_Text_GabbyPreFirstBattle: @ 0828AF05
	.string "마리: 오 이런 곳에서\n"
	.string "강해보이는 트레이너 발견!\p"
	.string "좋-아 카메라 돌리고\n"
	.string "인터뷰 시작이야!$"
	// マリ『おっ こんなところにｎ
	// つよそうな トレ-ナ- はっけん!ｐ
	// よ-し カメラを まわしてｎ
	// インタビュ- かいしよ!

GabbyAndTy_Text_GabbyIntro: @ 0828AF7D
	.string "마리: 아! 당신은\n"
	.string "지난번 배틀했던 {PLAYER}씨!\p"
	.string "좋-아 얼마나 강해졌는지\n"
	.string "바로 인터뷰 시작이야!$"
	// マリ『あ! あなたはｎ
	// このあいだの §あさん!ｐ
	// よ-し どのくらい つよく なったかｎ
	// さっそく インタビュ- かいしよ!

GabbyAndTy_Text_GabbyDefeatFirstTime: @ 0828B000
	.string "마리: 내 눈은 틀리지 않았어\n"
	.string "엄청난 트레이너를 발견한 거야!$"
	// マリ『わたしの めに くるいはないわｎ
	// すごい トレ-ナ-の はっけんよ!

GabbyAndTy_Text_WhoAreYouInterview: @ 0828B042
	.string "마리: 굉장해! 정말 굉장해!\n"
	.string "당신 대체 뭐 하는 사람이야?!\p"
	.string "역시 우리가\n"
	.string "눈독들일 만해!\p"
	.string "...앗 사실 우린\n"
	.string "다양한 장소의 다양한 트레이너를\l"
	.string "인터뷰하면서 돌아다니고 있거든\p"
	.string "그러니까 잠깐만\n"
	.string "인터뷰에 응해줄 수 있을까?$"
	// マリ『すごい! すごい!ｎ
	// あなた いったい なにもの!?ｐ
	// さすが わたしたちがｎ
	// めを つけただけ あるわ!ｐ
	// ……あっ じつは わたしたちｎ
	// いろんな ばしょの いろんな トレ-ナ-をｌ
	// インタビュ-して まわっているのよｐ
	// だから すこしだけｎ
	// インタビュ- させて もらえないかな?

GabbyAndTy_Text_QuoteFromLastInterview: @ 0828B137
	.string "마리: “{STR_VAR_1}!”\p"
	.string "기억나? 전에 배틀했을 때\n"
	.string "당신이 말한 마무리 대사야\p"
	.string "우린 제대로\n"
	.string "기억하고 있다고!$"
	// マリ『「§い!」ｐ
	// おぼえてる? まえに たたかった ときｎ
	// あなたが いった きめゼリフよｐ
	// わたしたち ちゃ-んとｎ
	// おぼえてるん だからね!

GabbyAndTy_Text_YouStompedUsInterviewAgain: @ 0828B1B3
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "손도 발도 못 썼었지...\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	// そうそう まえに たたかった ときはｎ
	// ても あしも でなかった のよねぇ……ｐ
	// ところで どう?ｎ
	// また インタビュ- うけてみる?

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain: @ 0828B23D
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "우리한테 몬스터볼을 던졌었지...\p"
	.string "정말 깜짝 놀라서 다른 사람들한테\n"
	.string "떠들고 다녔다니까!\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	// そうそう まえに たたかった ときはｎ
	// ボ-ルを なげられ たんだっけ……ｐ
	// もう びっくりして みんなにｎ
	// いいふらし ちゃったわよ!ｐ
	// ところで どう?ｎ
	// また インタビュ- うけてみる?

GabbyAndTy_Text_CleverItemSkillsInterviewAgain: @ 0828B2FA
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "도구를 잘 써서\l"
	.string "우리를 이겼었지\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	// そうそう まえに たたかった ときはｎ
	// どうぐを うまく つかわれてｌ
	// まけちゃった のよねｐ
	// ところで どう?ｎ
	// また インタビュ- うけてみる?

GabbyAndTy_Text_WeLookedRespectableInterviewAgain: @ 0828B379
	.string "맞아 맞아 전에 배틀했을 때는\n"
	.string "제법 좋은 승부를 했었지...\p"
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	// そうそう まえに たたかった ときはｎ
	// けっこう いいしょうぶ だったんだよね……ｐ
	// ところで どう?ｎ
	// また インタビュ- うけてみる?

GabbyAndTy_Text_InterviewAgain: @ 0828B3F3
	.string "그래서 어때?\n"
	.string "또 인터뷰 받아볼래?$"
	// ところで どう?ｎ
	// また インタビュ- うけてみる?

GabbyAndTy_Text_DescribeYourFeelings: @ 0828B433
	.string "정말?!\n"
	.string "고마워!\p"
	.string "그럼 배틀한 뒤의\n"
	.string "감상을 팍 하고 한마디로\l"
	.string "말해줘!$"
	// ほんと!?ｎ
	// ありがとう!ｐ
	// じゃあ たたかいの あとのｎ
	// かんそうを ビシッと ひとことでｌ
	// どうぞ!

GabbyAndTy_Text_PerfectWellBeSeeingYou: @ 0828B4AB
	.string "마리: 음-!\n"
	.string "최고의 마무리 대사야\p"
	.string "왠지 좋은 TV 방송이\n"
	.string "될 것 같은 예감이 들어!\p"
	.string "어쩌면 이 인터뷰를\n"
	.string "TV로 방송하게 될지도 모르니까\l"
	.string "TV 체크하는 거 잊지 마!\p"
	.string "그럼\n"
	.string "또 어딘가에서 보자!$"
	// マリ『ん-!ｎ
	// さいこうの きめゼリフねｐ
	// なんか いいテレビばんぐみがｎ
	// できそうな よかん!ｐ
	// もしかしたら このことをｎ
	// テレビで ほうそうするかも しれないからｌ
	// テレビの チェックを わすれないでね!ｐ
	// それじゃあｎ
	// また どこかで!

GabbyAndTy_Text_DontGiveUpKeepingEyeOut: @ 0828B577
	.string "마리: 그래...\p"
	.string "그래도 앞으로도 힘내!\n"
	.string "당신을 주목하고 있을 거야!$"
	// マリ『そう……ｐ
	// でも これからも がんばってね!ｎ
	// あなたのこと ちゅうもく してるわ!

GabbyAndTy_Text_KeepingAnEyeOutForYou: @ 0828B5C0
	.string "마리: 당신을\n"
	.string "주목하고 있을 거야!$"
	// マリ『あなたの ことｎ
	// ちゅうもく してるわ!

GabbyAndTy_Text_GabbyNotEnoughMons: @ 0828B5EC
	.string "마리: 포켓몬을 잔뜩 데리고 있는\n"
	.string "강한 트레이너 어디 없을까?$"
	// マリ『ポケモンを いっぱい つれてるｎ
	// つよい トレ-ナ-って いない かしら?

GabbyAndTy_Text_GiveUsAnInterviewThisTime: @ 0828B62D
	.string "마리: 음- 역시나!\p"
	.string "전에 배틀했을 때보다\n"
	.string "훨씬 강해졌어!\p"
	.string "역시 우리가 찾아낸\n"
	.string "트레이너야!\p"
	.string "그래서 어때?\n"
	.string "이번에야말로 인터뷰를\l"
	.string "받아보지 않을래?$"
	// マリ『う-ん さすがね!ｐ
	// まえに たたかった ときよりｎ
	// ずっと つよく なってる!ｐ
	// やっぱり わたしたちが みつけたｎ
	// トレ-ナ- よね!ｐ
	// ところで どう?ｎ
	// こんどこそ インタビュ-をｌ
	// うけて もらえないかな?

GabbyAndTy_Text_GabbyDefeat: @ 0828B719
	.string "마리: 굉장한 배틀이었어!\n"
	.string "이봐 제대로 카메라에 담았지?!$"
	// マリ『すごい たたかいだったわ!ｎ
	// ほら ちゃんと カメラにとった!?

GabbyAndTy_Text_TyPreFirstBattle: @ 0828B75C
	.string "다이: 오 이런 곳에서\n"
	.string "강해보이는 트레이너 발견!\l"
	.string "바로 녹화 개시다!$"
	// ダイ『おっ こんなところにｎ
	// つよそうな トレ-ナ- はっけん!ｌ
	// さっそく ろくが かいしだ!

GabbyAndTy_Text_TyIntro: @ 0828B7B1
	.string "다이: 넌 지난번의 그 애잖아!\p"
	.string "좋-아 이 배틀을\n"
	.string "모두 카메라에 담아주겠어$"
	// ダイ『きみは このあいだの!ｐ
	// よ-し この たたかいをｎ
	// すべて カメラに おさめてやる

GabbyAndTy_Text_TyPostBattle: @ 0828B805
	.string "다이: 역시나!\n"
	.string "좋은 영상을 얻을 수 있었어!$"
	// ダイ『さすがだな!ｎ
	// いい えいぞうを とることが できたよ!

GabbyAndTy_Text_TyNotEnoughMons: @ 0828B841
	.string "다이: 넌 1마리밖에 포켓몬을\n"
	.string "안 데리고 다니는 거야?\p"
	.string "포켓몬이 잔뜩 있어야\n"
	.string "좋은 영상이 나올 텐데...$"
	// ダイ『きみは 1ぴきしか ポケモンをｎ
	// もって ないのかい?ｐ
	// ポケモンが いっぱい いたほうがｎ
	// いい えいぞうに なるんだが……

GabbyAndTy_Text_TyDefeatFirstTime: @ 0828B8B1
	.string "다이: 굉장한 트레이너를 발견했어\n"
	.string "이건 대특종이야!$"
	// ダイ『すごい トレ-ナ-の はっけんだｎ
	// これは だいスク-プだぞ!

GabbyAndTy_Text_TyDefeat: @ 0828B8F6
	.string "다이: 지금 한 배틀의 모든 게\n"
	.string "이 카메라에 담겨 있어!$"
	// ダイ『いまの たたかいの すべてがｎ
	// この カメラのなかに!

gTVInSearchOfTrainersText00:: @ 0828B92C
	.string "IN SEARCH OF TRAINERS…\p"
	.string "GABBY: Hi! Today I'm visiting an area\n"
	.string "near {STR_VAR_1}.\p"
	.string "We're trying to spot some up-and-\n"
	.string "coming new talent in the field.\p"
	.string "Today, we turned our lens on the\n"
	.string "TRAINER {PLAYER}.\p"
	.string "There's something about this TRAINER\n"
	.string "that piqued our interest.$"
	// 『トレ-ナ-を もとめて』ｐ
	// マリ『は-い わたしは いまｎ
	// §いに きています!ｐ
	// きょうは ここで あたらしい さいのうをｎ
	// はっくつ しようと おもいます!ｐ
	// きょう わたしが ちゅうもく したｎ
	// トレ-ナ-は §あさん!ｐ
	// わたしは この トレ-ナ-にｎ
	// なにかを かんじます!

gTVInSearchOfTrainersText01:: @ 0828BA20
	.string "We've battled {PLAYER} before, but we\n"
	.string "can attest that the TRAINER has most\l"
	.string "definitely improved from before.\p"
	.string "I knew we were onto someone special\n"
	.string "when we spotted this TRAINER!$"

gTVInSearchOfTrainersText02:: @ 0828BAC8
	.string "The best way to determine how strong\n"
	.string "a TRAINER is…\p"
	.string "Well, the fastest way is to battle.\n"
	.string "And so we began our investigation!\p"
	.string "… …\p"
	.string "That's how we ended up in battle\n"
	.string "with {PLAYER}.\p"
	.string "In a dominating performance, we were\n"
	.string "flattened, rolled up, and tossed aside!\p"
	.string "{PLAYER} is ruthlessly strong…\p"
	.string "Here's our impressions after having\n"
	.string "battled our featured TRAINER.$"

gTVInSearchOfTrainersText03:: @ 0828BC18
	.string "The combination of {STR_VAR_1} and\n"
	.string "{STR_VAR_3} was divine!\p"
	.string "The sight of them--{STR_VAR_1} and\n"
	.string "{STR_VAR_3}--selflessly supporting\l"
	.string "each other in the thick of battle…\p"
	.string "It was a marvelous sight to behold!\p"
	.string "{STR_VAR_2} was the move the TRAINER\n"
	.string "used last in our battle.\p"
	.string "The move {STR_VAR_2} is {STR_VAR_1}\n"
	.string "and {STR_VAR_3}'s sign of friendship!$"

gTVInSearchOfTrainersText04:: @ 0828BD20
	.string "…I lost confidence in myself as\n"
	.string "a result of our encounter.\p"
	.string "We were beaten before we could launch\n"
	.string "a single attack.\l"
	.string "Ohhh… Snivel…\p"
	.string "In spite of that, {PLAYER}'s battles\n"
	.string "are worth seeing.\p"
	.string "I recommend confident TRAINERS to\n"
	.string "challenge {PLAYER}.$"

gTVInSearchOfTrainersText05:: @ 0828BE01
	.string "There's only one thing to be said.\n"
	.string "Don't you dare throw a POKé BALL during\l"
	.string "a TRAINER battle!\p"
	.string "{PLAYER} is certainly strong, but has\n"
	.string "no clue about the basic rules.\p"
	.string "To our TV audience, I have a request.\p"
	.string "If you see {PLAYER}, please caution\n"
	.string "the TRAINER!$"

gTVInSearchOfTrainersText06:: @ 0828BEEE
	.string "{PLAYER} is adept at reading the\n"
	.string "opponent's actions.\p"
	.string "The timing of item usage was remarkably\n"
	.string "effective!$"

gTVInSearchOfTrainersText07:: @ 0828BF50
	.string "Honestly speaking, I thought that\n"
	.string "I might even be pretty good.\p"
	.string "While we did end up losing, we did have\n"
	.string "a hotly contested battle.\p"
	.string "But if you're struggling against me,\n"
	.string "you have a ways to go, {PLAYER}!$"

gTVInSearchOfTrainersText08:: @ 0828C011
	.string "After our battle, we asked {PLAYER} for\n"
	.string "a succinct summary.\p"
	.string "The TRAINER replied, “{STR_VAR_1}.”\p"
	.string "{PLAYER}'s POKéMON {STR_VAR_2} and\n"
	.string "{STR_VAR_3}…\l"
	.string "And “{STR_VAR_1}”…\p"
	.string "Mmm! That's deep! There's deep\n"
	.string "significance behind that quote!\p"
	.string "It's no surprise--a good TRAINER has\n"
	.string "good things to say.\p"
	.string "That's all for today!\n"
	.string "See you again on our next broadcast!$"

gTVPokemonContestLiveUpdates2Text00:: @ 0828C137
	.string "“POKéMON CONTEST LIVE UPDATES!”\p"
	.string "MC: Sorry to interrupt the regular\n"
	.string "programming, and thanks for joining us!\p"
	.string "We bring you this live from\n"
	.string "the scene of a just-completed\l"
	.string "{STR_VAR_1}!\p"
	.string "Spectators: ?!!!!\p"
	.string "MC: Oh! It looks like the CONTEST\n"
	.string "participants are headed this way!\p"
	.string "I'll try to get an impromptu interview\n"
	.string "for you folks at home!\p"
	.string "Spectators: ?!!!!\n"
	.string "?!!!!$"

gTVPokemonContestLiveUpdates2Text01:: @ 0828C28C
	.string "MC: Excuse me!\n"
	.string "Thanks for joining us on live TV!\p"
	.string "May I congratulate you on your win?\p"
	.string "What was the key factor in today's\n"
	.string "stunning victory?\p"
	.string "BEAUTY: We gave it our best effort\n"
	.string "today, my {STR_VAR_2} and I!\p"
	.string "But I'm sure we wouldn't have made it\n"
	.string "if it weren't for all the help we\l"
	.string "received leading up to the CONTEST!\p"
	.string "MC: Do you have a special someone\n"
	.string "with whom you'd like to share your joy?\l"
	.string "Let's hear it live!\p"
	.string "BEAUTY: Hey, out there!\p"
	.string "{STR_VAR_3}! Are you watching?\n"
	.string "We did it!\l"
	.string "Thank you!$"

gTVPokemonContestLiveUpdates2Text02:: @ 0828C45B
	.string "MC: Excuse me!\n"
	.string "Thanks for joining us on live TV!\p"
	.string "You must be disappointed by that turn\n"
	.string "of events. Do you have any comments?\p"
	.string "BEAUTY: It's heartbreaking…\n"
	.string "My {STR_VAR_2} and I, we did our best…\p"
	.string "But I feel like I've let down everyone\n"
	.string "who has supported us through this.\p"
	.string "MC: I hate to say it, but the POKéMON's\n"
	.string "coloration is a little wanting.\p"
	.string "BEAUTY: {STR_VAR_3}, I'm so sorry…\n"
	.string "I'll do better next time, I swear…\l"
	.string "…Sniff… Waaaaah!\p"
	.string "Spectators: See that?\n"
	.string "The poor girl!\p"
	.string "MC: Uh… Uh-oh…\p"
	.string "Uh… That's all the time we have today!\n"
	.string "Thanks for tuning in!$"

gTVPokemonContestLiveUpdates2Text03:: @ 0828C662
	.string "MC: Excuse me!\n"
	.string "Thanks for joining us on live TV!\p"
	.string "How did your CONTEST appearance go?\p"
	.string "BEAUTY: Nothing went right…\n"
	.string "For some reason, my {STR_VAR_2}\l"
	.string "couldn't attract any popularity.\p"
	.string "MC: I hate to say it, but the POKéMON's\n"
	.string "coloration is a little wanting.\p"
	.string "BEAUTY: … … … … … …\n"
	.string "…Sniff… Waaaaah!\p"
	.string "Spectators: See that?\n"
	.string "The poor girl!\p"
	.string "MC: Uh… Uh-oh…\p"
	.string "Uh… That's all the time we have today!\n"
	.string "Thanks for tuning in!$"
