VerdanturfTown_House_MapScripts:: @ 820335E
	.byte 0

VerdanturfTown_House_EventScript_Woman1:: @ 820335F
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2:: @ 8203368
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague: @ 8203371
	.string "멀리 떨어진\n"
	.string "그랜드시티의 오지에 있다고 하는\l"
	.string "포켓몬리그\p"
	.string "그곳에 모이는 건\n"
	.string "굉장한 실력의 트레이너들뿐이래!$"

VerdanturfTown_House_Text_DefeatEliteFourInARow: @ 82033EE
	.string "In the POKéMON LEAGUE, I think the\n"
	.string "rules say that you have to battle the\l"
	.string "ELITE FOUR all in a row.\p"
	.string "If you lose to any of them, you have\n"
	.string "to begin your challenge again from the\l"
	.string "first one.$"

