OldaleTown_House1_MapScripts:: @ 81FBE85
	.byte 0

OldaleTown_House1_EventScript_Woman:: @ 81FBE86
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
	end

OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
	.string "포켓몬 승부를 할 때는\n"
	.string "지닌 포켓몬 리스트 왼쪽에 있는\l"
	.string "포켓몬이 나가서 싸워\p"
	.string "그래서 데리고 걷는 포켓몬이 많아졌을 경우\n"
	.string "포켓몬의 순서를 바꿔 놓으면\l"
	.string "승부가 유리해질 수도 있어!$"
	@ ポケモンしょうぶの ときｎ
	@ ポケモンの リストの ひだりに いるｌ
	@ ポケモンが とびだして たたかうのｐ
	@ だから つれあるく ポケモンが ふえてきたらｎ
	@ ポケモンの じゅんばんを かえるとｌ
	@ しょうぶが ゆうりに なるかも!

