@ Note: local IDs shared with scripts.inc for LilycoveCity_ContestLobby
.set LOCALID_MAN, 3
.set LOCALID_BOY, 9
.set LOCALID_TWIN, 10
.set LOCALID_POKEFAN_F, 15
.set LOCALID_EXPERT_M, 16
.set LOCALID_GIRL, 17

.set NUM_OPPONENTS, VAR_0x8009

BerryBlender_Text_WantToMakePokeblocks: @ 8292DEE
	.string "오! 할아버지랑 같이\n"
	.string "포켓몬스넥을 만들고 싶은 거니?$"

BerryBlender_Text_Excellent: @ 8292E28
	.string "그렇구나!$"

BerryBlender_Text_MadeOldTimerSad: @ 8292E33
	.string "그렇구나...\n"
	.string "할아버지 외로워...$"

BerryBlender_Text_KnowHowToMakePokeblocks: @ 8292E57
	.string "그럼 포켓몬스넥을 만드는 방법은\n"
	.string "이미 알고 있니?$"

BerryBlender_Text_LetsBerryBlender: @ 8292E78
	.string "그럼 시작한다!\p"
	.string "렛츠 나무열매블렌더!!$"

BerryBlender_Text_ExplainBerryBlending: @ 8292EA6
	.string "좋아 설명할게!\p"
	.string "뭐 간단해!\p"
	.string "나무열매블렌더의 마크가\n"
	.string "자기 쪽으로 올 때\l"
	.string "버튼을 누르기만 하면 되거든\p"
	.string "뭐 실제로 해보면\n"
	.string "금방 알게 될 거야!$"

BerryBlender_Text_DontHaveAnyBerries: @ 8292F77
	.string "어라?\n"
	.string "근데 나무열매를 안 갖고 있나 보네\p"
	.string "나무열매가 없으면 포켓몬스넥은\n"
	.string "만들 수 없어$"

BerryBlender_Text_CanHaveOneOfMyBerries: @ 8292FD1
	.string "뭐 어쩔 수 없지\p"
	.string "할아버지의 남은 나무열매라도\n"
	.string "괜찮다면 주마!\p"
	.string "이걸로 같이 나무열매블렌더로\n"
	.string "포켓몬스넥을 만들자꾸나$"

BerryBlender_Text_DontHaveAnyBerriesToSpare: @ 829307D
	.string "할아버지한테 남은 나무열매가 있으면\n"
	.string "줄 수 있을 텐데...\p"
	.string "오늘은 더 이상 남아있지 않구먼\n"
	.string "다음에 같이 하자꾸나$"

BerryBlender_Text_PokeblockCaseIsFull: @ 8293101
	.string "하지만 포켓몬스넥케이스가\n"
	.string "가득 찬 것 같구먼\p"
	.string "포켓몬스넥을 줄이고 나서\n"
	.string "다시 오게나$"

BerryBlender_Text_DontHavePokeblockCase: @ 8293157
	.string "하지만 포켓몬스넥케이스를\n"
	.string "아직 갖고 있지 않나 보구나\p"
	.string "포켓몬스넥케이스를\n"
	.string "받고 나서 다시 오렴$"

BerryBlender_Text_LetsGetBlendingAlready: @ 82931AA
	.string "빨리 섞어 보자!!$"
	// はやく まぜようぜ!!

BerryBlender_Text_WhatKindOfPokeblockWillIGet: @ 82931C6
	.string "어떤 포켓몬스넥이 완성될까?\n"
	.string "두근거리네!$"
	// どんな ポロックが できるのかしら?ｎ
	// ドキドキ しちゃう!

BerryBlender_Text_WantToBlendPokeblocksWithUs: @ 8293201
	.string "좋았어! 우리랑 같이\n"
	.string "포켓몬스넥을 만들고 싶은 거구나!$"
	// よっしっ! おにいさん たちと いっしょにｎ
	// ポロックを つくりたいんだね!

BerryBlender_Text_Okay: @ 8293237
	.string "좋았어!$"
	// よっしっ!

BerryBlender_Text_ThatsTooBad: @ 829323D
	.string "아쉽네...\p"
	.string "하지만 우리는\n"
	.string "언제나 너를 기다리고 있단다!$"
	// ざんねんだよ……ｐ
	// でも おにいさん たちはｎ
	// いつでも きみを まってる からね!

BerryBlender_Text_KnowHowToMakePokeblocks2: @ 829328C
	.string "물론 포켓몬스넥을 만드는 방법은\n"
	.string "알고 있겠지?$"
	// もちろん ポロックの つくりかたはｎ
	// しっているよね?

BerryBlender_Text_LetsBerryBlender2: @ 82932C3
	.string "좋았어! 그럼 시작할게!\p"
	.string "렛츠 나무열매블렌더!!$"
	// よっしっ! じゃあ はじめるよ!ｐ
	// レッツ きのみブレンダ-!!

BerryBlender_Text_ExplainBerryBlending2: @ 82932F1
	.string "좋았어!\n"
	.string "형이 설명해 줄게!\p"
	.string "나무열매블렌더의 마크가\n"
	.string "자기가 있는 곳에 오면\l"
	.string "버튼을 누르면 돼!\p"
	.string "엄청\n"
	.string "간단하지?$"
	// よっしっ!ｎ
	// おにいさんが せつめいして あげよう!ｐ
	// きのみブレンダ-の マ-クがｎ
	// じぶんの ところに きたらｌ
	// ボタンを おすんだよ!ｐ
	// とってもｎ
	// かんたんな ことだろう?

BerryBlender_Text_DontHaveAnyBerries2: @ 8293394
	.string "...라고 생각했는데\n"
	.string "넌 나무열매가 없는 모양이구나\p"
	.string "나무열매가 없으면 포켓몬스넥은\n"
	.string "만들 수 없어...\p"
	.string "형네는\n"
	.string "언제나 여기에 있을 테니까\l"
	.string "나무열매를 찾으면 다시 하자!$"
	// ……と おもったらｎ
	// きみ きのみを もっていない みたいだねｐ
	// きのみが ないと ポロックはｎ
	// つくれないんだよ……ｐ
	// おにいさん たちはｎ
	// いつも ここに いるからｌ
	// きのみを みつけたら また やろうね!

BerryBlender_Text_PokeblockCaseIsFull2: @ 829343E
	.string "...라고 생각했는데\n"
	.string "포켓몬스넥케이스가 가득한 모양이구나\p"
	.string "포켓몬스넥을 줄이고 나서\n"
	.string "다시 오렴$"
	// ……と おもったらｎ
	// ポロックケ-スが いっぱいの ようだねｐ
	// ポロックを へらしてからｎ
	// また きてね

BerryBlender_Text_DontHavePokeblockCase2: @ 82934A2
	.string "...라고 생각했는데\n"
	.string "넌 포켓몬스넥케이스를\l"
	.string "갖고 있지 않은 모양이구나\p"
	.string "포켓몬스넥케이스를\n"
	.string "받고 나서 다시 오렴$"
	// ……と おもったらｎ
	// きみ ポロックケ-スをｌ
	// まだ もって ないようだねｐ
	// ポロックケ-スをｎ
	// もらってから また きてね

@ Unused
BerryBlender_Text_MakePokeblocksWithOurGroup: @ 829350B
	.string "어머어머! 아주머니네랑 같이\n"
	.string "포켓몬스넥을 만들고 싶은 거니?$"
	// あらあら! おばさん たちと いっしょにｎ
	// ポロックを つくりたいのかしら?

BerryBlender_Text_OhDear: @ 829354E
	.string "어머어머!$"

BerryBlender_Text_LeftUsInShock: @ 8293558
	.string "어머어머...\p"
	.string "아주머니네는 엄청 쇼크야!$"

BerryBlender_Text_KnowHowToMakePokeblocks3: @ 829357E
	.string "그럼 물론 포켓몬스넥을 만드는 방법은\n"
	.string "알고 있겠지?$"

BerryBlender_Text_LetsBerryBlender3: @ 82935B1
	.string "어머어머!\n"
	.string "그럼 시작할게!\p"
	.string "렛츠 나무열매블렌더!!$"

BerryBlender_Text_ExplainBerryBlending3: @ 82935E5
	.string "어머어머!\p"
	.string "그럼 아주머니가\n"
	.string "친절하게 설명해 줄게!\p"
	.string "나무열매블렌더의 마크가\n"
	.string "자기가 있는 곳에 오면\l"
	.string "버튼을 파박 누르면 돼!\l"
	.string "간단하지-!$"
	// あらあら!ｐ
	// じゃあ おばさんがｎ
	// やさしく せつめいして あげるわね!ｐ
	// きのみブレンダ-の マ-クがｎ
	// じぶんの ところに きたらｌ
	// ボタンを バシッと おすだけで いいのよ!ｌ
	// かんたん ね-!

BerryBlender_Text_DontHaveAnyBerries3: @ 829367D
	.string "너 나무열매가 없구나\p"
	.string "나무열매가 없으면 포켓몬스넥은\n"
	.string "만들 수 없어...\p"
	.string "아주머니네는 언제나 여기서\n"
	.string "포켓몬스넥을 만들고 있을 테니까\l"
	.string "나무열매를 찾으면 다시 하자!$"
	// あなた きのみを もってないわねｐ
	// きのみが ないと ポロックはｎ
	// つくれないのよ……ｐ
	// おばさん たち いつでも ここでｎ
	// ポロックを つくっているからｌ
	// きのみを みつけたら また やろうね!

BerryBlender_Text_PokeblockCaseIsFull3: @ 8293738
	.string "포켓몬스넥케이스가\n"
	.string "가득한 모양이구나\p"
	.string "포켓몬스넥을 줄이고 나서\n"
	.string "다시 오렴$"
	// ポロックケ-スがｎ
	// いっぱいの ようねｐ
	// ポロックを へらしてからｎ
	// また きてね

BerryBlender_Text_DontHavePokeblockCase3: @ 8293792
	.string "포켓몬스넥케이스를\n"
	.string "아직 갖고 있지 않나 보구나\p"
	.string "포켓몬스넥케이스를\n"
	.string "받고 나서 다시 오렴$"
	// ポロックケ-スをｎ
	// まだ もって ないようねｐ
	// ポロックケ-スをｎ
	// もらってから また きてね

BerryBlender_Text_SetNewBlenderRecord: @ 82937F9
	.string "좋았어! 오늘이야말로\n"
	.string "블렌더의 최고 속도를 낼 거야!$"
	// よっしっ! きょうこそｎ
	// ブレンダ-の さいこうそくどを だすぞ!

BerryBlender_Text_LookGoodAtBlendingJoinUs: @ 8293842
	.string "어머어머!\n"
	.string "너 잘 섞는구나!\l"
	.string "같이 하지 않을래?$"
	// あらあら!ｎ
	// あなた まぜるの うまそうね!ｌ
	// いっしょに やらない?

BerryBlender_Text_MakeDeliciousPokeblocks: @ 829388F
	.string "맛있는 포켓몬스넥을 만들어서\n"
	.string "내 포켓몬을\l"
	.string "더 더 귀엽게 만들 거야-$"
	// おいしい ポロックを つくってｎ
	// わたしの ポケモンをｌ
	// もっと もっと かわいく するの-

BerryBlender_Text_SaveGameBeforeBerryBlenderLink: @ 82938CD
	.string "나무열매블렌더로 친구와 함께\n"
	.string "나무열매로 포켓몬스넥을 만듭니다\p"
	.string "통신하기 전에\n"
	.string "리포트를 작성해도 괜찮겠습니까?$"

BerryBlender_Text_SearchingForFriends: @ 8293955
	.string "친구를 찾고 있습니다\n"
	.string "......B 버튼으로 취소$"

BerryBlender_Text_Player1Arrived: @ 8293986
	.string "{STR_VAR_1}님이 왔습니다$"

BerryBlender_Text_Player1And2Arrived: @ 8293992
	.string "{STR_VAR_1}님과 {STR_VAR_2}님이\n"
	.string	"왔습니다$"

BerryBlender_Text_AllPlayersArrived: @ 82939A5
	.string "{STR_VAR_1}님과 {STR_VAR_2}님\n"
	.string "그리고 {STR_VAR_3}님이 왔습니다$"

BerryBlender_Text_NoBerriesLink: @ 82939BD
	.string "나무열매가 없으므로\n"
	.string "나무열매블렌더는 쓸 수 없습니다$"

BerryBlender_Text_PokeblockCaseIsFullLink: @ 82939F3
	.string "포켓몬스넥케이스가 가득하므로\n"
	.string "나무열매블렌더는 쓸 수 없습니다$"

BerryBlender_Text_DontHavePokeblockCaseLink: @ 8293A2D
	.string "포켓몬스넥케이스가 없으므로\n"
	.string "나무열매블렌더는 쓸 수 없습니다$"

BerryBlender_Text_LoveMakingPokeblocks: @ 8293A6B
	.string "나는 포켓몬스넥을\n"
	.string "만드는 게 너무 좋아서\p"
	.string "언제나 나무열매를\n"
	.string "갖고 오지$"

BerryBlender_Text_MakePokeblocksUsingBerryBlender: @ 8293AA5
	.string "만약 괜찮다면\n"
	.string "같이 나무열매블렌더로\l"
	.string "포켓몬스넥을 만들자고$"

BerryBlender_Text_DontHaveAnyBerriesHaveOne: @ 8293AF0
	.string "어라?\n"
	.string "나무열매를 안 가지고 있니?\p"
	.string "뭐 어쩔 수 없지\p"
	.string "아저씨의 남은 나무열매라도\n"
	.string "괜찮다면 줄게!$"

BerryBlender_Text_UseItToMakePokeblocksTogether: @ 8293B76
	.string "이제 같이 나무열매블렌더로\n"
	.string "포켓몬스넥을 만들자!$"

BerryBlender_Text_DontHaveAnyBerriesNoneToSpare: @ 8293BB4
	.string "어라?\n"
	.string "나무열매를 안 가지고 있니?\p"
	.string "아저씨한테 남은 게 있다면\n"
	.string "줄 수 있을 텐데...\p"
	.string "오늘 건 이제 다 썼어\n"
	.string "미안해$"

BerryBlender_EventScript_BerryBlender1:: @ 8293C3E
	lockall
	goto_if_unset FLAG_HIDE_LILYCOVE_CONTEST_HALL_BLEND_MASTER, BerryBlender_EventScript_BlendMasterPresent
	setvar NUM_OPPONENTS, 1
	applymovement LOCALID_EXPERT_M, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToMakePokeblocks, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryUseBerryBlender1
	goto BerryBlender_EventScript_DeclineBlender1
	end

BerryBlender_EventScript_DeclineBlender1: @ 8293C70
	msgbox BerryBlender_Text_MadeOldTimerSad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoBerries: @ 8293C7A
	msgbox BerryBlender_Text_DontHaveAnyBerries, MSGBOX_DEFAULT
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_Blender1NoSpareBerries
	goto BerryBlender_EventScript_Blender1GiveSpareBerry
	end

BerryBlender_EventScript_Blender1NoSpareBerries: @ 8293C92
	msgbox BerryBlender_Text_DontHaveAnyBerriesToSpare, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1GiveSpareBerry: @ 8293C9C
	msgbox BerryBlender_Text_CanHaveOneOfMyBerries, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_UseBerryBlender1: @ 8293CB9
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_StartBlender1
	goto BerryBlender_EventScript_ExplainBlending1
	end

BerryBlender_EventScript_StartBlender1: @ 8293CD2
	msgbox BerryBlender_Text_LetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending1: @ 8293CE0
	msgbox BerryBlender_Text_ExplainBerryBlending, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender1
	end

BerryBlender_EventScript_TryUseBerryBlender1: @ 8293CEE
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender1NoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_Blender1CaseFull
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender1NoBerries
	msgbox BerryBlender_Text_Excellent, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_UseBerryBlender1
	end

BerryBlender_EventScript_DoBerryBlending: @ 8293D2C
	copyvar VAR_0x8004, NUM_OPPONENTS
	fadescreen FADE_TO_BLACK
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_Blender1CaseFull: @ 8293D39
	msgbox BerryBlender_Text_PokeblockCaseIsFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender1NoCase: @ 8293D43
	msgbox BerryBlender_Text_DontHavePokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender2:: @ 8293D4D
	lockall
	setvar NUM_OPPONENTS, 2
	applymovement LOCALID_TWIN, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_MAN, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_WantToBlendPokeblocksWithUs, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryUseBerryBlender2
	goto BerryBlender_EventScript_DeclineBlender2
	end

BerryBlender_EventScript_DeclineBlender2: @ 8293D7D
	msgbox BerryBlender_Text_ThatsTooBad, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoBerries: @ 8293D87
	msgbox BerryBlender_Text_DontHaveAnyBerries2, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender2: @ 8293D91
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks2, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_StartBlender2
	goto BerryBlender_EventScript_ExplainBlending2
	end

BerryBlender_EventScript_StartBlender2: @ 8293DAA
	msgbox BerryBlender_Text_LetsBerryBlender2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending2: @ 8293DB8
	msgbox BerryBlender_Text_ExplainBerryBlending2, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender2
	end

BerryBlender_EventScript_TryUseBerryBlender2: @ 8293DC6
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender2NoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender2NoCase
	msgbox BerryBlender_Text_Okay, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_UseBerryBlender2
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_Blender2CaseFull
	end

BerryBlender_EventScript_Blender2CaseFull: @ 8293E0A
	msgbox BerryBlender_Text_PokeblockCaseIsFull2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2NoCase: @ 8293E14
	msgbox BerryBlender_Text_DontHavePokeblockCase2, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BerryBlender3:: @ 8293E1E
	lockall
	setvar VAR_0x8008, LOCALID_POKEFAN_F
	setvar NUM_OPPONENTS, 3
	applymovement LOCALID_BOY, Common_Movement_FaceOriginalDirection
	applymovement LOCALID_GIRL, Common_Movement_FaceOriginalDirection
	applymovement VAR_0x8008, BerryBlender_Movement_BlendLeaderWalkInPlace
	waitmovement 0
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryUseBlender3
	goto BerryBlender_EventScript_DeclineBlender3
	end

BerryBlender_EventScript_DeclineBlender3: @ 8293E5A
	msgbox BerryBlender_Text_LeftUsInShock, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoBerries: @ 8293E64
	msgbox BerryBlender_Text_DontHaveAnyBerries3, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_UseBerryBlender3: @ 8293E6E
	msgbox BerryBlender_Text_KnowHowToMakePokeblocks3, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_StartBlender3
	goto BerryBlender_EventScript_ExplainBlending3
	end

BerryBlender_EventScript_StartBlender3: @ 8293E87
	msgbox BerryBlender_Text_LetsBerryBlender3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_ExplainBlending3: @ 8293E95
	msgbox BerryBlender_Text_ExplainBerryBlending3, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_StartBlender3
	end

BerryBlender_EventScript_TryUseBlender3: @ 8293EA3
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender3NoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_Blender3NoCase
	msgbox BerryBlender_Text_OhDear, MSGBOX_DEFAULT
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_UseBerryBlender3
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_Blender3CaseFull
	end

BerryBlender_EventScript_Blender3CaseFull: @ 8293EE7
	msgbox BerryBlender_Text_PokeblockCaseIsFull3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender3NoCase: @ 8293EF1
	msgbox BerryBlender_Text_DontHavePokeblockCase3, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterPresent: @ 8293EFB
	lockall
	setvar NUM_OPPONENTS, 1
	msgbox BerryBlender_Text_SeeMyMasteryInAction, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryBlendWithBlendMaster
	msgbox BerryBlender_Text_TooBusyNowIsee, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterNoBerries: @ 8293F1E
	msgbox BerryBlender_Text_BlendMasterNoBerries, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryBlendWithBlendMaster: @ 8293F28
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_BlendMasterNoCase
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_BlendMasterNoBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_BlendWithBlendMaster
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_BlendMasterCaseFull
	end

BerryBlender_EventScript_BlendWithBlendMaster: @ 8293F64
	msgbox BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks, MSGBOX_YESNO
	compare VAR_RESULT, NO
	call_if_eq BerryBlender_EventScript_BlendMasterExplainBlending
	msgbox BerryBlender_Text_BlendMasterLetsBerryBlender, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoBerryBlending
	end

BerryBlender_EventScript_BlendMasterExplainBlending: @ 8293F85
	msgbox BerryBlender_Text_BlendMasterExplainBerryBlending, MSGBOX_DEFAULT
	return

BerryBlender_EventScript_BlendMasterNoCase: @ 8293F8E
	msgbox BerryBlender_Text_BlendMasterNoPokeblockCase, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_BlendMasterCaseFull: @ 8293F98
	msgbox BerryBlender_Text_BlendMasterPokeblockCaseFull, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_Blender2Man:: @ 8293FA2
	msgbox BerryBlender_Text_SetNewBlenderRecord, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender3PokefanF:: @ 8293FAB
	msgbox BerryBlender_Text_LookGoodAtBlendingJoinUs, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender2Twin:: @ 8293FB4
	msgbox BerryBlender_Text_MakeDeliciousPokeblocks, MSGBOX_NPC
	end

BerryBlender_EventScript_Blender1ExpertM:: @ 8293FBD
	setvar VAR_0x8008, 15
	goto BerryBlender_EventScript_ExpertMCheckGiveBerry
	end

BerryBlender_EventScript_ExpertMCheckGiveBerry: @ 8293FC8
	lock
	faceplayer
	msgbox BerryBlender_Text_LoveMakingPokeblocks, MSGBOX_DEFAULT
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, TRUE
	goto_if_eq BerryBlender_EventScript_ExpertMPlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_ExpertMNoBerries
	end

BerryBlender_EventScript_ExpertMPlayerHasBerries: @ 8293FEE
	msgbox BerryBlender_Text_MakePokeblocksUsingBerryBlender, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMNoBerries: @ 8293FF8
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_ExpertMNoSpareBerries
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_ExpertMNoSpareBerries
	dotimebasedevents
	goto_if_set FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY, BerryBlender_EventScript_ExpertMNoSpareBerries
	goto BerryBlender_EventScript_ExpertMGiveBerry
	end

BerryBlender_EventScript_ExpertMNoSpareBerries: @ 8294028
	msgbox BerryBlender_Text_DontHaveAnyBerriesNoneToSpare, MSGBOX_DEFAULT
	release
	end

BerryBlender_EventScript_ExpertMGiveBerry: @ 8294032
	msgbox BerryBlender_Text_DontHaveAnyBerriesHaveOne, MSGBOX_DEFAULT
	giveitem ITEM_PECHA_BERRY
	setflag FLAG_DAILY_CONTEST_LOBBY_RECEIVED_BERRY
	msgbox BerryBlender_Text_UseItToMakePokeblocksTogether, MSGBOX_DEFAULT
	release
	end

BerryBlender_Movement_BlendLeaderWalkInPlace: @ 8294053
	walk_in_place_fastest_right
	step_end

BerryBlender_EventScript_BerryBlenderLink:: @ 8294055
	lockall
	specialvar VAR_RESULT, PlayerHasBerries
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_LinkBlenderNoBerries
	checkitem ITEM_POKEBLOCK_CASE, 1
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_LinkBlenderNoCase
	specialvar VAR_RESULT, GetFirstFreePokeblockSlot
	compare VAR_RESULT, 65535
	goto_if_ne BerryBlender_EventScript_LinkBlenderSaveGame
	compare VAR_RESULT, 65535
	goto_if_eq BerryBlender_EventScript_LinkBlenderCaseFull
	end

BerryBlender_EventScript_LinkBlenderSaveGame: @ 8294092
	msgbox BerryBlender_Text_SaveGameBeforeBerryBlenderLink, MSGBOX_YESNO
	compare VAR_RESULT, YES
	goto_if_eq BerryBlender_EventScript_TryDoLinkBlender
	compare VAR_RESULT, NO
	goto_if_eq BerryBlender_EventScript_CancelLinkBlender
	end

BerryBlender_EventScript_LinkBlenderNoBerries: @ 82940B1
	msgbox BerryBlender_Text_NoBerriesLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_TryDoLinkBlender: @ 82940BB
	call Common_EventScript_SaveGame
	compare VAR_RESULT, FALSE
	goto_if_eq BerryBlender_EventScript_CancelLinkBlender
	specialvar VAR_RESULT, IsWirelessAdapterConnected
	compare VAR_RESULT, TRUE
	goto_if_eq BerryBlender_EventScript_StartDecideLinkLeader
	message BerryBlender_Text_SearchingForFriends
	waitmessage
	special TryBerryBlenderLinkup
	waitstate
	compare VAR_RESULT, LINKUP_SUCCESS
	goto_if_eq BerryBlender_EventScript_SpawnLinkPartners
	compare VAR_RESULT, LINKUP_SOMEONE_NOT_READY
	goto_if_eq BerryBlender_EventScript_CloseLinkNotReady
	compare VAR_RESULT, LINKUP_DIFF_SELECTIONS
	goto_if_eq BerryBlender_EventScript_CloseLinkDifferentSelections
	compare VAR_RESULT, LINKUP_FAILED
	goto_if_eq BerryBlender_EventScript_CloseLink
	compare VAR_RESULT, LINKUP_CONNECTION_ERROR
	goto_if_eq BerryBlender_EventScript_LinkError
	end

BerryBlender_EventScript_TwoPlayerLink: @ 829411D
	msgbox BerryBlender_Text_Player1Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_ThreePlayerLink: @ 829412B
	msgbox BerryBlender_Text_Player1And2Arrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_FourPlayerLink: @ 8294139
	msgbox BerryBlender_Text_AllPlayersArrived, MSGBOX_DEFAULT
	goto BerryBlender_EventScript_DoLinkBerryBlending
	end

BerryBlender_EventScript_DoLinkBerryBlending: @ 8294147
	setvar VAR_0x8004, 0  @ number of opponents, 0 indicates Link
	fadescreen FADE_TO_BLACK
	removeobject 240 @ Unclear where these local IDs come from,
	removeobject 239 @ but presumably they'd be the 4 link players
	removeobject 238 
	removeobject 237
	special DoBerryBlending
	waitstate
	releaseall
	end

BerryBlender_EventScript_CancelLinkBlender: @ 8294160
	releaseall
	end

BerryBlender_EventScript_LinkBlenderCaseFull: @ 8294162
	msgbox BerryBlender_Text_PokeblockCaseIsFullLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkBlenderNoCase: @ 829416C
	msgbox BerryBlender_Text_DontHavePokeblockCaseLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkNotReady: @ 8294176
	special CloseLink
	msgbox Text_SomeoneIsNotReadyToLink, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLinkDifferentSelections: @ 8294183
	special CloseLink
	msgbox Text_PlayersMadeDifferentSelections, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_CloseLink: @ 8294190
	special CloseLink
	msgbox gText_PokeblockLinkCanceled, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_LinkError: @ 829419D
	special CloseLink
	msgbox Text_LinkErrorPleaseReset, MSGBOX_DEFAULT
	releaseall
	end

BerryBlender_EventScript_SpawnLinkPartners: @ 82941AA
	fadescreen FADE_TO_BLACK
	specialvar VAR_RESULT, GetLinkPartnerNames
	copyvar VAR_0x8008, VAR_RESULT
	copyvar VAR_0x8004, VAR_0x8008
	special SpawnLinkPartnerObjectEvent
	goto BerryBlender_EventScript_LinkPlayersArrived
	end

BerryBlender_EventScript_LinkPlayersArrived: @ 82941C4
	fadescreen FADE_FROM_BLACK
	switch VAR_0x8008
	case 2, BerryBlender_EventScript_TwoPlayerLink
	case 3, BerryBlender_EventScript_ThreePlayerLink
	case 4, BerryBlender_EventScript_FourPlayerLink
	end

BerryBlender_EventScript_StartDecideLinkLeader: @ 82941ED
	setvar VAR_0x8004, LINK_GROUP_BERRY_BLENDER
	goto BerryBlender_EventScript_DecideLinkLeader
	end

BerryBlender_EventScript_DecideLinkLeader: @ 82941F8
	message LilycoveCity_ContestLobby_Text_PleaseDecideLinkLeader
	waitmessage
	multichoice 16, 6, MULTI_LINK_LEADER, 0
	switch VAR_RESULT
	case 0, BerryBlender_EventScript_TryJoinGroup
	case 1, BerryBlender_EventScript_TryLeadGroup
	case 2, BerryBlender_EventScript_CloseLink
	case MULTI_B_PRESSED, BerryBlender_EventScript_CloseLink
	end

BerryBlender_EventScript_TryLeadGroup: @ 8294235
	call BerryBlender_EventScript_TryBecomeLinkLeader
	compare VAR_RESULT, LINKUP_SUCCESS
	goto_if_eq BerryBlender_EventScript_LinkLeaderDecided
	compare VAR_RESULT, LINKUP_FAILED
	goto_if_eq BerryBlender_EventScript_DecideLinkLeader
	compare VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN
	goto_if_eq BerryBlender_EventScript_TryLeadGroup
	release
	end

BerryBlender_EventScript_TryJoinGroup: @ 829425D
	call BerryBlender_EventScript_TryJoinLinkGroup
	compare VAR_RESULT, LINKUP_SUCCESS
	goto_if_eq BerryBlender_EventScript_LinkLeaderDecided
	compare VAR_RESULT, LINKUP_FAILED
	goto_if_eq BerryBlender_EventScript_DecideLinkLeader
	compare VAR_RESULT, LINKUP_RETRY_ROLE_ASSIGN
	goto_if_eq BerryBlender_EventScript_TryJoinGroup
	release
	end

BerryBlender_EventScript_TryBecomeLinkLeader: @ 8294285
	special TryBecomeLinkLeader
	waitstate
	return

BerryBlender_EventScript_TryJoinLinkGroup: @ 829428A
	special TryJoinLinkGroup
	waitstate
	return

BerryBlender_EventScript_LinkLeaderDecided: @ 829428F
	goto BerryBlender_EventScript_SpawnLinkPartners
	end
