LilycoveCity_House4_MapScripts:: @ 821F5B4
	.byte 0

LilycoveCity_House4_EventScript_Man1:: @ 821F5B5
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2:: @ 821F5BE
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea: @ 821F5C7
	.string "이 별 최대의 수수께끼!\n"
	.string "그것은 바로\l"
	.string "해저에 있다고 생각한다!\p"
	.string "...라고\n"
	.string "누군가가 말했었지$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis: @ 821F62B
	.string "그러고 보니 이끼시티와\n"
	.string "루네시티 사이에는\l"
	.string "엄청나게 깊고 깊은 해구가 있지\p"
	.string "...라는 말도\n"
	.string "누군가가 했던 말이지$"

