LilycoveCity_House4_MapScripts:: @ 821F5B4
	.byte 0

LilycoveCity_House4_EventScript_Man1:: @ 821F5B5
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2:: @ 821F5BE
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea: @ 821F5C7
	.string "이 별 최대의 수수께끼\n"
	.string "그것은 바로 해저에 있다!\p"
	.string "...라는 말은\n"
	.string "누군가가 했었지$"
	@ この ほしの さいだいの なぞｎ
	@ それは かいていに あると おもうんだ!ｐ
	@ ……というのはｎ
	@ だれかが いってた ことなんだけど

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis: @ 821F62B
	.string "그러고 보니 이끼시티와 루네시티 사이엔\n"
	.string "깊고 깊은 해구가 있다\p"
	.string "...그런 말도\n"
	.string "누군가가 했었지$"
	@ そういや トクサネと ルネの あいだにはｎ
	@ ふかい ふかい かいこうが あるｐ
	@ ……そんな はなしもｎ
	@ だれかが いってた ことなんだけど

